### PR TITLE
[CP 3.9] Fixes #37025 - Navigation should only have 1 item expended

### PR DESCRIPTION
**Pull request by MariaAga**
(cherry picked from commit bf39cd0471e4e9bc1653d152ba25accc85140366)

### CODE REVIEW

**Comment by MariaAga** [comment]
Should I also CP https://github.com/theforeman/foreman/pull/9979 to fix snapshots ?

**Comment by adamruzicka** [comment]
Ideally, yes

**Comment by MariaAga** [comment]
Actually found another bug in this area so moving to draft

**Review by adamruzicka — APPROVED** [review]
lgtm

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
