### PR TITLE
Fixes #26679 - Add report template API attributes

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
LGTM however jenkins needs retrigger. Ping me when green.

**Comment by xprazak2** [comment]
[test foreman]
[test katello]

**Comment by lzap** [comment]
Thanks merged.

**Comment by ares** [comment]
does this need to be cherrypicked to 1.22? setting 1.23 in redmine for now

**Comment by xprazak2** [comment]
There was no target release for this AFAIK, but we cane cherry-pick if someone requests it.

**Comment by ares** [comment]
Please open a cherry-pick to 1.22, it's extremely safe and our BZ asks for that. If you ping me there, I'm happy to merge, unless @tbrisker objects. Given this is the new functionality in 1.22, I think the API should be complete.

**Comment by xprazak2** [comment]
I opened https://github.com/theforeman/foreman/pull/6821

**Pull request merged**
