### PR TITLE
fixes #10965 - limit range width for host#show range select list

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
It still breaks up the sentence for single digit numbers, I'd go with just removing select2 in that field?

**Comment by ohadlevy** [comment]
my guess trend pages have similar problem.

**Comment by ohadlevy** [comment]
is there any way for select2 to respect bootstrap classes?

**Comment by shlomizadok** [comment]
@eLobato, same happens when disabling select2
image

@ohadlevy select2 respects bootstrap classes afaik

**Comment by shlomizadok** [comment]
@eLobato and to verify, I have also tested w/ 1.8-stable:
image
with same result

**Comment by shlomizadok** [comment]
Changed (second commit) the sentence and removed duplicate "reports" word. Now it looks like:
image

**Comment by dLobatog** [comment]
Merged as e939689eb8e00aa6f0d0730ec422ca7216d13707, thanks @shlomizadok!

**Comment by domcleal** [comment]
This doesn't seem to fix the issue for me, and your screenshots above don't seem to show the same issue that I reported.  I think you've fixed something else.

Check the screenshot I attached (http://projects.theforeman.org/attachments/download/1307/Screenshot%20from%202015-07-01%2013_13_12.png), it shows that the select box is the full width of the column and taking up a full line.  I think what you've just done is to reduce the length of the sentence, which doesn't seem to have been the problem for me.

My dev install running e939689, which has the shorter sentence, but the same issue:
screenshot from 2015-07-02 07 57 34

Nightly from yesterday showing the original issue with the original sentence:
screenshot from 2015-07-02 07 57 30

Foreman 1.8.2 showing normal width of a select box:
screenshot from 2015-07-02 07 57 32

I'm not sure why you're not seeing the same width of select box.

Edit: verified under Chrome and Firefox, it's identical

**Comment by shlomizadok** [comment]
Oh, I see why... hehe :)
This PR is made of two commits, only one was merged....
https://github.com/shlomizadok/foreman/commit/da71686b43b7072b62501d7ae93fdd8254c22c92 needs to be merged too

**Comment by ohadlevy** [comment]
@shlomizadok then why not use bootstrap in this case md-2 or similar?

**Comment by domcleal** [comment]
The select already has col-md-1, but it also has form-control explicitly added, while the trends one (which displays fine) doesn't.  It looks like removing the `:class=>"col-md-1 form-control"` from `reports_show` allows it to automatically size itself sensibly.  Thoughts?

**Comment by shlomizadok** [comment]
@domcleal great catch, works perfectly.at https://github.com/shlomizadok/foreman/commit/7e76e343428cc0adc54d0ded0dbd585b2045316c

**Comment by domcleal** [comment]
Merged as bd7c4d2, thanks @shlomizadok.

**Pull request closed without merging**
