### PR TITLE
Fixes #4197: Adds 'plugins' directory to /var/log/foreman, /etc/foreman,...

### PR DESCRIPTION
**Pull request by ehelms**
... and

/usr/share/foreman to allow plugins to install their own log, config and other
files.

### CODE REVIEW

**Comment by lzap** [comment]
Nice, thanks. +1

**Comment by domcleal** [comment]
@ehelms could you check the package build error please?

<pre>
error: Symlink points to BuildRoot: /etc/foreman/plugins -> /builddir/build/BUILDROOT/foreman-1.5.0-0.develop.201401291800git9823412.el6.noarch/usr/share/foreman/config/settings.plugins.d
warning: File listed twice: /usr/share/foreman/config.ru
warning: File listed twice: /usr/share/foreman/config/environment.rb
warning: File listed twice: /usr/share/foreman/plugins
warning: File listed twice: /var/log/foreman/plugins
RPM build errors:
    Symlink points to BuildRoot: /etc/foreman/plugins -> /builddir/build/BUILDROOT/foreman-1.5.0-0.develop.201401291800git9823412.el6.noarch/usr/share/foreman/config/settings.plugins.d
    File listed twice: /usr/share/foreman/config.ru
    File listed twice: /usr/share/foreman/config/environment.rb
    File listed twice: /usr/share/foreman/plugins
    File listed twice: /var/log/foreman/plugins
</pre>

http://koji.katello.org/koji/getfile?taskID=78607&name=build.log

**Comment by ehelms** [comment]
@domcleal copy/paste fail on my part, should be updated now to reflect the other symlinks and pass build.

**Comment by domcleal** [comment]
Thanks.

@GregSutcliffe on [the issue](http://projects.theforeman.org/issues/4197) talks about handling *_/_.yaml in settings.plugins.d loading rather than just *.yaml.

Is your expectation that extensions to SETTINGS get placed at /etc/foreman/plugins/foo/foo.yaml, or /etc/foreman/plugins/foo.yaml also with /etc/foreman/plugins/foo/ for other things?

**Comment by ehelms** [comment]
From our previous discussions, the expectation was that a plugin would supply `/etc/foreman/plugins/foo.yaml` and if they had other system config needs would create and store those in `/etc/foreman/plugins/foo/`. I don't mind updating this if we want to support the case of `/etc/foreman/plugins/foo/foo.yaml` we just didn't discuss that in IRC as an option as I recall.

**Comment by domcleal** [comment]
Indeed, sounds fine to me, just wanted to clarify.  OK Greg?

**Comment by GregSutcliffe** [comment]
We only need to change core if Foreman itself is expected to load stuff from `/etc/foreman/plugins/foo/foo.yaml`. If that's just for the plugin itself to explicitly handle, then no core change should be needed. I'm fine with either, just noting the possible necessary code change :)

**Comment by ehelms** [comment]
Sounds like a matter of deciding the convention, whether as a plugin you either supply:

a) `/etc/foreman/plugins/foo.yaml` - if you only have a settings file
    `/etc/foreman/plugins/foo/foo.yaml` - if you have a settings file and extra config

or

b) `/etc/foreman/plugins/foo.yaml` - no matter what for your settings file
    `/etc/foreman/plugins/foo/<other>` - if you need other

Either convention works for me - what would you guys prefer?

**Comment by GregSutcliffe** [comment]
b) works for me

**Comment by domcleal** [comment]
Yep, let's stick with (b).

I just tried the RPM and was surprised to see the symlink was the other way around to my expectation:

```
lrwxrwxrwx. 1 root root 44 Feb  6 18:50 /etc/foreman/plugins -> /usr/share/foreman/config/settings.plugins.d
```

The other symlinks are _from_ /usr to /etc, so the actual files are stored on /etc (useful for backups etc).  Any chance we can flip it around?  I think the Debian packages were done that way around.

**Comment by GregSutcliffe** [comment]
@domcleal yes, they are.

**Comment by ehelms** [comment]
@domcleal updated

**Comment by domcleal** [comment]
Build failed: http://koji.katello.org/koji/taskinfo?taskID=80528

<pre>
+ ln -sv /builddir/build/BUILDROOT/foreman-1.5.0-0.develop.201402091820gitd7ca0dc.el6.noarch/etc/foreman/plugins /usr/share/foreman/config/settings.plugins.d
ln: creating symbolic link `/usr/share/foreman/config/settings.plugins.d': No such file or directory
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.7EyCDi (%install)
    Bad exit status from /var/tmp/rpm-tmp.7EyCDi (%install)
</pre>

**Comment by ehelms** [comment]
@domcleal updated, in case you beat me to testing it

**Comment by domcleal** [comment]
Merged as 39397a8 for Foreman 1.5.0, thanks @ehelms.

We'll need to update a couple of plugin RPMs too when approaching 1.5, and the upgrade notes (https://github.com/theforeman/theforeman.org/issues/176).

**Pull request closed without merging**
