### PR TITLE
fixing non admin host create error

### PR DESCRIPTION
**Pull request by avi3tal**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Would you mind expanding on the issue here please?  Preferably if you can file a Redmine ticket, we can reference that in the commit and give more background.

This rings a slight bell on an old SCL installation, but I didn't think it was a problem any more.  I'd probably need to see more info, like the stacktrace, RPMs and features (taxonomies?) in use to tell what the cause is.

**Comment by avi3tal** [comment]
No problem, I will reproduce and file a ticket, anyways this is similar
issue to an old taxonomy....  Failure.

**Comment by domcleal** [comment]
Seems that @tbrisker was looking at the same, and has filed http://projects.theforeman.org/issues/11220 - so you can amend your commit to use that ticket number, assuming it's the same issue.

**Comment by tbrisker** [comment]
I have reproduced the bug and confirmed the fix works. 
@domcleal - It seems @avi3tal is unresponsive in modifying the commit message, I suggest amending the message on merge.

**Comment by domcleal** [comment]
Merged as 4ca9215, thanks @avi3tal and @tbrisker.

**Pull request closed without merging**
