### PR TITLE
Fixes #7840 - Show correct values for smart variables on host edit page

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test] random katello failure

**Comment by dLobatog** [comment]
@tbrisker Sorry, I can't reproduce this neither with Smart Variables nor with Class Parameters. I set them to be overridden for an specific fqdn, then when I go to the host, I click on the Parameters tab, and check the value of the parameters, and it's the overridden value for both of them. This is in the current develop branch. 

Would you mind to check back and see if this is fixed in develop or am I testing it wrong?

**Comment by tbrisker** [comment]
@eLobato This happens when the override matcher is anything other then fqdn. Try adding a matcher for the domain.

**Comment by domcleal** [comment]
Merged as 33eca4d, thanks @tbrisker.

**Pull request closed without merging**
