### PR TITLE
Fixes #25075: fix provisioning template preview

### PR DESCRIPTION
**Pull request by leewaa**
This fixes a bug which was introduced in https://github.com/theforeman/foreman/pull/6009 a bug that caused the review functionality to stop working.

Also the tests have been fixed so that they guard against future failures as they were previously not covering it properly.

### CODE REVIEW

**Comment by leewaa** [comment]
@lzap care to take a look ?

**Comment by lzap** [comment]
Sure, but how do I reproduce? Tried Host detail - Preview - works. Tried Edit template - Preview button - works fine. All work fine :-)

**Comment by ares** [comment]
weird, I was 100% able to reproduce from host detail page, I might take a look later

**Comment by leewaa** [comment]
I could reproduce it in my local instance running on the develop branch. As I mentioned, the existing controller tests were not testing it either.

**Comment by lzap** [comment]
Nah. Works for me!

@leewaa time to do SHA checkup. I am on cbfa3f4b221c5b4bbe1ec8cff505e933781797b9 at the moment.

Also put down full reproducing steps, maybe I am doing it wrong.

**Comment by leewaa** [comment]
Well, I have basically a fresh db, with the forgeries seeded and configured some templates (I have specifically iPXE templates configured) for the os that my forgeries are using.

Then:
1. Navigate to a host show view. 
2. Click on templates tab.
3. Click on the actions drop down for a template.
4. Click on Review.
5. Witness crash :)

**Comment by leewaa** [comment]
Also might I just add, look at the code itself. As you can see specific tests for the preview functionality will always pass since `build` is true for the host being used. So the code is never reached and a template is returned, change the host's build attribute to false, and the tests fail.

**Review by lzap — APPROVED** [review]
Ok it works for me, could not reproduce it however no regressions in Preview and also Template Edit - Preview mode. @tbrisker I vote for merging this for 1.20 since this was reported as a regression in renderer.

**Review by tbrisker — APPROVED** [review]
Thanks @leewaa !

**Pull request merged**
