### PR TITLE
Fixes #7174 - add delay on autocomplete

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by lzap** [comment]
What a nice one-liner, looks good. Testing.

**Comment by lzap** [comment]
It works fine and I think you hit the decent number 250ms seems to be fine.

Slow typing gives queries approximetly about three characters instead of one, which is 30% better. I could imagine 250 - 400 ms for people who type slower but this is very subjective opinion. I am fine with 250ms.

Anyone else wants to try the feel of it?

**Comment by lzap** [comment]
This is RTM unless someone has different opinion about the delay.

**Comment by domcleal** [comment]
Merged as 233eea0 for Foreman 1.6.0, thanks @tbrisker.

**Pull request closed without merging**
