### PR TITLE
Fixes #21776 - Improved fact importing to deal with names

### PR DESCRIPTION
**Pull request by ShimShtein**
Now the list of fact names will be calculated beforehand and saved to the database. It will also consider that the name could be added from other thread.

This is the work from https://github.com/theforeman/foreman/pull/4996. It just got a new issue ID.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thanks I have no comments, good work. Can you please share output of all benchmarks just for record purposes? Ideally if you have development setup with postgresql, because sqlite3 numbers were a bit irrelevant the last time. Paste it here and we are good to merge.

**Comment by lzap** [comment]
FYI there are relevant failures on CI.

**Comment by ShimShtein** [comment]
Since unit tests are running in transaction by default, added an option to suppress transaction check in facts importer.

**Comment by ShimShtein** [comment]
Hopefully the tests will be green this time.
Here are the benchmark results:
[before.txt](https://github.com/theforeman/foreman/files/1530593/before.txt)
[after.txt](https://github.com/theforeman/foreman/files/1530594/after.txt)

**Comment by ShimShtein** [comment]
[test foreman]

Test failure unrelated, let's retest.

**Comment by lzap** [comment]
Thanks, LGTM the only thing is Katello tests do fail and it seems relevant. Are you planning to do a PR into Katello? Or is this an issue with the code?

**Comment by lzap** [comment]
Benchmark shows good results on performance, but allocations raised from 99 millions to 145 millions. I'd expect little bit less, but this is acceptable.

**Comment by ShimShtein** [comment]
Fixed tests for both Katello and Discovery.

**Comment by lzap** [comment]
Hmmm I am not sure if the price you are paying for `ensure_no_active_transaction` is really worth it. Is the whole tests breakage just because you want to be sure names are added outside of the transaction, or is there another reason I don't see?

**Comment by ShimShtein** [comment]
> Is the whole tests breakage just because you want to be sure names are added outside of the transaction

Yes, tests are run in transaction by default and the newly added exception is triggered. IMHO it's worth fixing the tests as long as the user will not encounter unexpected behavior down the road. To be more precise - I don't have a problem with running name additions inside a transaction, I do have a problem with fact names added concurrently while I am in a transaction. I think we should guard this place in code explicitly, since we don't know exactly how it will be used in plugins/at a later time.

The reason behind this is that failed `INSERT` statement marks the whole outer transaction as failed, so no more queries will be allowed (not even `SELECT`).

**Comment by lzap** [comment]
Merged, this breaks all plugins which rely on fact importing code, I was able to find: Katello, Discovery (both has PRs) and Foreman Salt: @stbenjam @mmoll @ares to name some commiters. Setting redmine this time!

**Pull request merged**
