### PR TITLE
fixes #4626 - update Facter calls for 2.0 compatibility

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1:

**Comment by domcleal** [comment]
@ares could you review please?

**Comment by ares** [comment]
ACK (+ tested with facter built from git - facter-2.0.1.rc1.550)
by 'review' you also mean merge (CP)? :-)

**Comment by domcleal** [comment]
@ares go for it :)

**Comment by ares** [comment]
merged as 312042b0ddd557fb42f67ba7424020b8dde72da2, thanks @domcleal 

correct? :-)

**Comment by domcleal** [comment]
:fireworks: :tada: :+1:

**Pull request closed without merging**
