### PR TITLE
fixes #13457 - update fog-vsphere to 0.6.0

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by domcleal** [comment]
The existing version spec should be OK, is there a specific reason to require this minimum?  Users will get the latest version available when installing or our packages are built.

**Comment by timogoebel** [comment]
@domcleal : The newer version fixes some issues that might break provisioning in some cases. I think, I do not have to get into details here if it's common practice not to update the version. :-)
That leads me to asking: How is the process for packaging the new version? Should I raise a Redmine?
You can close the PR and underlying issue if you want.

**Comment by domcleal** [comment]
Alright, I'd suggest we close it if that's OK and we'll just treat it as a regular bug update.

For the RPMs, I normally monitor them and update them semi-regularly (got about 12 deps on my queue right now) but I'm always happy to get PRs to the packaging repo ([update instructions](https://github.com/theforeman/foreman-packaging/tree/rpm/develop#howto-update-a-package)), it's quite easy to update a single gem.  For the debs, they'll get it automatically on the next build due to the bundler.d dependency.

Edit: if I don't update it for ages, feel free to ask me or raise a Redmine.

**Comment by timogoebel** [comment]
All right, thank's a lot @domcleal!
I agree, updating a single gem should be easy. I actually had some problems with git-annex in our restrictive corporate network, when I looked into it briefly. If I find some some time, I will take a closer look.

**Pull request closed without merging**
