### PR TITLE
Fixes #24969 - Further sort smart class parameter overrides by value

### PR DESCRIPTION
**Pull request by jcpunk**
I believe this should clean up a minor UI annoyance and provide some further level of predictability in the display.

### CODE REVIEW

**Comment by xprazak2** [comment]
Before:



After:



The overrides are now sorted by the overriding value, notice the overrides for fqdn. Do you want them to be sorted by value? The issue description mentions they should be sorted by the match value, in that case you need `val.match` instead of `val.value` and the result will be:

**Comment by jcpunk** [comment]
whoops, good catch!

Fixed

**Comment by jcpunk** [comment]
I updated the test a bit further to also include the values to avoid the typo I made earlier.

**Review by xprazak2 — APPROVED** [review]
:+1:

**Pull request merged**
