### PR TITLE
Fixes #22601 - Update Rails to 5.1.6

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
blocked on having a bullet release with https://github.com/flyerhzm/bullet/pull/388

**Comment by ekohl** [comment]
Should this also be applied to 1.17 when it's merged? This is mostly relevant for the packaging SCL

**Comment by mmoll** [comment]
The packaging would need to get updated before (or very shortly after) this will get merged anyway. Then we can check if it's cherry-pickable to 1.17 without further changes.

**Comment by ekohl** [comment]
The challenge is that we have the SCL as an external repository that's currently shared between 1.17 and nightly.

**Comment by mmoll** [comment]
I see... Would be OK to just update to 5.1.5 now? The 5.1.4 RPMs would stay in the repository and as the foreman RPMs depend on `rails =5.1.4`, everything should be fine? (Question mark, because I'm just blindly assuming).

**Comment by mmoll** [comment]
all 💚

**Comment by mmoll** [comment]
💚 also with 1.17. So it would be just about the RPM packging.

**Comment by ekohl** [comment]
To me it's fine and since we're only at RC1 it should be fine to update it.

**Comment by ehelms** [comment]
I honestly dont know if Copr keeps around old versions of built packages or follows an only latest model similar to Koji. I can't find any documentation one way or the other. We'd have to test that.

One thing to note is we do have a two repository system -- a staging repo and a release repository. So we can pre-build 5.1.5 into staging, test if both versions are present, and hold it there till we want to "promote" it to the release repository. This will also give me a chance to test moving tfm-ror51-packaging to Obal.

**Comment by mmoll** [comment]
@ehelms that sounds fine, there is no need to rush here. :)

**Review by tbrisker — DISMISSED** [review]
Ack on the foreman side, once packing side is also handled can be merged.
@theforeman/packaging - please let us know/merge once packaging is updated.

**Comment by tbrisker** [comment]
Lets have the discussion on whether or not we can update to SCL in time for 1.17 in GH-5256, and merge this for develop so that 1.18 gets this or newer. 
Needs an ack from packaging to merge since this touches the Gemfile.

**Comment by mmoll** [comment]
test failure unrelated :green_heart:

**Comment by ehelms** [comment]
I've updated our Rails staging SCL 5.1.6 -- https://copr.fedorainfracloud.org/coprs/g/theforeman/tfm-ror51-staging/

**Comment by xprazak2** [comment]
What is the status here? Can we get this in now that the SCL is built?

**Comment by mmoll** [comment]
Core- and DEB-wise yes, @ehelms @ekohl, what about the RPM side? :point_up:

**Comment by ekohl** [comment]
All the RPMs were merged to staging. https://github.com/theforeman/foreman-packaging/pull/2377 was opened to point 1.17 to 5.1.4. Once that's merged and released I think we can merge 5.1.6 to develop. Those with old repo files might still pull in 5.1.6 though if they just do a `yum update` instead of `yum update foreman-release && yum update`.

**Comment by mmoll** [comment]
re-opened for testing against 1.17-stable then: GH-5423

**Comment by ares** [comment]
Wasn't there a discussion on discourse where people didn't want to risk 5.1.6 in 1.17? https://community.theforeman.org/t/1-17-rc2-and-scl-update/8487/10

**Comment by xprazak2** [comment]
But this is opened against develop, 1.18 should actually have the newer version...

**Comment by mmoll** [comment]
I think there's a typo in @ekohl's comment, 1.17 will stay on 5.1.4: https://github.com/theforeman/foreman-packaging/pull/2377

**Comment by ekohl** [comment]
@mmoll is right, I've modified my comment to say 5.1.6 -> develop, not 1.17.

**Comment by mmoll** [comment]
@ekohl could you ACK this from the @theforeman/packaging side then? :)

**Comment by ekohl** [comment]
@mmoll IMHO only when https://github.com/theforeman/foreman-packaging/pull/2377 has been merged and rails 5.1.6 has been promoted to tfm-ror51 (currently it's just in tfm-ror51-staging). @ehelms has been leading the effort so I'll leave it to him to ack this.

**Comment by ares** [comment]
Ok, sorry I replied from phone so I haven't seen the update I guess :-) Of course :+1: for 5.1.6 in develop :-)

**Comment by mmoll** [comment]
@ehelms @ekohl what's the status here?

**Review by ehelms — APPROVED** [review]

**Comment by mmoll** [comment]
test failures unrelated :green_heart:

**Comment by ehelms** [comment]
@mmoll This packaging PR switches RPM nightly to 5.1.6 -- https://github.com/theforeman/foreman-packaging/pull/2556

**Comment by ehelms** [comment]
Thanks @mmoll !

**Pull request merged**
