### PR TITLE
Fixes #27354 - resort the package-json fields

### PR DESCRIPTION
**Pull request by sharvit**
The fields in the package.json are sorted in an annoying way so you need to scroll down to the relevant information.
I would prefer the most relevant fields to be on top.

### CODE REVIEW

**Comment by ohadlevy** [comment]
in general +1, however how do you enforce it going forward?

**Comment by sharvit** [comment]
> however how do you enforce it going forward?

I'm not sure what do you mean, I see it as a simple fix and forget, can you explain?

**Comment by ohadlevy** [comment]
On Sun, Jul 21, 2019 at 11:33 AM Avi Sharvit <notifications@github.com>
wrote:

> however how do you enforce it going forward?
>
> I'm not sure what do you mean, I see it as a simple fix and forget, can
> you explain?
>
next time someone adds something to package.json, what will complain to say
its not sorted?

**Comment by sharvit** [comment]
> next time someone adds something to package.json, what will complain to say it's not sorted?

I guess nothing. I don't think it deserves the effort automating it or adding information about the right sort.
We can update if we see it necessary.

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
