### PR TITLE
fixes #25305 - error when puppetclass cannot be created

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by xprazak2** [comment]
We now get a better error message, but it still relies on `ApplicationController` to `rescue_from Exception` in production. Maybe you could return errors from importer when you [uncomment these lines](https://github.com/theforeman/foreman/blob/develop/app/services/puppet_class_importer.rb#L81-L83)? That way we get a redirect with flash, which seems more user-friendly to me.

**Comment by timogoebel** [comment]
@xprazak2: Thanks, will take a look. What do you think should happen if a user has the `import_puppetclass` permission? Should he automatically be allowed to `create_puppetclasses` or should he also need this permission?

**Comment by tbrisker** [comment]
TBH I am not sure the `create_puppetclasses` makes sense? The UI doesn't allow creating them, only the API - but is that useful? My gut feeling is that puppetclasses should always be imported, not created, but I may be wrong

**Comment by timogoebel** [comment]
I think this is quite an edge case.
I can imagine this use case: I only want to allow users to import "role" puppet classes, so I give them input permissions, but only create permissions for `name ~ role::` or similar. WDYT?

**Comment by timogoebel** [comment]
@xprazak2: Changed according to your suggestions.

image

**Comment by xprazak2** [comment]
Works nicely, foreman test errors seem unrelated, waiting for katello.

**Review by xprazak2 — APPROVED** [review]

**Comment by timogoebel** [comment]
Katello also looks unrelated.

**Comment by xprazak2** [comment]
Yes, it looks like it. Merging, thanks!

**Pull request merged**
