### PR TITLE
don't quote CMD in Dockerfile

### PR DESCRIPTION
**Pull request by evgeni**
otherwise it will be interpreted as one command name and not as a
command with parameters

### CODE REVIEW

**Comment by evgeni** [comment]
[test foreman]

**Review by tbrisker — APPROVED** [review]
Thanks @evgeni

**Comment by tbrisker** [comment]
i aborted the tests, we don't actually do any tests on the docker file

**Comment by tbrisker** [comment]
2.0- 0672fa65b

**Comment by ohadlevy** [comment]
@evgeni just wondering, where did the issue surface itself? its likely I never saw it as we override the CMD in both docker-compose and in the kuberenetes configuration..

**Comment by evgeni** [comment]
I've been running it directly with "podman run", as I only needed a foreman, no redis, no postgres.

**Pull request merged**
