### PR TITLE
fixes #14692 - Disable edit user login for own login

### PR DESCRIPTION
**Pull request by gailsteiger**

### CODE REVIEW

**Comment by ohadlevy** [comment]
I'm not too sure this is really true, I would assume a user can rename his account regadless of he is an admin or not.
AFAIR in the past, we assumed the 'admin' user has to be present, so we perform operations using that account (e.g. on background operations) however, since then we've introduce foreman_admin and foreman_anonymous_admin accounts, hence, I'm not 100% if the original limitation is still true.
either way, I don't think this should be enforced for all admin users, maybe just for the 'admin' username if at all.

**Comment by orrabin** [comment]
@ohadlevy this started from a bug that the user can't actually change his login even though it appears to be enabled: http://projects.theforeman.org/issues/14692. This is probably caused by this code: https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/foreman/controller/users_mixin.rb#L24. The discussion on the original bug mentioned that `admin` username is disabled.

There are 2 possibilities in the issue that @gailsteiger opened, we can disable it or enable it for all admins.
Also, it's probably best to either disable it when editing your own user or fix the code that filters out `login`.

**Comment by gailsteiger** [comment]
@ohadlevy we are leaving Bug #14893 open for opinions.
This commit does not allow user to change own login.

**Comment by tbrisker** [comment]
[test]

**Comment by tbrisker** [comment]
[test]

**Comment by ares** [comment]
rubocop is unhappy, could you please fix these two nits?

```
users_controller_test.rb:412, Style/EmptyLines, Priority: Low
Extra blank line detected.

user_test.rb:834, Style/EmptyLinesAroundClassBody, Priority: Low
Extra empty line detected at class body end.
```

**Comment by orrabin** [comment]
[test]

**Comment by dLobatog** [comment]
I've been looking at this one carefully and here's what I think we should get at:
- The login field should be enabled for all users. Except those who use an LDAP authentication source, as that could break their login.
- There should be no special checks for 'admin', as we already have 'foreman_admin' and 'foreman_api_admin' as fallback admin accounts. All references to `user.name == 'admin'` and similar are most likely just leftovers that have to be cleaned up.
- We should lift the limitation and not filter `'login` in this controller so that submitting the form actually changes the field. Right now it's confusing as it won't throw an error but it won't change the login. https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/foreman/controller/users_mixin.rb#L25

cc @gailsteiger @ohadlevy @orrabin does that sound good?

**Comment by orrabin** [comment]
@dLobatog, I agree with the changes you suggested (especially the controller which should change right away)  but there is still one issue of someone else changing the login. I think an admin changing a non admin's login might make sense but how about an admin changing a different admins login? 
Maybe after a user is created, he should be the only one that can change his login?

**Comment by dLobatog** [comment]
I'm not sure, I tend to think an admin should be able to change another admin's login, except for foreman_admin and foreman_api_admin, which they can't change anyway. I don't think that situation (admin changes admin2 login) is that important to warrant adding more code to maintain.

**Comment by gailsteiger** [comment]
I think that Daniel's suggestions make sense. My only concern is that allowing the currently logged in user to change their 'login' might have undesirable side-effects. For instance with the session, permissions , logout or something like that. You are all more familiar with the implementation than I am so what do you think? There is probably no reason that the user shouldn't be able to change their own 'login'. If there are side-effects we could either refactor or log the user out and have them log in again.

**Comment by tbrisker** [comment]
I agree with @dLobatog about allowing changing an admin login; in fact, it is often considered best practice NOT to have a guessable admin username (such as 'admin' or 'root'), so that brute-force attacks are a bit more difficult (since finding the admin username will also require effort). 
It is possible to mitigate any possible side-effects by logging the user out after rename and forcing re-login.

**Pull request closed without merging**
