### PR TITLE
Fixes #38030 - Allow remote execution become any user

### PR DESCRIPTION
**Pull request by vhsantos**
This PR fix the sudoers.d/user_name configuration to allow the user to run playbooks with others users than root, for example:

```ansible
- name: Simple playbook demonstrating become and become_user
  hosts: all

  tasks:
    - name: Create a file as the root user (works well)
      ansible.builtin.file:
        path: /tmp/root_file.txt
        state: touch
      become: true
      become_user: root

    - name: Create a file as a different user (dont works, because the users is other than root)
      ansible.builtin.file:
        path: /tmp/www_data_file.txt
        state: touch
      become: true
      become_user: www-data
   ```

### CODE REVIEW

**Review by adamruzicka — COMMENTED** [review]
I'd be a little wary of changing the long established default for everyone. How about instead of hardcoding it to `root` (or `ALL`), we would set it to a result of something like this
```
host_param('remote_execution_deploy_effective_user') || host_param('remote_execution_effective_user') || 'root'
```

so that the old behaviour stays, but can be overridden by a, possibly global, parameter?

**Comment by ekohl** [comment]
I'm not sure that's a big deal. If you can become root, you can then run things as any user anyway. Security wise I don't think there's a difference.

**Comment by vhsantos** [comment]
Hi @adamruzicka and @ekohl can you reopen this ?
I dont have the privileges to do it !! :-(

**Comment by adamruzicka** [comment]
Yes, sorry about this, this somehow fell through the cracks.

**Comment by adamruzicka** [comment]
Could you please reword the commit message to 'Fixes #38030 - Allow remote execution become any user' to link it to the redmine issue https://projects.theforeman.org/issues/38030 and make the redmine issues check pass ?

**Comment by adamruzicka** [comment]
Sadly, you'll need to reword the commit itself, changing just the title of the pull request isn't enough to make the check happy.

**Comment by vhsantos** [comment]
I hope that is enough now !! :-)

**Review by adamruzicka — APPROVED** [review]
This can't have possibly caused the katello failures, let's get this in.

**Comment by adamruzicka** [comment]
@vhsantos Thank you and congratulations on your first contribution to foreman 🎉

**Pull request merged**
