### PR TITLE
refs #7587 refactor password confirmation

### PR DESCRIPTION
**Pull request by ohadlevy**
- confirmation status is now linked to password field
- extracted additional missing strings
- simplified jquery selectors
- switched to onKeyUp built in event
- hide progress bar by default
- fixed minor css
- handle empty pw/confirmation
- moved javascript/stylesheet into partial instead of new/edit
- moved inline js to onContentLoad event.

### CODE REVIEW

**Comment by ohadlevy** [comment]
probably easier to review with /files?w=1 added to the url

**Comment by ohadlevy** [comment]
[test]

**Comment by dLobatog** [comment]
Works well, merging in 3..2..1..:bomb:

**Comment by dLobatog** [comment]
Merged as 1222f85387f7d9d441d5f973302f798e9f4ceeff , thanks @ohadlevy !

**Pull request closed without merging**
