### PR TITLE
Fixes #37429 - Update theforeman-rubocop to v0.1.2

### PR DESCRIPTION
**Pull request by archanaserver**
for reference: https://github.com/theforeman/theforeman-rubocop/pull/8#issuecomment-1825840790

Updated this after working on series of cops fixes:
- [x] https://github.com/theforeman/foreman/pull/9926
- [x] https://github.com/theforeman/foreman/pull/9977
- [x] https://github.com/theforeman/foreman/pull/10257
  - [x] https://github.com/theforeman/foreman/pull/10051
- [x] https://github.com/theforeman/foreman/pull/10080
  - [x] https://github.com/theforeman/foreman/pull/10063
  - [x] https://github.com/theforeman/foreman/pull/10064
  - [x] https://github.com/theforeman/foreman/pull/10065
  - [x] https://github.com/theforeman/foreman/pull/10258
  - [x] https://github.com/theforeman/foreman/pull/10067
  - [x] https://github.com/theforeman/foreman/pull/10068
  - [x] https://github.com/theforeman/foreman/pull/10071
  - [x] https://github.com/theforeman/foreman/pull/10073
  - [x] https://github.com/theforeman/foreman/pull/10072

### CODE REVIEW

**Comment by ekohl** [comment]
I would start with fixing up the minitest cops and submit those as a PR. That will trim this down, but also work in `develop`.

**Comment by archanaserver** [comment]
@ekohl I was trying to run bundler but throwing this error, I can't continue because I can't understand why it is talking about `foreman-admin` dir here even though i'm in the right one? Would you mind taking a look here?

```

[!] There was an error parsing `Gemfile`: There are no gemspecs at /home/akumari/Desktop/foreman-admin. Bundler cannot continue.

 #  from /home/akumari/Desktop/foreman/Gemfile:56
 #  -------------------------------------------
 #  Dir["#{File.dirname(FOREMAN_GEMFILE)}/bundler.d/*.rb"].each do |bundle|
 >    instance_eval(Bundler.read_file(bundle))
 #  end
 #  -------------------------------------------

```

**Comment by ekohl** [comment]
Check if there's anything in your local bundler files: `grep foreman-admin bundler.d/*`

**Comment by archanaserver** [comment]
> Check if there's anything in your local bundler files: `grep foreman-admin bundler.d/*`

Got it, Thanks!

also @ekohl, how can we handle this Rubocop failed offenses, i can see this is a lot.

**Comment by ekohl** [comment]
> also @ekohl, how can we handle this Rubocop failed offenses, i can see this is a lot.

In my experience it's best to look at them one by one. RuboCop has `--only` to do that. Then there are also cops which change a lot of code, like `Layout`. So I'd first focus on `Minitest/*`

**Comment by stejskalleos** [comment]
@archanaserver can you please rebase over the latest develop?

**Comment by archanaserver** [comment]
@stejskalleos Now this need a long list of RuboCop fix, I have raised PR for Minitest/ and Layout/:
- [ ] https://github.com/theforeman/foreman/pull/9977
- [ ] https://github.com/theforeman/foreman/pull/9982

I posted something related to my Layout/ArgumentAlignment cops fixes issue I'm facing, https://community.theforeman.org/t/rubocop-changes-in-foreman-input-needed/36950

**Comment by archanaserver** [comment]
@ehelms  i have rebased PRs, do you mind looking on those PRs? I'm tracking it here https://github.com/theforeman/foreman/pull/9926#issue-2010230132

**Comment by ehelms** [comment]
I think this PR is stuck until https://github.com/Katello/katello/pull/11009#issuecomment-2362252765 is addressed

**Comment by archanaserver** [comment]
> I think this PR is stuck until [Katello/katello#11009 (comment)](https://github.com/Katello/katello/pull/11009#issuecomment-2362252765) is addressed

Made some changes there, https://github.com/Katello/katello/pull/11009

**Comment by evgeni** [comment]
This now looks mergeable?

@ekohl @ehelms what do you think?

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
@archanaserver Can you try rebasing this to fix the tests?

**Review by ehelms — APPROVED** [review]

**Pull request merged**
