### PR TITLE
fixes #8855 - remove unused oj gem

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dLobatog** [comment]
I'm currently benchmarking what was the performance gain, it's likely that we actually should be using it in production too. In case benchmarks are disappointing we should remove this from foreman-packaging as well.

**Comment by dLobatog** [comment]
More or less running `rake test:api` takes 80s on my setup, tried 5 times with and without `Oj`.

**Comment by dLobatog** [comment]
Good riddance, thanks @domcleal ! Merged as 5a09c3acd49b1efd18b55211eab08141481c10e9 .

Make sure to also remove from foreman-packaging if needed.

**Comment by domcleal** [comment]
Thanks!  We stopped packaging devel/test deps a little while ago as it was too much work, and could restrict us from using good, but unpackaged gems in devel/test setups.

**Pull request closed without merging**
