### PR TITLE
Fixes #10053 - search in logs must be explicit

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by tbrisker** [comment]
@ares please rebase.

**Comment by ares** [comment]
@tbrisker thanks, rebased

**Comment by iNecas** [comment]
:+1: I've seen this issue taking the whole machine down and this change fixing the issue.

**Comment by iNecas** [comment]
Removed the `Needs testing` button. Still leaving space for others to comment on the behavior change. I think it's reasonable to not over-commit in the fulltest search, especially when it's not working properly

**Comment by tbrisker** [comment]
:+1: Merging.

**Comment by tbrisker** [comment]
Merged as 2f1cc0f4b8e8d320e8eef309b1ab7c834b201dce, thanks @ares!

**Pull request closed without merging**
