### PR TITLE
fixes #2202 - add all unassigned actions to appropriate permissions

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ohadlevy** [comment]
<hint>does this includes API requests? </hint>

**Comment by domcleal** [comment]
@ohadlevy no, just the main app.  I'll file another ticket to go through the API permissions, as there are barely any done at the moment.

**Comment by ohadlevy** [comment]
I get an error while running the tests

```
 you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
    app/controllers/application_controller.rb:192:in `expire_session'
    app/controllers/application_controller.rb:181:in `session_expiry'
    app/controllers/unattended_controller.rb:20:in `send'
    app/controllers/unattended_controller.rb:20:in `_callback_before_4635'
    app/controllers/unattended_controller.rb:20:in `each'
    app/controllers/unattended_controller.rb:20:in `_callback_before_4635'
    lib/foreman/thread_session.rb:31:in `clear_thread'
    test/functional/unattended_controller_test.rb:55:in `test_should_render_spoof_when_user_is_not_logged_in'
```

**Comment by domcleal** [comment]
Sorry, I should have caught that.  I've updated the branch with a fix, so it lets Rails evaluates filters rather than trying to do it ourselves.

**Comment by ohadlevy** [comment]
merged - thanks

**Pull request closed without merging**
