### PR TITLE
Fixes #36571 - Remove dividers between navigation items

### PR DESCRIPTION
**Pull request by MariaAga**
before:
 
image
after:
 
image

### CODE REVIEW

**Comment by adamruzicka** [comment]
Should there be dividers between second level items and second level expandable items?

**Comment by MariaAga** [comment]
Yeah, also Maria S approved it here: https://community.theforeman.org/t/rfc-navigation-once-again/33065/23

**Comment by adamruzicka** [comment]
Very well then, LGTM

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
