### PR TITLE
Fixes #23142,#23503 - telemetry improvements (1.18)

### PR DESCRIPTION
**Pull request by lzap**
Safe improvements, better UX.

(cherry picked from commit c030096e0de5a026ec446069ecce188b57150667)

Thanks @mmoll

### CODE REVIEW

**Review by mmoll — APPROVED** [review]
APJ

**Comment by ares** [comment]
both foreman and katello failures seems to be unrelated

foreman failed on 2 combinations only
katello: `<class:HostCollectionTest>': undefined method `test_attributes' for Katello::HostCollectionTest:Class (NoMethodError)`

I'm not sure if this even runs on correct 1.18 codebase, if so, do we need to retrigger or are we good to merge?

**Review by mmoll — APPROVED** [review]
I think we're good.

**Review by xprazak2 — APPROVED** [review]
Merging, thanks!

**Pull request merged**
