### PR TITLE
fixes #2658 - apipie requirement bumped

### PR DESCRIPTION
**Pull request by lzap**
SSIA

The package was tagged: http://koji.katello.org/koji/buildinfo?buildID=4650

Repos masned. We should wait until it gets mirrored.

### CODE REVIEW

**Comment by lzap** [comment]
Ok changed to .22:

http://koji.katello.org/koji/taskinfo?taskID=39316
http://koji.katello.org/koji/taskinfo?taskID=39317

Repos are being generated right now.

**Comment by domcleal** [comment]
Could you bump the Gemfile version to match?

**Comment by lzap** [comment]
Done!

On Wed, Jun 12, 2013 at 08:28:19AM -0700, Dominic Cleal wrote:

> Could you bump the bundler.d version to match?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman/pull/715#issuecomment-19333596

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Merged as a39c00f.  Thanks @iNecas and @lzap!

**Pull request closed without merging**
