### PR TITLE
Fixes #25225 - clone oVirt disk only when source disk exists

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ohadlevy** [comment]
LGTM, but in which cases the source disk doesn't exists in a template? is it on another cluster or something like that?

**Comment by iNecas** [comment]
It's just as simple as adding more disk on top of what's defined in the template (so you can have empty template, and adding additional disks)

**Comment by iNecas** [comment]
FYI I got a confirmation from the users that this patch is fixing the issue for them. Quick merge appreciated.

**Comment by tbrisker** [comment]
@shiramax you did some work around this area recently, can you please review?

**Comment by shiramax** [comment]
@tbrisker I'm reviewing it at the moment,
right now I was able to reproduce the issue in the client environment, and also I can confirm that the workaround is working there.

But, I was unable to reproduce it on my setup, 
Not even when adding thair oVirt setup as compute resource in my setup.

**Comment by shiramax** [comment]
@tbrisker finally I was able to reproduce it on my setup, I can confirm the patch is working :)
 thanks @iNecas

**Review by tbrisker — APPROVED** [review]
Thanks @iNecas and @shiramax !

**Comment by tbrisker** [comment]
cherry-picked to 1.20 as f80e8fbb0

**Pull request merged**
