### PR TITLE
Fixes #12371 - Initialize select2 on virtual machine tab for new hosts

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
failed random katello [test]...

**Comment by dLobatog** [comment]
It looks like VCR is not loading on Katello and it's happening on other PRs. I'll set to Ready to merge and wait until tests are fixed.

**Comment by dLobatog** [comment]
[test] - https://github.com/Katello/katello/pull/5561 was merged to fix the VCR errors

**Comment by dLobatog** [comment]
Merged as 209260a19650f47bc2e9b0219e659c8bed1cf5ce, thanks @tbrisker!

**Comment by dLobatog** [comment]
ce59b5085c2def042cf302a9d1c413063ca19d67

**Pull request closed without merging**
