### PR TITLE
refs #18232 - make phantomjs optional, not available on all archs

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
Requires re-enabling installation of optional dependencies via https://github.com/theforeman/foreman-infra/pull/274.

**Comment by mmoll** [comment]
[test foreman] after theforeman/foreman-infra#274 is merged.

**Comment by mmoll** [comment]
Fixes `npm install` on Linux/aarch64, the test failures seem unrelated to me.

**Review by mmoll — APPROVED** [review]

**Comment by domcleal** [comment]
> the test failures seem unrelated to me.

Yes, they're unrelated - introduced by 2d9236b, fixed in #4236.

**Comment by dLobatog** [comment]
Thanks @domcleal & @mmoll !

**Pull request merged**
