### PR TITLE
Fixes #22938 refactor key pair removal on CR deletion test

### PR DESCRIPTION
**Pull request by mmoll**
It fails on Rails 5.2 otherwise

### CODE REVIEW

**Comment by mmoll** [comment]
taken from GH-5836

**Comment by iNecas** [comment]
Test failures seem independent, but just in case [test foreman]

**Comment by mmoll** [comment]
:green_heart:

**Review by iNecas — APPROVED** [review]

**Comment by iNecas** [comment]
Thanks @mmoll and @ik5

**Pull request merged**
