### PR TITLE
Refs #34526 - Update Rails to 6.1.6

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/7744 updates Rails to 6.1.6, but we don't allow that version (yet)…

**Comment by adamruzicka** [comment]
Makes sense, APT

**Comment by adamruzicka** [comment]
The deprecation related test failures should be fixed by this https://github.com/Dynflow/dynflow/pull/413 . Alternatively, we could change `ActiveSupport::Deprecation::Behavior` to not raise on deprecation warnings in tests

**Comment by evgeni** [comment]
> The deprecation related test failures should be fixed by this [Dynflow/dynflow#413](https://github.com/Dynflow/dynflow/pull/413) . Alternatively, we could change `ActiveSupport::Deprecation::Behavior` to not raise on deprecation warnings in tests

I'd prefer fixing things :)

**Comment by adamruzicka** [comment]
dynflow-1.6.6 just went out
[test foreman]
[test katello]

**Comment by evgeni** [comment]
[test katello]

**Review by ehelms — APPROVED** [review]

**Pull request merged**
