### PR TITLE
Fixes #12860 - Moves new_child_fields_template to LayoutHelper and connect new child to parent

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by dLobatog** [comment]
@orrabin Sorry, could you provide a bit more context? I didn't understand what the snippet @tbrisker put in [12860](http://projects.theforeman.org/issues/12860) was for.

**Comment by orrabin** [comment]
@dLobatog the snippet was to connect a perent id. new_child_fields_template creates an new child without a connection to it's parent. The parent id is only present after saving.
The method is always called from the parent that sends it's own form builder so you have the parent id present if it isn't a new record.
This change connects the parent so you can use it before saving the child.
This refactoring suggestion started as a way to know that a lookup_value should be hidden when creating it (delegating hidden_value? to the parent lookup_key when the value was still a new record).
The problem was that if the parent isn't saved there is no id to connect yet. For hidden_value I needed to find a different solution that also works with new lookup_keys but this change might still be relevant.

**Comment by dLobatog** [comment]
Merged as de78119ce0fe4bf675dadf0c767c56225962de14, thanks @orrabin!

**Comment by dLobatog** [comment]
6bbf50853340ac73ef37209aec8d0f3ef232ff70

**Pull request closed without merging**
