### PR TITLE
fixes #13698 - update rest-client and rbovirt gems

### PR DESCRIPTION
**Pull request by mmoll**
let's see, what the tests will return...

### CODE REVIEW

**Comment by shlomizadok** [comment]
[test] - Not sure Katello unstable is related

**Comment by mmoll** [comment]
it is :rotating_light:

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
_disabled_ - will merge if Katello tests pass

**Comment by domcleal** [comment]
@dLobatog they won't, there's a conflict with rest-client versions that needs fixing.

<pre>
15:05:34 Bundler could not find compatible versions for gem "rest-client":
15:05:34   In Gemfile:
15:05:34     rest-client (~> 1.8.0)
15:05:34 
15:05:34     katello was resolved to 2.5.0, which depends on
15:05:34       rest-client
15:05:34 
15:05:34     katello was resolved to 2.5.0, which depends on
15:05:34       runcible (< 2.0.0, >= 1.6.0) was resolved to 1.6.0, which depends on
15:05:34         rest-client (< 1.8.0, >= 1.6.1)
</pre>

**Comment by mmoll** [comment]
Yes, this has to wait for the two Katello issues to be addressed. One thing to note is that rest-client 1.7.0 enables verify_ssl per default, that might lead to problems in certain setups (and maybe also in that one direct rest-client usage in the ovirt CR?).

**Comment by domcleal** [comment]
> 15:05:34 rest-client (< 1.8.0, >= 1.6.1)

You could try reducing the dependency to >= 1.7.0 and < 2.0.0, which would allow 1.8 or 1.7 to be installed.

Also make sure that the Katello maintainers are aware this needs fixing, @ehelms and @jlsherrill appear to be the gem maintainers.

**Comment by jlsherrill** [comment]
Katello itself doesn't depend on it as far as i could tell, but a gem we use (Runcible) does, i opened a PR here to update it:  https://github.com/Katello/runcible/pull/171

EDIT: I should say katello itself doesn't seem tied to to a particular version

@domcleal looks like this change was introduced in 1.8.0 so i don't think you could support both easily without wrapping in a big if rest_client_version >= 1.8.0

**Comment by jlsherrill** [comment]
@mmoll we released a new version of runcible that supports both the old and new version of rest client, so if you want to rebase against develop, the katello tests should pass (unless there some other breakage we've missed).

**Comment by mmoll** [comment]
@jlsherrill thanks! :)

**Comment by mmoll** [comment]
rebased, now tests are green :green_heart:

**Comment by jlsherrill** [comment]
When doing some further testing, it appears the version of rbovirt that foreman is locked to isn't compatible with rest-client 1.8:

https://github.com/abenari/rbovirt/blob/v0.0.37/lib/restclient_ext/request.rb

This breaks us in a few places where we use client side ssl certs (and rbovirt isn't properly looking for them in the new request class).   It looks like this is resolved in 0.1.0.  Is foreman able to move to that?

This should break foreman's use of client side certs as well (assuming it is using rest client with those)

**Comment by mmoll** [comment]
I guess the rbovirt update "simply" also has to go into this PR then?

**Comment by mmoll** [comment]
@lzap @iNecas related: could you cut a new 0.1.x release of rbovirt?

**Comment by lzap** [comment]
@mmoll what exactly do you mean? I don't know exactly why we are pinned to 0.0.x series, @ohadlevy @domcleal ?

**Comment by domcleal** [comment]
The history of bundler.d/ovirt.rb explains.  http://projects.theforeman.org/issues/8527 pinned it because rbovirt was incompatible with rest-client 1.7. This has been rectified with 0.1.x, so it can all be unpinned.

I expect @mmoll was simply asking for a new 0.1.x release of rbovirt because you've only been releasing from the 0.0.x branch of rbovirt, so a move to 0.1.x would cause regressions.

**Comment by mmoll** [comment]
Exactly, there have been rbovirt 0.0.x releases lately with fixes needed by Foreman, but no recent 0.1.x release and and looks like we have to move rbovirt and rest-client together to a recent version.

**Comment by lzap** [comment]
https://rubygems.org/gems/rbovirt/versions/0.1.1

https://github.com/abenari/rbovirt/blob/master/CHANGES.rdoc#011

**Comment by mmoll** [comment]
Tests seem still to be green, so if anybody could test this with oVirt (especially that one call that does fetch the certificate) and with Proxies that use SSL but have certificate verification disabled, that would be nice...

**Comment by mmoll** [comment]
rebased.

**Comment by domcleal** [comment]
Merged as 7635745, thanks @mmoll.

**Pull request closed without merging**
