### PR TITLE
Fixes #30047 - fix Value boxes size to fit content

### PR DESCRIPTION
**Pull request by adiabramovitch**
…ll fit the table

### CODE REVIEW

**Review by tbrisker — CHANGES_REQUESTED** [review]
Change itself is good and fixes the issue, please update the commit message to match our guidelines (see https://theforeman.org/handbook.html#Commitmessages and https://chris.beams.io/posts/git-commit/ for details)

**Comment by adiabramovitch** [comment]
> Change itself is good and fixes the issue, please update the commit message to match our guidelines (see https://theforeman.org/handbook.html#Commitmessages and https://chris.beams.io/posts/git-commit/ for details)
@tbrisker 
Thank you

**Review by tbrisker — APPROVED** [review]
Thanks @adiabramovitch !

**Comment by ezr-ondrej** [comment]
This was a bad merge IMHO, this should only be fixed in a plugin, if we are serious about removing puppet from core.
Or at least opened against both. But doesnt make much sense to improve Puppet code now.

**Pull request merged**
