### PR TITLE
fixes #6860 - add missing attributes to hostgroup jail

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by dmitri-d** [comment]
lgtm.

**Comment by stbenjam** [comment]
[test]

**Comment by domcleal** [comment]
It also seems to be missing :os (an alias), :arch (a missing alias, might be useful to add), domain, subnet and realm (compared to Host::Managed).  Would you mind adding those too?

**Comment by domcleal** [comment]
Thanks @stbenjam, merged as 1cb5ba7 for Foreman 1.6.0-RC2.

**Pull request closed without merging**
