### PR TITLE
Fixes #31070 - update the macro documentation

### PR DESCRIPTION
**Pull request by ares**
the replacement of https://github.com/theforeman/foreman/pull/8074 with incorporated suggestion

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Tests are still running, but :+1:

**Review by ofedoren — APPROVED** [review]
Thanks, @ares. Tests are green except one which tests commit count, weird..

**Comment by ares** [comment]
it may have cached the branch which was force pushed? I guess we can ignore it

**Comment by ekohl** [comment]
I suspect you didn't update your develop branch when you pushed and it's safe to ignore.

**Comment by ofedoren** [comment]
Makes sense, merging then, thanks all again :)

**Pull request merged**
