### PR TITLE
fixes #9335 - adds toggle to puppet classes list & better ui

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by isratrade** [comment]
@shlomizadok, looks good, but another UI improvement would to remove the puppet group from "Available Classes" rather than showing a + sign with no children. A user needs to click on a module name to find out that there are no children, meaning they're already selected.
I'm ok which merging as is and making a new Redmine issue.

**Comment by isratrade** [comment]
If there is another ACK, then I'll merge.

**Comment by isratrade** [comment]
@shlomizadok, or another option instead of removing the puppet group is to remote the +/- sign since it's meaningless.

**Comment by shlomizadok** [comment]
Removed the +/- signs if a puppetgroup is empty.

**Comment by shlomizadok** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as ded38d14feb05301ae4542649ad951ac765258e4, thanks @shlomizadok

**Pull request closed without merging**
