### PR TITLE
refs #8747 - undo pinning google_api_client gem

### PR DESCRIPTION
**Pull request by stbenjam**
Reminder for when https://github.com/google/google-api-ruby-client/issues/183 is resolved

### CODE REVIEW

**Comment by shlomizadok** [comment]
@stbenjam google-api-client pushed a fixed version, 0.8.1.
can you please edit your pr to:

``` ruby
gem 'google-api-client', '0.8.1', :require => 'google/api_client'
```

And I suggest to pin it for the time being so we won't have surprises from that gem.

**Comment by stbenjam** [comment]
@shlomizadok Updated, but do we really need to pin to 0.8.1? It was only broken very briefly :)

**Comment by shlomizadok** [comment]
@stbenjam , I'd rather will be cautious if it broke our code.
@domcleal, comments?

**Comment by dLobatog** [comment]
`~> 0.8.1` should be safe enough in my opinion.

**Comment by shlomizadok** [comment]
:+1:

**Comment by domcleal** [comment]
Please just revert it to what it was...

**Comment by stbenjam** [comment]
@domcleal It was `~> 0.7`, which isn't going to work as the fix is now in 0.8.x.  

How about `~> 0.8`?

**Comment by domcleal** [comment]
`~> 0.7` is fine...

**Comment by stbenjam** [comment]
_sigh_ I **hate** that operator. Reverted.

**Comment by domcleal** [comment]
:+1:

**Comment by domcleal** [comment]
Merged as ca27745, thanks @stbenjam.

**Pull request closed without merging**
