### PR TITLE
Fixes #7392 Buttons on the top of the Host Edit page had no button class.

### PR DESCRIPTION
**Pull request by knowncitizen**

### CODE REVIEW

**Comment by komidore64** [comment]
[test]

**Comment by ohadlevy** [comment]
Any idea how this regression was introduced?

**Comment by isratrade** [comment]
@ohadlevy, @knowncitizen, this regression was caused by 6803db16e801fb31fa8014ef43c0a8c42519f777, committed 7 days ago.

It affected `onContentLoad` which runs the code that adds `:class => btn` as part of  `onContentLoad` for `title_action`
https://github.com/theforeman/foreman/blob/develop/app/assets/javascripts/application.js#L48

PR https://github.com/theforeman/foreman/pull/1734 fixes this other and another bug introduced by the same commit

**Comment by isratrade** [comment]
closing this as PR #1734 fixes redmine issue 7392

**Pull request closed without merging**
