### PR TITLE
fixes #3661 - mis-redirection from /hosts/fqdn/edit to /hosts

### PR DESCRIPTION
**Pull request by stbenjam**
Fixing a minor annoyance.

### CODE REVIEW

**Comment by stbenjam** [comment]
Host edit page was missing an integration test...thoughts on it?

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by stbenjam** [comment]
Implementing the edit host integration test is going to be a problem without changing some fixtures.   

The entire IP space of all of the subnets has valid PTR records, and 3/4 domains have wildcard A records...causing this when saving the newly edited host:

```
Failed to save: Conflict DNS A Records my5rename.mydomain.net/69.25.27.173 already exists,
Conflict DNS PTR Records 2.3.4.1/ALyon-651-1-21-1.w2-3.abo.wanadoo.fr already exists
DNS PTR Records 2.3.4.1/ALyon-651-1-21-1.w2-3.abo.wanadoo.fr already exists
```

@domcleal - Should I try to add new fixtures and see what breaks, or do you already know it's probably too fragile?  Any other ideas?

**Edit**: Discovered disable_orchestration.  That should do it...

**Comment by domcleal** [comment]
Merged as 625e5c7bef for Foreman 1.4.0, thanks @stbenjam!

**Pull request closed without merging**
