### PR TITLE
Fixes #11854 - New and Changed Downstream Strings

### PR DESCRIPTION
**Pull request by bkearney**
This PR contains new and modified downstream strings.  A summary of the changes can be found at https://gist.github.com/bkearney/54cce1bf0c6973be2609

### CODE REVIEW

**Comment by dLobatog** [comment]
@bkearney Can you `git rebase HEAD~2` ? There seem to be 2 commits in this PR that do the same thing. Thanks!

**Comment by dLobatog** [comment]
@bkearney I'm a little confused at this PR vs #2731 . Does this include both new strings and changed strings, and the other one only includes new strings? If so, either change this to only include changed strings - or close the other one as it's already included in here.

Sorry if I'm missing something, as far as I can see in the gists (very helpful btw, thanks!) this PR includes the other one.

**Comment by bkearney** [comment]
@eLobato on the two commits, The first refreshes teh strings from transifex. The second pulls in the downstream strings. I am happy to squash them once reviewed. The goal here was to show you both steps.

**Comment by bkearney** [comment]
@eLobato We can use this PR or https://github.com/theforeman/foreman/pull/2731. We do not need both. I would prefer this one because it brings in new translations AND changed translation from downstream. The other PR only pulls in the new translations. Consider that one a backup.

**Comment by bkearney** [comment]
@eLobato I have rebased the code off of develop.
@claer this contains your feedback.

**Comment by domcleal** [comment]
Reviewed by translators:
- [x] fr
- [ ] it
- [ ] ja
- [ ] ko
- [ ] ru
- [ ] de
- [ ] es
- [ ] pt_BR
- [ ] zh_CN
- [ ] zh_TW

**Pull request closed without merging**
