### PR TITLE
Fixes #15771 - add :token to the values returned by the API

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by domcleal** [comment]
[test] - running our test suite for you.

**Comment by domcleal** [comment]
Thanks for the PR. My only concern is that I don't think the token should be listed if it's expired, it might not be clear to the user that the token is inoperable as the expiry isn't shown anywhere.  Internally the token always stays associated to the host, even when expired, so we can keep track of it, but this means calling .token will show the old value.

It might be best to wrap this in a check that only includes the value when valid:

```
attributes :token, :unless => ->(h) { h.token_expired? }
```

**Comment by domcleal** [comment]
You mentioned on IRC that this renders for you as this:

<pre>
'token' => {
             'id' => 3,
             'value' => 'xxxx',
             'expires' => '2206-07-16T02:24:46.442Z',
             'host_id' => 79
           },
</pre>

Probably because it's an association, though for me it renders as

```
"token": "917371bf-54ac-4a6d-ad2b-53611b85cb6a",
```

Possibly it varies by rabl version if you're not on the latest. I'd suggest using the second format and making it explicit by doing:

```
node(:token, :if => ->(h) { h.token }) { |host| host.token.value }
```

and with the expiry suggestion in the previous comment, I think this might combine them:

```
node(:token, :if => ->(h) { h.token && !h.token_expired? }) { |host| host.token.value }
```

**Comment by ghost** [comment]
Thank you :-)

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Merged as 0b68495, thanks @SkySymbol!

**Pull request closed without merging**
