### PR TITLE
Fixes #22711 - fix uglifyjs-webpack plugin

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by xprazak2** [comment]
[test foreman]

**Comment by mmoll** [comment]
This seems to be incomplete and GH-5289 also doesn't fix it.

**Comment by xprazak2** [comment]
@sharvit, do we need this for 1.17? I mean, there were no js compilation problems for RC1 afaik...

**Comment by sharvit** [comment]
@xprazak2 my main issue is that I'm not sure why this error appearing.

I would say, if 1.17 compiled properly, let's not update it.

@mmoll Did you try to combine https://github.com/theforeman/foreman/pull/5287/commits/5c0a84753a2fb0938cf1e1c77af0c8d378247b6f and https://github.com/theforeman/foreman/pull/5289/commits/37abf0a72b9d8b91725a40eadea6b2aec68747b2 together?

**Comment by mmoll** [comment]
@sharvit yes, see GH-5289 which is on top of what's currently in develop

**Review by dLobatog — APPROVED** [review]
Same fix as in the other branches, thanks @mmoll

**Pull request merged**
