### PR TITLE
Refs #27854 - Only assign valid templates to new taxonomy

### PR DESCRIPTION
**Pull request by tbrisker**
If any default template somehow becomes invalid, new taxonomies cannot
be created.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Looks good, but maybe a good thing to actually write some tests for?

**Review by lzap — APPROVED** [review]
LGTM I am good.

**Comment by lzap** [comment]
Since Ewould waived I no longer want to delay this. If you want to write tests please do Refs commit. Thanks!

**Comment by tbrisker** [comment]
1.21 - a2096ecaa
1.22 - f3d9ec6e4
1.23 - 92ff9222f

**Pull request merged**
