### PR TITLE
Fixes #5568 - Improves performance of trends:clean rake task

### PR DESCRIPTION
**Pull request by jcmcken**
Perform trend counter dupe counting within the database rather than in the Ruby code.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test] <- this will trigger Jenkins to test your code.

**Comment by ohadlevy** [comment]
@ShimShtein please review, IMHO this task should be removed pre 1.9 ? (including the installer to set up the task) as the whole code changed since 1.8 release?

**Comment by ohadlevy** [comment]
might worth merging for 1.8.x if its a significant improvement ?

**Comment by ShimShtein** [comment]
@ohadlevy: The task will become a no-op after the trends move to intervals design (the chances for more than one interval with the same creation date are zero).
In the meantime it sounds like a very good idea - it won't load most of the datapoints into the memory, since most datapoints are already deduplicated.

**Comment by ohadlevy** [comment]
@ShimShtein not sure i follow... 

for the **develop** branch: do we need this rake task? if not we should drop it from here and the installer.
for the **1.8-stable** branch: should we cherry pick this to improve performance? does it worth it?

@jcmcken do you have a chance to try our 1.9 nightly (with the new trends storage redesign) I assume it should make a much bigger impact than this change?

**Comment by ShimShtein** [comment]
@jcmcken: Can you take a look at PR #2126? It changes a way the trends are stored in the DB, instead of storing multiple points, it stores single line with interval in which the value didn't change. That means that for static facts like "memory amount", there will be a single line in the DB instead of two lines per each hour the system was up.
It should solve many performance issues with this table, can you try this new design and see if ti solves your issues?
:exclamation: **Back up your trend_counters table** just to be sure you are not ruining your data!

**Comment by ohadlevy** [comment]
and to be clear too @jcmcken you just a recent nightly, you don't need to include the patch yourself etc.

**Comment by ShimShtein** [comment]
@ohadlevy, After a second thought about the feature:
in **develop**: the task can be removed (issue created)
in **1.8-stable**: I don't have big enough data set to test the performance gain. Anyway `trends:clean` is an async task anyway, I am not sure that cherry picking improvements to background processes is a good idea.

**Comment by domcleal** [comment]
> I am not sure that cherry picking improvements to background processes is a good idea.

Because it's background and shouldn't be a problem, or because of stability concerns?  Our rake trends:clean tasks is notoriously bad right now.

**Comment by ShimShtein** [comment]
@domcleal: Stability concerns. 
I have to add that I don't see how it is less stable than before.

**Comment by domcleal** [comment]
It looks low risk to me, especially with a test, but feedback to the contrary is definitely welcome...

**Comment by domcleal** [comment]
Thanks @jcmcken, this looks good and seems fully equivalent to me.

The next few lines concern me though as another possible source of memory leakage - they load the counters back into memory where they do need de-duping, then delete them one by one, which the exception of the first index.

I wonder if this would replace line 17 onwards in a more efficient manner?

<pre>
object_groups = dupes.each do |attrs, count|
  TrendCounter.where(:trend_id => attrs[0], :created_at => attrs[1]).offset(1).destroy_all
end
</pre>

**Comment by jcmcken** [comment]
Personally, I wouldn't mind getting rid of the task completely. We have lots of trend counters in our environment, with multiple frontend Foreman servers, and I haven't seen that task actually ever find dupes (granted, I haven't really been looking until recently).

If the architecture of the trends is changing (which I didn't realize) and that will remedy the issue, then I think it's really a toss-up for me whether it's worth it. We've already patched our production Foreman servers awhile ago with what I submitted because that task was causing oomkiller to go nuts.

I don't have a great way of testing the nightly against the volume of data available in our prod environment, but just looking at the new implementation, it seems to be an improvement in design. However the new rake task does concern me -- iterating through every value change is going to take an extremely long time to run for anyone who has a lot of historical trend data. It should be fine if you're standing up a new instance, but I'm worried about how long that's going to take to run on our prod database.

**Comment by domcleal** [comment]
Good point, dupes are unusual so that shouldn't be a common code path.

Merged as 040abfa for Foreman 1.8, thanks @jcmcken!

I added your last comment to ticket #10439 so it can be taken into account for 1.9.

**Comment by ohadlevy** [comment]
@jcmcken thanks!

One thing that could help us more, would be having a copy of your trend\* tables, we could then simulate your exact migration scenario.

**Comment by ohadlevy** [comment]
side note, since you mentioned that you run on multiple foreman servers... in the past, dupes could have been created if the exact rake task would be executed on multiple foreman servers.

when migrating to 1.9,  its important to ensure that the db migration  && cron job only runs on one of your servers

**Comment by jcmcken** [comment]
@ohadlevy It's not really possible for me to get that information to you, unfortunately. I think what I might do is just dump the trend counters table, archive the data (maybe offload it somewhere else and run the reduce task), and then prune out everything except for the last 30 days (or whatever). Then I should be able to run that rake task in a reasonable time without affecting performance. I could get you some numbers, though. As a first approximation, we have some trends that have been running continuously for almost 2 years now -- so a lot of counters (in the millions of rows). There are no doubt a lot of duplicated counters (based on the new interval design), but actually chugging through everything would take a bit

Thanks for the tip about the migration. We didn't really have a lot to go on when setting up multiple Foremans w/ separate app/db tiers (e.g. none of the Puppet modules we could find seemed to support that configuration when we initially set the stuff up). Mainly, our need is high availability not performance (I don't think we've ever run into performance issues with Foreman aside from this rake task). It would definitely be useful to have more documentation about best practices for that type of set up though

**Comment by ohadlevy** [comment]
actually @ShimShtein just confirmed that you can run the task while collecting new data points, so that is not relevant to the migration.

**Comment by ShimShtein** [comment]
@jcmcken The best approximation of time I can give you is that for a local DB with ~1-2M records, it took ~10-20 seconds on my laptop. I know it can vary a lot, but it's the best I have.

Also, it would be wonderful if you could dump the trends and trend_counters table and send them to us. I will be glad to work with some real data set.

**Pull request closed without merging**
