### PR TITLE
Fixes #32662 - Respect the visibility when editing an existing bookmark

### PR DESCRIPTION
**Pull request by nbarrientos**

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test
@nbarrientos I've invited you to the foreman organization, once you accept your PRs should auto-trigger CI runs :)

**Comment by nbarrientos** [comment]
Dunno why this MR is tagged as "waiting for contributor" :thinking:

**Comment by tbrisker** [comment]
> Dunno why this MR is tagged as "waiting for contributor" :thinking:

The commit message is too long, if it's over 65 characters it marks it that way (it used to comment about it in the past as well, not sure why it stopped...)

**Review by ofedoren — DISMISSED** [review]
LGTM, tests are green and does what expected.

UPD: Although, the commit message has a typo :)

**Comment by nbarrientos** [comment]
> Although, the commit message has a typo :)

Thanks @ofedoren, it's fixed now.

**Review by tbrisker — APPROVED** [review]
Thanks @nbarrientos and @ofedoren !

**Comment by tbrisker** [comment]
2.5 - ecefdaeaf

**Pull request merged**
