### PR TITLE
fixes #5897 - ordinary users require email, external, hidden and ldap users don't

### PR DESCRIPTION
**Pull request by unorthodoxgeek**

### CODE REVIEW

**Comment by dLobatog** [comment]
I don't think this is a bug, more details in the [redmine issue](http://projects.theforeman.org/issues/5897), looking forward to hear others opinions

**Comment by unorthodoxgeek** [comment]
[test]

**Comment by ares** [comment]
I tend to agree, the bug is that we require admin to enter email on user update, while this PR is making it necessary to set email for internal auth source even during creating. While the flag itself is useful, I think we still want to allow admin saving user without email, so this should be also part of PR.

**Comment by domcleal** [comment]
Indeed, the admin part is the bug.  I don't think that this change helps the situation - changing the behaviour based on the auth source probably isn't a good idea, it should be more consistent between auth sources if anything.

**Comment by dLobatog** [comment]
@unorthodoxgeek Setting this to waiting on contributor - I also think just fixing the 'admin has to set email' bug is enough.

**Comment by unorthodoxgeek** [comment]
@eLobato @domcleal  - you're right, I'm closing this PR.
Will the following solution work: the validation should not run if the user doing the operation is an admin and the user getting updated doesn't have an email?

**Comment by domcleal** [comment]
@unorthodoxgeek yeah, that would solve the bug.  I don't think requiring an e-mail address is a good idea longer term however, but could be changed separately (in which case, separate the redmine issues).

**Pull request closed without merging**
