### PR TITLE
Refs #14102 - Full location and organization passed as YAML to the ENC

### PR DESCRIPTION
**Pull request by edestecd**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
@edestecd I'll change the commit to 'fixes' instead of 'refs', as it's the first commit fixing that ticket. Other than that, :+1: to this - We should mention this in 1.12 release notes @domcleal as it might break stuff

**Comment by domcleal** [comment]
Sure, added to https://github.com/theforeman/theforeman.org/issues/555.

**Comment by dLobatog** [comment]
Merged as c7d9169d12e16bcd5f4e3466e5cf99ca963eeea7 - thanks @edestecd

**Pull request closed without merging**
