### PR TITLE
Fixes #14173 - Puppet Summary Report host listing should be alphabetically sorted.

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by shlomizadok** [comment]
Should they be sorted by created_at date?

**Comment by ranjan** [comment]
It should be sorted by hostname.

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
@ranjan Thanks! Please add a test for this. About the ordering, I think that's highly subjective, I'd prefer them to be ordered by last report - why do you say it should be sorted by hostname?

**Comment by domcleal** [comment]
@dLobatog note that the active list already is sorted by hostname (`@host`/`host_data`)

**Comment by ranjan** [comment]
[test] failure looks unrelated to the change

**Comment by dLobatog** [comment]
Merged as cce67207deb0eb33eecd725cf89ebd6768a5dbc5, thanks @ranjan!

**Pull request closed without merging**
