### PR TITLE
Fixes #30344 - Use pf4 in vertical navigation

### PR DESCRIPTION
**Pull request by MariaAga**
Depends on: ~~https://github.com/theforeman/foreman/pull/7804~~ ~~https://github.com/theforeman/foreman/pull/7778~~ ~~https://github.com/theforeman/foreman/pull/7788~~ https://github.com/theforeman/foreman/pull/7805
Foreman navigation width 250px (Current PR):
Screenshot from 2020-07-30 18-06-54

original PF4 navigation width 290px:
Screenshot from 2020-07-08 13-21-47

### CODE REVIEW

**Comment by ekohl** [comment]
Perhaps you should also post an RFC about this. It feels like a large change and usually we discuss those beforehand. My initial reaction was that it looks bad. Especially the org and location selectors looks very bad. There is no way to distinguish what's what. The navigation also looks like it'll have a lot of additional clicks to see things. The navigation affects everyone so some discussion should happen.

**Comment by MariaAga** [comment]
@ekohl This is a refactor of this PR: https://github.com/theforeman/foreman/pull/7555
About how it looks - thats the new PF4 design, if you have any comments/questions @Rohoover might help with those.
Also we're checking with pf4 about the many clicks to see things to maybe change the hover on main menu item behavior

**Comment by Ron-Lavi** [comment]
ready for a rebase :)

**Comment by MariaAga** [comment]
Rebased

**Comment by Ron-Lavi** [comment]
Can you add the category title for each group? it's really important to have those IMO
Screenshot (80)

**Comment by Ron-Lavi** [comment]
Also on React pages, there is this issue again with the extra margin:
Screenshot (79)

**Comment by MariaAga** [comment]
@laviro About the categories, please see the discussion here:
https://docs.google.com/document/d/1eFbHZjuZC40SYqAn93dOXU0nUf3RnL10Bb8uHIk60w4/edit?usp=drivesdk
I thought it would be better to do it in a separate pr (and forgot to open it🙃)

**Comment by Ron-Lavi** [comment]
> I thought it would be better to do it in a separate pr (and forgot to open it)

as the change won't be that big I think it would be better to add it to this PR, instead of creating a regression.

**Comment by MariaAga** [comment]
opened https://projects.theforeman.org/issues/32147 to address the menu re-org in openSCAP
Removed the extra margin 
Changed the order of the menu items to be more clear now that we don't have sub categories

**Comment by Ron-Lavi** [comment]
needs a rebase :)

**Comment by MariaAga** [comment]
Rebased

**Review by Ron-Lavi — COMMENTED** [review]
Thanks @MariaAga, I would suggest involving the community with this change as it is kinda a major change...
I prefer the current PF3 implementation over the PF4 design, maybe it's suited for smaller menus, but our grows very big, and then scrollbars appear, and not the same sub-categories as there were before, so I would suggest let's get more feedback about it, maybe with the help of @marisvirik?

**Comment by Rohoover** [comment]
> Thanks @MariaAga, I would suggest involving the community with this change as it is kinda a major change...
> I prefer the current PF3 implementation over the PF4 design, maybe it's suited for smaller menus, but our grows very big, and then scrollbars appear, and not the same sub-categories as there were before, so I would suggest let's get more feedback about it, maybe with the help of @MariSvirik?

Hey Ron - I am working with the PF team to identify gaps with the PF4 navigation (some of which you illustrated here)... can you perhaps send me an email with your feedback so I can pass that along?

**Comment by MariaAga** [comment]
Tests are failing because there is an issue with z-index.
The new layout is using `<main` which goes over the ruby pages.
I'm looking into that.

**Comment by Ron-Lavi** [comment]
Thanks @Rohoover, just sent the email :)

**Comment by MariaAga** [comment]
Closing this for now until there is a new nav design. might open a new pr with the new design.

**Comment by Ron-Lavi** [comment]
Thanks for the hard work on this @MariaAga, hope we could reuse some of the code in the new design,
I guess that this example shows us how important is to get feedback early about the design before starting to use it, usually when it's a small component there is less of an issue, but here it has a big impact on everyone that uses the app,

from what I know, Patternfly team is working now on the html & css of the new layout which is more similar in its behaviour to what we have now

**Pull request closed without merging**
