### PR TITLE
Fixes #32148 - Add ansible check mode global parameter

### PR DESCRIPTION
**Pull request by yifatmakias**
Add ansible_roles_check_mode global parameter.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Hi, I believe this should be part of foreman_ansible.

**Comment by yifatmakias** [comment]
> Hi, I believe this should be part of foreman_ansible.

@ezr-ondrej Do you mean the issue in Redmine?

**Comment by ezr-ondrej** [comment]
> Do you mean the issue in Redmine?

No, I mean the PR, but that would mean that the ticket needs to move as well.
I know that creating a new seed file in Ansible just for this parameter is bit annoying.

But creating this for users who don't use ansible is not really good manners :)

**Comment by yifatmakias** [comment]
> > Do you mean the issue in Redmine?
> 
> No, I mean the PR, but that would mean that the ticket needs to move as well.
> I know that creating a new seed file in Ansible just for this parameter is bit annoying.
> 
> But creating this for users who don't use ansible is not really good manners :)

I understand now. I agree, I will do that.

**Comment by yifatmakias** [comment]
I opened an new PR for foreman ansible

**Pull request closed without merging**
