### PR TITLE
Fixes #22489 - move the notification base class

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
This probably fixes http://projects.theforeman.org/issues/22649 in 1.17

**Comment by mmoll** [comment]
Test failures IMHO unrelated.

**Review by tbrisker — APPROVED** [review]
Ack from me, @xprazak2 please confirm before merge since this is in 1.17 branch.

**Comment by xprazak2** [comment]
I haven't tested, but I have no objections since it is meant to fix 1.17 with rex.

**Comment by tbrisker** [comment]
Thanks @mmoll and @xprazak2 !

**Pull request merged**
