### PR TITLE
Fixes #25778 - increase max_old_space_size for webpack:compile

### PR DESCRIPTION
**Pull request by iNecas**
The default value started causing:

    Allocation failed - JavaScript heap out of memory

Increasing max_old_space_size should fix the issue. Unfortunately,
webpack-rails doesn't allow to set params for node. Therefore we to
override the rake task by our own. Take directly from
[webpack-rails](https://github.com/mipearson/webpack-rails/blob/v0.9.11/lib/tasks/webpack.rake)
 (with extension of the node parameter)

After we move away from webpack-rails (probably by
[21203](https://projects.theforeman.org/issues/21203/), we should replace this
workaround by proper solution according to the tool we choose.

### CODE REVIEW

**Comment by iNecas** [comment]
The prove that this PR fixes the issue in plugins is here https://github.com/theforeman/foreman_remote_execution/pull/404 (would fail without it)

**Comment by iNecas** [comment]
Also, I've renamed the `webpack_try_compile.rake` to `webpack.rake`, as it seemed more appropriate after this change.

**Comment by adamruzicka** [comment]
For reference the failing jobs fail like this one https://ci.theforeman.org/job/foreman_remote_execution-pull-request/177/

**Comment by tbrisker** [comment]
Do all of our builders have enough memory for this? cc @theforeman/infrastructure

**Comment by mmoll** [comment]
I'd day yes, as we upgraded RAM a while ago after the "source map in production"-change did lead to failures on smaller slaves.

**Review by tbrisker — APPROVED** [review]
Thanks @iNecas ! By now we're not too far from having all of webpack-rails re-implemented in our codebase..  Would be good to migrate to webpacker, hopefully once @sharvit finishes with reworking how our plugins consume core webpack assets we may be able to do it.

**Pull request merged**
