### PR TITLE
Fixes #26288 - graphql: add User queries

### PR DESCRIPTION
**Pull request by kamils-iRonin**
This patch adds User queries to the GraphQL api.

### CODE REVIEW

**Comment by timogoebel** [comment]
Jenkins tests don't seem to run. Weird.

**Review by timogoebel — DISMISSED** [review]

**Comment by timogoebel** [comment]
[test foreman]
[test upgrade]
[test katello]

**Comment by kamils-iRonin** [comment]
It looks like Jenkins is down

**Comment by kamils-iRonin** [comment]
[test foreman]
[test upgrade]
[test katello]

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @kamils-iRonin.

**Pull request merged**
