### PR TITLE
Fixes #13478 - proxy_request_timeout should be a nonzero setting

### PR DESCRIPTION
**Pull request by daviddavis**
More info about proxy_request_timeout  https://github.com/theforeman/foreman/blob/develop/app/models/setting/general.rb#L25

### CODE REVIEW

**Comment by domcleal** [comment]
While not documented in our description of the setting, it looks like rest-client supports a value of -1 to disable the timeout.  Is it intentional to block this?

**Comment by daviddavis** [comment]
Nope, didn't realize that.

**Comment by domcleal** [comment]
You could still accept -1 and a minimum of 1, excluding zero and more negative numbers by implementing a validate_proxy_request_timeout method on the model if you wished.

**Comment by lzap** [comment]
> You could still accept -1 and a minimum of 1, excluding zero and more negative numbers by implementing a validate_proxy_request_timeout method on the model if you wished.

For the record, we have a "validation framework" to do that. There are
examples in the code base (websockets I think).

## 

Later,
 Lukas #lzap Zapletal

**Pull request closed without merging**
