### PR TITLE
Fixes #35061 - Remove syncing of hostname on save_interface_modal

### PR DESCRIPTION
**Pull request by Pigueiras**

### CODE REVIEW

**Comment by Pigueiras** [comment]
Probably this is not the correct fix because I guess that function `save_interface_modal` has some reason to exist for other use cases, but without it we don't have the issue. I'll try to explain again the bug that I added in Redmine so maybe someone can help to debug the issue:

If I have a node like:

image

And if I try to edit the environment or the hostgroup and press Enter (if I click with the mouse instead of pressing enter it works)

image

It removes the domain and puts the short name as name like:

image

And now if I don't put manually the full fqdn it causes the bad redirection error that I'm describing in the redmine issue (because the node is saved in the db with the fqdn, not the short name).

I'm also using this setting (not sure if it has anything to do with the issue we're having).

image

**Comment by MariaAga** [comment]
Hi, could you check if this pr: https://github.com/theforeman/foreman/pull/9564 (already merged) solves this issue?

**Comment by Pigueiras** [comment]
> Hi, could you check if this pr: #9564 (already merged) solves this issue?

Sorry I missed your question. If I'm not mistaken #9564 will come with 3.5.2, I will test it when it comes out and let you know 👍

**Comment by Pigueiras** [comment]
@MariaAga nope, it's still the same in 3.6.0. I guess we'd need to wait for #9613 😞

**Comment by Pigueiras** [comment]
3.6.2 works for us now! 😄

**Pull request closed without merging**
