### PR TITLE
Refs #23924 - Add react-router to core

### PR DESCRIPTION
**Pull request by tbrisker**
Also expose warning/warning.js explicity since it doesn't seem to be
included in vendor.js otherwise.

### CODE REVIEW

**Comment by tbrisker** [comment]
TBH i'm not too happy about this, but since we'll want it eventually and it may fix the issue for katello, i'm opening this pr

**Review by ohadlevy — APPROVED** [review]

**Comment by timogoebel** [comment]
To be honest, this shows that we're on the wrong track with this. As I mentioned before: When it gets to hard to use tooling to get the job done, you're usually doing something wrong. Using a screwdriver for a nail might work, but a hammer makes more sense.
I'm not going to block this, though. Just stating the obvious.
I know folks are trying very had to get this working and some ingenious engineering effort has been done, but I am pretty certain there is a much easier way to accomplish our goals. There has to be.

**Comment by ohadlevy** [comment]
Timo, you mean the fact that we have to include it for foreman because
Katello needs it? I totally agree with you that's not the right solution.

I only suggested this path simply because we know we need to use
react-router very soon (it would be needed for example for the hw model
page) and since this unblocks releasing 1.18 then I was in favor (e.g.
releasing 1.18 is more important to me at this time and I want to be able
to branch and release 1.19 on time).

Having said that, I'm 100% agreeing we need to get to the bottom of the
issue, like you I'm very uncomfortable with the outcome, and while i fully
appreciate the fact that a lot of people are doing their best to solve
this, the fact that its still an issue deserve a discussion and re
evaluation of the path we are in.

**Comment by timogoebel** [comment]
@ohadlevy: I am 100% with you on this. We can merge this PR if it allows us to branch and release in time. But I believe we should start from scratch after that so that we don't have to do this again. I don't want to nag all the time, but it's important to me that we spend our time doing productive things and do not try to fix stuff we never will.

**Comment by tbrisker** [comment]
@timogoebel I agree this isn't the ideal solution, but I would rather do it and improve the tooling afterwards so we can release 1.18. currently katello 3.7 RCs are broken due to this issue, so once we figure out a solution in nightlies that work we will unblock the 1.18/3.7 release with it (which has already been delayed for very long). 
However @sharvit and I figured why katello is expecting warning and invariant as top level modules, and it's related to packaging (https://github.com/theforeman/foreman-packaging/commit/5ebad8dad6431a86e52b5ad49a32fb7d0c54b25d introduced several modules as top-level modules, leading them to be expected in katello as top level modules under node_modules instead of as nested modules inside react router), so i'm going to close this PR for now and try fixing it there.

**Pull request closed without merging**
