### PR TITLE
Fixes #9453 - better phrasing for tooltip

### PR DESCRIPTION
**Pull request by gilad-chap**
Replacing 'add' with 'remove'.

### CODE REVIEW

**Comment by domcleal** [comment]
Unfortunately, this will only work in English.  Perhaps add a second string in app/helpers/application_helper.rb's add_link_to_function method for the remove tooltip?

We have data-original-title already for the add string, you could add a data-remove-title for the remove version and use that value in the tooltip.

**Comment by domcleal** [comment]
Hi @gilad-chap.  Do you need any help making the change mentioned above?

**Comment by dLobatog** [comment]
@gilad-chap ping? I could submit a separate PR with the changes Dominic requested & this if you don't have the time to update this one. Let us know what you prefer. Thanks!

**Comment by ohadlevy** [comment]
replaced by #2607

**Pull request closed without merging**
