### PR TITLE
Fixes #32051 - Change exit status in iPXE templates

### PR DESCRIPTION
**Pull request by andreamtp**
iPXE in UEFI env need exit with status code to attempt boot from other
device, i.e. netboot -> local disk

ref: https://forum.ipxe.org/showthread.php?tid=10327&pid=16696#pid16696

### CODE REVIEW

**Comment by ofedoren** [comment]
Thanks, @andreamtp! Can you please change the commit name to be something like `Fixes #32051 - Change exit status in iPXE`?

**Comment by andreamtp** [comment]
> Thanks, @andreamtp! Can you please change the commit name to be something like `Fixes #32051 - Change exit status in iPXE`?

Done, thanks for feedback: first contribution :sweat_smile:

**Comment by tbrisker** [comment]
ok to test

**Comment by lzap** [comment]
Are you sure this works in the EFI environment? The last time I checked this the firmware halted. But this will unlikely hurt so I am going to merge anyway, I am just curious.

If you tested this tell me please what kind of hardware is that and if you can share EFI vendor and version.

**Review by lzap — APPROVED** [review]

**Review by tbrisker — APPROVED** [review]
Thanks @andreamtp and congrats on your first contribution!

**Pull request merged**
