### PR TITLE
fixes #8410 - Foreman retrieves 'description' attribute if 'vm_descripti...

### PR DESCRIPTION
**Pull request by IvanovOleg**
...on' is not defined

### CODE REVIEW

**Comment by tbrisker** [comment]
[test]

**Comment by ohadlevy** [comment]
IMHO it is expected for every compute resource plugin to provide such a method, e.g. see https://github.com/theforeman/foreman/blob/develop/app/models/concerns/fog_extensions/ovirt/server.rb#L37

where does your description comes from? is it used by fog?

**Comment by IvanovOleg** [comment]
'description' comes from https://github.com/fog/fog/blob/master/lib/fog/xenserver/models/compute/server.rb, and they said that it's a Foreman issue. You can read about it here: https://github.com/fog/fog/issues/3241#issuecomment-62112824

**Comment by ohadlevy** [comment]
I read it already ;) vm_description is something that we added, so you can
properly define which text (and allowed it to be translated) will be shown
when editing compute profiles.

I have no idea if vm_description and the description in fog is the same or
should be the same.

**Comment by IvanovOleg** [comment]
You cann't save a compute profile and have no opportunity to use xenserver templates for VM creation via Foreman. So to fix it or not is up to you. I have already fix it on my installation and it works well.

**Comment by ohadlevy** [comment]
@IvanovOleg the right solution is to extend the xenserver plugin and add another method implementing vm_description.

thanks.

**Comment by ohadlevy** [comment]
@IvanovOleg by xenserver plugin i meant the foreman xen server at https://github.com/theforeman/foreman-xen rather then fog itself.

**Comment by IvanovOleg** [comment]
Is the foreman-xen responsible for 'vm_description' method? I have not found any 'vm_description' instance in foreman-xen code. So I don't understand why this bug depends on foreman-xen.

**Comment by ohadlevy** [comment]
yes it does, it should extend the fog server object and define it.

see an example, similar to foreman-docker plugin at
https://github.com/theforeman/foreman-docker/blob/master/app/models/concerns/fog_extensions/fogdocker/server.rb#L38

**Comment by IvanovOleg** [comment]
I got it. I will contact foreman-xen developers. Thanks!

**Pull request closed without merging**
