### PR TITLE
Fixes #29429 - Provide rake tasks for Dynflow migrations

### PR DESCRIPTION
**Pull request by adamruzicka**
Historically Dynflow tried to migrate its database on startup. This became an
issue with the move to Puma, because multiple instance of Dynflow running in
separate Puma workers would try to migrate the database concurrently and the
workers would die because of unique key validation errors.

This change adds dynflow:abort_if_pending migrations rake task for checking if
the Dynflow database is fully migrated. It also extends the db:migrate and
db:abort_if_pending_migrations to run their Dynflow counterparts as well.

Requires:
- [x] https://github.com/Dynflow/dynflow/pull/353

### CODE REVIEW

**Comment by ekohl** [comment]
Thanks for this! Looks like that with this implementation there's no need to change anything in the installer, which I like.

Is it a good idea to block starting up dynflow if the DB isn't migrated? This would match regular Foreman which doesn't start if it isn't.

**Comment by ekohl** [comment]
> Is it a good idea to block starting up dynflow if the DB isn't migrated? This would match regular Foreman which doesn't start if it isn't.

Just to be explicit in the PR rather than just on IRC: I don't think this should block this PR and would be OK to tackle later on. In itself this is a good PR and probably already fixes the issues we see.

**Comment by tbrisker** [comment]
> Is it a good idea to block starting up dynflow if the DB isn't migrated? This would match regular Foreman which doesn't start if it isn't.

Foreman does start if the db isn't migrated, but ui is not usable and tells the user they have pending migrations:

https://github.com/theforeman/foreman/blob/2f73d131e7bb3793a2140fd9a36b40c0d4469428/app/controllers/concerns/foreman/controller/migration_checker.rb#L4-L19

Perhaps that should be enhanced as well to check for dynflow migrations?

**Comment by adamruzicka** [comment]
I haven't disabled the automatic migration, I just added an option to do it ahead of time. Dynflow will still try to migrate the db on startup, but it should be a noop when it is already migrated.

Disabling the automatic migration should be fine when running only as a client, but running the executor like this (for example in development where it runs inside the rails process) or when running the console sounds like a bad idea.

I'm not against disabling it, but I think at least the executor should crash hard if the database is not migrated.

**Comment by adamruzicka** [comment]
Dynflow with needed changes was released and I bumped the dependency.

**Comment by mmoll** [comment]
@adamruzicka please rebase to fix the test failures

**Comment by adamruzicka** [comment]
Rebased

**Comment by mmoll** [comment]
RPM PR: https://github.com/theforeman/foreman-packaging/pull/5173

**Review by mmoll — APPROVED** [review]
packaging ACK

**Review by ekohl — APPROVED** [review]
@tbrisker I'd like to get this in before branching since we've seen some provision errors that I think this solves.

**Comment by tbrisker** [comment]
Done. Thanks @adamruzicka and all!

**Pull request merged**
