### PR TITLE
Fixes #26590 - Rename template snippets

### PR DESCRIPTION
**Pull request by mdellweg**
Rename provisioning template snippets to not start with '_' as rails
template partials. This will match better, what we see in
community-templates, and will allow to do a directory comparison via diff.

Script used:
`for i in $(ls *.erb); do mv $i ${i#_}; done`

### CODE REVIEW

**Comment by mdellweg** [comment]
@tbrisker Can you see, why katello tests are marked failed?

**Comment by tbrisker** [comment]
Looks like katello tests timed out for some reason, i'll rerun them [test katello]

**Review by tbrisker — CHANGES_REQUESTED** [review]
Please also update `script/sync_templates.sh` so this doesn't get overriden on the next import

**Comment by mdellweg** [comment]
@tbrisker Sorry, but something went wrong again with the katello unittests...
Updated the script. ;)

**Comment by mdellweg** [comment]
@tbrisker finally found the last occurance of the `_`. I just do not understand why it only failed in the test suite named 'katello'.

**Comment by tbrisker** [comment]
@mdellweg looks like that was just some transient failure, it passed now. I'll merge this after the 1.22 branching.

**Comment by mdellweg** [comment]
@tbrisker Actually i forgot this line
https://github.com/theforeman/foreman/pull/6673/files#diff-e6d89d0a951548fae5e5d88fddee57c1L130
and that got me thinking, why it would not break the foreman tests, but katello ones.

**Review by tbrisker — APPROVED** [review]
Thanks @mdellweg !

**Comment by tbrisker** [comment]
@mdellweg could you please add an upgrade warning to the nightly manual release notes about this? Also please check if this requires any changes in the [foreman_templates](https://github.com/theforeman/foreman_templates) or [foreman_git_templates](https://github.com/dm-drogeriemarkt/foreman_git_templates) plugins - from a quick look it doesn't look like it, but would be good to verify.

**Comment by mdellweg** [comment]
@tbrisker What kind of warning do you mean? I do not think, this change is facing the user, because (apart from the tests) the filenames had no meaning anyway (also where would i add such a thing?).
As for the plugins, i also do not see anything suspicious, but i will try eventually.

**Pull request merged**
