### PR TITLE
Fixes #33920 - drop translations for some languages

### PR DESCRIPTION
**Pull request by tbrisker**
Following the proposal on discourse[1], dropping languages that have
less than 40% translated strings.

[1] https://community.theforeman.org/t/rfc-drop-languages-from-all-repositories-under-theforeman-which-have-poor-translation-rate/25122

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Makes sense to me, thanks @tbrisker! :+1:

**Review by Ron-Lavi — APPROVED** [review]
Translating only 14% from a page / app is probably worse than not translating at all,
thanks @tbrisker 👍🏼

**Review by upadhyeammit — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
What will happen with the apps that has the settings set to these locales and users who has these as defaults?

**Comment by tbrisker** [comment]
@ezr-ondrej great question! I tested it now by setting the setting to one of these languages and my user to one of the other ones. Seems that the user locale gets reset to the browser locale if the language no longer exists, and the setting remains with the previous value but new users are created with browser locale. If you wish I could add a migration to clean these up but it seems keeping these values doesn't break anything as far as i can tell.

**Comment by ezr-ondrej** [comment]
Nah, if nothing breaks I'm good :)

**Comment by tbrisker** [comment]
As a nice side effect, we get a reduction in memory and allocations when loading all locales (which on production happens before forking puma, and on development once we go to the settings or user preferences page for the first time):

before:
```
[1] pry(main)> Benchmark.memory{|x| x.report { FastGettext.human_available_locales}}
Calculating -------------------------------------
2021-11-16T11:13:55 [D|app|] Loading and caching all available locales
                       214.449M memsize (     7.046M retained)
                         3.311M objects (    79.745k retained)
                        50.000  strings (    50.000  retained)
```

After:
```
[1] pry(main)> Benchmark.memory{|x| x.report { FastGettext.human_available_locales}}
Calculating -------------------------------------
2021-11-16T11:25:35 [D|app|] Loading and caching all available locales
                       153.147M memsize (     5.885M retained)
                         2.357M objects (    65.977k retained)
                        50.000  strings (    50.000  retained)
```
TBH we might want to look into why loading the locales takes so many allocations and memory, although in production it might be less (due to complied .mo files).

**Pull request merged**
