### PR TITLE
Fixes #24355 - Never override a smart class parameter on import

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Review by ik5 — COMMENTED** [review]
A different test fails on me here:

```
E

Error:
PuppetClassImporterTest#test_0011_should detect correct environments for import:
ActiveSupport::DeprecationException: DEPRECATION WARNING: The behavior of `attribute_was` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `attribute_before_last_save` instead. (called from block in taxonomy_and_child_ids at /home/vagrant/foreman/app/models/user.rb:462)
    app/models/user.rb:462:in `block in taxonomy_and_child_ids'
    app/models/user.rb:461:in `taxonomy_and_child_ids'
    app/models/user.rb:468:in `location_and_child_ids'
    app/models/taxonomies/location.rb:21:in `block in <class:Location>'
    app/models/user.rb:430:in `my_locations'
    app/models/user.rb:435:in `taxonomy_ids'
    app/models/user.rb:443:in `visible_environments'
    app/services/puppet_class_importer.rb:174:in `actual_environments'
    app/services/puppet_class_importer.rb:23:in `changes'
    test/unit/puppet_class_importer_test.rb:265:in `block in <class:PuppetClassImporterTest>'
```

But it does not related to your code, it happens also on the upstream develop branch.

The effected line is the following:
`importer = PuppetClassImporter.new(:url => proxy.url)`

Does this issue happens to you as well?

**Comment by orrabin** [comment]
If this happens to you for develop it's unrelated to this PR.
This passes for me locally and also passed in Jenkins.

**Review by tbrisker — APPROVED** [review]
Thanks @orrabin ! katello failure unrelated

**Comment by tbrisker** [comment]
please CP to all stable branches.

**Comment by orrabin** [comment]
@tbrisker I opened:
for 1.17: https://github.com/theforeman/foreman/pull/5894
for 1.18: https://github.com/theforeman/foreman/pull/5895
for 1.19: https://github.com/theforeman/foreman/pull/5896

**Pull request merged**
