### PR TITLE
Fixes #12261 - Removes foreign key constraint from reports table

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ohadlevy** [comment]
why? don't we want to attach a report to a host? is the purpose to allow deleting the host without deleting its reports?

**Comment by xprazak2** [comment]
Arf report is attached to host through asset and we want to keep it that way. Maybe @shlomizadok could expand on that. It could allow us to delete host and not its reports but that is not the purpose afaik.

**Comment by ohadlevy** [comment]
then why keep asset at all? imho a report should still link to a host?

**Comment by xprazak2** [comment]
I think we kept it mainly because policies are assigned through its polymorphic 'assetable' relationship either to a host or whole hostgroup. I cannot think of anything else.

**Comment by ares** [comment]
After a discussion with @xprazak2 we agreed to revisit how complicated it would be to use host_id to link directly to host omitting asset relation. If it's too complicated, I'd suggest adding `asset_id` column. Closing this PR, as it should not be needed either way.

**Pull request closed without merging**
