### PR TITLE
Docker nulldb

### PR DESCRIPTION
**Pull request by ohadlevy**
This PR includes #7594 and adds the relevant dockerfile changes.

a side effect is a bit more cleanup which reduce build time a few minutes by removing the node_modules earlier (avoid the expense chown)

### CODE REVIEW

**Comment by ohadlevy** [comment]
container image for this branch can be found at ```quay.io/ohadlevy/foreman:docker-nulldb```

**Comment by tbrisker** [comment]
nulldb pr has been merged, please rebase

**Comment by ohadlevy** [comment]
rebased.

**Comment by ohadlevy** [comment]
test failures not related.

**Review by tbrisker — APPROVED** [review]
Thanks @ohadlevy

**Pull request merged**
