### PR TITLE
Fixes #31723 - Show changes after setting update

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Changed to handle updates in a simpler fashion.

**Review by amirfefer — DISMISSED** [review]
Works well, just a few linting issues

**Review by ezr-ondrej — COMMENTED** [review]
:+1: just the lints, and I'm also good.

**Comment by amirfefer** [comment]
@xprazak2  thanks 👍 
snapshot errors seem related

**Review by ezr-ondrej — APPROVED** [review]
Thanks @xprazak2, works as expected :+1:

**Comment by ezr-ondrej** [comment]
CP 2.4 PR: #8337

**Pull request merged**
