### PR TITLE
Fixes #11791 - avoid N+1 query caused by configuration status

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
The second commit looks like it belongs to #2713, can you confirm if that's right?

**Comment by ares** [comment]
Sorry, some git typo on my side, I've cleaned the branch.

**Comment by dLobatog** [comment]
Merged as 8e67a8b6ef2348aabb164c9b861811b3c121a3a7, thanks @ares!

**Comment by domcleal** [comment]
> Merged as 8e67a8b, thanks @ares!

Actually it's 7397bf15.

**Pull request closed without merging**
