### PR TITLE
fixes #4557: namespaced plugins no longer raise exception on the filter screen

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by domcleal** [comment]
This doesn't seem to work for isolated engines, e.g. `undefined method 'katello_systems_path' for #<#<Class:0x000000090f5808>:0x00000008e3b158>`, what was the verdict for those?

**Comment by dmitri-d** [comment]
Hmm. It looks like we'll need to distinguish between various types of engines -- it appears they require different approaches. Lemme look more into this.

**Comment by dmitri-d** [comment]
@domcleal, @thomasmckay: this should work for both namespaced and mounted engines.

**Comment by domcleal** [comment]
@witlessbird could you rebase too please?  It shows a merge conflict.

**Comment by dmitri-d** [comment]
@domcleal: rebased.

**Comment by domcleal** [comment]
s/object_path/path/ on line 24, otherwise appears to work.

@ares are you happy?

**Comment by dmitri-d** [comment]
@domcleal: ty for catching that, fixed.

**Comment by ares** [comment]
Well, I'd prefer less efficient order but it's just my personal opinion

we have

``` ruby
path = type.pluralize.underscore + "_path"
if path.include?("/") # handle mounted engines
  prefix, suffix = path.split('/', 2)
  return send(prefix).send(suffix) if Rails.application.routes.mounted_helpers.method_defined?(prefix)
end
send(path.tr("/", "_"))
```

I'd prefer

``` ruby
path = type.pluralize.underscore + "_path"
prefix, suffix = path.split('/', 2)
if path.include?("/") && Rails.application.routes.mounted_helpers.method_defined?(prefix) # handle mounted engines
  send(prefix).send(suffix)
else
  send(path.tr("/", "_"))
end
```

I know that prefix and suffix would be useless for else branch, therefore less efficient but more readable. Anyway I'm ok with merging as is if noone else feels the same.

**Comment by domcleal** [comment]
Merged as 35da973 with @ares' suggestion, thanks @witlessbird!

**Pull request closed without merging**
