### PR TITLE
Fixes #36886 - upload facts for new hosts

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Thoughts about this @ares ?

**Comment by ares** [comment]
Oops sorry, please ping me on matrix in case you need my attention. I'm trying to better understand the motivation. Based on the RM ticket, I feel like the facts were ignored because the host was in build mode. That is correct, we ignore facts (primarily puppet facts) while host is in build mode, because the puppet agent runs in Anaconda environment. I assume, this is supposed to update sub-man facts right after the build mode is disabled but it could still be before the reboot. I think a better place would be in the post-reboot template, once https://github.com/theforeman/foreman/pull/9677 gets merged.

**Comment by sbernhard** [comment]
> I think a better place would be in the post-reboot template, once #9677 gets merged.

Thanks for your reply. post-reboot would be a good place but I'm unsure if all OSses would be then supported. Even, it depends on a final reboot after installation is done or not.

**Comment by stejskalleos** [comment]
@sbernhard @ares any agreement on the approach?

**Comment by sbernhard** [comment]
Thoughts @stejskalleos  / @ares?

**Comment by sbernhard** [comment]
ping....

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, we have the same approach for global registration.

**Comment by stejskalleos** [comment]
Thanks @sbernhard

**Comment by evgeni** [comment]
This was merged with super old test results and broke things as not all snapshots were uptodate. :crying_cat_face:

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman/pull/10198

**Comment by ares** [comment]
I'm very sorry I didn't reply earlier, as stated above, feel free to ping me on matrix.

The reason why we didn't upload facts from provisioning template is, that the facts come from Installer env, not the actual installed OS. That means you'll get e.g. wrong kernel version etc. I believe that's why we ignore facts while the host is in the build mode, even though puppet already uploads them on the first run. This may bite us in the future.

**Comment by evgeni** [comment]
But is that really *bad*? I mean _most_ facts would end up correct, and the ones that would not will get updated the next time the "real" OS runs a fact upload?

**Pull request merged**
