### PR TITLE
fixes #3107 - sort hostgroups alphabetically

### PR DESCRIPTION
**Pull request by stbenjam**
Makes hostgroup name a sortable column.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by ohadlevy** [comment]
i think we should use the label, as that includes the parent hostgroups

**Comment by domcleal** [comment]
Looks good, thanks @stbenjam.  I think we should probably sort by default too - this is defined by the default_scope set in the model (app/models/hostgroup.rb).  Have a look at other models, e.g. domains or environments to see how they set the default order.

**Comment by stbenjam** [comment]
Ok, done in 71802e5. Now sorts by default.

**Comment by domcleal** [comment]
Thanks! [test]

**Comment by stbenjam** [comment]
Sorry, in 9d6b50f, not sure if that messes up your testing.  I changed it to be all one commit.

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks for the patch @stbenjam!  Merged as 4b9d1fa for Foreman 1.4.0.

**Pull request closed without merging**
