### PR TITLE
Fixes #15037 - Improves editable elements in settings

### PR DESCRIPTION
**Pull request by amirfefer**
Foreman uses Jeditable jquery plugin for editable elements.
This plugin is unmaintained, and lack of some features (such as optgroup in select input).

A better alternative is [x-editable](https://vitalets.github.io/x-editable/) -  well maintained and supports much more input elements, and yet simpler.
`x-editable-rails` gem imports x-editable to rails and makes it easy to use.

optgroup in select input: 

screenshot from 2016-05-13 02-04-09

textarea input:
screenshot from 2016-05-13 10-06-57

Demonstration:

editable-gif

### CODE REVIEW

**Comment by amirfefer** [comment]
[test]

**Comment by amirfefer** [comment]
Test fails randomly and doesn't related.

**Comment by dLobatog** [comment]
@amirfefer Apologies for the delay on reviewing this, I keep on getting more and more things that are 'high prio'. Anyhow, this is looking great, thanks for doing it! I have just 2 qualms about it and then we can merge:
- This needs to be rebased
- Can you remove the `border-bottom: dashed 1px` for `editable-click`? It's the annoying dashes under every setting, you can either override the CSS or if the library allows you to disable it, that'd be even better.

:clap: Thanks, nearly ready to merge!

**Comment by amirfefer** [comment]
@dLobatog Thanks for the review.
The dashes can be removed only by css.

Furthermore, validation errors  are presented as intended: 
validations

**Comment by dLobatog** [comment]
Merged as d163507797c5d9c20249aa4d858465cbb74be229, thanks @amirfefer!

**Comment by dLobatog** [comment]
I've opened https://github.com/theforeman/foreman-packaging/pull/1238 to package the rubygem dependency - should be in nightly shortly I think

**Comment by johnpmitsch** [comment]
This is [causing issues](http://projects.theforeman.org/issues/15832) on Katello's "Red Hat Repositories" page

**Pull request closed without merging**
