### PR TITLE
fixes #8993 - handle FreeBSD patch releases better

### PR DESCRIPTION
**Pull request by mmoll**
@fraenki can test this, perhaps? :)

### CODE REVIEW

**Comment by fraenki** [comment]
@mmoll The regex should be more like `/\-RELEASE\-p[0-9]+/` to support releases with two-digit patchlevel like 9.2-RELEASE-p15. (Otherwise this release would be cut to 9.25.)

**Comment by mmoll** [comment]
@fraenki indeed, thanks. :bow: 
Also updated the tests to catch this.

**Comment by fraenki** [comment]
:+1: updated patch works well for me

**Comment by domcleal** [comment]
Merged as d4cac08 for 1.7.2, thanks @mmoll and @fraenki!

**Pull request closed without merging**
