### PR TITLE
Fixes #33265 - Revert foreman-js upgrade causing katello test failures

### PR DESCRIPTION
**Pull request by sjha4**
Context: The jest upgrade https://github.com/theforeman/foreman-js/commit/ed36c723acc4f7efd4f8a2d8dcb67433e42dea4c here seems to have broken katello react tests. 

The revert commit https://github.com/theforeman/foreman-js/pull/346 still seems to be failing with the same errors. 😕 

Proposing a short term fix to pin the foreman-js release so katello repo can be unblocked in the meantime. 
Open to other ideas.. 😄

### CODE REVIEW

**Review by jeremylenz — DISMISSED** [review]
LGTM pending Jenkins & packaging approvals

**Comment by evgeni** [comment]
Packaging wise we're still on 8.7/8.8, and so far nothing complained.

Should the pin be >= 8.7, <8.13 (if 8.13 is the breaking release), to more precisely say what we don't want?

I don't see a problem with pinning it for now, but it needs to be resolved before 3.1 branches.

**Comment by sjha4** [comment]
@evgeni..The failing tests are with 8.12.1 which upgrades jest. 
The backtrace shows the error to be coming from package jest-jasmine2 package which was also upgraded as a dependency of jest but not entirely sure.

**Review by xprazak2 — DISMISSED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
Please modify the message since this isn't reverting an upgrade, it's rather updating from 8.7.x to 8.12.0. That also needs a packaging update.

**Comment by sjha4** [comment]
@ekohl : Updated commit message to reflect the change. 👍🏽

**Comment by evgeni** [comment]
> Please modify the message since this isn't reverting an upgrade, it's rather updating from 8.7.x to 8.12.0. That also needs a packaging update.

This is why I suggested `>= 8.7, < 8.12.1`, as this wouldn't require packaging changes. ;)

**Comment by sjha4** [comment]
> > Please modify the message since this isn't reverting an upgrade, it's rather updating from 8.7.x to 8.12.0. That also needs a packaging update.
> 
> This is why I suggested `>= 8.7, < 8.12.1`, as this wouldn't require packaging changes. ;)

That sounds good..Let me do that.. 👍🏽

**Comment by evgeni** [comment]
Now the commit message doesn't match again, SORRY! :)

**Comment by sjha4** [comment]
> Now the commit message doesn't match again, SORRY! :)

Added more context to commit message.

**Review by evgeni — APPROVED** [review]

**Review by ekohl — APPROVED** [review]

**Pull request merged**
