### PR TITLE
Fixes #20387 - Handle extra spaces in the search field

### PR DESCRIPTION
**Pull request by rabajaj0509**
This commit shall improve the usability of the search field.

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM but I think it would be lovely if there was a test for that change.

**Review by timogoebel — CHANGES_REQUESTED** [review]
Thanks. Please add a test for this and add a dedicated ticket to Foreman's Redmine.

**Comment by ohadlevy** [comment]
I would like to understand where the initial whitespace is coming from.
it seems that when clicking on an auto completion suggestion it adds a whitespace.
I am guessing that was done so that if you already have a query it would include a space char between?

**Comment by rabajaj0509** [comment]
@ohadlevy  as I am testing it now, the bug is no longer reproducible. The search parameter is getting saved without the spaces automatically. Therefore, I am not sure what is to be done here.
The re-factoring pr still holds good https://github.com/theforeman/foreman_discovery/pull/366.

**Comment by ohadlevy** [comment]
@rahulbajaj0509 are you sure? I believe I can reproduce it, did you test discovery without your patched branch?

**Comment by rabajaj0509** [comment]
@ohadlevy, yes, i am not being able to reproduce it. 
discoverysearch
I had given extra spaces before the `cpu_count`. Am i missing something here?

**Comment by lzap** [comment]
So is my understanding correct that this patch:

https://github.com/theforeman/foreman_discovery/pull/366

fixed it?

**Comment by rabajaj0509** [comment]
@lzap nope, i guess there is some change in the gem itself that handled this issue (i am just guessing, i might be wrong). 

theforeman/foreman_discovery#366 is just refactoring, so when we added the welcome page to dicovery hosts (in theforeman/foreman_discovery#20247 ) we `added  model_of_controller`.

**Comment by lzap** [comment]
The thing is that the space is only visible when you editing the field. After save/submit it disappears. Let me ask the reporter in the BZ and then we can close this - I do not think this is worth any effort.

**Pull request closed without merging**
