### PR TITLE
Fixes #28874 - set/get eager zero flag

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Taking over #7647. Thanks @sbernhard !

Needs:
- [x] merge of fog/fog-vsphere#252
- [x] fog-vsphere gem release (v3.3.1)
- [x] packaging of the new version - theforeman/foreman-packaging#5200

### CODE REVIEW

**Comment by sbernhard** [comment]
Isn't there something missing which translates from "eagerZero" to eager_zero (= write the flag to fog-vsphere while creating a host) and backwards from eager_zero to eagerZero (= read the flag while editing a host)? See https://github.com/theforeman/foreman/pull/7634/files

**Comment by ezr-ondrej** [comment]
No, there isn't the process is happening as described in https://github.com/theforeman/foreman/pull/7647#pullrequestreview-409909376 translating to lower camel case to UI and translating back on parameter normalization on submitting. Very unreadable, but making it readable is out of scope of this PR IMHO

**Review by sbernhard — APPROVED** [review]
It looks pretty good and works as expected :-) Thank you very much.

**Comment by ezr-ondrej** [comment]
@shiramax this is unblocked, could you take a look? I'd like this to get in 2.1 before GA as it's quite a nice fix.

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
Working good! merging! thank you @ezr-ondrej , and also thank you @sbernhard for reviewing and testing.

**Comment by tbrisker** [comment]
Does this need a bump in the minimal fog-vsphere version as well?

**Comment by ezr-ondrej** [comment]
> Does this need a bump in the minimal fog-vsphere version as well?

Right - #7660, my bad :(

**Pull request merged**
