### PR TITLE
fixes 2812 - method lookup_values_attributes= not defined in Host::Managed (NameError)

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
Would you mind writing a test to exercise this setter @isratrade?  Thanks.

**Comment by domcleal** [comment]
Confirmed via scratch build to fix the problem:
http://koji.katello.org/koji/taskinfo?taskID=44030

**Comment by isratrade** [comment]
@domcleal, re-committed with test for lookup_values_attributes.

**Comment by domcleal** [comment]
Thanks @isratrade, will merge once tests have run.

**Comment by domcleal** [comment]
Merged as a6810fc, thanks @isratrade!

**Pull request closed without merging**
