### PR TITLE
fixes #3347 - add rake console task

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by skottler** [comment]
Looks good :+1: 

I expect the tests to be fine, but let's just see what they say.

**Comment by skottler** [comment]
Merged as 6ca42b142395dab5c05c2494a625b43f436316e2. Thanks!

**Comment by lzap** [comment]
But how do I tell it to use production environment?

If the RAILS_ENV is the only option, then this does not save us typing
(and users).

## LZ

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
@lzap RAILS_ENV is indeed what's used, but my intention is for users to run "foreman-rake console" which will automatically use RAILS_ENV=production.

**Comment by lzap** [comment]
+1 super cool

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Pull request closed without merging**
