### PR TITLE
Fixes #12652 - Remove VMware Volume name

### PR DESCRIPTION
**Pull request by chris1984**
Remove the Volume name label under Create Host since at this time its not possible to name VMware volumes.

### CODE REVIEW

**Comment by chris1984** [comment]
name column removed

https://nimbus.everhelper.me/client/notes/share/750620/9m3791ikk2hd6l55zddf

host built

https://nimbus.everhelper.me/client/notes/share/750621/2bqh7qvunqxtc4lq6rog

host in vmware and disk name showing default

https://www.dropbox.com/s/4n3dhhpx69opv5d/vcenter_vm.png?dl=0

**Comment by timogoebel** [comment]
@chris1984 : Thanks for the PR. I'd suggest not removing the field completely, but just showing the name as text when the vm is edited. We just recently added resizing support for volumes and it might be invaluable for users which volume they are actually resizing.

**Comment by chris1984** [comment]
@timogoebel Thanks for the review. I went ahead and added the field back but as readonly, also on edit hosts with resizing the vm it goes well with your suggestion now:

Creating the host:

https://nimbus.everhelper.me/client/notes/share/752339/3cp6vt4cmrgr484ty7x4

Editing the host:

https://nimbus.everhelper.me/client/notes/share/752332/s1q7q4wffc7adexeyk7i

**Review by timogoebel — APPROVED** [review]
@chris1984 : Works nicely, thanks!

**Pull request merged**
