### PR TITLE
Fixes #34996 - Do not proxy requests to smart proxies

### PR DESCRIPTION
**Pull request by adamruzicka**
This change introduces a new setting, which serves as a cache of hosts
to which http(s) requests should not be routed through the global
http(s) proxy. This setting is created from a migration and is
automatically updated each time a smart proxy is commited.

When checking if a request should be proxied, we check against this
setting and if a match is found, the request will not be proxied.

The setting might not be the best tool for the job, but it should be more performant then querying registered smart proxies each time Foreman makes an outgoing request and I didn't feel like delving deep into regular caching (and cache invalidation).

### CODE REVIEW

**Comment by ehelms** [comment]
Did you consider an option where all smart-proxy communication has proxying disabled at the smart-proxy API layer? Passing `proxy: nil` in some way to the setup code for the smart-proxy API?

https://github.com/theforeman/foreman/blob/develop/app/services/proxy_api/resource.rb#L8

**Comment by adamruzicka** [comment]
Yes, the implementation would be much simpler, but would not catch cases where someone bypasses the api layer and uses net::http/restclient/excon to talk to the proxy directly in an ad-hoc fashion. If we don't care about that, I can make the switch

**Comment by evgeni** [comment]
I would say that if someone is not using the ProxyAPI, they either:
- know what they are doing
- deserve the pain

(those options are not mutually exclusive)

Is Katello talking to Pulpcore on the Proxy w/o ProxyAPI?

**Comment by adamruzicka** [comment]
If I'm reading it right they're using pulpcore_client gem, which seems to use faraday under the hood. I'm not sure right now which adapter faraday uses, possibly net/http

**Comment by adamruzicka** [comment]
Hmm, maybe mystery solved? Outgoing connections using pulpcore_client don't seem to be going through a proxy.

```
> whereami

From: /usr/share/foreman/lib/foreman/http_proxy.rb:17 Foreman::HTTPProxy#proxy_http_request?:

    16:     def proxy_http_request?(current_proxy, request_host, schema)
 => 17: require 'pry-remote'; binding.remote_pry
    18:       !http_proxy.nil? &&
    19:       current_proxy.nil? &&
    20:       !request_host.nil? &&
    21:       http_request?(schema) &&
    22:       http_proxy_host?(request_host) &&
    23:       !local_request?(request_host)
    24:     end

> caller.take(45).reject { |line| line =~ /pry/ }                                                                                                                                                                                                                  
=> ["/usr/share/foreman/lib/foreman/http_proxy.rb:17:in `proxy_http_request?'",
 "/usr/share/foreman/lib/foreman/http_proxy/net_http_extension.rb:5:in `request'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:87:in `perform_request'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/faraday-0.17.3/lib/faraday/connection.rb:175:in `patch'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/pulp_rpm_client-3.17.4/lib/pulp_rpm_client/api_client.rb:69:in `public_send'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/pulp_rpm_client-3.17.4/lib/pulp_rpm_client/api_client.rb:69:in `call_api'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/pulp_rpm_client-3.17.4/lib/pulp_rpm_client/api/remotes_rpm_api.rb:318:in `partial_update_with_http_info'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/pulp_rpm_client-3.17.4/lib/pulp_rpm_client/api/remotes_rpm_api.rb:262:in `partial_update'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.5.0.rc1/app/services/katello/pulp3/repository.rb:96:in `remote_partial_update'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.5.0.rc1/app/services/katello/pulp3/repository.rb:84:in `update_remote'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.5.0.rc1/app/lib/actions/pulp3/repository/refresh_remote.rb:12:in `invoke_external_task'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action/polling.rb:84:in `initiate_external_action'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action/polling.rb:19:in `run'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action/cancellable.rb:14:in `run'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.5.0.rc1/app/lib/actions/pulp3/abstract_async_task.rb:10:in `run'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:582:in `block (3 levels) in execute_run'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:32:in `run'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'",
 "/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'"]

> schema
=> #<Net::BufferedIO io=#<OpenSSL::SSL::SSLSocket:0x000000000d4753d0>>

> http_request?(schema)
=> false
```

In `net_http_extensions` we pass in `@socket` as schema, which does not equal to neither `http` nor `https` (`http_request?` check). So unless we fix this, we should be good to go with only patching ProxyAPI and Katello should keep working just fine.

**Comment by adamruzicka** [comment]
## Background
We are using a couple of different libraries to make HTTP requests. We have `Net::HTTP`, `RestClient`, Katello has `pulpcore_client`, which uses `Faraday`. Both `Faraday` and `RestClient` use `Net::HTTP` under the hood.

In Foreman we are extending:
- `Net::HTTP`
  - but the current implementation does nothing (wrong arguments passed when checking whether a proxy should be used and proxy is set after the connection is already opened)
- `RestClient`
- `Excon`
  - don't see this used anywhere?

## After fixing Net::HTTP extension
When I fixed the extension of `Net::HTTP` I got into a slightly weird situation where I was setting up the proxy multiple times in multiple places (for example in restclient and then in `Net::HTTP`).

## Current state
Instead of directly extending `Net::HTTP` I chose to subclass it, so the "higher-level libraries" use the pristine version of it. If there's a bit of code where we want to use `Net::HTTP`, but with proxies, we can use the subclass, see the RSS checker commit. 

Because proxying with `Net::HTTP` never worked, we are not breaking anything:
- Katello can still use `pulpcore_client` to talk to pulp without going through a proxy
- we don't have the double proxy setup issue
- not proxying requests to smart proxies gets way easier too, assuming one sticks with `ProxyAPI`

Are there any places where we cannot use the subclass of `Net::HTTP`? Considering up until now noone noticed it does not work I would say no, but maybe I'm overlooking something.

**Comment by ehelms** [comment]
The only place I know of `excon` in use is this bit of code in Katello: https://github.com/Katello/katello/blob/master/app/models/katello/concerns/smart_proxy_extensions.rb#L193-L201

Looking back to the history, I see it was added by https://github.com/Katello/katello/commit/d2b75839705a72a7970f732c7d7159a48125f3fe which seems to be caused by foreman_azure_rm plugin overriding defaults: https://projects.theforeman.org/issues/30746

Following that history, to https://github.com/theforeman/foreman_azure_rm/commit/033a6452a9c0811f81f0808f53a7c84f55536220 it seems this was done to have HTTP proxy support coming from Foreman.

**Comment by adamruzicka** [comment]
Just checked and the excon monkey patch seems to work so we can just keep it as-is.

**Comment by ehelms** [comment]
I think this method looks good generally, I'll try and take it for a test run.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
