### PR TITLE
Fixes #6537: Entering a very large number for idle_timeout is unchecked, crashes UI

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by orrabin** [comment]
Question for reviewers - I needed to limit the `idle_timeout` because Marshal.dump(Setting[:idle_timeout].minutes.from_now.utc) was called and raised an exception when using  idle_timeout to change the session. Do you have a better why of doing this or at least a way to notify the user without changes to the db or serious refactoring of the setting model?

**Comment by ohadlevy** [comment]
Another option is to not serialize date object but rather convert it to
Unix time (plain int) instead

**Comment by orrabin** [comment]
@ohadlevy thanks, using Unix time worked

**Comment by lzap** [comment]
Tested, works for me. +1

**Comment by lzap** [comment]
Merged as 8e5a869 for Foreman 1.6. Thanks @orrabin !

**Pull request closed without merging**
