### PR TITLE
fixes #3762: menu urls defined using hashes should prefix controller name with a '/' (use absolute controller names)

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by skottler** [comment]
This fixes the issue, but it also ends up breaking deploying Foreman to a non-root path, preventing something like `https://example.com/foreman`.

**Comment by dmitri-d** [comment]
skottler is going to submit a new PR.

**Comment by domcleal** [comment]
Non-root paths still work for me when testing with RAILS_RELATIVE_URL_PATH.. not that there's much difference between the two PRs as far as I can tell, just a bit less duplication here.

**Comment by skottler** [comment]
@domcleal works for me, too when `RAILS_RELATIVE_ROOT_PATH` is set. I've re-opened this and will close the other PR since this is cleaner.

**Comment by domcleal** [comment]
Great, thanks @witlessbird and @skottler.  Merged as 3955498 for Foreman 1.4.0.

**Pull request closed without merging**
