### PR TITLE
Fixes #28921 - add updateURLQuery to urlHelpers

### PR DESCRIPTION
**Pull request by MariaAga**
updateURLQuery updates the url with a new query using the react router history object by merging the old query with the new

### CODE REVIEW

**Review by amirfefer — CHANGES_REQUESTED** [review]
Thanks @MariaAga! 
Few thoughts: 
1. is there any use for this function?
2. with the connected react-router [a similar helper](https://github.com/theforeman/foreman/pull/7186/files#diff-20eb6356edfcbe272a9eb949dad85569R34) already exists which uses router's history and its pushUrl mechanism

**Comment by MariaAga** [comment]
@amirfefer 
1.Yes in foreman tasks, and as this might be a common need I think it should be in foreman
2.Does it work the same? will it merge the search if there is already an existing search? for example:
```
url = '/foreman?search="a=b&c=d" '
search = {c:e, f:g}
```
does `pushUrl(url,search) === '/foreman?search="a=b&c=e&f=g" '`

**Review by amirfefer — COMMENTED** [review]
If you need it for foreman task, please add this helper there for a temp solution if it's needed now.
ATM we have distinct react-router for each plugin and changing history globally by that might result in issues. Soon the connected react router + react-router for plugins would be merged and the mechanism for pushing a new state to the history object for making a page transition will be unified for core and plugin.

**Comment by MariaAga** [comment]
Foreman tasks has this helper already.
This function uses react router history only, so why not add it?

**Comment by amirfefer** [comment]
when connected react-router to redux will be merged we won't use `history.push` directly anymore, the `history` object will be manipulated only through react-router and its helpers

**Comment by MariaAga** [comment]
@amirfefer  What will you use to specifically push history using react-router?

**Comment by amirfefer** [comment]
by using `push` action from `connected-react-router`
https://github.com/supasate/connected-react-router/blob/master/FAQ.md#how-to-navigate-with-redux-action

**Pull request closed without merging**
