### PR TITLE
Fixes #34293 - remove experimental banner in new host page

### PR DESCRIPTION
**Pull request by amirfefer**
The switch to the old UI and feedback still exist in the kebab dropdown.

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
How do we switch to the previous version now? I believe we should still keep that option and this is taking it away as the baner was also the way how to get to the old page, wasn't it?

**Comment by amirfefer** [comment]
@ezr-ondrej, The option for going back to the old UI also exists in the kebab dropdown.

**Comment by ezr-ondrej** [comment]
[test foreman]

**Review by ezr-ondrej — APPROVED** [review]
That case, no further questions :+1:
Thanks @amirfefer !

**Pull request merged**
