### PR TITLE
fixes #3672: Add in the zanata.xml file for pushing strings to zanata.

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by lzap** [comment]
How do I push? I am getting errors when I try to push or pull. Using zanata python client.

**Comment by bkearney** [comment]
You cd into the po directory, and you execute zanata push. You need to have your credentials set up for the client, and be a maintainer on the project. You are, so what error are you seeing?

**Comment by lzap** [comment]
I am unable to make this working. I tried zanata-python-client from Fedora 19:

```
[lzap@lzapx locale]$ zanata project info
Loading zanata project config from: /home/lzap/work/foreman/locale/zanata.xml
Loading zanata user config from: /home/lzap/.config/zanata.ini
zanata server: https://translate.zanata.org/zanata
zanata python client version: 1.3.13, zanata server API version: 3.0.2
Project: satellite6-foreman
Version: 6.0
Username: lzap
Source language: en-US
Traceback (most recent call last):
  File "/usr/bin/zanata", line 25, in <module>
    zanata.run()
  File "/usr/lib/python2.7/site-packages/zanataclient/zanata.py", line 945, in run
    program_name=os.path.split(sys.argv[0])[1],
  File "/usr/lib/python2.7/site-packages/zanataclient/command.py", line 339, in handle_program
    command(command_options, args)
  File "/usr/lib/python2.7/site-packages/zanataclient/zanata.py", line 800, in push
    command.run(command_options, args)
  File "/usr/lib/python2.7/site-packages/zanataclient/pushcmd.py", line 383, in run
    zanatacmd.verify_project(project_id, version_id)
  File "/usr/lib/python2.7/site-packages/zanataclient/zanatacmd.py", line 103, in verify_project
    self.zanata_resource.projects.get(project_id)
  File "/usr/lib/python2.7/site-packages/zanataclient/zanatalib/projectservice.py", line 84, in get
    project = Project(server_return)
  File "/usr/lib/python2.7/site-packages/zanataclient/zanatalib/project.py", line 45, in __init__
    setattr(self, str(a), [Link(item) for item in b])
TypeError: 'NoneType' object is not iterable
```

Also tried latest master from https://github.com/zanata/zanata-python-client with the same result

```
[lzap@lzapx locale]$ /home/lzap/work/zanata-python-client/zanata project info
Loading zanata project config from: /home/lzap/work/foreman/locale/zanata.xml
zanata python client version: 1.3.12-8-g629b, zanata server API version: 3.0.2
Project ID:          satellite6-foreman
Project Name:        Satellite6 Foreman
Traceback (most recent call last):
  File "/home/lzap/work/zanata-python-client/zanata", line 25, in <module>
    zanata.run()
  File "/home/lzap/work/zanata-python-client/zanataclient/zanata.py", line 945, in run
    program_name=os.path.split(sys.argv[0])[1],
  File "/home/lzap/work/zanata-python-client/zanataclient/command.py", line 339, in handle_program
    command(command_options, args)
  File "/home/lzap/work/zanata-python-client/zanataclient/zanata.py", line 529, in project_info
    zanatacmd.project_info(project_id)
  File "/home/lzap/work/zanata-python-client/zanataclient/zanatacmd.py", line 211, in project_info
    print ("Project Type:        %s")%p.type
AttributeError: 'Project' object has no attribute 'type'
```

Funny funky thing is the version in F19 is actually newer than in the git.

**Comment by lzap** [comment]
@domcleal do you think this will survive conflicts? I mean, what happens if someone edits the same PO file both using Transifex and Zanata? I _guess_ it should merge fine, but we might want to test that first. If not, we would need to "lock" Transifex for some time when guys are working on translations in Zanata.

**Comment by domcleal** [comment]
@lzap yeah, could get messy.  I wonder if both services can pull translated strings back from our repo - as far as I know, the Transifex one only syncs the .pot and not translated strings?

**Comment by bkearney** [comment]
I was assuming a lock model, since we will nkow internally when strings are being worked.

**Comment by domcleal** [comment]
A lock model should work, as mostly the existing translations aren't changing all that often.  I haven't tried the zanata client out, but as long as one of us is able to run it, we'll be ok...

Thanks @bkearney, merged as aa92e93 for Foreman 1.4.0.

**Comment by lzap** [comment]
Ok let us know when you push translations and we will update from Transifex and close it temporarily.

**Comment by domcleal** [comment]
@lzap yep, I think we might also need to upload the updated .po files to Transifex once pulled from Zanata

**Comment by bkearney** [comment]
A good rule of thumb would be to extract every week/sprint and the push 
the po files to both locations.

-- bk

**Comment by domcleal** [comment]
For the .pot file, yes.  Transifex automatically pulls it when we update (which is every few weeks), but I guess you're saying we need to push the pot to Zanata.

It's the translated .po files that we'll have to be careful about merging and ensuring are updated on both sites.

**Comment by bkearney** [comment]
On 11/20/2013 08:14 AM, Dominic Cleal wrote:

> For the .pot file, yes. Transifex automatically pulls it when we update
> (which is every few weeks), but I guess you're saying we need to push
> the pot to Zanata.
> 
> It's the translated .po files that we'll have to be careful about
> merging and ensuring are updated on both sites.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theforeman/foreman/pull/1030#issuecomment-28887859.
> 
> Crap.. messed up the items. I will ask the zanata folks how to deal with 
> a master/master model. Where merges can be done.

-- bk

**Comment by domcleal** [comment]
Thanks, for Transifex I think we're ok since we can upload any updated .po files that we pull from Zanata at the end of a translating sprint there.  As long as we can also push updated .po files _to_ Zanata at the start of those sprints when we lock Transifex, we're good I think.

**Pull request closed without merging**
