### PR TITLE
Job templates - demodulize resource type for permission

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Make sense :+1:

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
I've fixed the commit message and added commit body.
@stejskalleos btw there is more where this come from, I believe we have this issue for general permission model as well (I think `resource_class` doesn't work for namespaced plugins too well eighter)

**Comment by ares** [comment]
Perhaps this could be also helpful https://github.com/theforeman/foreman/blob/develop/app/models/permission.rb#L30-L46

**Pull request merged**
