### PR TITLE
Add support for Jenkins CI reports

### PR DESCRIPTION
**Pull request by bcrochet**
This add a rake task to support generating reports in a CI environment (specifically Jenkins)

### CODE REVIEW

**Comment by skottler** [comment]
I'm testing this out now with out Jenkins instance.

**Comment by skottler** [comment]
I setup a test job - http://ci.theforeman.org/job/test_jenkins/. This works nicely so I am comfortable merging it. @ohadlevy, can you take a look?

**Comment by ohadlevy** [comment]
@skottler @bcrochet any chance you guys can contribute some documentation on how to use it in the wiki?

**Comment by skottler** [comment]
Yup, I need to write a wiki page on Jenkins anyhow so I'll be sure to include info on this task.

**Comment by ohadlevy** [comment]
@bcrochet @skottler thanks!

**Pull request closed without merging**
