### PR TITLE
Fixes #8416 - Fix Puppet classes form n+1 queries

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by lzap** [comment]
I still experience a report:

```
http://localhost:3000/puppetclasses/2-apache/edit
N+1 Query detected
  LookupKey => [:lookup_values]
  Add to your finder: :include => [:lookup_values]
N+1 Query method call stack
  /home/lzap/work/foreman/app/helpers/lookup_keys_helper.rb:21:in `block in new_child_fields_template'
  /home/lzap/work/foreman/app/helpers/lookup_keys_helper.rb:20:in `new_child_fields_template'
  /home/lzap/work/foreman/app/views/lookup_keys/_fields.html.erb:44:in `_041903e0f16c7185bd8899cee0c3a0b0'
  /home/lzap/work/foreman/app/views/puppetclasses/_form.html.erb:55:in `block (2 levels) in _906d5ecbebf9f7d789128d3fef342cba'
  /home/lzap/work/foreman/app/views/puppetclasses/_form.html.erb:54:in `block in _906d5ecbebf9f7d789128d3fef342cba'
  /home/lzap/work/foreman/app/helpers/layout_helper.rb:268:in `form_for'
  /home/lzap/work/foreman/app/views/puppetclasses/_form.html.erb:3:in `_906d5ecbebf9f7d789128d3fef342cba'
  /home/lzap/work/foreman/app/views/puppetclasses/edit.html.erb:3:in `_f74c87076967586fe7d777e2d88d0cf2'
  /home/lzap/work/foreman/app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
  /home/lzap/work/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call
```

**Comment by lzap** [comment]
FYI I see this when edit form loads. I don't see where we have the query, must be hidden somewhere.

**Comment by dLobatog** [comment]
@lzap Can you provide more details of your class_params and lookup_keys associated with the puppetclass that's giving you that warning? I can't find a way to reproduce this, with a puppetclass with several class_params and lookup_keys all of them associated with lookup_values

**Comment by lzap** [comment]
Sure, I just imported puppetlabs/apache and clicked on the top class named "apache".

When I click on a node named "apache::dev" or "apache:anything" it does _not_ show the error.

**Comment by lzap** [comment]
One more thing - I have a "firewall" module as well and when I click on that one, no error. So it must be something in the apache class (parameter or something?)

**Comment by domcleal** [comment]
I also see one on the Puppet classes index?

<pre>
N+1 Query detected
  Puppetclass => [:class_params]
  Add to your finder: :include => [:class_params]
N+1 Query method call stack
  /home/dcleal/code/foreman/foreman/app/views/puppetclasses/index.html.erb:30:in `block in _app_views_puppetclasses_index_html_erb___4582230843538380607_79852680'
  /home/dcleal/code/foreman/foreman/app/views/puppetclasses/index.html.erb:15:in `_app_views_puppetclasses_index_html_erb___4582230843538380607_79852680'
  /home/dcleal/code/foreman/foreman/app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
  /home/dcleal/code/foreman/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call'
</pre>

(I can debug more if you don't see it.)

**Comment by dLobatog** [comment]
@domcleal Right this is highly dependent on what you have on the index page, my suggestion is to open a new PR per each bad query we see, with instructions on how to reproduce. I don't have any class that trigggers that in the index page, no idea why.

**Comment by domcleal** [comment]
@eLobato sure, will do.

So two points about this PR:
1. I can reproduce what lzap's seeing, which seems to be any class with at least one smart class parameter in an environment, which means changing line 43 to: `@puppetclass.class_params.includes(:environments, :environment_classes, :lookup_values).each do |key|`
2. The environment_classes include isn't needed here, and I can't see where it might be used.  It's the smart variables tab that you've optimised, but that doesn't use environments.

**Comment by dLobatog** [comment]
@domcleal The smart-variables tab uses environment classes as the first field, line 4 in lookup_keys/fields. I however do not see either how this include, outside of the scope of `f.fields_for`, seems to affect it, but this goes away after I include :environment_classes. 

Thanks for the reproducer for @lzap 's issue, I've added the appropriate includes now.

**Comment by domcleal** [comment]
That looks strange.. line 86 of the form is just listing smart variables, but line 4 of fields.html is only called `if is_param` which should only be smart class parameters.

Does the smart variables tab list class parameters for you?

**Comment by dLobatog** [comment]
@lzap @domcleal I found what it was, it did list class parameters, but I've just realized this is a malformed LookupKey I have, probably created through the console. I've removed environment_classes from that include. Hope it's good now, sorry for the confusion I may have caused.

**Comment by domcleal** [comment]
That makes sense.  Thanks @eLobato, merged as c4f9aca.

**Pull request closed without merging**
