### PR TITLE
Fixes #20668 - capitalize cards on smart proxy page

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by tbrisker** [comment]
@ares - Tests are failing.

**Comment by ares** [comment]
Thanks, tests should be fixed now.

**Review by dLobatog — APPROVED** [review]
Tests pass again, merging

**Comment by dLobatog** [comment]
Thanks @ares & @tbrisker

**Comment by ares** [comment]
Thanks for merging @dLobatog, I set a release in redmine to 1.16.0, please don't forget to set it after merge.

**Pull request merged**
