### PR TITLE
Fixes 19298 - Use chevron instead of colons for breadcrumbs

### PR DESCRIPTION
**Pull request by lizagilman**
before: 
colons

after:
chevron

### CODE REVIEW

**Comment by dLobatog** [comment]
Thanks @lizagilman ! - I modified the commit title to say "Fixes #" as it's what our automation expected.

**Comment by lizagilman** [comment]
oops :flushed:
thanks @dLobatog

**Comment by domcleal** [comment]
The commit message comment should have been addressed before this was merged. If the commit message is not in the correct format, the Redmine ticket will not be linked and checked.

Also, tests were clearly not run by either the author or on CI, as they fail. Please address comments from @theforeman-bot _before_ merging. See https://github.com/theforeman/foreman/pull/4463#issuecomment-294855690, https://github.com/theforeman/foreman/pull/4463#issuecomment-294855691, https://github.com/theforeman/foreman/pull/4463#issuecomment-294855692. Tests fixed in #4466.

**Comment by ohadlevy** [comment]
also please see the regression this pr introduce - http://projects.theforeman.org/issues/19305

**Comment by ares** [comment]
The problem is that some tests are running even for non-whitelisted PRs and it's easy to miss that only 3 checks succeeded instead of 6 if you see green box. Comments by @theforeman-bot are fine but can be easy missed if there's other communication. Maybe the prprocessor could enforce WoC (or whatever new label) until it can see the commit is fully tested.

**Comment by dLobatog** [comment]
I saw the 'green box' and didn't stop to check whether it was 3 or 6 checks that passed, that's why it got through, sorry. As for the extra empty space above and below the name, I' ll figure out how to remove them as clearly they were not here (https://groups.google.com/forum/?fromgroups#!searchin/foreman-dev/meeting$20facts%7Csort:relevance/foreman-dev/b4GjoGqAcxs/j3-4jjqeDAAJ)

**Comment by ohadlevy** [comment]
@dLobatog the spaces are because of the breadcrumbs css class, we might not need this css class at all for this specific usage case.

**Pull request merged**
