### PR TITLE
fixes #1489 - AIX not showing up on Hosts page

### PR DESCRIPTION
**Pull request by rmueck**
Added the modifications mentioned at http://projects.theforeman.org/issues/1489 and also added 
the modifications from  Ludovic Dépinoy.

### CODE REVIEW

**Comment by skottler** [comment]
[test]

**Comment by skottler** [comment]
I don't have an AIX machine to test this on, but since it's just extending patterns that we already use I think it should be fine. That being said, it'd be nice to get someone else who has a working AIX setup to take a look at this just to confirm it works properly.

**Comment by GregSutcliffe** [comment]
I believe the issue with #1489 was partially the copyright for the logo - do we know we can use this one?

**Comment by rmueck** [comment]
i will try to check this out with IBM!

**Comment by ohadlevy** [comment]
@rmueck ping ?

**Comment by rmueck** [comment]
@ohadlevy 

"Fair use" of IBM trademarks, that is, use by a third party without express permission or license, is limited to 
text-only references to IBM trademarks such as product and service names, and excludes IBM logos. 

Use of IBM logos

IBM carefully limits the use of its logos. No other company may use IBM logos unless it has the express written permission of IBM, or is licensed by IBM to do so.

To obtain permission to use any IBM logo, contact your IBM representative or the IBM Call Center at 1-800-IBM4YOU (1-800-426-4968) and ask for Corporate Branding.

**Comment by domcleal** [comment]
Due to the above restrictions on logo usage, I've dropped the logo from the patch and updated [#2445](http://projects.theforeman.org/issues/2445) to request info if this situation changes.

The remainder I've merged as 7e2880b6 for Foreman 1.4.  Thanks for the contribution @rmueck!

**Comment by lzap** [comment]
I cant see any logo in your commit, so which logo do we currently use for AIX?

Btw where our logos come from? Is this some kind of library of small distro logos, or we do edit them (scale down) ourselves?

I am asking on Fedora Legal about this, maybe we can just redraw this in GIMP.

**Comment by domcleal** [comment]
@lzap I removed it entirely, so no logo is shown - just the text name.  Usually we scale down the logos from the OS/distribution site.  Thanks for investigating further.

**Pull request closed without merging**
