### PR TITLE
Fixes #14492 - Unify delete and minimize for dashboard widgets

### PR DESCRIPTION
**Pull request by tbrisker**
Originally the idea was for the buttons to have a different effect on
the widgets, however with changes introduced later on these differences
have been reduced to being insignificant.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker thanks, please note the test failures

**Comment by tbrisker** [comment]
@ohadlevy Thanks, should be fixed now

**Comment by ohadlevy** [comment]
test foreman

**Comment by tbrisker** [comment]
Test failures unrelated.

**Comment by ohadlevy** [comment]
thanks @tbrisker

**Pull request merged**
