### PR TITLE
refs #21394 - user login with access token api

### PR DESCRIPTION
**Pull request by timogoebel**
This PR fixes some comments by @ares, that didn't make it in time into https://github.com/theforeman/foreman/pull/4930.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@timogoebel can you please rebase? thanks.

**Comment by timogoebel** [comment]
Rebased.

**Comment by ares** [comment]
Thanks @timogoebel, works still great :-) Is there a plan to add support to hammer-cli-foreman? Would you mind creating redmine issue for that? Also would you be so kind and sent a PR to the Foreman manual that would describe how to use it? I think [this](https://theforeman.org/manuals/1.15/index.html#5.1.8Authentication) would be a good place. If not it's fine, just let me know so someone else will cover it.

Anyway, neither of above blocks merging. Merged as 596cf7cfb5c40e3ec7376f77300c50fcdcdf9ae7

**Comment by timogoebel** [comment]
@ares: Thanks, I opened http://projects.theforeman.org/issues/21514 to cover this in hammer-cli.

**Comment by timogoebel** [comment]
@ares: Regarding the manual entry, we currently don't have a manual for 1.17. What's the best way to document this, then?

**Comment by ares** [comment]
Thanks @timogoebel! I'm afraid the only reasonable way is to send a PR against 1.16 and rebase it once it's copied for 1.17.

**Pull request closed without merging**
