### PR TITLE
fixes #13845 - remove 1.13 deprecations

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
Test failure on Katello might be due to the deprecated behaviour still in use: http://projects.theforeman.org/issues/15256

**Comment by dLobatog** [comment]
Cool, waiting on https://github.com/theforeman/foreman-tasks/pull/189

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
The test failures are now fixed, thanks.

**Comment by dLobatog** [comment]
Merged as f21ca7d529052497eb343fc34828513cee84cd75, thanks @domcleal!

**Pull request closed without merging**
