### PR TITLE
Fixes #9584 - User email address length can be longer than 60

### PR DESCRIPTION
**Pull request by dLobatog**
As far as I know, there's no need for this artificial limitation.

### CODE REVIEW

**Comment by stbenjam** [comment]
The database length is 255, which is technically 1 more than the maximum length but otherwise :+1: 

 A discussion of the topic here: http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

**Comment by tbrisker** [comment]
I would say we should follow the standards here; while currently the DB limits to 255, that may change in the future, and we should explicitly limit according to the IETF standard to 254.

**Comment by dLobatog** [comment]
Updated to limit to 254

**Comment by tbrisker** [comment]
Merged as b6ebaea14c3d38e8e44789f25832d0d71457938a, thanks @dLobatog!

**Pull request closed without merging**
