### PR TITLE
Fixes #34689 - bootfile should be useable in Jail

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Review by ofedoren — CHANGES_REQUESTED** [review]
Thanks, @sbernhard, could you please add documentation just above that method [1] similar to [2]? Just because ideally all the methods available in `Jail` should be documented :)

[1] - https://github.com/theforeman/foreman/blob/731e24511c656e3800afd8c4ceada201e4067a0b/app/models/operatingsystem.rb#L227
[2] - https://github.com/theforeman/foreman/blob/731e24511c656e3800afd8c4ceada201e4067a0b/app/models/operatingsystem.rb#L223

Also, I'm curious how did that work for Windows templates in safe mode so nobody noticed that it was broken...

**Comment by sbernhard** [comment]
> Thanks, @sbernhard, could you please add documentation just above that method [1] similar to [2]? Just because ideally all the methods available in `Jail` should be documented :)
> 
> [1] -
> 
> https://github.com/theforeman/foreman/blob/731e24511c656e3800afd8c4ceada201e4067a0b/app/models/operatingsystem.rb#L227
> 
> [2] -
> 
> https://github.com/theforeman/foreman/blob/731e24511c656e3800afd8c4ceada201e4067a0b/app/models/operatingsystem.rb#L223
> 
> Also, I'm curious how did that work for Windows templates in safe mode so nobody noticed that it was broken...

Or, it was never used in safe mode? :)

**Review by ofedoren — APPROVED** [review]
Thanks, @sbernhard, LGTM now :)

**Comment by lzap** [comment]
3.2 CP: https://github.com/theforeman/foreman/pull/9170

**Pull request merged**
