### PR TITLE
fixes #5248 - restrict fog-core to compatible version (fog#2873)

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
I'm going to look into the followup issue reported on the bug before merging.

**Comment by stagrlee** [comment]
On a live foreman 1.5.0 rc1, after editing /usr/share/foreman/bundler.d/fog.rb, how do you rebundle the gems for foreman?

**Comment by domcleal** [comment]
`cd ~foreman && bundle update fog-core`

**Comment by domcleal** [comment]
This is up for review, I'll send a new PR for the second issue (#5453).

**Comment by ohadlevy** [comment]
merged as a253106 thanks!

**Pull request closed without merging**
