### PR TITLE
Fixes #30713 - power_status helper fixed

### PR DESCRIPTION
**Pull request by lzap**
I have no idea why but Rails complains about non-existing method for
this code. I googled this, I have no idea why/how this worked. Probably
something from the pre-Rails5 time.

### CODE REVIEW

**Review by tbrisker — DISMISSED** [review]
rebase please

**Review by ekohl — COMMENTED** [review]
Should we add a test for this? Clearly there isn't one or we would have found this.

**Comment by lzap** [comment]
Amended, added test.

**Comment by lzap** [comment]
This is also ready, small change, test done.

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Looks good and it has tests so merging this.

**Comment by lzap** [comment]
Cherry pick into 2.2: https://github.com/theforeman/foreman/pull/8172

**Pull request merged**
