### PR TITLE
Fixes #36307 - Remove * for non mandatory fields

### PR DESCRIPTION
**Pull request by girijaasoni**
Removed "*" for non-required fields. Screenshot's attached below:
Screenshot from 2023-04-17 14-40-06
Screenshot from 2023-04-17 14-39-55

### CODE REVIEW

**Review by Ron-Lavi — COMMENTED** [review]
@girijaasoni can you update the tests snapshots? `npm test -- -u`
and also can you rebase with upstream/develop? (should fix the npm v12 tests failures)

**Comment by girijaasoni** [comment]
> @girijaasoni can you update the tests snapshots? `npm test -- -u` and also can you rebase with upstream/develop? (should fix the npm v12 tests failures)
Thnks Ron, updated it

**Comment by girijaasoni** [comment]
> @girijaasoni can you update the tests snapshots? `npm test -- -u` and also can you rebase with upstream/develop? (should fix the npm v12 tests failures)

Thanks Ron, updated it

**Review by Ron-Lavi — DISMISSED** [review]
Thanks @girijaasoni, looks good to me 👍🏼 
btw, there's a proptypes issue that we might want to fix while we are working on this form (but not blocking this PR on it)

the proptypes issue:
```
warning: Failed prop type: Invalid prop `pluginValues.lifecycleEnvironmentId` of type `string` supplied to `ActivationKeys`, expected `object`.
    in ActivationKeys (created by RegistrationActivationKeys)
    in RegistrationActivationKeys
    in Slot (created by ConnectFunction)
 ```

**Review by stejskalleos — CHANGES_REQUESTED** [review]
JWT expiration should not be required too, in API we set the default value [0] to 4 hours if the parameter is not set.
In UI, the field should be validated with a warning in case of an invalid value.

[0] https://github.com/theforeman/foreman/tree/develop/app/controllers/concerns/foreman/controller/registration_commands.rb#L35-L40

**Comment by girijaasoni** [comment]
> np

> JWT expiration should not be required too, in API we set the default value [0] to 4 hours if the parameter is not set. In UI, the field should be validated with a warning in case of an invalid value.
> 
> [0] https://github.com/theforeman/foreman/tree/develop/app/controllers/concerns/foreman/controller/registration_commands.rb#L35-L40

Thanks Leos, updated it

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected!

Thanks @girijaasoni

**Review by stejskalleos — APPROVED** [review]

**Pull request merged**
