### PR TITLE
Fixes #24874 - update secure_headers to 6.x

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I didn't find any places in our code that are mentioned in the docs for breaking changes of 6.x and an update of my prod instance didn't seem to introduce any ill effects...

**Review by ekohl — APPROVED** [review]

**Comment by tbrisker** [comment]
@mmoll while i'm fine with this, i wonder if we still need it at all? iirc rails 5.2 already includes options for setting most if not all of the headers we use.

**Comment by mmoll** [comment]
I'd vote for getting this in now to have a good gut feeling for the time being. :smirk:

I did subscribe to https://github.com/twitter/secure_headers/issues/375 and opened https://projects.theforeman.org/issues/24934 in order to check if the current config we use is on Rails 5.2 standards.

**Review by tbrisker — APPROVED** [review]
Sure, works for me. sorry for the delay, thanks @mmoll !

**Pull request merged**
