### PR TITLE
Fixes #4370 - Filters list show permissions

### PR DESCRIPTION
**Pull request by dLobatog**
http://projects.theforeman.org/issues/4370

### CODE REVIEW

**Comment by dmitri-d** [comment]
I'm getting "Invalid search query: the field 'permissions' in the order statement is not valid field for search" when attempting to sort by permissions -- filter model is missing corresponding scoped search definition.

I'm not sure how useful this sorting order is, perhaps it's better to leave it out? Would it be better to allow filtering based on permission name?

**Comment by dLobatog** [comment]
@thomasmckay ^^

**Comment by thomasmckay** [comment]
@eLobato Not sorting seems fine to me. I assume search works?

**Comment by dmitri-d** [comment]
Search on permissions isn't working atm; should be straightforward to add though.

**Comment by dLobatog** [comment]
I'll add scoped_search to permissions then.

**Comment by domcleal** [comment]
Some of the columns (like the last one with dropdown + button) look rather squashed to me when viewing something like the manager role.

**Comment by dLobatog** [comment]
I'm not quite sure how to handle searches with spaces, queries should be made like this now:
`role = "Manager" and permission = edit_organizations`

It's understandable for us devs but regular users will see stuff like "Edit organizations" in the permissions column, should I better change that to "edit_organizations" like what users see when editing the filter?

**Comment by domcleal** [comment]
I think edit_organizations is clearer, keep it consistent.

**Comment by dmitri-d** [comment]
+1 to what @domcleal said.

**Comment by dLobatog** [comment]
Ask and you shall receive. :smile:

**Comment by dmitri-d** [comment]
Sorting by permissions is still enabled, but isn't working: "Invalid search query: the field 'permissions' in the order statement is not valid field for search". Filtering by permission name works, but values are not being auto-suggested as for other fields (I tried it -- looks helpful, although the auto-suggest list can get pretty long).

**Comment by dLobatog** [comment]
I disabled sorting by permissions.

**Comment by domcleal** [comment]
Merged as 46da92f for Foreman 1.5.0, thanks @eLobato!

**Pull request closed without merging**
