### PR TITLE
Fixes #23273 - use safemode which allows .freeze

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
waiting on a safemode release with https://github.com/svenfuchs/safemode/pull/25

**Review by tbrisker — DISMISSED** [review]
Looks like the PR in safemode was merged, please update this once they release a new version

**Comment by lzap** [comment]
Version 1.3.5 is out, ignore the rubygem release date ("January 2018"), it does contain the properly tagged 1.3.5 contents.

**Comment by mmoll** [comment]
this got updated accordingly.

**Review by lzap — APPROVED** [review]
LGTM

**Comment by lzap** [comment]
There are still some failures: http://ci.theforeman.org/job/test_plugin_matrix/5167/

Why the PR tests were green while develop is red?

**Comment by mmoll** [comment]
@lzap these happen *only* in discovery. It has to do something with the extension discovery does with core objects.

**Comment by rabajaj0509** [comment]
The failing tests seem to have some issue with the permissions for non-admin users.

**Comment by lzap** [comment]
Oh I missed the fact it was plugin suite link, sorry for the noise.

**Pull request merged**
