### PR TITLE
Fixes #24122 - Remove limit from LookupValue value

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by tbrisker** [comment]
@orrabin should lookup key `default_value` also have limit removed?

**Review by dLobatog — DISMISSED** [review]
Setting to WoC, I think `default_value` should also remove the limit too, the value was changed in the same way in db/migrate/20121218084123_change_smart_variable_length.rb

**Comment by orrabin** [comment]
For some reason I'm not getting the error on default_value, I'll try to fail it with a test and fix according to that but I tested before adding the PR and it saved the `default_value` without an error.

**Comment by orrabin** [comment]
@dLobatog I was able to get the error on `default_value` in a test so I added the test as well and added it to the migration.

**Review by tbrisker — APPROVED** [review]
Thanks @orrabin !

**Pull request merged**
