### PR TITLE
Build packit against rhel-8

### PR DESCRIPTION
**Pull request by ekohl**
This matches what we use in foreman-packaging.

### CODE REVIEW

**Review by ehelms — APPROVED** [review]

**Comment by evgeni** [comment]
@ekohl @ehelms did you also update docs and forklift to use the new chroot name?

https://github.com/theforeman/forklift/blob/master/roles/packit/tasks/main.yml#L5

**Comment by ekohl** [comment]
No. I only realized it changed after it was merged. This should be applied project wide then I guess

**Comment by evgeni** [comment]
Yepp

**Pull request merged**
