### PR TITLE
fixes #3673 - auditing added to ptable w/ test

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by skottler** [comment]
@thomasmckay this seems to break the tests - can you take a look?

**Comment by thomasmckay** [comment]
fails in
https://github.com/theforeman/foreman/blob/develop/db/migrate/20100523114430_add_ubuntu_custom_lvm_ptable.rb

Do I need to add ptable to this file?
https://github.com/theforeman/foreman/blob/develop/app/models/concerns/audit_extensions.rb?source=cc

**Comment by domcleal** [comment]
It looks to be a DB migration ordering problem, since we set up some of the audit columns in migrations like 20110712064120_update_audits_table but the ptables are being added before that in 20100523114430_add_ubuntu_custom_lvm_ptable and similar, so the audit code doesn't run on the old table schema.

Ideally I think we'd be moving the ptables and other data into seed scripts or something, which would run on the finalised database and we wouldn't hit this problem.

I don't know how to fix this otherwise, any ideas @ohadlevy?  I don't think we can simply rename the migrations, since existing schema metadata will be out of date.

**Comment by domcleal** [comment]
Here's an idea: https://gist.github.com/7562599

The same in other migrations (like solaris disks) which also create ptables.

**Comment by ohadlevy** [comment]
you can also do:

``` ruby
Ptable.without_auditing {
  Ptable.create....
}
```

**Comment by thomasmckay** [comment]
@ohadlevy @domcleal clean tests. two migrations altered w/ Ptable.without_auditing

**Comment by domcleal** [comment]
Thanks for the patch @thomasmckay!  Merged as 0fecb5337 for Foreman 1.4.0.

**Pull request closed without merging**
