### PR TITLE
Fixes #10133 - Prevent deadlocks when fixing counter_cache

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by domcleal** [comment]
Could you explain a bit about how this fixes it?  Is it running outside of the main transaction so is less likely to deadlock based on hitting the same rows/columns?  Is it still transactional?

**Comment by tbrisker** [comment]
@domcleal :  From looking at the logs of the original bug reporter, it seems that rails and the counter cache fix both attempted to update the counter in the same transaction as the one updating the relation. Some condition, most likely related to the load on the server (~40k hosts, ~60 puppet masters), caused concurrent updates to block each other. 
`after_commit` will cause the fix to run in a separate transaction, hopefully leading to this issue being resolved. 
Unfortunately I could not reproduce such a large setup to test, and the original poster has reduced the number of puppet masters in his network which led to the deadlocks going away as well.

**Comment by dLobatog** [comment]
I'd say let's merge if the reporter says this worked.

**Comment by dLobatog** [comment]
@tbrisker OK, just read the original reporter doesn't have that problem any more... I'd love to try it but as you said it's not that easy to reproduce. If you provide some script to simulate the load from these 60 puppet masters maybe we can get it in, otherwise I would suggest closing this for the moment, can be reopened if someone experiences similar pains.

**Comment by tbrisker** [comment]
Alright, closing for now, will reopen if another user runs into similar issue.

**Comment by ares** [comment]
Reopening, another user (@balexx) hit the same issue when importing chef facts. He tested this patch and it fixed the issue. For more details see http://projects.theforeman.org/issues/11232

**Comment by ares** [comment]
Merged as 7fad1fa0e253e793511df1cde24d8b1885d640c4, thanks @tbrisker!

**Comment by lzap** [comment]
Shell we remove this whole hack now having Rails 4.x ?

```
# cat /usr/share/foreman/app/models/concerns/counter_cache_fix.rb
# Fix for counter cache not being updated on related model updates.
# See: https://github.com/rails/rails/issues/9722
# TODO: remove when upgrading to Rails 4.x
# inspired by fix from http://stackoverflow.com/a/11569554/1091445
```

I am hitting massive database deadlocks with Satellite 6.2 client creation test.

**Comment by tbrisker** [comment]
@lzap I'm afraid the issue still remains for at least one edge case in rails 4, see http://projects.theforeman.org/issues/7246 and https://github.com/rails/rails/issues/23265 for more info.
I'm actually inclined to get rid of the counter cache entirely if we can get decent enough performance on the pages using it, but it won't be in time for 6.2.
btw, are you sure the deadlocks are in this hack and not in the rails implementation? This should not cause deadlocks as it is run in a separate transaction (unlike the rails implementation that uses `COALESCE` inside the same transaction as the host update).

**Comment by lzap** [comment]
Looks like Rails issue. The whole cache thing is crazy from the day one, DB systems are optimized to give decent results I suppose:

```
2016-06-10 10:58:53 CEST ERROR:  deadlock detected
2016-06-10 10:58:53 CEST DETAIL:  Process 19805 waits for ShareLock on transaction 1661291; blocked  +by process 24817.
        Process 24817 waits for ExclusiveLock on tuple (0,24) of relation 18010 of database 17659;   +blocked by process 19805.
        Process 19805: UPDATE "hostgroups" SET "hosts_count" = COALESCE("hosts_count", 0) + 1 WHERE  +"hostgroups"."id" = 2
        Process 24817: UPDATE "hostgroups" SET "hosts_count" = COALESCE("hosts_count", 0) + 1 WHERE  +"hostgroups"."id" = 2
2016-06-10 10:58:53 CEST HINT:  See server log for query details.
2016-06-10 10:58:53 CEST STATEMENT:  UPDATE "hostgroups" SET "hosts_count" = COALESCE("hosts_count", +0) + 1 WHERE "hostgroups"."id" = 2

2016-06-10 10:58:53 CEST ERROR:  deadlock detected
2016-06-10 10:58:53 CEST DETAIL:  Process 19784 waits for ShareLock on transaction 1661291; blocked  +by process 24817.
        Process 24817 waits for ExclusiveLock on tuple (0,59) of relation 17911 of database 17659;   +blocked by process 19784.
        Process 19784: UPDATE "operatingsystems" SET "hosts_count" = COALESCE("hosts_count", 0) - 1  +WHERE "operatingsystems"."id" = 4
        Process 24817: UPDATE "operatingsystems" SET "hosts_count" = COALESCE("hosts_count", 0) + 1  +WHERE "operatingsystems"."type" IN ('Redhat') AND "operatingsystems"."id" = 4
2016-06-10 10:58:53 CEST HINT:  See server log for query details.
2016-06-10 10:58:53 CEST STATEMENT:  UPDATE "operatingsystems" SET "hosts_count" =                   +COALESCE("hosts_count", 0) - 1 WHERE "operatingsystems"."id" = 4
```

We should measure the impact of this and get rid of it ideally.

For the record the bug is: https://bugzilla.redhat.com/show_bug.cgi?id=1344709

**Pull request closed without merging**
