### PR TITLE
New OpenNebula compute resource

### PR DESCRIPTION
**Pull request by b0e**
Hi,

we added a compute resource for OpenNebula. With this PR it is possible to create, delete, start, stop virtual machines in an OpenNebula instance.  VNC is working as well. New virtual machines are created from the available templates in the OpenNebula instance and some major values can be overridden.

Fog is used to talk to the OpenNebula XML-RPC daemon, though it is necessary to install a fog version with a OpenNebula provider (there is an existing pull request to the fog project) which is available here https://github.com/NETWAYS/fog.

Any feedback is welcome!

### CODE REVIEW

**Comment by ohadlevy** [comment]
nice! we are now on the process of moving all compute resources into plugins, would you consider implementing this as a plugin instead? (see foreman-xen or foreman-docker for examples)

thanks!

**Comment by mauerj** [comment]
great work!
there seems to be a feature request for this:
http://projects.theforeman.org/issues/3643

**Comment by b0e** [comment]
Hi! 

Now there is a foreman-one plugin. https://github.com/NETWAYS/foreman-one 

But you have to use the netways fog versions https://github.com/NETWAYS/fog 
I need some time to update the fog versions used by foreman.  The fog versions net-v1.19.0, net-v1.21.0, net-v1.22.0 and the branch one_compute_provider should work with the new foreman-one plugin.

**Comment by arnisoph** [comment]
Awesome work guys! Looking forward to see this in upstream! :)

**Comment by dLobatog** [comment]
Great job @b0e ! Shall we close this PR since people can use your plugin https://github.com/NETWAYS/foreman-one instead?

You can set a different source for fog in your plugin Gemfile, so that it points to your fog repository, although it'd be so much better if that could be merged upstream :smile:  

I've just watched the video http://youtu.be/Lind0WNaxYI and it looks wonderful!

**Comment by domcleal** [comment]
Thanks for creating the plugin @b0e.  Please let us know once your Fog changes are included upstream in a release that we're using as I'd like to package foreman_one up and promote it so people can start using it.

Closing the PR now :+1:

**Comment by lzap** [comment]
Thanks, OpenNebula rocks! :-)

LZ

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by david-strejc** [comment]
I got a problem with OpenNebula and foreman I am getting this error:

> ]
> Failed to create a compute OpenNebula (OpenNebula) instance whatever-22.es1.easycloud.cz: undefined method `id' for nil:NilClass
>  /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.23.0/lib/fog/opennebula/models/compute/flavor.rb:102:in`block in get_nic'
> /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.23.0/lib/fog/opennebula/models/compute/flavor.rb:101:in `each'
> /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.23.0/lib/fog/opennebula/models/compute/flavor.rb:101:in`get_nic'
> /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.23.0/lib/fog/opennebula/models/compute/flavor.rb:34:in `to_s'
> /opt/rh/ruby193/root/usr/local/share/gems/gems/foreman_one-0.2/app/models/foreman_one/one.rb:82:in`create_vm'

The log continues, but I just want to know if I am able to somehow get this working.

**Comment by domcleal** [comment]
@david-strejc looks like the thread going on here: https://github.com/theforeman/foreman-one/issues/4

**Pull request closed without merging**
