### PR TITLE
Fixes #11339 - ensure unique parameters before adding uniq index

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by domcleal** [comment]
Please note that tests are failing.

**Comment by jlsherrill** [comment]
Doh! Last minute change, updated!

**Comment by dLobatog** [comment]
Works well. However it worries me that the following code:

``` ruby
2.times do 
   foo = Parameter.new(:name => 'foo', :reference_id => 2)
   foo.type = 'DomainParameter'
   foo.save
end

Parameter.where(:name => 'foo') # this will return 2 values
```

still produces duplicates despite the unique index. Validations do actually run if you create the parameter using `DomainParameter`, etc... instead of setting the `type` manually.

update - I try to fix this on https://github.com/theforeman/foreman/pull/2604

**Comment by dLobatog** [comment]
Merged as aabf3c22f047b4cb9b8699a11c04abd954a397b5, thanks @jlsherrill!

**Pull request closed without merging**
