### PR TITLE
Fixes #16131 - Upgrade select2 to version 4

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by dLobatog** [comment]
:+1: for the Foreman side of things. For packaging, `add_npm_package` (bundle strategy, since we don't have nodejs-almond and nodejs-jquery-mousewheel) would do most of what's needed to get it in there - https://github.com/theforeman/foreman-packaging/tree/rpm/develop#howto-create-a-new-core-package-or-dependency-npm-modules

**Comment by dLobatog** [comment]
[test foreman]

**Comment by dLobatog** [comment]
Ready to merge if Jenkins tests pass

**Comment by dLobatog** [comment]
@tbrisker Check out tests, I didn't look in detail but the hostgroup and network select2 fields worked when I tested manually :disappointed:

**Comment by dLobatog** [comment]
@tbrisker Mind to rebase and see if tests pass? Last time I tested it worked well enough to merge. Thanks!

**Comment by ohadlevy** [comment]
@tbrisker ping?

**Comment by tbrisker** [comment]
Closing this for now, I don't think I'll be able to get to it soon, and it may be better to replace this with a react implementation in any case.

**Pull request closed without merging**
