### PR TITLE
fixes #4524 - The logged in user should be the default one in create new...

### PR DESCRIPTION
**Pull request by martin-ducar-gd**
... hosts

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
I don't think this is the right place to fix it, since the code added in 452 is still present, albeit in a slightly different form.  It's now here:

https://github.com/theforeman/foreman/blob/develop/app/models/host/managed.rb#L806-L809

It looks like #2179 broke this as it added validation of "owner types", but when you're using the form, no owner type is set.

I'd suggest changing set_default_user to something like:

```
def set_default_user
  return if self.owner_type.present? && !OWNER_TYPES.include?(self.owner_type)
  self.owner_type ||= 'User'
  self.owner ||= User.current
end
```

What do you think @eLobato?

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
It looks good to me with the new changes, [test]

**Comment by martin-ducar-gd** [comment]
Can you please take a look at the change and possibly merge it please?

**Comment by domcleal** [comment]
@martin-ducar-gd thanks for the update, I'll give it a test soon and merge.

**Comment by domcleal** [comment]
Merged as 19579f8 for Foreman 1.4.2.  Thanks for the contribution @martin-ducar-gd!

**Pull request closed without merging**
