### PR TITLE
Refs #28320 - upgrade sass to sassc

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Upgrade to sassc. With the wrapper there should be no code change needed.

Packaging: theforeman/foreman-packaging#4661

### CODE REVIEW

**Comment by sharvit** [comment]
I guess we want to wait with it after the 2.0 branching?

**Comment by ekohl** [comment]
Yes. On IRC we had a conversation about this. Packaging shows that we still have dependencies on sass via [patternfly-sass](https://rubygems.org/gems/patternfly-sass) and [font-awesome-sass](https://rubygems.org/gems/font-awesome-sass) (latest versions of that do use `sassc`, not the 4.6.2 we have packaged now).

That means that even if we update, we're still using `sass`. Rails 6 was also moved to Foreman 2.1 and that includes this change.

In the mean time, it'd be great to push patternfly-sass to depend on `sassc`.

**Comment by ezr-ondrej** [comment]
> In the mean time, it'd be great to push patternfly-sass to depend on `sassc`.

I've already opened a PR patternfly/patternfly#1199 for it, but we would need them to move to font-awesome-sass >= 5 in order to remove `sass` completely :(

**Review by tbrisker — APPROVED** [review]
packaging pr: https://github.com/theforeman/foreman-packaging/pull/4661

**Review by tbrisker — APPROVED** [review]
Packaging merged, thanks @ezr-ondrej !

**Comment by ekohl** [comment]
FYI: packaging broke because sassc doesn't actually work. Revert PR @ https://github.com/theforeman/foreman-packaging/pull/4836 & https://github.com/theforeman/foreman/pull/7501

**Comment by ekohl** [comment]
Looks like sassc also fails to build (compile) on ARM. We don't build nightly on ARM, but in a PR we do and there I noticed it.

**Comment by tbrisker** [comment]
> Looks like sassc also fails to build (compile) on ARM. We don't build nightly on ARM, but in a PR we do and there I noticed it.

Would this be a good opportunity to drop arm support? It's already something that we've considered doing in the past, and feedback from the community survey indicates very few people would be affected by it. If it's preventing us from upgrading our dependencies, than it's more significant than just the effort and time taken for maintaining it.

**Comment by ekohl** [comment]
IMHO we can start with opening an issue in their tracker. If that's all we need to do, then it's not too difficult.

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman-packaging/pull/4907 seems to fix it and independently of ARM, this is also needed for x86.

**Comment by ekohl** [comment]
And not just for deb, I also noticed we should do the same on RPM. Optimizing for a particular CPU (that's even undefined) is not something you can generally do in packaging.

**Pull request merged**
