### PR TITLE
Fixes #25910 - Move js test-helpers to npm

### PR DESCRIPTION
**Pull request by sharvit**
It removes our js test-helpers and consumes them from the new npm react-redux-test-utils.
https://sharvit.github.io/react-redux-test-utils/

Also, contain some small adjustments to the storybook docs.

### CODE REVIEW

**Review by ohadlevy — DISMISSED** [review]

**Comment by sharvit** [comment]
Need to fix some linting errors

**Review by ekohl — COMMENTED** [review]
Is it wise to rely on a package that's not in theforeman namespace for test helpers? If we need a fix then we rely on @sharvit to do this. There are no other collaborators on npm. Is it also likely that others will start using this?

**Comment by sharvit** [comment]
It's a great point @ekohl and I would be ok moving the library under the-foreman scope.

I believe it might be useful to any developer who wants to test react/redux code.

**Comment by sharvit** [comment]
Linting errors fixed, it should be ready to go.

**Comment by sharvit** [comment]
Rabased, can we merge it?

@ekohl we can move it to `@theforeman` org once we will finish the sub-packages architecture we started with `@theforeman/vendor`.

**Comment by ekohl** [comment]
Yes, I'd strongly prefer to move to the foreman org. We should also look at a Foreman org on NPM similar to https://rubygems.org/profiles/theforeman

**Comment by sharvit** [comment]
> Yes, I'd strongly prefer to move to the foreman org. We should also look at a Foreman org on NPM similar to https://rubygems.org/profiles/theforeman

Already created `@theforeman` organization under my npm account: https://www.npmjs.com/org/theforeman

We can move it to foreman account once we ready

**Review by Ron-Lavi — COMMENTED** [review]
Awesome work @sharvit,
I can't believe this library name wasn't taken before :rofl:
Looks good, can you please rebase?
by the way, do you know why the coverage decreased ?

**Comment by ohadlevy** [comment]
@sharvit can you rebase please?

**Comment by sharvit** [comment]
Thanks, rebased!

**Review by Ron-Lavi — DISMISSED** [review]
Thanks @sharvit LGTM :+1:

**Comment by mmoll** [comment]
@sharvit Was that npm package moved the theforeman org on npmjs?

**Comment by sharvit** [comment]
> @sharvit Was that npm package moved the theforeman org on npmjs?

Not yet, I would like to wait for the upcoming meetup so we can finalize how we want to do so.

Once we decide we can just move it to `theforeman` in github and maybe publish under `@theforeman` in npm.
Anyway, I don't think it should block us from merge this PR.

**Comment by sharvit** [comment]
@mmoll @ohadlevy can we merge it please?

**Comment by mmoll** [comment]
@sharvit please rebase and fix the then occuring test failure.

**Comment by ohadlevy** [comment]
@sharvit  should we just move it to https://github.com/theforeman/foreman-js as a new package?

**Comment by sharvit** [comment]
> @sharvit should we just move it to https://github.com/theforeman/foreman-js as a new package?

Yes! I will be working on that :+1: 

It should not block the PR since it will still be deployed to `npm` with the same package name. (but from another github repository)

**Review by tbrisker — CHANGES_REQUESTED** [review]
Tests are failing after rebase, please update

**Comment by tbrisker** [comment]
ping @sharvit what is the status here?

**Comment by sharvit** [comment]
> ping @sharvit what is the status here?

Waiting for me to rebase and migrate new places to use the test-helpers

**Comment by tbrisker** [comment]
ping @sharvit?

**Comment by mmoll** [comment]
What's the status here?

**Comment by sharvit** [comment]
> What's the status here?

Pretty awful, basically I will need to restart the effort. Not my first priority atm.

**Comment by tbrisker** [comment]
Thanks @sharvit !

**Pull request closed without merging**
