### PR TITLE
Fixes #12278 - make sure permission set is uniq for role

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares :+1: , could you add a description why this is necessary to the commit? Ready to merge after that IMO.

**Comment by ares** [comment]
I updated the message, more dev-related description is in redmine issue which I prefer.

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@ares Apparently there are a few problems with Katello permissions after this :disappointed:

**Comment by ares** [comment]
how comes it was green before I changed the commit message??

**Comment by ares** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as 6190cbb507f5cdda646cd59278bb8c543ba9cf88, thanks @ares!

**Comment by domcleal** [comment]
The commit above doesn't seem to be on the `develop` branch.  @ares could you please push this branch again and reopen the PR so we can re-run it through Jenkins before pushing again?

**Comment by ares** [comment]
@domcleal repushed and reopened, I suppose new [test] has to be triggered manually as it remembers it passed all checks

**Comment by dLobatog** [comment]
Merged as 6190cbb507f5cdda646cd59278bb8c543ba9cf88, thanks @ares!

**Comment by dLobatog** [comment]
Not sure what happened last time - https://github.com/theforeman/foreman/commit/ea04cccaf405f297206afba7e73dd3192a342563 is the right commit sha

**Pull request closed without merging**
