### PR TITLE
Fixes #15108 - allow editing cloned roles

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares Thanks, it works well :smile: I'm wondering why not using a migration to ensure `builtin` has a valid value?

**Comment by ares** [comment]
Thanks for looking, that was my original thought but it seems that schema changes are not accepted for stable branches (and this is meant to be added to stable 1.12). In develop it's already fixed by https://github.com/theforeman/foreman/pull/3659/files#diff-dbdb4ceb4a2d790f9001a3bc2be67da1R3

**Comment by dLobatog** [comment]
I see, I don't recall ever merging patches specific for a minor version outside CVE fixes - @domcleal OK to merge this ?

**Comment by ares** [comment]
I think we do it regularly for regressions introduced in current or previous branch. Since the impact is quite big for users who actively use roles I think this should get to 1.12 branch.

**Comment by domcleal** [comment]
@dLobatog fine by me, so long as it was addressed in develop. Having a different patch is OK to minimise changes in the stable branch.

**Comment by dLobatog** [comment]
Merged as 919cde52ef017819767dabd0424a6c6bb6c9e788 for 1.12-stable, thanks !

**Pull request closed without merging**
