### PR TITLE
API Development Guidelines

### PR DESCRIPTION
**Pull request by stejskalleos**
Migrated guidelines from our old wiki page [0]

[0] https://projects.theforeman.org/projects/foreman/wiki/API_v2_Development_Guidelines

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@ofedoren could you please also take a look if there is nothing outdated? :)

**Comment by ofedoren** [comment]
Well, the info present here is quite up to date. The only thing that bothers me is that, except `.rabl` info, it's not quite API dev guide, but more like API docs dev guide. Few things I'd like to be mentioned:
 - If you add a new UI feature or API feature, please make sure that this functionality is present in the corresponding counterpart.
 - Please think about the future: **don't** create too general names and please **don't** simplify parameter names too much. It's better to be explicit now than deal with overlapping and confusion later (**don't** use `environment` as a parameter name if the actual resource is called `FavoriteEnvironment`)
 - If you add a new API endpoint, please be sure to create a corresponding `hammer` command if it makes sense (most of the time) or at least create a ticket for it in [Redmine](https://projects.theforeman.org/projects/hammer-cli/issues/new).
 - Please, be sure the API docs actually match the endpoint, since users (including `hammer`) will rely on that information first.

**Review by ezr-ondrej — DISMISSED** [review]
I'd agree here with @ofedoren that this is by no means complete, but I also would like to first put what we have to the places we want to have that, in this case that place is here IMHO.
@stejskalleos would you want to do a follow-up for the aforementioned improvements or should we open a RM ticket for it?

**Comment by stejskalleos** [comment]
@ezr-ondrej Updated with @ofedoren comment (new section **Adding new feature**)

**Review by ezr-ondrej — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
Thanks @stejskalleos and @ofedoren ! :+1:

**Pull request merged**
