### PR TITLE
Fixes #13279 - Adapt alerts to Patternfly

### PR DESCRIPTION
**Pull request by dLobatog**
Currently our alerts have a h4 header, then a text. Alerts on Patternfly
are meant to have a bold title, then the content, like one can see in
https://www.patternfly.org/widgets/#alerts

### CODE REVIEW

**Comment by dLobatog** [comment]
[test] , job was aborted

**Comment by ohadlevy** [comment]
would you consider also fixing up the toast alerts? simple css can be found at https://rawgit.com/patternfly/patternfly/master/tests/cards.html (top left corner)

**Comment by ohadlevy** [comment]
@dLobatog note it requires 2.9.0 (https://github.com/patternfly/patternfly/releases/tag/v2.9.0)

**Comment by dLobatog** [comment]
@ohadlevy I'm cool with that, but can we adapt toasts to patternfly on a separate PR? 

This PR fixes many alerts that currently look very wrong - toasties look 'OK' for our current version of patternfly. I don't see it on https://rawgit.com/patternfly/patternfly/v2.8.0/tests/cards.html. I can add a screenshot in a comment inline for every fix I made here if that helps reviewers.

Also it would require packaging once again, and [patternfly-sass](https://rubygems.org/gems/patternfly-sass) 2.9 (what we use) is not released yet.

**Comment by ohadlevy** [comment]
merged as 90aa4b0 thanks @dLobatog

**Pull request closed without merging**
