### PR TITLE
Fixes #30999 - Add :activation_key to the Global registration template

### PR DESCRIPTION
**Pull request by stejskalleos**
`@activation_key` is for Katello plugin, see https://github.com/Katello/katello/pull/8903

### CODE REVIEW

**Review by ares — APPROVED** [review]
Thanks @stejskalleos, APJ (Ack pending jenkins), merging one it's green.

**Review by timogoebel — CHANGES_REQUESTED** [review]
I think this should be guarded with the `plugin_present?` macro to check that katello is avaliable.

**Comment by ekohl** [comment]
> I think this should be guarded with the `plugin_present?` macro to check that katello is avaliable.

That's on line 43, right?

**Review by timogoebel — APPROVED** [review]
Never mind me. :)

**Review by ekohl — APPROVED** [review]

**Pull request merged**
