### PR TITLE
[refactor] breakdown of proxy api classes

### PR DESCRIPTION
**Pull request by ohadlevy**
the proxy api had many classes in a single file, this commit simply break it down

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Will test this with Discovery today, looks good though.

**Comment by ohadlevy** [comment]
@GregSutcliffe is that a :+1: ?

**Comment by GregSutcliffe** [comment]
@ohadlevy i get ProxyAPI errors on creating a host: Failed to initialize the Puppetca proxy: uninitialized constant ProxyAPI::Puppetca

**Comment by ohadlevy** [comment]
pushed fixed, can you try again please?

**Comment by GregSutcliffe** [comment]
Looks good, I can provision a discovered host (which exercises the PuppetCa and BMC code, at least). :+1: from me

**Pull request merged**
