### PR TITLE
Fixes #10658 - corrected logger use in templates

### PR DESCRIPTION
**Pull request by lzap**
Quick merge?

### CODE REVIEW

**Comment by domcleal** [comment]
What context is this used in then?  Probably better to delegate `logger` to the correct place?

I can only see uses in controllers, models and helpers.

**Comment by lzap** [comment]
Bootdisk.

**Comment by lzap** [comment]
Specifically `app/services/foreman_bootdisk/renderer.rb` from its controllers.

**Comment by domcleal** [comment]
Given it's working in core, we could simply have foreman_bootdisk delegate `logger`, even to its own plugin logger (soon).

**Pull request closed without merging**
