### PR TITLE
fixes #6228 - disable provisioning method radio boxes after host is provisioned

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
Do we have any model-level validation to prevent the provision_method being changed via the API?

**Comment by isratrade** [comment]
recommitted with model-level validation to prevent update on `provision_method` but still 2 failing tests that I'm not sure of cause.

**Comment by domcleal** [comment]
Merged as 57e4204 for Foreman 1.6.0, thanks @isratrade.

**Comment by ohadlevy** [comment]
Should we allow to change if we are in build mode?

**Comment by ohadlevy** [comment]
The like of thought here is the same for any other attribute which is set
only for provisioning, e.g os  arch ptable etc

**Comment by domcleal** [comment]
While that sounds attractive, I don't think it's particularly feasible (at least right now) as you're talking about a host that's already been created in the case of an image build, destroying it and then setting up a PXE build or vice versa...

**Pull request closed without merging**
