### PR TITLE
Fixes #38053 - Remove syspurpose addons from Foreman

### PR DESCRIPTION
**Pull request by chris1984**
* In https://github.com/Katello/katello/pull/11196 we removed syspurpose addons from Katello. I didn't realize we had them in Foreman too which of course then broke QE tests.

### CODE REVIEW

**Comment by chris1984** [comment]
@jeremylenz 👀

**Comment by jeremylenz** [comment]
Test failures look like they might be related.

**Review by jeremylenz — DISMISSED** [review]
Code LGTM, let's just get the tests green. APGHA :+1:

**Comment by chris1984** [comment]
@jeremylenz checking from my phone but they all passed it looks like 😄

**Review by jeremylenz — APPROVED** [review]
ACK

**Pull request merged**
