### PR TITLE
Documentation link fix

### PR DESCRIPTION
**Pull request by kyzh**
While i was doing a new install, i realised that all link on the default pages were broken.
This is an attempt at fixing it.

I replaced the link to their equivalent on the manual.
So far the version is hardcoded to 1.1, that might need to be change in the long run.
I also replaced the "wiki" link at the bottom of the page by "manual" as i think the wiki is to be deprecated.

Also i just updated the following with the new URL to the "issues" page :
- app/models/orchestration/dhcp.rb
- app/views/common/500.rhtml

Also spotted few places where URL could do with an update:

```
extras/cli/foremancli:puts "     http://theforeman.org/projects/foreman/wiki/Search_API"
extras/cli/foremancli:opts.on( "--custom COLLECTION", "Custom COLLECTION string, see: http://theforeman.org/projects/foreman/wiki/API" ) do |f|
extras/foreman-release.spec:URL: http://theforeman.org/projects/foreman/
```

This was based on branch 1.1 .

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
@kyzh I think you need to rebase and squash - I suspect you didn't mean to add 57 other commits :)

**Comment by kyzh** [comment]
Arf - that wasn't the plan indeed. 
Hopefully next time will be the 3rd time lucky.
I also shouldn't try do do pull request on my lunch break.

**Comment by ohadlevy** [comment]
@kyzh any chance you could open a new PL? or shall I extract the commits from this PR?

**Comment by kyzh** [comment]
I seen the URL to the old wiki were functioning again.
That mitigated the need to have it pointing to the new site.

There is probably some documentation that were not there last month.
If you give me a day, I should be able to provide a clean PR.

**Comment by ohadlevy** [comment]
Awesome - thanks!

**Pull request closed without merging**
