### PR TITLE
Fix #2816: Prevent diff viewer on report page from overflowing to be outside the parent modal

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by domcleal** [comment]
On hold as per ticket comments, since one part of the issue remains.

**Comment by domcleal** [comment]
@skottler ping, this on the 1.3 target list but will be bumped to 1.4 if not updated.

**Comment by skottler** [comment]
I'll update this as well tomorrow.

**Comment by skottler** [comment]
[test]

**Comment by skottler** [comment]
I'm still having issues reproducing the second part of the bug. I open the modal after saving and the content is that; it looks a little odd because the modal isn't wide enough, but it's always been like that.

**Comment by ohadlevy** [comment]
@abenari can you review please?

**Comment by mmoll** [comment]
could this be merged to fix the first part of the bug for now?

**Comment by domcleal** [comment]
Merged 76ab062 for Foreman 1.4.1, thanks @skottler.  I've left the ticket open so we can resolve the second issue later.

**Pull request closed without merging**
