### PR TITLE
fixes #5879 - minimum of scoped_search 2.7.0 required

### PR DESCRIPTION
**Pull request by domcleal**
See comments in http://projects.theforeman.org/issues/5879

### CODE REVIEW

**Comment by parthaa** [comment]
ACK worked for me

**Comment by stbenjam** [comment]
@domcleal If it were 2.7.1, you get the reverse column sorting.

**Comment by stbenjam** [comment]
Nevermind, it's in 2.7.0 too.

**Comment by domcleal** [comment]
@ares would you mind reviewing/merging?

**Comment by ohadlevy** [comment]
merged as 447e48f thank @domcleal

**Pull request closed without merging**
