### PR TITLE
Fixes #35177 - Option to switch to graphical kickstart

### PR DESCRIPTION
**Pull request by jcpunk**
When my disk layouts blowup, this is a handy option to have.

I'll probably need help getting the template selftests updated....

### CODE REVIEW

**Comment by evgeni** [comment]
Can we help you re-record the snapshots? :)

**Comment by jcpunk** [comment]
I'd love some help with the snapshots.... I tried but got:

```
[riehecky@leibniz foreman]$  RAILS_ENV=test bundle exec rake snapshots:generate
rake aborted!
LoadError: cannot load such file -- net/smtp
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `require'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
/tmp/bar/foreman/config/application.rb:58:in `<top (required)>'
/tmp/bar/foreman/Rakefile:1:in `require'
/tmp/bar/foreman/Rakefile:1:in `<top (required)>'
/tmp/bar/foreman/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/usr/share/gems/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
/usr/share/gems/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/share/gems/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
/usr/bin/bundle:25:in `load'
/usr/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```

**Comment by evgeni** [comment]
Yeah, right now, you need to run this on Ruby 2.7 right now. 3.0 and 3.1 aren't supported yet.

**Comment by jcpunk** [comment]
These templates seemed simple enough that I could hack them by hand... I may not have been successful....

**Comment by jcpunk** [comment]
ping....

**Comment by jcpunk** [comment]
Just checking in

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
Sorry @jcpunk, I am waaaay to lazy sometimes!

**Comment by jcpunk** [comment]
No worries :)

**Pull request merged**
