### PR TITLE
Fixes #30504 - Remove trends and statistics endpoints

### PR DESCRIPTION
**Pull request by tbrisker**
These have been extracted to a plugin in 2.3 and can be dropped by now.

### CODE REVIEW

**Comment by xprazak2** [comment]
Looks good, test failures seem like they are related.

**Comment by tbrisker** [comment]
thanks @xprazak2, removed the ACL change that caused the failure, opened https://projects.theforeman.org/issues/33387 to remove this unused permission.

**Comment by tbrisker** [comment]
all 🍏 now

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Comment by lzap** [comment]
Ah you were faster. No surprise!

**Pull request merged**
