### PR TITLE
Fixes #14720 - Handling invalid email from auth source

### PR DESCRIPTION
**Pull request by ahumbe**

### CODE REVIEW

**Comment by domcleal** [comment]
Please note that this ticket was marked as a duplicate of #14720, please use that ticket number in your commit message and PR title.

**Comment by timogoebel** [comment]
@ahumbe: Thanks for your contribution. Would you mind adding a test case for this? Just to make sure we don't beak it in the future again. If you need any help, let me know.

**Comment by ahumbe** [comment]
@timogoebel Test cases added. Thanks!

**Comment by timogoebel** [comment]
[test] - this triggers the ci tests

**Comment by ranjan** [comment]
[test] failure looks unrelated to the change

**Comment by timogoebel** [comment]
@ahumbe : Thanks for adding the tests. I think, we shouldn't fail silently here. Can you maybe add a flash message that the attribute was invalid and not imported? If no email is set, the user is then redirected to it's own user edit page and he can add the e-mail address. What do you think?

**Comment by ahumbe** [comment]
@timogoebel If the email address is blank then user is automatically redirected to the user edit page. This is already handled in the old code base. 
Firstname and Lastname are not mandatory attributes so user is not redirected to the user edit page, but it will be good to have a flash message informing user that firstname/lastname is invalid, after successful login. Will work to have a flash message. Thanks.

**Comment by ahumbe** [comment]
@timogoebel Added flash message while creating user first time from external authentication source, if we are setting any invalid values as blank. 

Current flash message we added looks like  " Success: Firstname or Lastname of the user returned from auth source is invalid so it is set to nil  ", if there are any improvements required in the flash message, please let us know.

**Comment by dLobatog** [comment]
[test] @ahumbe If tests pass, this should be ready to merge. The comments make the intent of that code very clear, so thanks for that!

**Comment by dLobatog** [comment]
Merged as 714a42c51d2bb6e2e61b4b99fb7183573e8bfd1c, thanks @ahumbe!

**Pull request closed without merging**
