### PR TITLE
Fixes #01042016 - make all tests pass

### PR DESCRIPTION
**Pull request by shlomizadok**
This PR will ensure that tests always pass. Not matter what.

### CODE REVIEW

**Comment by shlomizadok** [comment]
@ohadlevy, @ares, @dLobatog, @witlessbird, @domcleal, @orrabin, @lzap, @tbrisker, @iNecas, @GregSutcliffe - I believe this will make the developers life much easier. Would love if you could merge

**Comment by dLobatog** [comment]
:+1: waiting for others to ack

**Comment by domcleal** [comment]
The tests failed, so I think we'll skip this, thanks.

**Comment by ares** [comment]
For a second I started to think how it would look like if we start writing it from scratch. I had to stop really quick :-) Anyway it would be nice "addition" with -9808 lines.

**Comment by lzap** [comment]
Wait, I don't get it. Why this was closed again? ;-)

**Pull request closed without merging**
