### PR TITLE
Fixes #31399 - snapshot tests exclude plugins

### PR DESCRIPTION
**Pull request by lzap**
Plugins should be disabled, every deveoper has a different set of plugins and when calling `snapthot:generate` rake task it can make a different output which then fails on CI.

### CODE REVIEW

**Comment by lzap** [comment]
I have found the issue why I still saw the `string lsb-release wget python` in the codebase: it was some old template that was deleted/renamed. I modified the rake task to clean the directory prior generating them, now it's clear.

**Comment by lzap** [comment]
One more thing this patch could solve is using these "test_on" tags to solve an ugly solution that was introduced some time ago: #6951

My thinking is introducing test flag like with_foreman_ansible and that would cause the stub to actually return true on plugin_present?. This would give us full control on what to actually render during test.

**Comment by lzap** [comment]
Just for the record, I can implement the solution mentioned in the previous comment only after https://github.com/theforeman/foreman/pull/8149 is merged and this is rebased on top of it because that would require the new feature introduced by the other patch.

**Comment by ezr-ondrej** [comment]
> My thinking is introducing test flag like with_foreman_ansible and that would cause the stub to actually return true on plugin_present?. This would give us full control on what to actually render during test.

This would be nice, but if something is behind a plugin guard, it usually means it also needs to have the plugin funcionality, wouldn't it fail on CI? :thinking:

**Comment by lzap** [comment]
Well, yes, this would only work for those "simple" cases e.g. when ssh remote execution is reported as installed, drop few extra commands to install SSH keys. Not when plugin code is actually called.

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by lzap** [comment]
CI expired the jobs, let me rebase once again.

**Comment by lzap** [comment]
This is still relevant and it is bugging me quite a bit, @ezr-ondrej 

Every time I run snapshot generate rake task, ansible adds some changes to some snapshots and I need to manually revert the changes. Thanks.

**Review by ezr-ondrej — APPROVED** [review]
I still believe this dosn't solve the issue completely (plugins are still patching the core methods, even if they are not found by our `Plugin.find` so they can alter the snapshot results), but it works for our current templates, so I'm ok whit this :+1:

**Pull request merged**
