### PR TITLE
fixes #9135 - set hostgroup based on fact/default value

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by mmoll** [comment]
is this https://github.com/GregSutcliffe/foreman_default_hostgroup ? ;)

**Comment by stbenjam** [comment]
Yes, but the plugin isn't available in Red Hat downstream and it's a relatively easy addition to core... which is what prompted this.  Although `foreman_default_hostgroup` seems to have some more advanced matching features...

**Comment by mmoll** [comment]
I see, carry on :) :mount_fuji:  :mountain_cableway:

**Comment by stbenjam** [comment]
Maybe @GregSutcliffe has an opinion about this in core :-)

**Comment by dLobatog** [comment]
I'd say let's make it available in Red Hat downstream then?

**Comment by stbenjam** [comment]
Well, that's fine, but when you're looking at the plugin list in Katello it's really getting very long...why shouldn't this just be in core if default taxonomies are?

**Comment by stbenjam** [comment]
It also has implications for things like hostgroup provisioning, which _is_ a core feature (albeit a not well maintained one).  I'd really like to be able to have a hostgroup provisioned machine actually end up in the designated host group, and this would be one way to do it.

**Comment by domcleal** [comment]
> I'd really like to be able to have a hostgroup provisioned machine actually end up in the designated host group

http://projects.theforeman.org/issues/6952 for the record.

**Comment by domcleal** [comment]
[test] failure due to #9138, now resolved.

**Comment by stbenjam** [comment]
[test]

**Comment by dLobatog** [comment]
@GregSutcliffe @ohadlevy any more thoughts on this? I still think it'd be better to package foreman_default_hostgroup. Even better we could instead move provisioning from default facts (in general) to a plugin, and get rid of `default_xxxx` in core.

**Comment by stbenjam** [comment]
I've given up on hostgroup provisioning and related issues.

**Comment by lzap** [comment]
@stbenjam sorry it took so long for us to take a look. This should really not happen. I am going to review and test all the realted patches, if you are willing to get back to this. These kind of bugs are real pain both upstream and downstream, got two customer issues now.

**Pull request closed without merging**
