### PR TITLE
Fixes #34987 - Force 1 call on first load for TableIndexPage

### PR DESCRIPTION
**Pull request by Ron-Lavi**
(cherry picked from commit 59a5d167803fbc483e68a83d377d2ded8e89bf6c)

### CODE REVIEW

**Comment by ofedoren** [comment]
The tests are failing, but it's not (yet) related to this PR, but other issue we had with broken deps: https://github.com/theforeman/foreman/pull/9288, but I guess better fix is https://github.com/theforeman/foreman/pull/9353.

**Comment by Ron-Lavi** [comment]
Thanks @ofedoren! Cherry-picked also https://github.com/theforeman/foreman/commit/c3c697fa131aa54c11918bcc563a7789f3c08ef7

**Comment by ofedoren** [comment]
[test]

**Comment by ofedoren** [comment]
ok to test

**Comment by ofedoren** [comment]
Thanks, @Ron-Lavi, seems to be :green_apple:, but since we bump a dependency here, I guess we need ack from @theforeman/packaging

**Comment by evgeni** [comment]
`bundler.d/test.rb` is not owned by packaging, hack away!

https://github.com/theforeman/foreman/blob/4ac4abff0d6681efbfdf3e383a8ff9d2da42ecab/.github/CODEOWNERS#L4-L7

**Review by ofedoren — APPROVED** [review]
> `bundler.d/test.rb` is not owned by packaging, hack away!
> 
> https://github.com/theforeman/foreman/blob/4ac4abff0d6681efbfdf3e383a8ff9d2da42ecab/.github/CODEOWNERS#L4-L7

:facepalm: sorry ._.

Merging then.

**Pull request merged**
