### PR TITLE
Fixes #7738 - logout_url is nil by default for all SSO backends

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by adelton** [comment]
:+1: This does not seem to cause regressions for base and intercept logon form-based logins.

**Comment by dLobatog** [comment]
@ares I think you meant to put this on `sso/base.rb`?

**Comment by ares** [comment]
Thanks @eLobato for review, I moved it and removed the try.

**Comment by dLobatog** [comment]
[test]

**Comment by domcleal** [comment]
I don't think re-testing will help, the test failure looks pretty definitive:

<pre>
  1) Error:
test_0002_allows logout when CSRF token is correct(UsersControllerTest::CSRF):
NoMethodError: undefined method `logout_url' for nil:NilClass
    /var/lib/workspace/workspace/test_develop_pr_core/database/postgresql/puppet/3.0/ruby/1.9.3/app/controllers/users_controller.rb:102:in `logout'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/abstract_controller/base.rb:167:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:461:in `block (3 levels) in _run__1713842057170396581__process_action__1659504123630294770__callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9080'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:326:in `around'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:310:in `_callback_around_1301'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9080'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:460:in `block (2 levels) in _run__1713842057170396581__process_action__1659504123630294770__callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9079'
    /var/lib/workspace/workspace/test_develop_pr_core/database/postgresql/puppet/3.0/ruby/1.9.3/app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9079'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:426:in `block in _run__1713842057170396581__process_action__1659504123630294770__callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9078'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:326:in `around'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:310:in `_callback_around_13'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9078'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:414:in `_run__1713842057170396581__process_action__1659504123630294770__callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/abstract_controller/callbacks.rb:17:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `block in instrument'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activesupport-3.2.18/lib/active_support/notifications.rb:123:in `instrument'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/activerecord-3.2.18/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/abstract_controller/base.rb:121:in `process'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:45:in `process'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/metal/testing.rb:17:in `process_with_new_base_test'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/test_case.rb:490:in `process'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/apipie-rails-0.2.6/lib/apipie/extractor/recorder.rb:118:in `process_with_api_recording'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/test_case.rb:54:in `process'
    /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-0/gems/actionpack-3.2.18/lib/action_controller/test_case.rb:412:in `post'
    /var/lib/workspace/workspace/test_develop_pr_core/database/postgresql/puppet/3.0/ruby/1.9.3/test/functional/users_controller_test.rb:366:in `block (2 levels) in <class:UsersControllerTest>'
</pre>

**Comment by ares** [comment]
Ah right, get_sso_method can still return nil if we didn't use any sso method. I reverted try.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/5ed22f148b7238eef70cc38636cb9bc4624158ef , thanks @ares for the quick turnaround!

**Pull request closed without merging**
