### PR TITLE
fixes #15622 - add about link for non-admin user

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by timogoebel** [comment]
[test] - this triggers our ci tests

**Comment by ranjan** [comment]
[test] failure looks unrelated to the change

**Comment by dLobatog** [comment]
I think I'll merge. I was a bit hesitant because it shows smart proxies / compute resources, etc.. but those are properly scoped via permissions. No special info is disclosed there, merging...

**Comment by dLobatog** [comment]
Merged as 3d81c7dfb390e22bd4401d6cf8d9fb56607370e6, thanks @anandkumaragrawal!

**Pull request closed without merging**
