### PR TITLE
Fixes #28248 - Notify about SQLite production usage deprecation

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Do we have a way to say we want to remove this blueprint in version 1.27 let's say? Or just @tbrisker remembers what ought to be removed? xD
Otherwise LGTM! :+1:

**Comment by tbrisker** [comment]
> Do we have a way to say we want to remove this blueprint in version 1.27 let's say?

The blueprint is generic for feature deprecation and shouldn't be removed, the notification itself can be cleaned up by notification clean up task after it expires.

**Comment by ezr-ondrej** [comment]
> > Do we have a way to say we want to remove this blueprint in version 1.27 let's say?
> 
> The blueprint is generic for feature deprecation and shouldn't be removed, the notification itself can be cleaned up by notification clean up task after it expires.

Yeah right, thats what I meant :)

**Review by lzap — APPROVED** [review]
That's fine. I am actually surprised that there is someone who does this.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @tbrisker! I believe we should backport to 1.24, and 1.23 right?

**Comment by tbrisker** [comment]
1.23 - 02c723213
1.24 - 4d038185b

**Pull request merged**
