### PR TITLE
fixes #2296 Hostgroup fields not populating when parent fields are selec...

### PR DESCRIPTION
**Pull request by abenari**
...ted

### CODE REVIEW

**Comment by lzap** [comment]
So this just prevents the 404 error in the log, right?

**Comment by isratrade** [comment]
@lzap, correct
@abenari can you close this PR as I included your commit in PR #693 (and changed the commit message)

**Comment by isratrade** [comment]
@abenari, I needed your patch to work on my PR.

**Comment by abenari** [comment]
closing included in PR #693

**Pull request closed without merging**
