### PR TITLE
fixes #2772 cloning locations and organizations is broken

### PR DESCRIPTION
**Pull request by abenari**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@isratrade didnt we handle this already? is this a leftover?

**Comment by isratrade** [comment]
@ohadlevy, yes, I thought I already did this.

**Comment by isratrade** [comment]
@ohadlevy, I just checked it.  It definitely needs to be .dup

**Comment by ohadlevy** [comment]
@isratrade so we have clone in other places (e.g. interfaces.clone), can you make sure we didnt mix it up again? :)

**Comment by ohadlevy** [comment]
thanks! merged as 532d961

**Pull request closed without merging**
