### PR TITLE
[WIP] Eslint error

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
I”m testing a different linting ci that actually works with prettier (unlike hound) in order to be consistent with patternfly-react: 
https://github.com/amirfefer/foreman/pull/6

**Comment by mmoll** [comment]
While I don't know about the background here, personally I'd use eslint-plugin-prettier, so that prettier is used in addition to possible eslint plugins.

**Comment by ohadlevy** [comment]
@mmoll I assume this can be closed now?

**Pull request closed without merging**
