### PR TITLE
Fixes #18722 - fix host parameters in host form

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
If it's acked, it should be cherry-picked to 1.14-stable as it's marked for 1.14.3 in redmine. Not sure if the Label 1.14 is used for that so rather not setting it.

**Comment by dLobatog** [comment]
Works well - I do agree it has to be cp-ed. @ares can you write a test for it? `test/integration/parameters_permissions_test.rb` doesn't cover this well. Thanks

**Comment by ares** [comment]
Test added. Testing this is hell.

**Comment by ohadlevy** [comment]
@ares one of the reasons I think we should slowly move params into react/redux

**Comment by dLobatog** [comment]
Thanks @ares!

**Pull request merged**
