### PR TITLE
Fixes #24672 - fix new line in template export metadata

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
when we inject metadata inside the comment, we can't add new line (part of metadata) since on re-import/re-export it would always add additional  line

**Comment by xprazak2** [comment]
[test foreman]

**Comment by tbrisker** [comment]
Please rebase on latest develop to get tests to run

**Comment by ares** [comment]
rebased

**Review by tbrisker — APPROVED** [review]
Thanks @ares !

**Pull request merged**
