### PR TITLE
Fixes #13594 - Pin parser gem to 2.3

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
Is this fixed in master upstream, or reported?

Which release are you intending to pin to exactly?  2.3.0.0?

**Comment by shlomizadok** [comment]
@dLobatog found the issue on parser and is about to submit a patch.

Rubocop on [test](http://ci.theforeman.org/job/test_develop_pull_request/14320/) passes, would you like me to pin it to 2.3.0.0 specifically?

**Comment by dLobatog** [comment]
2.3.0.2 is good too, the issue is that they tried to introduce a cache for line reading in parser on 2.3.0.3 - https://github.com/whitequark/parser/commit/1779727b6ab8bf48c2769b82e0ca96928531a55b but the hash is not initialized under some conditions, hence it fails.

**Comment by domcleal** [comment]
Yes, pinning to a more specific version would be better (.2 preferably), it's slightly unclear to me what `2.3` means otherwise.

**Comment by shlomizadok** [comment]
Done. Thanks for the input.

**Comment by dLobatog** [comment]
https://github.com/whitequark/parser/pull/271 has been filed now, will merge if green, thanks @shlomizadok

**Comment by dLobatog** [comment]
Rubocop is green, don't think we need to wait for tests to finish as this gem is exclusively used by Rubocop.

**Comment by dLobatog** [comment]
Merged as 9dfe1feb6f817c3d266da0c7446cc032e331203d, thanks @shlomizadok!

**Comment by dLobatog** [comment]
http://ci.theforeman.org/job/test_develop_pull_request/14321/

**Pull request closed without merging**
