### PR TITLE
Refs #7719 - explicitly create .ssh dir in home

### PR DESCRIPTION
**Pull request by lzap**
A simple patch that adds extra dir. SPEC change will follow.

### CODE REVIEW

**Comment by lzap** [comment]
Ok I don't think it is necessary to change the SPEC file, it recursively adds it:

```
%files
%defattr(-,root,root,0755)
%doc README.md
%doc VERSION
%doc LICENSE
%exclude %{_datadir}/%{name}/bundler.d/*
%{_datadir}/%{name}
%{_datadir}/%{name}/plugins
%exclude %{_datadir}/%{name}/app/assets
%{_initrddir}/%{name}
%{_sbindir}/%{name}-debug
%{_sbindir}/%{name}-rake
%{_sbindir}/%{name}-tail
%{_mandir}/man8
```

**Comment by lzap** [comment]
When merging make sure this one gets into the build as well: https://github.com/theforeman/foreman-selinux/pull/36

**Comment by domcleal** [comment]
Just a few thoughts off the top of my head:
- ownership needs to be foreman
- mode needs to be restricted
- Debian package needs checking
- I'm not really convinced this should be in core, it's a packaging extra as it's linked to the foreman _user_ not the application

**Comment by lzap** [comment]
Right, all fixed except Debian. Taking look, no clue how to do this (owner, permissions) there...

http://koji.katello.org/koji/taskinfo?taskID=168349

**Comment by lzap** [comment]
Sorry the link above belongs to https://github.com/theforeman/foreman-packaging/pull/381

**Comment by domcleal** [comment]
Merged as 016e15c for Foreman 1.7, thanks @lzap.

**Pull request closed without merging**
