### PR TITLE
Fixes #33781 - deprecate non-DSL setting definitions

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Deprecate class definition settings.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej !

**Review by tbrisker — DISMISSED** [review]
Looks like katello settings need to be updated to the DSL first

**Comment by ezr-ondrej** [comment]
> Looks like katello settings need to be updated to the DSL first

Surprisingly enough it complains about foreman-tasks settings, but probably just because it's first in line.
Anyways I've done tasks https://github.com/theforeman/foreman-tasks/pull/659, tho Katello I'll try to find someone for the job :)

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by ekohl** [comment]
@ezr-ondrej this is green. Should this go into 3.2 or do you want to postpone to 3.3?

**Comment by ezr-ondrej** [comment]
> @ezr-ondrej this is green. Should this go into 3.2 or do you want to postpone to 3.3?

I'd love this to get into 3.2 as I'd like to remove this in 3.3

**Review by ekohl — APPROVED** [review]
Looks like Katello has been fixed so I'm merging this now.

**Pull request merged**
