### PR TITLE
Fixes #25994 - drop puppet run

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@tbrisker would it be possible to deprecate in 1.21? I know it would be last second change but would save us 3 months of waiting.

**Review by ekohl — COMMENTED** [review]
The jq.json file is odd

**Comment by mmoll** [comment]
@ares please rebase and remove the jq.json file :)

**Comment by ekohl** [comment]
There was a discussion at https://community.theforeman.org/t/dropping-run-puppet-button-with-a-replacement-using-remote-execution-plugin/12781.

@ares what's the plan with this?

**Comment by ares** [comment]
I have update the thread. There was a progress on user input side, that would make it work also for mco/choria users. I no longer have time to finish this (maybe next fosdem? :) Therefore I'm closing for now. I'd be happy if we get rid of this at some point though.

**Pull request closed without merging**
