### PR TITLE
Fixes #12326 - make sure host status is always loaded

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
I'm struggling to reproduce this.  I have an empty plugin, which has app/models/host_status/foo.rb, I enabled cache_classes and every time, the host_status.rb in core gets loaded before my foo.rb in the engine.

Do you have something that's triggering a load of the engine's host status during engine initialisation too?

**Comment by ares** [comment]
The reproduced is this PR https://github.com/theforeman/foreman_remote_execution/pull/42 on remote execution plugin. Could you paste your foo.rb a engine.rb? If you define it like

``` ruby
module HostStatus
  class Foo < HostStatus::Status
  end
end
```

and load it in engine in initializer with `after: :finisher_hook` with `register_custom_status HostStatus::Foo`

it should fail

EDIT: sorry, the PR was already fixed to define status like `class HostStatus::ExecutionStatus < HostStatus::Status`, maybe I could find some jenkins test failure from previous version if needed

**Comment by domcleal** [comment]
I had forgotten to add the register_custom_status line into engine.rb, but even with that I'm unable to reproduce it.  My foo.rb matches your suggestion.

I see that Rails is reading engine.rb, coming across HostStatus::Foo in the register line and then loading host_status.rb from Foreman core in response - so it's not loading foo.rb first.

<pre>
/home/dcleal/code/foreman/foreman/app/models/host_status.rb:1:in `&lt;top (required)>'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:359:in `require_or_load'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `each'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `const_missing'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:514:in `load_missing_constant'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `each'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `const_missing'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:514:in `load_missing_constant'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `each'
/home/dcleal/.rvm/gems/ruby-2.0.0-p353@foreman/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:190:in `const_missing'
/home/dcleal/code/foreman/foreman_test/lib/foreman_test/engine.rb:66:in `block in <class:Engine>'
</pre>

My only thought is that foo.rb is being required from somewhere before the initialiser's run.

Here's the plugin - you have push permission on the repo to fix/break it! https://github.com/domcleal/foreman_test_12326.  Sorry to waste your time on this.

**Comment by dLobatog** [comment]
I'm not able to reproduce this with https://github.com/theforeman/foreman_remote_execution/pull/42 `execution_status.rb` either, `host_status.rb` loads first, then `host_statuses/status.rb`, then `foo.rb` (from the test plugin @domcleal wrote), then `execution_status.rb`. Tested with branches master of foreman_remote_execution and develop of foreman.

**Comment by ares** [comment]
rex PR was already fixed, I'll try to "break" Dom's plugin when I have chance, if you can't reproduce, we can probably remove 1.10 label, I won't to get to it anytime soon (>1 month)

**Comment by tbrisker** [comment]
@ares ,
Thank you very much for your efforts!
This PR has been open for a very long time with no activity.
Please indicate if you plan to continue working on it or not; if not, feel free to close it.
If you do not respond either way within a couple of weeks, I will assume this PR is abandoned and will go ahead and close it for you.

**Comment by ares** [comment]
I'm sorry for inactivity, it wasn't high prio but it's still on my radar. I'm closing until I get to it.

**Comment by ares** [comment]
I was not able to reproduce anymore.

**Pull request closed without merging**
