### PR TITLE
Fixes #23961 - Update Foreman Fog-Vsphere select_nic method.

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Review by timogoebel — CHANGES_REQUESTED** [review]
Nice, this is missing the version bump of `fog-vsphere` (and a new release).

**Comment by chris1984** [comment]
Yep, once the new version is released I will update the gem spec. TY again.

**Comment by chris1984** [comment]
[test]

**Comment by chris1984** [comment]
@timogoebel updated with the new gem version for when you release.

**Review by dLobatog — CHANGES_REQUESTED** [review]
WoC until new version of fog-vsphere is released

**Comment by chris1984** [comment]
[test foreman]

**Review by timogoebel — APPROVED** [review]
fog-vsphere 2.3.0 was just released. Good to go.

**Comment by timogoebel** [comment]
@dLobatog: Ok for you as well?
@tbrisker: Is this before or post-branching?

The fog-vsphere release fixes two bugs (small changes) and speeds up network interface listing (this is a rather large change).

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test upgrade]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
@tbrisker here are the 2 packaging prs:

https://github.com/theforeman/foreman-packaging/pull/2729

https://github.com/theforeman/foreman-packaging/pull/2731

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Personally I've never seen fog-vsphere causing any packaging troubles, so I'd go with merging no matter how close we  are to 1.19. @tbrisker as you mentioned on https://community.theforeman.org/t/1-19-branching-in-core-heads-up/10048/8 , feel free to make the final call

**Review by tbrisker — APPROVED** [review]
Ack, packaging side has been merged, we discussed this yesterday.

**Pull request merged**
