### PR TITLE
[cp] Fixes #23991 - rephrase RSS setting description

### PR DESCRIPTION
**Pull request by amirfefer**
cherry picked from commit [e4df3b8](https://github.com/theforeman/foreman/commit/e4df3b804f5cf3c0633dd7e6acbf78d523a06884)

### CODE REVIEW

**Review by tbrisker — DISMISSED** [review]
This is a string change that will break translations. String changes shouldn't be cherry picked to older versions.

**Comment by ares** [comment]
How is this supposed to be fixed in that case? Or is it too late for 1.18?

**Comment by amirfefer** [comment]
could we fix the translation in this case?

**Comment by amirfefer** [comment]
@waldenraines - FYI

**Comment by ares** [comment]
> could we fix the translation in this case?

do you know how to translate that in all translated languages? :-)

**Comment by tbrisker** [comment]
@ares looking in transifex looks like the new string is translated at least in some languages, so we might be able to pull it in to 1.18 after all. @xprazak2 - do you think it's ok or did you pull translations already?

**Comment by xprazak2** [comment]
[test foreman]

I haven't pulled the translations yet, so I think we should be ok when we merge and I do that afterwards.

**Pull request merged**
