### PR TITLE
fixes #2981 - adding plugins repo to foreman-release

### PR DESCRIPTION
**Pull request by lzap**
SSIA

http://koji.katello.org/koji/taskinfo?taskID=58374

### CODE REVIEW

**Comment by lzap** [comment]
FYI this is the content from above build:

```
[foreman-plugins]
name=Foreman plugins nightly
baseurl=http://yum.theforeman.org/plugins/nightly/el6/$basearch
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman

[foreman-plugins-source]
name=Foreman plugins nightly - source
baseurl=http://yum.theforeman.org/plugins/nightly/el6/source
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman
```

**Comment by domcleal** [comment]
:+1: looks good, thanks.  Could you please bump %changelog/release?  (you'll need to rebase on develop, I bumped it earlier today)

**Comment by lzap** [comment]
Rebased, pushed.

**Comment by domcleal** [comment]
Thanks @lzap, merged as 648a248.

**Pull request closed without merging**
