### PR TITLE
Fixes #12034 - scope nics to validate uniqueness against

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
Hehe [#12034](http://projects.theforeman.org/issues/12034) fixes [#11034](http://projects.theforeman.org/issues/11034), I hope there won't be #13034 needed for this one :-)

**Comment by dLobatog** [comment]
Merged as 5863e065915980199b529562d1820017f57d3ad3, thanks @ares!

**Comment by lzap** [comment]
Discovery creates all interfaces as Managed, I wonder if it's the time to create our own NIC type.

**Comment by ares** [comment]
@lzap I don't think that would be a good idea, think about how hard is converting Host::Discovered to Host::Managed during provisioning, you'd have to do the same with nics... I thought discovered interface were untouched since they are imported as unmanaged (managed: false). Unfortunately but luckilly it does not have anything to do with the class name.

**Pull request closed without merging**
