### PR TITLE
Fixes #26910 - problem with import new parameters from puppet manifests

### PR DESCRIPTION
**Pull request by leagueofsoups**
problem with condition

### CODE REVIEW

**Comment by mmoll** [comment]
ok to test

**Comment by xprazak2** [comment]
[test foreman]
[test katello]
[test upgrade]

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Comment by timogoebel** [comment]
@leagueofsoups: Do you mind explaining your use case of this? It's a pretty ancient feature and we'll probably remove it soon [unless somebody convinces us not to do it](https://community.theforeman.org/t/deprecate-rake-tasks-for-puppet-import/14099/4).

**Comment by leagueofsoups** [comment]
@timogoebel I'm migrate to "hammer", and do not use rake tasks now.

**Pull request merged**
