### PR TITLE
Fixes #37069 - Fallback to UTC on invalid timezone

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by sbernhard** [comment]
Nice PR for the 10.000 PR :-)

**Comment by evgeni** [comment]
[test katello]

**Review by adamruzicka — APPROVED** [review]
Nice and clean, as the 10000th pr should be

**Comment by adamruzicka** [comment]
[test katello] for a good measure

**Comment by adamruzicka** [comment]
The only failure in katello test suite is
```
[2024-03-15T11:49:44.233Z] unsatisfied expectations:
[2024-03-15T11:49:44.233Z] - expected exactly once, invoked twice: #<Katello::Api::V2::ContentViewVersionsController:0x8cca80>.async_task(Actions::Katello::ContentView::Promote, #<Katello::ContentViewVersion:0x8ccb70>, [#<Katello::KTEnvironment:0x8ccb98>], false, nil)
```
It can't possibly be caused by this change, merging.

**Comment by adamruzicka** [comment]
Thank you @ofedoren and sorry for the wait

**Pull request merged**
