### PR TITLE
Refs #22979 - Robottelo tests attr - operating_systems

### PR DESCRIPTION
**Pull request by ldjebran**
Related robottelo issues:
SatelliteQE/robottelo#6125
https://github.com/SatelliteQE/robottelo/issues/5840

update to PR: https://github.com/theforeman/foreman/pull/5346

Port robottelo tier1 tests for organization part of robottelo minitest port project: https://github.com/SatelliteQE/robottelo/projects/1

### CODE REVIEW

**Comment by lzap** [comment]
Hey, I opened discussion about need of such UUIDs: https://community.theforeman.org/t/on-uuids-in-tests/10347

**Comment by ares** [comment]
Failures seems unrelated, katello seems to have problems with rubocop. @lzap does that mean that you don't want this to be merged before the thread is resolved? The reply from @ldjebran hopefully explains the purpose.

**Comment by lzap** [comment]
The discussion is ongoing, this is trivial to rebase let's wait a bit.

**Comment by ldjebran** [comment]
rebased

**Comment by ldjebran** [comment]
@tbrisker rebased and removed ids

**Review by tbrisker — APPROVED** [review]
Thanks @ldjebran !

**Pull request merged**
