### PR TITLE
Fixes #27109 - sync freeipa snippet

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by timogoebel** [comment]
Doesn't the syncing happen during release prep?

**Comment by ares** [comment]
It does for sure, but there's no reason no to sync in between, especially if we need to fix something in nightlies. I'd even say we should sync on daily/weekly basis, otherwise we don't test template changes until the release process starts, leading to bugs found only during stabilization phase. I took this separately since I know we'll need to cherry-pick this fix, but there are more changes pending sync (I can open separate PR)

**Comment by ares** [comment]
any chance this can go in? `Api::V2::RealmsControllerTest.test_0009_should get realms for location only` is probably unrelated, the change was reviewing in community templates repo already (by @lzap)

**Review by tbrisker — APPROVED** [review]
Thanks @ares , we did start discussing how we can improve the sync process in https://community.theforeman.org/t/provisioning-templates-testing-separate-repository/13654 but i think we didn't reach any final conclusions. any improvements in this regard are welcome.

**Pull request merged**
