### PR TITLE
Fixes #5169 - Error in smart class param or value cause tab header to turn red...

### PR DESCRIPTION
**Pull request by orrabin**
... in Puppet Class edit form

### CODE REVIEW

**Comment by dLobatog** [comment]
is how this PR looks. 

It's ready to merge in my opinion, but tests are red for some reason, in my setup (:gem: 2.0.0, MariaDB). tests are green. Let's re-kick the tests see what happens... [test]

**Comment by ohadlevy** [comment]
Any idea why the js highlight does not work? Does the extra error checks
generate extra SQL?

**Comment by orrabin** [comment]
@eLobato tests on Jenkins are failing because of two controllers that have nothing to do with this PR. 
This has been happening since yesterday on all PRs

**Comment by orrabin** [comment]
@ohadlevy not sure I understand correctly, if you are talking about `application.js` the highlight isn't working because there is no `form-group` in `smart-vars` tab to add the `class="has-error"` , the js searches for: 

``` javascript
 $(".tab-content").find(".form-group.has-error")
```

I could use it for smart class parameters but I wanted them to be the same.
Also, even if I did use it I'd still have to add the `has-error` class that would turn into `tab-error` (because the way this form is built).

As for the extra sql,  the errors are not on the puppetclass itself (not on the form builders object) so I couldn't find a better way to find the errors then

``` ruby
if @puppetclass.class_params.any? { |param| param.errors.any? }
```

If you have a better way I'd be glad to change this, I don't like the fact that the form needs to check`@puppetclass.class_params.each`  twice - once for errors and once to show all of them (the same goes for `@puppetclass.lookup_keys`.

**Comment by dLobatog** [comment]
[test]

**Comment by orrabin** [comment]
@ohadlevy I fixed `application.js` so the highlight will work. The focus on the first error tab still doesn't work in puppetclasses edit form

**Comment by orrabin** [comment]
@ohadlevy ping?

**Comment by orrabin** [comment]
@eLobato ping? this needs re-review and re testing

**Comment by dLobatog** [comment]
It's fine in my opinion, merging..

**Comment by dLobatog** [comment]
Merged as 3d42bbe5af6ff5201e127ffd5681e9ffb330f909, thanks @orrabin . It doesn't focus on the failing element as far as I can see though, so if you could open a redmine issue and fix that, it'd be great. Thanks @orrabin !

**Pull request closed without merging**
