### PR TITLE
Fixes #29317 - Add title to login page

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test foreman]

**Review by amirfefer — COMMENTED** [review]
The Login page is already a react component.
How about using [react-helmet](https://github.com/nfl/react-helmet) which simply adds tags to the head 

```js
 <Helmet>
     <title> __(Login) </title>
</Helmet>
```
we use it already in [katello](https://github.com/Katello/katello/blob/bc7a371aa24d2842a0ca0c8c4cd725fb7fd001be/webpack/containers/Application/Headers.js) and sooner or later we'll need it in foreman :)

**Comment by sbernhard** [comment]
> The Login page is already a react component.
> How about using [react-helmet](https://github.com/nfl/react-helmet) which simply adds tags to the head
> 
> ```js
>  <Helmet>
>      <title> __(Login) </title>
> </Helmet>
> ```
> 
> we use it already in [katello](https://github.com/Katello/katello/blob/bc7a371aa24d2842a0ca0c8c4cd725fb7fd001be/webpack/containers/Application/Headers.js) and sooner or later we'll need it in foreman :)

What would be the advantage to use react for this change? This is just one line of code to set the title which is currently missing (even in satellite - I guess).

**Comment by amirfefer** [comment]
At the moment `Login Page` is based on react but still use erb for mounting, when we will move it to react-router, it needs a different mechanism for rendering title because it won't use the layout anymore.

I've made https://github.com/theforeman/foreman/pull/7505/ , don't mind to merge this for now :)

**Comment by sbernhard** [comment]
Thanks for the explanation @amirfefer

**Review by tbrisker — APPROVED** [review]
Thanks @sbernhard ! merging for now as is, feel free to update to use Helmet in the future.

**Pull request merged**
