### PR TITLE
Fixes #32391 - change alignment from inline to inline-block

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Comment by adiabramovitch** [comment]
[kattelo test]

**Comment by adiabramovitch** [comment]
[katello test]

**Comment by adiabramovitch** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
Katello failure is irrelevant and no reason to wait for those test to pass on this PR :)

**Review by ezr-ondrej — APPROVED** [review]
Nice and simple, thanks @adiabramovitch  :+1:

**Pull request merged**
