### PR TITLE
Fixes #32928 - Allow templates to hide preview button

### PR DESCRIPTION
**Pull request by ofedoren**
SSIA :)

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @ofedoren !

**Comment by lzap** [comment]
I requested 2.5 CP for this one, can we get a confirmation yes/no before we commit to a webhook patch?

**Comment by tbrisker** [comment]
@lzap looks safe enough, feel free to open a CP PR

**Comment by ofedoren** [comment]
CP 2.5: https://github.com/theforeman/foreman/pull/8726

**Pull request merged**
