### PR TITLE
Fixes #29390 - Unpin pry-byebug

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Review by mmoll — APPROVED** [review]

**Review by tbrisker — APPROVED** [review]
thanks @orrabin and @mmoll !

**Comment by tbrisker** [comment]
2.0- eb69ae528

**Comment by amirfefer** [comment]
I still have an issue,  only removing `pry-byebug` works :/

**Comment by tbrisker** [comment]
@amirfefer did you run `bundle update`?

**Pull request merged**
