### PR TITLE
fixes #6888 - remove duplicate presence validator causing two errors

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1:

**Comment by lzap** [comment]
Fine with merging without testing that? This is covered by our unit tests.

**Comment by domcleal** [comment]
Up to you, you probably could have tested it in the time it took us to write this :)

**Comment by lzap** [comment]
And it works.

Thanks Dom, merged as 51b90bf

**Pull request closed without merging**
