### PR TITLE
fixes 2602 - scoped_search error when using postgresql

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
@isratrade there are test failures on SQLite and PostgreSQL with this patch, could you investigate please?

<pre>
  1) Failure:
test_0008_anonymous(Api::V1::ConfigTemplatesControllerTest) [/var/lib/workspace/workspace/test_develop_pull_request/database/sqlite3/puppet/3.0/ruby/1.9.3/test/functional/api/v1/config_templates_controller_test.rb:60]:
Expected response to be a <:ok>, but was <422>
  2) Failure:
test_0008_anonymous(Api::V2::ConfigTemplatesControllerTest) [/var/lib/workspace/workspace/test_develop_pull_request/database/sqlite3/puppet/3.0/ruby/1.9.3/test/functional/api/v2/config_templates_controller_test.rb:60]:
Expected response to be a <:ok>, but was <422>
  3) Failure:
test_destroy(ConfigTemplatesControllerTest) [/var/lib/workspace/workspace/test_develop_pull_request/database/sqlite3/puppet/3.0/ruby/1.9.3/test/functional/config_templates_controller_test.rb:87]:
Failed assertion, no message given.
  4) Failure:
test_destroy_json(ConfigTemplatesControllerTest) [/var/lib/workspace/workspace/test_develop_pull_request/database/sqlite3/puppet/3.0/ruby/1.9.3/test/functional/config_templates_controller_test.rb:95]:
Expected response to be a <:ok>, but was <422>
</pre>

**Comment by isratrade** [comment]
@domcleal, I will squash the new commit if all passes.  I have no idea my removing LOWER() would cause test failure on destroy for example.

**Comment by domcleal** [comment]
Hmm, if it passes again, do you think removing LOWER() from compute resources etc could introduce an issue?  Perhaps one we're not testing for?

**Comment by isratrade** [comment]
@domcleal, it's hard to imagine that the order scope would cause any failures, unless .first or .last is assumed to be a particular fixture and now it's not.  The "worst" side effect that I would expect is that postgres does not correctly sort alphabetically since it's case sensitive, meaning it sorts a-z, A-Z.

apple
orange
Banana

**Comment by isratrade** [comment]
@domcleal, the above appears to be the reason.

``` ruby
  test "should destroy" do
    config_template = ConfigTemplate.first
```

**Comment by domcleal** [comment]
Ah, gotcha.  Let's see if the tests pass this time then!

**Comment by isratrade** [comment]
@domcleal, passed for 2.0 but failed for 1.9.3 or 1.8.7 with "no failures" again??

**Comment by domcleal** [comment]
Check the console output for tests and it shows errors with rubygems.org, which went down to today.  Let's [test] again.

**Comment by isratrade** [comment]
@domcleal, re-based and re-pushed

**Comment by isratrade** [comment]
@domcleal, tests passed so I squashed the commits of the config_template tests

**Comment by domcleal** [comment]
Thanks @isratrade, merged as 93ce3a1.

**Pull request closed without merging**
