### PR TITLE
Fixes #12452 - Enable non admin users to do bulk actions on hosts

### PR DESCRIPTION
**Pull request by alongoldboim**

### CODE REVIEW

**Comment by domcleal** [comment]
Wouldn't it be better to fix the ambiguity in the query by specifying the table name rather than removing the optimisation?  See `find_multiple` in hosts controller.

**Comment by alongoldboim** [comment]
Im not getting n+1 even when removing it though, i could do it over there as well, you prefer that?

**Comment by domcleal** [comment]
How are those associations loaded if not using .includes?

**Comment by alongoldboim** [comment]
@domcleal changes made in find_multiple solves the problem.

**Comment by alongoldboim** [comment]
Tests are failing, checking the problems

**Comment by alongoldboim** [comment]
@domcleal tests are passing, working properly.

**Comment by domcleal** [comment]
Could you add a functional test for this PR to demonstrate the bug?  I would have thought it's probably from taxonomy/org/loc contexts rather than specifically a non-admin user, which should be easy to reproduce.

**Comment by alongoldboim** [comment]
@domcleal  when I use an admin user with a specific org/loc I don't get the error (not only when I'm on any context) so how can I check if it is in fact related to taxonomy? the `.to_sql` is the same for both types of users but for admin it succeeds.

**Comment by domcleal** [comment]
I'm not sure then, the current context was the only idea I had from the SQL query in the bug report.  I can't think of anything off the top of my head that would be different between the two apart from authorisation, but it's unclear from the report whether that's in effect.  Write a test and compare?

**Comment by alongoldboim** [comment]
@domcleal Removed assoc from the view, 1 to 1 assoc don't need to use includes in rails.

**Comment by domcleal** [comment]
> @domcleal Removed assoc from the view, 1 to 1 assoc don't need to use includes in rails.

This seems to be back to square one, where this PR removes the optimisation added in d5896a1.

While I quite agree that you don't need to use includes, it's there to prevent individual records being retrieved when associations are accessed by preloading them.  This is quite clear when comparing the SQL logs:

<pre>
2015-11-30T12:37:02 [app] [I] Started GET "/hosts/select_multiple_hostgroup?host_ids%5B%5D=110&host_ids%5B%5D=109&host_ids%5B%5D=170&host_ids%5B%5D=82&host_ids%5B%5D=168&host_ids%5B%5D=118" for 127.0.0.1 at 2015-11-30 12:37:02 +0000
2015-11-30T12:37:03 [app] [I] Processing by HostsController#select_multiple_hostgroup as HTML
2015-11-30T12:37:03 [app] [I]   Parameters: {"host_ids"=>["110", "109", "170", "82", "168", "118"]}
2015-11-30T12:37:03 [sql] [D]    (0.2ms)  SELECT COUNT(*) FROM "hosts" WHERE "hosts"."type" IN ('Host::Managed') AND (id IN ('110','109','170','82','168','118') or name IN (NULL))
2015-11-30T12:37:03 [sql] [D]   Host::Managed Load (0.3ms)  SELECT "hosts".* FROM "hosts" WHERE "hosts"."type" IN ('Host::Managed') AND (id IN ('110','109','170','82','168','118') or name IN (NULL))
2015-11-30T12:37:03 [sql] [D]   Hostgroup Load (0.2ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 5 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   Environment Load (0.1ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 1 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 5 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   Environment Load (0.2ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 2 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [sql] [D]   Hostgroup Load (0.3ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 6 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 1 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 6 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 1 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 5 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 1 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "hostgroups".* FROM "hostgroups" WHERE "hostgroups"."id" = 6 ORDER BY hostgroups.title LIMIT 1
2015-11-30T12:37:03 [sql] [D]   CACHE (0.0ms)  SELECT "environments".* FROM "environments" WHERE "environments"."id" = 1 ORDER BY environments.name LIMIT 1
2015-11-30T12:37:03 [app] [I]   Rendered hosts/_selected_hosts.html.erb (436.1ms)
[..]
2015-11-30T12:37:05 [app] [I] Completed 200 OK in 1685.2ms (Views: 1487.9ms | ActiveRecord: 3.1ms)
2015-11-30T12:37:05 [app] [W] user: dcleal
 | http://0.0.0.0:3000/hosts/select_multiple_hostgroup?host_ids%5B%5D=110&host_ids%5B%5D=109&host_ids%5B%5D=170&host_ids%5B%5D=82&host_ids%5B%5D=168&host_ids%5B%5D=118
 | N+1 Query detected
 |   Host::Managed => [:hostgroup]
 |   Add to your finder: :includes => [:hostgroup]
 | N+1 Query method call stack
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:24:in `block in _app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:20:in `_app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/select_multiple_hostgroup.html.erb:1:in `_app_views_hosts_select_multiple_hostgroup_html_erb___3528782661295736821_80400480'
 |   /home/dcleal/code/foreman/foreman/app/controllers/concerns/application_shared.rb:13:in `set_timezone'
 |   /home/dcleal/code/foreman/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 |   /home/dcleal/code/foreman/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call'
 | 
 | /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:24:in `block in _app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 | /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:20:in `_app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 | /home/dcleal/code/foreman/foreman/app/views/hosts/select_multiple_hostgroup.html.erb:1:in `_app_views_hosts_select_multiple_hostgroup_html_erb___3528782661295736821_80400480'
 | /home/dcleal/code/foreman/foreman/app/controllers/concerns/application_shared.rb:13:in `set_timezone'
 | /home/dcleal/code/foreman/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 | /home/dcleal/code/foreman/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call'
2015-11-30T12:37:05 [app] [W] user: dcleal
 | http://0.0.0.0:3000/hosts/select_multiple_hostgroup?host_ids%5B%5D=110&host_ids%5B%5D=109&host_ids%5B%5D=170&host_ids%5B%5D=82&host_ids%5B%5D=168&host_ids%5B%5D=118
 | N+1 Query detected
 |   Host::Managed => [:environment]
 |   Add to your finder: :includes => [:environment]
 | N+1 Query method call stack
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:25:in `block in _app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:20:in `_app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 |   /home/dcleal/code/foreman/foreman/app/views/hosts/select_multiple_hostgroup.html.erb:1:in `_app_views_hosts_select_multiple_hostgroup_html_erb___3528782661295736821_80400480'
 |   /home/dcleal/code/foreman/foreman/app/controllers/concerns/application_shared.rb:13:in `set_timezone'
 |   /home/dcleal/code/foreman/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 |   /home/dcleal/code/foreman/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call'
 | 
 | /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:25:in `block in _app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 | /home/dcleal/code/foreman/foreman/app/views/hosts/_selected_hosts.html.erb:20:in `_app_views_hosts__selected_hosts_html_erb___3706601346162922857_97029440'
 | /home/dcleal/code/foreman/foreman/app/views/hosts/select_multiple_hostgroup.html.erb:1:in `_app_views_hosts_select_multiple_hostgroup_html_erb___3528782661295736821_80400480'
 | /home/dcleal/code/foreman/foreman/app/controllers/concerns/application_shared.rb:13:in `set_timezone'
 | /home/dcleal/code/foreman/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 | /home/dcleal/code/foreman/foreman/lib/middleware/catch_json_parse_errors.rb:9:in `call'
</pre>

I'd suggest going back to the second version of this PR that simply fixed the column ambiguity through using the table name, then add the test to demonstrate the bug.

**Comment by alongoldboim** [comment]
@domcleal testing this is a bit tricky because the includes happens in the view, while doing functional tests I don't think views are rendered hence i wont get the error, I can change the whole functionality and move the includes into the controller for the needed actions (then it will be testable) or we can leave it like that (then we could just use the trivial fix and not checking it).

**Comment by domcleal** [comment]
Yes, it still needs a test.  If you need to move the includes, that's easy enough isn't it?  No need to change the "whole functionality"!

**Comment by alongoldboim** [comment]
hehe, will do.

**Comment by alongoldboim** [comment]
@domcleal test added.

**Comment by domcleal** [comment]
Merged as 935bc24, thanks @alongoldboim.

(Squashed both commits, please do that next time.)

**Pull request closed without merging**
