### PR TITLE
fixes #3646 - API v2 change default root name for api json single object response to no root node but make it configurable

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
Some test failures, but otherwise looks good.

**Comment by isratrade** [comment]
recommitted with tests fixed

**Comment by isratrade** [comment]
@komidore64, this PR for single object response changes to 'root_name' so now it's consistent with collections or single objects.  Can you update the manual accordingly?  Thanks.

**Comment by domcleal** [comment]
Thanks @isratrade, merged as 15d9132!

**Pull request closed without merging**
