### PR TITLE
fixes #18574 - add ip6 address to the REST api results

### PR DESCRIPTION
**Pull request by jovandeginste**
fixes #18574 - add ip6 address to REST api

### CODE REVIEW

**Comment by mmoll** [comment]
ok to test

**Comment by timogoebel** [comment]
@jovandeginste : Thanks, could you please file a redmine issue for this?

**Comment by jovandeginste** [comment]
@timogoebel I did, #18574 (see the original message, I edited it yesterday)

**Comment by timogoebel** [comment]
@jovandeginste : Merged, thanks! And sorry I missed the ticket ;-)

**Comment by jovandeginste** [comment]
No problem! It's a weird omission, however...

**Pull request merged**
