### PR TITLE
Fixes #11389 - Remove API v1

### PR DESCRIPTION
**Pull request by tbrisker**
API v1 has been deprecated since Foreman 1.9 - over 2 years ago.
This is more then enough time for anyone needing to migrate to v2.
Even though the original issue requests extraction to a plugin, I do not
see any point in investing the time and effort to maintain a long
deprecated API.

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
SGTM

**Comment by lzap** [comment]
I am all for dropping it but I remember @ohadlevy preferred putting this into plugin. But frankly, I only agree with this if there is someone committed to maintain the plugin for several releases. Anyway possible plugin is not part of this PR, so +1 for me.

**Comment by tbrisker** [comment]
If anyone wishes to make a plugin they are more then welcome too - that doesn't mean we can't drop it from core until it exists. TBH I don't think there would be much demand for supporting this api considering how old v2 is already - and anyone still using v1 is most likely also still using an older version of Foreman.

**Comment by tbrisker** [comment]
@xprazak2 As the release manager for 1.17 you should make the call if this should go in before or after branching.

**Review by lzap — APPROVED** [review]
I agree let's merge it.

**Comment by xprazak2** [comment]
I have no objections against merging this before 1.17 branches, it does not affect packaging as far as I can see.

**Comment by tbrisker** [comment]
@xprazak2 if we want to try and maintain semver and merge this into 1.17 i think that means 1.17 should be 2.0.

**Comment by ares** [comment]
I think there was no clear agreement on 1.17 being 2.0. I was hoping to have a big warning that api v1 is being dropped in 1.17 release notes and merge this just after branching.

**Comment by ares** [comment]
this needs rebasing now

**Comment by tbrisker** [comment]
@ares thanks, rebased

**Review by mmoll — APPROVED** [review]
Let's merge this, now that 1.17 is branched.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
In case anybody cares to put this into a plugin, let me point you to a starter: https://github.com/unorthodoxgeek/foreman_v1

**Comment by tbrisker** [comment]
@mmoll @timogoebel @lzap @ares - looks like there is consensus to drop it, who wants to do the honors? I added the task of indicating in 1.17 docs that it is the last version supporting apiv1 - https://github.com/theforeman/theforeman.org/issues/974

**Comment by timogoebel** [comment]
Merged, thanks @tbrisker.

Now we have plenty of room for a new graphql api! 👍

**Pull request merged**
