### PR TITLE
Fixes #22724 - Update patternfly-react

### PR DESCRIPTION
**Pull request by sharvit**
* update and pin patternfly-react to v1.11.0
* update tests snapshots

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you fix the typo in the commit message?

Packaging PR: https://github.com/theforeman/foreman-packaging/pull/2239

**Review by ohadlevy — COMMENTED** [review]
Should we pin pf-react going forward to avoid snapshot failing?

**Comment by sharvit** [comment]
@ekohl fixed!

@ohadlevy yes let's do that and update manually until we will migrate our tests :+1: 
pinned on version `1.11.0` for now

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
this PR fixes travis tests, merging regardless of the failure in webpack jenkins build.

**Pull request merged**
