### PR TITLE
add an IAM role field to a compute image, to allow use of IAM to control...

### PR DESCRIPTION
**Pull request by isratrade**
... access to AWS services within an instance.

This is a refactor of pull request #160 by @pccowboy 

@ohadlevy, if you merge this pr, change the author to @pccowboy

### CODE REVIEW

**Comment by ohadlevy** [comment]
thanks @isratrade, would you mind adding a couple of tests?

**Comment by ohadlevy** [comment]
this looks good, but I'm unable to test it ( i don't have the correct account, can anyone give it a try?)

**Comment by pccowboy** [comment]
Hmmm, not sure how "pure" my dev server is, but I will try and merge this in, and see that it still works as expected in our environment.  I will be back in the office tomorrow.

**Comment by pccowboy** [comment]
@isratrade - thanks for resurrecting this!

**Comment by ohadlevy** [comment]
merged - @isratrade @pccowboy thanks!

**Pull request closed without merging**
