### PR TITLE
Fixes #29387 - don't try to import blank domain or OS

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Wait, no, the blank? guard is required, but it shouldn't revert the ignore

**Comment by evgeni** [comment]
`unless ignore || blank?` is what I need (talking to myself)

**Comment by ShimShtein** [comment]
@evgeni, test failures are related

**Comment by ShimShtein** [comment]
@evgeni, gentle reminder... Test failures are actually related

**Comment by evgeni** [comment]
I know, but didn't have time to debug that further. Isn't "waiting on contributor" the right state for that? ;)

**Pull request closed without merging**
