### PR TITLE
Fixes #26781 - DateTimePicker placement

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Before 1920 resolution:
TimePicker-positioning
Before 1920/2 resolution:
DateTimePicker-owerflow-halfscreen
After 1920 resolution:
DateTimePicker
After 1920/2 resolution
DateTimePicker-halfscreen

### CODE REVIEW

**Comment by ares** [comment]
Nice, @MariaAga or @amirfefer any comments related to code?

**Review by MariaAga — APPROVED** [review]

**Review by Ron-Lavi — APPROVED** [review]
Thanks @ezr-ondrej, looks good !
@MariaAga I think that the main issue here is 
that the `DateTimePicker` is sometimes out of the page,
maybe this should be automatically adjusted in a future PR?

**Comment by ezr-ondrej** [comment]
> @MariaAga I think that the main issue here is
> that the `DateTimePicker` is sometimes out of the page,
> maybe this should be automatically adjusted in a future PR?

I believe the support for that is not in `bootstrap-react < 1` component `Overlay`, which we are using in PF 3, so it would be a lot of work. I do not know if there is some plan to upgrade PF to `bootstrap-react ^1.0`, but if so, it would solve the problem as there the `Overlay` has placement auto :slightly_smiling_face:

**Review by ares — APPROVED** [review]
Thanks @ezr-ondrej, @Laviro and @MariaAga, merging!

**Pull request merged**
