### PR TITLE
2.5 Registration cherry-picks

### PR DESCRIPTION
**Pull request by stejskalleos**
Fixes #32918 - Host registration - Update packages 
New parameter `update_packages` for update of
all packages on the host when registered

(cherry picked from commit 198040f)

Fixes #33121 - Registration command API & params with false values
Registration API for generating registration command
incorrectly ignores parameters with `false` boolean value.

(cherry picked from commit eb03be9)

Fixes #32780 - Delete host params when register host
(cherry picked from commit fe6b364)

Fixes #33004 - Registration - Refresh subscription data
(cherry picked from commit 1d2db6e)

Fixes #33033 - shell_escape template macro 
New template macro `shell_escape` using
Ruby's `Shellwords.shellescape` for safe shell strings.
Use `shell_escape` for user input variables
in registration templates (`global` & `host_init`)

(cherry picked from commit 9c1b18f)

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
ACK, I'm ok with this.

**Comment by ezr-ondrej** [comment]
@tbrisker this also CPs the #8707, which was not marked by maintainers to CP, but it made the CP clean and its pretty safe (at least not to break anything else then registration) and also in this combination it is gona be tested by Satellite QE.

**Review by tbrisker — APPROVED** [review]

**Comment by stejskalleos** [comment]
[test katello]

**Comment by tbrisker** [comment]
katello tests don't work on stable branch as it takes develop katello, aborted them.

**Pull request merged**
