### PR TITLE
Fixes #23790 - Upgrade and pin patternfly-react

### PR DESCRIPTION
**Pull request by sharvit**
Upgrade and pin patternfly-react to v2.5.1
May fix #23721

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM :1st_place_medal:

**Review by waldenraines — APPROVED** [review]
Works for me, @tstrachota can you review please?

**Comment by tstrachota** [comment]
I tested this and it works fine. It makes sense to me to both upgrade and pin patternfly-react.
@ekohl ?

**Comment by ekohl** [comment]
I had some issues in bumping the dependencies. There is some issue in npm2rpm that tries to download d3 resources from the wrong URL. Not sure why.

**Comment by amirfefer** [comment]
it seems that `patternfly-react` uses react 16.3 as a peer dependency 
I've just opened a [PR](https://github.com/theforeman/foreman/pull/5651) in order to update to 16.3

**Review by tbrisker — APPROVED** [review]
This and https://github.com/Katello/katello/pull/7416 may fix broken katello nightlies when merged. Waiting on @ekohl to ack on the packaging side

**Comment by ekohl** [comment]
I just submitted https://github.com/dLobatog/npm2rpm/pull/42 to handle `@types/d3@5.0.0` in the dependency. After this meeting I'll submit the updated the packaging PRs.

**Comment by dLobatog** [comment]
@tbrisker We already have 2.5.1 on nightlies, or at least it's in packaging (https://github.com/theforeman/foreman-packaging/tree/rpm/develop/packages/foreman/nodejs-patternfly-react/) and foreman-assets. Even with that I'm seeing the RH repos page not loading...

```
[root@centos7-katello-nightly foreman]# cat /usr/lib/node_modules/patternfly-react/package.json
{
  "name": "patternfly-react",
  "version": "2.5.1",
  "private": false,
  "description": "This library provides a set of common React components for use with the PatternFly reference implementation.",
  "main": "dist/js/index.js",
  "module": "dist/esm/index.js",
  "sideEffects": false,
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/patternfly/patternfly-react.git"
  },
  "keywords": [
    "react",
    "patternfly"
  ],
  "author": "Red Hat",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/patternfly/patternfly-react/issues"
  },
  "homepage": "https://github.com/patternfly/patternfly-react#readme",
  "dependencies": {
    "bootstrap-slider-without-jquery": "^10.0.0",
    "breakjs": "^1.0.0",
    "classnames": "^2.2.5",
    "css-element-queries": "^1.0.1",
    "patternfly": "^3.48.0",
    "react-bootstrap": "^0.32.1",
    "react-bootstrap-switch": "^15.5.3",
    "react-c3js": "^0.1.20",
    "react-fontawesome": "^1.6.1",
    "reactabular-table": "^8.14.0",
    "recompose": "^0.26.0"
  },
  "optionalDependencies": {
    "sortabular": "^1.5.1",
    "table-resolver": "^3.2.0"
  },
  "peerDependencies": {
    "prop-types": "^15.6.0",
    "react": "^16.3.1",
    "react-dom": "^15.6.2 || ^16.2.0"
  },
  "sassIncludes": {
    "patternfly": "../../node_modules/patternfly/dist/sass",
    "bootstrap": "../../node_modules/bootstrap-sass/assets/stylesheets",
    "fontAwesome": "../../node_modules/font-awesome-sass/assets/stylesheets"
  },
  "scripts": {
    "prebuild": "yarn build:sass && yarn build:less",
    "build:less": "mkdir -p dist/less && cp -r less/* dist/less",
    "build:sass": "mkdir -p dist/sass && cp -r sass/patternfly-react/* dist/sass && node-sass --output-style compressed --include-path sass --include-path $npm_package_sassIncludes_patternfly --include-path $npm_package_sassIncludes_bootstrap --include-path $npm_package_sassIncludes_fontAwesome -o dist/css sass/patternfly-react.scss"
  }
}
```

Something interesting is that the `plugin_webpack_directories.rb` which should include Katello, REX and Ansible, returns nothing:
```
[root@centos7-katello-nightly foreman]# ./script/plugin_webpack_directories.rb
{"entries":{},"paths":[],"plugins":{}}
```

**Review by ekohl — APPROVED** [review]
Generally not a fan of this specific pinning but given we have this version in our repos, sure.

**Comment by waldenraines** [comment]
@sharvit will this need to be cherry-picked into 1.18?

**Comment by ares** [comment]
settting redmine to 1.19 for now, please change to 1.18 or keep based on the answer

**Comment by dLobatog** [comment]
I'm updating my nightly instance to test this as 3h ago the latest nightly RPM should include this - in any case I'm certain we were using 2.5.1 before the change, will update the thread if I see any changes in the behavior.

**Pull request merged**
