### PR TITLE
Fixes #24832 - Adds bootstrap-sass package

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by tbrisker** [comment]
This needs a matching PR in packaging.

**Comment by ares** [comment]
@sharvit could you please open the packaging PR? I believe @ekohl would help if needed but according to https://github.com/theforeman/foreman-packaging/tree/rpm/develop#adding-npm-packages, that should be easy task.

**Comment by mmoll** [comment]
[test foreman]
[test upgrade]

**Comment by sharvit** [comment]
https://github.com/theforeman/foreman-packaging/pull/2931

**Review by ohadlevy — APPROVED** [review]

**Comment by mmoll** [comment]
Merging already now, to unbreak DEB builds. RPMs are broken because of this anyway.

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @sharvit!

**Pull request merged**
