### PR TITLE
Fixes #25693 - Update fallback config for i18n 1.1 gem

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
If this finds approval, I'd open an update for i18n to 1.2.0 for RPMs. The alternative would be to pin it to 1.0.x.

**Comment by mmoll** [comment]
See https://github.com/svenfuchs/i18n/pull/442

**Comment by mmoll** [comment]
[test upgrade]

**Review by tbrisker — APPROVED** [review]
Makes sense to me

**Comment by mmoll** [comment]
RPM PR: https://github.com/theforeman/rails-packaging/pull/150/

I guess this change should also go into 1.20 then?

**Comment by tbrisker** [comment]
for 1.20 i think it's better to pin for debians (i assume that rpms are on 1.0 anyways?)

**Comment by mmoll** [comment]
@ehelms @ekohl Is the Rails 5.2 repo shared across Foreman versions?

**Review by ohadlevy — APPROVED** [review]

**Comment by ekohl** [comment]
@mmoll no, we have split them per version: https://yum.theforeman.org/rails/

**Comment by mmoll** [comment]
OK, then I think this should go into develop and the RPM PR merged, I'll take care of pinning i18n in older DEB builds then.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Comment by tbrisker** [comment]
@mmoll did you pin this for 1.20 debians? we're planning to do 1.20.2 this week

**Comment by mmoll** [comment]
@tbrisker Could we pin this in the -stable branch itself (`<1.1`)?

**Comment by tbrisker** [comment]
@mmoll sure, works for me. rpm uses scl which has 1.0.1 for 1.20 anyways.

**Comment by mmoll** [comment]
done.

**Pull request merged**
