### PR TITLE
fixes #9212 - using webkit headless browser in order to run Capybara tests

### PR DESCRIPTION
**Pull request by unorthodoxgeek**

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
fails because there's no QT on the CI machine. this should fix it: https://github.com/theforeman/foreman-infra/pull/151

**Comment by ShimShtein** [comment]
Is it worth considering  [poltergeist](https://github.com/teampoltergeist/poltergeist/tree/v1.6.0) as the alternative? It doesn't require QT, and it's completely headless. Based on Phantomjs

**Comment by unorthodoxgeek** [comment]
@ShimShtein - thanks! works locally, trying to see if the CI will work (if not, it will still be easier to install than QT, and I will update my puppet PR accordingly)

**Comment by unorthodoxgeek** [comment]
this is quite bizarre. test failed on ruby 2.0 / PG, passed on rest of DBs and rubies.
lets try again?
[test]

**Comment by unorthodoxgeek** [comment]
[test]

**Comment by dLobatog** [comment]
:+1: from my side, however we don't have that package nor I can find it on the SCL, submit the spec to foreman-packaging. @domcleal should this PR be blocked on packaging?

**Comment by unorthodoxgeek** [comment]
what's "that package"? I moved to the alternative Shimon offered and it
seems to work fine, no packages needed.

**Comment by domcleal** [comment]
We don't package test or development dependencies, go for it.

**Comment by dLobatog** [comment]
@unorthodoxgeek poltergeist was what I was referring to, it's not packaged but it's true it's not needed, didn't realize what @domcleal said above.

Merged as 6f49408253fe16d9f3c4d05beb92661a09aecb1f , thanks!

**Pull request closed without merging**
