### PR TITLE
Fixes #26552 - simplify autocomplete redux actions

### PR DESCRIPTION
**Pull request by Ron-Lavi**
use `AUTO_COMPLETE_INIT` instead of `AUTO_COMPLETE_SUCCESS`
fix some test fixtures and tests that were not updated.

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
needed for https://github.com/theforeman/foreman/pull/6615

**Comment by Ron-Lavi** [comment]
@theforeman/ui-ux could you take a look ?

**Review by sharvit — APPROVED** [review]
Thanks @Laviro LGTM :+1:

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @Laviro!

**Pull request merged**
