### PR TITLE
Fixes #31931 - Allow searching by id on Hosts

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Yeah that must work.

**Review by ares — APPROVED** [review]
Thank you @adamruzicka, merging!

**Comment by ares** [comment]
btw extra credit if you add this to the active record base class in separate PR, all models would benefit from this in report, job and webhook templates I believe

**Comment by adamruzicka** [comment]
> btw extra credit if you add this to the active record base class in separate PR, all models would benefit from this in report, job and webhook templates I believe

Created an issue so it doesn't get lost https://projects.theforeman.org/issues/31936

**Comment by adamruzicka** [comment]
CPs:
- [ ] 2.3 https://github.com/theforeman/foreman/pull/8347
- [ ] 2.4 https://github.com/theforeman/foreman/pull/8348

**Pull request merged**
