### PR TITLE
Fixes #23196 - Add default values for cores and socket in VM

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by lzap** [comment]
You have failures.

**Comment by shiramax** [comment]
@lzap , the tests should fail right now, 
The following PR:  https://github.com/fog/fog-ovirt/pull/16  needs to be merged first.
After it, the tests will pass.

**Comment by iNecas** [comment]
https://github.com/fog/fog-ovirt/pull/16 got merged: we should probably bump version dependency on the fog-ovirt.

**Review by tbrisker — COMMENTED** [review]
`fog-ovirt` dependency has been bumped in 04ae1269e109, tests are now green. Thanks @shiramax !

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
I didn't notice the issue had already been closed by another pr, in the future- if you are submitting a follow-up PR on the same issue please use `Refs #...` instead of `Fixes #...` in the commit message.

**Pull request merged**
