### PR TITLE
Fixes #21606 - Allow searching facts by host_id

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
test failure is intermittent and unrelated.

**Review by ares — CHANGES_REQUESTED** [review]
works well but it lists all ids in auto suggestion menu, for id values we usually add `:complete_enabled => false` too

**Comment by tbrisker** [comment]
@ares thanks, toggled complete_value to false.

**Review by ares — APPROVED** [review]

**Comment by ares** [comment]
Nice one, thanks @tbrisker, merged as c31ce1ce3f7e72ce0d4acef56e14319c6d5d14db

**Comment by ares** [comment]
interesting, github rejects my push, because of protected branch hook

**Comment by ares** [comment]
Using squash and merge, tests were green already

**Comment by ares** [comment]
new commit hash is 06b2899f008648d1fc392fa2781f95e7ed2154ec

**Pull request merged**
