### PR TITLE
Fixes #14679 - Fix tabbing of puppet CA in proxy

### PR DESCRIPTION
**Pull request by tbrisker**
The links were missing the `data-toggle="tab"` attribute, causing the
tabbing to break when using under katello.

### CODE REVIEW

**Comment by tbrisker** [comment]
Please do not merge yet, this PR only solves part of the problem. It is still broken when navigating via the dropdown button or the cards. (The issue is caused by angular preventing the firing of `hashchange` events, which is used to change tabs in those cases: https://github.com/angular/angular.js/issues/1647)

**Comment by waldenraines** [comment]
https://github.com/Katello/katello/pull/5992

**Comment by tbrisker** [comment]
Katello side is RTM, can someone from @theforeman/core please take a look at this? Once both are RTM we should merge them together. Test failure is unrelated.

**Comment by waldenraines** [comment]
Any updates on this?

**Comment by dLobatog** [comment]
I'll merge, this doesn't change anything in our side and unblocks the other PR. I wonder why that test is failing though http://ci.theforeman.org/job/test_develop_pr_core/8892/database=postgresql,label=fast,ruby=2.1/testReport/junit/%28root%29/AuditJSTest/test_0001_show_audit_with_diff/

**Comment by dLobatog** [comment]
Merged as ddbd8f72da0b3584e8810248996bf32e2b466741, thanks @tbrisker!

**Pull request closed without merging**
