### PR TITLE
Fix #3242: clarify language around import button for classes

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by domcleal** [comment]
I don't much care one way or the other (think they both read OK), but it makes a wide button even wider?

**Comment by ohadlevy** [comment]
Whats the BG for this request?

**Comment by isratrade** [comment]
I also thinks it makes the button unnecessarily wider.  If there are changes, the user is presented with which classes are new, obsolete, updated, and then needs to select which ones to submit.  The button is not 'destructive', it just presents information, so the wording is not crucial.

**Comment by skottler** [comment]
This is something that David Caplan asked to have changed. His case is that it's not an "import" in the most true sense of the word; it's not _just_ adding new classes. I've personally never found the language very confusing, but maybe that's because I've been looking at the interface every day for the last 1.5 years.

**Comment by domcleal** [comment]
Can I suggest a compromise?

Let's add a :title attribute to the button with an overall longer description which accurately describes what it does (i.e. new/updated/obsolete classes and environments).  We did something similar for the associate VM buttons to keep the labels short.

**Comment by ohadlevy** [comment]
@skottler ping?

**Comment by domcleal** [comment]
Closing due to no activity.

**Pull request closed without merging**
