### PR TITLE
WIP: Rails 5.2

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
[test katello]

**Comment by xprazak2** [comment]
Tested, seems to work ok, rebase will be needed. The foreman test failures do not look random.

**Comment by mmoll** [comment]
Rebased.

The test failure is indeed new and I didn't suceed in finding the cause, somebody with actual knowledge about the CR and keypair stuff needs to have a look. Maybe it's only a test problem (or a Rails bug).

See https://projects.theforeman.org/issues/22938 for more information.

**Comment by mmoll** [comment]
@ehelms any idea why the DB creation in the katello PR test fails here?

**Comment by ehelms** [comment]
What appears to be happening (without digging too deep) is that the plugin code is triggering this error. If you look through the stack trace when creating the database you will find it calls this line:

https://github.com/theforeman/foreman/blob/develop/app/registries/foreman/plugin.rb#L318

I am guessing something in 5.2 changed where it attempts to check that even if a database does not exist and Rails throws an error. I think we need to modify some of that code to not run pending migrations check if no database exists? Or if we are in the rake task 'db:create' ?

**Comment by mmoll** [comment]
@ehelms thanks, I think I already know now, where to poke :point_left:

**Comment by mmoll** [comment]
Turns out, I have no idea what's going on there, it's working with _discovery in my travis test setup...

**Comment by mmoll** [comment]
see GH-5836

**Pull request closed without merging**
