### PR TITLE
Fixes #10521 - fix report templates API after refactoring

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
found one issue that has left after the refactoring to `template.render`, @timogoebel mind to take a quick look?

**Comment by timogoebel** [comment]
@ares: Looks good to me, could you also please take a look at:

```
app/models/host_status.rb:6: warning: already initialized constant HostStatus::ExpirationStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::MonitoringStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::OmahaStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::ExecutionStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::ToolsStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::OperatingsystemStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::CpuHotAddStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::ExpirationStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::MonitoringStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::OmahaStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant HostStatus::ExecutionStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::ToolsStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::OperatingsystemStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
app/models/host_status.rb:6: warning: already initialized constant ForemanWreckingball::CpuHotAddStatus::Jail
app/models/host_status.rb:6: warning: previous definition of Jail was here
```

**Comment by ares** [comment]
katello test failure is unrelated, warning should have been gone by now

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @ares.

**Pull request merged**
