### PR TITLE
Fixes #15681 - Fog Openstack version should require at least version 0.1.7 to ensure compatibility with Openstack Liberty

### PR DESCRIPTION
**Pull request by imriz**

### CODE REVIEW

**Comment by imriz** [comment]
@dLobatog I would love your help testing this with libvirt :) Thanks!

**Comment by imriz** [comment]
It seems the failure in the test start between  fog-openstack 0.1.5 and 0.1.6 (0.1.5 passes, 0.1.6 fails)

I've ran bisect, and the first bad commit is fog/fog-openstack@72fde2b6fe4af766dbc88ecfc4b3f991ac10ea1c

**Comment by imriz** [comment]
I think it is because the default is now v3, we must provide openstack_domain_id

**Comment by dLobatog** [comment]
@imriz Thanks for the update! We normally just tests updates of fog with all Compute Resources, not fog-core. Take a look at tests though,  there's one that's failing. The integration one (HostJSTest::create new host) doesn't have to do with this and has been failing intermittently

**Comment by imriz** [comment]
@dLobatog yeah. It is the same root cause. It seems fog-openstack moved the default to V3 without implementing proper Mock support. I am hard coding it to V2 ATM. I don't think Foreman supports V3 anyway yet (according to their README it needs another variable in the credentials)

**Comment by imriz** [comment]
[test]

**Comment by imriz** [comment]
@dLobatog Is there anything wrong with Jenkins? I don't think the failures are related.

**Comment by domcleal** [comment]
The Ruby 2.0.0 and upgrade test failures are due to a new issue today with the rabl gem, please ignore them for now - they're being fixed.

**Comment by imriz** [comment]
[test]

**Comment by dLobatog** [comment]
[test] after the Rabl gem was pinned a few hours ago - if it works I'll merge

**Comment by dLobatog** [comment]
Merged as e8bceb07db45810abafe354f474a4c3cabffb295, thanks @imriz!

**Pull request closed without merging**
