### PR TITLE
Adding unique IDs to menu and submenu entries.

### PR DESCRIPTION
**Pull request by omaciel**
Unique IDs are crucial for proper UI automation.

### CODE REVIEW

**Comment by skottler** [comment]
Thanks @omaciel! Can you create a ticket for this at http://projects.theforeman.org and then add the ID to the commit?

**Comment by omaciel** [comment]
Here you go @skottler  http://projects.theforeman.org/issues/3684

**Comment by ohadlevy** [comment]
I know this conflicts with #987 but @abenari would it be possible for you to merge it as part of it?

**Comment by domcleal** [comment]
It's now fixed in the menu redesign PR, but the logout menu bit I think is still useful, so we'll keep this open until the menu redesign's merged and rebase on top.

**Comment by abenari** [comment]
Ids for testing are good idea.
I have added it to #987, it is working for the user menu too.
Can close this PR once #987 is in and @omaciel confirms that it solves his issue.

**Comment by domcleal** [comment]
@omaciel the other PR's been merged now and I see ID attrs on all menu items.  Could you confirm if there's anything more you need to add here?  Thanks!

**Comment by omaciel** [comment]
@domcleal will install and test it as soon as nightly build is available. I wonder if my PR is relevant anymore as I believe the default will be to add "menu_item_*" to the menus now?

**Comment by omaciel** [comment]
@domcleal @abenari  The sub-menu items all have unique IDs, which is awesome, but the first level menus (i.e. Monitor, Hosts, etc) don't. Could you also add IDs to those?

**Comment by omaciel** [comment]
Also, the menu for the user account (where you have the signout link) needs an ID.

**Comment by domcleal** [comment]
Added these in #1049.

**Pull request closed without merging**
