### PR TITLE
fixes #5172 - typo SETTINGS[:location_enabled] instead of :locations_enabled causes default location select box not to be visible

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@eLobato, check your settings.yaml file.  It seems the only way for your commit 070b83feac98a613b3d6a287ea31aed6ec9089b7 to have worked in your local dev environment is if you had `location_enabled` rather that `locations_enabled`

**Comment by dLobatog** [comment]
I had that setting, sorry. Can you change it to SETTING[:locations_enabled] as per @domcleal 's comment https://github.com/theforeman/foreman/pull/1191#discussion-diff-11474234R26 ?

**Comment by isratrade** [comment]
The helper method `show_location_tab?` uses `SETTINGS[:locations_enabled]`

``` ruby
  def show_location_tab?
    SETTINGS[:locations_enabled] && User.current.allowed_to?(:view_locations)
  end
```

**Comment by dLobatog** [comment]
Yeah, I used it at first too, but the reason why @domcleal didn't want to use the helper was that we don't want users to need special permissions (`:view_locations`) to change their own default taxonomies.

**Comment by isratrade** [comment]
re-committed. It makes senses not to have (:view_conditions) to change default taxonomies.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/936bab04d3b1d3136c28b77129cc052bcd04260c , thanks @isratrade !

**Pull request closed without merging**
