### PR TITLE
Fixes #14981 - use root_object for host RABL

### PR DESCRIPTION
**Pull request by lzap**
Can you review @tstrachota please?

### CODE REVIEW

**Comment by fwdIT** [comment]
thx ! also came across this issue this morning after upgrading to 1.11.*
implemented your fix manually and it fixed my hooks again
so tests worked at least on my end

**Comment by dLobatog** [comment]
ACK, waiting for @tstrachota's comment

**Comment by tstrachota** [comment]
I didn't have a chance to test it yet, but it looks fine
+1 for using `root_object` !

**Comment by dLobatog** [comment]
Merged as 4b80f3a91958b85ad8396884bc26c8b4fe829077, thanks @lzap!

**Pull request closed without merging**
