### PR TITLE
Fixes #1827: ensure there are no backslashes in config template name

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by ohadlevy** [comment]
mind rebasing? it does not apply cleanly

**Comment by skottler** [comment]
Rebased @ohadlevy. Once this is committed I'll rebase #356.

**Comment by ohadlevy** [comment]
I guess the rebase didnt work as expected? :) or we should we merge all PR?

**Comment by skottler** [comment]
@ohadlevy yeah this can go in as is and then the subsequent rebase will have conflicts because of the method names and I'll fix them. If you're okay with that then it works for me.

**Comment by ohadlevy** [comment]
@skottler yeah, please merge and close the other (you can keep two commits if you like)

**Comment by skottler** [comment]
All set @ohadlevy. No need for multiple commits, a squash should be fine.

**Comment by ohadlevy** [comment]
@skottler this does not apply cleanly, please rebase and squash - thanks

**Comment by skottler** [comment]
Rebased and squashed. I tested the merge from `value_config_template` into `develop` manually as well and it worked as expected so this should be ready to rock now :+1:

**Comment by skottler** [comment]
Updated to use the parameterize method instead of gsub @ohadlevy

**Comment by ohadlevy** [comment]
the more i think of it, I think that changing the name in the db is wrong, this is purely a representational issue.

how about changing the routes to use ID's instead, we could make them pretty using the to_param method, e.g.

``` ruby
  def to_param
    "#{id}-#{name.parameterize}"
  end
```

otherwise, if we change the name, you can break existing people snippets.

**Comment by skottler** [comment]
@ohadlevy that sounds like a good plan. Thanks!

**Comment by ohadlevy** [comment]
fixed at c4038d6f
thanks @skottler

**Pull request closed without merging**
