### PR TITLE
Bootstrap2

### PR DESCRIPTION
**Pull request by abenari**
Bootstrap css and javascript package upgrade.
Most of the ui is unchanged, except for:
- The ui can fit itself to different screen sizes (Fluid design)
- Different color scheme (Minor changes)
- Errors highlight with red border instead of pink well.
- Actions in some of the index tables has multi-function buttons in it (Open-Stack Nova style. Thank you Gary)
- Drop-down  menus improved.

### CODE REVIEW

**Comment by ohadlevy** [comment]
this looks good, bug a big chunk of the screens are still not updated (hostgroups etc)

**Comment by abenari** [comment]
See if you can find additional pages that looks wrong (or browsers that shows a page wrong).

**Comment by ohadlevy** [comment]
thanks, dashboard run interval graph seems to be broken too

**Comment by ohadlevy** [comment]
already squashed & merged

**Pull request closed without merging**
