### PR TITLE
Fixes #30030 - use media_type where appropriate

### PR DESCRIPTION
**Pull request by mmoll**
Also, set config.action_dispatch.return_only_media_type_on_content_type
to false, as it will be in Rails 6.1.

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Thanks @mmoll for addressing it.
What about:
https://github.com/theforeman/foreman/blob/bcee8f4f624650d8ee2c89feef8acb42af51696f/app/controllers/api/v2/base_controller.rb#L45
https://github.com/theforeman/foreman/blob/bcee8f4f624650d8ee2c89feef8acb42af51696f/app/controllers/unattended_controller.rb#L17
https://github.com/theforeman/foreman/blob/bcee8f4f624650d8ee2c89feef8acb42af51696f/app/controllers/unattended_controller.rb#L220
https://github.com/theforeman/foreman/blob/bcee8f4f624650d8ee2c89feef8acb42af51696f/app/views/api/v2/errors/unsupported_content_type.json.rabl

Should we do something about those as well?

**Comment by mmoll** [comment]
> Should we do something about those as well?

AFAICT no, as these didn't hit any deprecation warnings.

**Comment by ezr-ondrej** [comment]
Those are all `request.content_type` and it seems only `response.content_type` triggers the Deprecation introduced in https://github.com/rails/rails/pull/36490, request has both, but I don't think it got changed. Though we should address it as well as I'd expect the same shift in the future.

**Review by ezr-ondrej — APPROVED** [review]
Let's do this to get rid of the warning, I'll open a follow up for the request :)

**Pull request merged**
