### PR TITLE
Fixes #25241 - Add the ability to pass in include=[facts] to /api/v2/hosts

### PR DESCRIPTION
**Pull request by scottd018**
This helps to speed things up for things such as the Ansible Dynamic Inventory Script.  Currently, the Ansible Dynamic Inventory Script makes one API call per host to pull this information back.  This will allow a single call to be made, and the rest to be parsed in memory.

This will allow us to do the same thing as this PR (https://github.com/ansible/ansible/pull/47257) for the Foreman inventory for Ansible.

Sample API call.  Notice the new 'facts' key in the body of the response:

```
[root@satmlmv001 hosts]# curl -k -u 'admin:redacted' 'https://localhost/api/v2/hosts?include=\[all_parameters,facts\]' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18163    0 18163    0     0  51967      0 --:--:-- --:--:-- --:--:-- 51894
{
    "page": 1,
    "per_page": 20,
    "results": [
        {
            "all_parameters": [
                {
                    "created_at": "2018-10-18 18:51:15 UTC",
                    "id": 4,
                    "name": "new_param",
                    "priority": 0,
                    "updated_at": "2018-10-18 18:51:15 UTC",
                    "value": "new"
                },
                {
                    "created_at": "2018-10-17 15:38:10 UTC",
                    "id": 2,
                    "name": "global_param",
                    "priority": 0,
                    "updated_at": "2018-10-17 15:38:10 UTC",
                    "value": "test"
                }
            ],
            "architecture_id": 1,
            "architecture_name": "x86_64",
            "build": false,
            "capabilities": [
                "build"
            ],
            "certname": "satmlmv001.laptop.scott.lab",
            "comment": null,
            "compute_profile_id": null,
            "compute_profile_name": null,
            "compute_resource_id": null,
            "compute_resource_name": null,
            "configuration_status": 0,
            "configuration_status_label": "No changes",
            "created_at": "2018-10-17 14:25:58 UTC",
            "disk": null,
            "domain_id": 1,
            "domain_name": "laptop.scott.lab",
            "enabled": true,
            "environment_id": 1,
            "environment_name": "production",
            "facts": {
                "agent_specified_environment": "production",
                "aio_agent_version": "1.10.9",
                "architecture": "x86_64",
                "augeas": null,
                "augeas::version": "1.4.0",
                "augeasversion": "1.4.0",
                "bios_release_date": "05/19/2017",
                "bios_vendor": "Phoenix Technologies LTD",
                "bios_version": "6.00",
                "blockdevice_sda_model": "VMware Virtual S",
```

......etc etc

### CODE REVIEW

**Comment by timogoebel** [comment]
Thanks for your contribution!

I'm wondering how many of these options we want to support. Our api is becoming more and more a bunch of patchwork. Are these options documented somewhere?

**Comment by scottd018** [comment]
@timogoebel That's a good question.  I have not found these options documented anywhere.  I found out you could do this via the Rails code itself.

I also think we could do better by allowing the user to specify which attributes that they want back, as opposed to dumping a giant JSON blob (perhaps the attr dump is default, but passing in includes=[facts, domain_id, organization_id], etc will ONLY pass name, id and the requested attrs back).  This is especially important for hosts (because there are lots of them, and they all have many attributes associated with them), as it will help to speed up the API response times.  A specific case I'm referring to here is the Ansible/Foreman integration, which is painfully slow due to inefficiencies on both ends (see https://github.com/ansible/ansible/pull/47257 for a first attempt at fixing some of the Ansible inefficiencies).  This PR will allow us to improve the Ansible inventory sync further, but the API call will still likely be slow for large scale customers.

**Comment by ekohl** [comment]
> I'm wondering how many of these options we want to support. Our api is becoming more and more a bunch of patchwork. Are these options documented somewhere?

It is possible to record API examples from tests and have them included in the generated docs. We should do a better job of reviewing those though. https://theforeman.org/api/1.20/apidoc/v2/auth_source_ldaps/index.html has a HTTP 403 example which isn't that useful to users.

**Comment by scottd018** [comment]
@ekohl reviving this one from the dead in reference to https://github.com/ansible/ansible/pull/59455 and https://github.com/ansible/ansible/pull/47257 (sorry - I had totally lost track of this but now I have time to support it).  The foreman dynamic inventory is still abysmally slow in large environments.  This would certainly help correct that (in theory).  Do you feel this is worth looking into further?

**Comment by timogoebel** [comment]
@scottd018: The best way to move forward with this is probably changing dynamic inventory script to use Foreman's new graphql API. This should be much faster.

**Comment by ekohl** [comment]
@ares it's on your agenda to take a look at the Ansible inventory. Could you share your thoughts?

**Comment by scottd018** [comment]
@ekohl i believe @timogoebel perhaps answered the question in referring to the new graphql API.  I think the only thing to be aware of is backwards compatibility for those who do are not yet on a version that supports graphql.  I believe https://github.com/ansible/ansible/pull/59455 is close to the best we can do with the REST-based method, in which it will always struggle to accommodate large scale environments (I tested with 5000, but I've seen customers downstream who are much larger).

That being said.  I believe this can remain closed, as I was unaware that graphql was coming.  Thanks for the info @timogoebel !

**Comment by ekohl** [comment]
@ares was talking about introducing a dedicated endpoint but maybe graphql is good enough. That said, graphql is still experimental and having external tools rely on it might be tricky. Especially Ansible which moves at a different pace and some versions can live for a long time.

**Comment by ares** [comment]
Thanks for pinging me here @ekohl and sorry for late answer. I believe the new endpoint would be always better, because there we have option to gather data from database the most optimal way. We've seen huge data sets in such inventories. The time to construct it can be really long, regardless if we do it by one endpoint or by separate API queries, these block the web process. So I was thinking it would be better to use report template engine for this. We can introduce a report template that would construct the inventory. The benefit are
* it can be rendered asynchronously, meaning the ansible side would ask for inventory and it would be polling foreman with the job id, once the inventory is ready, it would download it
* we can use template inputs to make the inventory configurable, e.g. include facts can be one option
* users can easily modify the template if they want to add more data or remove some data from the inventory, e.g. if I know I will never use some information, I want to optimize the SQL query

Timeline wise - there's a chance we could make this work in Foreman 1.24 timeframe.

**Pull request closed without merging**
