### PR TITLE
Fixes #20271 - update safemode gem

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by dLobatog — APPROVED** [review]
Thanks @tbrisker , merging for 1.15.3

**Comment by dLobatog** [comment]
Merged into 1.15-stable as b1b357cf039c86c50bedf268d370e9ab7f9fae6f

**Comment by dLobatog** [comment]
Probably worth cp-ing to 1.14-stable

**Comment by tbrisker** [comment]
@dLobatog i agree

**Comment by dLobatog** [comment]
Cherry picked as 4b740d9652b86695df777a39c67fa6e5e7c94cff

**Pull request merged**
