### PR TITLE
fixes #18477 - update Rails to 4.2.8

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by tbrisker** [comment]
Went over the release notes and looks like this shouldn't break anything. Will merge once Jenkins is :green_apple: .

**Comment by tbrisker** [comment]
@domcleal A couple of katello tests are failing, not sure if this is related or not - could you please check?

**Comment by domcleal** [comment]
I wouldn't know, their maintainers should fix it after Foreman is updated (if it's indeed related to this change).

**Comment by dLobatog** [comment]
I'll check the 2 broken tests later today - please wait and I'll be happy to submit a fix for it in Katello

**Comment by dLobatog** [comment]
Indeed the 2 of them fail because of 4.2.8 - on the develop branch they pass. I'll investigate what's wrong. Please don't merge until then, I don't think it's a good idea to ever break the build for Katello

**Comment by jlsherrill** [comment]
[test katello]

**Comment by dLobatog** [comment]
@domcleal Could you rebase this branch? After that, I think it will pick up the CVE fix commit, which should turn all tests green - I think the failures in Katello we're seeing now have to do with that.

**Comment by domcleal** [comment]
PR rebased, tests pass (single failure appears to be transient).

**Comment by dLobatog** [comment]
For the record, the failure was "Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:33395/hosts/host1734/edit' failed to reach server, check DNS and/or server status..." on a few integration tests on Ruby 2.1 - doesn't seem related.

Merging

**Comment by dLobatog** [comment]
Thanks @domcleal !

**Pull request merged**
