### PR TITLE
Fixes #29349 - Fix Layout/SpaceInsideArrayLiteralBrackets cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
- :rocket: use this PR as-is (Rubocop defaults)
- :eyes: use with `EnforcedStyle: space`

**Comment by ekohl** [comment]
With as-is you mean as you've submitted the PR or what's currently in master?

**Comment by mmoll** [comment]
@ekohl The first, I updated the comment.

**Review by tbrisker — DISMISSED** [review]
Please rebase

**Comment by tbrisker** [comment]
Thanks @mmoll !

**Pull request merged**
