### PR TITLE
Fixes #4895: Adds CSRF protection check to the API if a session user is ...

### PR DESCRIPTION
**Pull request by ehelms**
...present.

### CODE REVIEW

**Comment by dLobatog** [comment]
Good catch!

You could just put a  `protect_from_forgery` in the base_controller, just that, instead of checking if  `session[:user]` exists? 
If you really just want to protect CSRF for POST/PUT requests, you can use `:only =>` or `:except => ...`, or even `protect_from_forgery unless request.method == 'GET'`

We already use `protect_from_forgery` for all requests [here](https://github.com/theforeman/foreman/blob/develop/app/controllers/application_controller.rb#L6)

I would say the best choice would be to put it in the Foreman::Controller::Authentication module in the `included` part, just like we do with Foreman::Controller::UsersMixin. It would be one line of code that would work both for API and non-API requests

**Comment by ehelms** [comment]
@eLobato if I open this up to CSRF protection for all PUT/POST I would think that a generic API call using either basic auth or oauth would fail as the user would need to have a CSRF token and pass it along. Whereas here I am targeting someone that is logged in with a session and is using the API either from a UI component or directly via curl/postman/etc. Thoughts?

**Comment by domcleal** [comment]
@ehelms makes sense, this was one of my concerns with #4776.  Arguably this applies to SSO too, but I'm not sure how we should fix it.  Maybe @adelton has some thoughts or experience?

**Comment by adelton** [comment]
> @ehelms makes sense, this was one of my concerns with #4776. Arguably this applies to SSO too, but I'm not sure how we should fix it. Maybe @adelton has some thoughts or experience?

Not sure what the issue is exactly. Can you rephrase it?

**Comment by domcleal** [comment]
Our API permits requests if the user has an active session (via a session cookie).  @ehelms is adding CSRF protection to prevent an attack against a user who has a session open in Foreman, which usually uses a token hidden in the form to verify the request actually comes from a Foreman page, rather than an attack.

However as well as session auth, our API accepts SSO (e.g. via REMOTE_USER with mod_auth_kerb), so if a user was using SSO to access Foreman then they might be vulnerable to a similar sort of attack against our API.  I wonder if we should provide a similar token for SSO access to the API.

**Comment by adelton** [comment]
SSO should mean that the user does not need to authenticate multiple times. It does not mean the user shouldn't acknowledge entering the authenticated area or being asked to confirm actions in the authenticated area.

So I see nothing wrong creating that session based on separate SSO-authentication call, and then requiring that session identification to be present.

**Comment by domcleal** [comment]
Makes sense, thanks @adelton.  I filed http://projects.theforeman.org/issues/4968 so we can collect some further thoughts in that area.  Sorry for derailing your PR @ehelms.

@ehelms would you mind adding a test to test/functional/api/base_controller_subclass_test.rb to check that CSRF is active on session requests?  Thanks.

**Comment by ehelms** [comment]
Closing in favor of - https://github.com/theforeman/foreman/pull/1352

**Pull request closed without merging**
