### PR TITLE
Fixes #15984 - Avoid escaping overridden parameters

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Review by jyejare — APPROVED** [review]
QE Review:

Tests Performed:
```
1) Test on Host

- Create host, add puppet environment env1 to it (puppet parameter was overridden of type array - override check was checked in parameter)
- Go to host -> params and edit/override the param (save/dont save)
- Change the puppet env to env2
- Come back to param tab and see the param overridden is intact and no more chars were added to it

2) Test on HostGroup

- Create hostgroup, add puppet envirronment env1 to it (puppet parameter was overridden of type array - override check was checked in parameter)
- Go to host -> params and edit/override the parameter (save/dont save)
- Change the puppet env to env2
- Come back to param tab and see the param overridden is intact and no more chars were added to it
```
```
QE ACK
```

**Comment by mmoll** [comment]
@orrabin please rebase :)

**Comment by orrabin** [comment]
Thanks @mmoll, I rebased.

**Review by mmoll — APPROVED** [review]

**Comment by ares** [comment]
Given tests are green, @mmoll and @jyejare acks and my read through I think this can be merged. Thanks @orrabin, merging!

**Pull request merged**
