### PR TITLE
Fixes #34062 - update ace-editor to fix toggel typo

### PR DESCRIPTION
**Pull request by MariaAga**
Blocked by: https://github.com/theforeman/foreman-js/pull/363

### CODE REVIEW

**Comment by MariaAga** [comment]
https://github.com/theforeman/foreman/pull/8385/ needs to change the import to `import langTools from 'ace-builds/src-noconflict/ext-language_tools`

**Comment by MariaAga** [comment]
Not sure what to do with the failing tests as rails reads:`d-i partman-auto/disk string /dev/sda\nd-i` that was written into the html as `d-i \npartman-auto/disk string /dev/sda\nd-i` so `has_css` fails to find the text
@ofedoren @ezr-ondrej any ideas?

**Comment by ezr-ondrej** [comment]
@ofedoren any idea where the extran new line comes from?
@MariaAga is that a visible new-line in the UI (DEBUG_JS_TEST=1)?

**Comment by MariaAga** [comment]
Thanks @ezr-ondrej! it did add extra line, I think I solved the test issues with replacing `set` with `send_keys` for ruby tests

**Review by ezr-ondrej — APPROVED** [review]
Thanks @MariaAga :+1:
We need the packaging for this, could you please open it? :)

**Comment by MariaAga** [comment]
Sure! opened https://github.com/theforeman/foreman-packaging/pull/7487

**Review by evgeni — APPROVED** [review]

**Pull request merged**
