### PR TITLE
Fixes #3678 - Make Pry default development console

### PR DESCRIPTION
**Pull request by tbrisker**
Also added a few useful pry plugins that help debugging.

### CODE REVIEW

**Comment by tbrisker** [comment]
what do @theforeman/core feel about this? i'm guessing most already have these in their Gemfile.local.rb anyways? Should we also change the default production console to pry?

**Comment by tbrisker** [comment]
opened https://community.theforeman.org/t/change-default-console-to-pry/16770 for feedback, please don't merge until there is clear consensus there.

**Review by apuntamb — DISMISSED** [review]
I think it is better to switch to pry console for development.
+1

**Comment by ezr-ondrej** [comment]
I think thre is clear consensus on having it default in development (only I'm against it xD) so if someone doesn't raise concerns today, merging during the evening!

**Comment by ezr-ondrej** [comment]
@tbrisker one last thing: while we are at it, what about `pry-remote` ? I didn't knew about that before and it's quite usefull if you use the `foreman` gem to start the app.

**Review by ezr-ondrej — DISMISSED** [review]
I'll go ahead and propose pry-remote myself :upside_down_face: 
Thanks @tbrisker :+1:

**Comment by ezr-ondrej** [comment]
@ekohl could you ack? You can go ahead and merge.

**Comment by tbrisker** [comment]
i'll add it, sorry, didn't get around to answering yet

**Comment by tbrisker** [comment]
I aborted the builds since this only affect development bundle which is skipped in ci anyways

**Review by ekohl — APPROVED** [review]
:+1: from a packaging perspective.

**Review by ezr-ondrej — APPROVED** [review]
Awesome! Thanks @tbrisker :heart:

**Pull request merged**
