### PR TITLE
fixes #2910 - renamed *.erb extensions to *.html.erb

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm I cannot find any references to these files.

**Comment by lzap** [comment]
Ah got it. Yeah that works for me. Lemme test that.

**Comment by lzap** [comment]
Edit host form does work, I assume the extension is picked up by Rails. +1

**Comment by domcleal** [comment]
There's another file in that directory that I think you missed:

app/views/common_parameters/_puppetclasses_parameters.erb

Also, what about these?

app/views/common/_notice.erb
app/views/common/_edit_habtm.erb
app/views/common/_searchbar.erb
app/views/hosts/_progress.erb
app/views/config_templates/_diff.erb
app/views/audits/_list.erb

**Comment by isratrade** [comment]
@domcleal, added more files to the commit.

**Comment by domcleal** [comment]
Merged as 1d7d1ff, thanks @isratrade.

**Pull request closed without merging**
