### PR TITLE
Fixes #18728 - notifications scroll

### PR DESCRIPTION
**Pull request by matanwerbner**
fixes http://projects.theforeman.org/issues/18728

### CODE REVIEW

**Comment by ohadlevy** [comment]
@matanwerbner thanks! can you add screenshots of before / after?

**Comment by ohadlevy** [comment]
also what about tests? :)

**Comment by matanwerbner** [comment]
nothing to test here..it's all css :)

**Comment by matanwerbner** [comment]
mar 14 2017 12-01 pm

**Comment by matanwerbner** [comment]
before:
mar 14 2017 12-07 pm

after:
mar 14 2017 12-08 pm

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
Test foreman

**Comment by ohadlevy** [comment]
Test failure unrelated, thanks @matanwerbner

**Pull request merged**
