### PR TITLE
support #4966 - refactor safemode rendering to allow helpers and variables from plugins

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
Looks very useful, thanks.  Would you mind adding an interface to app/services/foreman/plugin.rb so these can be added via the plugin registration?  (It gives us the freedom to change the internal renderer API later then.)  Corresponding tests for plugin registration are in test/unit/plugin_test.rb.

**Comment by iNecas** [comment]
Here we go

**Comment by domcleal** [comment]
Merged as 869bbff for Foreman 1.5.0, thanks @iNecas.

**Comment by lzap** [comment]
Nice

**Pull request closed without merging**
