### PR TITLE
fixes #21331 - http proxies: name is required

### PR DESCRIPTION
**Pull request by timogoebel**
image

cc: @ohadlevy

### CODE REVIEW

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
thanks @timogoebel

**Comment by ares** [comment]
Thanks @ohadlevy for merging, please don't forget to set the release in redmine. I set it to 1.17 for you.

**Comment by sean797** [comment]
I think it been mentioned before, but we should automate that to he next major release. I’ll take a look if I have time.

**Comment by ares** [comment]
@sean797 that would be awesome, the prprocessor would need to find out what version is the last one and ideally add a comment to github of what it set. Note that prprocessor is not triggered after PR is merged, the issue is updated once redmine sees the change in the repo. Since it was not trivial change, no one has fixed it yet.

**Pull request merged**
