### PR TITLE
fixes #5631 - API v2 - host and hostgroups show.json.rabl should show all puppetclasses in child node

### PR DESCRIPTION
**Pull request by isratrade**
currently it only shows what is in host_classes or hostgroup_classes and not what is inherited or in config_groups

### CODE REVIEW

**Comment by domcleal** [comment]
I'm a bit unsure about doing this without distinguishing in the output classes that are directly associated and those that are inherited.  It could be an important distinction for applications manipulating the associations.

**Comment by isratrade** [comment]
@domcleal, I left the `puppetclasses` child node as is, which is only directed added classes, and added the node `all_puppetclasses`

**Comment by domcleal** [comment]
:+1: sounds better, thanks.

**Comment by isratrade** [comment]
The other option is to have a node `included_classes` or `inherited_class`, but I think adding `all_puppetclasses` works.  It's just not obvious that node `puppetclasses` is directly added only, but that's how it's been until now.

**Comment by isratrade** [comment]
[test]

**Comment by isratrade** [comment]
@domcleal, this looks ready to merge.

**Comment by domcleal** [comment]
It needs testing first.

**Comment by domcleal** [comment]
Merged as d77c457 for Foreman 1.5.1, thanks @isratrade!

**Pull request closed without merging**
