### PR TITLE
Fixes #24780 - update NodeJS versions

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
6.14 is probably the last NodeJS 6.x version and also currently in EPEL. 10.x is going to be declared LTS in October and I'd like to switch DEBs to it, then.

**Review by ekohl — DISMISSED** [review]

**Comment by ohadlevy** [comment]
I might be missing something, but if 6.14 is in epel should we change 6.10 to 6.14 and drop 6?

**Comment by mmoll** [comment]
We can do that, too.

**Review by ekohl — APPROVED** [review]
Given Travis passed I think this can be merged.

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
