### PR TITLE
fixes #3267 - API v1 compatibility for /api/hosts

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@eLobato, can you confirm if this is now compatible with the original api v1?

**Comment by domcleal** [comment]
Will this break v2? :)

**Comment by isratrade** [comment]
@domcleal, you're right.  I will make new views for api/v2/hosts in this PR which needs to be done soon anyway

**Comment by isratrade** [comment]
@domcleal, can this PR be merged after @eLobato confirms it fixes the v1 issue.  API v2 is not the default and we never said that we would not make breaking changes for v2. I think it's OK to merge as V2 is going to see a lot of changes soon.

**Comment by dLobatog** [comment]
I confirm the returned value by the API is that of API v1 - 

```
"environment" : { "environment" : { "id" : 61, "name" : "random" } }
```

I also agree v2 should be the way this was originally, without the doubly nested hash - 

```
"environment" : { "id" : 61, "name" : "random" } }
```

**Comment by isratrade** [comment]
@domcleal, after @eLobato ack, can we merge this, since api v2 can still have breaking changes

**Comment by ohadlevy** [comment]
merged as 2508c6b, thanks!

**Pull request closed without merging**
