### PR TITLE
Fixes #32908 - Allow UTF character in vnic attributes

### PR DESCRIPTION
**Pull request by yifatmakias**

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @yifatmakias !

**Comment by ezr-ondrej** [comment]
@yifatmakias do we want to cherry-pick this to 3.0?

**Comment by yifatmakias** [comment]
> @yifatmakias do we want to cherry-pick this to 3.0?

I am not sure. @tbrisker What do you think?

**Comment by tbrisker** [comment]
sure, i think it's safe enough

**Comment by ezr-ondrej** [comment]
CP 3.0: #8737

**Pull request merged**
