### PR TITLE
fixes #26612 - snapshots for nested snippets

### PR DESCRIPTION
**Pull request by timogoebel**
This adds support for nested snippets in template snapshots.

The actual fix is to change the parameters of `Foreman::Renderer::Source::Snapshot.new` to accept a template so that `get_source` can create a new instance of `Foreman::Renderer::Source::Snapshot`.
https://github.com/theforeman/foreman/blob/3f4943103cf73274c827bfe61b7b14cc4ff0c2fb/lib/foreman/renderer.rb#L31-L33
During template rendering the source class is then passed down the rendering chain.

cc: @tbrisker, @lzap

### CODE REVIEW

**Comment by timogoebel** [comment]
[test foreman]

**Comment by timogoebel** [comment]
Rebased.

**Comment by lzap** [comment]
Related failures :-(

**Comment by timogoebel** [comment]
@lzap: Renamed the snippet fixture files to not have a leading `_` in the filename.

**Review by lzap — APPROVED** [review]
It works fine, generation rake task works as well. Thanks.

**Comment by lzap** [comment]
Merged, katello failure unrelated.

**Pull request merged**
