### PR TITLE
explicitly use rsync.theforeman.org for debug upload

### PR DESCRIPTION
**Pull request by evgeni**
theforeman.org might point at a different system than the one running
rsync

### CODE REVIEW

**Comment by evgeni** [comment]
I am unsure whether this should be rsync.tfm or debugs.tfm?

For other features (like deb and yum syncs), we've been explicitly calling out rsync.tfm as the features might be behind the CDN, but I don't see us moving debugs to the CDN?

**Comment by ekohl** [comment]
> I am unsure whether this should be rsync.tfm or debugs.tfm?

I think `debugs` is good. That's the function here and there is already a domain for it, because that's also where we download them from.

**Comment by lzap** [comment]
Haven't we disabled debug upload feature (on the server)? I remember some discussion about it that discourse provides attachments and we don't need it.

**Comment by evgeni** [comment]
The code still has `UPLOAD_DISABLED=0` and there is an `rsyncd` running that accepts writes. So I'd go with no.

I'd be happy to disable it if you find that discussion?

**Comment by lzap** [comment]
Could not find it, however at some point we would switch over to sosreport. It's just Debian is holding us back a bit with its quite old version: https://community.theforeman.org/t/rfc-deprecate-foreman-debug-in-favor-of-sosreport/12465

Let me test this.

**Review by lzap — APPROVED** [review]
```
A debug file has been created: /var/tmp/foreman-debug-bYsBM.tar.xz (48768 bytes)

Uploading...
The tarball has been uploaded, please contact us on community.theforeman.org
or on IRC/Matrix (#theforeman), making sure you reference the following URL:

    http://debugs.theforeman.org/foreman-debug-bYsBM.tar.xz
```

**Comment by ekohl** [comment]
@lzap just because it works, doesn't mean it's correct. Today we host rsync and debugs on the same server but the infra team may decide to host them on different servers. Please don't ignore my comments.

**Comment by evgeni** [comment]
given that the debugs upload method it rsync, pointing it at rsync.tfm.o is OK, IMHO

**Comment by lzap** [comment]
> Today we host rsync and debugs on the same server but the infra team may decide to host them on different servers.

Let's change it when the time comes then.



> Please don't ignore my comments.

It was not intentional, I missed it.

**Comment by ekohl** [comment]
> > Today we host rsync and debugs on the same server but the infra team may decide to host them on different servers.
> 
> Let's change it when the time comes then.

The thing is, if you want to change it, you need all references to be updated. Given we don't control when users update, it's important to get it right long before you want to change it.

**Comment by evgeni** [comment]
and to bring some closure here, we've just completely dropped the upload functionality in https://github.com/theforeman/foreman/pull/10148 *because* the infra team decided to move things around and turn off rsync.tfm.o (https://community.theforeman.org/t/sunsetting-rsync-theforeman-org/37884)

**Pull request merged**
