### PR TITLE
Fixes #21329 - Fix webpack build

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
In conjunction, adding a test condition to test_develop to ensure that future changes do not break RPMs as easily by running the same install and webpack build steps in the same way: https://github.com/theforeman/foreman-infra/pull/352

**Comment by ehelms** [comment]
@dLobatog @ekohl You may want to review this to fix nightlies

**Comment by ehelms** [comment]
Successful scratch build -- http://koji.katello.org/koji/taskinfo?taskID=39573

**Comment by ohadlevy** [comment]
as discussed earlier, this approx conflict with the plugin development for webpack. if you like, we can schedule a meeting to discuss this in more details.

I'm OK with merging this to unblock nightly, but it was changed back for a reason.

**Comment by ekohl** [comment]
@ohadlevy I'd like to unblock nightlies now and then discuss how we can move forward. Obviously we want plugin development w/ webpack to be possible but nightlies are important.

**Comment by tbrisker** [comment]
merging per https://github.com/theforeman/foreman/pull/4913#issuecomment-336793353 to unblock nightlies. Please follow up on fixing this for plugins in a way that doesn't break nightly. Thanks @ehelms @ohadlevy @ekohl !

**Comment by ehelms** [comment]
We could try having both paths in place for resolving. This got merged so I
can't test that here, but once the test job changes I linked above are
merged we can test it.

On Oct 16, 2017 8:04 AM, "Tomer Brisker" <notifications@github.com> wrote:

Merged #4913 <https://github.com/theforeman/foreman/pull/4913>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/theforeman/foreman/pull/4913#event-1294687499>, or mute
the thread

**Pull request merged**
