### PR TITLE
Display page for hosts

### PR DESCRIPTION
**Pull request by sidkhemka**
(note - similar to hostgroups display as on this other pull request - https://github.com/theforeman/foreman/pull/1742)

Adds a new display action for hosts. Some host details cannot be viewed by a user with edit permissions as they are only shown on the edit page. This creates a display action and view, which renders the edit page with all fields disabled and buttons removed so a user with view permissions can see the page but not edit it. The display button is added next to the edit button on the show page of a host. 

screen shot 2014-08-21 at 3 51 39 pm

screen shot 2014-08-21 at 3 52 29 pm

### CODE REVIEW

**Comment by isratrade** [comment]
[test]

**Comment by orrabin** [comment]
[test]

**Comment by orrabin** [comment]
[test]

**Comment by tbrisker** [comment]
@sidkhemka,
Thank you very much for your efforts! 
This PR has been open for a very long time with no activity. 
Please indicate if you plan to continue working on it or not; if not, feel free to close it. 
If you do not respond either way within a couple of weeks, I will assume this PR is abandoned and will go ahead and close it for you.

**Comment by tbrisker** [comment]
Dear @sidkhemka ,
It has been 20 days since my last comment with no replies. 
I am assuming this pull request has been abandoned and closing it.
If you wish to continue working on this in the future, feel free to reopen.
On behalf of the entire Foreman team, I wish to thank you for your efforts here and hope to see more contributions from you in the future.

**Pull request closed without merging**
