### PR TITLE
fixes #6496 - Allowed match helper

### PR DESCRIPTION
**Pull request by starless72**
Added :match helper method to ALLOWED_HELPERS, to allow for substring pattern matches in templates.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@starless72 Are you missing some file? I'm afraid this by itself will not do much. 

All allowed helpers need to be methods included in the `Host` model. If you want to use match to match regexes, it should be easy to create a `match(regex)` method in that model that simply uses Ruby's match.

**Comment by starless72** [comment]
Er... sorry eLobato, what do you mean? I tested this simple change in my Foreman 1.5.1 install and it allowed me to use @host.domain.name.match(/pattern/) in my provision template without the need to disable safe render. See the discussion at https://groups.google.com/forum/#!topic/foreman-users/ojZHTNsclIQ too.

**Comment by dLobatog** [comment]
Nevermind, I was doing something stupid with my Safemode box, this works perfectly.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/07a89c567fec8a3cce882fe9bd91b7526316f662 , thank you @starless72 !

**Pull request closed without merging**
