### PR TITLE
Fixes #33712 - console action responding in json

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by ekohl** [comment]
I'd like to point out https://projects.theforeman.org/issues/3779 exists.

**Comment by ezr-ondrej** [comment]
> I'd like to point out https://projects.theforeman.org/issues/3779 exists.

Problem is, the console is not just for hosts, so we would have to implement the API for all the resources that are using console.
Which would be the correct way to go, but we would like to get this in for 3.1 :thinking:

**Comment by ekohl** [comment]
I'm not insisting we must build the API now, but it's a long standing gap in functionality.

For this implementation, could you at least add some tests to this? I'm also worried about exposing internal details in an inconsistent manner.

**Comment by ezr-ondrej** [comment]
> I'm also worried about exposing internal details in an inconsistent manner.

That's IMHO fine in the "UI" controllers as those are still internal details and that's why I'm reluctant to do it in API now, as we can change this easily, but we should not do so in API.

I'll add some tests, once I get ack from @amirfefer we want to push this direction :)

**Comment by ekohl** [comment]
> That's IMHO fine in the "UI" controllers as those are still internal details and that's why I'm reluctant to do it in API now, as we can change this easily, but we should not do so in API.

I'm more worried about something that's actually a secret. Something like the real VNC server IP/port. Right now it appears that isn't the case. The password that is sent is the VNC password, but that's really needed to connect and exposed in the current templates too.

**Pull request closed without merging**
