### PR TITLE
Fixes #22166 - Move deps to devDependencies

### PR DESCRIPTION
**Pull request by ekohl**
These deps feel like devDependencies rather than dependencies, but I'm not actually sure since I'm not that familiar with it. Please have a critical look.

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @ekohl

`babel-polyfill` should be a normal dep

**Comment by sharvit** [comment]
`raf` can also be a devDep

**Comment by ekohl** [comment]
Like this?

**Comment by sharvit** [comment]
@ekohl yes :+1: 

Will review it deeper later today

**Comment by sharvit** [comment]
@ekohl I have tested and it feels good!
Also tested it against https://github.com/theforeman/foreman/pull/5145 and it works well (except some error i found there which is my fault)

I am not sure why the tests are failing, i ran them locally and they passed.
any idea?

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ekohl** [comment]
@sharvit I forgot to move the babel-polyfill back to dependencies. Does that mean it's more of a devDependency?

**Comment by sharvit** [comment]
@ekohl you haven't forgotten, it is in the dependencies.
(or I am missing something?)

From babel-polyfill doc https://babeljs.io/docs/usage/polyfill/:
> Because this is a polyfill (which will run before your source code), we need it to be a dependency, not a devDependency

**Review by sharvit — APPROVED** [review]
LGTM

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
[test prprocessor]

**Comment by ohadlevy** [comment]
@ekohl should the pr processor re-check this PR? (is this a pr processor bug?)

**Comment by ohadlevy** [comment]
based on discussion with @ehelms, currently the pr processor doesn't retest on pr that were [wip]

**Comment by ekohl** [comment]
I think it doesn't trigger on subject renames, so I most likely should have changed the title first and then force push.

**Pull request merged**
