### PR TITLE
Refs #25217 - Fix small issue with the Layout

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by sharvit** [comment]
@glekner can you review please?

**Comment by glekner** [comment]
LGTM. thanks @sharvit

**Review by ohadlevy — DISMISSED** [review]

**Comment by ohadlevy** [comment]
@sharvit what is the customer impact ? (screenshot?) in case there is one, we should cherrypick to 1.20?

**Comment by sharvit** [comment]
@ohadlevy It does not affect in any way.
We do nothing with the `manage-menu` class.

**Comment by ohadlevy** [comment]
> We do nothing with the manage-menu class.

so why keep it then?

**Comment by sharvit** [comment]
To explain the context of the link?
I'm fine with removing it.

**Comment by ohadlevy** [comment]
@glekner any reason to keep the css class?

**Comment by glekner** [comment]
can be safely removed.

**Comment by sharvit** [comment]
Updated

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
