### PR TITLE
Fixes #30711 - new report template to report installable_errata

### PR DESCRIPTION
**Pull request by snagoor**
This report template is dependent on https://github.com/Katello/katello/pull/8896

### CODE REVIEW

**Comment by ares** [comment]
@snagoor you'll actually need 2 tickets, one for Foreman change (the template itself) second for Katello change. Otherwise the code looks great. It will just need newer Katello version requirement, once we know which Katello version the PR lands in. I'll test if afterwards for SQL n+1 issues but it seems you included all relations already. Good work on this report!

**Comment by ekohl** [comment]
Is this still blocked?

**Comment by ares** [comment]
it is, the Katello PR is not merged yet and a comment in it was not addressed

**Comment by ezr-ondrej** [comment]
What is the status here? If there will be no activity for two more weeks, we will close, but you're always welcome to reopen.

**Comment by ezr-ondrej** [comment]
@snagoor this is still blocked by the Katello PR, that has not seen activity in quite some time. I'll close this PR for now.
If you wish to continue working on this, please feel free to reopen :+1:

**Pull request closed without merging**
