### PR TITLE
fixes #4895 - Adds CSRF protection check to the API if a session user is present

### PR DESCRIPTION
**Pull request by domcleal**
Replaces #1331 with added tests (had to rework how we only applied this to session users)

### CODE REVIEW

**Comment by domcleal** [comment]
@eLobato and @ehelms could you review between you please?  thanks!

**Comment by ehelms** [comment]
Looks good to me. My tests that worked as expected:

a) removed token and attempted to do a create in Katello UI and was denied

b) Attempted to use Postman to post to the API without the CSRF token and was denied and logged out of my web session. Followed up by logging back in, using basic auth and making an API request that was successful.

Note there is a corresponding Katello PR (https://github.com/Katello/katello/pull/3802) that needs to go in prior to or in conjunction with this update.

Thanks for finding that weird issue with skip vs prepend!

**Comment by dLobatog** [comment]
@ehelms If the Katello PR is in good shape I say :+1: to merge this one now.

**Comment by domcleal** [comment]
@eLobato the Katello PR was merged, so you're ok there

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/73f99b5c79de3d2a6b65e8833c6be72117ca1257 , thanks @ehelms & @domcleal !

**Pull request closed without merging**
