### PR TITLE
fixes #6930 - set vendor flag to Foreman for provisioning templates

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by domcleal** [comment]
This won't update existing templates, I think you should add a migration.

**Comment by stbenjam** [comment]
@domcleal A migration causes a problem, how do I update existing records? ConfigTemplate.update_all will change Katello/Boot Disk/et al templates, which I don't want to do.

Maybe like you do in Boot Disk?

`ConfigTemplate.find_or_create_by_name(XXXX).update_attributes(:vendor => "Foreman")`

**Comment by stbenjam** [comment]
@domcleal Actually, I don't think I can update existing records.  It needs to only be on new installs, any other way and I'll potentially take ownership of user (or other plug-in) supplied templates.

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
Actually just disregard, I'll solve my issue downstream.

**Pull request closed without merging**
