### PR TITLE
Fixes #25437 - fix missing ids in audits page

### PR DESCRIPTION
**Pull request by ares**
@kgaikwad / @tbrisker  mind to take a look?

### CODE REVIEW

**Comment by kgaikwad** [comment]
@ares,
Codewise looks legitimate! :thumbsup:
Tested it, showing `id/value` instead of `missing_id(x)`.

Some tests are failing but I think those are irrelevant.

**Comment by leewaa** [comment]
The issue number is incorrect or am I missing something  ? I tested this locally and the bug I reported in [#25431](https://projects.theforeman.org/issues/25431) still exists.

EDIT: Yep the issue number in the title should be 25437 if I'm not mistaken 🙂

**Comment by ares** [comment]
oops sorry, updated the commit message, it had a typo in bug number

**Review by tbrisker — APPROVED** [review]
Thanks @ares and @kgaikwad !

**Comment by tbrisker** [comment]
:cherries: to 1.20-stable as c3baf5585

**Pull request merged**
