### PR TITLE
Fixes #31758 - Removes unterminated single quote that breaks grub2 parser

### PR DESCRIPTION
**Pull request by lindeneau-scott**

### CODE REVIEW

**Comment by ofedoren** [comment]
Thanks, @lindeneau-scott. Although it's a simple one-char-fix, I'd suggest you to follow the rules (https://theforeman.org/handbook.html#Codingstandards) and create an issue here (https://projects.theforeman.org/projects/foreman/issues/new) and link it to your PR with proper commit message such as Fixes #NumberOfTheIssue - Fix message. So it gets merged a bit faster :)

Also, I think it's better to use `cannot` instead of `cant`.

**Review by lzap — DISMISSED** [review]
Sure, if you have a screenshot of an error I would love to see it.

**Comment by lzap** [comment]
What @ofedoren said, would you mind rebasing this and giving it a proper commit message with an issue? We do this for all commits, thanks!

**Comment by lindeneau-scott** [comment]
@ofedoren Changed commit message to meet redmine requirements & changed wording from can't to cannot.

@lzap I'm sorry, I don't know what screenshot you would like to see? The grub2 loader printing an error message?

There wasn't an issue when I made the pull request as I didn't know about the issues board when I made the change and the PR originally.

**Comment by lzap** [comment]
All is good, thank you. Actually a community user ran into this: https://community.theforeman.org/t/unable-to-pxe-boot-discovery-image-in-uefi-mode-legacy-is-working/22198/4

This is an important fix, thanks. We need to backport this one @ares @ezr-ondrej @tbrisker setting labels.

**Comment by lzap** [comment]
ok to test

**Comment by lzap** [comment]
Damn, can you please run `RAILS_ENV=test bundle exec rake snapshots:generate` and amend those template snapshot changes into this PR? Keep just one commit, the message is okay. This will get tests passing.

**Comment by lzap** [comment]
Another user hit this, we need to fix this ASAP: https://community.theforeman.org/t/uefi-install-problem-rhel-8-3-grub2-efi/22237/

**Comment by lindeneau-scott** [comment]
@lzap I don't have a suitable development environment at the moment, but these changes should succeed. If this fails, I will setup a dev environment for this.

**Comment by lindeneau-scott** [comment]
@lzap This appears to have succeeded.

**Review by ekohl — APPROVED** [review]
Looks good to me and it now passes. Given the prior discussions I think there's consensus that it's a correct change so I'm merging this. Thanks @lindeneau-scott!

**Comment by lzap** [comment]
Thanks all, cpicks:

* https://github.com/theforeman/foreman/pull/8316
* https://github.com/theforeman/foreman/pull/8317

**Comment by lzap** [comment]
Ouch, just got bitten by this when testing Satellite 6.9. What a nasty one.

**Pull request merged**
