### PR TITLE
Fixes #35708 - Fix various bad translations

### PR DESCRIPTION
**Pull request by ekohl**
This was initially found by running `make -C locale tx-update` and that showed malformed strings. Many dating back to older releases. Then I also found the Javascript string interpolation by using ``rg '__\(`'``.

Each commit is there to fix another commit so it can be traced back to how long it was a problem. Initially it was part of https://github.com/theforeman/foreman/pull/9496 but that become too hard to review.

### CODE REVIEW

**Comment by ekohl** [comment]
We should really make this part fatal and add it to CI:
https://github.com/theforeman/foreman/blob/d559505b68f5461593ecb945f602a7925f260179/lib/tasks/locale.rake#L32-L43

As for Javascript I don't know what the best way of preventing `__(`` to show up.

**Comment by ekohl** [comment]
@Ron-Lavi @MariaAga @jeremylenz this is blocking me in the release process. Could you have a look? I can merge it myself if needed, but I'd appreciate someone with more JS knowledge taking a look.

**Comment by jeremylenz** [comment]
> I don't know what the best way of preventing `__(`` to show up

sorry, not sure I understand the question. Where does it show up?

**Comment by ekohl** [comment]
> sorry, not sure I understand the question. Where does it show up?

Now it no longer shows up (because that was one of the points of this PR), but it is **never** valid to use JS string interpolation when calling `translate()` or `__()`: it should always use format strings like `sprintf()`. That means we should have a CI check that yells when it detected in a PR.

**Comment by jeremylenz** [comment]
Seems like we need a rule similar to https://github.com/square/eslint-plugin-square/blob/master/docs/rules/no-translation-key-interpolation.md

That handles `t` from `ember-intl`, but we'd need the same thing for `__`. I can't find any existing rules from eslint plugins that we already use.. :confused:

**Comment by ekohl** [comment]
Yes, something like that. Note that preventing future problems is a long term thing, but shouldn't be solved as part of this PR. If you think this PR is all valid as it is now, I'd appreciate an approval.

**Review by jeremylenz — APPROVED** [review]

**Comment by jeremylenz** [comment]
I don't see any more string interpolation instances, so this LGTM :+1:

**Pull request merged**
