### PR TITLE
Fixes #38068 - Consistently use errors.add

### PR DESCRIPTION
**Pull request by ekohl**
Using `errors[:field] << 'the error'` is deprecated in favor of `errors.add(:field, 'the error')`. Instances found using:

    rg 'errors\[.+\]\s+<<'

### CODE REVIEW

**Comment by ofedoren** [comment]
Is this the same as https://github.com/theforeman/foreman/pull/10299/commits/4d569a27f88c3852d588fa3634f4102a42192995?

Also, not all of the `@errors` are `ActiveModel::Errors` instances, the test failures are related

**Comment by ekohl** [comment]
Oh, I think you're right. Shall I close this instead or do we want to get this merged so #10299 is a bit smaller?

**Comment by ofedoren** [comment]
> Oh, I think you're right. Shall I close this instead or do we want to get this merged so #10299 is a bit smaller?

Mostly depends on you :) If you adjust PR, so the tests are green, we can merge it and I'll rebase my PR, no problem.

The only thing why I'd like to have these changes in Rails 7 PR, so if anyone will try to see why their plugin stopped working or what we did to upgrade Rails, they'll find this as a must have. But probably this particular change is obvious looking on the Rails change log and deprecation warnings :)

**Comment by ekohl** [comment]
Given how close we are to merging, I'm going to close this.

**Pull request closed without merging**
