### PR TITLE
Fixes #14038 - pass corespersocket in VMWare image-based provisioning

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
Requires https://github.com/fog/fog-vsphere/pull/29

**Comment by dLobatog** [comment]
I suppose we have to wait for a release - https://github.com/fog/fog-vsphere/blob/master/CHANGELOG.md - @iNecas mind to ping me here when fog-vsphere releases a version with this? Thanks

**Comment by iNecas** [comment]
Yes, we need to wait there, I will update the PR once done

**Comment by iNecas** [comment]
@dLobatog A new `fog-vsphere` gem was released https://github.com/fog/fog-vsphere/commit/7ab0298bd08a2444c089cb9ca520b73f24d05dfc

**Comment by tbrisker** [comment]
@iNecas Please pin fog-vshpere to at least a version containing the needed changes.

**Comment by iNecas** [comment]
Version number requirement increased

**Comment by dLobatog** [comment]
Merged as 17c277d5733cf4b814f3d5b357269f38bafcfa8f, thanks @iNecas!

**Pull request closed without merging**
