### PR TITLE
Fixes #14182 - authorize role index

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
[test]

**Comment by dLobatog** [comment]
@ares Thanks but is this necessary? `action_permission` in api/base_controller seems to handle this very well already. If I try to access `api/v2/roles/` or `api/v1/roles` with an user that is lacking the role , I just get `"error": {"message":"Access denied","details":"Missing one of the required permissions: view_roles"}` as expected.

PS: Please don't rerun the tests suite until it's green - we're already fixing the flaky tests and know which ones are not working.

**Comment by ares** [comment]
Your request was rejected because your user doesn't have this permission at all, try to assign him view_roles permissions with filter like "name = a". That will allow action to be accessed and would load all roles. Ok I won't rerun it, I saw different test failure on second try...

**Comment by dLobatog** [comment]
@ares Sorry but I'm not seeing that behavior. If I create a new filter with `view_roles` , `name ~ Manager`, I get `{"builtin":0,"name":"Discovery Manager","id":14},{"builtin":0,"name":"Manager","id":5},{"builtin":0,"name":"Remote Execution Manager","id":4},{"builtin":0,"name":"Site manager","id":10},{"builtin":0,"name":"Tasks Manager","id":1}` back (which is fine). If I set the filter to `name = Manager`, I get just `{"builtin":0,"name":"Manager","id":5}`. Am I missing something else?

**Comment by ares** [comment]
@dLobatog please test in UI. For API please double check that you're using API v1, API v2 does not contain this issue. I'd be really surprised that you get this output with v1 since I just realized it's broken and it returns 403 unless you're admin regardless of permissions. If it's really the case, please provide application log with debug log level. v1 is missing mapping in access_permission for roles, I'm not sure if it should be changed to allow user to access it, leaving as it is now.

**Comment by dLobatog** [comment]
@ares Ah I see it now - sorry, v2 was misleading me. Merging

**Comment by dLobatog** [comment]
Merged as 1dc50766d599f1121f959117e98e639bfc0e9ff1, thanks @ares!

**Pull request closed without merging**
