### PR TITLE
Fixes #17136 - Enable ha flag when creating ovirt VM

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by shiramax** [comment]
Need to merge this PR as well:
https://github.com/fog/fog-ovirt/pull/22

**Review by dLobatog — CHANGES_REQUESTED** [review]
WoC because of the fog-ovirt dependency, looks good @shiramax

**Comment by shiramax** [comment]
[test foreman]

**Review by dLobatog — CHANGES_REQUESTED** [review]
@shiramax Looking good, could you rebase & push again with the fixed conflicts? I'll merge afterwards if :green_apple:

**Comment by shiramax** [comment]
@dLobatog done :) 
thanks

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @shiramax !

**Comment by shiramax** [comment]
@dLobatog  thanks!
could you please review https://github.com/fog/fog-ovirt/pull/22 as well, This PR also needs to be merged to get high availability work.

**Comment by shiramax** [comment]
@dLobatog thanks , 
I think now that it was mistake to merge this bug first, because it's waiting for this to merge first: 
fog/fog-ovirt#22
could you please revert this one?

**Comment by shiramax** [comment]
@dLobatog , I spoke with Ori and Shim, There is no need to revert this PR, thanks!!!

**Pull request merged**
