### PR TITLE
Fixes #22910 - Port robottelo tier1 environment tests

### PR DESCRIPTION
**Pull request by odovzhenko**
Redmine issue: http://projects.theforeman.org/issues/22910

Port robottelo tier1 tests for environment part of robottelo minitest port project https://github.com/SatelliteQE/robottelo/projects/1

Related Robottelo issue: SatelliteQE/robottelo#5842

Relates on #5295 for rfauxfactory dependency.

### CODE REVIEW

**Comment by mmoll** [comment]
ok to test

**Comment by ares** [comment]
add to PR whitelist 

3rd PR with no bad intention :-)

**Comment by mmoll** [comment]
[test upgrade]

**Review by ares — APPROVED** [review]
Looks good, controller tests took 3 seconds to finish, model tests took 1.5 seconds :-) Note that times include existing tests too from updated files.

**Comment by ares** [comment]
Test issues are unrelated, thanks @odovzhenko, merging!

**Pull request merged**
