### PR TITLE
Fixes #11025: Allow skip test runner to run through Jenkins test task.

### PR DESCRIPTION
**Pull request by ehelms**
The Jenkins CI gem implements it's own custom test runner. When trying
to use a custom test runner in the jenkins environment, this test
runner needs to be inherited from and included as the last argument.
In order to do this, the test tasks must be overwritten to set the
test runner to use on an individual basis so that the custom test
runner is always the last argument and wins over the base Jenkins
runner. Thus, this change recreates each of the existing test tasks
with this design in mind. The interface for users calling this test
tasks should remain the same, only the output (and ability to run
the custom test runner in Jenkins) should change.

### CODE REVIEW

**Comment by ehelms** [comment]
I am working on this change in conjunction with this Katello PR (https://github.com/Katello/katello/pull/4534) that implements the use of this functionality as my test bed. I took this approach from experiences we had need to use a custom test runner in Katello. I am open to other ideas given the constraints of how the Jenkins CI gem works currently, but to date, I have not found a better solution from having tried many variations.

**Comment by ehelms** [comment]
Things (I think) that should be tested/considered:

1) Ensure Foreman test tasks still run as expected (e.g. rake test:units)
2) Ensure Foreman test tasks still run as expected in Jenkins context (e.g. rake jenkins:unit)
3) Test that Foreman unit tests can be run with a plugin(s) present and that skip tests works (suggest using https://github.com/Katello/katello/pull/4534) or attempting with another big plugin that makes modifications to Foreman core
4) Use Jenkins test job to test this PR against the Katello PR to see it all in action (e.g. http://ci.theforeman.org/job/test_katello_core_gsutcliffe/14/)
5) Read through https://groups.google.com/forum/#!searchin/foreman-dev/custom$20test/foreman-dev/mP0xcXzYYiA/anjlcPL7UzQJ

**Comment by domcleal** [comment]
Is it necessary to inject our own runner during the execution of the test task, which means redefining them?

I wonder if we can simply define a new task (e.g. foreman:runner_setup) that changes the runner, à la ci:setup:minitest, and then:
1. change our jenkins:\* jobs in lib/tasks/jenkins.rake to run jenkins:setup:minitest followed by foreman:runner_setup
2. prepend foreman:runner_setup as a dependency for the existing test:\* jobs without redefining them

Administrativia: please file a new ticket, since #6549's closed and shipped.

Edit: don't use `:runner:` in a name with emoji, sigh.

**Comment by ehelms** [comment]
I'll give this strategy a try, I know in the past I have had a number of issues with the way the CI gem sets up the test runner and having to override that. 

Would you consider my looking into upgrading to ci_repoter 2.0 as a viable option? My cursory examination appears to indicate they take a different strategy than the one that currently requires this overriding.

**Comment by domcleal** [comment]
> Would you consider my looking into upgrading to ci_repoter 2.0 as a viable option?

Yeah, I'd like that a lot if it helps.  I think we pinned it without really considering why it wasn't working.

**Comment by ehelms** [comment]
Looks like ci_reporter gem for minitest requires minitest 5.0 and the minitest-spec-rails gem only supports minitest 4.7 for Rails 3.X. So looks like I'll have to give your idea a shot until we upgrade to Rails 4.X.

**Comment by ehelms** [comment]
Updates:

1) Changed to a new issue
2) Changed to Dominic's idea that simplified the changes, which worked locally, running a Jenkins test against the Katello PR to confirm

**Comment by ehelms** [comment]
Another update, you will see I had to write an enhance for each test Rake task so that the local versions of the test tasks can be run and use the test runner as well. If the `test_runner` is required by the `test_helper` file then the Jenkins tasks break in terms of using the runner. I really have never been able to figure out why.

**Comment by domcleal** [comment]
> If the test_runner is required by the test_helper file then the Jenkins tasks break in terms of using the runner. I really have never been able to figure out why.

The only thing that comes to mind is that the test_helper would be used if you ran a single test file (`be ruby -Itest test/functional/foo_test.rb`), so would running a single file not use our runner?

**Comment by ehelms** [comment]
Correct, you'd have to utilize the rake task way of doing this, e.g.

```
rake test TEST=test/functional/foo_test.rb
```

Another option would be to try to use `in_rake` to only require it if not running from the Jenkins perspective. The way the ci_reporter gem sets the test runner has caused many a headache and compromises (it's why the Katello rake tasks break so much from normality).

**Comment by domcleal** [comment]
> Another option would be to try to use in_rake to only require it if not running from the Jenkins perspective

Would you mind doing that?  I'd find it useful, maybe others also use the same technique.

**Comment by ehelms** [comment]
If I try:

```
require 'test_runner' unless Foreman.in_rake?('jenkins')
```

I still get it failing because this:

```
defined?(Rake) && Rake.application.top_level_tasks.any?
```

returns false and thus never runs the check because `Rake.application.top_level_tasks` is empty,

**Comment by domcleal** [comment]
Oh, perhaps because tests are spawned under a separate process IIRC?  Oh well, not a big loss in any case, and it only affects when we're running individual files directly and when a plugin is loaded and is trying to skip the test.

**Comment by domcleal** [comment]
Merged as dcc3a96 with a rewrite of the commit message.  Thanks @ehelms.

**Pull request closed without merging**
