### PR TITLE
fixes #11374 - re-initialize select2 on smart vars

### PR DESCRIPTION
**Pull request by shlomizadok**
To be honest, I'd remove select2 from the smart vars and lookup keys and leave only the "without_select2" class

### CODE REVIEW

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
I'd love to kick-out select2 from lookup_keys / smart variables (see also [Ori's comment](https://github.com/theforeman/foreman/pull/2606#discussion_r37415803)).
Thoughts?

**Comment by orrabin** [comment]
:+1:

**Comment by dLobatog** [comment]
Merged as 839a5b4b6919a60d2e0d232a9934aaf03c83bc87, thanks @shlomizadok!

**Pull request closed without merging**
