### PR TITLE
Fixes #23705 - Do not associate ptable snippets

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
would it make sense to provide migration to unassigned already assgined ptable snippets? and also perhaps add a validation to model level, as this could be still achieved through API?

**Comment by xprazak2** [comment]
I added a migration and a validation.

**Review by dLobatog — CHANGES_REQUESTED** [review]
@xprazak2 Please take a look at tests, many of them are failing

**Comment by xprazak2** [comment]
Test are green now.

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @xprazak2 !

**Comment by ares** [comment]
@dLobatog please don't forget to set release in redmine after merging, setting to 1.19

**Pull request merged**
