### PR TITLE
Fixes #13444 - Don't show empty properties

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test]

**Comment by dLobatog** [comment]
@sean797 Use `if @host.whatever.present?` instead of just `@host.whatever`. Otherwise attributes that have blank strings will show up too. Thank you! Will merge after that if the jenkins CI check passes.

**Comment by sean797** [comment]
@dLobatog how's that?

**Comment by dLobatog** [comment]
Merged as 445050954687e5c0cd546e46e9d138805791a164, thanks @sean797!

**Pull request closed without merging**
