### PR TITLE
Fixes #22256 - refactores statement modifier

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ekohl** [comment]
Needs a rebase now

**Comment by ares** [comment]
thanks @ekohl for the reminder, rebased

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Looks like the prprocessor only works if you first change the PR title and then push an updated PR because there is no webhook event sent for updating the PR title.

**Comment by iNecas** [comment]
[test foreman] looks like some intermittents

**Review by iNecas — APPROVED** [review]

**Comment by iNecas** [comment]
Actually, the code really looks safe and the test failures were inrelated: merging away, thanks @ares

**Pull request merged**
