### PR TITLE
Removing unused coffeescript gem

### PR DESCRIPTION
**Pull request by daviddavis**
It doesn't look like you guys have any coffeescript so I thought I'd remove this gem since it shouldn't be needed.

### CODE REVIEW

**Comment by domcleal** [comment]
Could you confirm please @abenari?

(also if cherry picking, please amend the commit and swap the commit message order to "fixes ...")

**Comment by skottler** [comment]
The assets continue to compile just fine with this patch applied and all the app renders properly so I assume it's fine to get merged, but just waiting for @abenari's confirmation.

**Comment by abenari** [comment]
+1 no coffeescripts in foreman.

**Comment by domcleal** [comment]
Thanks @daviddavis, merged as 43c50b4 for Foreman 1.4.

**Pull request closed without merging**
