### PR TITLE
fixes #6994 - update apipie_examples.json

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
Should this be removed from the repo?  What's the purpose?

**Comment by isratrade** [comment]
I think apipie_examples.yml / .json is used by hammer. @tstrachota, is this correct?  Do you agree to delete the .yml file in the repo? It hasn't been updated in 2 years in the foreman repo. I updated it only on the doc site on theforeman.org.

**Comment by domcleal** [comment]
Hammer relies on the apipie cache at install time (rake apipie:cache).

**Comment by isratrade** [comment]
if hammer doesn't need it, the only use if a user goes to /apidoc

**Comment by domcleal** [comment]
Ah, so we use the one in the repository to generate the static docs on a live system?  I guess that makes sense... would be nice to know when it gets out of date

**Comment by isratrade** [comment]
What do you think about setting up a background job that automatically updates apipie_examples.json every time there are any changes to files in directory `app/views/api`

Along these lines, what do you think about an automatic job that runs `rake apipie:cache` and updates docs on theforeman.org where there are changes to `app/controllers/api`

**Comment by domcleal** [comment]
Yeah, though I'd prefer not to have jobs that commit to the repository.  If we had a test for it, that'd be great, else we'll just have to remember to do it when we update the website docs, or add a job to tell us when it's out of date.

(API docs only need updating on major releases, I don't think that needs automating right now.)

**Comment by isratrade** [comment]
@domcleal, I agree. We can do it manually on major releases

**Comment by isratrade** [comment]
@domcleal, should I close this PR or update it? I don't think we updated apipie_examples.json on the 1.6 release

**Comment by domcleal** [comment]
I think we can keep it up to date, maybe add it to the release process wiki page too.

**Comment by isratrade** [comment]
update apipie_examples.json file

**Comment by isratrade** [comment]
will re-open after other api v2 PR's are merged

**Pull request closed without merging**
