### PR TITLE
Fixes #29338 - Add hosts to the hostgroup jail

### PR DESCRIPTION
**Pull request by bagasse**

### CODE REVIEW

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Comment by ares** [comment]
note that this should be done rather by `load_hosts(search: "hostgroup = #{hostgroup.id}")` macro, otherwise you risk loading thousands of records in a single query (problem on large setups)

**Comment by bagasse** [comment]
Thank for the pointer @ares !

**Comment by ares** [comment]
Out of curiosity, do you need this in some report template? If so, what report do you build?

**Comment by bagasse** [comment]
We don't need that for reports for now. We need that in smart_class_parameter for unicast discovery for some clusters (elasticsearch, keepalived...)

**Comment by ares** [comment]
Ah, just saw what you say in the redmine issue, thanks!

**Pull request merged**
