### PR TITLE
Fixes #34329 - Allow permissions to be excluded from default roles

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by ezr-ondrej** [comment]
[test foreman]

**Review by ezr-ondrej — COMMENTED** [review]
I do not love making this more complex, but :shrug:
Can you drop a line of documentation for this in https://github.com/theforeman/foreman/blob/develop/developer_docs/how_to_create_a_plugin.asciidoc#adding-your-permissions-to-foremans-roles

So we at least have that documented? :)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adamruzicka :+1:

**Comment by adamruzicka** [comment]
3.1 CP - https://github.com/theforeman/foreman/pull/9072

**Pull request merged**
