### PR TITLE
Fixes #31236 - Host setup action in RegistrationController extendable from plugins

### PR DESCRIPTION
**Pull request by stejskalleos**
Feature allowing plugins to "hook" into the host's setup process in Api::V2::RegistrationController#host method and add plugin-related actions for host setup.

**Example:**
When REX plugin is installed, we want to extend Registration feature with option for specifying host's primary interface for REX.

**How to test**
Best with: https://github.com/theforeman/foreman_remote_execution/pull/548

**Notes**
I also fixed one small issue in Registration UI form, where I forgot to add `smart_proxy` to ignored `params`.
When SmartProxy have been selected in the UI form, generated command had argument `/register?smart_proxy=ID`,
which was doing nothing.

### CODE REVIEW

**Review by pondrejk — COMMENTED** [review]
I'm hitting https://projects.theforeman.org/issues/31245 so didn't test fully, confirming that the url is generated with the rex interfac parameters, also confirming the smart_proxy fix.

minor questions:
- does it make sense to have the field enabled if the rex dropdown is set to no?
- should there be some validation on what is written in the field

**Comment by stejskalleos** [comment]
@pondrejk 

From the error log it looks like a problem with openscap plugin, not related to these changes:
```
2020-11-03T09:25:45 [W|app|8389153e] wrong number of arguments (given 2, expected 1)
2020-11-03T09:25:45 [I|app|8389153e] Backtrace for 'wrong number of arguments (given 2, expected 1)' error (ArgumentError): wrong number of arguments (given 2, expected 1)
 8389153e | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_openscap-4.0.3/app/models/concerns/foreman_openscap/hostgroup_extensions.rb:31:in `inherited_ancestry_attribute'
```
I'll need to confirm that on Foreman setup with Openscap, on `katello-devel-stable` without openscap everything works okay.

> does it make sense to have the field enabled if the rex dropdown is set to no?

Well there can be a case when you have already SSH keys on the host (so no rex setup) but you want to set the interface.

> should there be some validation on what is written in the field

I couldn't find any information about validation of interface, and we don't do any validation of interface name on host edit form, so I would say current behavior is okay. Maybe adding same label help as it is on Host form wouldn't be bad idea. But this is for this is for theforeman/foreman_remote_execution#548 changes, not this PR.

**Comment by stejskalleos** [comment]
@pondrejk 
> I'm hitting https://projects.theforeman.org/issues/31245 so didn't test fully

Issue have been fixed in here: https://projects.theforeman.org/issues/31186

**Review by ares — APPROVED** [review]
Looks good from code perspective. During testing I found one thing. While I agree there's no good validation for identifier input, if user adds a value that is not an existing interface, they get the following error

```
ERROR: not_found
Couldn't find Nic::Base with [WHERE nics.host_id =  AND nics.identifier = ]
```

from user perspective, this is not telling much. However I understand this is not behavior introduced here, I'll add a comment to the REX plugin PR that only takes advantage of this extension point.

This one is good to go, merging, thanks @stejskalleos

**Pull request merged**
