### PR TITLE
fixes #9308 - fix kickstart_kernel_options.erb escaping

### PR DESCRIPTION
**Pull request by jograb**
Fixes #9308 - for explanation see https://community.theforeman.org/t/foreman-uefi-provisioning-grub-failure/30577/5

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
Hi @jograb, can you fix the commit message to be: `Refs #34975 - fix kickstart_kernel_options.erb escaping`? this was the original redmine issue in #9308

**Review by ekohl — COMMENTED** [review]
Looking at this I think `foreman_url` should take care of this, rather than repeating it all over.

Can you tell me where the `&` was? Was it in some value?

**Comment by jograb** [comment]
the problem might be the `?static=1`. Foreman(-proxy) adds another token here as an additional URL parameter (`&token=...`) - here it breaks accordingly. Not sure right now where the `&token` for `foreman_url('provision')` comes from.

**Comment by ekohl** [comment]
> `foreman_url` is configured in `/etc/foreman-proxy/settings.yml`.

That is irrelevant here. `foreman_url` is defined here:
https://github.com/theforeman/foreman/blob/b2d06d0ddbf01923d527feef16c4aef97aada881/app/services/foreman/foreman_url_renderer.rb#L17-L43

I suspect the keyword arguments may be a problem. What may be happening is that it passes values to `unescaped_params` instead of `params`. That can be verified by adding a test where a value needs escaping here:
https://github.com/theforeman/foreman/blob/b2d06d0ddbf01923d527feef16c4aef97aada881/test/unit/foreman_url_renderer_test.rb#L46-L57

**Comment by ofedoren** [comment]
Actually, I don't think https://github.com/theforeman/foreman/pull/9308 has to deal somehow with the issue. Moreover, I've just tested (on current 3.6-develop) generation of provisioning templates and it seems to be right. Here's an example for Grub as was mentioned here https://community.theforeman.org/t/foreman-uefi-provisioning-grub-failure/30577/7: 
ScreenShot-1673020228097

I also don't think it's even worth to escape `&` since it's allowed character for conjunction of URL params. So technically unescaped `&` is the right one. Also, it seems `foreman_url` helper works as expected, it doesn't escape `&` for params automatically.

Surely I'm missing something. As of now I don't see a reason for this patch. Unless there is something else to the problem.

**Comment by stejskalleos** [comment]
@ekohl @ofedoren

Do you have guys working setup with provisioning UEFI & GRUB?
I can test PXE & BIOS, but I don't have working UEFI+GRUB.

**Comment by ekohl** [comment]
No, I never got that working. I did try it with libvirt (like with https://www.redhat.com/sysadmin/uefi-http-boot-libvirt) but had some issues. Though perhaps that was mostly for secure boot.

**Comment by ofedoren** [comment]
I'll try, but my provisioning setups are pretty limited to use libvirt only :/

Also, I'd better have https://github.com/theforeman/foreman/pull/9582 solution instead if that fixes the issue, I just don't quite like such escapings...

**Comment by stejskalleos** [comment]
> Also, I'd better have #9582 solution instead if that fixes the issue, I just don't quite like such escapings...

It doesn't, according to https://github.com/theforeman/foreman/pull/9477#issuecomment-1433057111

**Comment by jpasqualetto** [comment]
> @ekohl @ofedoren
> 
> Do you have guys working setup with provisioning UEFI & GRUB? I can test PXE & BIOS, but I don't have working UEFI+GRUB.

If you guys need, I can test both scenarios or help you guys setup a test environment. You can do it with only libvirit. 


> I'll try, but my provisioning setups are pretty limited to use libvirt only :/
> 
> Also, I'd better have #9582 solution instead if that fixes the issue, I just don't quite like such escapings...

Simply quoting the URL fixes the problem for Grub2 + UEFI, but then it breaks PXE + BIOS.

**Comment by ofedoren** [comment]
> Simply quoting the URL fixes the problem for Grub2 + UEFI, but then it breaks PXE + BIOS.

In that case, shouldn't we close https://github.com/theforeman/foreman/pull/9582?

**Comment by stejskalleos** [comment]
> In that case, shouldn't we close https://github.com/theforeman/foreman/pull/9582?

Let's wait for QAs, they are trying this fix on their infra, when I'll get results I'll update the PR

**Comment by shubhamsg199** [comment]
Hello,
I've tested this patch for PXE + BIOS as well as Grub2 + UEFI  provisioning and it is working fine!

**Comment by wbclark** [comment]
> Hello, I've tested this patch for PXE + BIOS as well as Grub2 + UEFI provisioning and it is working fine!

Thank you @shubhamsg199 ! I believe @jpasqualetto also tested both provisioning methods using essentially the same patch which escapes the `&`s, so @stejskalleos is there any update on your end?

**Review by stejskalleos — APPROVED** [review]

**Comment by stejskalleos** [comment]
:green_apple:  **LGTM**, let's get this in.
Thanks everyone!

**Comment by ekohl** [comment]
@stejskalleos this feels like a cherry pick candidate to me. We're planning to release 3.5.2 soon, so I'd appreciate your thoughts.

**Comment by lzap** [comment]
I do not believe that `&` needs any escaping. This is not a browser or command line, this is kernel option buffer and there is no interpret like bash or any syntax. What you see is parsed by Linux kernel and exposed also via `/proc/cmd`. So I think this patch is not correct.

As it was pointed out, in some workflows (bootdisk I think) a `static=1` URL parameter is somehow incorrectly prepended. The issue is, URL params must start with `?` and then continue with `&`. So the proper fix would be to find where the static is being set and making sure this goes into the URL as a proper paramter so the URL can be rendered correctly.

**Edit**: Unless this is escaping for the Grub itself, in that case, this makes sense. But why this would be a regression? We need to check with grub2 guys if there was such a fix that started enforcing this or something.

**Comment by lzap** [comment]
Ha, that is the case, and I understand why this worked before. When static parameter was not present, the URL only had `?` however when it is present it will not work because how the `?` turned to be `&` which needs escaping in grub. It always has been like that:

image


https://www.gnu.org/software/grub/manual/grub/grub.html#Shell_002dlike-scripting

**Comment by stejskalleos** [comment]
> @stejskalleos this feels like a cherry pick candidate to me. We're planning to release 3.5.2 soon, so I'd appreciate your thoughts.

Yop, already did the PR: https://github.com/theforeman/foreman/pull/9631

**Pull request merged**
