### PR TITLE
Fixes #26832 - Bump unidiff to 1.x

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Packaging was updated in https://github.com/theforeman/foreman-packaging/commit/0641b9ec5ca051567f584f45e47f965631d88b81, this matches it.

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
No idea if this is related:

```
NoMethodError: undefined method `audited_changes' for nil:NilClass...
```

**Comment by ohadlevy** [comment]
> No idea if this is related:
> 
> ```
> NoMethodError: undefined method `audited_changes' for nil:NilClass...
> ```

I dont think it is... this is usually when trying to fetch a rails model and get its audits, but the object is nil...

**Comment by ekohl** [comment]
[test foreman]

**Review by tbrisker — APPROVED** [review]
lgtm, looking at the actual changes in the module itself doesn't seem like anything that should be problematic for us. merging in the hope we can get working nightlies again.

**Pull request merged**
