### PR TITLE
fixes #4581 Implement available_networks API for VMware

### PR DESCRIPTION
**Pull request by gpetras**
Implemented the available_networks, available_clusters, and available_storage_domains for VMware compute resources.The API for this was initially added in #4222.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Mostly looks good, thanks.  The one thing I can't see working is the use of cluster_id for listing networks.  Fog only supports filtering by accessible or datacenter.  Does this patch make sense to you - https://github.com/domcleal/foreman/commit/c7e856f2b6ff8fa8b0d1809f13e9dcbed6af9239?  I've changed available_networks to work as a top level API call so cluster_id isn't required for VMware but is for oVirt.

If so, I'll merge with those combined.

**Comment by gpetras** [comment]
I did notice that the networks don't really filter at the cluster level. Having the cluster_id optional makes more sense. I applied your patch and it works against vSphere.

Thanks for your help!

Greg

**Comment by domcleal** [comment]
Merged as e4d8817 for Foreman 1.5.0, thanks @gpetras!

**Pull request closed without merging**
