### PR TITLE
Fixes #12486 - custom uniqueness validations for interface attributes

### PR DESCRIPTION
**Pull request by imriz**
This is a backport of the validation fix in develop.
Commit message edited to reflect the right redmine ticket.

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks for the PR, but there are [no 1.9 point releases scheduled](http://projects.theforeman.org/projects/foreman/wiki/Foreman_19_Schedule) at the moment, so this can't be merged.  If there's sufficient reason to do one (not a single bug) then we can consider #11034 as a candidate.

**Comment by imriz** [comment]
I would argue that this is a critical bug. People who upgrade from 1.7 are left with a broken state, which requires either manual database manipulation, running custom code (via the console, rake task etc), or manual patching of some sort. Since 1.9 is still the current stable version, I don't think this should be an acceptable state.

For the very least, this should be documented in the upgrade notes, with the manual steps required to remedy this situation.

**Comment by domcleal** [comment]
Noted, but I'm being realistic - there aren't enough candidates to warrant a release at the moment.  If that changes or there's another reason (security issue as per http://projects.theforeman.org/projects/foreman/wiki/Release_Management#Minor-releases) then I'll definitely consider it, as I said above.

**Comment by imriz** [comment]
What about the documentation in the upgrade notes?

**Comment by domcleal** [comment]
Documentation should be added to https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/manuals/1.8/3.6_upgrade.md, or onto the wiki.

**Comment by imriz** [comment]
Closing the PR, then.

I hope we created enough chatter on this so people googeling for this issue will at least understand where it is coming from :)

**Pull request closed without merging**
