### PR TITLE
Fixes #4350 - Allow any format for role name

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
[test]

**Comment by domcleal** [comment]
This seems to expose a UI bug when you try to view filters & permissions for the role.  I tried creating a role called `<script>alert("hi")</script>`.  When you click "Filters and permissions" next to the role, it shows the filters index with a search for `role = "<script...."` but this doesn't work correctly with scoped_search which generates the following SQL:

```
SQL (0.3ms)  SELECT DISTINCT "filters".id FROM "filters" LEFT OUTER JOIN "roles" ON "roles"."id" = "filters"."role_id" LEFT OUTER JOIN "filterings" ON "filterings"."filter_id" = "filters"."id" LEFT OUTER JOIN "permissions" ON "permissions"."id" = "filterings"."permission_id" LEFT OUTER JOIN "taxable_taxonomies" ON "taxable_taxonomies"."taxable_id" = "filters"."id" AND "taxable_taxonomies"."taxable_type" = 'Filter' LEFT OUTER JOIN "taxonomies" ON "taxonomies"."id" = "taxable_taxonomies"."taxonomy_id" AND taxonomies.type='Location' LEFT OUTER JOIN "taxable_taxonomies" "taxable_taxonomies_filters_join" ON "taxable_taxonomies_filters_join"."taxable_id" = "filters"."id" AND "taxable_taxonomies_filters_join"."taxable_type" = 'Filter' LEFT OUTER JOIN "taxonomies" "organizations_filters" ON "organizations_filters"."id" = "taxable_taxonomies_filters_join"."taxonomy_id" AND taxonomies.type='Organization' WHERE "filters"."role_id" = 20 AND ((("roles"."name" = '<script>alert(') AND ("taxonomies"."name" LIKE '%hi"%' OR "taxonomies"."name" LIKE '%hi"%' OR "filters"."search" LIKE '%hi"%' OR "roles"."name" LIKE '%hi"%' OR "permissions"."resource_type" LIKE '%hi"%' OR "permissions"."name" LIKE '%hi"%'))) ORDER BY role_id, filters.id LIMIT 30 OFFSET 0
```

It might be possible to change the scoped_search definition for :role in app/model/filter.rb to prevent it breaking up the name, else we might have to change the UI to search for role_id rather than the role name for reliability.

EDIT: oh, it's the double quotes isn't it.  Gah.

**Comment by domcleal** [comment]
Merged as 1e1c857 for Foreman 1.6.0-RC2, thanks @tbrisker.

**Pull request closed without merging**
