### PR TITLE
Cherrypicks for 2.4 stable

### PR DESCRIPTION
**Pull request by ares**
Cherry-picks for #8293, #8249 and #8276

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
JS errors are unrelated, just a package update, that has added a parameter it seems.
We can fix it in another PR :)

**Comment by ekohl** [comment]
> JS errors are unrelated, just a package update, that has added a parameter it seems.

And it also shows up in develop so fixing it first in a stable branch doesn't make sense.

**Review by lzap — APPROVED** [review]
LGTM, there are some "mystery" warnings in the JS code, no idea what these are. Ruby looks fine :-)

**Comment by tbrisker** [comment]
This was merged into develop, which already contained these fixed.

**Comment by tbrisker** [comment]
I've manually cherry-picked all three into 2.4-stable as 1bdefd70b fb6a774fa and b68dc53e2

**Comment by ezr-ondrej** [comment]
Thank you @tbrisker 3 of us didn't notice :facepalm:

**Pull request merged**
