### PR TITLE
Fixes #34063 - Drop deprecated Host#import_facts method

### PR DESCRIPTION
**Pull request by tbrisker**
Katello test will fail, as will some other plugins that still use this method. Will open PRs to clean up there as well.

### CODE REVIEW

**Comment by tbrisker** [comment]
Plugin PRs:
https://github.com/Katello/katello/pull/9825
https://github.com/theforeman/foreman_salt/pull/158
https://github.com/theforeman/foreman-tasks/pull/661

There are also a couple of uses in puppetdb and default_hostgroup plugins but they seem to be unmaintained.

**Review by ezr-ondrej — DISMISSED** [review]
once Katello PR gets in this is ready.
Nice cleanup @tbrisker :)

**Comment by tbrisker** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
[test katello] what the heck

**Review by ezr-ondrej — APPROVED** [review]
I'll try to open PR against the default_hostgroup before merging, but apart of that :+1:

**Comment by ezr-ondrej** [comment]
It's already done, not perfectly, but done :shrug:

**Pull request merged**
