### PR TITLE
Fixes #15372 - Merge the correct hash when adding new volumes

### PR DESCRIPTION
**Pull request by agx**
Use 'attr' passed into the method and not the attrs hash on the cr.

### CODE REVIEW

**Comment by timogoebel** [comment]
@agx: Looks good to me, good catch. Let's wait for tests and i'll merge.

**Comment by timogoebel** [comment]
Merged as 583865ce08656fe4eef189e4585b731cdac330d4, thanks @agx!

**Comment by domcleal** [comment]
@timogoebel I don't think you pushed it, that commit doesn't exist.

**Comment by timogoebel** [comment]
@domcleal : It rejected my credentials. Pushed it now.

**Pull request closed without merging**
