### PR TITLE
Fixes #8433 - Fix type transformation for all ENC-able NICs

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@tstrachota could you please review? I think you know the context already.

**Comment by domcleal** [comment]
Should Nic::Bootable also receive this transformation?

**Comment by ares** [comment]
@domcleal yeah, bootable could also be included in ENC output, thanks, fixed

**Comment by domcleal** [comment]
Thanks @ares, merged as 177a281 for Foreman 1.7.0.

**Pull request closed without merging**
