### PR TITLE
Fixes #19779 - Fix Layout/IndentHeredoc cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
Now that we can rely on Ruby 2.3, should we actively use `<<~` to let it strip of the whitespace at the beginning and have properly indented code?

**Comment by mmoll** [comment]
Changed, but I'm unsure how much better this really looks. :eyes:

**Review by ekohl — APPROVED** [review]
I think this is better

**Review by tbrisker — APPROVED** [review]
thanks @mmoll !

**Pull request merged**
