### PR TITLE
Fixes #9339 - Added version fields to the sorting

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ShimShtein The original issue refers to the sorting when you click on the title of the table, but this PR fixes the order when you go to operating systems index. As soon as you click on the `Name` header it gets the clunky sorting again. I think you only need to change `sort :name` to `sort :title` in operatingsystems#index.html.erb. 
Changing the default_scope can be a big deal (in fact we are trying to get rid of default_scope entirely), so let's close this with just the change in the view.

Thanks! :fireworks:

**Comment by dLobatog** [comment]
[test]

**Comment by ShimShtein** [comment]
Had to change the old migrations to unscoped, to avoid hitting non-existing column.

**Comment by ShimShtein** [comment]
[test] Probably a glitch

**Comment by dLobatog** [comment]
Merged as 61b5da1bb089a313375ef232e2643b0cd422bf92, thanks @ShimShtein . I only changed the commit message to put the details in the description instead of the title.

**Pull request closed without merging**
