### PR TITLE
Feature #4521 - Openstack block device options

### PR DESCRIPTION
**Pull request by dLobatog**
http://projects.theforeman.org/issues/4521
New hosts should be able to be provisioned using block device mapping
Block device mapping should support ephemeral disks
Host#view should show volumes attached to it if its an Openstack VM.
Openstack Compute Resources should show volumes.

Some screenshots - http://imgur.com/a/Dbtwg 

Tests will follow.

### CODE REVIEW

**Comment by domcleal** [comment]
@GregSutcliffe could you give this a general review with a view to how this integrates with OpenStack before I do picky stuff?

Why are volumes synchronised and stored in the DB?

**Comment by GregSutcliffe** [comment]
Overall, looks good. I don't have an issue storing the volumes in the DB - we do that for Images as well. I do wonder why we should bother with the synchronisation stuff? We expect users to manually create/manage/remove Images in Foreman, and this feels like an extension of that.

Given Images and Volumes are not so different, perhaps we should be using STI on the Images table?

**Comment by dLobatog** [comment]
STI?

**Comment by GregSutcliffe** [comment]
Single Table Inheritance. Most of the attirubutes and methods are going to be the same for images and volumes, after all...

**Comment by GregSutcliffe** [comment]
Oh, and you're missing some permissions on the new controller, which is why the tests are failing

**Comment by domcleal** [comment]
The main difference with images IMO is that an image is associated to an operating system, so we have to persist it to store the association.  Is there a need for a volume though?

**Comment by justicel** [comment]
I at least personally have a pretty great need for volume (especially bootable volume) support in foreman. Essentially many openstack installations only persist data for volumes, and also don't support live migration without using volumes.

**Comment by domcleal** [comment]
Sorry, I didn't mean to imply is there a need for the feature, but questioning the implementation which persists (and duplicates) this data in Foreman's database.

**Comment by ohadlevy** [comment]
I tend to agree with @domcleal here, lets not store date in foreman that would get out of date, unless we need it to map with existing objects in foreman.

The reason why image references are stored in foreman, is that we could associate them with operating systems/ ssh keys etc.

**Comment by dLobatog** [comment]
Closing after https://github.com/theforeman/foreman/pull/2003 was merged which provides a basic functionality for this. This would need major updates to handle device mapping and redoing it is probably a better option as of now.

**Pull request closed without merging**
