### PR TITLE
Fixes #26083 - rename default in search definition

### PR DESCRIPTION
**Pull request by ares**
@ranjan would you like to test and confirm this fixes your issue?

### CODE REVIEW

**Comment by xprazak2** [comment]
[test foreman]

**Comment by xprazak2** [comment]
Maybe rebase could make Jenkins happy.

**Comment by ares** [comment]
Thanks, rebased

**Comment by ares** [comment]
@xprazak2 failures are most likely unrelated

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
