### PR TITLE
Fixes #14838 - Redirect to index page after proxy updated

### PR DESCRIPTION
**Pull request by xprazak2**
successfully

### CODE REVIEW

**Comment by dLobatog** [comment]
@xprazak2 I'm sorry, but I can reproduce the issue reported on the bug. When you update the smart proxy successfully, it returns to 'back' which is the proxy page (that's fine, the issue complains about staying on the edit page), or the index page. Maybe I'm missing something?

**Comment by xprazak2** [comment]
I am officially confused now. I was able to reproduce on yesterday's compose - I remained on edit page after a successful update - but it works fine today. I will try again and if the issue does not appear again I will close this.

**Comment by dLobatog** [comment]
@xprazak2 any success reproducing this?

**Comment by xprazak2** [comment]
Surprisingly, yes. On today's compose. When I go to edit page directly from index, I get redirected back to index. When I go from show page, I get stuck at edit page after successful save.

**Comment by dLobatog** [comment]
@xprazak2 Could you try on theforeman/foreman:develop? I can't reproduce it there. Sorry :/

**Comment by xprazak2** [comment]
I can't reproduce on theforeman/foreman:develop either. I do not see a reason why current code shouldn't work. Sometimes when going from show page to edit, `request.referer` for edit page is actually edit page (should be show):

But I haven't figured out why :-(.

**Comment by dLobatog** [comment]
@xprazak2 Maybe a plugin is causing this. If I try to reproduce it on 'Satellite's Foreman' latest branch it's still fine, edit page redirects to index on success. Mind to close this PR until we can reproduce it?

**Comment by xprazak2** [comment]
Not at all, closing.

**Comment by ohadlevy** [comment]
@xprazak2  where you testing this with katello? i wonder what happens on this line: https://github.com/Katello/katello/blob/master/app/controllers/katello/concerns/smart_proxies_controller_extensions.rb#L47

**Pull request closed without merging**
