### PR TITLE
VmWare max cpu core RAM should be 32G not 16G.

### PR DESCRIPTION
**Pull request by AnneTheAgile**
To fix this Ticket; 
Bug #5901: Unable to select more than 8 cores in VMware template - Foreman
http://projects.theforeman.org/issues/5901
Bug #5901: Unable to select more than 8 cores in VMware template - Foreman
Added by Jon Skarpeteig 5 months ago. Updated 17 days ago. Status:  New Start date: 05/23/2014
Priority:   Normal  Due date:    Assigned To:   -   % Done:  0% Category:   Compute resources - VMware       Target version:    -        Difficulty:    trivial     Bugzilla link:  
Found in release:   1.5.0   Pull request:    Story points   - Velocity based estimate   -

Description  VMware itself supports up to 32 cores (on a single CPU). Max 32 virtual sockets combined.  E.G:
1 x 32
2 x 16
4 x 8
8 x 4 
are all valid configurations
 Related issues Related to Foreman - Bug #2314: Smaller grains for Libvirt VM RAM needed

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
Other related tix; 
[1] Numerous people would like a nicer GUI and more grranularity. 
Feature #1946: Addition VMWare options required for VM creation - Foreman
http://projects.theforeman.org/issues/1946

[2] Generic location was changed previously.
https://github.com/theforeman/foreman/pull/1168/files
fixes #2314 - more choices in memory drop down by rbirnie · Pull Request #1168 · theforeman/foreman
app/helpers/compute_resources_helper.rb

```
def memory_options max_memory
gb = 1024*1024*1024
- opts = [0.25, 0.5, 0.75, 1, 2, 4, 8, 16]
+ opts = [0.25, 0.5, 0.75, 1, 2, 3, 4, 6, 8, 12, 16, 24, 32]
opts.map{|n| [number_to_human_size(n*gb), (n*gb).to_i] unless n > (max_memory / gb)}.compact
end
```

[3] GUI Pretty eye candy, referenced elsewhere...  Pretty Slider for Bootstrap, from Twitter
http://www.eyecon.ro/bootstrap-slider/

```
<input type="text" class="span2" value="" data-slider-min="-20" data-slider-max="20" data-slider-step="1" data-slider-value="-14" data-slider-orientation="vertical" data-slider-selection="after"data-slider-tooltip="hide">
```

[4] This other slider fails on my Firefox , cannot SLIDE; ; ; ;  X.jQuery Bootstrap TouchSpin Plugin Examples
http://www.jqueryscript.net/demo/Touch-Friendly-jQuery-Input-Spinner-Plugin-For-Bootstrap-3-TouchSpin/

**Comment by AnneTheAgile** [comment]
I love the practice of adding tests for all new bug fixes, however here I wasn't sure how to add a test. It seems like this is the right place, though perhaps not at the right level of abstraction; 
foreman/compute_resources_controller_test.rb at 54141ab94976f2c398d94f314cf284fcb88fbc4a · theforeman/foreman
https://github.com/theforeman/foreman/blob/54141ab94976f2c398d94f314cf284fcb88fbc4a/test/functional/api/v2/compute_resources_controller_test.rb
Some of its code ; 

```
require 'test_helper'
class Api::V2::ComputeResourcesControllerTest < ActionController::TestCase
def setup
Fog.mock!
end
//etc
test "should update compute resource for owner" do
setup_user 'edit', 'compute_resources', "id = #{compute_resources(:mycompute).id}"
put :update, { :id => compute_resources(:mycompute).to_param, :compute_resource => { :description => "new_description" } }
assert_equal "new_description", ComputeResource.find_by_name('mycompute').description
assert_response :success
end
//etc
 context 'vmware' do
//etc
```

**Comment by AnneTheAgile** [comment]
I'm  here thinking to apply to this; https://wiki.gnome.org/OutreachProgramForWomen#Submit_an_Application
AnneTheAgile aka TheCantique - trouble with my multiple Github id's it appears :).

**Comment by dLobatog** [comment]
[test]

**Comment by isratrade** [comment]
@AnneTheAgile, I think a helper test makes more since here than a unit test. Here's an idea.

``` ruby
class ComputeResourcesHelperTest < ActionView::TestCase

  test "max memory options are correct for Vmware compute resource in edit form" do
    cr = compute_resources(:vmware)
    expected_options = ["256 MB", "512 MB", "768 MB", "1 GB", "2 GB", "3 GB", "4 GB", "6 GB", "8 GB", "12 GB", "12 GB", "16 GB", "32 GB"]
    available_options = memory_options(cr.max_memory).map {|m| m[0]}
    assert_equal available_options, expected_options
  end

end
```

**Comment by dLobatog** [comment]
@AnneTheAgile vSphere (the commercial version) has a maximum of 1TB of ram, could you change it to that? Also please create or link to an issue in our official Redmine, thank you! http://projects.theforeman.org/issues/

**Comment by AnneTheAgile** [comment]
I apologize I won't be able to finish this as I was trying to apply for the program and didn't hear back in time. I don't use The Foreman on a regular basis so it would be better for you to take over. 

@eLobato there is indeed a ticket on your system, as I referenced at the top.

I just started a new job and I'm  super busy. Thank you for supporting open source!

**Comment by ohadlevy** [comment]
closing due to inactivity.

**Pull request closed without merging**
