### PR TITLE
Fixes #6763 - Correctly choose autocomplete search scope for taxonomies ...

### PR DESCRIPTION
**Pull request by tbrisker**
...depenant on controller. 
Corrects scoped search mistakenly setting the wrong class on locations/organizations for auto-complete.

### CODE REVIEW

**Comment by orrabin** [comment]
Works for me

**Comment by tstrachota** [comment]
Works fine and looks good to me. :+1: 
One question just out of my curiosity: where does scoped search process the `:controller` option? I couldn't find it in the codebase.

**Comment by tbrisker** [comment]
Scoped search mistakenly thinks the search is being run on Taxonomy (it calculates the klass from the table name and it can't be easily overriden) and calls it's complete_scope instead of the one on Location/Organiztion.

**Comment by domcleal** [comment]
The controller option's being processed in our completer_scope impl, second part of the PR.

**Comment by isratrade** [comment]
Merged as 26ee3b1e4f526a3c3975a3640e868dda205b5850  Thanks @tbrisker !

**Pull request closed without merging**
