### PR TITLE
Reduce the lodash affect on the bundle

### PR DESCRIPTION
**Pull request by sharvit**
Using [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) to reduce bundle size.

# Before

```bash
[331] ./webpack/assets/javascripts/bundle.js 1.88 kB {0} [built]
[589] ./webpack/assets/javascripts/bundle_flot.js 245 bytes {0} [built]
[596] ./webpack/assets/javascripts/bundle_multiselect.js 84 bytes {0} [built]
[599] ./webpack/assets/javascripts/bundle_select2.js 110 bytes {0} [built]
[604] ./webpack/assets/javascripts/bundle_datatables.js 104 bytes {0} [built]
[608] ./webpack/assets/javascripts/foreman_users.js 2.87 kB {0} [built]
[609] ./webpack/assets/javascripts/foreman_ssh_keys.js 608 bytes {0} [built]
[610] ./webpack/assets/javascripts/foreman_trends.js 479 bytes {0} [built]
[611] ./webpack/assets/javascripts/foreman_hostgroups.js 1.23 kB {0} [built]
[612] ./webpack/assets/javascripts/foreman_hosts.js 4.78 kB {0} [built]
[613] ./webpack/assets/javascripts/foreman_http_proxies.js 1.24 kB {0} [built]
[614] ./webpack/assets/javascripts/jquery.ui.custom_spinners.js 4.35 kB {0} [built]
[615] ./webpack/assets/javascripts/react_app/common/MountingService.js 1.92 kB {0} [built]
[915] ./webpack/assets/javascripts/foreman_editor.js 12 kB {0} [built]
[935] ./webpack/assets/javascripts/foreman_navigation.js 1.94 kB {0} [built]
```

# After

```bash
[308] ./webpack/assets/javascripts/bundle.js 1.88 kB {0} [built]
[578] ./webpack/assets/javascripts/bundle_flot.js 245 bytes {0} [built]
[585] ./webpack/assets/javascripts/bundle_multiselect.js 84 bytes {0} [built]
[588] ./webpack/assets/javascripts/bundle_select2.js 110 bytes {0} [built]
[593] ./webpack/assets/javascripts/bundle_datatables.js 104 bytes {0} [built]
[597] ./webpack/assets/javascripts/foreman_users.js 2.97 kB {0} [built]
[602] ./webpack/assets/javascripts/foreman_ssh_keys.js 608 bytes {0} [built]
[603] ./webpack/assets/javascripts/foreman_trends.js 479 bytes {0} [built]
[604] ./webpack/assets/javascripts/foreman_hostgroups.js 1.23 kB {0} [built]
[605] ./webpack/assets/javascripts/foreman_hosts.js 5.04 kB {0} [built]
[621] ./webpack/assets/javascripts/foreman_http_proxies.js 1.24 kB {0} [built]
[622] ./webpack/assets/javascripts/jquery.ui.custom_spinners.js 4.35 kB {0} [built]
[623] ./webpack/assets/javascripts/react_app/common/MountingService.js 1.92 kB {0} [built]
[861] ./webpack/assets/javascripts/foreman_editor.js 12 kB {0} [built]
[881] ./webpack/assets/javascripts/foreman_navigation.js 1.94 kB {0} [built]
```

I would prefer not to use `lodash` anymore because es2015 comes with most of the features we need from `lodash` (e.g. .map, .reduce, .filter):
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore
https://gist.github.com/amowu/131686e5946b44423fc33e67130844c4

### CODE REVIEW

**Comment by ohadlevy** [comment]
@sharvit I might be missing something but the stats look very similar?

**Comment by sharvit** [comment]
@ohadlevy, there is only a very small change in `foreman_users` and in `foreman_hosts` :-1: 

I am trying to understand why.
I expected a change in `MountingService`...

**Comment by sharvit** [comment]
Removing this line remove only 4K from the bundle.js:
```js
require('expose-loader?_!lodash');
```

**Comment by sharvit** [comment]
OK, diving deeper.

After removing `require('expose-loader?_!lodash');` and creating `bundle_lodash` those are the results.
I am not sure why is the deference between `WEBPACK VISUALIZER` to my logs and my files, am i missing something?

`WEBPACK VISUALIZER` giving very satisfied results :+1: 

# Before

screenshot from 2017-12-26 18-20-44

```bash
Asset       Size  Chunks                    Chunk Names
bundle-14cfdaa59d179d765b55.js    2.92 MB       0  [emitted]  [big]  bundle
vendor-7d94d8c9f676072121fc.js     1.4 kB       1  [emitted]         vendor
bundle-14cfdaa59d179d765b55.css    70.5 kB       0  [emitted]         bundle
vendor-7d94d8c9f676072121fc.js.gz  776 bytes          [emitted]         
bundle-14cfdaa59d179d765b55.css.gz    13.4 kB          [emitted]         
bundle-14cfdaa59d179d765b55.js.gz     795 kB          [emitted]  [big]  
manifest.json  216 bytes          [emitted]         
[331] ./webpack/assets/javascripts/bundle.js 1.88 kB {0} [built]
[589] ./webpack/assets/javascripts/bundle_flot.js 245 bytes {0} [built]
[596] ./webpack/assets/javascripts/bundle_multiselect.js 84 bytes {0} [built]
[599] ./webpack/assets/javascripts/bundle_select2.js 110 bytes {0} [built]
[604] ./webpack/assets/javascripts/bundle_datatables.js 104 bytes {0} [built]
[608] ./webpack/assets/javascripts/foreman_users.js 2.87 kB {0} [built]
[609] ./webpack/assets/javascripts/foreman_ssh_keys.js 608 bytes {0} [built]
[610] ./webpack/assets/javascripts/foreman_trends.js 479 bytes {0} [built]
[611] ./webpack/assets/javascripts/foreman_hostgroups.js 1.23 kB {0} [built]
[612] ./webpack/assets/javascripts/foreman_hosts.js 4.78 kB {0} [built]
[613] ./webpack/assets/javascripts/foreman_http_proxies.js 1.24 kB {0} [built]
[614] ./webpack/assets/javascripts/jquery.ui.custom_spinners.js 4.35 kB {0} [built]
[615] ./webpack/assets/javascripts/react_app/common/MountingService.js 1.92 kB {0} [built]
[915] ./webpack/assets/javascripts/foreman_editor.js 12 kB {0} [built]
[935] ./webpack/assets/javascripts/foreman_navigation.js 1.94 kB {0} [built]
+ 922 hidden modules

$ l public/webpack
total 3.7M
  69K Dec 26 18:13 bundle-14cfdaa59d179d765b55.css
  14K Dec 26 18:13 bundle-14cfdaa59d179d765b55.css.gz
 2.8M Dec 26 18:13 bundle-14cfdaa59d179d765b55.js
 777K Dec 26 18:13 bundle-14cfdaa59d179d765b55.js.gz
  216 Dec 26 18:13 manifest.json
 1.4K Dec 26 18:13 vendor-7d94d8c9f676072121fc.js
  776 Dec 26 18:13 vendor-7d94d8c9f676072121fc.js.gz
```

# After

screenshot from 2017-12-26 18-21-00

```bash
Asset       Size  Chunks                    Chunk Names
bundle-cbca1c14b16dcac87da6.js    2.83 MB       0  [emitted]  [big]  bundle
vendor-b181da0b58d2317222de.js     1.4 kB       1  [emitted]         vendor
bundle-cbca1c14b16dcac87da6.css    70.5 kB       0  [emitted]         bundle
vendor-b181da0b58d2317222de.js.gz  773 bytes          [emitted]         
bundle-cbca1c14b16dcac87da6.css.gz    13.4 kB          [emitted]         
bundle-cbca1c14b16dcac87da6.js.gz     765 kB          [emitted]  [big]  
manifest.json  216 bytes          [emitted]         
[309] ./webpack/assets/javascripts/bundle.js 1.87 kB {0} [built]
[584] ./webpack/assets/javascripts/bundle_multiselect.js 84 bytes {0} [built]
[587] ./webpack/assets/javascripts/bundle_select2.js 110 bytes {0} [built]
[592] ./webpack/assets/javascripts/bundle_datatables.js 104 bytes {0} [built]
[596] ./webpack/assets/javascripts/bundle_lodash.js 705 bytes {0} [built]
[601] ./webpack/assets/javascripts/foreman_users.js 2.97 kB {0} [built]
[603] ./webpack/assets/javascripts/foreman_ssh_keys.js 608 bytes {0} [built]
[604] ./webpack/assets/javascripts/foreman_trends.js 479 bytes {0} [built]
[605] ./webpack/assets/javascripts/foreman_hostgroups.js 1.23 kB {0} [built]
[606] ./webpack/assets/javascripts/foreman_hosts.js 5.04 kB {0} [built]
[622] ./webpack/assets/javascripts/foreman_http_proxies.js 1.24 kB {0} [built]
[623] ./webpack/assets/javascripts/jquery.ui.custom_spinners.js 4.35 kB {0} [built]
[624] ./webpack/assets/javascripts/react_app/common/MountingService.js 1.92 kB {0} [built]
[862] ./webpack/assets/javascripts/foreman_editor.js 12 kB {0} [built]
[882] ./webpack/assets/javascripts/foreman_navigation.js 1.94 kB {0} [built]
+ 869 hidden modules

$ l public/webpack
total 3.6M
  69K Dec 26 18:06 bundle-cbca1c14b16dcac87da6.css
  14K Dec 26 18:06 bundle-cbca1c14b16dcac87da6.css.gz
 2.8M Dec 26 18:06 bundle-cbca1c14b16dcac87da6.js
 747K Dec 26 18:06 bundle-cbca1c14b16dcac87da6.js.gz
  216 Dec 26 18:06 manifest.json
 1.4K Dec 26 18:06 vendor-b181da0b58d2317222de.js
  773 Dec 26 18:06 vendor-b181da0b58d2317222de.js.gz

```

**Comment by sharvit** [comment]
@ohadlevy - Ready to get merged...

**Comment by ohadlevy** [comment]
@sharvit can you rebase please? also - what is the finial difference in size in production webpack build? thanks.

**Comment by priley86** [comment]
thanks for researching this @sharvit , i was wondering about the same thing last week...

I also prefer to avoid lodash when possible but can't seem to find a good alternative for doing multi column ordering for table columns w/ [lodash.orderby](https://lodash.com/docs/4.17.4#orderBy). For now, I think cherry-picking lodash is best option (or only using when desired).

Nice job here... 👍

**Comment by sharvit** [comment]
@ohadlevy - rebased and:
`bundle.js`      - `72.383KB` less
`bundle.js.gz` - `25.267KB` less

@priley86 - Thanks for the feedback!
Can't you replace _.orderBy w/ Array.sort while you write a comparing function?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
