### PR TITLE
Fixes #28957 - reduce the amount of taxonomies queries

### PR DESCRIPTION
**Pull request by shiramax**
otherwise, the hostgroup list page will very slow.. 
before the fix: 
^Cmshira@dhcp-2-186:~/git/foreman(28957)cat production.log  | grep ↳ | awk '{print $4}' | sort  | uniq -c  | sort -n
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/helpers/layout_helper.rb:15
      1 app/helpers/layout_helper.rb:21
      1 app/helpers/layout_helper.rb:47
      1 app/models/host/base.rb:53
      1 app/models/host/base.rb:54
      1 app/services/authorizer.rb:18
      1 app/services/foreman_seeder.rb:56
      1 app/services/host_counter.rb:39
      1 app/services/topbar_sweeper.rb:17
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/foreman/controller/authentication.rb:10
      2 app/models/user.rb:188
      2 app/models/user.rb:192
      2 app/models/user.rb:406
      2 app/services/authorizer_cache.rb:12
      3 app/models/setting.rb:243
      4 app/controllers/concerns/application_shared.rb:101
      4 app/services/authorizer.rb:48
      6 app/models/setting.rb:276
      7 lib/foreman/silenced_logger.rb:37
      9 app/helpers/hostgroups_helper.rb:7
      9 app/models/hostgroup.rb:243
      9 app/models/role.rb:123
     12 app/models/setting.rb:277
     14 app/models/user.rb:495
     62 app/models/concerns/taxonomix.rb:114
     68 app/models/concerns/taxonomix.rb:61
    125 app/models/user.rb:497

after the fix:
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/helpers/layout_helper.rb:15
      1 app/helpers/layout_helper.rb:21
      1 app/helpers/layout_helper.rb:47
      1 app/services/authorizer.rb:18
      1 app/services/foreman_seeder.rb:56
      1 app/services/topbar_sweeper.rb:17
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/foreman/controller/authentication.rb:10
      2 app/models/user.rb:188
      2 app/models/user.rb:192
      2 app/models/user.rb:406
      2 app/services/authorizer_cache.rb:12
      3 app/models/setting.rb:243
      3 app/services/authorizer.rb:48
      4 app/controllers/concerns/application_shared.rb:101
      6 app/models/setting.rb:276
      7 lib/foreman/silenced_logger.rb:37
      8 app/models/user.rb:495
      9 app/helpers/hostgroups_helper.rb:7
      9 app/models/hostgroup.rb:243
      9 app/models/role.rb:123
     12 app/models/setting.rb:277
     50 app/models/user.rb:497
     62 app/models/concerns/taxonomix.rb:114
     68 app/models/concerns/taxonomix.rb:61

steps to test: 
1.create (main-)organization with 20 nested organizations 
2. create a non admin user with permissions to view the hostgroups
3. enable the sql logging in the settings.yaml 
4. add in application.rb:  config.active_record.logger = Foreman::Logging.logger('sql')
5. run the server and save the logs in a file , next go to the hostgroup page 
6. cat production.log  | grep ↳ | awk '{print $4}' | sort  | uniq -c  | sort -n -> to check the  calls count

### CODE REVIEW

**Comment by ares** [comment]
Tests failures seems related, but it's great to see efforts like this! Perhaps this caching has unintended side effects, but I believe we can still introduce it in some form.

**Comment by shiramax** [comment]
@ares tests are related,
but I still think that this fix is correct, since  @location_and_child_ids and  @organization_and_child_ids are instance variables, and they should be initialized, for each new request. 

It's only breaks the tests, not the UI, and  I could fix the tests with initializing the user  again,
for example: 
https://github.com/theforeman/foreman/blob/develop/test/controllers/api/v2/organizations_controller_test.rb#L36
changing this line to : as_user User.find(user.id) do

the only problem is that there are many tests that I should change, and It's not the best solution.
 
I also tried to initialize  @location_and_child_ids and  @organization_and_child_ids after save of the user or after_update but it didn't fix the tests. 

@ares @tbrisker what do you think? thanks!

**Comment by shiramax** [comment]
[test foreman]

**Comment by tbrisker** [comment]
@shiramax looks like there is a merge conflict, can you please rebase on develop?

**Comment by shiramax** [comment]
@tbrisker done! thanks :)

**Review by tbrisker — COMMENTED** [review]
Looking good! can you please provide a timing before/after on the hg view/edit pages?

**Comment by shiramax** [comment]
@tbrisker 
before:

^Cmshira@dhcp-2-186:~/git/foreman(master)$ cat production.log | grep ↳ | awk '{print $4}' | sort | uniq -c | sort -n
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/controllers/users_controller.rb:163
      1 app/helpers/layout_helper.rb:229
      1 app/helpers/puppet_related_helper.rb:86
      1 app/helpers/puppet_related_helper.rb:87
      1 app/models/host/managed.rb:678
      1 app/models/host.rb:15
      1 app/models/role.rb:99
      1 app/models/user.rb:249
      1 app/models/user.rb:289
      1 app/models/user.rb:704
      1 app/services/foreman_seeder.rb:56
      1 app/services/host_counter.rb:39
      1 app/services/topbar_sweeper.rb:17
      1 app/services/ui_notifications/cache_handler.rb:44
      1 app/services/ui_notifications/cache_handler.rb:56
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 config/initializers/seeds.rb:3
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/application_shared.rb:101
      2 app/controllers/concerns/application_shared.rb:89
      2 app/services/authorizer.rb:18
      3 app/helpers/layout_helper.rb:15
      3 app/helpers/layout_helper.rb:21
      3 app/helpers/layout_helper.rb:47
      3 app/models/setting.rb:243
      4 app/controllers/concerns/application_shared.rb:56
      4 app/models/user.rb:332
      5 app/services/authorizer_cache.rb:12
      6 app/models/setting.rb:276
      8 app/controllers/hosts_controller.rb:50
     11 app/helpers/hostgroups_helper.rb:7
     11 app/models/hostgroup.rb:243
     12 app/models/setting.rb:277
     19 app/services/power_manager/virt.rb:9
     20 app/controllers/concerns/find_common.rb:12
     20 app/models/concerns/parameterizable.rb:48
     24 app/models/user.rb:406
     25 app/models/user.rb:188
     26 app/controllers/concerns/foreman/controller/authentication.rb:10
     28 app/models/user.rb:192
     30 app/services/authorizer.rb:48
     50 app/models/concerns/taxonomix.rb:101
     60 app/models/concerns/taxonomix.rb:87
     89 lib/foreman/silenced_logger.rb:37
    120 app/models/concerns/taxonomix.rb:114
    120 app/models/taxonomy.rb:85
    160 app/models/role.rb:123
    270 app/models/host/base.rb:54
    434 app/models/user.rb:495
   1125 app/models/host/base.rb:53
   1856 app/models/concerns/taxonomix.rb:61
   6336 app/models/user.rb:497

after:
^Cmshira@dhcp-2-186:~/git/foreman(master)$ cat production.log | grep ↳ | awk '{print $4}' | sort | uniq -c | sort -n
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/helpers/layout_helper.rb:15
      1 app/helpers/layout_helper.rb:21
      1 app/helpers/layout_helper.rb:47
      1 app/services/authorizer.rb:18
      1 app/services/foreman_seeder.rb:56
      1 app/services/topbar_sweeper.rb:17
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 config/initializers/seeds.rb:3
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/application_shared.rb:56
      2 app/controllers/concerns/foreman/controller/authentication.rb:10
      2 app/models/user.rb:188
      2 app/models/user.rb:192
      2 app/models/user.rb:406
      2 app/services/authorizer_cache.rb:12
      3 app/models/setting.rb:243
      3 app/services/authorizer.rb:48
      6 app/models/setting.rb:276
      7 lib/foreman/silenced_logger.rb:37
     11 app/helpers/hostgroups_helper.rb:7
     11 app/models/hostgroup.rb:243
     12 app/models/setting.rb:277
     20 app/models/role.rb:123
     37 app/models/concerns/taxonomix.rb:101
     37 app/models/concerns/taxonomix.rb:87
     74 app/models/concerns/taxonomix.rb:114
     74 app/models/taxonomy.rb:85
    158 app/models/user.rb:495
   1160 app/models/concerns/taxonomix.rb:61
   2541 app/models/user.rb:497

**Comment by shiramax** [comment]
@tbrisker 
before:
^Cmshira@dhcp-2-186:~/git/foreman(master)$ cat production.log | grep ↳ | awk '{print $4}' | sort | uniq -c | sort -n
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/helpers/layout_helper.rb:15
      1 app/helpers/layout_helper.rb:21
      1 app/helpers/layout_helper.rb:47
      1 app/services/authorizer.rb:18
      1 app/services/foreman_seeder.rb:56
      1 app/services/topbar_sweeper.rb:17
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 config/initializers/seeds.rb:3
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/application_shared.rb:56
      2 app/controllers/concerns/foreman/controller/authentication.rb:10
      2 app/models/user.rb:188
      2 app/models/user.rb:192
      2 app/models/user.rb:406
      2 app/services/authorizer_cache.rb:12
      3 app/models/setting.rb:243
      3 app/services/authorizer.rb:48
      6 app/models/setting.rb:276
      7 lib/foreman/silenced_logger.rb:37
     11 app/helpers/hostgroups_helper.rb:7
     11 app/models/hostgroup.rb:243
     12 app/models/setting.rb:277
     20 app/models/role.rb:123
     37 app/models/concerns/taxonomix.rb:101
     37 app/models/concerns/taxonomix.rb:87
     74 app/models/concerns/taxonomix.rb:114
     74 app/models/taxonomy.rb:85
    158 app/models/user.rb:495
   1160 app/models/concerns/taxonomix.rb:61
   2541 app/models/user.rb:497

after: 
^Cmshira@dhcp-2-186:~/git/foreman(28957)$ cat production.log | grep ↳ | awk '{print $4}' | sort | uniq -c | sort -n
      1 app/controllers/application_controller.rb:31
      1 app/controllers/concerns/foreman/controller/migration_checker.rb:10
      1 app/helpers/layout_helper.rb:15
      1 app/helpers/layout_helper.rb:21
      1 app/helpers/layout_helper.rb:47
      1 app/services/authorizer.rb:18
      1 app/services/foreman_seeder.rb:56
      1 app/services/host_counter.rb:39
      1 app/services/topbar_sweeper.rb:17
      1 app/views/hostgroups/index.html.erb:15
      1 config/initializers/fix_cache.rb:6
      1 config/initializers/seeds.rb:3
      1 lib/foreman/middleware/logging_context_request.rb:11
      2 app/controllers/concerns/application_shared.rb:56
      2 app/controllers/concerns/foreman/controller/authentication.rb:10
      2 app/models/user.rb:189
      2 app/models/user.rb:193
      2 app/models/user.rb:407
      2 app/services/authorizer_cache.rb:12
      3 app/models/setting.rb:243
      4 app/models/user.rb:498
      4 app/services/authorizer.rb:48
      6 app/models/host/base.rb:54
      6 app/models/setting.rb:276
      7 lib/foreman/silenced_logger.rb:37
     11 app/helpers/hostgroups_helper.rb:7
     11 app/models/hostgroup.rb:243
     12 app/models/setting.rb:277
     20 app/models/role.rb:123
     25 app/models/host/base.rb:53
     33 app/models/user.rb:500
     37 app/models/concerns/taxonomix.rb:101
     37 app/models/concerns/taxonomix.rb:87
     74 app/models/concerns/taxonomix.rb:114
     74 app/models/taxonomy.rb:85
   1160 app/models/concerns/taxonomix.rb:61

**Comment by tbrisker** [comment]
@shiramax how does it affect the timings in `200 Completed` message?

**Comment by shiramax** [comment]
@tbrisker 
before:
2020-03-05T16:30:44 [I|app|c4cb8d3f] Completed 200 OK in 4666ms (Views: 4062.8ms | ActiveRecord: 62.9ms)
after:
2020-03-05T16:35:45 [I|app|9600cccf] Completed 200 OK in 3362ms (Views: 2848.9ms | ActiveRecord: 44.4ms)

**Review by tbrisker — APPROVED** [review]
Nice improvement! there is still plenty to improve, but this is a great step in the right direction. Thanks @shiramax !

**Comment by ares** [comment]
:clap:

**Pull request merged**
