### PR TITLE
Fixes #19161 - expand value plus icon change to minus icon after click

### PR DESCRIPTION
**Pull request by lizagilman**

### CODE REVIEW

**Comment by tbrisker** [comment]
add to PR whitelist

**Comment by ohadlevy** [comment]
@lizagilman can you please attach a before / after screenshot? thanks@

**Comment by lizagilman** [comment]
before:
before

after:
after

@ohadlevy

**Comment by lizagilman** [comment]
@tbrisker merge?

**Comment by tbrisker** [comment]
Thankgs @lizagilman !

**Pull request merged**
