### PR TITLE
Fixes #28130 - show selected machine_type on GCE host edit form

### PR DESCRIPTION
**Pull request by kgaikwad**
Adding @jyejare into loop for testing this GCE change.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Good catch! Seems ok, works well, I don't understand why the `server.machine_type` is not matching the `name` in `machine_types`, but I guess it's just a fog thing, right?

**Comment by ezr-ondrej** [comment]
Thanks @kgaikwad! Nice catch, it would deserve a fix in fog I believe, if you would be into it :)

**Comment by kgaikwad** [comment]
Thank you @ezr-ondrej for review.

Here the problem is with GCE compute API because when user fetches `machine_types` list API then it shows `name` and full URL path in `self_link` attribute.
In case of server, while creation compute API expects path in `machine_type` and in [GET server API](https://cloud.google.com/compute/docs/reference/rest/v1/instances/get) it returns full URL path in `machine_type`. 

But yes, `fog-google` should provide a method like `pretty_machine_type` which will return `name` not full path. Second thing if you see in [GET machine_type API](https://cloud.google.com/compute/docs/reference/rest/v1/machineTypes/get), it only takes `resourceId` as parameter which is nothing but `name`  of that machine_type.

I would like to hear your suggestions on how I can add fix on fog-google side with above scenario. 
I will be more happy to add it on fog-google side.

**Comment by ezr-ondrej** [comment]
Ok, from the reference it seems it's only us who don't need the fully qualified machine type, because we say that compute resource is tight with the zone. But if that wouldn't be the case, we would have to use the fully qualified machine types as they differ zone to zone, right?
It seems we should use the `self_link` as an identifier instead of name, but for our use case it doesn't really make sense :thinking: 
So only thing we could do is to patch the server to return the pretty name directly, or probably keep as is...

**Comment by kgaikwad** [comment]
@ezr-ondrej,

> Ok, from the reference it seems it's only us who don't need the fully qualified machine type, because we say that compute resource is tight with the zone. 

Yes.

> But if that wouldn't be the case, we would have to use the fully qualified machine types as they differ zone to zone, right?

I would say yes but it won't happen because for instance creation, zone is mandatory field for GCE.
So user has to select zone value first.

> It seems we should use the `self_link` as an identifier instead of name, but for our use case it doesn't really make sense 

For us, fog-google is doing [this](https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/requests/insert_server.rb#L84) already. 
It constructs the proper `machine_type` value using provided zone and machine_type's name.

**Pull request merged**
