### PR TITLE
Fixes #34913 - Take plugins into consideration when checking pending …

### PR DESCRIPTION
**Pull request by adamruzicka**
…migrations

### CODE REVIEW

**Comment by evgeni** [comment]
I didn't test this, but https://github.com/theforeman/foreman/blob/75e7c0bf6d3fa1049931ec9000a0819e72201a05/lib/tasks/plugins.rake#L19-L27 suggests this is a "known" issue (albeit, I'd wish Rails would just handle this for us correctly)

**Comment by ofedoren** [comment]
>
>  `# get loaded before environment`
>

Couldn't we update the `migrations_paths` whilst registering a plugin?..

**Comment by evgeni** [comment]
@upadhyeammit FYI, this is what's required to unbreak the plugin upgrades on 3.3 ;-)

**Comment by adamruzicka** [comment]
> Couldn't we update the `migrations_paths` whilst registering a plugin?..

We could and it seems to do the trick for this particular issue, but I cannot vouch for it not having any unforeseen side effects elsewhere.

**Comment by evgeni** [comment]
> > Couldn't we update the `migrations_paths` whilst registering a plugin?..
> 
> We could and it seems to do the trick for this particular issue, but I cannot vouch for it not having any unforeseen side effects elsewhere.

Yeah, I would vote for adding this particular band-aid now (and backporting it to 3.3 to fix the REX upgrade issue) and then re-visit ripping both band-aids off and replacing them with a nice fix later on with more time and less rush.

**Review by evgeni — APPROVED** [review]
this does fix the issue at hand, thanks Adam!

**Comment by evgeni** [comment]
picked to 3.3 as 661676842f2b39bf4515251f14cd734b01c3393d

**Pull request merged**
