### PR TITLE
Use PF4 styling for warning in registration form

### PR DESCRIPTION
**Pull request by stejskalleos**
Before:
alert_before

Now:
alert_now

### CODE REVIEW

**Comment by ares** [comment]
Is there an easy way to get the error message above the button? That was another recommendation, the submit button should but the last thing in the form. Everything below gets low attention form user.

**Comment by stejskalleos** [comment]
> Is there an easy way to get the error message above the button? 

Done.

**Comment by ares** [comment]
Looks much better now, could you please add some margin in between the Insecure field and the warning? It seems to close and indicates the error is related to the Insecure checkbox. I've tested ~15px

**Comment by ares** [comment]
For some reason, I can't see the spacing still but interestingly enough, it does not work only in General tab, in Advanced tab there is the spacing. It may be something on my setup, it would be great if someone can test and upload the screen shot. If that works is an oddity on my side (I tested both chrome and FF), I'm fine merging it.

EDIT: and I see the correct CSS class in the HTML source, could be a PF4 issue

**Comment by xprazak2** [comment]
I also noticed that styles sometimes do not get applied for pf4 util classes, [a small change](https://github.com/theforeman/foreman-js/pull/334) should take care of that but foreman-js version in core has not been bumped yet.

Anyway, this is how it looks on my setup:
keys-warning
keys-padding

**Review by ares — APPROVED** [review]
Thanks for confirmation @xprazak2, in such case I'm happy to merge. Thanks @stejskalleos for a nice improvement.

**Comment by ezr-ondrej** [comment]
CP 3.0: #8770

**Pull request merged**
