### PR TITLE
Fixes #26760 - Improve lookup of partially taxed audits

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
this solves the issue for me (as shown in https://gist.github.com/ohadlevy/72a1b9f63dd285feeb477d278eb08cac) thanks @tbrisker

**Comment by ezr-ondrej** [comment]
Why do we prefer class methods over scope? :)

**Comment by timogoebel** [comment]
I can confirm this speeds up the queries and they work fine in a larger environment. 👍 from my side

**Comment by tbrisker** [comment]
> Why do we prefer class methods over scope? :)

It just seemed to me like the logic is becoming a bit too complex for a scope, but I don't have a very strong preference either way. They are essentially the same behind the scenes.

**Comment by tbrisker** [comment]
test failure unrelated

**Comment by timogoebel** [comment]
> test failure unrelated

You're joking. I can't merge this.

[test foreman]

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @tbrisker. Nice one.

**Pull request merged**
