### PR TITLE
Fixes #6117 - clean usergroup cache

### PR DESCRIPTION
**Pull request by ares**
Dependent destroy was missing on through association from user side.

### CODE REVIEW

**Comment by dmitri-d** [comment]
I think I'm missing something -- I don't think the fix here has any effect on the problem described in #6117? I also cannot see any issues with assignment of groups to users -- could you clarify what the problem is please?

**Comment by ares** [comment]
When there's `has_many :through` you can specify `:destroy => true` which means that it should run destroy callbacks on 'through' objects, otherwise it just deletes them from DB. Since we were missing this for usergroups association we didn't run destroy callbacks on usergroup_member hence the cache was not deleted.

**Comment by dmitri-d** [comment]
Thanks, I understand the problem now. Could you add a test(s) pls? The docs aren't entirely clear on what will happen during assignment when `:dependent => :destoy` is present on a `:through` association.

**Comment by dmitri-d** [comment]
tested, looks good once a test has been added.

**Comment by ares** [comment]
Good idea, tests added, this is critical to work correctly. Btw it's documented at https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/associations.rb#L966

Please re-review and let me know whether I can merge.

**Comment by dmitri-d** [comment]
looks good (once tests pass). Yeah, should've looked at the source was quicker to test in the console :).

**Comment by ares** [comment]
hm, error does not seem to be related, maybe [test] will help

**Comment by ares** [comment]
Could anyone confirm whether rundeck issues can be ignored?

output of test:
http://ci.theforeman.org/job/test_develop_pr_core/1229/database=postgresql,puppet=3.0,ruby=1.8.7/testReport/junit/(root)/HostsControllerTest/test_0059_index_returns_YAML_output_for_rundeck/

**Comment by domcleal** [comment]
They can, yep (http://projects.theforeman.org/issues/4642)

**Comment by ares** [comment]
Thanks, merging then as 5db9d35307e6d8ce6e4558a8a554e526be729b8f

**Comment by domcleal** [comment]
Note for the future, please try to have somebody else merge commits, we don't merge our own.  (Also, one line commit msgs)

**Comment by ares** [comment]
Oh, sorry, I won't do it again.

**Pull request closed without merging**
