### PR TITLE
fixes #7257 - all facts returned if host has no facts

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@eLobato, can you look at this at it changes your commit e44f5c1c08d3f332b13fadd442dd754597db2b90

**Comment by isratrade** [comment]
@GregSutcliffe, can you review this PR?

**Comment by dLobatog** [comment]
@isratrade Thanks, it looks much cleaner than my clunky code. I'm usually not in favor of testing scoped_search -as 99% of the times it's retesting the library- but when we use custom SQL helpers I think we want to make sure they keep on working. 
You can test this though any functional test that tests FactValuesController.

:+1: to merge after the test

**Comment by domcleal** [comment]
They're a frequent source of bugs and regressions too, so tests for scoped_search extensions really are mandatory.  You can usually test search_for in a unit test, instead of a functional.

**Comment by isratrade** [comment]
unit tests added for scope search

**Comment by isratrade** [comment]
[test] got failure for sqlite3 only 'TEST-UsersControllerTest.xml.<init>'. Any ideas?

**Comment by isratrade** [comment]
now all tests are passing. No failure on sqlite3 for 'TEST-UsersControllerTest.xml.'

**Comment by domcleal** [comment]
Link to the original failure?

**Comment by isratrade** [comment]
@domcleal, http://ci.theforeman.org/job/test_develop_pr_core/2299/ is link to original sqlite3 failure

**Comment by domcleal** [comment]
@isratrade thanks, out of space error, now fixed

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/738a8d23c8e485e51573cebd459cf20f2495d940 , thanks @isratrade !

**Pull request closed without merging**
