### PR TITLE
Fixes #15268 - limit user taxonomies using my scopes

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares All looks good to me - Would you mind to write a test to verify some of these actions (one per controller) - like:
- GET api/v2/organizations
- DELETE api/v2/locations/unaccessiblelocation fails when user doesn't have the location but has permission to delete locations
- Some UI action

Thanks!

**Comment by ares** [comment]
I've added tests you asked for and added CVE identifier that we received in the commit message. Please take another look.

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
[test] HostJSTest::NIC once again

**Comment by ares** [comment]
[test] again, let's try last time

**Comment by dLobatog** [comment]
@ares Sorry, it looks like there are a few Katello tests that break after this change - http://ci.theforeman.org/job/test_katello_core/19025/

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
katello fix PR opened, they can merge the PR ahead of this, test results with both PRs are green - http://ci.theforeman.org/job/test_katello_core/19089/ removing WoC

**Comment by jlsherrill** [comment]
[test]

**Comment by ares** [comment]
@dLobatog all is green now, Katello is ready for this PR, would you mind taking another look?

**Comment by dLobatog** [comment]
Merged as a30ab44ed6f140f1791afc51a1e448afc2ff28f9, thanks @ares!

**Pull request closed without merging**
