### PR TITLE
Refs #28468 - Misspelling on login page

### PR DESCRIPTION
**Pull request by Ron-Lavi**
cherry-pick the commit from #7237 
and fix the relevant locales.

luckily, the strings were not translated yet.

### CODE REVIEW

**Comment by tbrisker** [comment]
please also update the strings in the locale folder, and i guess we would want to cp it to 1.24-stable as well?

**Comment by Ron-Lavi** [comment]
thanks, added more fixes to the locales,
after this would get merged would it be possible to cherry-pick the commit to 1.24-stable?

**Comment by Ron-Lavi** [comment]
opened also cp PR to 1.24 - https://github.com/theforeman/foreman/pull/7246

**Review by tbrisker — APPROVED** [review]
Thanks @laviro

**Pull request merged**
