### PR TITLE
Refs #29474 - adds destroy callback

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Forgotten destroy callback.

### CODE REVIEW

**Review by tbrisker — COMMENTED** [review]
I intentionally didn't add the destroy since it never ran - after_save is only triggered on create and update. Also if you look at the callback, it doesn't actually make sense in the case of destroy.

**Comment by ezr-ondrej** [comment]
> I intentionally didn't add the destroy since it never ran - after_save is only triggered on create and update. Also if you look at the callback, it doesn't actually make sense in the case of destroy.

I'd disagree ... it definitelly make sense for it to run :thinking: not sure if the `saved_change_to_<>` would be true on destroy, but the title should be updated on destroy, right?

**Comment by tbrisker** [comment]
> > I intentionally didn't add the destroy since it never ran - after_save is only triggered on create and update. Also if you look at the callback, it doesn't actually make sense in the case of destroy.
> 
> I'd disagree ... it definitelly make sense for it to run thinking not sure if the `saved_change_to_<>` would be true on destroy, but the title should be updated on destroy, right?

Only there can't be any children on destroy, so there won't be anything to update the title for: 

https://github.com/theforeman/foreman/blob/develop/app/models/concerns/nested_ancestry_common.rb#L7 

https://github.com/stefankroes/ancestry#options-for-has_ancestry

**Comment by ezr-ondrej** [comment]
> Only there can't be any children on destroy, so there won't be anything to update the title for:

Right, I've missed that one :man_cartwheeling: closing :+1:

**Pull request closed without merging**
