### PR TITLE
[WIP][DO NOT REVIEW] Rails 6 for katello tests

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Digging into the locale issue with katello, it seems that this line:
https://github.com/Katello/katello/blob/master/lib/katello/engine.rb#L23

seems to cause the locales to not be loaded before the 'warn_if_autoloaded' initalizer to run.  this rails initializer seems to throw a warning and wants to i18n the message.  But for some reason katello adding an initializer ':before => :load_config_initializers' seems to either cause 'warn_if_autoloaded' to be run before config/initializers/1_fast_gettext.rb  or else somehow prevents config/initializers/1_fast_gettext.rb from being run at all.

This method of using '':before => :load_config_initializers' is what is recommended in developer_docs/how_to_create_a_plugin.asciidoc (so it may not be just katello that is affected).  If i remove the ':before => :load_config_initializers", the app loads fine (but i am guessing something else may be broken)

**Comment by mmoll** [comment]
This does not happen in other plugin tests on Jenkins.

Although it might be because of the fact that in these tests, the plugin is introduced later to the build....

**Comment by tbrisker** [comment]
>  If i remove the ':before => :load_config_initializers", the app loads fine (but i am guessing something else may be broken)

IIUC, the reason this needs to run before initializers is the runcible initializer needs one of these settings - https://github.com/Katello/katello/blob/master/config/initializers/runcible.rb.
Perhaps we could move that one initializer to run `after: 'katello.load_default_settings'` and remove the `before` here?

**Comment by mmoll** [comment]
@jlsherrill :point_up:

**Comment by jlsherrill** [comment]
Opened a pr here to test a couple things wrt the initializer: https://github.com/Katello/katello/pull/8676

**Comment by jlsherrill** [comment]
[test katello]

**Comment by tbrisker** [comment]
[test upgrade]

**Comment by tbrisker** [comment]
Looks like it's all green! upgrade is failing on sqlite, need to drop that one as well.

**Comment by mmoll** [comment]
Let's continue in GH-7609

**Pull request closed without merging**
