### PR TITLE
Fixes #7451 - Review whitespace in extracted strings

### PR DESCRIPTION
**Pull request by ofedoren**
related to: https://github.com/theforeman/hammer-cli-foreman/pull/349

### CODE REVIEW

**Comment by tstrachota** [comment]
:+1: it makes that 3 messages consistent with the rest of the API action descriptions.

**Review by lzap — APPROVED** [review]
Thanks merging then.

**Comment by ares** [comment]
@lzap this PR was not tested in jenkins, the ticket is not assigned to Foreman in redmine, it should have not been merged like that, please pay attention to what @theforeman-bot says

**Comment by lzap** [comment]
:man_facepalming:

**Pull request merged**
