### PR TITLE
Fixes #29960 - set PrivateTmp=true in foreman.service

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
IMHO a candidate for cherry pick to 2.4.

**Comment by evgeni** [comment]
[test katello]

**Comment by ekohl** [comment]
I'm going to merge this. The katello appears unrelated and that can't run systemd services anyway.

**Comment by ezr-ondrej** [comment]
CP 2.4: #8356

**Pull request merged**
