### PR TITLE
Fixes #13896 - Rename Anonymous role to Default role

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by unorthodoxgeek** [comment]
:+1:

**Comment by domcleal** [comment]
Could you rebase this please @tbrisker?

**Comment by tbrisker** [comment]
@domcleal rebased, thank you.

**Comment by dLobatog** [comment]
Please notice http://www.theforeman.org/manuals/1.10/#4.1.2RolesandPermissions needs to be updated accordingly

**Comment by domcleal** [comment]
It can be added to https://github.com/theforeman/theforeman.org/issues/555 for 1.12.

**Comment by domcleal** [comment]
Merged as a2b3be5, thanks @tbrisker.

**Pull request closed without merging**
