### PR TITLE
Fixes #26652 - Refactor folder structure of ToastList

### PR DESCRIPTION
**Pull request by MariaAga**
currently is:

<pre>
toastNotifications
├── __snapshots__
├── index.js
├── ToastList.fixtures.js
├── ToastList.stories.js
└── ToastList.test.js

</pre>
should be:
<pre>
ToastList
├── __snapshots__
├── ToastList.js
├── index.js
├── ToastList.fixtures.js
├── ToastList.stories.js
└── ToastList.test.js

</pre>

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Glad to see moving legacy stuff towards the standard structure, good job :+1:
Wouldn't be worth it to move the redux actions as well, while we are touching the component already? :)

**Comment by MariaAga** [comment]
@ezr-ondrej, Thanks, you're right! I'll move them

**Comment by ezr-ondrej** [comment]
But I guess can be follow up PR, if you don't want to make this one too big, I think that would be ok as well :)

**Comment by MariaAga** [comment]
I see now that other components then ToasterList are using the toasts actions (Like `webpack/assets/javascripts/react_app/redux/actions/common/forms.js` and `webpack/assets/javascripts/foreman_toast_notifications.test.js`).
So I'm not sure if I should move the redux actions as well.
@ezr-ondrej, what do you think?

**Comment by ezr-ondrej** [comment]
Oh, I see, I think it should be moved anyway, but not in this PR, as I believe there is going to be a discussion about that :)
I hope there is going to be agreement not to move it here, so i will test it later today and ACK :+1:

**Comment by tbrisker** [comment]
ok to test

**Comment by ohadlevy** [comment]
ping @sharvit ?

**Review by ezr-ondrej — APPROVED** [review]
Works as expected, good job :+1:

**Review by tbrisker — APPROVED** [review]
Thanks @MariaAga !

**Pull request merged**
