### PR TITLE
Fix Rubocop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
this looks good, any idea why hound / ci didn't find these earlier? (just wondering how we got here?)

**Review by ohadlevy — APPROVED** [review]

**Comment by mmoll** [comment]
We don't run these on the CI, so once in, we can't detect it. Hound should have been red (AFAICT), but I'm unsure if it was in these PRs.

**Comment by ekohl** [comment]
Hound only looks at the diffs AFAIK, not the full picture. That means you never fix your past mistakes.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
