### PR TITLE
Fixes #37189 - Registration before & after snippets

### PR DESCRIPTION
**Pull request by stejskalleos**
`before_registration` & `after_registration` snippets allow users to add their code to the template without directly editing it.

### CODE REVIEW

**Review by nofaralfasi — APPROVED** [review]
LGTM.
I also suggest adding it to the [documentation](https://github.com/theforeman/foreman-documentation).

**Comment by maximiliankolb** [comment]
Hey @stejskalleos 

I like the idea as previously expressed during discussions/reviews in foreman-documentation. However, why did you go with these names and not "Global Registration custom pre" and "... post"? 

```
$ rg custom
...
app/views/unattended/provisioning_templates/finish/kickstart_default_finish.erb
35:<%= snippet_if_exists(template_name + " custom pre") -%>
83:<%= snippet_if_exists(template_name + " custom post") -%>
...
same for Preseed/AutoYaSt templates
```

**Comment by stejskalleos** [comment]
> However, why did you go with these names and not "Global Registration custom pre" and "... post"?

I liked `before_registration` more than `Global Registration custom pre`. I wanted to do it the same way as the Rails callbacks.

**Comment by ekohl** [comment]
My objection is that now they're not alphabetically sorted together. A suffix will naturally group them together when you browse.

**Pull request merged**
