### PR TITLE
Refs #3809 - Remove cop AssignmentInCondition

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by daviddavis** [comment]
Not a huge fan of this cop but the code looks good.

**Comment by ares** [comment]
I would prefer avoiding this one, I'm used to github guidelines (https://github.com/styleguide/ruby) which allows this.

**Comment by daviddavis** [comment]
We allow it in Katello as well:

http://git.io/NHQX

**Comment by domcleal** [comment]
I don't mind either way, but looks like we're heading towards 'no'.

**Comment by dLobatog** [comment]
Ok, I'll close in a few days if no one else pitches in, thanks for the comments :smile:

**Comment by dLobatog** [comment]
[test] because of the latest enabled cops

**Comment by dLobatog** [comment]
Closed by popular demand

**Pull request closed without merging**
