### PR TITLE
fixes #19419 - invalid syntax

### PR DESCRIPTION
**Pull request by plessbd**

### CODE REVIEW

**Comment by timogoebel** [comment]
@plessbd : Thanks for fixing this. I'll quickly kick off our ci pipeline, then we're ready to merge.

@theforeman-bot ok to test

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Tests fail because of `validates_length_from_database`. This is unrelated, however I'd like to wait for it to be fixed before merging this.

**Comment by timogoebel** [comment]
[test foreman]
[test katello]
[test upgrade]

New version of `validates_length_from_database` has been released. Re-kicking the ci pipeline.

**Comment by tbrisker** [comment]
[test foreman]

**Comment by timogoebel** [comment]
[test foreman]

**Comment by tbrisker** [comment]
Merged as 704659e68fd9f11c5d95b96a64c165fc4d750cf7 with minor change to commit message, thanks @plessbd!

**Pull request closed without merging**
