### PR TITLE
Fixes #13233 - Minor changes in proxy show page and related js

### PR DESCRIPTION
**Pull request by xprazak2**
Changes in Foreman to display Pulp status. I split proxy_status into separate files + minor changes in js.

### CODE REVIEW

**Comment by ohadlevy** [comment]
there is a lot of overlap between #3069 and #3018 ?are you guys aligned?

**Comment by shlomizadok** [comment]
apparently, not aligned.

**Comment by domcleal** [comment]
Marking as WoC due to @ohadlevy's comment above.  The ticket is also from another project, please use a specific one and have a commit message that reflects the actual change (it doesn't add Pulp status, as far as I can see.)

**Comment by xprazak2** [comment]
Is replaced by #3069, closing.

**Pull request closed without merging**
