### PR TITLE
Fixes #23235 - Disable Style/IfUnlessModifier cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
I'd argue this is less readable code. The lines are typically long and you might not see the if/unless at the end. Should we just disable this cop?

**Comment by mmoll** [comment]
That syntax is quite Ruby-esque and personally I slightly like it, but I'm also happy to disable that cop.

**Comment by ares** [comment]
I like the statement modifier syntax but only where it makes sense. No syntax linter can decide that. +1 for disabling this cop.

**Comment by mmoll** [comment]
there we go :)

**Review by ekohl — APPROVED** [review]

**Review by lzap — APPROVED** [review]

**Comment by mmoll** [comment]
anybody? :)

**Comment by lzap** [comment]
3 vs 1, I think this one is not sensitive, merging, thanks!

**Pull request merged**
