### PR TITLE
Fixes #25476 - downgrade fog-openstack to 0.2.0

### PR DESCRIPTION
**Pull request by pyslarvt**

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
This matches what we currently package in RPM (0.1.25). @ares - how does this stand wrt the fog-core upgrade?
Long term I think we'll need to update the code in Foreman to work with newer versions of the gem.

**Comment by ares** [comment]
This would not be compatible, we need fog-openstack >= 1.0.0 after we upgrade fog-core to 2.1.0. I'll see what was the progress on GCE side. I also added this action item to the plan on discourse.

**Comment by tbrisker** [comment]
@pyslarvt we are currently in the process of upgrading all of our fog dependencies to more recent versions, would you be able to look into upgrading fog-openstack to a new version and fixing what needs to change on the foreman side?

**Review by tbrisker — APPROVED** [review]
Merging this for now until we update fog-core as that will require further changes anyways. 
Thanks @pyslarvt ! If you are able to work on making openstack changes to make it compatible with fog-core 2.1, please comment on the discussion at https://community.theforeman.org/t/big-provisioning-libraries-update-and-test/12809.

**Comment by tbrisker** [comment]
Cherry picked to stable branches as:
1.21 - 5e5ff43ac
1.20 - 49416d084

**Comment by pyslarvt** [comment]
> @pyslarvt we are currently in the process of upgrading all of our fog dependencies to more recent versions, would you be able to look into upgrading fog-openstack to a new version and fixing what needs to change on the foreman side?

Hello. I would be glad to contribute to the project but I am not a ruby developer so I am not sure that my programming skill is enough to do this kind of job. I'll see the code to evaluate my abilities and let you know if I can help.

**Pull request merged**
