### PR TITLE
fixes #26724 add dashboard background color

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
before
image

**Comment by ohadlevy** [comment]
after
image

**Comment by ohadlevy** [comment]
[test katello]

**Review by sharvit — APPROVED** [review]
Thanks @ohadlevy,
@theforeman/ui-ux do you aware of other pages with the same issue?

**Comment by ohadlevy** [comment]
I would say the next candidate is the statistics page?

**Comment by xprazak2** [comment]
Looks good, just one question: the [patternfly cards](https://www.patternfly.org/pattern-library/content-views/card-view/) seem to have white background while we have `rgba(255, 255, 255, 0.5) ` which makes the widgets slightly gray-ish. 
Do we want to adjust it or keep as is?


rgba(255, 255, 255, 0.5)
alpha-point-zero

rgba(255, 255, 255, 1)
alpha-one

**Comment by ohadlevy** [comment]
I personally don't mind, anyone else? :) /ping @theforeman/ui-ux

**Comment by Ron-Lavi** [comment]
My screen doesn't show the difference :cry:
should I visit the optometrist ?

**Comment by Rohoover** [comment]
I'd recommend following the PF color of white. It also provides the contrast needed for accessibility issues.

**Comment by ohadlevy** [comment]
> I'd recommend following the PF color of white. It also provides the contrast needed for accessibility issues.

@Rohoover to clarify, you suggest that we keep the background as proposed in this PR and change the card to white based on @xprazak2 suggestion? double asking as I'm not certain what you mean :)

**Pull request closed without merging**
