### PR TITLE
Fixes #35319 - host card remove isSelectable

### PR DESCRIPTION
**Pull request by MariaAga**
Cursor should be default and not pointer when hovering cards in the new host details page.
https://github.com/theforeman/foreman/pull/9054#discussion_r818501017
https://github.com/theforeman/foreman/pull/9189#discussion_r852379274

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
Thanks @MariaAga 

Needs a rebase..

Works great on cards that use CardTemplate, but many cards on Overview and in Katello don't use it. They should be updated as well.

**Comment by MariaAga** [comment]
Thanks! Didn't see them as they used `isHoverable`. Will open pr in Katello as well. Didn't find it in any other plugin

**Comment by MariaAga** [comment]
https://github.com/Katello/katello/pull/10252

**Review by jeremylenz — APPROVED** [review]
Changes look good, thanks! ACK :+1:

**Pull request merged**
