### PR TITLE
Fixes #37085 - Add netiq as an authentication source

### PR DESCRIPTION
**Pull request by knoppi**
- Bump version of ldap_fluff to the next version
- Add netiq to LDAP auth-sources

This PR is a consequence of [Bump version to 0.7.0 #80](https://github.com/theforeman/ldap_fluff/pull/80) and [Add NetIQ ldap-flavour #71](https://github.com/theforeman/ldap_fluff/pull/71)

### CODE REVIEW

**Comment by adamruzicka** [comment]
Why was the previous PR (#10269) closed?

**Comment by knoppi** [comment]
> Why was the previous PR (#10269) closed?

That was some kind of mis-click. Better to continue the old PR?

**Review by sbernhard — APPROVED** [review]
LGTM. Thanks.

**Review by Thorben-D — CHANGES_REQUESTED** [review]
IMO, it would make sense to update the [AuthSource welcome page](https://github.com/theforeman/foreman/blob/1a5c1b9b2b35f88a8ec177bd76ae5d3e280a7d81/webpack/assets/javascripts/react_app/components/AuthSource/Welcome.js#L15-L25) to reflect this change.
On a similar note: Is there a PR to add docs for this?

**Comment by sbernhard** [comment]
> IMO, it would make sense to update the [AuthSource welcome page](https://github.com/theforeman/foreman/blob/1a5c1b9b2b35f88a8ec177bd76ae5d3e280a7d81/webpack/assets/javascripts/react_app/components/AuthSource/Welcome.js#L15-L25) to reflect this change. On a similar note: Is there a PR to add docs for this?

I would not do this. There a hundreds of possible products out there. We should not list every single one.

**Review by adamruzicka — APPROVED** [review]

**Review by evgeni — APPROVED** [review]

**Comment by knoppi** [comment]
Thanks!

**Pull request merged**
