### PR TITLE
Fixes #17255 - authorizer supports admin users

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by tbrisker** [comment]
Test failure unrelated, merging. Thanks @ares!

**Comment by tbrisker** [comment]
Oops, should have clicked the button to expand the entire function before clicking on merge. 
Could you please remove https://github.com/theforeman/foreman/pull/4000/files#diff-2a8c1ced7ef4dfe08f35154c5a3ef0f1R19 which is now a noop?

**Comment by ares** [comment]
oh, good catch, will do as a separate issue

**Comment by ares** [comment]
@tbrisker addressed by https://github.com/theforeman/foreman/pull/4004

**Pull request merged**
