### PR TITLE
Refs #27906 - Clean up PuppetFactParser

### PR DESCRIPTION
**Pull request by ekohl**
As a preparation to moving to modern facts, this refactor cleans up the operatingsystem method to make a future refactor easier.

### CODE REVIEW

**Comment by lzap** [comment]
This PR references a most likely incorrect issue number. Also there are relevant test failures.

**Comment by ekohl** [comment]
Yes, should have marked this as WIP

**Comment by tbrisker** [comment]
test failures seem related

**Comment by ekohl** [comment]
Looks like the issue was `gsub!` where I should have used `gsub`. Ready for review now.

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
In a future patch we should start to use the `os` fact which is present in at least facter 2.3:
https://github.com/theforeman/foreman/blob/6dd32db0a81062a258e3508c4a65c8fe2f0d16b9/test/static_fixtures/facts/facts_freebsd_stable.json#L5-L13

On more recent versions it's more complete (may need `lsb-release` installed for facts like `codename`):
```json
{
  "os": {
    "architecture": "amd64",
    "distro": {
      "codename": "buster",
      "description": "Debian GNU/Linux 10 (buster)",
      "id": "Debian",
      "release": {
        "full": "10",
        "major": "10"
      }
    },
    "family": "Debian",
    "hardware": "x86_64",
    "name": "Debian",
    "release": {
      "full": "10.1",
      "major": "10",
      "minor": "1"
    },
    "selinux": {
      "enabled": false
    }
  }
}
```

**Review by ares — APPROVED** [review]
Tested, works well, thanks @ekohl, merging!

**Pull request merged**
