### PR TITLE
fixes #2411 Refactor /lib directory and STI /models

### PR DESCRIPTION
**Pull request by isratrade**
as well as app/models/concerns or app/controllers/concerns and app/services, plus other code cleanups

### CODE REVIEW

**Comment by isratrade** [comment]
Test failures on MySql on Ruby 1.8.7 and 1.9.3 but passes 1.9.2 ???

**Comment by ohadlevy** [comment]
@isratrade looks good, I think I would keep the proxy and the net stuff under lib, as they are realy libs to communicate with external services (and could become a gem) - what do you think?

**Comment by domcleal** [comment]
@isratrade ignore those failures, they should be fixed by GH-528.

**Comment by isratrade** [comment]
@ohadlevy sounds good. I can put the proxy and net stuff back in lib.

**Comment by ohadlevy** [comment]
@isratrade can you rebase please?

**Comment by isratrade** [comment]
@ohadlevy, rebased and ready to be merged. Should I added another commit to change the STI_PREFIX of ComputeReosurce and the file locations of the sti models.

**Comment by domcleal** [comment]
Sorry to have been slow on reviewing, but I'm going to wait until post-1.2 before looking at this again - it's going to be too disruptive to other PRs at this stage.  Let's revisit in a few weeks.

**Comment by isratrade** [comment]
closing.  will re-submit later.  Some commits were extracted to pr #614

**Pull request closed without merging**
