### PR TITLE
Fixes #30604 - replace mount_react_component in ReactApp

### PR DESCRIPTION
**Pull request by MariaAga**
replaces mount_react_component with react_component in ReactApp.
Changes were made to resolve `mounting layout after the container to change its width if the navbar is collapsed`

### CODE REVIEW

**Comment by amirfefer** [comment]
[test foreman]

**Comment by MariaAga** [comment]
Test failures aren't related and fixed in: https://github.com/theforeman/foreman/pull/7962

**Comment by xprazak2** [comment]
@MariaAga could you rebase please to see if the tests turn green?

**Comment by MariaAga** [comment]
test failures look unrelated

**Comment by xprazak2** [comment]
Yeah, I have seen those on other PRs as well.

**Review by xprazak2 — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
[test foreman] should pass now

**Comment by ezr-ondrej** [comment]
We are :green_apple: @xprazak2 ?

**Review by amirfefer — APPROVED** [review]
Tested and works as expected, Thanks @MariaAga, @xprazak2 , @ezr-ondrej

**Pull request merged**
