### PR TITLE
Fixes #2817 - wrong param types in lookup keys api documentation 

### PR DESCRIPTION
**Pull request by tstrachota**
There is no parameter type :boolean. :bool must be used for true/false values.
Wrong type was breaking lookup controller apidoc page.

### CODE REVIEW

**Comment by domcleal** [comment]
apidoc works for me, which apipie version are you on?

**Comment by tstrachota** [comment]
0.0.22
Try loading api v2 documentation index page

**Comment by domcleal** [comment]
apidoc_v2

**Comment by domcleal** [comment]
Ok, I've no idea why it works for me, but I can see it matches the other controllers and that apipie only has :bool in the code.  Could you file a redmine bug please, and add this tot he commit message?  Thanks.

**Comment by domcleal** [comment]
ping @tstrachota

**Comment by tstrachota** [comment]
Updated http://projects.theforeman.org/issues/2817

**Comment by domcleal** [comment]
Merged as c70fcb7, thanks @tstrachota!

**Pull request closed without merging**
