### PR TITLE
fixes #15977 - change enc output in a compatible way

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by dLobatog** [comment]
Fair enough, although this will be a breaking change for 1.12 users who rely on it :smile: 
Can you call it organization_title? It's just because we use _title in some places in the application to refer to the full name. Thanks @timogoebel !

**Comment by timogoebel** [comment]
> Fair enough, although this will be a breaking change for 1.12 users who rely on it 😄

Yes, I know. Too bad I didn't spot this earlier. Naming ENC parameters is always a hard thing. Will change the parameter name in a sec.

**Comment by dLobatog** [comment]
Merged as b96e021026cdcc6918c61d246dbf5c7baabfc1b4, thanks @timogoebel!

**Comment by timogoebel** [comment]
@domcleal / @dLobatog : Can we put this on 1.12.2? What do you think? I'd be in favor of it.

**Pull request closed without merging**
