### PR TITLE
Return unsorted facts to improve /fact_values performance

### PR DESCRIPTION
**Pull request by xorpaul**
With around 150k facts and 7k hosts clicking the fact tab in the foreman GUI takes around 4-6 seconds.

https://gist.github.com/xorpaul/7232272

@ohadlevy suggested this patch to cut the time for the first SQL query down to a few milliseconds.

If this shouldn't be the default, maybe a config parameter or a smart switch (if the number of facts is above $THRESHOLD) should be possible.

### CODE REVIEW

**Comment by skottler** [comment]
[test]

**Comment by domcleal** [comment]
Okay, I don't mind this change as the default ordering (by value) is weird enough that this makes no discernible difference.  Though rather than reorder, we'd remove `:default_order => true` from value in app/models/fact_value.rb as otherwise this prevents explicit column sorting from working too.

My only concern is what happens to pagination if we remove all ordering.  Both PostgreSQL and MySQL seem to treat this as undefined behaviour - if we ask for items 1-20, and then the user clicks the next page, there's no guarantee that the result set will be ordered the same.  I wonder if sorting speed would change if we used a different field (like a primary or indexed key)?  @witlessbird, any thoughts?

**Comment by dmitri-d** [comment]
@domcleal: Hmm, don't think I like the idea of removing ordering: "whatever order the system finds fastest to produce" doesn't inspire confidence in seeing the same order of records on same queries. Index use during sorting depends on the db: MySQL may or may not use it; Postgres can have sorted indexes (see http://www.postgresql.org/docs/8.3/static/indexes-ordering.html).

Probably worth a look into query execution plans?

**Comment by domcleal** [comment]
I've filed this as http://projects.theforeman.org/issues/3886 for further work, as I'm not sure now that removing the sorting is best.  Ideally we should find a better way to increase performance, like the sorted indexes referred to above.  The addition of nested fact support will mean some sorting on the fact_values page is more important.

Thanks for opening the PR @xorpaul, but we'll need to revisit this later.

**Pull request closed without merging**
