### PR TITLE
fixes #4565 - class params search is now significantly faster

### PR DESCRIPTION
**Pull request by lzap**
Don't ask me why, credit to @abedari

### CODE REVIEW

**Comment by domcleal** [comment]
Do you mean the class search is faster?  As far as I can see, you've _disabled_ class param searching by default, not made it faster.

**Comment by ohadlevy** [comment]
@domcleal only_excplict means that it is not included in the free text search, rather only when you would type key = ...

**Comment by abenari** [comment]
"Free text" searches in scoped search is done by querying all the searchable field. This can make the free-text search create complicated joins.
In this case searching for puppet class by its keys name (puppet class parameters) on a db with large set of puppet classes and environments caused many seconds query (dropped to ms after applying the patch)
+1 from me

**Comment by domcleal** [comment]
@ohadlevy indeed, which is why the commit message seemed at odds with the diff

**Comment by ohadlevy** [comment]
@lzap +1 to what @domcleal said then :)

**Comment by abenari** [comment]
yes commit message should be 'puppet class free-text search in now faster'

**Comment by domcleal** [comment]
Merged as 0126385 for Foreman 1.4.2, thanks @lzap and @abenari.

**Pull request closed without merging**
