### PR TITLE
Fixes #24817 - Add VM UUID info to vmware compute resource page

### PR DESCRIPTION
**Pull request by chris1984**
End result looks like this:

https://s.nimbusweb.me/share/2048726/2axee0sa6v502vtcnrwq

### CODE REVIEW

**Comment by chris1984** [comment]
@timogoebel can I get a review please?

**Comment by timogoebel** [comment]
I‘m on pto this week, but the code looks good on my phone. I‘m just wondering if it makes sense tobactually show this data to a user. What use case does this solve?

The associated issue asks for the info to be present in the API. It should already be present on the host index and show actions.
And the issue states, that the vm uuid was generated by Foreman - but it is not. The uuid is generated and used by vSphere, Foreman just saves it in the db to link the host to the vm.

**Comment by ohadlevy** [comment]
I had the same question as @timogoebel - whats the value of showing the uuid? (if for example there is a use case to use the same id for hammer for example, maybe we can have a complete hammer command example and not just the uuid). another thing to consider is to add it to the vm show page, or on hover instead of using the table?

**Comment by ares** [comment]
If it's already present in API that's fine, Abut it probably doesn't hurt to have it in UI too. IIUC listing UUID in host API is too late, we need to find the UUID of VM before it even exists as a host. The user could associate host created by registration (not provisioning) and this vm.

Showing it in table is IMHO useful, if I'm searching for VM and find it, I get the value right away. Using hover would make it hard to ctrl C. If table is bad place, then I vote for vm show page.

**Comment by chris1984** [comment]
We have it in the VM tab currently today in 6.3:

http://nimb.ws/ykEv2D

I just wanted to add it to the compute resource page as well:

http://nimb.ws/2d7qSp

**Comment by ares** [comment]
Chris, your screen shows host detail page, not vm detail page. That's the same thing that applies to host API, it's too late. IIUC user request, they want to find the VM by UUID and associate it with existing host created by registration (unmanaged host not linked to any compute resource). Therefore they wouldn't see this UUID on host page until they associate the VM

**Comment by chris1984** [comment]
@ares ah true, to get that info I did have to associate it. I still think this is a valid PR though.

**Comment by ares** [comment]
and apparently we already have it on vm detail page
vm

**Comment by ares** [comment]
and it seems we don't expose API to list compute resource VMs, only to associate all VMs

**Comment by ares** [comment]
yes, I don't object that, but the original task was

```
it would be very useful for us to be able to perform a lookup to match the Satellite UUID with the vSphere UUID, and the easiest way for doing this is for Satellite to expose that information through the API somehow.
```

and it's not addressed by this PR. The information already is in webui and you're adding it to another place too

I don't know how complicated it would be adding a vm listing to our API, but that would solve the issue that this PR is linked to

**Comment by timogoebel** [comment]
Then let‘s add the vm listing to the API so hammer can use that. I don‘t think the uuid in the index table will actually help anyone. Sorry, Chris. Extending the API is more fun to implement, so see it as a chance to learn more ruby. :-)
Can we also add a workflow to the ui to associate a single host. We already have that when you view a vm, let‘s add that to the host page as well. Something like „Foreman has found this host on CR younameit.example.com. Click here to link it to this host.“ That might be a little more difficult to do, but has a great UX. We also have a host import from VM workflow, we could extend that and do more than associating the Vm. Copying UUIDs seems very technical to me. There should be a better way.

**Comment by chris1984** [comment]
Closing for now to help lower the stale Foreman PRS, will revisit when I get my other 6.5 GA stuff done.

**Pull request closed without merging**
