### PR TITLE
Refs #21997 - pin excon gem

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
excon is a dependency of fog-core, taking the `~> 0.58` requirement from it. The pinning is to fix the tests for now. Once the RPM packaging is on tfm-ror51, the real update task can be worked on.

**Review by boaz0 — APPROVED** [review]
LGTM 💯

**Review by tbrisker — CHANGES_REQUESTED** [review]
@mmoll can you please add a comment inside the Gemfile so we don't forget why this was pinned and keep it like that forever?

**Comment by mmoll** [comment]
sure, updated

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
APJ

**Comment by tbrisker** [comment]
Test failure unrelated. Thanks @mmoll !

**Pull request merged**
