### PR TITLE
fixes #2109 - improve session token security

### PR DESCRIPTION
**Pull request by domcleal**
- adds security:generate token rake task to create static token
- generate and cache a token on startup if static token isn't present

Thanks to Sandor Szücs sandor.szuecs@fu-berlin.de

### CODE REVIEW

**Comment by ohadlevy** [comment]
@domcleal looks good, one concern is that if tmp is trashed (e.g. in a crontab) or if you use a multi head foreman (e.g. no sharing of tmp dir) this wont work.

regardless, seems way better than what we currently have.

**Comment by domcleal** [comment]
Yep, tmp/ is also on tmpfs (/run) on Fedora 17+ so every reboot there.  I thought it was a reasonable compromise, since it'll only affect current sessions.  Having the webapp rewrite its own files is going to cause pain with SELinux etc in the future.

If we update the packages to run the rake task post-install (and mark it `%config(noreplace)`), then that'll help most people and other users can run the rake task to get a permanent token.

**Comment by domcleal** [comment]
Comment from Sandor on the ticket itself: "It's not a good idea to use activesupport's SecureRandom, because they removed it: https://github.com/rails/rails/commit/1170cceaaec8c0c8aef173913405be1456e4b2be#activesupport/lib/active_support"

That's a bit of a pain if we were to update to Rails 3.2 but still support Ruby 1.8.  I'll look for another solution.  I dislike the original /dev/random implementation, as it required lots of entropy to generate a short token and would block startup.

**Comment by domcleal** [comment]
Ruby 1.8.7 (our minimum version) had the securerandom library backported, so I've changed it to simply use this.

**Comment by ohadlevy** [comment]
another issue i see, is that via packaging the config/initializer directory might not be writable? also via git, its currently checked it, and the rake tasks rewrite it? (so its flagged as modified)

**Comment by domcleal** [comment]
Foreman itself will only write to `tmp/secret_token` so that will be writable.  The admin would be running the rake task as root if they wanted a static token, so that won't have permissions problems.

Good point on the git modification, perhaps I'll split it into a local_secret_token.example.rb and make it write local_secret_token.rb, then add the latter to gitignore.

**Comment by domcleal** [comment]
Updated branch as per above.

**Comment by ohadlevy** [comment]
merged - thanks Sandor and @domcleal!

**Pull request closed without merging**
