### PR TITLE
fixes #11023 - Downgrade fog to 1.31.0 until OpenStack issue resolved

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
A downgrade's quite a severe step to take, is there no other way forwards?  Is a change in our code required or possible, or even a fog_extension to change its behaviour?  Failing that, I'd probably prefer to live with 1.32.0 and some temporary brokenness and take 1.33.0 immediately, assuming a fix is merged.

**Comment by domcleal** [comment]
Note that we recommend people put the version number into the OpenStack URL (see app/views/compute_resources/form/_openstack.html.erb), has Fog changed to mean the version goes into some other attribute instead?

**Comment by shlomizadok** [comment]
So that's the issue... we demo how the right url should look like (on tokens), fog breaks it on tenants...

**Comment by dLobatog** [comment]
https://github.com/theforeman/foreman/pull/2529 <- this should make it work, explanation in the description of that pull request.

**Comment by shlomizadok** [comment]
Closing in favor of #2529

**Pull request closed without merging**
