### PR TITLE
Fixes #17561 - Allow Dynamic keyword in autoyast files

### PR DESCRIPTION
**Pull request by Klaas-**

### CODE REVIEW

**Comment by timogoebel** [comment]
@theforeman-bot ok to test

**Comment by timogoebel** [comment]
[test foreman] - tests result look unrelated, let's retry :-)

**Comment by dLobatog** [comment]
Thanks @Klaas- @timogoebel !

**Comment by Klaas-** [comment]
thanks @dLobatog for the quick reaction

**Pull request merged**
