### PR TITLE
Fixes #23479 - Enhance OpenStack VM Creation

### PR DESCRIPTION
**Pull request by plessbd**
Adds the selection of multiple security groups and default if only one available security zone

thanks for help from @minnus

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by plessbd** [comment]
If someone can help me figure these out I would be happy to fix the tests / failures.  However I am not even sure what I am looking at.

I know this works cause I have applied these patches to my local instance.

**Comment by plessbd** [comment]
I updated this and added a safeguard (tests failed at first) seems the tests passed afterwards but for some reason the bot added needs testing

**Review by mmoll — APPROVED** [review]
This is looking OK visually, but I have no idea of OpenStack...

**Comment by tbrisker** [comment]
@dLobatog can you take a look please?

**Review by dLobatog — APPROVED** [review]
Thanks, this is a great improvement for Security Groups, @tbrisker @xprazak2 do you think this could go in 1.18?

**Comment by ares** [comment]
@dLobatog mind to demo this? I guess you have the configuration ready since you did the review. Btw opened 1.18 CP PR at https://github.com/theforeman/foreman/pull/5819

**Pull request merged**
