### PR TITLE
Fixes #22817 - update scoped search to 4.1.3

### PR DESCRIPTION
**Pull request by tstrachota**
Scoped search 4.1.3 contains important fix that is required for correct filtering repositories in Katello:
https://github.com/wvanbergen/scoped_search/commit/6a3b759b0826239f3f82b3b6c17f28bcdce55299

Packaging is ready:
https://github.com/theforeman/foreman-packaging/pull/2261

### CODE REVIEW

**Comment by ares** [comment]
:+1: once https://github.com/theforeman/foreman-packaging/pull/2261 gets in

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
@ares the packaging PR has been meerged

**Comment by ares** [comment]
[test foreman] [test katello] - failing with `Could not load database configuration. No such file - ["config/database.yml"]`

**Comment by tstrachota** [comment]
[test foreman]

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
test failure unrelated (would have needed a rebase to succeed)

**Comment by mmoll** [comment]
merged, díky @tstrachota!

**Pull request merged**
