### PR TITLE
Fixes #37244: Add new virtual hw versions for VSphere 8.0 and 8.0U2

### PR DESCRIPTION
**Pull request by Areyus**
See https://kb.vmware.com/s/article/1003746 for reference

### CODE REVIEW

**Comment by Areyus** [comment]
Disclaimer: I do not currently have a VSphere 8 instance around to test this myself, so I ask ksiminski, who originally reported this, for tests: https://community.theforeman.org/t/update-for-vmware-hardware-version/37242

**Comment by Odilhao** [comment]
ok to test

**Comment by Areyus** [comment]
Rebased on top of current develop to fix unrelated test failures

**Review by Gauravtalreja1 — APPROVED** [review]
ACK, Thanks @Areyus , I've tested this on VCenter 8, and we now see virtual H/W versions 21 (ESXi 8.0 U2) and 20 (ESXi 8.0)
I also tested the provisioning with these virtual hardware versions and it worked.

Screenshot 2024-03-13 at 5 38 32 PM

**Review by stejskalleos — APPROVED** [review]

**Comment by stejskalleos** [comment]
Thanks @Areyus @Gauravtalreja1

**Pull request merged**
