### PR TITLE
Fixes #25538 - Do not singularize hostgroups in menu

### PR DESCRIPTION
**Pull request by xprazak2**
Caused by a bad translation. It seem like it is already fixed in [transifex](https://www.transifex.com/foreman/foreman/viewstrings/#en/foreman/29279030?q=text%3A'Host+Groups')

cc @lhellebr

### CODE REVIEW

**Comment by tbrisker** [comment]
If it's fixed in transifex, wouldn't the updated translation be pulled anyways prior to the next release?

**Comment by xprazak2** [comment]
There is a BZ, so main reason I opened this was to address the downstream issue. Feel free to either merge or close.

**Comment by tbrisker** [comment]
Looks like the real issue here is that for some reason English translations use fuzzy matching, which should be disabled. I'm investigating, closing this in favor of fixing the root cause.

**Comment by tbrisker** [comment]
Opened GH-6375 instead

**Pull request closed without merging**
