### PR TITLE
Fixes #3540 - pluck('table.column') replaced with pluck(:column)

### PR DESCRIPTION
**Pull request by xprazak2**
Hopefully I got them all.

### CODE REVIEW

**Comment by domcleal** [comment]
As per the ticket description, this change is only to be made with Rails 4.  It's required for our 3.2 compatibility.

**Comment by xprazak2** [comment]
@domcleal: I noticed, is there anything I should do that I am missing?

**Comment by domcleal** [comment]
Wait until Foreman uses Rails 4?  I'm not sure what you mean, we can't take this today.

**Comment by xprazak2** [comment]
@domcleal: I know we can't, I got confused by the tracker where there are other PRs related to Rails 4.0 upgrade marked as 'Ready for testing', so I assumed we wait until all are finished. I've looked at the details just now to see they are all closed. I apologize for the mistake and confusion. I will delete the branch to close this.

**Pull request closed without merging**
