### PR TITLE
fixes #2166 - error when clearing location

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@isratrade, this looks like the wrong path imho, as that code should be skipped (via skip_before_filter)

**Comment by isratrade** [comment]
@ohadlevy The failing code is called within def find_taxonomy which cannot be skipped since def select uses it.
I think find_by_id is the way to go imho

**Comment by ohadlevy** [comment]
@isratrade why do we need to find taxonomy when we clear it? maybe i'm missing something?

**Comment by isratrade** [comment]
@ohadlevy, in routes  get 'clear', :action => 'select'

We use :select as the method for **both** /clear and /:id/select.  

If I did this below and skipped :find_taxonomy for /clear, then I'm also skipping it to :id/select

```
skip_before_filter :authorize, :set_taxonomy, :find_taxonomy, :only => %w{select}
```

The other option to have a def clear in the controller and make edit the route so it goes to clear and not select.

Other way is fine with me.

**Comment by isratrade** [comment]
@ohadlevy I committed with the new method clear.  I think it makes more sense that def clear sets taxonomy_class.current = nil, than than def select not finding and :id and thus setting it to nil.

**Comment by ohadlevy** [comment]
@isratrade, this looks much better, can you please add tests?

**Comment by isratrade** [comment]
@ohadlevy: added test on organizations_controller_test and locations_controller_test

**Comment by ohadlevy** [comment]
this was merged already - closed

**Pull request closed without merging**
