### PR TITLE
fixes #4670: switch search string on OS page

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by isratrade** [comment]
@mmoll, good catch. The method `find_by_to_label` was recently merged.  I suggest to use scoped search's `:ext_method` to search by a custom method.  If we just search by `description`, it's not enough, because the OS may not have a description which in this case, we search for `fullname` "#{name} #{release}"

**Comment by mmoll** [comment]
implemented search_by_label()

**Comment by abenari** [comment]
This implementation has a few drawbacks.
It produce options that doesn't make sense os_lable > "CentOS 6.3" will get all the os with larger ids. 
It doesn't support '~' like operator for writing os_label~"centos 6.*"
It doesn't support value autocompletion.

My suggestion is to add label to os table with db migration, and having a regular search.
A little more work but much better results.

**Comment by mmoll** [comment]
Searching for label has it's downsides and my approach to require description to be set in the database opened up a huge can of worms, so I'm now going a simple, unelegant way.

**Comment by domcleal** [comment]
:+1:

**Comment by isratrade** [comment]
@mmoll, this looks good if the purpose is only the hosts.count link on operatingsystems#index. I think a new version of `scoped_search` gem has a feature to hide `os_id` in the dropdown complete_for options, but it's no big deal.  We don't have a Gemfile.lock so we can't guarantee which gem version.  I was going to suggest to rename to use os.id but I see that the hyphen was used for others (os_description, os_major, os_minor) so os_id seems good. Good job. +1 from me.

**Comment by domcleal** [comment]
scoped_search just takes a hash, so specifying an option that's not available in our minimum version (2.6.2 right now) is usually fine.  Package installs will probably get 2.7+.

**Comment by mmoll** [comment]
complete_enabled => false added.

**Comment by isratrade** [comment]
Merged as b597e59ef48e2f1d2bcc89ea20852ffffad13850, thanks @mmoll !!

**Pull request closed without merging**
