### PR TITLE
Bug #3869 API error messages poorly formatted

### PR DESCRIPTION
**Pull request by dLobatog**
This fix wraps all API errors with the key "error", and fixes the problem with erroneous metadata being showed on errors. I have also dropped `route_error` as the catch-all route was removed recently to allow plugins define their own routes.

``` json
{
  "error": {"message":"Unable to authenticate user asdasd"}
}
```

http://projects.theforeman.org/issues/3869

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
[test]

**Comment by domcleal** [comment]
:+1: 

@mbacovsky or @tstrachota - is this OK with you?

**Comment by tstrachota** [comment]
I like that. Does it also change the format of 404 responses? AFAIR it wasn't nested here #1098 
Don't get me wrong, I prefer this format but we should be consistent.

**Comment by domcleal** [comment]
Yeah, it does change the 404 response to this format too.

**Comment by domcleal** [comment]
Thanks @eLobato, merged as 0f7d219a4 for Foreman 1.4.0.

**Pull request closed without merging**
