### PR TITLE
Fixes #16030 - Add foreman_cache_data to foreman-debug

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by dLobatog** [comment]
@chris1984 Thanks! This won't work with Puppet AIO though (it's , can you retrieve the lib directory via `puppet config print libdir`, or detect whether we have AIO vs regular puppet?

**Comment by domcleal** [comment]
This directory will likely contain passwords and tokens which foreman-debug deliberately attempts _not_ to collect. The list of files should probably be filtered to exclude all credentials in this directory.

**Comment by domcleal** [comment]
Did you mean to close this?

**Comment by chris1984** [comment]
@domcleal sorry closed the wrong one

**Comment by chris1984** [comment]
@domcleal This should filter out any passwords etc
https://github.com/theforeman/foreman/blob/develop/script/foreman-debug#L42-L55

**Comment by domcleal** [comment]
> This should filter out any passwords etc
> https://github.com/theforeman/foreman/blob/develop/script/foreman-debug#L42-L55

The contents of the files are YAML strings without any of those keywords - the filter matches key/value type structures, filtering out any keys that match the known words.  Almost all files in this directory are likely to be sensitive, are they not?

**Comment by chris1984** [comment]
Closing this out since its not needed

**Pull request closed without merging**
