### PR TITLE
Fixes #10442 - dry up host managed logic

### PR DESCRIPTION
**Pull request by ares**
I'll rebase the PR when https://github.com/theforeman/foreman/pull/2359 gets merged.

### CODE REVIEW

**Comment by domcleal** [comment]
@ares could you rebase this please?

**Comment by ares** [comment]
rebased

**Comment by domcleal** [comment]
Sorry, and again please!

**Comment by ares** [comment]
rerebased :-)

**Comment by domcleal** [comment]
Merged as ba64f02, thanks @ares.

**Pull request closed without merging**
