### PR TITLE
Fixes #29043 - Add name to 'generate_at' field

### PR DESCRIPTION
**Pull request by xprazak2**
The field value is now correctly submitted. Even though I see the jobs in dynflow console, they seem to be 'scheduled pending' forever. I am not sure if there is something wrong in my setup or if it is actually another bug. It would be nice if someone dynflow savvy could test.

### CODE REVIEW

**Review by tbrisker — COMMENTED** [review]
Can you please add a test to make sure the form does submit what it should (or add the check to an existing test)? I'm assuming this also needs to be cherry-picked to all stable versions? 
@adamruzicka can you please check regarding the question about dynflow if it is related or not?

**Comment by ares** [comment]
Adding WoC based on @tbrisker comment, needs test. Otherwise looks reasonable to me.

**Comment by adamruzicka** [comment]
Works on my machine, I'll take a look at it with @xprazak2

**Review by ezr-ondrej — APPROVED** [review]
Code looks good, works like a charm! Thanks @xprazak2 ! :+1:

**Pull request merged**
