### PR TITLE
Fixes #30107 - graphql powerStatus field

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Add graphql field `powerStatus` to host

### CODE REVIEW

**Comment by xprazak2** [comment]
Works nicely, could you add a test for the new resolver please?

**Comment by ezr-ondrej** [comment]
> Works nicely, could you add a test for the new resolver please?

I can definitely try :)

**Comment by ezr-ondrej** [comment]
I've added a simple test on basic response, do we want more tests for failures? :thinking:

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
