### PR TITLE
Fixes #33389 - Make the registration form more compact

### PR DESCRIPTION
**Pull request by stejskalleos**
Before:
from_before

Now:
form_now

### CODE REVIEW

**Comment by ares** [comment]
Better but please at least one or two more steps narrower. The longest OS name I have can still fit in the fields twice.

**Comment by stejskalleos** [comment]
> Better but please at least one or two more steps narrower. The longest OS name I have can still fit in the fields twice.

That would make some fields cropped, for example setup rex & insights:
narrow

**Review by ares — APPROVED** [review]
Perfect, thanks @stejskalleos, merging!

**Comment by ezr-ondrej** [comment]
CP 3.0: #8770

**Pull request merged**
