### PR TITLE
Fixes #20610 - Prevent chrome password autofill

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]
@tbrisker: This is lovely and works great.

I do see this JS error, but I have a feeling this is unrelated:
image

**Comment by ohadlevy** [comment]
@timogoebel this seems to be a bug somewhere with yarn, using npm instead (remove your node_modules dir first) works correctly.

from some reason yarn pulls the wrong version of datatables.net regardless and npm doesn't.

**Comment by timogoebel** [comment]
@ohadlevy: Thanks. `npm` doesn't work with our corporate proxy. I guess, it's time to call it a day.

**Comment by ohadlevy** [comment]
thanks @timogoebel added https://github.com/yarnpkg/yarn/issues/4176

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Merged, thanks @tbrisker. Long overdue, this patch. :-)

**Comment by tbrisker** [comment]
@timogoebel Indeed, last time I tried chrome was still trying to be smarter then me. Turns out in Chrome 44 they finally realized there may be cases that don't need to be auto-filled.

**Pull request merged**
