### PR TITLE
fixes #4652 error when running test from ide

### PR DESCRIPTION
**Pull request by abenari**

### CODE REVIEW

**Comment by domcleal** [comment]
@ares one for you

**Comment by dLobatog** [comment]
I don't see the `.value` error no more with this patch, however I'm not entirely sure what triggers it.

**Comment by ares** [comment]
I encountered this today. @abenari could you rather put the `if File.basename...` block into first if. I'd prefer either this or renaming the flag to something else since it's not flag anymore.

**Comment by abenari** [comment]
@ares changed the code to if in if as suggested.

**Comment by ares** [comment]
I'm sorry to be that pedant, but could you please also move `.value` back into second condition? I find it more readable.

**Comment by abenari** [comment]
@ares done!

**Comment by ares** [comment]
merged as 8592cd2775499d229a9ff0ca9bf8e042d1b403f3, thanks @abenari!

**Pull request closed without merging**
