### PR TITLE
fixes #7613 - make search bar route lookup usable from isolated engine

### PR DESCRIPTION
**Pull request by dkliban**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by orrabin** [comment]
gemset error that has nothing to do with you, re[test]

**Comment by dLobatog** [comment]
Thanks @dkliban for the patch! We do this in a few places to give engines access to the route helpers. I'll merge it, however on update to Rails 4 we should get rid of all main_app references and tell plugins to use `EngineController.send(:include, Rails.application.routes.url_helpers)`.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/6cf71d7961353e3b79d1afed56c18a60aa057725 , thanks again @dkliban , hope to see you here again!

**Pull request closed without merging**
