### PR TITLE
Fixes #19789 - fix Layout/SpaceAroundOperators cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Some overly long lines in `test/models/compute_resources/vmware_test.rb` got reformatted.

**Comment by mmoll** [comment]
Do you want this PR get merged and thus this cop enabled? React :+1:
Do you want this cop to be disabled? React :-1:

**Comment by tbrisker** [comment]
@mmoll this needs a rebase now :)

**Comment by mmoll** [comment]
@tbrisker rebased :)

**Review by tbrisker — APPROVED** [review]
+5, -0 = consensus :)

**Pull request merged**
