### PR TITLE
Fixes #10228 - adding index to source_id in logs table

### PR DESCRIPTION
**Pull request by xprazak2**
Migration that adds index to source_id in logs table

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by xprazak2** [comment]
[test]

**Comment by domcleal** [comment]
Merged as bd3a90f, thanks @xprazak2!

**Pull request closed without merging**
