### PR TITLE
fixes #5566 - Fact Values Query Produces Error

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@abenari, please check. I added `:only_explicit => true` to two problematic search definitions when entering free text.
The `:in_key=> :fact_name, :on_key=> :name` caused the table name on the join to be renamed to such as

```
INNER JOIN "fact_names" fact_names_77948 ON (fact_names_77948.id = fact_values.fact_name_id)
```

`ext_method => :search_by_host` was also problematic as the method to returned `nil` so the SQL statement had `OR OR` in it which caused an error.

**Comment by isratrade** [comment]
re [test]

**Comment by isratrade** [comment]
@domcleal, any reason why it fails on 1.8.7 / mysql with "no failures"?

**Comment by domcleal** [comment]
@isratrade no idea now, as the test was overwritten, sorry

**Comment by isratrade** [comment]
@domcleal, ok, at least it all passes now :-)

**Comment by domcleal** [comment]
Merged as b7ae683 for Foreman 1.5.2, thanks @isratrade.

**Pull request closed without merging**
