### PR TITLE
#32795 - Update confirm modal in editor options

### PR DESCRIPTION
**Pull request by kmalyjur**
Update window.confirm dialog in editor options to PF4 confirmation modal.

### CODE REVIEW

**Comment by adamruzicka** [comment]
The commit will eventually need to be shaped as 'Fixes #32795 - some description'.

Could you lay out a plan what needs to be done here before it can be undrafted?

**Comment by kmalyjur** [comment]
> The commit will eventually need to be shaped as 'Fixes #32795 - some description'.
> 
> Could you lay out a plan what needs to be done here before it can be undrafted?

Sure, thanks for noticing.
I need to update it with the test before it can be undrafted.

**Comment by kmalyjur** [comment]
Waiting for the [9652](https://github.com/theforeman/foreman/pull/9652) that includes changing the class component to the arrow one before continuing

**Comment by kmalyjur** [comment]
This PR is not a priority right now, so I'm getting back to it until further due.

**Pull request closed without merging**
