### PR TITLE
Smart proxy api v1

### PR DESCRIPTION
**Pull request by tstrachota**
- new api controller for smart proxies
- modification in subnet controller docs
- new method show in subnet api controller

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tstrachota I think this might conflict with existing work from @isratrade at #239 ? 

I'll have a closer look after I'll merge 239 (hopefully today)

**Comment by tstrachota** [comment]
Yeah, there will be conflicts. Thanks for looking at this. I'd like to get those two controllers into develop soon. We need to build new version of the foreman_api gem.

**Comment by ohadlevy** [comment]
@tstrachota thanks, the #239 work should include all proxies and a major overall to the api docs and all remaining controllers.

**Comment by ohadlevy** [comment]
@tstrachota can we close this PR ?

**Pull request closed without merging**
