### PR TITLE
fixes #2808 - pin nokogiri to 1.5.x for Ruby 1.8

### PR DESCRIPTION
**Pull request by domcleal**
PR tests are down at the moment as test_develop is broken, they won't run this.

### CODE REVIEW

**Comment by skottler** [comment]
Merged as 0b547e84f7342cbb. Thanks!

**Comment by ohadlevy** [comment]
Hmm.. I know this is closed, but:

any reason not to restrict fog version instead? I'm guessing other 1.7 breaking changes would happen eventually....

I would simply put fog in a block based on the ruby version.

additionally, another thing that worries me here, is that we FORCE to install nokogiri now..... this is really not required for smaller deployments.

**Comment by domcleal** [comment]
I understand your concerns, but:

a) we need newer fog versions to fix bugs (e.g. [#2694](http://projects.theforeman.org/issues/2694)) or very likely in the near future, to add new functionality to Foreman, so I didn't want to pin fog.
b) nokogiri is used by at least three gems in separate groups (fog, capybara, rbovirt), so it would have meant duplicating this in three files.  Adding it just to 1.8 installs seemed safer to me, in case this changed and broke again later, and to be more DRY.

**Comment by ohadlevy** [comment]
and what about the next non friendly 1.87 change that we'll see in fog?

**Comment by domcleal** [comment]
Let's cross that bridge when we know what the change is, since Fog is still supporting 1.8 for the time being.  This was a documented change.

Whether we should continue to support it is a separate matter I think for the -dev list, but I've no desire to continue supporting it personally.

**Comment by skottler** [comment]
I agree that we should really consider whether we'll continue supporting 1.8.x for the time being. The sole platform that's holding us back right now from dropping support for it is Debian squeeze. We may be able to use omnibus packaging to get ruby 1.9 running smoothly there. I'll start the conversation on the dev list.

**Pull request closed without merging**
