### PR TITLE
Add Catalan Language

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks for the PR @rbuj.  Is this the same content as you've uploaded into Transifex?  (It's just we don't normally ask translators to do this step.)

**Comment by rbuj** [comment]
Yes, I'm translating it in Transifex. I'll try to translate a bit more in the next days.

I'm also reviewing the translations by using "make -C locale tx-update (http://projects.theforeman.org/projects/foreman/wiki/Translating) and "rails server (http://theforeman.org/contribute.html).

You can close & remove this PR, and upload the Catalan translation, without any problem.

**Comment by domcleal** [comment]
Perfect, thanks!  I'll run tests now: [test] and merge it in to get the language added.

On most releases I update the files from Transifex, so any further translations will get pulled in automatically, usually to the current stable branch rather than develop (synced periodically when we re-branch to stable).

**Comment by domcleal** [comment]
Merged as dead2a6, thanks @rbuj!

**Pull request closed without merging**
