### PR TITLE
Fix #2839 - Authentication issues with cloud-init

### PR DESCRIPTION
**Pull request by imordey**
Fixes authentication issue with openstack cloud-init. Foreman attempts to ssh before the user is created and causes a rollback.

### CODE REVIEW

**Comment by domcleal** [comment]
@GregSutcliffe?

**Comment by GregSutcliffe** [comment]
Looks sane to me. [test]

**Comment by lzap** [comment]
Generic comment - are we trying here in an endless loop?

**Comment by domcleal** [comment]
@lzap yes, but within the confine of a 360 second timeout

**Comment by imordey** [comment]
Does this not timeout the connection after 360 seconds?

def initiate_connection!
    Timeout::timeout(360) do
      begin
        Timeout::timeout(8) do
          ssh.run('pwd')
        end

**Comment by skottler** [comment]
That will properly timeout, yes.

[test]

**Comment by domcleal** [comment]
Thanks for the patch @imordey, merged as f9d5655 for Foreman 1.3.

**Pull request closed without merging**
