### PR TITLE
Refs #26781 - css independent on the placement

### PR DESCRIPTION
**Pull request by ezr-ondrej**
I have forgotten to check the css in #6750 and it gives different UI in other than top placement.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
This is the issue:

Top:
placement_css_top
Bottom:
placement_css_bottom

**Review by ares — APPROVED** [review]
Tested, fixes the problem. Will merge when I see jenkins green, unless someone beats me to it.

**Review by sharvit — APPROVED** [review]
Thanks @ezr-ondrej

**Comment by ezr-ondrej** [comment]
@ares I believe we won't get any greener :( but katello fails are not related.

**Comment by ares** [comment]
> Pull requests that have a failing status can’t be merged on a phone.

So it will have to wait till tomorrow :-)

**Comment by ezr-ondrej** [comment]
No worries :+1:

**Comment by ares** [comment]
Thanks @ezr-ondrej, merging!

**Pull request merged**
