### PR TITLE
Fixes #16293 - Move vendored diff.js to webpack

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
@tbrisker Can you rebase? I'll be happy to merge after that. I'll take a look if you submit a PR to packaging too.

I've tested it by looking at a few diffs and I didn't see any difference on how they were presented, so I guess it works.

**Comment by tbrisker** [comment]
@dLobatog rebased, i'll create a PR to packaging in a bit.

**Comment by tbrisker** [comment]
@dLobatog https://github.com/theforeman/foreman-packaging/pull/1318 opened

**Comment by dLobatog** [comment]
Thanks @tbrisker!

**Pull request merged**
