### PR TITLE
Fixes #30517 - Targeting hosts table should not be re-loaded every second

### PR DESCRIPTION
**Pull request by stejskalleos**
Cherry-picked from https://github.com/theforeman/foreman/commit/26d08e6ab1f1a634e9560132118da8686f9f17e9

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]
Works nicely.

Katello tests are red, but that is expected since katello tests are running katello develop, which is not compatible with 2.1

**Comment by adamruzicka** [comment]
@tbrisker are you ok with pulling this one into 2.1?

**Comment by tbrisker** [comment]
Please cherry-pick the original commit to the stable branch using `git cherry-pick -x`, if redmine issue #30517 is actually a duplicate of #29990 it should be closed as such.

**Review by tbrisker — APPROVED** [review]
Thanks @stejskalleos and @adamruzicka !

**Comment by Ron-Lavi** [comment]
Thanks @stejskalleos @adamruzicka @tbrisker !

**Pull request merged**
