### PR TITLE
fixes #24571 - vsphere nic selection works with fog-vsphere updates

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by chris1984** [comment]
Currently working on testing this

**Review by chris1984 — APPROVED** [review]
ACK, Thanks @timogoebel Results of my testing:
~~~
PXE:

Normal VM creation with single HDD on Local Datastore - Passed
Normal VM creation with added HDD on Local Datastore - Passed 
Normal VM creation with single HDD on Storage Pod - Passed
Normal VM creation with added HDD on Storage Pod - Passed

Bootdisk:

Normal VM creation with single HDD on Local Datastore - Passed
Normal VM creation with added HDD on Local Datastore - Passed
Normal VM creation with single HDD on Storage Pod - Passed
Normal VM creation with added HDD on Storage Pod - Passed

Image:

Normal VM creation with single HDD on Local Datastore - Passed
Normal VM creation with added HDD on Local Datastore - Passed
Normal VM creation with single HDD on Storage Pod - Passed
Normal VM creation with added HDD on Storage Pod -  Failed ( Has not worked since 6.2 or upstream so not regression)

Network:

Normal VM creation with NIC in portgroup on Standard Switch - Passed
Normal VM creation with NIC in portgroup on Distributed Switch - Passed - Didn't work before.
Normal VM creation with NIC in portgroup on Distributed Switch with VLAN - Passed - Didn't work before.
~~~

**Comment by ekohl** [comment]
[test katello]

**Review by ekohl — APPROVED** [review]
Finally the tests have completed

**Pull request merged**
