### PR TITLE
Fixes #11029 - Host name in title on facts index page

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by dLobatog** [comment]
Merged as ee43a2c33a28ce99cf6ae353cd6d7f5ccf2f03f0, thanks @xprazak2!

**Comment by shlomizadok** [comment]
So, we'll have `fact values |` if no params[:host_id] ?

**Comment by ohadlevy** [comment]
Should we revert this patch?

**Comment by shlomizadok** [comment]
No. https://github.com/theforeman/foreman/pull/3233 is fixing it.

**Pull request closed without merging**
