### PR TITLE
Fixes #25542 - Storybook style fixes

### PR DESCRIPTION
**Pull request by tstrachota**
- adds a wrapper component `Story` that ensures all stories have consistent spacing
- replaces dependecies loaded from cloudflare with correct configuration for webpack loaders
- moves components that are not intended for reuse into a section "Page chunks"

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tstrachota can you please deploy it?
 lgtm.. @theforeman/ui-ux  ?

**Comment by sharvit** [comment]
@tstrachota I like the `Story` component, couldn't you use it as a `decorator` so it will wrap our stories automatically?

**Comment by tstrachota** [comment]
@sharvit I could but I didn't want to. I'd like to give people options to use various styles like narrow width. I expect that some more presets like this will arrive in future. I find it easier to read when it's in one component.

**Comment by ohadlevy** [comment]
@tstrachota why close?

**Comment by tstrachota** [comment]
@ohadlevy it got automatically closed after I deployed the storybook with `storybook-deploy` I'm trying to find you why and I'm going to re-open.

**Comment by tstrachota** [comment]
Re-opened as https://github.com/theforeman/foreman/pull/6280 Sorry for troubles.

**Pull request closed without merging**
