### PR TITLE
Fixes #22294 - Run dynflowd from rails root location

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Related packaging change -- https://github.com/theforeman/foreman-packaging/pull/2107

**Review by iNecas — APPROVED** [review]

**Comment by iNecas** [comment]
Thanks @ehelms , I guess this needs to go to 1.17 release as well

**Comment by ares** [comment]
@iNecas if that's the case, also please set a milestone here and cp to 1.17-stable (or at least that's how we did it in 1.16, we cherry-pick stuff right after it's merged to develop to avoid surprises later)

**Comment by ares** [comment]
cc @xprazak2 for visibility

**Comment by iNecas** [comment]
Cherry-picked to 1.17-stable

**Pull request merged**
