### PR TITLE
fixes #13144 - enable missing precompiled asset errors in test env

### PR DESCRIPTION
**Pull request by domcleal**
Remove extraneous ace/ace JS, which is included through vendor.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by domcleal** [comment]
Filed the test failure as http://projects.theforeman.org/issues/13214.

**Comment by dLobatog** [comment]
Merged as 62a6652d2a5422734a60396d838a8154182fa800, thanks @domcleal!

**Comment by ehelms** [comment]
Twice in a week PRs have been merged that then break Katello tests and block PRs and developers. Is this intentional?

**Pull request closed without merging**
