### PR TITLE
fixes #2491, fixes #2487 - i18n issues

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Untested but looks good. We could probably drop the translator notes as I feel those strings are self-documenting now, but since they're there and not causing any harm... ;)

**Comment by domcleal** [comment]
I thought it better to leave them, in case the meaning of the single letter wasn't clear.

**Comment by GregSutcliffe** [comment]
Good point. As I say, now they're written it's not worth the keystrokes to remove them :)

**Comment by lzap** [comment]
All three fixes look sane! +1

**Comment by ohadlevy** [comment]
merged as 0ee000e thanks!

**Pull request closed without merging**
