### PR TITLE
Fixes #35569 - set correct icons

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Review by Ron-Lavi — DISMISSED** [review]
Thanks @sbernhard

**Comment by Ron-Lavi** [comment]
[test unit]

**Comment by Ron-Lavi** [comment]
[test katello]

**Comment by sbernhard** [comment]
Ready to be merged @Ron-Lavi

**Review by Ron-Lavi — APPROVED** [review]
Looks good, thanks @sbernhard !

**Pull request merged**
