### PR TITLE
Fixes #28561 - Configure and fix Layout/AlignArguments cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by tbrisker — COMMENTED** [review]
Looking at the changes, it looks like the common style is `with_fixed_indentation` of width 2, but i may be wrong and that would cause even more changes? if it's smaller i would prefer maintaining the most common style used currently

**Comment by mmoll** [comment]
Changed it. This Changeset is a bit smaller. :+1:

**Comment by mmoll** [comment]
[test upgrade]

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
[test foreman]

**Comment by lzap** [comment]
I like this one. Thanks!

**Comment by ezr-ondrej** [comment]
I like it! Thanks @mmoll

**Review by tbrisker — APPROVED** [review]
Looks like enough consensus and no objections. thanks @mmoll !

**Pull request merged**
