### PR TITLE
Refs #28384 - Use correct Foreman version in error log task

### PR DESCRIPTION
**Pull request by tbrisker**
Looks like this was missed when updating the original PR for comments.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Looks like it was introduced in a7874f5722625e3a64c557a4d2d445c8b67d1548, so it's only in 2.2.

**Comment by ares** [comment]
APJ, feel free to merge yourself once it turns green :-)

**Comment by tbrisker** [comment]
Merging right away, we don't have tests for rake tasks so no point in wasting CI resources on this.

**Comment by tbrisker** [comment]
2.2 - d26200de2

**Pull request merged**
