### PR TITLE
Fixes #11625:  refactor the ace editor to make it reusable.

### PR DESCRIPTION
**Pull request by waldenraines**
Make the ace editor reusable and include it on the global parameters
page.

http://projects.theforeman.org/issues/11625

### CODE REVIEW

**Comment by dLobatog** [comment]
@waldenraines The refactor is :fire: , thanks! I love the syntax coloring. It seems like this needs a rebase, and the box on provisioning templates/partition tables became a lot smaller all of a sudden.

screenshot from 2015-09-03 09-23-55
screenshot from 2015-09-03 09-24-06

Can you rebase and fix that? I'm a bit confused as to why do we want such a full-fledged editor for params (in my experience parameters usually are simple, and no more than one line), any background on that?

Thanks again @waldenraines !

**Comment by waldenraines** [comment]
> I'm a bit confused as to why do we want such a full-fledged editor for params (in my experience parameters usually are simple, and no more than one line), any background on that?

@orrabin can you provide any more information on this?

**Comment by waldenraines** [comment]
@eLobato updated.

**Comment by dLobatog** [comment]
Merged as a4ed89d9f5407366a838087e30621d08429f0406, thanks @waldenraines!

**Comment by orrabin** [comment]
> I'm a bit confused as to why do we want such a full-fledged editor for params (in my experience parameters usually are simple, and no more than one line), any background on that?

@eLobato when the type or a parameter is yaml or json we wanted the full screen editor to be formatted correctly to make editing them easier.

**Pull request closed without merging**
