### PR TITLE
fixes #20334 - ensure api promise is called correctly.

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Comment by boaz0** [comment]
It appears that unit-tests fail:
```
TypeError: request.done is not a function
```

Does using `success` instead of `done` fix it?

**Comment by ohadlevy** [comment]
@ripcurld0 thanks for the review, changing to success doesn't make any difference.

@tbrisker do you happen to have an idea?

**Comment by tbrisker** [comment]
Looks like the issue is in the mock implementation of the `$.getJSON` function, e.g. [here](https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/components/notifications/notifications.test.js#L31) which only has a `.then` method.

**Comment by boaz0** [comment]
Nice, I didn't know we are using jest! Awesome testing framework.

**Comment by ohadlevy** [comment]
any idea on how to test the multiple callbacks? if i use the current approach i can't chain the calls.

**Comment by tbrisker** [comment]
You could try creating a mock `jqXHR` object that responds to all these calls and returns itself after calling the callback that was passed to each method.

**Comment by ohadlevy** [comment]
@tbrisker if you have time to mock it properly I'll appreciate it, i didn't have luck :)

**Comment by tbrisker** [comment]
@ohadlevy i'll try to look into it tomorrow if i have the time.

**Comment by tbrisker** [comment]
@ohadlevy I think I figured it out, check out https://github.com/ohadlevy/foreman/pull/9 and feel free to squash.

**Comment by ohadlevy** [comment]
@tbrisker pr updated :-)

**Comment by tbrisker** [comment]
@ohadlevy can you squash please?

**Comment by ohadlevy** [comment]
@tbrisker rebased and squashed.

**Comment by ohadlevy** [comment]
@tbrisker tests are green :)

**Comment by tbrisker** [comment]
Thanks @ohadlevy !

**Pull request merged**
