### PR TITLE
Fixes #7588 - 'Displaying x entries' button doesn't seem to do anything

### PR DESCRIPTION
**Pull request by boaz0**

### CODE REVIEW

**Comment by boaz0** [comment]
This is how it looks like:
http://imgur.com/CfhLMCi
Note: the upper one is _on-mouse-over_.

**Comment by lzap** [comment]
Before:



After:



To me it still looks like a button...

I am all for selecting something that is really just a label, preferably something grey which does not take first attention. This is complementary kind of information. http://getbootstrap.com/components/

Also both Displaying label and Pager are not aligned with tables which is a bit confusing and looks ugly. Let's align them? @ohadlevy ?

**Comment by boaz0** [comment]
@lzap, your review, please. :smile:

**Comment by ohadlevy** [comment]
[test]

**Comment by lzap** [comment]
Sorry github does not notify me when you rebase. This looks much better to me:



On the other hand this does not correspond with pagers.



But I am fine with this. Is it possible to aligh the pagers as well? I assume they both live in the same divider/span.

**Comment by lzap** [comment]
@ohadlevy what you think of this style? Would you prefer the same font/size as the pagers?

**Comment by boaz0** [comment]
@lzap yes, I am sure I can align the pager. 
Regarding the font, I will try to see what I can do.

**Comment by boaz0** [comment]
@lzap http://imgur.com/Gw2wZA2 -- how does it look now?

**Comment by lzap** [comment]
Looks good, please push so I can test this.

**Comment by lzap** [comment]
Ok it looks like we need more refactoring to have the pager properly aligned, raising new PR.

**Comment by dLobatog** [comment]
@ripcurld00d Thanks for your patch. Could you use an easier to read color scheme? https://github.com/theforeman/foreman/pull/1816#issuecomment-57604921 links to a page with examples.

**Comment by lzap** [comment]
I can carry on from that. Thanks for your contribution!

**Comment by dLobatog** [comment]
@ripcurld00d , your patch (authored) is still in https://github.com/theforeman/foreman/issues/1816 , it will probably be merged after Jenkins comes back.

**Pull request closed without merging**
