### PR TITLE
Fixes #22698 - clear the search filter

### PR DESCRIPTION
**Pull request by tbrisker**
clearing the search filter does not take place when submitting

Signed-off-by: Boaz Shuster <boaz.shuster.github@gmail.com>
(cherry picked from commit 2ce888d2b98697dbfec964ea9ff03905607aa237)

cc @xprazak2 - this is a CP of GH-5434 to 1.18 stable

### CODE REVIEW

**Comment by xprazak2** [comment]
There are more commits here than we need, could you remove the other ones? They are already in 1.18-stable...

**Review by dLobatog — CHANGES_REQUESTED** [review]
@tbrisker I see this bug mentioned on https://community.theforeman.org/t/1-17-1-bug-lineup/8886 - since it missed 1.17.1, do you think it's worth cp-ing to 1.17.2?

**Comment by tbrisker** [comment]
@xprazak2 oops, bad rebase on my side, fixed now.
@dLobatog It's a minor annoyance but not critical, so i guess it's up to @xprazak2 to decide if we want to cp it there as well.

**Comment by xprazak2** [comment]
Test failures seem unrelated, some builds were [aborted](http://ci.theforeman.org/job/test_develop_pr_core/17673/database=postgresql,ruby=2.4,slave=fast/console) due to timeout and and there was one Jenkins [error](http://ci.theforeman.org/job/test_develop_pr_core/17673/database=mysql,ruby=2.4,slave=fast/console). Js tests on Travis all passed.

I do not mind doing cp into 1.17.2, seems like a small change.

@dLobatog, any additional comments?

**Comment by mmoll** [comment]
[test foreman]

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
if anybody wants this in 1.17, just open a respective PR :)

**Pull request merged**
