### PR TITLE
Sync templates from community-templates (1.18)

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by sean797** [comment]
We do this fairly often.. I think it would be worth automating via packing for production installs and forklift of development environments

**Comment by ares** [comment]
should not be related, but just in case [test foreman] [test katello]
otherwise :+1:

**Comment by mmoll** [comment]
Foreman test failures related, some RancherOS stuff or test updates need cherry-picking, I guess.

**Comment by lzap** [comment]
Develop PR is at https://github.com/theforeman/foreman/pull/5622

**Comment by lzap** [comment]
I merged the develop part.

**Comment by xprazak2** [comment]
I added a second commit that makes sure the new templates are seeded. Lets see if tests pass now.

**Comment by mmoll** [comment]
test failures unrelated :green_heart:

**Comment by mmoll** [comment]
merged, díky @xprazak2!

**Pull request merged**
