### PR TITLE
Fixes #12946 - Do not fail miserably when compute instance is not found.

### PR DESCRIPTION
**Pull request by imriz**

### CODE REVIEW

**Comment by dLobatog** [comment]
@imriz Thanks, that's useful. 

Would you mind printing out the `body` of the response on screen, and also adding tests? With this fix, it'll fail silently which is not better IMO.

**Comment by imriz** [comment]
@dLobatog It doesn't fail silently... I am running with this fix, and it does show the body

**Comment by imriz** [comment]
@dLobatog btw, I think that the root cause of this, is that delUserData (app/models/concerns/orchestration/compute.rb:111) sets the user_data attribute to nil, instead of removing it. What do you think?

**Comment by imriz** [comment]
I've updated the PR - When user data is being rolled back, it should be _removed_, and not set to nil

**Comment by imriz** [comment]
PR updated - Adding a test.

**Comment by imriz** [comment]
@dLobatog can you please have a look? Thanks :)

**Comment by imriz** [comment]
Can anyone have a look?

**Comment by dLobatog** [comment]
Merged as 3ce9810bc26e49a11ba6bc978deaf5520311efc8, thanks @imriz!

**Pull request closed without merging**
