### PR TITLE
Fixes #10683 - Permission to view individual compute resource VMs is incorrect

### PR DESCRIPTION
**Pull request by untsakas**
Same issue as in http://projects.theforeman.org/issues/6331 also affects oVirt compute resource.

### CODE REVIEW

**Comment by dLobatog** [comment]
Hi @untsakas !

Looks like the same issue indeed. I've created [10683](http://projects.theforeman.org/issues/10683) to track it, could you amend your commit to look like the foreman bot suggested? 

`Fixes #10683 - Permission to view oVirt VMs in compute resource is incorrect`

I'll change it myself upon merge if tests are green.

[test] <- this triggers our Jenkins job to run a test suite against this change

**Comment by domcleal** [comment]
It'd also be great if you could apply this to the other identical pages (app/views/compute_resources_vms/index/_*.html.erb), not sure why I didn't in the original change!

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks very much @untsakas.  Merged as 5daf26a.

**Pull request closed without merging**
