### PR TITLE
Refs #10337 - Update Host searches to use outofsync_interval

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by domcleal** [comment]
app/views/dashboard/_status_widget.html.erb too had some "5" references, see https://github.com/theforeman/foreman/pull/2342/files#r29494478.

I'm not sure I follow your comment about recent not using the 5 minute out of sync interval over here: https://github.com/theforeman/foreman/pull/2342#issuecomment-99396199.  If the setting is meant to indicate how many minutes after the run interval that the host is no longer "active" then I think it should probably be consistent and use the setting?  Host::Managed.recent is used in app/services/dashboard/data.rb for showing lists of active hosts...

**Comment by dLobatog** [comment]
Updated, I didn't see the dashboard thing, now it makes more sense. Thanks @domcleal for taking the time to review.

**Comment by domcleal** [comment]
:+1: but just noticed one more instance, Host::Managed#no_report which is used for the status icons on the host list.  Could you change that "3" to the setting please?

**Comment by dLobatog** [comment]
Updated!

**Comment by domcleal** [comment]
Merged as e57ed7b, thanks @eLobato!

**Pull request closed without merging**
