### PR TITLE
fixes #5242 - Update user upon every logon

### PR DESCRIPTION
**Pull request by ares**
Attributes and group memebership are being updated upon every logon.

This is a new PR that replaces #1391 it's squashed and implements reviews from original PR

### CODE REVIEW

**Comment by ares** [comment]
@domcleal could you please go over it again and check whether your concerns were addressed (except the delete one which I commented in #1391)

**Comment by domcleal** [comment]
Looks good, thanks.

**Comment by domcleal** [comment]
@ares some 1.8.7 failures: http://ci.theforeman.org/job/test_develop_pr_core/993/database=postgresql,puppet=3.0,ruby=1.8.7/testReport/junit/%28root%29/UserTest/test_0048__find_or_create_external_user_updates_external_groups/

**Comment by domcleal** [comment]
Merged as 1e8a508 for Foreman 1.6.0.  Thanks @ares and @adelton!

**Pull request closed without merging**
