### PR TITLE
Fixes #13401 - ssh_provision: safe stderr as well

### PR DESCRIPTION
**Pull request by agx**
The log file currently only gets stdout which leaves only guessing when
looking for provision errors.

### CODE REVIEW

**Comment by domcleal** [comment]
Just a couple of notes on the commit message: a) it's missing the leading # in front of the ticket number, and b) "save" rather than "safe".

[test]

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@agx It's still missing the # before the ticket number in the commit title, that's why the foreman bot groans. I can fix it on merge if tests work.

On another  @ohadlevy @domcleal mind to add him to the foreman org? He has submitted a few patches already. @agx this means your PRs will automatically run through CI from then on :smile:

**Comment by domcleal** [comment]
Gladly - please see your e-mail for an invitation @agx.  If/once you accept, please set your membership to public on https://github.com/orgs/theforeman/people for our system to see you.

**Comment by dLobatog** [comment]
Odd, It wasn't able to update from 1.8 because the Rails 3 gem could not be found. I'll pull the trigger again [test]

**Comment by dLobatog** [comment]
Great, looks fine now. The error in the integration test does not have to do with this. Merging

**Comment by dLobatog** [comment]
Merged as f9d2bf10a168d8f4d76a35b97aae4d630c54e376, thanks @agx!

**Comment by agx** [comment]
Hi,

On Thu, Jan 28, 2016 at 12:35:53AM -0800, Daniel Lobato García wrote:

> @agx It's still missing the # before the ticket number in the commit title, that's why the foreman bot groans. I can fix it on merge if tests work.

Fixed, but I figure you already merged this. Thanks!

> On another  @ohadlevy @domcleal mind to add to the foreman org? He has
> submitted a few patches already. @agx this means your PRs will
> automatically run through CI from then on :smile:

Great. I joined happily!
 -- Guido

**Pull request closed without merging**
