### PR TITLE
Fixes #36915 - Correct datetime input for report generation

### PR DESCRIPTION
**Pull request by sjha4**
Steps to reproduce:
1. Go to Monitor > Report Templates > Click on Generate against any template.
2. On the template generate form > Click the Generate at calendar icon to open input datetime calendar. The date/time overlap.
3. Patch with this PR.
4.  On the template generate form > Click the Generate at calendar icon to open input datetime calendar. The date/time should not overlap.
5. Upon entering some value in the field and generating report, make sure report generation task is scheduled for the selected time in foreman tasks.

### CODE REVIEW

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test]

**Comment by ianballou** [comment]
Before: 
image

After:
image

The box looks better but I'm not seeing a time picker.

**Comment by sjha4** [comment]
> The box looks better but I'm not seeing a time picker.

Guessing it's a firefox thingy..

**Review by ianballou — APPROVED** [review]
Works great!

image

**Comment by MariaAga** [comment]
@ianballou Please don't merge PRs with failing tests :) added a fix here: https://github.com/theforeman/foreman/pull/9910

**Comment by ianballou** [comment]
@MariaAga sorry about that, I thought it was just the rpm build that seems to usually be failing. I'll take a look at the other one.

**Comment by sjha4** [comment]
Oh I missed that failing test too..Sorry about that..

**Pull request merged**
