### PR TITLE
fixes #10956 - add annotation support for vmware

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by timogoebel** [comment]
crazy [test] failures...

**Comment by angystardust** [comment]
Great feature, @timogoebel ! It will be ever greater if you could make a flag to copy the annotation in the "Additional Information -> Comment" field. Just wondering if it may be doable...

**Comment by dLobatog** [comment]
@angystardust That'd probably be useful, I'm going to go with merging this already though as it's worth it as it stands already.

**Comment by dLobatog** [comment]
Merged as 5cdb5b36c2fe3149614c0aea6cdf35f85611a741, thanks @timogoebel!

**Comment by timogoebel** [comment]
@angystardust : I agree with @dLobatog here. Would you mind opening a Redmine describing the feature you want in more detail? http://projects.theforeman.org/projects/foreman/issues/new

**Pull request closed without merging**
