### PR TITLE
Fixes #10664 - map only physical interfaces in compute orchestration

### PR DESCRIPTION
**Pull request by ares**
@tstrachota could you please review? Maybe the compute attributes should not only be hidden but also disabled in the UI. Anyway, this seems to fix the issue for me.

### CODE REVIEW

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
:+1: it fixes the issue.

I know it's difficult to test the code around orchestration and it requires quite some mocking but would you mind adding a test for the behaviour to `orchestration/compute_test.rb` ?

**Comment by ares** [comment]
added tests, @tstrachota let me know if I should change PR flags

**Comment by tstrachota** [comment]
Thanks, @ares. Ready to merge from my point of view.

**Comment by dLobatog** [comment]
[test] , it timed out for some reason

**Comment by dLobatog** [comment]
Merged as 0006c5c6f34f2bd8c8777032d39d7fa129d6c7a2, thanks @ares!

**Pull request closed without merging**
