### PR TITLE
fixes #17007 - normalize dns records before comparison

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by lzap** [comment]
Thanks, could you create "bang" helper methods in the Validations class and use them? This will look much consistent.

**Comment by domcleal** [comment]
@lzap apologies, I'd been reviewing this and the page didn't update.

Thanks @timogoebel, merged.

**Comment by lzap** [comment]
No biggie, this is fine too.

**Comment by timogoebel** [comment]
@domcleal + @lzap : Thank you both.

**Pull request merged**
