### PR TITLE
fixes #26052 - add missing IDs to Layout

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Review by ohadlevy — DISMISSED** [review]

**Comment by glekner** [comment]
I'm using the `url` (e.g. Hardware Models is `menu_item_models` for the new attributes.
I assumed dividers don't need the additional attributes.

**Comment by glekner** [comment]
Dashboard url is `/` so the attributes are wrong

`<a id="menu_item_" data-id="aid_" href="/"><span class="list-group-item-value">Dashboard</span></a>`

maybe we should hardcode the attributes in the server @ohadlevy ?

**Comment by waldenraines** [comment]
@lhellebr you may want to have a look at this as I'm not sure what the IDs were prior to the react navigation.

**Review by tbrisker — CHANGES_REQUESTED** [review]
A couple of comments -
1. This does not restore the same ids for the menu items as before. The original id was generated by the item name - https://github.com/theforeman/foreman/blob/1.19-stable/app/helpers/home_helper.rb#L41. This means that changing it to be based on the url will still cause multiple failures for QE automation.
2. The data `aid` attribute should no longer be used by automation - see https://github.com/theforeman/foreman/pull/5712#issuecomment-409261110 and https://github.com/SatelliteQE/airgun/commit/8438e7274a73e01dcb7073f47068eba877e2bed5 which dropped it completely, so we don't need to continue using this attribute which was only used for QE automation.

**Comment by glekner** [comment]
removed `data-id` and changed `id` to item.name
Also opened a [quick fix PR](https://github.com/patternfly/patternfly-react/pull/1574) because right now theres an empty `data-id` attribute
Screenshot 2019-03-14 12 06 48

**Comment by glekner** [comment]
- rebased and updated PF version, so data-id isn't shown anymore

**Review by tbrisker — CHANGES_REQUESTED** [review]
See inline comment; this also needs updating the react-patternfly rpm version

**Comment by glekner** [comment]
@tbrisker can we merge? `aid` is no longer used

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
Thanks @glekner! I didn't notice that you pushed the update a couple of weeks ago.

**Pull request merged**
