### PR TITLE
[CP 1.20] Fixes #25207 - do not instantiate during permission checks

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
It works.

**Comment by lzap** [comment]
There are 7 failures, probably relevant?

**Comment by ares** [comment]
I'd say unrelated, ruby 2.3 and 2.5 is green, audits fact values are known to be problematic

**Comment by lzap** [comment]
Kay letting the rel engineering to do the pick. Thanks.

**Pull request merged**
