### PR TITLE
add fact value audting support

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by domcleal** [comment]
I think we need a bit of configuration around this, either a global setting (at least) or a method like a UI or ignored_environments to exclude facts from this.  I can imagine many environments having custom facts that they wouldn't want audited, or that facter introduces some more in the future that users need to be able to exclude.

**Comment by ohadlevy** [comment]
@domcleal I tend to agree with everything you said, IMHO the current auditing view would not work that well, there are different scenarios you would probably want to track, e.g.
All facts that change for a given host, vs a specific Fact that change on many hosts.

I would also assume we want a different UI, maybe something with a timeline?

**Comment by domcleal** [comment]
Indeed, and we already have something similar in the trends part of Foreman.

**Comment by domcleal** [comment]
Closing due to no activity.

**Pull request closed without merging**
