### PR TITLE
Fixes #21946 - Matches generator error when calling #fact_name

### PR DESCRIPTION
**Pull request by bitcrush**

### CODE REVIEW

**Comment by ShimShtein** [comment]
[test foreman]

**Review by alexjfisher — APPROVED** [review]
LGTM.

Bug crept in when fact_value was extracted into its own method.  Original code here. https://github.com/theforeman/foreman/pull/3701/files#diff-bec20964ead6a00adfe25f42324af3e1L130

**Review by tbrisker — APPROVED** [review]
Welcome @bitcrush and thank you very much for the contribution!

**Comment by tbrisker** [comment]
Merged as fc6bd230ff83180493df1f10517d0c91b4b8a047 with minor modification to commit message (to make it inline with our style guidelines). Thank you @bitcrush !

**Comment by tbrisker** [comment]
Looks like github now blocks manual merges with modification, reopening. @bitcrush, can you please update the commit message and push again to your branch?

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
Ok, so by pushing to your branch I managed to merge. Thanks again @bitcrush and sorry for the noise!

**Pull request merged**
