### PR TITLE
Fixes #6538 - User group vs usergroup name consistency

### PR DESCRIPTION
**Pull request by boaz0**
I haven't seen any inconsistency in the app/view/*. However, I have changed to user group in app/controllers/api/v1/usergroups_controller.rb and app/models/auth_sources/auth_source_ldap.rb.

### CODE REVIEW

**Comment by orrabin** [comment]
[test]

**Comment by orrabin** [comment]
[test]

**Comment by boaz0** [comment]
What the devil?

```
Resolving dependencies...
Could not find gem 'rails (= 3.2.18) ruby' in the gems available on this
machine.
Build step 'Execute shell' marked build as failure
```

Is this my fault?

**Comment by orrabin** [comment]
@ripcurld00d it's not your'e fault all of the tests failed.
[test] again

**Comment by boaz0** [comment]
@orrabin i see :) thanks.

**Comment by domcleal** [comment]
There's a "Usergroup" on the first form tab, stored in app/views/usergroups/_form.html.erb.

**Comment by boaz0** [comment]
Yes, you're right. I've also found some in views/usergroups/index.html.erb.
I used a wrong regex when running grep.
Anyhow, I will fix this and squash.

**Comment by boaz0** [comment]
I am not sure what `s_` does. Is it okay to replace `s_("Usergroup|Name")` with `s_("User group|Name")`?

**Comment by orrabin** [comment]
[test]

**Comment by domcleal** [comment]
Don't change the s_() calls, what happens in these is that s_() returns the section after the | but translated - users will never see the first part.  The "Usergroup" in those refers to the table name, which isn't changing, so just keep them as-is.

**Comment by boaz0** [comment]
Uh huh. OK.

**Comment by orrabin** [comment]
[test]

**Comment by isratrade** [comment]
merged as f45717f8666c892ebf704dee00380fc341c97007. Thanks @ripcurld00d !

**Pull request closed without merging**
