### PR TITLE
Fixes #31664 - add OpenWrt icons

### PR DESCRIPTION
**Pull request by ares**
OpenWrt is correctly detected from facts however we don't have a good
representing icon. This adds the official logo. Adding a logo based on
the OpenWrt trademark policy that can be found at https://openwrt.org/trademark#guidelines_for_using_logos

Foreman is not affiliated with OpenWrt. OpenWrt is a registered trademark owned by Software Freedom Conservancy (SFC)

before
foreman_openwrt

### CODE REVIEW

**Comment by tbrisker** [comment]
I don't think we can include this logo in our repo. https://openwrt.org/trademark#how_to_use_the_openwrt_trademarks requires quite harsh disclaimers and limitations.

**Comment by ares** [comment]
I didn't get any negative reaction here https://forum.openwrt.org/t/openwrt-logo-smaller-than-75-pixels/85535 but I'll contact official address with the question.

**Review by lzap — DISMISSED** [review]
Technically, all good.

Let's wait for the approval.

**Comment by ares** [comment]
The use has been officially approved

"The usage you described is in compliance to the OpenWrt logo guidelines, you can use it."

**Comment by tbrisker** [comment]
@ares thanks! can you please modify the commit message to include who gave the approval and when, just in case someone in the future needs to check?

**Comment by ares** [comment]
Done

**Review by tbrisker — APPROVED** [review]
Thanks @ares !

**Pull request merged**
