### PR TITLE
fixes #26727 - import host with bonded primary interface

### PR DESCRIPTION
**Pull request by timogoebel**
This is an alternative fix for #6731.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Good test, let's have it! Thanks.

**Comment by lzap** [comment]
F*****K and I broke discovery tests. We need discovery alongside with Katello the plugin deserves it it was the top plugin for years (now katello and rex are first on the ladder).

**Comment by ares** [comment]
there is a luna pipeline that contains it, perhaps we just need to run discovery tests there?

**Comment by timogoebel** [comment]
I think this is the wrong place for this discussion, but how would that have helped?
This PR fixes a bug and introduces a test so we don't break it again. Discovery tests are affected by this (if i understand this correctly) and the tests broke there. We need to fix them now. Annoying, but isn't that the purpose of these tests?

If they were run with every core PR, we'd still need to fix the discovery tests.
I see it this way: Discovery tests work. :-)

**Comment by lzap** [comment]
Yeah wrong PR, wrong place. I was just unhappy with an unexpected work. I am going to tackle it this week.

**Comment by ofalk** [comment]
> This is an alternative fix for #6731.

Confirmed this fixes the situation for my customer when applied together with https://github.com/theforeman/foreman/pull/5989 .

**Pull request merged**
