### PR TITLE
Release 1.19.0-RC1

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
This can probably be merged when test_1_19_stable has completed.

**Comment by ehelms** [comment]
@ekohl Looks like addition of community templates broke tests

Makes me wonder if we should be updating these at this point, the whole idea for RC1 is to take nightly as is. I feel like we should be merging these in about a week or a few days prior to branch and then maybe again for RC2.

**Comment by ekohl** [comment]
@ehelms it's standard procedure to take the nightly templates after branching. Looks like it's a new file should be added to the seeds as well.

**Comment by ehelms** [comment]
@ekohl I get its standard, I'm saying let's consider changing that since it can introduce instability and does not get tested nightly

**Comment by ehelms** [comment]
The failing test looks like an intermittent failure but I am not familiar enough to know

**Pull request merged**
