### PR TITLE
Added arm64 support to Travis-CI

### PR DESCRIPTION
**Pull request by odidev**
Added 'arch: arm64' to .travis.yml file.

Signed-off-by: odidev odidev@puresoftware.com

### CODE REVIEW

**Comment by sharvit** [comment]
Thank you for your contribution @odidev.

I am wondering, what is the reason to add arm64 to Travis? are you using an arm64 machine for development?

* Notice it's not the only testing stack (Jenkins, gh-actions), and it only used run the javascript unit testing.

**Comment by rhenwood-arm** [comment]
@sharvit  (I'm working with @odidev ): we're looking at a few scenarios, one of which is developing on AArch64. However, as you point out, this PR only triggers a JS unit testing suite. 

More valuable for AArch64 testing is how the tool behaves at it's core competency: managing server lifecycle. I will work with @odidev on looking at other testing options. Do you have any suggestions?

**Comment by sharvit** [comment]
Very interesting...

1. I would start by trying to run foreman development/production server on an arm64, could you do that?
2. We have too many testing stacks
    1. The js unit-testing in Travis, looks like it works pretty well.
    2. The "main" testing stack is the ruby tests, see the ruby-tests section here: https://theforeman.org/handbook.html
    3. Plugins have their own ruby/js testing.
    4. foreman-js: https://github.com/theforeman/foreman-js

My main concerns are:

1. We will need double the CI work (cost & time) where atm we already wait a long time for the CI to finish.
2. It might be more difficult to maintain two different architectures, especially if we will need to maintain different sets of code/configs/tools

@tbrisker @ekohl anything you would contribute to the conversion?

**Comment by tbrisker** [comment]
Replied in https://community.theforeman.org/t/add-aarch64-support-to-travis-ci/19755/2 with some more context.

**Pull request closed without merging**
