### PR TITLE
Refs #28874 - bump fog version

### PR DESCRIPTION
**Pull request by ezr-ondrej**
I've forgotten to bump fog version in #7650

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej

**Comment by tbrisker** [comment]
please cherry-pick to 2.1 as well

**Comment by tbrisker** [comment]
nm, cped it to 2.1 as d9a03b1d1

**Comment by ezr-ondrej** [comment]
> nm, cped it to 2.1 as [d9a03b1](https://github.com/theforeman/foreman/commit/d9a03b1d16ecabcdbca74e18a0bc973fddd3d9d0)

Thanks :heart:

**Pull request merged**
