### PR TITLE
Fixes #10817 - Initialize all autocomplete fields that needs it

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares Thanks, is there any example of this in the current forms? I couldn't find any form with autocomplete embedded in another page with autocomplate (/filters search uses autocomplete but the form not displayed as two-pane)

**Comment by ares** [comment]
@eLobato no, actually this was the reason why filters aren't displayed in two-pane. @shlomizadok did some testing though.

**Comment by shlomizadok** [comment]
@eLobato - I have tested (and it works very well) with 
/users -> mail preferences -> audit build query
untitled

**Comment by dLobatog** [comment]
Merged as ba6271ccc48ce149e7f1bb29162ee11925760ae9, thanks @ares!

**Comment by dLobatog** [comment]
Thanks to @shlomizadok too, my mergepr script is not that smart as to identify the tester yet :smile:

**Pull request closed without merging**
