### PR TITLE
Fixes #30681 - fact value host search

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by ares** [comment]
@ShimShtein this seems to solve your problem, mind to take a look?

**Review by ShimShtein — COMMENTED** [review]
I still don't know why it helps, but it does for me.

@ares, if I understand the code correctly, it means the user will be able to search hosts by fact name/value pare even if the user does not have permission to view that specific fact.

**Comment by ezr-ondrej** [comment]
> I still don't know why it helps, but it does for me.
> 
> @ares, if I understand the code correctly, it means the user will be able to search hosts by fact name/value pare even if the user does not have permission to view that specific fact.

It's just "please don'd bring another stuff from other places"
It makes sure, there are no prior joins (from inherited scope or default scope). That's it.

**Review by ares — APPROVED** [review]
Thanks @ezr-ondrej, merging!

**Pull request merged**
