### PR TITLE
Fixes #27460 - Add comp_resource to hostgroup api

### PR DESCRIPTION
**Pull request by mdellweg**
The api/v2 response of hostgroup was missing informations of the
selected compute resource.

### CODE REVIEW

**Comment by evgeni** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Thanks @mdellweg !

**Comment by timogoebel** [comment]
Thanks, @mdellweg.

**Comment by timogoebel** [comment]
@mdellweg: This might be worth cherry-picking to `1.23-stable`.

**Comment by mdellweg** [comment]
> @mdellweg: This might be worth cherry-picking to `1.23-stable`.

How can i do that?

**Comment by tbrisker** [comment]
> > @mdellweg: This might be worth cherry-picking to `1.23-stable`.
> 
> How can i do that?

check out 1.23-stable and run `git cherry-pick -x bcbc930` and open a pr (or ping me to do it)

**Pull request merged**
