### PR TITLE
Fixes #12660 - adding no-stretch class to host parameters textarea af…

### PR DESCRIPTION
**Pull request by orrabin**
…ter unhiding the value

### CODE REVIEW

**Comment by domcleal** [comment]
It's fine as-is, but a thought - could we store the classes from the old control on the new hidden field before replacing them, then restore them after?  That way we won't have to worry about these files being in sync, any change to the original input fields will always stay.

**Comment by orrabin** [comment]
@domcleal the editor shouldn't pass on it's classes but I fixed it for the textarea, class is now passed between the textarea and hidden field.

**Comment by orrabin** [comment]
@domcleal preserving the classes only works when you start out with a parameter that isn't hidden and hide it. If you have a hidden parameter then the view has already put a password field there without the class `no-stretch` (there is no old control with that class so we would need to add it anyway).

**Comment by dLobatog** [comment]
@orrabin Sorry, I'm confused about what is this fixing? I'm definitely not looking at the right thing, on develop, the no-stretch class on Host Parameters seems to work the same as in this PR, as input tags are not stretchable.

file

**Comment by domcleal** [comment]
The class should set a minimum size vertically, but IME it only applies to Firefox which otherwise lets you resize the field to below one line's height.  In Chrome it's already prevented.

**Comment by tbrisker** [comment]
@domcleal @dLobatog The `no-stretch` class serves two purposes:
1. prevent horizontal stretching of text areas to prevent messing up the form layout.
2. prevent FF from vertically re-sizing the text area to less then one line.
In the case of hidden parameters that are unhidden, the javascript did not apply this class to the resulting text area.

**Comment by domcleal** [comment]
Merged as 420ab77, thanks @orrabin.

**Pull request closed without merging**
