### PR TITLE
Fixes #20470 - Audit role filter changes

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ares** [comment]
Tests are failing. From testing it seems to only audit the changes of search and taxonomy search. I think the request is for tracking what permissions were added to the filter. I was trying to look how to do it and it does not seem trivial. I think we'd need to add a before_save callback and use audit_comment for reasonable output, since the has_many associations can't be easily audited.

**Comment by tbrisker** [comment]
Pushed with fix to tests and better filter naming (permissions list instead of id). Still doesn't audit when permissions on an existing filter change (like any other many-to-many relationship that isn't audited atm). 
Screenshot of example audit log:
screenshot from 2017-08-14 16-36-58

**Review by dLobatog — CHANGES_REQUESTED** [review]
@tbrisker This needs a rebase, changes look reasonable, thanks !

**Comment by tbrisker** [comment]
@dLobatog thanks, rebased

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @tbrisker !

**Pull request merged**
