### PR TITLE
Fixes #35622 - Add kernel release to new host UI OS card

### PR DESCRIPTION
**Pull request by chris1984**
Requires this backend change:

https://github.com/theforeman/foreman/pull/9460

screenshot-192 168 121 2-2022 10 11-10_11_10

### CODE REVIEW

**Comment by lfu** [comment]
How about Kernel modules mentioned in the Jira card?

**Comment by lfu** [comment]
LGTM 👍🏻 

Screenshot from 2022-10-11 14-48-33

**Comment by parthaa** [comment]
[test katello]

**Comment by chris1984** [comment]
@jeremylenz tests are green :)

**Comment by chris1984** [comment]
@jeremylenz backend card is merged, can this one get in?

**Review by jeremylenz — APPROVED** [review]
LGTM, thanks @chris1984 !

**Pull request merged**
