### PR TITLE
fixes #13527 - remove 'users' from attr_accessible

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by dLobatog** [comment]
@thomasmckay Why should .users not be mass-assignable within the UI? I agree getting 'users' through /organizations/:id/ GET then not being able to use it on PUT is inconsistent and wrong.

If you want `:users` to be a supported call - have you tried adding `param_group :users` to the API taxonomies controller? That should allow Apipie to recognize it.

**Comment by thomasmckay** [comment]
@dLobatog - This is unrelated to apipie. It causes an error when it is allowed through. Was there a reason it is present at all instead of sticking to the pattern of the others (_ids and _names)?

**Comment by thomasmckay** [comment]
[test]

**Comment by thomasmckay** [comment]
closing as not-a-bug

**Pull request closed without merging**
