### PR TITLE
fixes #8056 - replaces . (dot) in params with - (hyphen) in params

### PR DESCRIPTION
**Pull request by shlomizadok**
cc @tstrachota

### CODE REVIEW

**Comment by stbenjam** [comment]
Same for org selector, I have an org called "Stephen's Widgets, Inc."

Previously, it linked to `/organizations/1-stephens-widgets-inc` but now links to `/organizations/1-Stephen's Widgets, Inc.` which is broken.

This PR fixes it, but the URL still has spaces in it, is that intended? `/organizations/1-Stephens%20Widgets%20Inc`

**Comment by stbenjam** [comment]
Ah ok, according to @domcleal the spaces are intentional

**Comment by dLobatog** [comment]
Seems good, even for for UTF8 + dots, I get urls(correct) like: 1767-acron-ѠѡѢѣѤѥѦѧѨѩѪѫѬѭѮѷѸѹѺѻѼѽѾѿ-domain/

Spaces are OK since browsers will just translate the URL. 

@shlomizadok could you add a quick test that verifies characters like that work and, dots are replaced by hyphens in the URL? Checking that parameterize does its job in the test is fine.

**Comment by dLobatog** [comment]
Merged as 873467e4c263c1808677ad8c04c0e3493272353b , great job @shlomizadok :wine_glass: !

**Pull request closed without merging**
