### PR TITLE
Fixes #9967 - make sure User.current is isolated

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by ehelms** [comment]
Test run against latest PR to Katello -- http://ci.theforeman.org/job/test_katello_core/12275/database=postgresql,ruby=1.9.3/console

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
so we must have something different in our test script, since the job still fails http://ci.theforeman.org/job/test_katello_core/12277/

EDIT: oh, I didn't realize https://github.com/Katello/katello/pull/5161 is not in yet

**Comment by stbenjam** [comment]
@ares Merged Katello/katello#516

[test]

**Comment by dLobatog** [comment]
Merged as fbbda1282c4ea4f17bd12132aa61f4a66832e8b8, thanks @ares

**Pull request closed without merging**
