### PR TITLE
fixes #3911 - jquery.multi-select.js should disable selected ids that are passed to :disabled =>

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@abenari, I thought this was previously merged.  I wonder who it was removed.  I don't see the change in git history ???

**Comment by domcleal** [comment]
@isratrade looks like we lost it in the VPC support, beed05de7562fbc74d751860434b681d431acfe5.  Might have been a merge accident as the history was a bit messy...

**Comment by isratrade** [comment]
@domcleal, any reason why it was removed in beed05d.

**Comment by domcleal** [comment]
The only reason that code was touched IIRC was because the multi-select is being reloaded by the VPC code (part of the network selection on EC2 hosts) in client-side JavaScript.  As long as that continues to work, we could revert.

**Comment by ohadlevy** [comment]
@isratrade can you confirm?

**Comment by isratrade** [comment]
@domcleal, I'm don't understand how this PR will loading or re-loading of a multi-select.  The previous code only disables on the 'left side' (selectable) and the fix allows for the 'right side' (selected) to also be disabled.   

I see in the VPC code that `:disabled =>` is passed, but it returns `true` or `false` rather than id's.  Maybe this is the issue?   

``` ruby
 selectable_f f, :security_group_ids, groups, {},
                    { :multiple => true, :label => _("Security groups"), :disabled => !(@host.nil? || @host.ip.empty?),
```

The loc / org code passes an array of id's to `:disabled =>`

``` ruby
multiple_selects f, :smart_proxies, SmartProxy, taxonomy.selected_ids[:smart_proxy_ids],
           {:disabled => taxonomy.used_and_selected_ids[:smart_proxy_ids], :label => ''},
```

Also, the VPC code uses `selectable_f   :multiple => true` whereas taxonmoies uses `multiple_selects`
I think it's important for this is be merged.  @abenari, do you see any re-loading issues affecting `/views/compute_resources_vms/form/_ec2.html.erb`?

**Comment by isratrade** [comment]
@domcleal, can you check the VPC code works as expected. I haven't been able to find any changes in behavior before or after the PR fix, but then again, I may not know every case.

**Comment by domcleal** [comment]
Yes, I will.

**Comment by isratrade** [comment]
@domcleal, ping

**Comment by domcleal** [comment]
Thanks @isratrade, can't see any regressions, merged as 28595e2 for Foreman 1.4.0.

**Pull request closed without merging**
