### PR TITLE
Fixes #9859 - add STI to environments

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@jlsherrill Do you think it makes sense to merge this before https://github.com/theforeman/foreman/pull/2144 ? Or do you actually want to make _any_ environment optional, not just Puppet. 

I'd say the latter makes more sense, is there any reason why environments are mandatory set? I think not.

**Comment by ohadlevy** [comment]
i guess it make sense to select the host configuration type, and if it has
a puppet type, then it needs a puppet env, otherwise it should be optional?

**Comment by ares** [comment]
host can be assigned to multiple environments later but still I think STI would be good anyway as e.g. puppet and chef environment are both environments and share things like association, scopes etc. Second phase would be adding chef_environment and possibly renaming environment to puppet_environment.

Anyway this PR breaks some tests so it will take me some time to fix.

**Comment by jlsherrill** [comment]
@eLobato i think they can probably be merged in any order, i'm not sure it really matters?

@ohadlevy when you say 'host configuration type' I am assuming you are referring to something that does not exist yet?

**Comment by ohadlevy** [comment]
@jlsherrill yes, I mean puppet managed host, chef/salt etc...

**Comment by domcleal** [comment]
Tests are red.

**Comment by ares** [comment]
Rebased, failing tests are caused by Katello, compensating PR opened at https://github.com/Katello/katello/pull/5478

**Comment by domcleal** [comment]
I don't think adding STI like this is a good idea, as the general assumption about the Host::Managed to Environment association is that the env will always be a Puppet one, and have further associations to Puppet classes.  I suspect there could be a lot of issues when this is anything other than a PuppetEnvironment.

I think the association must be renamed to only match PuppetEnvironment, and for any new Environment subclasses to add their own associations.

I'd also question whether STI is strictly necessary if you renamed the association, and if it just adds unnecessary complication, when different types of environments could simply be served by different models - and if needed, to have useful associations in a non-STI base class or mixin.

All the controllers you're touching should also be renamed and changed to deal with PuppetEnvironment and not Environment - at the moment you've changed bits of the behaviour (e.g. references in the controllers to the class name), but their resource_class method will still return Environment etc.

**Comment by ares** [comment]
OK, I came to similar conclusion when I got back to this PR recently. Originally the motivation was to share the environment relation but it turned out it would be better if host could belong to multiple cfgmgmt environments.

The actual renaming and cleaning is out of my time possibilities right now. Maybe there should be some feature team to extract Puppet to a plugin. Thanks @domcleal for taking the time you've spent on reviewing. I'm closing this.

**Pull request closed without merging**
