### PR TITLE
fixes #19912 - added Style/WordArray cop

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by tbrisker** [comment]
I think for this rule we should enforce the bracket format rather then the percent format, more readable imho. Any other opinions @theforeman/core ? feel free to give thumbs up/down.

**Comment by timogoebel** [comment]
+1 for bracket format

**Review by dLobatog — COMMENTED** [review]
-1 to the bracket format - I would prefer to stick to https://github.com/bbatsov/ruby-style-guide as much as possible. It's the closest thing to PEP8 we have in Ruby and IMO it's easier to read when all projects adhere to that standard (which is what rubocop is meant to do)

**Comment by ares** [comment]
I vote for keeping `%w()`, `%w[]` and `[]` allowed. I don't think any of these would be significantly better, I'd keep it disabled.

**Comment by iNecas** [comment]
If the purpose of Rubocop is to keep things consistent, that we probably want to have this rule. I would vote for bracket format: the reason would be to be open to the sys-admins community, that not necessary need to know Ruby that well, while know other languages, and `%w[]` thing is pretty specific to Ruby. You can take my vote for it. I will not spend any more time discussing it :) Thanks for letting us to have voice in the decision.

**Comment by tbrisker** [comment]
Since no agreement was reached, it seems that we should allow all styles. Please move the cop to `.rubocop.yml` and rollback any fixes, or close this PR.

**Pull request closed without merging**
