### PR TITLE
Test jenkins chromium

### PR DESCRIPTION
**Pull request by ezr-ondrej**
TEST

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by jlsherrill** [comment]
I think i've  i've isolated the problem independent of testing to running this command:
```
/usr/bin/chromium-browser --enable-plugins --enable-extensions --enable-user-scripts --enable-printing --enable-gpu-rasterization --enable-sync --auto-ssl-client-auth --user-data-dir=/tmp/chrom --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-gpu http://redhat.com --headless --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222  --remote-debugging-host=0.0.0.0
```

With the old version of chromium (where my tests work locally), this behaves normally as far as i can tell.   however  on latest, it errors:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/c82e1b8c-3645-46b9-821c-e284431781ad
Received signal 11 SEGV_MAPERR ffffffffffffffe9
#0 0x556716fe0519 base::debug::CollectStackTrace()
#1 0x556716f56696 base::debug::StackTrace::StackTrace()
#2 0x556716fdfeba base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x556716fe04ae base::debug::(anonymous namespace)::StackDumpSignalHandler()
#4 0x7fabfe603630 (/usr/lib64/libpthread-2.17.so+0xf62f)
#5 0x5567173e792f net::CookieMonster::InternalInsertCookie()
#6 0x5567173ef98e net::CookieMonster::StoreLoadedCookies()
#7 0x5567173efc49 net::CookieMonster::OnKeyLoaded()
#8 0x5567173e34f0 base::internal::Invoker<>::RunOnce()
#9 0x55671857a699 network::SessionCleanupCookieStore::OnLoad()
#10 0x556718579043 base::internal::Invoker<>::RunOnce()
#11 0x5567185cefa5 net::SQLitePersistentCookieStore::CompleteKeyedLoad()
#12 0x5567185cedda base::internal::Invoker<>::RunOnce()
#13 0x5567185cff02 net::SQLitePersistentCookieStore::Backend::Notify()
#14 0x5567185cffee net::SQLitePersistentCookieStore::Backend::CompleteLoadForKeyInForeground()
#15 0x5567185ce766 base::internal::Invoker<>::RunOnce()
#16 0x556716fab162 base::TaskAnnotator::RunTask()
#17 0x556716fbd595 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#18 0x556716fbd9ae base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#19 0x5567170029d1 base::MessagePumpLibevent::Run()
#20 0x556716fbcef5 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#21 0x556716f90df6 base::RunLoop::Run()
#22 0x556716fcc58b base::Thread::ThreadMain()
#23 0x556716ff1f25 base::(anonymous namespace)::ThreadFunc()
#24 0x7fabfe5fbea5 start_thread
#25 0x7fabf779e8dd __clone
  r8: 00007fabe706fd60  r9: 0000000000000000 r10: 00003f20b096a570 r11: 00007fabf782e4d0
 r12: 00003f20b09fb140 r13: 00003f20b09a4840 r14: 00003f20b09dfdf8 r15: 0000000000000001
  di: 0000000000000001  si: 00003f20b09a40d8  bp: 00007fabe7070140  bx: 00003f20b09dfd80
  dx: 00003f20b09dfdf8  ax: 00003f20b09dfdf8  cx: 000055671f694980  sp: 00007fabe70700a0
  ip: 00005567173e792f efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000005
 trp: 000000000000000e msk: 0000000000000000 cr2: ffffffffffffffe9
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0922/154906.704706:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
```

**Comment by jlsherrill** [comment]
the odd thing, is i get the same error when running it through vnc.  It just doesn't work at all....

EDIT: meaning the plain browser doesn't work at all (chromium), irregardless of headless or not

 ~~EDIT2:  Although when i spun up a fresh centos7 box  (without foreman/katello) from forklift, yum updated, installed chromium, and tried the same command it worked fine~~  Nevermind, user error, it does reproduce.  

Even this command will reproduce:
```
/usr/bin/chromium-browser http://redhat.com  --headless
```

**Comment by jlsherrill** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1881142

**Comment by ezr-ondrej** [comment]
New chromium with fix released, tests are working now! :tada:

**Pull request closed without merging**
