### PR TITLE
fixes #3975 - add audit to classes Domain, Subnet, SmartProxy, Role, Usergroup, AuthSource, Image that were not audited

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
please see test failures :)

**Comment by isratrade** [comment]
@ohadlevy, re-committed with fix to seeds.rb.  seed_test now passes.

**Comment by domcleal** [comment]
Maybe bookmarks should be audited too?

**Comment by isratrade** [comment]
Bookmark audit added and re-committed.

**Comment by domcleal** [comment]
Thanks @isratrade, merged as 229d7436f6 for Foreman 1.4.

**Pull request closed without merging**
