### PR TITLE
Fixes #21510 - Update server config to rails 5.1

### PR DESCRIPTION
**Pull request by tbrisker**
These are options that are deprecated in rails 5.0 and will be removed
in 5.1.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker will this break nightly?

**Comment by mmoll** [comment]
yes it will, see #4836 for all the changes that are only 5.0 compatible

**Comment by mmoll** [comment]
also, there's already http://projects.theforeman.org/issues/21097

**Comment by mmoll** [comment]
@tbrisker maybe https://github.com/theforeman/foreman/pull/4836/commits/1d9cfafe993eeaf987731005f867ec001079e122 and https://github.com/theforeman/foreman/pull/4836/commits/fc505f3208f9f136885f142f8eead4cc6896aeec could get included here also

**Comment by tbrisker** [comment]
As usual, looks like @domcleal has beat me to it... I added the first one since it's in the config, the second one is in the tests so i think it deserves it's own pr.

**Comment by xprazak2** [comment]
@tbrisker, what is the status here? It seems like [1d9cfaf](https://github.com/theforeman/foreman/commit/1d9cfafe993eeaf987731005f867ec001079e122) and [b1bb3aa](https://github.com/theforeman/foreman/pull/4836/commits/b1bb3aa4d3e8572f84556ff6cf1af53ce3d865da) cover these changes, or am I missing something?

**Comment by tbrisker** [comment]
Closing in favor of GH-4836

**Pull request closed without merging**
