### PR TITLE
Fixes #23962 - Fix Style/ExpandPathArguments cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Do you want this PR get merged and thus this cop enabled? React :+1:
Do you want this cop to be disabled? React :-1:

**Review by lzap — DISMISSED** [review]
Thanks, rebase needed tho.

**Comment by lzap** [comment]
I apologize, tried Resolve button on github, it created some merge commit. We can probably still squash tho.

**Comment by mmoll** [comment]
I'll rebase this soon.

**Comment by mmoll** [comment]
rebased :green_heart:

**Comment by lzap** [comment]
This branch has conflicts that must be resolved - :man_facepalming:

**Comment by lzap** [comment]
It's a clean git rebase. I will merge this manually.

**Comment by lzap** [comment]
Oh wait I can't we have disabled direct push into `develop`, I guess you need another rebase.

**Comment by mmoll** [comment]
no problem, as there are no manual changes here, rebased.

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
Thank you very much for your contribution, this is now merged.

**Pull request merged**
