### PR TITLE
Fixes #23920 - add missing header in some of the welcome pages

### PR DESCRIPTION
**Pull request by amirfefer**
before:
hostsgroup1

after:
fixed-header

### CODE REVIEW

**Comment by amirfefer** [comment]
[test foreman]

**Comment by xprazak2** [comment]
Shouldn't we rather transform it into Patternfly Empty style?

**Comment by ohadlevy** [comment]
The idea here is that we can cp it to 1.18 as we can't introduce new
strings at this point.

**Comment by amirfefer** [comment]
more the that - it's fixing a regression that might affect plugins

**Review by tbrisker — APPROVED** [review]
Thanks @amirfefer !

**Comment by tbrisker** [comment]
Please open a CP to 1.18-stable

**Pull request merged**
