### PR TITLE
Fixes #30200 - plugin test fixtures

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Ability for plugins to define test fixtures

```ruby
Plugin.register :plugin_name do
  #load all fixtures in plugin/test/fixtures folder
  test_fixtures :all
end

### CODE REVIEW

**Comment by lzap** [comment]
While I have no problems with this, some time ago when we introduced FactoryGirl (as it was named) we made a statement that we would not accept any more fixtures into the codebase. We broke the rule many times, so I am good. @ares or @tbrisker can you give me a blessing? :-)

**Comment by lzap** [comment]
There are Hound failures.

**Review by ekohl — COMMENTED** [review]
If this is common, should we do this in foreman.git instead? I'm never a fan of copying code via templates. Alternatively it could be a gem, but that's probably too much.

**Comment by lzap** [comment]
> If this is common, should we do this in foreman.git instead? I'm never a fan of copying code via templates. Alternatively it could be a gem, but that's probably too much.

Was this comment supposed for a different PR? Not following.

**Comment by ekohl** [comment]
This PR defines a large method to load fixtures for all plugins. It feels like that's very generic code. Can we introduce some helpers in Foreman, perhaps by introducing some `ForemanPluginTestCase` class.

**Comment by ezr-ondrej** [comment]
Well I mean the `FactoryBot` would do just fine, I can refactor the uses of the fixtures instead :man_shrugging:
Fixtures are not all that bad though. I believe that if we need those to be in for many tests, it's much better as they are much simplier and thus faster. That's not my use case though

**Comment by ezr-ondrej** [comment]
We should use fixtures, but only for models that always needs to be present (settings, permissions..) and we should make sure plugins do not need to care about those. I've intended to use it for PuppetclassLookupKey fixtures and those should be refactor to use `FactoryBot` instead.
Closing this one for now. We can reopen if we hit proper use case

**Comment by ezr-ondrej** [comment]
I've opened #7772 to begin the path to get rid of the fixtures I intended to use from plugin.

**Comment by lzap** [comment]
> Fixtures are not all that bad though

Yeah, I did like FactoryGirl at all to be introduced. There was probably some reason, but I'd rather stick with fixtures for most of our tests.

**Comment by ezr-ondrej** [comment]
> Yeah, I did like FactoryGirl at all to be introduced. There was probably some reason, but I'd rather stick with fixtures for most of our tests.

It's pretty bad to have full database for all the tests, it is hard to keep track of purpose of each fixture (thus understand the test). Factories are more verbose about setup data for the given test :man_shrugging:

**Pull request closed without merging**
