### PR TITLE
fixes #5200 - set config group counters to zero by default

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by stbenjam** [comment]
While you're in app/views/config_groups/index.html.erb, can you set the default sort on numerical columns to be descending?

```
sort :hosts_count, :as => _('Hosts'), :default => "DESC"
```

Or should it be a separate issue?

**Comment by domcleal** [comment]
Good idea, fixed.

**Comment by ohadlevy** [comment]
@isratrade mind reviewing? thanks!

**Comment by isratrade** [comment]
Looks good @domcleal. I thought of doing this a couple of days ago, but didn't have internet access.

**Comment by ohadlevy** [comment]
@isratrade feel free to merge :)

**Comment by isratrade** [comment]
merged as a047e0d4721f39248aef78b0b5e2cf89dd9ca5bf, thanks @domcleal!

**Pull request closed without merging**
