### PR TITLE
Fixes #20672 - add button for autosign entry

### PR DESCRIPTION
**Pull request by ares**
before
before

after
after

### CODE REVIEW

**Comment by ares** [comment]
@Rohoover is this better?

**Comment by ares** [comment]
ping @Rohoover

**Comment by Rohoover** [comment]
@ares 
Way better! Wasn't sure what the plus sign did before, now it's very clear. Thanks!

bitmoji

**Comment by iNecas** [comment]
@dLobatog I see you not being very happy about the change. I would agree with @Rohoover here but don't want to merge without ensuring you're ok with that.

**Review by dLobatog — APPROVED** [review]
@ares This needs a rebase now
@iNecas I 👎 ed it because I never thought that was bad UX and was intuitive, but I prefer to just trust @Rohoover with these matters so if it's 👍 ed by her, merge at will

**Comment by iNecas** [comment]
The branch has conflicts, will merge after rebase

**Comment by ares** [comment]
@iNecas rebased

**Comment by iNecas** [comment]
[test foreman] as we have the tests green now

**Comment by iNecas** [comment]
[test foreman]

**Comment by ares** [comment]
rebased, that should help with failures

**Comment by iNecas** [comment]
Thanks @ares

**Pull request merged**
