### PR TITLE
Fixes #12280 - fix label for field helper

### PR DESCRIPTION
**Pull request by ares**
Please see [redmine](http://projects.theforeman.org/issues/12280) issue for more details

### CODE REVIEW

**Comment by shlomizadok** [comment]
:+1: works well. need to fix rubocop and good to merge :)

**Comment by ares** [comment]
Rubocop is happy now.

**Comment by domcleal** [comment]
I can't see where this bug shows up, am I looking in the right place?

screenshot from 2015-10-29 11-36-16

(that's on develop)

**Comment by ares** [comment]
No, sorry I should have described it better. Go to existing role filters and try create new or edit existing filter. See `demo1` label on screenshot
roles

**Comment by domcleal** [comment]
Ah, I see.  Thanks!

**Comment by domcleal** [comment]
Merged as f72212f, thanks @ares.

**Pull request closed without merging**
