### PR TITLE
Fixes #8043 - Statistic links to OS

### PR DESCRIPTION
**Pull request by dLobatog**
Click on the chart for Operating Systems on /statistics. It'll redirect you to a search on os_description for Hosts.  It should instead search on title to ensure it'll show what the chart shows. The chart itself counts operating systems looking at their title.

### CODE REVIEW

**Comment by boaz0** [comment]
:+1:

**Comment by orrabin** [comment]
@eLobato I tested this and it looks good

**Comment by mmoll** [comment]
tested, works for me :+1:

**Comment by isratrade** [comment]
I was going to merge, but I get `os_title=~VAL~` in the search box why I click on the OS chart. Any ideas why?

**Comment by dLobatog** [comment]
@isratrade I think you might be getting getting cached assets. charts.js changed a bit here https://github.com/theforeman/foreman/commit/357a911123f425055b180f2a224f351e59bc9617

**Comment by ohadlevy** [comment]
merged as a2f0773 thanks @eLobato

**Pull request closed without merging**
