### PR TITLE
Fixes #25542 - Storybook style fixes

### PR DESCRIPTION
**Pull request by tstrachota**
- adds a wrapper component `Story` that ensures all stories have consistent spacing
- replaces dependecies loaded from cloudflare with correct configuration for webpack loaders
- moves components that are not intended for reuse into a section "Page chunks"

### CODE REVIEW

**Comment by tstrachota** [comment]
Deployed for testing here:
https://tstrachota.github.io/foreman/

I had some troubles with js reaching out of memory when I was building the storybook. Could someone try if you experience the same or if it's just my setup?

**Comment by tstrachota** [comment]
Rebased

**Review by waldenraines — APPROVED** [review]
LGTM.

**Review by mmoll — APPROVED** [review]
looks much better, indeed :+1:

**Comment by mmoll** [comment]
merged, díky @tstrachota!

**Pull request merged**
