### PR TITLE
smart proxy features are now being defined/loaded dynamically

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by domcleal** [comment]
Got redmine? :)

I wonder if it needs to be more dynamic - not just at class load (i.e. a method)?  e.g. you couldn't use it within a migration that has just added the Feature object?

**Comment by dmitri-d** [comment]
redmine: http://projects.theforeman.org/issues/3622

@domcleal: One way to achieve what you suggest would be to revert back from a constant to a method -- @ohadlevy you ok with that (since it was your change).

**Comment by skottler** [comment]
@witlessbird can you add the redmine issue ID to the commit?

**Comment by dmitri-d** [comment]
@skottler: done & done

**Comment by domcleal** [comment]
Let's do this as-is.  Merged as c6723506 for Foreman 1.4, thanks @witlessbird.

**Comment by dmitri-d** [comment]
ty, pretty trivial to convert that from a constant to a method if/when we need to.

**Pull request closed without merging**
