### PR TITLE
Fixes #23222 - enable switcher on puppet classes page

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Review by dLobatog — APPROVED** [review]
This seems to work, I'll merge if tests pass. 

Thanks @amirfefer !

**Comment by amirfefer** [comment]
[test upgrade]

**Comment by amirfefer** [comment]
[test foreman]

**Comment by dLobatog** [comment]
Failures seem unrelated (`Exception when executing the batch command : no workspace from node hudson.slaves.DumbSlave[slave06.rackspace.theforeman.org] which is computer hudson.slaves.SlaveComputer@3c208c86 and has channel null `,

Thanks @amirfefer!

**Pull request merged**
