### PR TITLE
fixes #2314 - more choices in memory drop down

### PR DESCRIPTION
**Pull request by rbirnie**
It would be nice to have more granular choices in memory as well as more choices on the high end.

### CODE REVIEW

**Comment by domcleal** [comment]
I'm happy to merge this, but am wondering if there's a slider + text box type control we can use - @abenari?

**Comment by abenari** [comment]
I would use something like:
http://www.jqueryscript.net/demo/Touch-Friendly-jQuery-Input-Spinner-Plugin-For-Bootstrap-3-TouchSpin/
because it's functional and not too fancy.

One issue with this input component is that it doesn't have the logarithmic scale that we use in this case. The other issue is that if we replace the select with text input we will need review the validator too.

**Comment by rbirnie** [comment]
So we'd just do a step of 512 or 1024 I believe?  It might be nice to have it take a MB or GB ending and compute the correct value based on that.

**Comment by domcleal** [comment]
I'd have suggested we could get away with a hardcoded GB suffix, but it doesn't seem to do decimal points (maybe a config option) so getting lower than 1GB would be tricky.  It'd be nice not to display it in MB for large values.

Perhaps we could emulate the disk option and use a plain text box which would let users enter in any units they like, then have buttons or a dropdown for common values on the right, instead of trying to find and use a slider widget?

**Comment by sodabrew** [comment]
A slider could be nice here: http://www.eyecon.ro/bootstrap-slider/

**Comment by domcleal** [comment]
Merged as f7d5a22 for Foreman 1.4.1, thanks @rbirnie.  I've left the ticket open as I'd like a more free form solution still.

**Pull request closed without merging**
