### PR TITLE
Refs #15806 - add eslint also to travis tests

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]

**Comment by ohadlevy** [comment]
thanks @mmoll do you have an example of linting failure on travis? (I assume it marks the test as fail)

**Comment by mmoll** [comment]
> do you have an example of linting failure on travis?

good point, I removed the "exit 0" from the lint job.

See GH-6024

**Review by amirfefer — APPROVED** [review]
Thanks @mmoll ! :+1: 
this improves some reliability for js linting

**Review by ekohl — APPROVED** [review]
Test failures appear to be unrelated

**Review by ohadlevy — APPROVED** [review]
test failures not related - thanks!

**Pull request merged**
