### PR TITLE
fixes #7898 - ensure that format can respond to json / yaml

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
Line 104 too.

However isn't the fact that Rails is interpreting the resource name as a format an issue too?  Should dots be removed from the resource names, or something?

**Comment by shlomizadok** [comment]
Added on line 104 too.
It is very weird.... FriendlyId is supposed to handle the name <-> param / param <-> name -- yet it fails to do so on auth_source_ldap.
Seems that auth_source_ldap is the only place it fails.
cc @isratrade

**Comment by dLobatog** [comment]
@shlomizadok Works well, could you add a test to ensure we don't get regressions in the future? I'm not sure whether dots should be removed from the name if we can get around it as easily as this.

**Comment by shlomizadok** [comment]
Tested locally, it seems that unknown formats (e.g., ".weird") are treated as html -- and this seems to be a normal Rails behavior. Checked on external Rails sites 
(See: http://railscasts.com/episodes/417-foundation.json, http://railscasts.com/episodes/417-foundation and http://railscasts.com/episodes/417-foundation.weird)

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/f4cecb481293915fbd0241080aa70f7e0ed1b1d3 , thanks for the fix @shlomizadok!

**Pull request closed without merging**
