### PR TITLE
Fixes #19765 - Disable Layout/AlignHash cop 

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Do you want this PR get merged and thus this cop enabled? React :+1:
Do you want this cop enabled, but rather [with `key` (the default)](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/AlignHash)? React :laughing:
Do you want this cop enabled, but rather [with `separator`](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/AlignHash)? React :tada:
Do you want this cop to be disabled? React :-1:

**Comment by ares** [comment]
This would make me very unhappy, I don't want to change the alignment of multiple lines when I add longer key, this has impact on reviewing PRs as one line changes looks as multiple line changes. Ruby is not Puppet.

**Comment by tbrisker** [comment]
Looks like disabling it is, can you pleas update the PR @mmoll ?

**Comment by mmoll** [comment]
sure, updated

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
