### PR TITLE
Sync community templates

### PR DESCRIPTION
**Pull request by ares**
since we sync fixes in 1.15 it's probably good time to sync it for develop too

### CODE REVIEW

**Review by dLobatog — APPROVED** [review]
We normally sync on every major release, so this would come just before setting version to 1.17-develop.
 
@ares If you want to, feel free to commit the output of `script/sync_templates.sh` directly to develop, it's already been reviewed on community-templates.

**Comment by ares** [comment]
I think we did the sync whenever someone asked in the past. I can push directly if you want, but this ensures tests passes. Tests in community templates repo are quite limited.

**Review by dLobatog — CHANGES_REQUESTED** [review]
@ares Since you set http://projects.theforeman.org/issues/19998#change-89318 as Ready for Testing and as a Bug with a Release number, please change the commit & title so the issue is automatically closed when this PR is merged.

Thanks!

**Comment by ares** [comment]
As I descried in the [redmine](http://projects.theforeman.org/issues/19998#note-7) I didn't want to link the PR to the issue since it contains also unrelated changes. This would make it unclear if we need to cherry-pick this later. Redmine issue contains all necessary information, I'd prefer to close it manually once this is in.

If you insist I'll link it though.

**Comment by ares** [comment]
Removing WoC to get attention for my last comment.

**Comment by dLobatog** [comment]
Thanks @ares , close the Redmine manually please

**Comment by ares** [comment]
Thanks, done.

**Pull request merged**
