### PR TITLE
Fixes #21857 - don't use ES6 syntax in Rails JS asset

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
Thanks @mmoll!

**Comment by jovandeginste** [comment]
Thanks @mmoll - just ran into this :-/

**Comment by mmoll** [comment]
@jovandeginste into what exactly?

**Comment by jovandeginste** [comment]
@mmoll I was trying to build our Foreman Docker image with branch 1.16.0, and the step `apipie:cache` gave the above error. Your patch solves this (cherry-picked in 1.16.0)

**Comment by mmoll** [comment]
Ah,  I see, we should get out a 1.16.1 out soonish, I guess...

**Comment by jovandeginste** [comment]
@mmoll of course :-) but I'd rather have a stable release than a rushed-out release ...

**Pull request merged**
