### PR TITLE
Fixes #31747 - host checkin report fix

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Review by ofedoren — APPROVED** [review]
Thanks, @ranjan. Although I couldn't reproduce it (tried both true/false for `include unknown`, different output formats), but still it's better to call `report_headers` just once instead of calling for each host again and again.

The only way it can fail with such an error is if `order` option of `report_render` contains more fields then `report_headers`...

**Comment by ranjan** [comment]
@ofedoren , I tried to reproduce this issue again, the report will fail if there is no host in the organization.  since report_headers is not initialized when hosts are blank. it fails during the sorting. 
Here is an error trace
[Foreman::Renderer::Errors::UnknownReportColumn]: Rendering failed, one or more unknown columns specified for ordering - "Last Checkin"):
 /usr/share/foreman/lib/foreman/renderer/scope/report.rb:74:in `apply_order!'
 /usr/share/foreman/lib/foreman/renderer/scope/report.rb:27:in `report_render'
 /opt/theforeman/tfm/root/usr/share/gems/gems/safemode-1.3.6/lib/safemode/scope.rb:37:in `method_missing'
 Host - Last Checkin:66:in `bind'

**Review by ares — APPROVED** [review]
Thanks @ranjan and @ofedoren, merging!

**Comment by ezr-ondrej** [comment]
CP 2.4: #8306

**Comment by tbrisker** [comment]
2.4 - b68dc53e2

**Pull request merged**
