### PR TITLE
Fixes #2298: users no longer can access enitites in any organization/location when their current organization/location is not set

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
A note: Entities NOT associated with any Organization/Location are accessible to anyone. I'm not sure how desirable this is in multi-tenant environments.

And another: ATM, if an Organization and/or a Location is selected, all queries will be restricted to this Location/Organization exactly (as in no other taxonomies or non-associated entities). I think non-associated entities should be returned with those.

**Comment by domcleal** [comment]
I'm not quite sure what to say to this PR, tbh.  My immediate reaction is that it's risky, as we're touching a huge number of tests which have been individually reviewed inline with the feature or bug that they were added to cover, so I'm very concerned about reducing the quality of test coverage without going through every one painstakingly (I'm aware it took you a while).

What was the reason to touch so many tests?

(@isratrade, your thoughts would be very welcome too)

**Comment by isratrade** [comment]
@domcleal, @witlessbird, it seems that there are two separate things in this PR:
1) taxonomy functionality changes
2) re-factoring / DRY tests - (i.e. removing as_user :one) without any connection to taxonomy 

I would split these out into two PR's

Regarding your points on taxonomy, it touches on whether to have a default org/loc for every entity once locs/orgs are enabled.  If I remember correctly, we decided against this, but we can re-address it. I think the current implementation of with_taxonomy_scope works as designed to for "all queries to be restricted to this Location/Organization exactly"

**Comment by dmitri-d** [comment]
I didn't reduce the test coverage (no tests were removed), but I changed quite a few tests because:
- a lot of them started failing once the behaviour "no current organization/location == all organizations/locations" was removed
- a whole other bunch started failing once organization/location was being initialized (and carried between tests, as it's stored in thread-local variable)

At some point it became clear to me that (pls. keep in mind I tried to keep changes at a minimum) updating test data/test setups/etc is more appropriate than trying to fiddle with individual tests.

**Comment by ares** [comment]
Would assigning of all taxonomies to user(:one) help to keep original behaviour similar? In such case it should work as "Any org/location" before the patch. Obvious disadvantage would be to assign any new org or location fixture.

**Comment by ares** [comment]
Also we should consider another way of fixing, as @isratrade says, it's expected to select just one  Location/Organization exactly. Your solution would make granular permission system much more complex because you can have filters that would apply to just some of selected taxonomies. I'd vote for enforcing first taxonomy if user haven't choose any specific.

**Comment by dmitri-d** [comment]
re: tests -- I did refactor tests, but only after making too many changes to make them pass with the changes in the code. It can be done as a separate commit, but I'm not convinced it's worth it.

It is also possible (and I think it is useful) to have entities not associated with any location at all something we should support.

**Comment by ares** [comment]
> It is also possible (and I think it is useful) to have entities not associated with any location at all something we should support.

Yes but here it's more about whether user can see entities not associated with any taxonomy if he is assigned to some specific. And even though I can see benefit of seeing entities from more locations I still think user should decide under in which context he currently works. It can become confusing listing entities from more locations at the same time when some links are displayed only for some entities. Not speaking about bigger complexity itself.

**Comment by dmitri-d** [comment]
I think that depends on the interpretation: to me no location/organization == available in all locations/organizations, which means the entity should appear in all locations/organizations.

**Comment by ares** [comment]
Could be. But that does not change the fact that the user should select in which context he works. E.g. in location A he should see all entities from location A and (by your understanding) all entities without location set. What I'm trying to say is when user is limited to 2 locations he should choose in which he currently works. When you allow him to select "any" which means both he'll end up in situation described in previous comments. Maybe this should be discussed with more devs using mailing list, especially with those who worked on this concept.

**Comment by thomasmckay** [comment]
I'm not sure I agree that "no org/loc" equates to "show in every org/loc"; is that what is being suggested?

Also, is there really no access control on entities not belonging to an org/loc?

@mccun934 @bkearney @ohadlevy - where is the product requirement doc driving this?

**Comment by isratrade** [comment]
@witlessbird, can you rebase and resolve the merge conflicts?

**Comment by dmitri-d** [comment]
I don't think this is relevant any longer. Closing the PR.

**Pull request closed without merging**
