### PR TITLE
fixes #18216 - volume size editable for existing VMs one

### PR DESCRIPTION
**Pull request by TheKangaroo**
This PR implements feature #18216

### CODE REVIEW

**Comment by timogoebel** [comment]
@theforeman-bot : ok to test

**Comment by TheKangaroo** [comment]
I updated the PR.
Thanks for your support @timogoebel  :)

**Review by timogoebel — APPROVED** [review]
@TheKangaroo : Thanks, works nicely. I'll merge when ci-tests pass.

**Comment by timogoebel** [comment]
@TheKangaroo : Some tests are failing. Could you please take a look?

**Comment by TheKangaroo** [comment]
Hi @timogoebel, I checked the tests. They should pass now.

**Comment by timogoebel** [comment]
Merged, thanks @TheKangaroo.

**Pull request merged**
