### PR TITLE
Fixes #12057 - enable editing compute attrs for new nics

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by tstrachota** [comment]
[test]

**Comment by dLobatog** [comment]
@tstrachota Good addition, it also gets clearer to read. Mind to add an integration test to make sure this doesn't get removed by accident later on? Thanks!

**Comment by tstrachota** [comment]
@eLobato which reminds me of https://github.com/theforeman/foreman/pull/2115 :neutral_face:
I need to try to fix that one first. I really have no clue what makes it fail time to time.

**Comment by domcleal** [comment]
Marking as WoC as there are merge conflicts.

**Pull request closed without merging**
