### PR TITLE
Fixes #12978 - foreman-debug -m 0 to collect all files

### PR DESCRIPTION
**Pull request by pmoravec**
Replace MAXLINES=0 by MAXLINES=99999999999 to achieve that.

Signed-off-by: Pavel Moravec pmoravec@redhat.com

### CODE REVIEW

**Comment by dLobatog** [comment]
[test] - this will trigger Jenkins to test your PR

**Comment by dLobatog** [comment]
@pmoravec Thanks for the PR. I don't understand why not to simply replace `tail -n` by `cat` when `-m 0` or something similar? It seems more solid to me.

Aside from that , can you add an explanation of what `-m 0` does to help? It's at the beginning of the file.

Thanks!

**Comment by pmoravec** [comment]
@dLobatog Thanks for feedback. I had some minor objections against "cat" but the current implementation is fine for me.

Re "can you add an explanation of what `-m 0` does to help" - you mean add it to `usage()`? Added it there.

**Comment by lzap** [comment]
Feel free to increase the 5000 default to 10 thousand. Won't hurt, I already hit the 5000 limit few times.

**Comment by dLobatog** [comment]
Merged as 51f005e139c09fdd37273ac408dc21a176431cda, thanks @pmoravec!

**Pull request closed without merging**
