### PR TITLE
fixes #18796 - do not use statistics-pie css as its used by flot

### PR DESCRIPTION
**Pull request by ohadlevy**
flot initalization relay on the above css class, using it here makes
legacy flot to try and initalize on the same div as c3.

### CODE REVIEW

**Comment by tbrisker** [comment]
@ohadlevy Appears that one of the js tests broke.

**Comment by gailsteiger** [comment]
The modal charts aren't opening.

Remove `//= require charts` from app/assets/javascripts/application.js line 9 (I thought I did this in the original PR) and add back the `statistics-pie` class

Should solve both problems and the test should pass.

**Comment by ohadlevy** [comment]
@gailsteiger I've updated it according to your suggestions, I do believe this will impact plugins that are using charts (/cc @ares for openscap and rex).

I also think using the same css class that is used by flot is confusing.

**Comment by gailsteiger** [comment]
@ohadlevy I don't care much about the css class. `small` has a different meaning when used without `statistics-pie` but things look OK. If `statistics-pie` is removed the failing test should be fixed. I think charts.js should be removed from application.js. Can't the plugins add charts.js where needed as in core?

charts.js adds an event listener to the window object: 

`$(window).on('resize', refreshCharts);`

We should look to retiring that file.

**Comment by dLobatog** [comment]
Tests still fail, set to WoC

**Comment by gailsteiger** [comment]
@dLobatog the js test mentioned by tbrisker above no longer fails.

@ohadlevy Are the failing foreman tests related to this change? I didn't see any connections.

**Comment by dLobatog** [comment]
@gailsteiger Yes, see http://ci.theforeman.org/job/test_develop_pr_core/12358/#showFailuresLink or how the errors are `ReferenceError: Can't find variable: refreshCharts`

**Comment by gailsteiger** [comment]
@dLobatog Thank you very much for the info.

**Comment by ohadlevy** [comment]
@dLobatog updated missing charts.js, the one place that I was confused about was the host form, on submit, we replace the page content instead of redirecting, basically ignoring the html head sections.

**Comment by gailsteiger** [comment]
OK with me

**Comment by dLobatog** [comment]
Thanks @ohadlevy @gailsteiger

**Pull request merged**
