### PR TITLE
fixes #11175 - [API] Add taxonomies to ptables, display ptables in ta…

### PR DESCRIPTION
**Pull request by shlomizadok**
…xonomies

### CODE REVIEW

**Comment by domcleal** [comment]
Could you also add API param docs please to the controllers?

**Comment by shlomizadok** [comment]
@domcleal no sure we need? as this is only on show, the only param is `:id`

**Comment by domcleal** [comment]
Sorry, I mean the taxonomy controllers - i.e. app/controllers/concerns/api/v2/taxonomies_controller.rb.

**Comment by shlomizadok** [comment]
Hope this is what you meant for

**Comment by domcleal** [comment]
Yep.  Now I look though, there are also two lines about allowed nested IDs in the file, which are missing ptables so should also have ptable_ids added.  I'm not certain which routes they're for, possibly something like /api/v2/locations/Foo/ptables.

**Comment by shlomizadok** [comment]
Added. Thanks

**Comment by domcleal** [comment]
Ah, found which route it was meant to be: /api/v2/ptables/Foo/locations, which is missing from config/routes/api/v2.rb.  Would you mind adding it?

Otherwise looks complete.

**Comment by shlomizadok** [comment]
Added the route.

**Comment by domcleal** [comment]
Merged as d1e6d79, thanks @shlomizadok.

**Pull request closed without merging**
