### PR TITLE
Fixes #19891 - Disable Style/PreferredHashMethods cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
react :+1: for merging and enabling this cop (`.key?`, 71 changes) 
react :laughing: for enabling this cop, but with the "verbose" style (`.has_key?`, 122 changes)
react :-1: for disabling this cop, allowing both styles

**Comment by mmoll** [comment]
rebased, more votes, please :)

**Comment by lzap** [comment]
Stalemate, looks like we keep it as is :)

**Comment by ekohl** [comment]
Should we allow both because of the stale mate?

**Comment by lzap** [comment]
I'd definitely prefer that.

**Comment by mmoll** [comment]
:ok: disabled this cop

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
Thanks!

**Pull request merged**
