### PR TITLE
Refs #31060 - Move environment cleanup to rake task

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I've left it's creation in the migrations, so we should remove it there as well in this case.

**Comment by tbrisker** [comment]
> I've left it's creation in the migrations, so we should remove it there as well in this case.

Are you sure?
https://github.com/theforeman/foreman/pull/8790/files#diff-4c5ebd3a3cf69ada60a90fd7f797de5a6882379c5aebed9df1572816e6fad811L48
https://github.com/theforeman/foreman/pull/8790/files#diff-299ad570d5312f3b57bfd4808d6f3cfb187c864e653d1766a05ceb271b30c2e5L3
https://github.com/theforeman/foreman/pull/8790/files#diff-e893d3c064ea98da22d70c1c1767eb491e9338c07789dd9981affdd0f6e2ad51L27
https://github.com/theforeman/foreman/pull/8790/files#diff-e893d3c064ea98da22d70c1c1767eb491e9338c07789dd9981affdd0f6e2ad51L37

**Review by ezr-ondrej — APPROVED** [review]
I'm very confused already it seems, glad you caught this. :+1: 
Thanks @tbrisker !

**Comment by ezr-ondrej** [comment]
Hmm @tbrisker so who should take care of cleaning up this column? It is causing some issues when the migration to the plugin is done, but removing it in the plugin seems just wrong. Now I'm buffled.

Why this is needed: https://community.theforeman.org/t/removing-puppet-environment-fails/26125/4

**Comment by tbrisker** [comment]
that's a fair point. I think the right thing then is to only remove the foreign key constraint in core, and leave the column. even though theoretically you might have someone deleting an environment before migration to the plugin, that would be fairly rare.

**Pull request merged**
