### PR TITLE
fixes #3999 - refactor DRY implementation of "nested label" for objects with ancestry

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
I will rebase PR #1105 and #1155 on this PR, so this will be merged first.

**Comment by isratrade** [comment]
re-committed, taking code from PR #1105 and #1155 and moving here, so the commits are cleaner

**Comment by isratrade** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @isratrade, merged as 7ff50dd for Foreman 1.5.  Go ahead and rebase.

**Pull request closed without merging**
