### PR TITLE
fixes #6044 - production.log should have timestamps in it

### PR DESCRIPTION
**Pull request by opuk**
This will add timestamps and severity to production.log or whatever is the current environment.

Example log:
2015-02-25 11:31:14 +0100 (INFO)   Rendered home/_user_dropdown.html.erb (1.7ms)
2015-02-25 11:31:14 +0100 (DEBUG)   CACHE (0.0ms)  SELECT COUNT(_) FROM "taxonomies" WHERE "taxonomies"."type" IN ('Organization')
2015-02-25 11:31:14 +0100 (DEBUG)   CACHE (0.0ms)  SELECT "taxonomies"._ FROM "taxonomies" WHERE "taxonomies"."type" IN ('Organization') ORDER BY title
2015-02-25 11:31:14 +0100 (INFO)   Rendered home/_organization_dropdown.html.erb (6.8ms)

### CODE REVIEW

**Comment by dLobatog** [comment]
[test] @opuk I think we want to move production.log to `journalctl` or similar in the future, but this is helpful until then.

**Comment by ares** [comment]
Could we maybe add some thread id as well? This won't help with multiple threads mixing the logs issue. Also I think that log level would be better in square brackets `[]` as there are already a lot of round brackets `()` in debug log.

**Comment by opuk** [comment]
@ares Agreed, brackets makes more sense.

**Comment by lzap** [comment]
Let's change the date/time/gmt to some shorter format as well? `YY-MM-DD HH:MM:SS`

**Comment by lzap** [comment]
I'd appreciate one-letter shortcuts instead: `(D) (E) (I) (W)` - the shorter it can be the better (more space for actual messages)

**Comment by ohadlevy** [comment]
@lzap does it make sense to make it configurable ?

**Comment by ares** [comment]
So before this gets too complicated, we could take the complex logging mechanism from "katello":https://github.com/Katello/katello/blob/master/lib/katello/logging.rb which is extremely configurable and has everything one might want, but until we grab it this small enhancement could be used (without making it more complex). The only thing I'd like to see as an addition is the thread identifier since mixed logs can be serious issue in production.

**Comment by lzap** [comment]
> @lzap does it make sense to make it configurable ?

I'd just prefer shorter default value, configurable does not give me
anything. I hope for systemd-journld only in future :-)

## 

Later,
 Lukas #lzap Zapletal

**Comment by dLobatog** [comment]
[test] , please change the labels if you've reviewed this

**Comment by lzap** [comment]
Can you squash it into one commit? This is too much for six lines. :-) Tested, :+1:

**Comment by opuk** [comment]
Hopefully that should do it.

**Comment by ares** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as 70a602462261f6e9404c408e296618997c1e7ba5, thanks @opuk 

This is a nice 'hack', however just so you know (maybe you want to work on it), some people have asked about integrating the Foreman log in journalctl, or like @ares mentioned above, we could consider moving Katello logging here if it makes sense.

**Comment by lzap** [comment]
Yes, we track the request but since we still support CentOS6/RHEL6 and similar, we will likely use this for some time :-) Thanks.

**Pull request closed without merging**
