### PR TITLE
Fixes #26854 - disable Turbolinks for 3rd-party Routing

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by ohadlevy** [comment]
where does this actually use the turbolinks setting? e.g. won't it fail on https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/routes/index.js#L31

**Comment by glekner** [comment]
> where does this actually use the turbolinks setting? e.g. won't it fail on https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/routes/index.js#L31

Layout pushes to the history state based on the `useTurbolinks` created in the `LayoutSelectors`
https://github.com/theforeman/foreman/pull/6790/files#diff-843af54cc0dae12eaa3db8a6b8dd3daaR88

**Comment by johnpmitsch** [comment]
@glekner what do plugins need to update with this change?

**Comment by ohadlevy** [comment]
> @glekner what do plugins need to update with this change?

@johnpmitsch I dont think anything is needed, its already in katello's code base. please try this out and let us know if it solves the issue?

**Comment by johnpmitsch** [comment]
@ohadlevy thanks, will do!

**Comment by glekner** [comment]
@johnpmitsch these changes still push the new route to the history stack, can you check that its not pushed twice by the 3rd party router?

**Comment by johnpmitsch** [comment]
@glekner The error did disappear when moving between angular pages. However, I do see an issue when moving from a React page (e.g. subscriptions) to an angular page (e.g. products). The page won't actually switch and will stay on the previous page. I also see this when switching from a Foreman page as well (e.g. Architectures) to an angular page.

Maybe @waldenraines could confirm that its not just my environment, but it seems like the routing isn't working to the third-party (angular) pages when coming from a Foreman or React page. Angular page to angular page does work fine though.

Let me know if you need any more info!

**Comment by glekner** [comment]
`preventHref` is now based on turbolinks. should fix the issue @johnpmitsch

**Review by johnpmitsch — APPROVED** [review]
I'm not familiar with this area of code, but all the transitions I've tested in katello are now working! :)

**Review by ohadlevy — APPROVED** [review]

**Comment by waldenraines** [comment]
> Maybe @waldenraines could confirm that its not just my environment, but it seems like the routing isn't working to the third-party (angular) pages when coming from a Foreman or React page. Angular page to angular page does work fine though.

Sorry I didn't get to this yesterday but, yes it fixes the problem for me :)

**Pull request merged**
