### PR TITLE
Fixes #12043 - introduces interface for background support of importers

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
Here's a PR that can help understanding why this is needed - https://github.com/theforeman/foreman-tasks/pull/145

Foreman chef already implements this interface https://github.com/theforeman/foreman_chef/blob/master/app/models/foreman_chef/fact_importer.rb#L13 as well as foreman salt https://github.com/theforeman/foreman_salt/blob/master/app/services/foreman_salt/fact_importer.rb#L7

**Comment by dLobatog** [comment]
@ares Can't foreman-tasks modify FactImporter to add this method? I can see why it's needed, but on a Foreman installation without foreman-tasks this code won't be called anywhere.

**Comment by ares** [comment]
It could be added or it could even check it using `.respond_to?(...` but (my) long-term plan is having Puppet just another cfgmgmt system and Foreman being an interface provider. The same argument would applyt to other methods, e.g. registering custom importers, parsers, states etc, are not called in core without specific plugin.

Another reason is that there are (or certainly were) users using [foreman_background](https://github.com/ohadlevy/foreman-background) that could find this useful as well.

**Comment by lzap** [comment]
So by default there should be no change (e.g. on discovery).

**Comment by ares** [comment]
@lzap yes, this change does not actually change anything, just adds a method that we can rely on being present

**Comment by domcleal** [comment]
Fine by me, but please just add a test to check it works so we don't break it.

**Comment by domcleal** [comment]
Merged as 0f6d25a, thanks @ares.

**Pull request closed without merging**
