### PR TITLE
Fixes #25889 - Remove the limit from compute resource password

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
LGTM

**Comment by chris1984** [comment]
@timogoebel This would be good to have

**Comment by timogoebel** [comment]
Ok, so this only applies to sqlite and mysql?

**Comment by chris1984** [comment]
@timogoebel yeah just sqlite and mysql. It looks like this has already been changed in Postgresql here

https://github.com/theforeman/foreman/blob/develop/db/migrate/20130813105054_change_compute_resource_password_to_text.rb

**Review by timogoebel — APPROVED** [review]
LGTM.

**Comment by timogoebel** [comment]
Thanks, @shiramax.

**Pull request merged**
