### PR TITLE
fixes #10997 - update fog to 1.33.0

### PR DESCRIPTION
**Pull request by domcleal**
Most changes appear to be around OpenStack, so it would perhaps be useful to check that's still working.

### CODE REVIEW

**Comment by dLobatog** [comment]
Unfortunately this seems to break Openstack indeed. It's working on develop, here any request I've tested will make Excon throw an exception `: Expected([200, 204]) <=> Actual(300 Multiple Choices)`. I found that error on https://github.com/theforeman/foreman/pull/2529 and it was fixed by passing the URL to the identity server as another parameter. This doesn't feel like a minor version update if it breaks the API...? 

I'll dig deeper unless you know of some workaround we could use.

**Comment by domcleal** [comment]
Seems that https://github.com/fog/fog/commit/6ecc87496b0f3bdb71fbd7c90cb8e4945dadd432#diff-3aa267766daa7f21447cd3c77b43bf39L74 broke it, since it no longer copies "openstack_identity_endpoint" to `@openstack_identity_public_endpoint`.  We can change the OpenStack model to pass in "openstack_identity_public_endpoint" instead though Fog then issues a warning that this isn't a known property - it does work though!

I'll keep digging.  And indeed, these little niggles are why I think it should remain pinned to this extent.

**Comment by domcleal** [comment]
Reported over at https://github.com/fog/fog/issues/3662#issuecomment-131744252 on a ticket that also describes the issue you hit in #2529.  I've left both as it's likely this workaround should be reverted in future.

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as 3defe0ca12cd6f2ab787faa21d1a9db01d6b0ca1, thanks @domcleal!

**Pull request closed without merging**
