### PR TITLE
3.0 cherry picks

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Cherry picks for 3.0.1

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]

**Comment by evgeni** [comment]
3.0 GA was tagged already: https://github.com/theforeman/foreman/releases/tag/3.0.0

**Comment by upadhyeammit** [comment]
The 3.0 already tagged, so we will get these in 3.0.1

**Comment by ekohl** [comment]
@ares could you weigh in on what should be picked given that it's already been tagged? I'm mostly wondering about the report.

**Comment by ezr-ondrej** [comment]
I'll split the report template then, others are good to go to 3.0.1 anyway IMHO

**Pull request merged**
