### PR TITLE
Fixes #34122 - Report disallowed metric labels as other

### PR DESCRIPTION
**Pull request by lzap**
(cherry picked from commit a26eb29)

Backport of: https://github.com/theforeman/foreman/pull/8985

### CODE REVIEW

**Comment by lzap** [comment]
DO NOT MERGE

**Comment by ekohl** [comment]
> DO NOT MERGE

GH has a "convert to draft" which prevents merging. I've done that now, but please use it in the future to indicate this.

**Comment by lzap** [comment]
So I had a ton of merging conflicts due to renaming of files that Leos implemented, the safest is to backport all the three commits as they were commited into master.

**Comment by ezr-ondrej** [comment]
> the safest is to backport all the three commits as they were commited into master.

I'm not loving it, but I'm content with that, there should not be any harm (just that it seems in the log, that RM#33968 is fixed by this), wich is not. I'll fix that manually.

**Pull request merged**
