### PR TITLE
Fixes #32397 - changed button type to submit

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Do we know what was the issue?

The `return false` does not work for the button or the enter key event did not get caught by the button?

**Comment by adiabramovitch** [comment]
@ezr-ondrej 
The problem was when pressing on the Enter button the Entire Host was submitted and not the Inteface. 
"If interface modal (in edit host menu) is confirmed with enter, enter confirms host update instead of new interface, this action cause another misbehavior" , I guess this was the problem "enter key event did not get caught by the button" but I haven't checked

**Comment by tbrisker** [comment]
I didn't manage to reproduce the original issue locally, but when testing this change manually on a reproducer machine it seems to fix the issue properly.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adiabramovitch and @tbrisker for testing.

**Comment by ezr-ondrej** [comment]
CP 2.5: #8590

**Pull request merged**
