### PR TITLE
Fixes #34542 - Add ouiaId for easier testing

### PR DESCRIPTION
**Pull request by Ron-Lavi**
This commit adds OUIA ID in the confirm modal.
More about the Open UI Automation: https://www.patternfly.org/v4/developer-resources/open-ui-automation/

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
Thanks, @Ron-Lavi! 
Could you please add a comment that this is a temp workaround?  OUIA is a black box from the development perspective, and it should generate the `ouia-id` automatically. in most cases, it shouldn't be hard coded.

**Comment by Ron-Lavi** [comment]
let's wait with this PR until we discuss this deeply with Patternfly next week?

**Comment by Ron-Lavi** [comment]
@amirfefer any new thoughts about this one?

**Comment by jeremylenz** [comment]
I raised our concerns around OUIA-ID with Patternfly. 
Confirmed that when QE needs a static ID, adding the `ouiaId` prop is the correct way to make it static.
If we have specific cases where something is not as expected, we should bring up PF issues.

**Comment by MariaAga** [comment]
@Ron-Lavi Can you rebase to maybe fix the tests and change the commit message so it would specify that this is only a fix for the ConfirmModal?

**Comment by Ron-Lavi** [comment]
Updated, thanks :)

**Review by MariaAga — APPROVED** [review]
Thanks!

**Pull request merged**
