### PR TITLE
Fixes #27334 - Remove hardcoded max values for ovirt

### PR DESCRIPTION
**Pull request by bagasse**
As discussed in #6852, remove hardcoded max values for ovirt instead of updating these values.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
LGTM and based on discussion it is what was agreed upon.
Could you just ACK @shiramax I understood the results well and we want this?

**Review by ezr-ondrej — APPROVED** [review]
LGTM, will wailt for @shiramax or @orrabin to ACK, though.

**Review by shiramax — APPROVED** [review]
thanks @bagasse, looks good to me

**Comment by ezr-ondrej** [comment]
Sound like I understood correctly :)
Thanks @bagasse, merging!

**Comment by ezr-ondrej** [comment]
And thanks @shiramax for confirmation ;)

**Pull request merged**
