### PR TITLE
Bump sidekiq to at least 6.5

### PR DESCRIPTION
**Pull request by ehelms**
Picking up some fixes including one CVE -- https://github.com/sidekiq/sidekiq/blob/v6.5.11/Changes.md

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
With my "packaging" and "keep shit uptodate" hats, I'm happy. And the changelog doesn't read too crazy.

But I'd love to also hear @adamruzicka's ACK here.

**Comment by adamruzicka** [comment]
I'll take this for a spin on monday to be sure

**Comment by ehelms** [comment]
> I'll take this for a spin on monday to be sure

Great, let me know what you find.

**Review by adamruzicka — APPROVED** [review]
Seems to work just fine

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
(added a redmine)

**Pull request merged**
