### PR TITLE
Fixes #9878 - refresh external usergroup on API manipulation

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares Thanks for the patch! Isn't the original issue referring to deleting an external user group in the UI? https://github.com/theforeman/foreman/blob/develop/app/controllers/usergroups_controller.rb#L4 misses `:destroy` I think that's the whole bug, however the API catch is pretty good too!

So to summarize, I think this is ready to go after homogenizing the api/v2 behaviour and the UI controller, and writing some tests to ensure it works (particularly the delete case which prompted the bug report).

Thanks again @ares !

**Comment by ares** [comment]
@eLobato thanks for looking into this quickly

from the issue report

```
How reproducible:
deleting an external AD User-group from the CLI and checking the User-Group,  it appears the users are still associated under the User-group.
```

Deletion in UI is a separate issue which I was not aware of, `:destroy` won't help since the refresh is triggered by hostgroup, not external hostgroup. Deletion of external hostgroup equals to update of hostgroup which should trigger refresh already, the thing is probably the fact that after_filter is too late to call refresh.

What exactly do you want me to test here? That the controller calls controller's refresh private method which I have to stub to not perform any external calls?

**Comment by ares** [comment]
FTR, reported the WebUI bug in a separate issue http://projects.theforeman.org/issues/9884, another PR incoming soon.

**Comment by dLobatog** [comment]
Merged as 22d2b02fefc54228631008181c3d0db0b2360d28, thanks @ares !

**Comment by domcleal** [comment]
test_develop is currently failing, I think since this PR was merged.  Please check out this ticket: http://projects.theforeman.org/issues/10123

**Comment by dLobatog** [comment]
@domcleal Yup, git bisect found it too. Merging this and the other external user groups PR in the opposite order would've surfaced this I think. Anyway I'm on it.

**Comment by domcleal** [comment]
Yes or if tests had run on this one more recently, e.g. in a rebase (if they'd conflicted), or PR update.  I was wondering if we can do more to retest PRs in [test-pull-requests](https://github.com/theforeman/test-pull-requests) when develop changes, by retesting one existing pull request an hour or something (like trickle charging) just to ensure it remains green even when the base branch (develop) has changed.

**Pull request closed without merging**
