### PR TITLE
refs #11250 - Remove uniqueness check from network address validator in subnet.rb

### PR DESCRIPTION
**Pull request by lawre**
implements Feature #11250 Remove uniqueness check from network address validator in subnet.rb

This is for redmine project: http://projects.theforeman.org/issues/11250

### CODE REVIEW

**Comment by domcleal** [comment]
[test] will trigger Jenkins.

**Comment by lawre** [comment]
hmm... test passes for everything but Katello.  I tried to trace it back and get to here: http://ci.theforeman.org/job/test_katello_core/database=postgresql,ruby=1.9.3/

There is no indication as to which job failed, so I looked at the one with the same time stamp overlap:
http://ci.theforeman.org/job/test_katello_core/database=postgresql,ruby=1.9.3/14780/

In the console, the failure for this job seems to be with the cleanup:

<pre>
12:45:46 Archiving artifacts
12:45:46 ERROR: No artifacts found that match the file pattern "pkg/*". Configuration error?
12:45:46 ERROR: ‘pkg/*’ doesn’t match anything, but ‘*’ does. Perhaps that’s what you mean?
12:45:46 Build step 'Archive the artifacts' changed build result to FAILURE
</pre>

Please advise with the next step.  Thanks!

**Comment by domcleal** [comment]
Oh, don't worry about that, it's some intermittent failure (http://projects.theforeman.org/issues/11189).

Next step will be a review.  It's on the queue, but I need to have a think about it first :)

**Comment by domcleal** [comment]
Merged as 3bd9a89, thanks @lawre!

**Pull request closed without merging**
