### PR TITLE
Fixes #21086 - revert roadie-rails pinning for Ruby <2.2

### PR DESCRIPTION
**Pull request by mmoll**
This reverts commit 76dd13f7b99c3687629b02383041fbfcda9c969e.

### CODE REVIEW

**Comment by tbrisker** [comment]
ACK, tests are failing on 2.1 (obviously), good to merge once we get rid of 2.1 in core matrix.

**Comment by tbrisker** [comment]
On second thought, I think we need a new issue for this since [#19524](http://projects.theforeman.org/issues/19524) was released in 1.15.1 already.

**Comment by mmoll** [comment]
created an issue :bowtie:

**Comment by tbrisker** [comment]
As an interesting side note - looks like only one of the 2.1 tests fails, the others successfully install roadie-rails 1.2.0 somehow. :man_shrugging:

**Comment by mmoll** [comment]
there's some gem caching via RVM gemsets going on

**Comment by tbrisker** [comment]
[test foreman] just to make sure we're green now and then we'll merge

**Comment by mmoll** [comment]
💚

**Comment by tbrisker** [comment]
Thanks @mmoll !

**Pull request merged**
