### PR TITLE
Refs #8364 - removed javascript N+1 alerts

### PR DESCRIPTION
**Pull request by lzap**
The N+1 is a nifty plugin but these javascript alerts are _killing_ me and will
definitely ruin my today's demo which must be done in 2 minutes and 30 seconds
:-)

I beg for a quick merge. There is still the log and the footer box (which is
quite obvious and big). These are both non-modal but still useful.

### CODE REVIEW

**Comment by dLobatog** [comment]
Sorry but I :-1: , I think the point of Bullet is to make it painfully obvious so you fix the db problems instead of disabling the notices. Speaking for myself, alerts do kind of force me to spend 5 minutes fixing the query so I don't have to see it again :smile: 

I'll leave it open for others to merge if enough people is interested.

**Comment by GregSutcliffe** [comment]
:+1: to merge. It may be 5mins to fix some of them, or for your awesome Rails-skillz @eLobato, but the last time I tried to fix one, I spent an hour I couldn't afford to lose on it.

In any case, popups belong in the 90s. I agree with lzap that the footer contains all the relevant info and is very obvious if you _are_ in the mood to fix it.

I'll not merge until we get another +1, it's 1 vote each right now :)

**Comment by GregSutcliffe** [comment]
Oh, and it's worth remembering that even if you _do_ fix one, until the PR is merged (which can take a while, even for easy stuff) your other branches will still suffer. Unless you're willing to manually rebase ontop of your N+1 branch, but then you're making work for yourself in another place.

**Comment by iNecas** [comment]
At least an environment variable to turn it off would be nice. IMO the alert turned on by default makes perfect sense for case, when there are not N+1 issues and you want to avoid that in future. I would prefer having a dedicated effort to eliminate the known issues first, and then consider turning it on.

**Comment by dLobatog** [comment]
Cool, let's merge this. 3 vs 1 :smile: . I'll try to carve up some time to find all n+1 queries I can find and submit a PR fixing these and enabling it again as Ivan said, since then it won't be so annoying.

**Comment by dLobatog** [comment]
Merged as 287d97450fee16cfec2deaa75d9f1a09576cfdd1, thanks @lzap !

**Pull request closed without merging**
