### PR TITLE
fixes #6501: pin jquery-ui-rails

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by stbenjam** [comment]
This fixes my problem.  :icecream:

**Comment by domcleal** [comment]
If you don't mind me flipping this around, I wonder if we should update to support >= 5.0.0?  The [changelog](https://github.com/joliss/jquery-ui-rails/blob/master/History.md) suggests we might just need to change the paths we try and load:
- Rename jquery.ui._.{js,css} to jquery-ui/_.{js,css}

**Comment by isratrade** [comment]
@mmoll, @domcleal, I think we only need jquery.ui as part of scoped_search's autocomplete. Maybe we should consider manually extracting the needed function and not package all of jquery-ui.

**Comment by domcleal** [comment]
I don't agree, dependencies on other projects reduces our maintenance work and also allows us to follow distribution (Fedora etc) packaging guidelines more closely, as vendoring code is frowned upon.

**Comment by domcleal** [comment]
Thanks @mmoll, merged as dd6a0f3 for Foreman 1.5.2.

**Comment by isratrade** [comment]
@domcleal, I agree with packaging concerns, but a quick look shows 109 .js files in the jquery-ui-rails gem, when we only need one of them `jquery.ui.autocomplete.js`. There's 74 jquery.ui.datepicker files with different locales that are a waste of time to compile in public/assets and load in the DOM upon start-up.

**Comment by domcleal** [comment]
We require only jquery.ui.autocomplete though, so datepicker etc shouldn't ever get compiled into our assets?  In development, I only see: ui.autocomplete, ui.core, ui.menu, ui.position, ui.theme and ui.widget, which I are direct dependencies of autocomplete.

**Comment by isratrade** [comment]
interesting, if I go to `http://localhost:3000/assets/jquery-ui.js` and search for datepicker, I get 284 instances

**Comment by domcleal** [comment]
Sure, the JS is accessible, but doesn't mean it's used in the page render.  app/assets/javascripts/application.\* only require jquery.ui.autocomplete so that's all that the Foreman pages will load.

**Comment by isratrade** [comment]
I see. So, it only affects asset compilation time but not rendering time. Thanks.

**Comment by domcleal** [comment]
I'm not even sure that it'll affect assets compilation, I think Rails will compile application.js which only requires jquery.ui.autocomplete.

**Comment by isratrade** [comment]
Yes, you're right about asset compilation. Does it affect rails startup time or memory footprint, since rails autoloads all gems, right?

**Comment by domcleal** [comment]
Probably to a very small degree as it is another gem to load, but there's very little ruby to evaluate in it as it's 99% assets.

**Pull request closed without merging**
