### PR TITLE
fixes #8638 - ensure that a redirect to hosts index after host destroy

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by TJM** [comment]
Looks good to me. I assume it will have to have full testing from Jenkins land?

Is it possible to "Backport" this to 1.7 since its just a single line change?

Thanks!

**Comment by TJM** [comment]
[test]

**Comment by domcleal** [comment]
@TJM yeah, it'll go into 1.7

**Comment by ohadlevy** [comment]
merged as e29e550 thanks @shlomizadok

**Pull request closed without merging**
