### PR TITLE
Fixes #2199: Fix install media submit/cancel buttons when locations/orgs disabled.

### PR DESCRIPTION
**Pull request by strider**
- When locations and Organizations are disabled, the submit/cancel Buttons are
  not well displayed when you want to add a new medium.

### CODE REVIEW

**Comment by domcleal** [comment]
@strider thanks for the patch!  It tests ok for me and fixes the problem.

We try to keep a history of tickets and associate commits to them.  Would you mind opening one for this?
1. open ticket here to describe the issue: http://projects.theforeman.org/projects/foreman/issues/new
2. amend commit message (`git commit --amend`) to say "fixes #1234 - fix install media submit/cancel buttons when locations/orgs disabled" or similar (the important bit is the prefix)

**Comment by strider** [comment]
@domcleal: is it right for you ?

**Comment by domcleal** [comment]
@strider the branch has ended up with three commits including a merge (see the commits tab in github).  To resolve it, try this:
1. `git reset --hard HEAD~2` to reset the branch back to before your three commits
2. `git cherry-pick 5168d590` to re-apply your good commit to the branch
3. `git push -f origin develop` to push and overwrite the remote develop branch (-f only because they've diverged, it isn't a straight forward update)

If you get stuck, ping me on IRC!

**Comment by strider** [comment]
@domcleal: It seems good now, thanks ;-)

**Comment by domcleal** [comment]
Thanks @strider! 

@ohadlevy :+1:

**Comment by ohadlevy** [comment]
merged - thanks!

**Pull request closed without merging**
