### PR TITLE
Fixes #28542 - Remove smart variables from puppet class form

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by mmoll** [comment]
integration tests fail :broken_heart:

**Comment by tbrisker** [comment]
[test foreman] that's odd, my changes shouldn't affect any pages other than the puppet ones and they seem to be passing locally.

**Comment by mmoll** [comment]
:green_heart: now

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
