### PR TITLE
Fixes #10305 - complete handling for cloudinit-like in vsphere feature

### PR DESCRIPTION
**Pull request by karmab**
add the fix from Francois Herbert (kudos to him ) to actually transform the cloudinit to customisation template in vsphere compute ressource

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
@shlomizadok or @fherbert, could you test this works?  Thanks.

**Comment by fherbert** [comment]
@domcleal I've been using this patch for a while now. Works fine.

**Comment by domcleal** [comment]
Merged as 5d47a16, thanks @fherbert and @karmab!

**Pull request closed without merging**
