### PR TITLE
Fixes #1453 - add use_image and jumpstart helpers to Host jail

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Some other OSes tend to use `@initrd` variables defined by a filter in UnattendedController and inside the TFTP concern.  Should we prefer defining variables instead of directly using `@host` methods from templates?

I can understand moving away from the helper which is only present in the host model for TFTP rendering, but would like to confirm which direction we should adopt as standard in future.

**Comment by ares** [comment]
I would like to limit global variables like @initrd as much as possible. Otherwise we should properly document all available variables and unify the available list for every renderable object we have which seems much more complicated.

**Comment by dLobatog** [comment]
:+1: to @ares idea, will just leave this one as Ready to merge in case someone else disagrees.

**Comment by domcleal** [comment]
Fine by me.  Would you mind adding some unit tests for these host methods, so we don't break them again?

**Comment by ares** [comment]
So I've added test that makes sure host responds to these methods. Should I open a refactoring issue to add tests for methods functionality defined in HostTemplateHelpers? A part of it should be the whole unification and complete coverage, not just testing these 4 methods...

**Comment by domcleal** [comment]
Yes, that'd be good.  Could you rebase too please?

**Comment by ares** [comment]
Opened as http://projects.theforeman.org/issues/11293, PR rebased, sorry it took me a while.

**Comment by domcleal** [comment]
Merged as 6ea461f, thanks @ares.

**Pull request closed without merging**
