### PR TITLE
fixes #27634 - enable running this container on openshift.

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
in order to test PR, you need openshift (such as https://manage.openshift.com/ or your own cluster) and use the deployment script in https://github.com/ohadlevy/foreman-kube (you would probably need to change the reference to the image name as during the PR its built at quay.io/ohadlevy/foreman:docker-openshift)

**Comment by ohadlevy** [comment]
also, its possible to view this instance at http://foreman-foreman.apps.us-east-1.online-starter.openshift.com (with default creds)

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
@iNecas maybe you have a few cycles to review this? thanks.

**Comment by iNecas** [comment]
Some findings:

1. first time the setup pod has run, it failed with:

```
Seeding /home/foreman/db/seeds.d/040-roles.rb
2019-08-19T07:36:03 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:04 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
Seeding /home/foreman/db/seeds.d/050-taxonomies.rb
2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
Seeding /home/foreman/db/seeds.d/060-architectures.rb
rake aborted!
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, 2019-08-19 07:36:07.009213, 2019-08-19 07:36:07.009213).
: INSERT INTO "architectures" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `block (2 levels) in exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:590:in `execute_and_clear'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:117:in `exec_insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:115:in `exec_insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:149:in `insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:187:in `_insert_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:733:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/counter_cache.rb:184:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/locking/optimistic.rb:70:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/attribute_methods/dirty.rb:137:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `block in _create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/timestamp.rb:102:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:704:in `create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:275:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:46:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block in save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:309:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:44:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:36:in `create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:85:in `block in create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:281:in `scoping'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:85:in `create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:104:in `first_or_create'
/home/foreman/db/seeds.d/060-architectures.rb:3:in `block in <top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/audited-4.8.0/lib/audited/auditor.rb:353:in `without_auditing'
/home/foreman/db/seeds.d/060-architectures.rb:2:in `<top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/db/seeds.rb:36:in `block (2 levels) in <top (required)>'
/home/foreman/app/models/concerns/foreman/thread_session.rb:108:in `as'
/home/foreman/app/models/concerns/foreman/thread_session.rb:114:in `as_anonymous_admin'
/home/foreman/db/seeds.rb:35:in `block in <top (required)>'
/home/foreman/db/seeds.rb:29:in `each'
/home/foreman/db/seeds.rb:29:in `<top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/railties-5.2.1/lib/rails/engine.rb:551:in `load_seed'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
/usr/share/gems/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/share/gems/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/home/foreman/bin/bundle:3:in `load'
/home/foreman/bin/bundle:3:in `<main>'

Caused by:
PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, 2019-08-19 07:36:07.009213, 2019-08-19 07:36:07.009213).
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `block (2 levels) in exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_no_cache'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:590:in `execute_and_clear'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:117:in `exec_insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:115:in `exec_insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:149:in `insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:187:in `_insert_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:733:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/counter_cache.rb:184:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/locking/optimistic.rb:70:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/attribute_methods/dirty.rb:137:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `block in _create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/timestamp.rb:102:in `_create_record'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:704:in `create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `create_or_update'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:275:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:46:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block in save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:309:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:44:in `save'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:36:in `create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:85:in `block in create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:281:in `scoping'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:85:in `create'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:104:in `first_or_create'
/home/foreman/db/seeds.d/060-architectures.rb:3:in `block in <top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/audited-4.8.0/lib/audited/auditor.rb:353:in `without_auditing'
/home/foreman/db/seeds.d/060-architectures.rb:2:in `<top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/db/seeds.rb:36:in `block (2 levels) in <top (required)>'
/home/foreman/app/models/concerns/foreman/thread_session.rb:108:in `as'
/home/foreman/app/models/concerns/foreman/thread_session.rb:114:in `as_anonymous_admin'
/home/foreman/db/seeds.rb:35:in `block in <top (required)>'
/home/foreman/db/seeds.rb:29:in `each'
/home/foreman/db/seeds.rb:29:in `<top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/foreman/vendor/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/foreman/vendor/ruby/2.6.0/gems/railties-5.2.1/lib/rails/engine.rb:551:in `load_seed'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/foreman/vendor/ruby/2.6.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/foreman/vendor/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
/usr/share/gems/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/share/gems/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/share/gems/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/home/foreman/bin/bundle:3:in `load'
/home/foreman/bin/bundle:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```
2. readme in the foreman-kube would benefit from describing where to find initial credentials

3. on OCP 4.2, the route was not setup properly (was trying to point to foreman-prod.local, while I would expect the foreman to be available, location pointing to `http://foreman-prod.local` (probably originated by the ingress). When creating a custom route (without ingress), it worked:

```
spec:
  host: foreman-prod
  subdomain: ''
  path: /
  to:
    kind: Service
    name: rails
    weight: 100
  port:
    targetPort: 3000
  wildcardPolicy: None
```

Other than that, foreman started successfully.

Btw. I'm having issues with running `docker-compose up` with `Mysql2::Error::ConnectionError: Unknown MySQL server host 'db' (-2)`, but that's also with master branch.

**Review by iNecas — APPROVED** [review]
I can confirm ability to deploy foreman on openshift using the changes in the dockerfile

**Comment by ekohl** [comment]
Is there any explanation why openshift needs gid 0?

**Comment by ohadlevy** [comment]
> Is there any explanation why openshift needs gid 0?

https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines

**Comment by ohadlevy** [comment]
> Some findings:
> 
> 1. first time the setup pod has run, it failed with:
> 
> ```
> Seeding /home/foreman/db/seeds.d/040-roles.rb
> 2019-08-19T07:36:03 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:04 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:05 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
> Seeding /home/foreman/db/seeds.d/050-taxonomies.rb
> 2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
> 2019-08-19T07:36:06 [W|app|] Scoped order is ignored, it's forced to be batch order.
> Seeding /home/foreman/db/seeds.d/060-architectures.rb
> rake aborted!
> ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint```

not sure why, but its good thing that it keeps on trying :)

regardless, I would move this discussion to the foreman-kube repo vs here?

> 
> 1. readme in the foreman-kube would benefit from describing where to find initial credentials
> 2. on OCP 4.2, the route was not setup properly (was trying to point to foreman-prod.local, while I would expect the foreman to be available, location pointing to `http://foreman-prod.local` (probably originated by the ingress). When creating a custom route (without ingress), it worked:
> 
> ```
> spec:
>   host: foreman-prod
>   subdomain: ''
>   path: /
>   to:
>     kind: Service
>     name: rails
>     weight: 100
>   port:
>     targetPort: 3000
>   wildcardPolicy: None
> ```
> 
> Other than that, foreman started successfully.

ACK I was aware of that, I need to find something that works on kube and openshift at the same time, didn't get to it yet, patches are welcomed :)

> 
> Btw. I'm having issues with running `docker-compose up` with `Mysql2::Error::ConnectionError: Unknown MySQL server host 'db' (-2)`, but that's also with master branch.

interesting, this doesn't happen to me, which version of docker are you running this on? (can be taken to another thread)

**Comment by ohadlevy** [comment]
anything else blocking this PR? thanks.

**Review by ekohl — APPROVED** [review]
> > Is there any explanation why openshift needs gid 0?
> 
> https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines

Thanks. I tried to search for this but couldn't find it.

Since @iNecas approved it and I have no objections I'll merge it.

**Pull request merged**
