### PR TITLE
Do not use string interpolation when composing SQL queries.

### PR DESCRIPTION
**Pull request by martinpovolny**
Do not use string interpolation when composing SQL queries.

Fix some places that seem simple enough.

Work in progress.

Issues: https://projects.theforeman.org/issues/23300

### CODE REVIEW

**Comment by mmoll** [comment]
@martinpovolny thanks for looking to this. :+1:
With Rails 5.2., some messages about this are emmitted, maybe the output in e.g. https://travis-ci.org/mmoll/foreman/jobs/359276702 about "Dangerous query method" used can help to identify some more places.

**Comment by mmoll** [comment]
http://ci.theforeman.org/job/test_brakeman/ also has some things...

**Comment by tbrisker** [comment]
@martinpovolny Thanks, please open an issue in redmine for this.

**Comment by ohadlevy** [comment]
@martinpovolny what is the status of the PR? thanks.

**Comment by ohadlevy** [comment]
[ok to test]

**Comment by mmoll** [comment]
@martinpovolny test failures related, I'd say...

**Comment by mmoll** [comment]
@martinpovolny what's the status here?

**Pull request closed without merging**
