### PR TITLE
fixes #4995 - editing location with 'all users' checked fails on edit page in postgres

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by iNecas** [comment]
:+1:

**Comment by isratrade** [comment]
@domcleal, is this a Jenkins thing?  No idea why using `.map(&:id)` instead of `.pluck(:id)` in `taxonomy.rb` causes a failure in Ruby 1.8.7 on test 'index returns YAML output for rundeck' in hosts_controller_test

**Comment by domcleal** [comment]
@isratrade intermittent test failure, ignore it (http://projects.theforeman.org/issues/4642)

**Comment by isratrade** [comment]
[test]

**Comment by domcleal** [comment]
Merged as 144d6f9 for Foreman 1.4.3, thanks @isratrade.

**Pull request closed without merging**
