### PR TITLE
Fix #3678: use pry as the default REPL in the dev environment

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by lzap** [comment]
+1

**Comment by domcleal** [comment]
While I'm a pry fan too, we do already have wirb+hirb as our default console irb implementations, as per bundler.d/console.rb and config/application.rb.  Using this patch seems to disable hirb's table layout at least.

I've seen somebody (@komidore64?) complain about us forcing this, so would be happy to see something more configurable rather than us trying to dictate which people should use.

**Comment by komidore64** [comment]
yes, i PR'd this in the past (against katello, i believe). I don't think we should enforce it, but :+1: for easily configurable options

**Comment by skottler** [comment]
So we'd use wirb + hirb as the default and have a setting to switch to pry without having to alter the environment?

**Comment by komidore64** [comment]
sounds good to me.

while you're at it, could we get a configurable toggle for wirb+hirb also?

i've had those turned of in my checkout of foreman for a good while now.

**Comment by domcleal** [comment]
I think that makes most sense..

**Comment by skottler** [comment]
Cool, I'll make that change. Probably won't get to it today, but should be able to take care of it tomorrow.

**Comment by domcleal** [comment]
I found by accident that installing pry-rails in your Gemfile.local.rb also does this.

**Comment by domcleal** [comment]
Closing due to no activity.  I'd suggest pry-rails as a workaround for now.

**Pull request closed without merging**
