### PR TITLE
Fixes #34744 - Remove reports deprecation warning

### PR DESCRIPTION
**Pull request by Ron-Lavi**
We won't be able to make the reports change in 3.3.
discourse thread will be updated as well.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I suppose this also should be cherry picked into stable branches that have this deprecation.

**Comment by Ron-Lavi** [comment]
@ekohl yeah I will create a cherry-pick once this is merged

**Comment by Ron-Lavi** [comment]
@MariaAga could you also take a look?
once it's merged I will open a CP to stable branches

**Review by ofedoren — APPROVED** [review]
Thanks, @Ron-Lavi, I see that it's a simple "revert" of https://github.com/theforeman/foreman/pull/8862, so merging.

**Comment by Ron-Lavi** [comment]
Thanks @ofedoren, CP opened in https://github.com/theforeman/foreman/pull/9185

**Comment by ofedoren** [comment]
3.2 CP: https://github.com/theforeman/foreman/pull/9185

**Pull request merged**
