### PR TITLE
fixes #2829 - migration to remove environment field from hosts table

### PR DESCRIPTION
**Pull request by isratrade**
field is not used.

### CODE REVIEW

**Comment by domcleal** [comment]
I don't know the history of this, can you comment @ohadlevy?

**Comment by domcleal** [comment]
ping @ohadlevy

**Comment by ohadlevy** [comment]
the environment was part of puppet schema, I can't see a problem with removing it?

**Comment by domcleal** [comment]
Makes sense @ohadlevy, thanks.

Merged as 23e2e9b, thanks @isratrade!

**Pull request closed without merging**
