### PR TITLE
Generate source with the actual version specified in VERSION

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by tbrisker** [comment]
I'm feeling i'm missing some context here?

**Comment by ehelms** [comment]
When this generates source, it drops the `develop` which I feel is wrong (and complicates RPM packaging as well) given that's in the version string. So this is to ensure that whatever is in VERSION is what the source is generated as. I'd like to make this change to -selinux, -installer and -proxy as well but piloting the change here first.

**Review by ekohl — APPROVED** [review]
I think this makes sense. Given we now print the generated filename we don't need to depend on guessing. The tito custom fechter just downloads `*.tar*` and `*.gem*` and doesn't care about the exact filename.

**Review by mmoll — APPROVED** [review]

**Comment by ekohl** [comment]
@mmoll so Debian nightlies would also understand this?

**Comment by mmoll** [comment]
@ekohl I'm pretty sure there will be adjustments needed for the DEB build, but this change here is fine.

**Comment by ehelms** [comment]
@ekohl or @mmoll care to merge?

There is also:

 * https://github.com/theforeman/smart-proxy/pull/599
 * https://github.com/theforeman/foreman-installer/pull/286
 * https://github.com/theforeman/foreman-selinux/pull/85

**Review by tbrisker — APPROVED** [review]
Ok, seems like everyone agrees. I'll merge them all, please be prepared to fix any breakages in nightlies if this causes something to fail unexpectedly.

**Pull request merged**
