### PR TITLE
Change format validation for user:firstname and user:lastname

### PR DESCRIPTION
**Pull request by xavier-calland**
Allow all except :cntrl: (allow accent, …)

### CODE REVIEW

**Comment by lzap** [comment]
Hello,

we have strict constraints on users for reasons - some plugins like Katello heavily realy on user names because these are handed over to backend systems like Pulp or Candlepin. I don't think we can accept that. Opinions? [test] @ehelms ?

**Comment by xavier-calland** [comment]
In my case, the need is to have accents (é, ô, à, …) in firstname and lastname.

**Comment by thomasmckay** [comment]
@lzap I would have expected that first and last names should support any i18n characters. This would be different than "username" which likely would have more restrictions.

Typically in katello if a backend service has character restrictions a "label" field will be added to the object. This allows the "name" fields to be any characters.

Hope that helps!

**Comment by lzap** [comment]
Oh yeah, sorry I misread the patch. First name and stuff is fine of course, thanks! [test]

**Comment by domcleal** [comment]
A couple of tests are failing around test/unit/user_test.rb:52, could you take a look please?

**Comment by ghost** [comment]
I have just tested this on our test host and it indeed does fix "Invalid Surname" errors for Users not being able to log in, if coming from LDAP and users Name/Surname is containing an UTF8 character.

**Comment by domcleal** [comment]
I've submitted a new PR with tests: #1467

**Pull request closed without merging**
