### PR TITLE
fixes #3671 - 3671-org-audit - added audit to organization

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by isratrade** [comment]
@thomasmckay, `class Taxonomy` is already audited so `class Organization` which inherits from Taxonomy does not need it.

**Comment by thomasmckay** [comment]
Orgs are being audited already; closing and deleted issue.

**Comment by domcleal** [comment]
Just a note for the future, please just flip the status of issues to "rejected" so we still have a record anyway.  Sometimes we find they were actually valid after all :)

**Comment by isratrade** [comment]
@domcleal, good point

**Pull request closed without merging**
