### PR TITLE
Refs #21204 - correct duplicate key in settings fixture

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I guess this happened while rebasing

**Comment by mmoll** [comment]
test failure unrelated :green_heart:

**Review by ekohl — APPROVED** [review]

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Comment by lzap** [comment]
Thanks, I wonder if it has any effect at all.

**Pull request merged**
