### PR TITLE
fixes #4673 - make default sort order descending on count columns

### PR DESCRIPTION
**Pull request by stbenjam**
Scoped Search 2.7.1 now supports default orders.

### CODE REVIEW

**Comment by domcleal** [comment]
Could you update the min version in both the Gemfile and foreman.spec please?

**Comment by stbenjam** [comment]
Sure, done.  I wasn't sure since it's not a hard requirement, older versions will still work.

**Comment by domcleal** [comment]
Ah sorry, I thought it was.  I think I see now, this is just an options hash so it'll be ignored.

**Comment by stbenjam** [comment]
Yup, should I change it back then?

The 2.7.1 RPM is already being built, not sure how the debian side of things works.

**Comment by domcleal** [comment]
Yep, sorry about that!  The EL6 RPM is there but F19 is on 2.6.x (maybe @xsuchy can update it, I've also requested ACLs on the package).  Debian will pick up the latest gem that satisfies the Gemfile.

**Comment by stbenjam** [comment]
No worries, changed it back.

**Comment by domcleal** [comment]
Merged as 846433a for Foreman 1.5.0, thanks @stbenjam!

**Pull request closed without merging**
