### PR TITLE
Fixes #7757 - Fix link_to to call super with proper args

### PR DESCRIPTION
**Pull request by ifarkas**
The original code calls the parent with a single argument: an array of
arguments given to the method. It should call the parent with the
original arguments.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@ifarkas Thanks for your patch! I guess there are not many `link_to` calls that pass a block, since this bug has been in Foreman for 10 months.  

Could you create a Redmine issue as specified in the [guidelines](http://theforeman.org/contribute.html#SubmitPatches)? 

A test to make sure we don't get the same bug again would be great too, let me know if you need help with that. You can find examples in test/unit/helpers.

**Comment by dLobatog** [comment]
Thanks @ifarkas for creating the Redmine issue. I've changed the commit format as the title has to specify the Redmine issue number to be picked up by our Jenkins CI butler :smile: 

Merged as https://github.com/theforeman/foreman/commit/bf5920d8c967775f8a64e1e104d80e1544cdf4bd , we're eager to see more contributions from you!

**Comment by ifarkas** [comment]
Thanks @eLobato!

**Pull request closed without merging**
