### PR TITLE
Fixes #26856 - Support for fog-ovirt namespace changes

### PR DESCRIPTION
**Pull request by orrabin**
This needs a new version of fog-ovirt that includes: https://github.com/fog/fog-ovirt/pull/55 so WIP for now

### CODE REVIEW

**Review by shiramax — DISMISSED** [review]

**Comment by tbrisker** [comment]
@orrabin test failure seems related

**Comment by orrabin** [comment]
@tbrisker thanks, there was one line that was not part of the namespace change, I removed it from this PR.

**Review by tbrisker — APPROVED** [review]
Thanks @orrabin ! test failures are unrelated. is there a packaging PR for fog-ovirt 1.2.0?

**Comment by shiramax** [comment]
@tbrisker - yes : https://github.com/theforeman/foreman-packaging/pull/3799

**Comment by tbrisker** [comment]
Test failures unrelated, packaging merged. Thanks @orrabin and @shiramax !

**Pull request merged**
