### PR TITLE
Fixes #35166 - Enable DHCP and static IP deployment for Ubuntu Autoinstall

### PR DESCRIPTION
**Pull request by bastian-src**
* Add `options` variable to the `APPEND` statement (make actually use of the options)
* Enable flexible network configuration (switch between DHCP and static IP)
* Make BOOTIF default for multi-network device setup
* Remove unused parameters from options
* Adapt snapshot accordingly

### CODE REVIEW

**Comment by bastian-src** [comment]
[test foreman]

**Comment by bastian-src** [comment]
[test all]

**Comment by bastian-src** [comment]
[test katello]

**Comment by bastian-src** [comment]
[test katello]

**Comment by bastian-src** [comment]
Checks seem fine. @evgeni any objections on this? I've tested it and was able to deploy dhcp and static hosts successfully.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
