### PR TITLE
[RAILS4] fixes #7567 - update syntax of deprecated find_by_[attribute] dynamic me...

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
worked on this together with @shlomizadok

**Comment by isratrade** [comment]
waiting on PR https://github.com/theforeman/foreman/pull/1784 before merge

**Comment by isratrade** [comment]
Closing Rails4 PR.  `find_or_create_by` is not in Rails 3.x

**Comment by unorthodoxgeek** [comment]
can you reopen the pr to the unorthodoxgeek:rails4 branch?

**Pull request closed without merging**
