### PR TITLE
Fixes #6650: Friendlier message when attempting to delete oneself.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by dLobatog** [comment]
:+1:  , but test/functional/users_controller.rb is failing because it checks for the exact string in the test, please fix and it'll be ready to merge.

**Comment by ehelms** [comment]
@eLobato updated

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/88c35a24d10da0d355785d6b0a76bd7901056238 , thanks @ehelms !

**Comment by lzap** [comment]
Hehe, this message was fun...

**Pull request closed without merging**
