### PR TITLE
Fixes #19869 - Fix Style/LineEndConcatenation cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Personally I rather like the `+`, but this cop is not configurable and I like consistency over personal preference.

vote :+1: for merging and enabling this cop
vote :-1: for disabling this cop

**Comment by ares** [comment]
I'd also prefer +, if there's no such option, I vote for keeping disabled

**Comment by mmoll** [comment]
Disabled this cop

**Review by ekohl — DISMISSED** [review]

**Review by tbrisker — APPROVED** [review]
Looks like disabling is agreed.

**Pull request merged**
