### PR TITLE
Script to set up Foreman first install automatically

### PR DESCRIPTION
**Pull request by dLobatog**
I included a little script to make foreman installation a simple one liner for anyone new to the project, it sets up the environment so you can run a rails server right away. 

http://zachholman.com/talk/unsucking-your-teams-development-environment

### CODE REVIEW

**Comment by ohadlevy** [comment]
@skottler @GregSutcliffe any comments?

**Comment by GregSutcliffe** [comment]
The script seems fine, but why not use the foreman-installer?

**Comment by ohadlevy** [comment]
@eLobato do you find the installer insufficient ? e.g. unable to install from git for example? if not, can we close this? thanks!

**Comment by dLobatog** [comment]
Yeah let's actually close it.

**Pull request closed without merging**
