### PR TITLE
fixes #16786 - don't call to_sentence on associations

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by daviddavis** [comment]
I'm not familiar with rails 5 but am curious why you're calling `map(&:name)` over `pluck(:name)`?

**Comment by domcleal** [comment]
> I'm not familiar with rails 5 but am curious why you're calling map(&:name) over pluck(:name)?

The associations are all eager loaded in the index query, so the data (on say `SmartProxy#features`) is already preloaded and available. Using `pluck(:name)` would generate an additional query (actually, N queries).

**Comment by daviddavis** [comment]
LGTM

**Comment by dLobatog** [comment]
Thanks @domcleal @daviddavis !

**Pull request merged**
