### PR TITLE
Fixes #23462 - bump patternfly-react to ^2.1.0

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Review by tstrachota — APPROVED** [review]
I tested it together with Katello and it provides the desired functionality.

**Comment by tstrachota** [comment]
@mmoll do you have a clue what is causing the test failures?

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by tstrachota** [comment]
Tests are green, merging. Thanks @mmoll

**Pull request merged**
