### PR TITLE
Fixes #18467, #18737 - search input is not layed on top of notification drawer

### PR DESCRIPTION
**Pull request by lizagilman**

### CODE REVIEW

**Comment by gailsteiger** [comment]
As a general comment, always prefer a pure css solution to a javascript solution to style issues.

The patternfly design calls for the notification layer to overlay other elements on the page. In this case, I suggest that you look into setting the `z-index` of `.navbar-outer`  to 3. That might also help with #18737.

There is a peculiar phenomenon in this case resulting from relative layout. When the screen width falls below 1000, the width of the search bar increases and overlays the navigation drawer - something that does not make sense.

Another thing to consider is that the navigation drawer will hide essential action buttons on the far right of the screen when it is displayed.

**Comment by lizagilman** [comment]
@gailsteiger changed z-index as you suggested

**Comment by gailsteiger** [comment]
The `.autocomplete-clear` 'x' is visible on top of the navigation drawer.

image

**Comment by lizagilman** [comment]
updated
the autocomplete results box tops the notifications drawer 
should the drawer be on top of that box?

scrn_sht

**Comment by ohadlevy** [comment]
@lizagilman yes

**Comment by lizagilman** [comment]
@gailsteiger 
indeed helped with #18737

**Comment by gailsteiger** [comment]
@lizagilman glad to know it worked for both bugs

**Comment by ohadlevy** [comment]
@lizagilman if this solves two bugs, please indicate that in the commit, e.g. fixes #12345, #54321...

**Comment by ohadlevy** [comment]
@matanwerbner I assume this will not conflict with #4401 ?

**Comment by lizagilman** [comment]
@ohadlevy 
updated

**Comment by matanwerbner** [comment]
I dont think so.

**Pull request merged**
