### PR TITLE
fixes #20369 - change host creation form tab order

### PR DESCRIPTION
**Pull request by ohadlevy**
see PR screenshot for more info.

### CODE REVIEW

**Comment by ohadlevy** [comment]
this pr is mostly for discussion /cc @rohoover

image

**Comment by ohadlevy** [comment]
image

**Comment by timogoebel** [comment]
I like it. Seems to be a more natural / workflow oriented order.

**Review by dLobatog — COMMENTED** [review]
Big +1, this is normally my workflow, why "Do not merge"?

I think the only risk is that plugins that use `deface` could be broken but nothing that can't be fixed before 1.16. Ansible for example tags its tab next to the Puppet tab so it still makes sense.

**Comment by ares** [comment]
:+1: from me too

**Comment by ohadlevy** [comment]
@dLobatog removed DNM and added a redmine issue.

**Comment by tbrisker** [comment]
Thanks @ohadlevy !

**Comment by ares** [comment]
Thanks for merging @tbrisker, please don't forget to set release in redmine.

**Pull request merged**
