### PR TITLE
Fixes #6768 - Hammer set-parameter does not work

### PR DESCRIPTION
**Pull request by mbacovsky**
Added scoped search to parameters. It helps hammer search parameters the same way as any other resource.

### CODE REVIEW

**Comment by dLobatog** [comment]
@mbacovsky :+1:  

I tested it and it works well. My only concern is that all tests are exactly the same except for one word (host2, group2, etc..) and the new fixtures. Could you refactor them to avoid the code duplication and the new fixtures (by creating the parameters 'manually')?

**Comment by mbacovsky** [comment]
I refactored the tests. @eLobato, thanks for hints ;)

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/1eaa44cab92bd1a89d56b3ec022eab0704ba7281 , thanks @mbacovsky !

**Comment by GregSutcliffe** [comment]
@eLobato can you ensure commit messages make sense before merging, please? This commit message implies we merged something that does not work :)

**Comment by mbacovsky** [comment]
@GregSutcliffe it was supposed to mean that it fixes #6768, that has a subject "Hammer set-parameter does not work". Has it different sense written that way in English?

**Comment by GregSutcliffe** [comment]
@mbacovsky, commit messages should accurately describe what functionality they add. The point is that the git logs should be readable, and a reader should be able to get a feel for what each commit does. 

In this case, if in 6 months we had an issue with scoped search on parameters, and went looking for related commits, a reader might skip this one entirely, as it doesn't mention scoped search at all. I would expect to see something like "Fixes #6768 - Add scoped search to parameters model and controller".

It's not worth updating this one, since it's already been merged, but we're merging too many things with unclear/misleading messages at the moment, and yours was the first one I happened to see today :P

**Comment by mbacovsky** [comment]
@GregSutcliffe, makes sense, thanks for explanation

**Pull request closed without merging**
