### PR TITLE
Fixes #23255 - Speed up seeds test

### PR DESCRIPTION
**Pull request by tbrisker**
Every seed run takes about 10s. This combines 6 tests to run on the same
seed action, leading to about 60s saved locally.

### CODE REVIEW

**Comment by lzap** [comment]
Thanks, wanted to do the same but was busy with webmock thing. Anyway, first question - after DatabaseCleaner README read, I think it is not being used at all - we should explicitly call it before and after test runs.

https://github.com/DatabaseCleaner/database_cleaner

Can you confirm it works?

**Comment by lzap** [comment]
If my assumption that the most expensive call is the seed method correct, we should go much further. I suggest to extract the loading code into some helper which can hand over list of Ruby seed files which can be then loaded via regexp one by one. Each test could load just what is needed. We would need to keep some basic seeds because of some dependencies but should be possible I think.

**Comment by tbrisker** [comment]
[test foreman] for some reason the test results aren't available on jenkins so we can't see the affect on times, trying agian

**Comment by tbrisker** [comment]
[test foreman]

**Comment by tbrisker** [comment]
@lzap Your assumption is correct, the slowest part here is running the seeds. I think we should keep using the whole seed, we want to make sure that when we seed everything is in the state we expect it to be and works correctly, doing only partial seeding will not give us this capability. We could try to see if more tests can be combined as well, these seemed like the lowest hanging fruit.

**Review by lzap — APPROVED** [review]
Don't want to push here, any second counts! Thanks.

**Comment by lzap** [comment]
It's 2.5 ruby tests what makes safemode to fail the suite, PR was merged in safemode.

https://github.com/svenfuchs/safemode/commit/65fcbbf933821ce1f5b5a0117b81e1122eb8d937

I asked for version bump: https://github.com/svenfuchs/safemode/pull/27

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Comment by lzap** [comment]
Great work @tbrisker ! My digging which went towards implementing webmock did not shown such an improvement, on the other hand it's good to prevent internet/DNS access anyway... :-)

**Pull request merged**
