### PR TITLE
apipie-os-update - add missing params

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by domcleal** [comment]
Is this as applicable with #1040 in progress?

**Comment by thomasmckay** [comment]
@domcleal @isratrade I assume it would be relevant still. #1040 or another will need to go through and correct or update the apipie for all the controllers. Alternatively we can do it bit by bit; this is a bit.

**Comment by domcleal** [comment]
Okay.  Can you a) file a redmine ticket, b) add this to the create action too, c) copy to the v1 controller please?

**Comment by isratrade** [comment]
@thomasmckay, there's the issue of **all possible attributes** that can be passed (such as _ids magic attributes) and what we document.  If we document the way in PR #1040 then I think the use of the _ids magic attributes should not documented in apipie.  Possible, it can be documented in an alternative section.  On the other hand, more documentation in better than less documentation as long as it's not confusing.

**Comment by thomasmckay** [comment]
Closing as irrelevant

**Comment by thomasmckay** [comment]
Retracting my close. Where are the relations documented if not here? I cannot find the apipie docs to match the hammer organization add_ and remove_ subcommands.

```
$ bundle exec hammer -v organization --help
Usage:
    hammer organization [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    list                          List all organizations
    info                          Show an organization
    create                        Create an organization
    update                        Update an organization
    delete                        Delete an organization
    add_configtemplate            Associate a resource
    remove_configtemplate         Disassociate a resource
    add_user                      Associate a resource
    remove_user                   Disassociate a resource
    add_smartproxy                Associate a resource
    remove_smartproxy             Disassociate a resource
    add_computeresource           Associate a resource
    remove_computeresource        Disassociate a resource
    add_subnet                    Associate a resource
    remove_subnet                 Disassociate a resource
    add_medium                    Associate a resource
    remove_medium                 Disassociate a resource
    add_domain                    Associate a resource
    remove_domain                 Disassociate a resource
    add_environment               Associate a resource
    remove_environment            Disassociate a resource
    add_hostgroup                 Associate a resource
    remove_hostgroup              Disassociate a resource

Options:
    -h, --help                    print help
```

**Comment by thomasmckay** [comment]
http://projects.theforeman.org/issues/3923

**Comment by isratrade** [comment]
@thomasmckay, I just saw your IRC message.  My original thought was not to document every *_ids= attribute every though Rails accepts these attributes.  However, I see the benefit in documenting them.  I plan to send an etherpad document to the -dev list about api/cli associations.

**Comment by thomasmckay** [comment]
Closing as presumably irrelevant at this point

**Pull request closed without merging**
