### PR TITLE
Fixes #34228 - close bookmarks after selecting a bookmark

### PR DESCRIPTION
**Pull request by MariaAga**
After selecting a bookmark some page don't reload and just replace the data so the dropdown should close on select

### CODE REVIEW

**Comment by stejskalleos** [comment]
> After selecting a bookmark some page don't reload and just replace the data so the dropdown should close on select

Hi, on which pages can I test it?

**Comment by MariaAga** [comment]
For example: Audits

**Comment by stejskalleos** [comment]
[test foreman]

**Review by stejskalleos — APPROVED** [review]
:heavy_check_mark: LGTM, works as described

There is however an issue with the search field: after selecting the bookmark search field is empty, we should populate the value from the bookmark there. I created special [RM#34546](https://projects.theforeman.org/issues/34546) for it.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @MariaAga for the fix and thanks @stejskalleos for the review :heart:

**Pull request merged**
