### PR TITLE
fixes #3767 - add new host to hosts menu

### PR DESCRIPTION
**Pull request by joshuabaird**
Adds "New host" to the "Hosts" menu in the top-bar.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by lzap** [comment]
_THANK YOU_ :-)

**Comment by stbenjam** [comment]
:+1:

**Comment by mccun934** [comment]
from a UI consistency standpoint why do Hosts get their own top level 'New' action where the rest of the objects within Foreman don't.  The menu items are meant to take you to a place to manage things vs the addition of the New Host option breaks that pattern.  I'm not saying this isn't a handy way to get to a very common page that people use all the time.

just throwing a bit of caution around adding top level menu items.

**Comment by kybaker** [comment]
I agree 100% mccun934

**Comment by ehelms** [comment]
Isn't there a bookmark (in foreman not the browser all though that exists
to) feature that could achieve this goal for users that want it? New host
could be a default provided at install.

**Comment by domcleal** [comment]
@ehelms bookmarks are for searches, not pages

**Comment by ehelms** [comment]
I don't see the difference, I'm just bookmarking a particular page and a
"state" of that page no?

**Comment by domcleal** [comment]
@ehelms there's a big implementation (read: speed) difference

**Comment by lzap** [comment]
> from a UI consistency standpoint why do Hosts get their own top level
> 'New' action where the rest of the objects within Foreman don't.  The
> menu items are meant to take you to a place to manage things vs the
> addition of the New Host option breaks that pattern.  I'm not saying
> this isn't a handy way to get to a very common page that people use
> all the time.

This is the example where we need to break this artificial consistency.
My point is - Foreman users do create a lot of Hosts while you create
things like Smart Proxies, Distributions or even Content not that often.
This is major difference between Hosts and all the other resources.

Hosts menu entry is different anyway today, we have different wording
and separator for bookmarks. The new "New Host" menu item will not break
anything in this submenu.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by stbenjam** [comment]
Host is already special - no other model has "All ______." New Host is a frequent activity and it should be easily accessible. Why so much drama over a menu item? :-(

I and plenty of other end users who use Foreman every day want the item. If it hinders Katello you can also remove it there...

**Comment by GregSutcliffe** [comment]
+1 to adding the entry for the reasons @lzap and @stbenjam put forward - Hosts have always been special in Foreman.

**Comment by mccun934** [comment]
@stbenjam definitely doesn't break anything.  I do agree that Hosts are such a core use case that they may in fact warrant their own menu item.  Was just cautioning about the difference in pattern.

**Comment by joshuabaird** [comment]
As a user, 'New Hosts' is a very important and a frequently used action.  I don't like to have to click to 'All Hosts' and then click 'New Host' every time I want to create a new host - which lately has been very often.  Hosts, in my opinion should treated differently.

**Comment by thomasmckay** [comment]
Having the menu "cleaned up" if it doesn't match what downstream Satellite product wants seems like a reasonable thing to do. Can we agree that a pull-request to change the pure foreman UI should come with a corresponding katello pull-request (created with/by a foretello developer assisting)? That way foretello reflects the union.

**Comment by stbenjam** [comment]
@thomasmckay What needs to happen on the Katello side? Remove the menu item in ./lib/katello/plugin.rb or something else?

I doubt this is going to be a common occurrence, this is the only menu item that I think is really missing and the only one that people have been requesting.

**Comment by thomasmckay** [comment]
@stbenjam Right now, my opinion is just to create a redmine for the katello side and reference it here. That way it will at least be in the backlog to address (either keep or remove in plugin).
:+1: ack from me

**Comment by domcleal** [comment]
Thanks @joshuabaird, sorry for the noise.  Merged as 3a2fdfd for Foreman 1.5.0.

**Pull request closed without merging**
