### PR TITLE
Fixes #15011 - don't expect the facet tables in migration

### PR DESCRIPTION
**Pull request by iNecas**
The problem was the
db/migrate/20140910153654_move_host_nics_to_interfaces.rb tries to
read the attributes that get extended by the facets, but the facets
table might not be ready yet.

To avoid unnecessary checks in production where the host.attributes
is used pretty heavily, we define the method with checks in migration only.

### CODE REVIEW

**Comment by iNecas** [comment]
failure is intermittent [test]

**Comment by bbuckingham** [comment]
@iNecas, I tested this on a downstream instance that was encountering the error with an older migration and this change resolves the issue that was being seen there.

**Comment by ShimShtein** [comment]
:+1:  Looks OK.

**Comment by tbrisker** [comment]
Merged as d1e1d191db4b765e9edb1bae12e4f407d782eac6, thanks @iNecas!

**Pull request closed without merging**
