### PR TITLE
Fixes #13697 - Remove json from gemfile

### PR DESCRIPTION
**Pull request by tbrisker**
JSON is included in Ruby stdlib >= 1.9

### CODE REVIEW

**Comment by tbrisker** [comment]
[test]

**Comment by dLobatog** [comment]
@tbrisker please rebase with develop and I think it should be ready

**Comment by tbrisker** [comment]
@dLobatog rebased

**Comment by dLobatog** [comment]
Merged as 39bb8e39a3079a6df06bc158aecb5198be604451, thanks @tbrisker!

**Pull request closed without merging**
