### PR TITLE
Fixes #28035 - Fix ovirt instance type behavior

### PR DESCRIPTION
**Pull request by bagasse**
Needs https://github.com/fog/fog-ovirt/pull/75
Follow #7070

Tested on foreman 1.22 + fog-ovirt fixes and ovirt 4.3.x

### CODE REVIEW

**Comment by bagasse** [comment]
@shiramax, @ezr-ondrej, if you have some time to take a look ;)

**Comment by ezr-ondrej** [comment]
Sorry for the dalay.
Thanks for this, nice to see the sockets resolved!
I'm still missing the js part (onChange of `instance_type`) to disable/enable the fields on the fly.
Would you like some guidance on how to do that?

**Comment by bagasse** [comment]
@ezr-ondrej the JS part is already working and already disable all fields see https://github.com/theforeman/foreman/pull/7070#issuecomment-538923169 first screenshot and javascript part https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/compute_resource/ovirt.js#L74

**Review by ezr-ondrej — COMMENTED** [review]
Ah, sorry, didn't notice that. But with our current implementation I believe we should have the fields `disabled`, not `readOnly`.

**Comment by bagasse** [comment]
I didn't noticed the difference between both `disable` and `readonly`, but I think that it don't change anything in this case because oVirt will always use instance type values for these fields (and on the foreman side we override vm value with instance type values only to make the buggy oVirt validation happy). But some guidance is definitively welcome if I'm wrong.

**Comment by ezr-ondrej** [comment]
It was readoOnly to send the values anyway (IMO because we haven't filled them out on background).
But now we do not want to send them, but will work with readOnly as well.

**Review by ezr-ondrej — DISMISSED** [review]
Thanks @bagasse. Still need to test it though.

**Comment by bagasse** [comment]
Rebased, @ezr-ondrej, sorry to poke you, but did you find some time to test this ?

**Comment by ezr-ondrej** [comment]
I would love to, but fog/fog-ovirt#75 is not released yet, right? I can apply it locally, but I can't merge until it's released and packaged.

**Comment by bagasse** [comment]
Yes, my bad... :man_facepalming:

**Comment by ezr-ondrej** [comment]
@bagasse do you know who to talk to about the release of fog-ovirt? I'm happy to make the packaging PR once it got released.

**Comment by shiramax** [comment]
@ezr-ondrej @bagasse I can do it for you. will do it today.

**Comment by bagasse** [comment]
@shiramax, thank you ! If you can take a look at https://github.com/fog/fog-ovirt/pull/76 also it would be very nice :)

**Comment by tbrisker** [comment]
@shiramax this is still pending a new fog-ovirt release, right?

**Comment by shiramax** [comment]
@tbrisker yes, sorry I was waiting for a PR to get merge,
 I created now a PR for fog-ovirt release: https://github.com/fog/fog-ovirt/pull/79 , which hopefully will be merge today.

**Comment by ezr-ondrej** [comment]
@shiramax I'm ok with the implementation, the messy assigns in view are bit ugly, but not a blocker for me. Do you want to take over and merge once ready? :slightly_smiling_face:

**Comment by shiramax** [comment]
[test foreman]

**Comment by shiramax** [comment]
@ezr-ondrej , yes thanks !

**Comment by shiramax** [comment]
I created the packaged PR for fog-ovirt: https://github.com/theforeman/foreman-packaging/pull/4315/files
@bagasse can you please rebase? we have some failing tests which I think will pass after rebase.

**Comment by bagasse** [comment]
@shiramax, done.

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
fog-ovirt packaging was merged: https://github.com/theforeman/foreman-packaging/pull/4315
thanks @bagasse

**Comment by bagasse** [comment]
@ezr-ondrej, @shiramax thanks !

**Pull request merged**
