### PR TITLE
Fixes #22075 - move activateTooltips logic to react

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by sharvit** [comment]
Nice @amirfefer!

What about tests and storybook?

**Comment by amirfefer** [comment]
@sharvit I've extracted this component logic to a different [npm package](https://www.npmjs.com/package/react-ellipsis-with-tooltip)

**Review by sharvit — APPROVED** [review]
LGTM

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
thanks @amirfefer

**Pull request merged**
