### PR TITLE
Fixes #25664 - Update pattternfly and patternfly-react versions

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Packaging:
https://github.com/theforeman/foreman-packaging/pull/3293
https://github.com/theforeman/foreman-packaging/pull/3294

**Comment by ohadlevy** [comment]
[test foreman]

**Review by sharvit — APPROVED** [review]
LGTM! Thanks @xprazak2

**Review by ekohl — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @xprazak2!

**Pull request merged**
