### PR TITLE
Fixes #22540 - auto-focus search bar

### PR DESCRIPTION
**Pull request by sean797**
This is somewhat subjective, I'm not sure how everyone feels about it

@timogoebel you mentioned it currently takes too many clicks to find a host, please try this out and let us know your thoughts.

@rohoover you may also have an opinion on this.

### CODE REVIEW

**Comment by timogoebel** [comment]
@sean797: Thanks for putting effort into this, but I'm afraid this doesn't really solve my issue.

What I think, we need is a global search bar with typeahead. Something like this:

image

I think we need something that is visible on every page and that allows you to navigate to a host just by typing the hostname.

**Comment by ShimShtein** [comment]
@timogoebel, I think I have something for you: https://github.com/ShimShtein/foreman-opensearch. It adds the ability to search foreman from browser's searchbox/omnibox.

**Review by dLobatog — APPROVED** [review]
This might not be of everyone's liking, but personally I think it makes sense. 👍 

Let's wait in case someone says otherwise

**Review by Rohoover — COMMENTED** [review]
I know that there have been talks about a global search but I don't know what the status of it is at this time. I think it could be valuable for users who want to get to something specific but don't want to wade into the UI.

**Review by lzap — APPROVED** [review]
I don't like it. I LOVE IT!

**Comment by ohadlevy** [comment]
Does it make sense to have a test that we have only one auto focus input on
this very page we have search for?

On Feb 13, 2018 12:16 PM, "Lukáš Zapletal" <notifications@github.com> wrote:

*@lzap* approved this pull request.

I don't like it. I LOVE IT!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theforeman/foreman/pull/5246#pullrequestreview-96225524>,
or mute the thread

**Review by dLobatog — APPROVED** [review]
@ohadlevy I don't think it's critical to test - from a quick check, a few forms have 'name' as autofocus, but create forms would not have a search bar in general. We can fix any of these anecdotes later if needed/

**Comment by dLobatog** [comment]
Thanks @sean797 !

**Comment by lzap** [comment]
I see one misbehavior - when I load a page and it is properly auto-focus and I switch to a different browser tab and go back, auto-suggestion drop down opens up without typing or anything.

**Comment by ares** [comment]
this happens to me on every new page I enter, Chrome 63, I hope I'm the only one since this is pretty disturbing

**Comment by sean797** [comment]
I'm not sure what we can or should do about that? Feel free to revert if no one has a good solution.

**Comment by ohadlevy** [comment]
:+1: to revert, this makes a horrible ux :(

**Comment by sean797** [comment]
Created https://github.com/theforeman/foreman/pull/5266

**Comment by timogoebel** [comment]
@sean797: Thanks anyway for your attempt. This is a good idea. I think it's the small things that make a large difference.

**Pull request merged**
