### PR TITLE
Fixes #20750 - Comment field in host page

### PR DESCRIPTION
**Pull request by ron-benaim**
Add comment field to host main page if exists.
Currently need to edit the host to see the comment (free text)

### CODE REVIEW

**Comment by boaz0** [comment]
@ron-benaim congrats for your first PR!
Can you attach a screenshot of how it looks?

**Review by boaz0 — APPROVED** [review]
LGTM

**Comment by ron-benaim** [comment]
@ripcurld0 thanks!
attached screen shots with and without the comment field
without:
without
with:
with

**Comment by ohadlevy** [comment]
What happens on a large / multi line comment? Afair it's a text field

**Comment by tbrisker** [comment]
ok to test

**Comment by orrabin** [comment]
[test katello]

**Comment by orrabin** [comment]
Looks good with reasonable long comments.
image
Edit: This depends on the usage, if the comment field is used to explain each change maybe it should be trimmed and appear in a tooltip or have a fullscreen button added to read all of it.
👍 from me to adding it and if needed trimming later.

**Review by tbrisker — APPROVED** [review]
:+1: to merge. If needed we'll figure out trimming in the future.

**Comment by orrabin** [comment]
Thanks for your patch @ron-benaim  - always great to see a new contributor! We hope you'll send more patches in the future, and if you have any challenges, please get in touch! https://www.theforeman.org/support

**Pull request merged**
