### PR TITLE
Fixes #21465 - load owners from any context

### PR DESCRIPTION
**Pull request by ares**
similar fix like in https://github.com/theforeman/foreman/pull/4879, please see the redmine issue for more details

### CODE REVIEW

**Comment by tbrisker** [comment]
Please rebase to get tests to run

**Review by dLobatog — COMMENTED** [review]
Lots of "Unknown member type: " errors, the error should only be raised when trying to set (create/update) the attribute, not any time owner is called, correct? cc @ares

**Review by dLobatog — CHANGES_REQUESTED** [review]
Back to WoC

**Comment by ares** [comment]
> Lots of "Unknown member type: " errors, the error should only be raised when trying to set (create/update) the attribute, not any time owner is called, correct? cc @ares

no, owner_type should be known whenever we read owner, but there are valid cases when owner_type is unknown (nil) and we try to read it, e.g. when we build a new instance and we try to auto suggest the new owner for it

I've added a case branch for this case which should fix the tests.

**Review by mmoll — DISMISSED** [review]
test failures related

**Comment by ares** [comment]
reruning tests after rebase, I expect failures that I'll need to look into, this became a bigger problem for discovery when refreshing facts

**Comment by ares** [comment]
[test foreman] [test upgrade] tests failures were unrelated, @dLobatog would you mind taking another look?

**Review by dLobatog — APPROVED** [review]
@ares Changes make sense to me, tests failures are unrelated -> Merging

**Comment by xprazak2** [comment]
It takes care of the issue where `owner` method cannot find the real owner. However, I found out that you can unknowingly switch owner when editing a host in UI.

1) log in as admin
2) create john as an admin with no location/organization
3) assign john as and owner of a some-host.example.com (host is in Default Organization/Default Location)
4) create beth with manager role in Default Organization/Default Location
5) log out, log in as beth
6) edit some-host.example.com, go to 'Additional Information' tab
7) notice john is not set as owner (dropdown has a blank value set) and is not available in dropdown selection
8) Hit the submit, revisit 'Additional Information' again
9) beth is now owner of some-host

This is caused by the fact that beth is not an admin and cannot see [users outside of her taxonomies](https://github.com/theforeman/foreman/blob/develop/app/views/hosts/_form.html.erb#L126), so john is not included in dropdown selection.

Not sure if we want to handle it here or fix it separately as a UI issue.

**Comment by ares** [comment]
we should handle it as a separate issue, would you mind opening it in redmine? I guess we need to add extra check, similar to what we have for taxonomies that user can't see in the form

**Comment by xprazak2** [comment]
I created a redmine [issue](https://projects.theforeman.org/issues/22396)

**Pull request merged**
