### PR TITLE
Refs #30659 - pin friendly_id to < 5.4

### PR DESCRIPTION
**Pull request by tbrisker**
The new release causes a breaking change to friendly.find methods.
Pinning for now until a new version is released fixingin this change.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
:+1: from a packaging perspective. From a code perspective, is there an issue? Is it https://github.com/norman/friendly_id/issues/950?

**Comment by tbrisker** [comment]
> +1 from a packaging perspective. From a code perspective, is there an issue? Is it [norman/friendly_id#950](https://github.com/norman/friendly_id/issues/950)?

It is, I added that link in the redmine issue but didn't in the commit message.

**Comment by ekohl** [comment]
I guess you caught me that I don't read the Redmine issue.

**Comment by tbrisker** [comment]
2.0 - b2d0d71ff
2.1 - 841d2e419
2.2 - 6969aaf4b

**Pull request merged**
