### PR TITLE
 Fixes #27759 - BreadcrumbBarActions to use async/await

### PR DESCRIPTION
**Pull request by MariaAga**
Update JavaScript code in Foreman to use async/await instead of .then

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
I'm wondering how about using the new API middleware instead of using the old API 
It's time to reuse our infrastructure :)

**Comment by MariaAga** [comment]
@amirfefer There is already a PR for it :) https://github.com/theforeman/foreman/pull/6894

**Review by amirfefer — DISMISSED** [review]
LGTM :+1: 

can you fix the commit message please?

**Comment by MariaAga** [comment]
Fixed the commit message, text failure seems unrelated

**Review by tbrisker — APPROVED** [review]
Thanks @MariaAga !

**Comment by tbrisker** [comment]
[test foreman]

**Comment by tbrisker** [comment]
I think the failing test is related, it is failing on the same test in two runs.

**Review by tbrisker — APPROVED** [review]
actually forget about that, looks like GH didn't update the link. Thanks @MariaAga !

**Pull request merged**
