### PR TITLE
fixes #17484 - remove reported_at sequence from report factory

### PR DESCRIPTION
**Pull request by domcleal**
Prevents reports getting ever more out of sync from Time.now.

### CODE REVIEW

**Comment by domcleal** [comment]
[test foreman]
[test upgrade]

**Comment by domcleal** [comment]
@theforeman-bot ok to test

**Comment by shlomizadok** [comment]
++ LGTM

**Comment by domcleal** [comment]
I made a further change to the _host_ factory that creates many reports to change the reported_at value to different values. The precision of the timestamp field is low by default, and there's a unique index on it so the value needs to be changed when adding multiple reports.

Most uses of the factory for single reports should be fine, but any user creating more than one report (like the host factory) will need to supply unique values for `reported_at`.

**Comment by dLobatog** [comment]
Thanks @domcleal & @shlomizadok !

**Pull request merged**
