### PR TITLE
Fixes #19770 - Disable Layout/DotPosition cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
There are a few more occurences in the current codebase with the dot at the end.

Also, it feels more logical to me, because I know when I see such a dot that the statement does continue.

Opinions?

**Review by tbrisker — COMMENTED** [review]
TBH, I prefer the leading version, esp. when the dot is aligned to the previous lines' dots it makes it clear this is a chain of functions. In the trailing style when reading a line it isn't a clear it continues the previous line, especially if the previous line is long and the trailing dot isn't visible.

**Comment by mmoll** [comment]
I opened GH-5419 for comparison

**Comment by ares** [comment]
Tbh I prefer this one more than the alternative, but I don't insist. I'd be even happier if we keep this disabled.

**Comment by ekohl** [comment]
I also have a slight preference for the other version.

**Comment by mmoll** [comment]
Just to kick into this again, I'm still preferring this version, the alternative PR has about the double amount of chnages and I discovered this setting like here also in foreman_ansible... But also I wouldn't be really sad to disable this cop.

**Comment by ekohl** [comment]
I really see benefits in both styles so I can see why there's a difference in preferences. To me that suggests disabling it is a good way forward here.

**Comment by tbrisker** [comment]
I agree, we don't have an agreement on preferred style so let's disable it.

**Comment by mmoll** [comment]
sure, disabled :)

**Review by tbrisker — CHANGES_REQUESTED** [review]
Please remove the relevant lines from the todo yml :)

**Comment by mmoll** [comment]
aw. done.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll

**Comment by lzap** [comment]
Proper execution by everyone, thank God we don't have this one.

**Pull request merged**
