### PR TITLE
Fixes #22379 - Remove pagination from csv export

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker mind adding a test ? this my warrant a bigger change, as most controllers do use the  resource_base_search_and_page method...? maybe we should detect inside that method if we are using csv format so it works for all controllers?

**Comment by tbrisker** [comment]
@ohadlevy added test, fixed issue in HG controller and opened https://github.com/mislav/will_paginate/pull/562 to fix the issue in will_paginate gem that throws an error when resetting limit on paginated scope.

**Comment by xprazak2** [comment]
Works as expected, I was able to export all the facts, not just a page of 20.

**Review by ares — APPROVED** [review]
makes sense, works well, thanks @tbrisker @xprazak2 @ohadlevy

**Comment by ares** [comment]
cherry-picked to 1.17-stable as https://github.com/theforeman/foreman/commit/44780a3cdb53e376a44fcc203e171c0db236d959

**Pull request merged**
