### PR TITLE
Fixes #35017 - Add Tracer installation status to System properties card

### PR DESCRIPTION
**Pull request by lfu**
Add Tracer installation status to System properties card in Details tab.

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
See other PR comment, let's revert the slot name changes.

Works well otherwise!

**Comment by MariaAga** [comment]
LGTM, can you please change the commit and pr title?

**Review by jeremylenz — APPROVED** [review]
LGTM, pending test runs :+1:

**Comment by jeremylenz** [comment]
'React on plugins' test failures are in foreman-tasks and unrelated; merging.

**Pull request merged**
