### PR TITLE
Fixes #26089 - Handle empty times in react date components

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
@tbrisker probably also a good cherry pick into 1.21.

**Review by tbrisker — APPROVED** [review]
Thanks @ekohl !

**Comment by tbrisker** [comment]
1.21 :cherries: - 8652e24fe

**Comment by alexjfisher** [comment]
Thanks for cherry-picking.  I'm hoping to be able to use a post 1.21 development version of the smart-proxy (with new puppet-ca provider), but with a released 1.21 foreman.

**Pull request merged**
