### PR TITLE
Fact parsers organization

### PR DESCRIPTION
**Pull request by domitea**
Since parsers have own place in core, it's good to have them organized in better way. Current parsers are still in plugin-specific folders and it's not a good idea. So this PR introduces `FactParsers` namespace where parsers are much better organized. It also introduces `FactNames` namespace where is the same problem.

The PR is based on https://github.com/theforeman/foreman/pull/8781 so It will be good to merge it after mentioned PR. Also, tests are only updated to pass because there is still a https://github.com/theforeman/foreman/pull/8870 PR where some tests are added and updated regarding to parsers. After merging mentioned PRs, I think it will be good time to refactor tests of parsers too.

### CODE REVIEW

**Comment by domitea** [comment]
> Issues: [#33094](https://projects.theforeman.org/issues/33094)

Correct issue number is  [#33904](https://projects.theforeman.org/issues/33904)

**Comment by domitea** [comment]
[test katello]

**Comment by lzap** [comment]
Apologies that this was left so long without proper review. I see this references the other commit which is currently draft. This PR now contains two commits, so what is the plan? Where do you want me to review?

I dropped a comment in the other PR as well. If this one depends on the other one, I think it is better to start there and then to rebase this one.

**Comment by domitea** [comment]
As I wrote in the first comment. This is based on the works of unifying if `FactImporter` class. That's the reason why there is two commits. 

Also there is fix for katello tests (https://github.com/Katello/katello/pull/9830) that's will be good to merge after this PR will be merged.

**Comment by jturel** [comment]
No activity on this PR in quite some time - is it ready for merge?. As soon as it's in we can test the related Katello PR.

**Comment by ekohl** [comment]
AFAIK @domitea has left Red Hat so I think we may need to find someone else to take over the effort.

**Comment by jturel** [comment]
> AFAIK @domitea has left Red Hat so I think we may need to find someone else to take over the effort.

Ah, right :(

Maybe the current reviewer can do that since they have the most context. What do you think @lzap ?

**Comment by lzap** [comment]
This patch is too big, if anyone wants to take over I suggest smaller steps. Feel free to reopen.

**Pull request closed without merging**
