### PR TITLE
fixes #11408 - allow plugin to define own permission for layout helper

### PR DESCRIPTION
**Pull request by stbenjam**
Plugin example https://github.com/theforeman/foreman_salt/pull/46

### CODE REVIEW

**Comment by stbenjam** [comment]
I can just as easily do this myself with `alias_method_chain`, but I'd rather not.

**Comment by stbenjam** [comment]
Random katello failure [test]

**Comment by dLobatog** [comment]
Looks great, thanks @stbenjam . Can you leave a comment in the code explaining how plugins should use it? A test would also be a great way to make sure this doesn't get removed again.

**Comment by ares** [comment]
[test] unrelated katello test failure

**Comment by stbenjam** [comment]
Not really sure how to test this @eLobato, I guess I'd have to create a fake plugin like we did before, but with a model that has taxonomies :fearful: and write a similar test to the one in https://github.com/theforeman/foreman/pull/2564.

It could be simpler if I were just unit testing authorized_associations_permission_name, but its a  private method so that doesn't seem right to me, either.

I think I'll just `alias_method_chain` this method in Salt instead, unless you have a suggestion about what to do here.

**Comment by stbenjam** [comment]
I did alias_method_chain.

**Pull request closed without merging**
