### PR TITLE
Fixes #3130 - Use the standard CentOS mirror

### PR DESCRIPTION
**Pull request by GregSutcliffe**

### CODE REVIEW

**Comment by lzap** [comment]
+1 Much better, I wonder do they have location-based resolving on that? For me it returns:

```
$ host mirror.centos.org
mirror.centos.org has address 93.113.36.66
```

**Comment by GregSutcliffe** [comment]
it seems so:

```
$ host mirror.centos.org
mirror.centos.org has address 85.214.205.10
```

**Comment by domcleal** [comment]
Ah yes, I assumed it was just the central system.

```
mirror.centos.org has address 88.208.217.170
```

**Comment by lzap** [comment]
Problem with mirrors solved :-) At least for CentOS.

**Comment by domcleal** [comment]
Thanks @GregSutcliffe, merged as 00ddc9db for Foreman 1.3.

**Pull request closed without merging**
