### PR TITLE
Fixes #13721 - Some settings should dispaly a drop down list

### PR DESCRIPTION
**Pull request by sean797**
I was also thinking about doing this for "Location fact" & "Organization fact" but I think we should allow this to be set to a fact that foreman potentially hasn't seen yet?

### CODE REVIEW

**Comment by sean797** [comment]
[test]

**Comment by sean797** [comment]
Any idea why it's failing? Seems odd to me - http://ci.theforeman.org/job/test_develop_pr_core/8102/database=postgresql,label=fast,ruby=2.2/testReport/junit/%28root%29/HostIntegrationTest__edit%20page/test_0007_choosing_a_hostgroup_does_not_override_other_host_attributes/

**Comment by ares** [comment]
[test]

**Comment by domcleal** [comment]
It's an intermittent error (http://projects.theforeman.org/issues/13293), just ignore it.

**Comment by dLobatog** [comment]
Merged as a8f5a4c10ea8481b896c3c7fc17fadc2634505f5, thanks @sean797!

**Pull request closed without merging**
