### PR TITLE
Refs #3809 - Remove cop IndentationConsistency

### PR DESCRIPTION
**Pull request by dLobatog**
Cop to enforce indentation consistency

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by daviddavis** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by ares** [comment]
+1

**Comment by dLobatog** [comment]
Closed in favor of https://github.com/theforeman/foreman/pull/2174

**Pull request closed without merging**
