### PR TITLE
Fixes #34948 - drop missing owner notification

### PR DESCRIPTION
**Pull request by nofaralfasi**
Dropped the missing owner notification since we no longer have a way to create a host without an owner.

### CODE REVIEW

**Review by ofedoren — COMMENTED** [review]
Thanks, @nofaralfasi, :+1: for removing some code :)

LGTM, the only issue is incorrect commit message: it should be `Fixes` instead of `Fixed`.

**Comment by nofaralfasi** [comment]
> Thanks, @nofaralfasi, +1 for removing some code :)
> 
> LGTM, the only issue is incorrect commit message: it should be `Fixes` instead of `Fixed`.

Thanks @ofedoren. My bad, I'll fix it.

**Comment by ofedoren** [comment]
ok to test

**Comment by nofaralfasi** [comment]
I see that two of the tests are failing (which makes sense to me after checking).
The test: `'notification when host has no owner'` (test/controllers/notification_recipients_controller_test.rb:87) is failing because I deleted this notification in this PR. 

Also, we are using the `MissingOwner` class which was deleted, in the following test: `'deliver! should not run if audience is nil'` (test/unit/ui_notifications/hosts/base_test.rb:29), which is calling the `deliver!` method here: `app/services/ui_notifications/hosts.rb:4`.

@Ron-Lavi - do you agree we should delete these tests, and maybe also the code inside the `unless subject.owner` block in the `deliver!` method (app/services/ui_notifications/hosts.rb:5-10)? Or maybe you have other suggestions? 
I tried to be as clear as possible but maybe it will be best if I show you the code.

**Comment by nofaralfasi** [comment]
Update:
I deleted the two tests that were failing, and deleted the `deliver!` method from the `Base < UINotifications::Base` class here at: `app/services/ui_notifications/hosts.rb:4`.

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, all tests are green and looks like all related files have been deleted.
@ofedoren if you ok with the changes we can merge

**Review by ofedoren — APPROVED** [review]
Thanks, @nofaralfasi and @stejskalleos, let's get this in.

**Pull request merged**
