### PR TITLE
Fixes #24737 - add read_attribute_before_type_cast for settings

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
[test foreman]

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Comment by lzap** [comment]
So I assume that Rails stack now calls this method which is missing and throwing an exception?

**Comment by mmoll** [comment]
See the linked issue for the related Rails change. The issue came up as with Rails 5.2.1, numerical values can't get saved for settings, as the default value is coming out as yaml and it can't get casted to an int.

**Comment by lzap** [comment]
I also assume this is a temporary hack for 5.2.0 version? Then can we leave a comment when this can go away?

**Comment by lzap** [comment]
Is the referenced commit in Rails actually the fix or the commit which broke it?

**Comment by mmoll** [comment]
It is needed for Rails 5.2.1+ (not for 5.2.0), the real solution will be to do a bigger refactoring of settings and default settings.

**Comment by tbrisker** [comment]
not quite. The numeric validator changed in 5.2.1 so now it pulls the value before type casting in a different way (previously it used `value_before_type_cast` which we aliased to `value`). since we have a ton of voodoo around the way we serialize and deserialize values, the value before type casting in the database isn't what rails would expect it to be.

**Comment by lzap** [comment]
Yeah I just figured it out, thanks. Well, nice hack. Let's merge this thanks.

**Pull request merged**
