### PR TITLE
Fixes #2433 - Fix Orchestrastion resond_to? test to work on ruby 2.0

### PR DESCRIPTION
**Pull request by GregSutcliffe**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Also adds a test for the fix and a small typo fix to the error handling itself.

**Comment by GregSutcliffe** [comment]
Added a test for the error handling too

**Comment by domcleal** [comment]
Merged as d1eb00f.  Thanks especially for the test @GregSutcliffe!

**Comment by lzap** [comment]
lol d1eb00f = die boof

:-)

On Fri, Apr 26, 2013 at 08:03:18AM -0700, Dominic Cleal wrote:

> Merged as d1eb00f.  Thanks especially for the test @GregSutcliffe!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman/pull/554#issuecomment-17079749

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Pull request closed without merging**
