### PR TITLE
fixes #5128 - use compute resource hostname for libvirt console connection

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by domcleal** [comment]
This will be incorrect if the libvirt daemon is running on a different system to the hypervisor though?

**Comment by jlsherrill** [comment]
@domcleal thanks, i figured there was some scenario i was overlooking.  Any other idea how we would solve the issue?  A hostname override perhaps?

**Comment by domcleal** [comment]
Maybe you could use Resolv::DNS to check that hypervisor.hostname resolves, else try using the hostname from the CR URL, as long as you provide some logging when this happens.

**Comment by jlsherrill** [comment]
@domcleal ah thanks!  I'll give that a try

**Pull request closed without merging**
