### PR TITLE
Fixes #29670 - upgrade patternfly

### PR DESCRIPTION
**Pull request by ezr-ondrej**
As #7187 - sprockets PR won't get it in for 2.1, this needs to go in, as packaging is already on this version.

Not sure who does the dep bump in packaging, in case it's not taken care of in other means: theforeman/foreman-packaging#4814. If it is, please close that one :)

### CODE REVIEW

**Review by tbrisker — DISMISSED** [review]
Thanks @ezr-ondrej !

**Review by ekohl — DISMISSED** [review]
> As #7187 - sprockets PR won't get it in for 2.1, this needs to go in, as packaging is already on this version.

Not so sure about that: https://github.com/theforeman/foreman/pull/7187#pullrequestreview-403416359

That said, :+1: since this matches what's already packaged. It's rather messy that we merged things in packaging without the corresponding core change.

**Comment by tbrisker** [comment]
@ezr-ondrej can you please rebase on develop? i think you're hitting integration test failures that were already fixed

**Comment by ezr-ondrej** [comment]
> @ezr-ondrej can you please rebase on develop? i think you're hitting integration test failures that were already fixed

bad news @tbrisker: this is on latest develop :( specifically 10e7aa5c16283d90dd92d679051ac2853d742069 is in.

**Comment by tbrisker** [comment]
[test foreman]

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej !

**Review by mmoll — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
https://gph.is/2blAYuC c'mon Katello!

**Comment by mmoll** [comment]
There we go...

**Comment by mmoll** [comment]
merged, díky @ezr-ondrej!

**Comment by ezr-ondrej** [comment]
:heart_eyes: 
tenor

**Pull request merged**
