### PR TITLE
fixes #9815 - Corrects group parameter cloning on hostgroup

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by dLobatog** [comment]
Thanks for the new PR @cfouant ! There seem to be a few test failures:

```
HostgroupTest::#clone.test_0001_clone should clone config groups as well
HostgroupTest::#clone.test_0002_clone should clone puppet classes
HostgroupTest::#clone.test_0003_clone should clone parameters values but update ids
```

**Comment by domcleal** [comment]
> HostgroupTest::#clone.test_0001_clone should clone config groups as well
> HostgroupTest::#clone.test_0002_clone should clone puppet classes

Mostly seems to have been a rebase error, lookup_value_matcher doesn't need to be listed in the deep_clone.

This extra commit ought to fix it, and also based on my PR #2588 (which fixed host_common) should ensure Puppet related things are cloned properly: https://github.com/domcleal/foreman/commit/9ecaee72685b68aaf17f6a08964ef325c8a53d95 (just cherry pick and squash).

**Comment by cfouant** [comment]
@domcleal Thanks - I wouldn't have been able to work on this branch until next week!

**Comment by ares** [comment]
Some tests are red :disappointed:

**Comment by cfouant** [comment]
@ares - Thanks, I will look into this and fix ASAP.

**Comment by cfouant** [comment]
@domcleal - Some of the changes you made to the parameters included in deep clone were causing failures on save (specifically host_config_groups and hostgroup_classes). I kept them out to leave same functionality as before.

**Comment by domcleal** [comment]
Okay, I can always look at that separately after.  Please note that there are still test failures, some old usage of "nested" that needs removing?

**Comment by dLobatog** [comment]
Merged as 621cdaf6a594499818c143db28297c82d8d04b7d, thanks @cfouant!

**Pull request closed without merging**
