### PR TITLE
Sync templates

### PR DESCRIPTION
**Pull request by ares**
Template were already reviewed in community-templates, I'm adding this via PR only because there were two new snippets, so I added them to seeds.d definition. Given how many changes we're pulling in, I think we should do this more often.

### CODE REVIEW

**Review by mmoll — APPROVED** [review]
test failures unrelated

**Comment by mmoll** [comment]
merged, díky @ares!

**Comment by ekohl** [comment]
Normally we do this before branching but it looks like it happened after branching inside the branch. That means it's a much larger set. I don't mind doing it more often though.

**Comment by ares** [comment]
some feaures/bugs couldn't be tested on nightlies without sync, I'd prefer to do the sync ideally on nightly basis :-)

**Pull request merged**
