### PR TITLE
Fixes #20287 - fix plugin assets precompilation

### PR DESCRIPTION
**Pull request by mmoll**
The error was only visible with RAILS_ENV=production

### CODE REVIEW

**Comment by mmoll** [comment]
@ehelms @waldenraines could you also have a look here?

**Review by iNecas — APPROVED** [review]
I can confirm this works for compiling assets for foreman-tasks and foreman_remote_execution

**Comment by iNecas** [comment]
@dLobatog @ehelms @waldenraines anything against merging this? Plugin assets compilation just doesn't work currently without this fix and I can confirm it works with this patch.

**Review by dLobatog — APPROVED** [review]
Tested the difference with and without the patch - works just fine, thanks @mmoll & @iNecas

**Pull request merged**
