### PR TITLE
Fixes #34009, #34010 - add finalization hook to plugin and RBAC

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Add a method, that finalizes the plugin setup.
This should serve as a hook to do stuff that needs to be done only after the initialization of Foreman completed.

First step to achieve #8954

### CODE REVIEW

**Review by tbrisker — CHANGES_REQUESTED** [review]
looks like tests are failing

**Comment by ezr-ondrej** [comment]
Yeah, we changed the initialize of the `RbacRegistry`, hopefully thos are initialized only in tests apart of the `Plugin.new`

**Comment by ezr-ondrej** [comment]
:green_apple: could we get this in, unless there is some issue with the naming (naming is hard).

**Comment by ezr-ondrej** [comment]
Closing and keeping the #8954 for a wholistic approach.

**Pull request closed without merging**
