### PR TITLE
Fixes #28001 - add rainbow gem to development group

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
~will require RPM adjustment, once merged.~

**Comment by ekohl** [comment]
Is this used on production systems? @timogoebel

**Comment by timogoebel** [comment]
> Is this used on production systems? @timogoebel

I don't know. Why are you asking? :-)

**Comment by mmoll** [comment]
It might go into `bundler.d/development.rb` instead.

**Comment by ekohl** [comment]
That was indeed the underlying question I have.

**Comment by timogoebel** [comment]
> That was indeed the underlying question I have.

I don't think this is for dev only and I guess it won't hurt in any case.

**Comment by tbrisker** [comment]
@mmoll @timogoebel @ekohl what's the decision here? should we add the gem to the development group, general gemfile or remove the code relying on it?

**Comment by mmoll** [comment]
Personally I think GH-7085 is more correct.

**Comment by ekohl** [comment]
I can see the value of colors in output, but would prefer some abstraction. `info`, `warn` and `error` methods that only display colors when relevant make the most sense to me.

**Comment by lzap** [comment]
I don't mind either dropping colors or adding new dependency. Since it's development one, I really don't care (no packaging).

However I dropped a comment in the other PR (https://github.com/theforeman/foreman/pull/7085) - the code we are talking about could maybe be refactored.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll, merging this now to fix the broken dependency. Feel free to open follow up prs refactoring or changing code.

**Pull request merged**
