### PR TITLE
Fixes #16414 - reword alphanumeric validation error message

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
It's not clear to me the new error says anything new, "underscored" is also kind of hard to translate, at least I don't know any translations for it. Deferring the review to others

**Comment by ares** [comment]
maybe "must be alphanumeric with underscores and cannot contain spaces or hyphens"

**Comment by shlomizadok** [comment]
@domcleal - I would appreciate your help with the right rewording :) - thanks

**Comment by domcleal** [comment]
@ares' suggestion is most definitely better. Perhaps also add separate checks for spaces and hyphens if you want to mention them in the error, then add an error stating `cannot contain spaces` only if they're found. It keeps the default message much simpler ("must be alphanumeric with underscores"), and Rails will concatenate errors automatically.

Or simpler still, "must only contain alphanumeric or underscore characters". Should be clearer than a list of things that it can't contain.

**Comment by shlomizadok** [comment]
Thanks @domcleal , this reads better.

**Comment by dLobatog** [comment]
Thanks @ares @shlomizadok @domcleal !

**Pull request merged**
