### PR TITLE
fixes #8364 - Adds SQL N+1 Query detection using bullet.

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test]

**Comment by ohadlevy** [comment]
not sure why this fails, [test] again, not sure why it looks for commit:3f0dac4dd1b8761eb881f5cbb451dfd1db12b988

**Comment by domcleal** [comment]
Error when running db:migrate rake task:

<pre>
00:03:23.724 NameError: uninitialized constant Bullet
00:03:23.725 /var/lib/workspace/workspace/test_develop_pr_core@2/database/postgresql/ruby/1.9.3/config/initializers/bullet.rb:2:in `<top (required)>'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/engine.rb:592:in `each'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/engine.rb:592:in `block in <class:Engine>'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/initializable.rb:30:in `instance_exec'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/initializable.rb:30:in `run'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/initializable.rb:55:in `block in run_initializers'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/initializable.rb:54:in `each'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/initializable.rb:54:in `run_initializers'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/application.rb:136:in `initialize!'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/railtie/configurable.rb:30:in `method_missing'
00:03:23.725 /var/lib/workspace/workspace/test_develop_pr_core@2/database/postgresql/ruby/1.9.3/config/environment.rb:5:in `<top (required)>'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/application.rb:103:in `require_environment!'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/gems/railties-3.2.20/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/bin/ruby_executable_hooks:15:in `eval'
00:03:23.725 /usr/local/rvm/gems/ruby-1.9.3-p392@test_develop_pr_core-2/bin/ruby_executable_hooks:15:in `<main>'
00:03:23.725 Tasks: TOP => db:migrate => environment
</pre>

**Comment by dLobatog** [comment]
According to the gem README, Bullet goes under `config.after_initialize`. Why not putting it under  `config/environments/development.rb`?

**Comment by ohadlevy** [comment]
updated, thanks

**Comment by ohadlevy** [comment]
its still failing, is it possible that we don't include the bundler development environment in our CI?

**Comment by domcleal** [comment]
@ohadlevy correct, we don't.  I'm not sure assuming the Rails env equals the bundler group is the right thing to do.. maybe best to check if Bullet is defined?

**Comment by ohadlevy** [comment]
@domcleal thanks, updated.

**Comment by dLobatog** [comment]
Merged as 3bc0dde528503f7e626b140a3ab9da7ebf8c3c5d , thanks @ohadlevy ! 
Fortunately I've countered very few n+1 queries in Foreman and only one or two that dealt with large data sets, hope this helps keeping the project tidy.

**Pull request closed without merging**
