### PR TITLE
Fixes #28258 - Fixed a typo in the UI

### PR DESCRIPTION
**Pull request by garwil**
I noticed a typo in the UI and wanted to fix it.

### CODE REVIEW

**Review by ohadlevy — DISMISSED** [review]

**Comment by ohadlevy** [comment]
thanks! can you please just change the commit message, e.g. something like "fixes #28258 - fixes typo in facts page"

**Comment by garwil** [comment]
Hope that's OK now. I misread the instructions when I made the PR :man_facepalming:

**Comment by ekohl** [comment]
ok to test

**Review by ekohl — APPROVED** [review]

**Comment by ohadlevy** [comment]
thanks @garwil!

**Pull request merged**
