### PR TITLE
Fixes #20514 - Accept dollar sign($) in login names

### PR DESCRIPTION
**Pull request by avylove**
This will allow dollar signs to be valid characters in login names. This facilitates using Active Directory machine SAMaccountNames as valid user accounts.

### CODE REVIEW

**Review by dLobatog — COMMENTED** [review]
ok to test

**Comment by xprazak2** [comment]
Works for me:

**Review by dLobatog — APPROVED** [review]
@avylove This looks good, I'll add a test on a PR following this one, seems safe enough.

**Comment by dLobatog** [comment]
Thanks @avylove & @xprazak2 !

**Pull request merged**
