### PR TITLE
Fixes #36305 - Pin sass version to 1.60.z to avoid node 14 dependency

### PR DESCRIPTION
**Pull request by sjha4**
Opening this to pin sass in foreman instead of foreman-js: https://github.com/theforeman/foreman-js/pull/464

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
FWIW, for packaging we still use `node-sass`

https://github.com/theforeman/foreman/blob/968998dbb73a975573d55f8e2d16c3437bf0bfaa/package.json#L56

Let's try this!

**Review by ekohl — APPROVED** [review]
We'll need to cherry pick this to 3.6 & 3.5 as well.

**Comment by evgeni** [comment]
@ekohl could you kick off https://ci.theforeman.org/job/foreman-develop-source-release/? Don't have Jenkins creds on my phone

**Comment by ekohl** [comment]
https://ci.theforeman.org/job/foreman-develop-source-release/1920/

**Comment by evgeni** [comment]
Seems to have passed \o/

**Pull request merged**
