### PR TITLE
Fixes #19357 - update the edit icon in hostgroup os edit page

### PR DESCRIPTION
**Pull request by junezhang**
Updating the edit icon in HostGroup Operation System Edit Page.
Updating the edit icon from Bootstrap icon to PatternFly icon.

Please check the before vs after attachment.
edit-root-password

### CODE REVIEW

**Comment by dLobatog** [comment]
[test foreman]
[test katello]
[test upgrade]

Can anyone @theforeman/core invite @junezhang to @theforeman organization?

@junezhang after you get the invitation and accept it, you need to make sure your profile has the Foreman organization visible, here are some steps on how to do it.

**Review by dLobatog — APPROVED** [review]
👍 if tests pass

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
Thanks @junezhang !

**Comment by junezhang** [comment]
@dLobatog Thanks for reviewing it, unfortunately I haven't received the invitation. So My PRs still can't run testing automatically.  :-( still need your help to test my next PR. Thanks.

**Pull request merged**
