### PR TITLE
Fixes #37150 - Race condition in edit smart proxy test

### PR DESCRIPTION
**Pull request by dosas**

### CODE REVIEW

**Comment by ekohl** [comment]
Ok to test

**Comment by stejskalleos** [comment]
[test katello]

**Comment by stejskalleos** [comment]
Integration tests are failing on:
```
    test/integration_test_helper.rb:302:in `login_admin'
    test/integration_test_helper.rb:331:in `before_setup',Selenium::WebDriver::Error::InvalidSessionIdError: invalid session id
```
Guess it's not related to this changes, let's if they'll fail on rerun again

**Comment by dosas** [comment]
@stejskalleos Looks to me like the integration tests are failing all over the place for some time now.
https://github.com/theforeman/foreman/actions/runs/7934552063
I would be surprised it rerun works.

**Comment by stejskalleos** [comment]
Yeah without green CI I can't be sure that this _actually_ fixes the issue.
cc @ekohl @evgeni

**Comment by evgeni** [comment]
you can temporarily pull in the changes from https://github.com/theforeman/foreman/pull/10034 and see if things pass.

chrome 122 is supposed to be released today and fix the issue (fingers crossed)

**Comment by dosas** [comment]
@evgeni Are there any news on the chromedriver? The PR you mentioned above is still a draft.
Should I rebase?

**Comment by evgeni** [comment]
Yes, rebase please, there is now a fixed chrome deployed.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
Thanks @dosas and sorry it took way too long for a one-liner.

**Pull request merged**
