### PR TITLE
Fixes #15628 - Require rdoc for apipie-rails

### PR DESCRIPTION
**Pull request by vkrizan**
apipie-rails has rdoc optional, however, its default markup generator is
RDoc.  rdoc seems to be found on most of the default OS installations
through inclusion from rubygems.

This fixes (development) setup when rdoc is missing:

https://projects.theforeman.org/issues/15628
```
`require': cannot load such file -- rdoc (LoadError)
```

Reproduced on Fedora 32 using standalone bundle install.

Technically, the apipie-rails should not fail with default configuration
when an optional dependency is not installed: see https://github.com/Apipie/apipie-rails/issues/544

(Repush of pull #4503)

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
@ofedoren can you take a look and say if this should be fixed here or in apipie?

**Review by lzap — DISMISSED** [review]
Thank you for the contribution, looks good. No packaging involved as rdoc is part of core Ruby.

**Review by ekohl — CHANGES_REQUESTED** [review]
Mind removing it here:
https://github.com/theforeman/foreman/blob/17d7be599c88ab953d10a396eccdc93d30a69e88/Dockerfile#L49

Other than that I can confirm I have this on my Fedora setup as well.

**Comment by vkrizan** [comment]
Removed from the Dockerfile.

> [...] say if this should be fixed here or in apipie?

I've submitted a patch for apipie (to lazyload it): https://github.com/Apipie/apipie-rails/pull/683
However, the dependency is still need to be required, as Forman seems to use the RDoc markup generator through apipie-rails.

Thanks.

**Review by ekohl — APPROVED** [review]

**Comment by ofedoren** [comment]
@tbrisker, well. It makes sense to have this fixed in apipie-rails first. Thanks, @vkrizan, I'll take a look and merge that patch.

Although, I don't quite follow why it should be fixed here and there. If we fix it in apipie-rails then this fix is no longer needed (we use Maruku in dev mode and, if I'm not mistaken, cached doc version in prod mode). But I'm not against it, seems safer.

**Comment by vkrizan** [comment]
Oh, I've missed that there is a different markup configured.

`config/initializers/apipie.rb`:
```
Apipie.configure do |config|
  config.markup = Apipie::Markup::Markdown.new if Rails.env.development? && defined? Maruku
end
```
It looks like it would only be used for development env, on other env it would be default RDoc (?).

**Comment by ofedoren** [comment]
@vkrizan, Probably, yes :( And there is a possibility if someone will try to generate/load docs in different env without rdoc gem installed, it will crash. Your [PR](https://github.com/Apipie/apipie-rails/pull/683) was merged, so I'll create a new release today/tomorrow, thanks!

**Comment by tbrisker** [comment]
Congrats on first PR merged in Foreman @vkrizan ! looking forward to more of them :)

**Pull request merged**
