### PR TITLE
Fixes #19116 - Remove 1.17 deprecations

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by dLobatog** [comment]
Depends on https://github.com/Katello/katello/pull/6928 being merged first.

**Review by dLobatog — COMMENTED** [review]
@ares @xprazak2 https://github.com/theforeman/foreman/pull/3701 and https://github.com/theforeman/foreman/pull/3983 were meant to remove `host.info`. Now we're in a situation where it can't be removed as the providers refactoring relies completely on it. 

I realize you don't want people to call `host.info` in templates, and use `host_enc` exclusively (already voiced my concerns on the mailing list, won't fight that fight again). 

This leaves us with few options:

1. Leave host.info as is. Raise an error when called from anywhere but host_enc. Keeping a reference to a file (`/renderer\.rb.*host_enc/`) is not great for maintainability and is confusing if you don't know the "background story".

2. ..? Any other suggestions?

**Comment by ares** [comment]
can't we just remove it from safe mode whitelist?

**Comment by mmoll** [comment]
this was done in GH-5051, or is there still something missing?

**Comment by dLobatog** [comment]
#5051 did it

**Pull request closed without merging**
