### PR TITLE
Fixes #7286: Can not create a compute resource without selecting a provider

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by isratrade** [comment]
@orrabin, looks good, but there may be another bug that the form doesn't hide when you switch back to "Choose a provider"

**Comment by orrabin** [comment]
@isratrade there was another bug, I fixed it now

**Comment by isratrade** [comment]
Merged as 6803db16e801fb31fa8014ef43c0a8c42519f777. Thanks @orrabin !

**Comment by domcleal** [comment]
I filed http://projects.theforeman.org/issues/7336 as this breaks editing of CRs.

**Comment by isratrade** [comment]
@domcleal, good catch! I submitted https://github.com/theforeman/foreman/pull/1734 to fix it.

**Pull request closed without merging**
