### PR TITLE
Fixes #34349 - improve api/settings#index coverage

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by evgeni** [comment]
```
Failure:
test_0001_should get index(Minitest::Result) [/home/jenkins/workspace/test_develop_pr_core/database/postgresql/ruby/2.5/slave/fast/test/controllers/api/v2/settings_controller_test.rb:15]:
Expected: 112
  Actual: 20
```

:woman_shrugging: 

something, something, paging?

**Comment by ezr-ondrej** [comment]
> something, something, paging?

Yeah pagination not set properly.

**Review by evgeni — DISMISSED** [review]
would you mind rebasing this once, so we see it green after the fun we had with #9062? :D

**Comment by ezr-ondrej** [comment]
sure :) let's get a little bit more confidence, that never hurts :)

**Comment by evgeni** [comment]
[test katello]

This seems unrelated

**Comment by ezr-ondrej** [comment]
[test katello]
I mean it can't be related

**Comment by ezr-ondrej** [comment]
:green_apple:

**Review by evgeni — APPROVED** [review]

**Pull request merged**
