### PR TITLE
Fixes #27536 - cr tests for image attributes

### PR DESCRIPTION
**Pull request by ezr-ondrej**
The tests were copied too fast :man_shrugging:

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
In #6953 we realized we are testing gce in all the compute resources tests :man_facepalming:

**Comment by ezr-ondrej** [comment]
And they fails... any volunteers on fixing them? I wouldn't mind just to delete them, they weren't testing anything so far... but I will try to take a look if I can fix at least some :frowning_man:

**Comment by lzap** [comment]
So what is the story behind this? Looks like some copy-paste error, can you fix those tests? What is the purpose of the PR then? ;-)

**Comment by ezr-ondrej** [comment]
Now it has as much sense as life itself... none :thinking: 
I just tried if it's going to "just work" xD
Now it's just a reminder it is needed to be fixed, but I am going to do something about it :)

**Review by kgaikwad — APPROVED** [review]
Thank you @ezr-ondrej.  
Legitimate change  :+1: 

@lzap, do you have any additional comment otherwise we can merge this pull-reqest.

**Review by lzap — APPROVED** [review]
Le Git! Go ahead and merge. Thanks.

**Comment by kgaikwad** [comment]
Sorry @lzap, I don't have merge rights!

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej @kgaikwad and @lzap !

**Comment by lzap** [comment]
Thanks Tomer, sorry I am late on GH.

**Pull request merged**
