### PR TITLE
fixes #5510 - Set network as first boot device for VMs in VMware comp…

### PR DESCRIPTION
**Pull request by timogoebel**
…ute resources

This only works if connecting to via vsphere api version > 5.0. Fog defaults to 4.0, so I added a setting for this.

What do you think?

### CODE REVIEW

**Comment by timogoebel** [comment]
This requires changes in fog: https://github.com/fog/fog/pull/3754

**Comment by domcleal** [comment]
> This only works if connecting to via vsphere api version > 5.0. Fog defaults to 4.0, so I added a setting for this.
> 
> What do you think?

It would be better if we could put the setting on the compute resource itself, as different endpoints may be at different versions.  It'll also be more visible to users when they add the vSphere CR so they can select the right version at that time.

Inside compute resource models you can store any additional attributes you like.  For vSphere, we already store and retrieve `pubkey_hash` - see the two methods in app/models/compute_resources/foreman/model/vmware.rb, and add your own - e.g. `api_version`.  Add it also to the form in app/views/compute_resources/form/_vmware.html.erb as a select_f or similar and it'll appear on when creating or editing CRs.  Lastly, add it to the API in app/controllers/api/*/compute_resources_controller.rb and app/views/api/v2/compute_resources/vmware.json.rabl.

> This requires changes in fog

This may require a wait - we're blocked on updating to the next version Fog, which will be 2.0.0.  Track this on http://projects.theforeman.org/issues/11729.

**Comment by timogoebel** [comment]
@domcleal : Thanks a lot for this very detailed review. As setting the api revision is also a necessity for deploying a vm on a storage pool, which I am working on, I raised a separate Redmine for this. The corresponding PR is #2913 . 
I'll update this PR as soon as this is merged and I can rebase.

**Comment by timogoebel** [comment]
@domcleal: As https://github.com/fog/fog-vsphere/pull/3 was merged, this PR is now just a minor change. This still requires a newer fog to work. Should not do any harm though when uses with an older fog version. Should we wait for the update until we can merge this or can we do it now?

**Comment by domcleal** [comment]
We'd normally wait until the dependency is also updated, so we can test it, set the appropriate min version and know which release(s) it'll work with.

**Comment by domcleal** [comment]
Note that Fog v1.36.0 was released with your original Fog PR merged.  I opened a PR against Foreman to update our version of Fog - is that sufficient, or do you need extra code to support the API version change?

**Comment by timogoebel** [comment]
@domcleal: Unfortunately we still need the api version thing. The code is already in fog-vsphere. We should wait for a release.

**Comment by shlomizadok** [comment]
Tested. Works as expected. Pending fog-vsphere release.

**Comment by timogoebel** [comment]
@shlomizadok : Thanks a lot for testing! How did you get fog-vsphere working in your local testing environment? I always get a "TypeError: superclass mismatch for class Vsphere" caused by Foreman's fog extensions when updating fog and fog-vsphere to the latest master...

**Comment by shlomizadok** [comment]
@timogoebel - my test env is someone else's production.... (that's why I rebooted only at the weekend....)

**Comment by timogoebel** [comment]
Sometimes you better test in production. ;-)
What I ment was your local foreman env. I cannot add vog-vsphere as a separate gem to my bundler.d directory without breaking foreman. Have you had similar issues?

**Comment by shlomizadok** [comment]
Oh, yeah I'm sorry - forgot about this (plan to submit a PR...)
I also encountered that issue.
For the testing purpose I have done the following:
- I have cloned `fog-vphere` locally and changed in `fog-vsphere.gemspec` to `spec.add_runtime_dependency 'fog-core', '~> 1.35'`
- In Foreman:
  -  In Gemfile, updated to `gem 'fog-core', '1.35.0'`
  -  In bundler.d/vmware.rb: `gem 'fog-vsphere', :path => 'path/to/fog-vsphere'`

**Comment by timogoebel** [comment]
@shlomizadok: :+1: , works great. did not see that dependency... Thanks! :-)

**Comment by domcleal** [comment]
I'm setting WoC due to the dependency on a new version of Fog, once that's been fixed we can come back to this.

**Comment by timogoebel** [comment]
Rebased this on current develop, let's wait for tests...

**Comment by timogoebel** [comment]
Tests fail only for Katello (unstable).

**Comment by domcleal** [comment]
Merged as b466551, thanks @timogoebel.

**Pull request closed without merging**
