### PR TITLE
fixes #9274 - hostgroup#clone works for config groups as well

### PR DESCRIPTION
**Pull request by unorthodoxgeek**

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@unorthodoxgeek Just for the record Puppetclass associations for the cloned Config groups are being kept after the clone as you just reuse them instead of cloning the groups like you do for parameters. Can you perhaps use `deep_clone` for the whole clone method as it was written a long time ago? Thanks!

**Comment by unorthodoxgeek** [comment]
what's up with turbolinks on 1.9.3?

**Comment by unorthodoxgeek** [comment]
@eLobato - parameters should be cloned. config groups aren't the same, they're associated (i.e. many-to-many), not belonging (only) to that hostgroup.

**Comment by domcleal** [comment]
> what's up with turbolinks on 1.9.3?

pg, possibly?  I'm seeing if reverting bundler 1.8.0 will fix it: [test]

**Comment by dLobatog** [comment]
@unorthodoxgeek I left the comment precisely to remember what you said :smile: sorry if I wasn't clear

**Comment by dLobatog** [comment]
Merged as 6a07eb8155e82dcd7b22b2b41e05cb2233e8f52a, thanks @unorthodoxgeek

**Pull request closed without merging**
