### PR TITLE
Fixes #23358 - Fix audit mails for template content

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by mmoll** [comment]
@treydock could you test this?

**Comment by treydock** [comment]
Applied patch to my 1.17.0 install and was able to run the `reports:daily` task and got the emails.

**Comment by mmoll** [comment]
[test katello]

**Review by mmoll — APPROVED** [review]
test failure unrelated :green_heart:

**Comment by mmoll** [comment]
Merged, díky @xprazak2!
Please open PRs with cherry-picks to 1.18 and 1.17.

**Pull request merged**
