### PR TITLE
fixes #3170 - dash separated mac address notation

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by domcleal** [comment]
Could you add a test to test/lib/net/validations_test.rb please?

**Comment by domcleal** [comment]
Is it just me, or does this not work on the new host page?

If I enter "22-44-66-11-22-44" in the MAC address field and submit, it fails and shows these errors against the field: has already been taken, can't be blank, and is invalid.  The MAC address field is also emptied, so something odd is happening in the normalization or validation order perhaps?

**Comment by domcleal** [comment]
I tried duplicating the test at test/unit/host_test.rb:14 for hyphens and get:

<pre>
  1) Failure:
HostTest#test_0003_should fix mac address hyphens [test/unit/host_test.rb:21]:
&lt;"aa:bb:cc:dd:ee:ff"> expected but was
&lt;nil>.
</pre>

Something's fishy....

**Comment by domcleal** [comment]
ping @tstrachota?

**Comment by tstrachota** [comment]
Hmm, I didn't manage to reproduce that. I tested it in UI on my local install and it works as expected. I have no clue what can be wrong...

**Comment by domcleal** [comment]
You're right, I think that was PEBKAC, sorry!  Merged as d42d1f5, thanks @tstrachota :)

**Pull request closed without merging**
