### PR TITLE
fixes #26002 - set cors headers

### PR DESCRIPTION
**Pull request by timogoebel**
Extracted from #5596.

https://devonblog.com/security/difference-between-cors-and-csp-security-headers/

### CODE REVIEW

**Review by xprazak2 — DISMISSED** [review]
LGTM. I am personally not a big fan of env variables, but in this case it probably makes sense. I am ok when packaging acks.

**Comment by mmoll** [comment]
I am OK with this but wonder why it has to an env variable and where it would come from in a production setup (via Apache config, I suppose?).

**Comment by timogoebel** [comment]
> wonder why it has to an env variable

Because it requires a server restart and I believe we cannot rely on settings so early in the initialization phase.

> where it would come from in a production setup (via Apache config, I suppose?)

```puppet
  $cors_domains = [
    "https://${::fqdn}",
    'https://foreman.example.com',
    'https://lisa.example.com',
  ]
  $cors_domains_joined = join($cors_domains, ',')

  systemd::unit_file { 'cors-domains.service':
    path    => '/etc/systemd/system/httpd.service.d',
    content => "[Service]\nEnvironment=FOREMAN_CORS_DOMAINS=${cors_domains_joined}\n",
  }
```

@mmoll: Can you ack?

**Review by ekohl — CHANGES_REQUESTED** [review]
Like @mmoll I have my doubts about doing this via an env variable. There is a precedent for using settings in initalizers already:

https://github.com/theforeman/foreman/blob/b4e2da6199a1ff7560c016a29b1d33c94acfa1a3/config/initializers/secure_headers.rb#L2-L6

**Comment by timogoebel** [comment]
@ekohl: But then I can not use the fqdn per machine in there, can I?

**Review by ohadlevy — DISMISSED** [review]

**Comment by ekohl** [comment]
Why not? You could set a different FQDN in settings.yaml and that's still on the local disk.

**Comment by timogoebel** [comment]
Ok, I give up. But I still believe, this applies: https://12factor.net/config

Changing this now...

**Comment by ekohl** [comment]
When we deprecate running via passenger I'd feel a lot more comfortable about using env vars. Currently we don't use them and we'd need to start documenting that. For now I'd rather extend the current framework we have because it allows for discovering settings by reading the settings file.

**Comment by timogoebel** [comment]
Reworked the patch to use `settings.yaml` file.

**Comment by timogoebel** [comment]
> . For now I'd rather extend the current framework we have because it allows for discovering settings by reading the settings file.

Fair enough, I was a little harsh yesterday. That was because of unrelated stuff. This is the correct approach to this.

**Review by ohadlevy — APPROVED** [review]

**Review by ekohl — APPROVED** [review]

**Comment by timogoebel** [comment]
This looks ready to 🚢.

**Comment by ohadlevy** [comment]
thanks @timogoebel !

**Comment by tbrisker** [comment]
@timogoebel @ekohl looks like nightlies are now failing to build - i can't see the cors gem rpm in packaging
```
BUILDSTDERR: Gem loading error: cannot load such file -- rack/cors
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/output.rb:13:in `strict_err'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:46:in `rescue in block in system_require'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:39:in `block in system_require'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `each'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `system_require'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:19:in `block in system_require'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `each'
BUILDSTDERR: /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
BUILDSTDERR: /builddir/build/BUILD/foreman-1.22.0-develop/config/application.rb:17:in `<top (required)>'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
BUILDSTDERR: /builddir/build/BUILD/foreman-1.22.0-develop/Rakefile:1:in `<top (required)>'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/bin/rake:23:in `load'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/bin/rake:23:in `<main>'

**Pull request merged**
