### PR TITLE
Fixes #20955 - Remove conditions to {destroy, delete}_all calls

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
taken from Dominic's rails51 branch

**Comment by mmoll** [comment]
test failures look unrelated

**Comment by mmoll** [comment]
[test foreman]

**Review by iNecas — CHANGES_REQUESTED** [review]
There is also https://github.com/theforeman/foreman/blob/develop/app/controllers/compute_resources_controller.rb#L12 that should be updated accordingly I think

**Comment by iNecas** [comment]
There is also https://github.com/theforeman/foreman/blob/develop/app/controllers/settings_controller.rb#L10 and https://github.com/theforeman/foreman/blob/develop/app/models/host/managed.rb#L912-L913

**Comment by mmoll** [comment]
updated, tests are green 💚

**Review by iNecas — APPROVED** [review]

**Comment by iNecas** [comment]
Thanks @mmoll and @domcleal

**Pull request merged**
