### PR TITLE
Fixes #30415 - use only repos managed by sub-man

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
The failed test in foreman is pretty sure not related to this change.

**Comment by ares** [comment]
@jturel any comments on this one? It would be great to get an ACK from someone familiar with this part, I'm happy to merge then as it generally looks good. Thanks

**Comment by jturel** [comment]
Nice change! I tested that the template renders as expected and that the script performs as expected - either changing the setting or adding the setting to my plugin config if it's missing.

When I do `yum repolist` I see the system repos get disabled:

```
Disabling system repository "epel" in file "/etc/yum.repos.d/epel.repo"
Disabling system repository "cr" in file "/etc/yum.repos.d/CentOS-CR.repo"
Disabling system repository "base" in file "/etc/yum.repos.d/CentOS-Base.repo"
Disabling system repository "updates" in file "/etc/yum.repos.d/CentOS-Base.repo"
Disabling system repository "foreman-client" in file "/etc/yum.repos.d/foreman-client.repo"
Disabling system repository "extras" in file "/etc/yum.repos.d/CentOS-Base.repo"
```

**Review by jturel — APPROVED** [review]
ACK

**Review by ares — APPROVED** [review]
My appologies for not merging this earlier! Thanks @sbernhard and @jturel, merging now! Foreman failure unrelated for sure.

**Pull request merged**
