### PR TITLE
Fixes #14960 - Improve settings helper for collections

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by orrabin** [comment]
:+1:  This fixes discovery for me.

**Comment by ohadlevy** [comment]
does this solve bootdisk plugin too?

**Comment by orrabin** [comment]
@ohadlevy the error in discovery was a result of turning settings helper into a concern to use `alias_method_chain`, I didn't see the bootdisk error but this should fix all plugins since it's going back to the original helper and just changing the `value` method.

**Comment by dLobatog** [comment]
:+1: from me, this also fixes the bug about readonly collections not being 'readonly'. Will merge if Jenkins is green. Is there a ticket number for the readonly bug? If not, don't worry, but if there's one please add it to the commit

**Comment by tbrisker** [comment]
@dLobatog I don't think so, I only noticed it when I removed the `alias_method_chain`. Since PR #3272 was only merged 3 days ago I doubt anyone had time to notice this.

**Comment by dLobatog** [comment]
Merged as f88a7a55bb0a9e6522dd952980a3e6bf3e4b5045, thanks @tbrisker!

**Pull request closed without merging**
