### PR TITLE
Fixes #28144 - update notifications with our modern conventions

### PR DESCRIPTION
**Pull request by Ron-Lavi**
After replacing the notifications polling by the API middleware
I noticed this component hasn't been updated for a very long time.
this make it very difficult to modify the component and may lead to bugs.

In this PR I only copy-paste the code from the old folders conventions of `/actions` `/reducers` and `/component/notifications` into one folder: `/component/Notifications` with path updates and some small modifications.

This PR is blocked by:
- #7069 
- #7121 

Todo:
- Upgrade tests to the modern conventions

### CODE REVIEW

**Review by jeremylenz — APPROVED** [review]
Tested and clicked around; everything seems to work fine.  LGTM and also the file structure is refreshing!  :heavy_check_mark:

**Comment by jeremylenz** [comment]
I think this needs a rebase

**Comment by Ron-Lavi** [comment]
Thanks @jeremylenz, I will rebase after #7121  will get in :+1:

**Comment by jeremylenz** [comment]
Per [this comment](https://github.com/theforeman/foreman/pull/7121#discussion_r363650004), this is waiting on #7121

**Comment by amirfefer** [comment]
@laviro what is the status here? #7121 has been merge already

**Comment by Ron-Lavi** [comment]
imo it makes sense to wait until #7261 and #7337 which are going to get merge soon,
than update notifications with more API replacement with middleware
and only than update this PR - hopefully with less code and less tests :)

**Pull request closed without merging**
