### PR TITLE
fixes #2809 - send host subject as xpi opt to prevent ssl connect errors

### PR DESCRIPTION
**Pull request by jmontleon**
relies on https://github.com/abenari/rbovirt/pull/23

### CODE REVIEW

**Comment by domcleal** [comment]
Looks good, could you:

a) add a redmine ticket and update the commit message to contain it ("fixes #1234 - blah")
b) update bundler.d/ovirt.rb to require rbovirt 0.0.21
c) update foreman.spec for the same, bump the release and add a %changelog entry

Thanks!

**Comment by jmontleon** [comment]
@domcleal updated. thank you.

**Comment by domcleal** [comment]
Great, thanks.  Could you rebase the branch too, I think there's been a conflicting edit to foreman.spec since the branch was created.

**Comment by jmontleon** [comment]
I think it's set now

**Comment by domcleal** [comment]
Merged as 36a6345, thanks @jmontleon!

**Pull request closed without merging**
