### PR TITLE
Fixes #30993 - Host Registration endpoind - Remove :owner from Host params

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ares — APPROVED** [review]
Thanks @stejskalleos, APJ

**Comment by timogoebel** [comment]
What if I want the new hosts to be owned by, let's say, a group?

**Comment by stejskalleos** [comment]
> What if I want the new hosts to be owned by, let's say, a group?

Well for now we don't want to allow user to set `@host.owner` at all.

**Comment by ekohl** [comment]
> Well for now we don't want to allow user to set `@host.owner` at all.

One possible use case that you would want this is groups (as @timogoebel mentioned). Then https://github.com/theforeman/foreman/blob/develop/app/views/unattended/provisioning_templates/snippet/create_users.erb can use this to create all users from that group with their SSH key.

**Comment by ares** [comment]
Owner can only be setup through `owner_id` and `owner_type` I believe. `owner` is a polymorphic relation and I don't think can be set through API parameter. While I understand there is potentially a use case, this PR (and redmine issue) is about dropping this useless parameter from the whitelist. Please open a separate RFE for that, if you think it should be added. That however consists of more steps

1) make sure the user is member of that group and has view permission on it
2) make sure user is associated to the same orgs/locs or enforce organization_id/location_id parameters to be of his scope
3) include the linked snippet into the registration template, probably disabled by some parameter by default

Given we don't include this snippet today anywhere in default templates, I think this is quite rare. I think people use some advanced cfgmgmt to configure user accounts on hosts instead of Foreman host ownership feature.

Anyway, this PR solves the issue, Merging, thanks @stejskalleos for quick fix!

**Pull request merged**
