### PR TITLE
Fixes #21012 - taxonomies API to show hosts associated with it

### PR DESCRIPTION
**Pull request by snagoor**
Taxonomies API would be consistent with the other items (such as subnets, users etc) in the rendered result

~~~
# curl -k -s -u admin:changeme https://$(hostname -f)/api/v2/locations/2/ | json_reformat
{
    "select_all_types": [
        "ProvisioningTemplate",
        "Hostgroup"
    ],
    "description": null,
    "created_at": "2017-06-12 15:39:01 UTC",
    "updated_at": "2017-06-12 15:39:01 UTC",
    "ancestry": null,
    "parent_id": null,
    "parent_name": null,
    "id": 2,
    "name": "Default Location",
    "title": "Default Location",
    "hosts": [
        {
            "name": "virt-who-esxi5-1.example.com-1",
            "id": 10
        },
        {
            "name": "virt-who-esxi-2.example.com-1",
            "id": 9
        },
        {
            "name": "server.example.com",
            "id": 4
        },
        {
            "name": "rhel70.lab.example.com",
            "id": 8
        },
        {
            "name": "rhel7ws.example.com",
            "id": 6
        },
        {
            "name": "client.example.com",
            "id": 5
        }
    ],
    "users": [
        {
            "id": 5,
            "login": "test",
            "description": ""
        }
    ],
    "smart_proxies": [
        {
            "name": "foreman-devel.example.com",
            "id": 1,
            "url": "https://foreman-devel.example.com:9090"
        }
    ],
    "subnets": [
        {
            "id": 1,
            "name": "vagrant-domain",
            "description": "",
            "network_address": "192.168.123.0/24"
        }
    ],
    "compute_resources": [

    ],
    "media": [

    ],
    "config_templates": [

    ],
    "ptables": [

    ],
    "provisioning_templates": [

    ],
    "domains": [

    ],
    "realms": [

    ],
    "environments": [
        {
            "name": "KT_Default_Organization_Library_PuppetCV_4",
            "id": 2
        }
    ],
    "hostgroups": [
        {
            "id": 1,
            "name": "HG1",
            "title": "HG1",
            "description": ""
        },
        {
            "id": 2,
            "name": "HG2",
            "title": "HG2",
            "description": ""
        }
    ],
    "organizations": [
        {
            "id": 1,
            "name": "Default Organization",
            "title": "Default Organization",
            "description": null
        }
    ],
    "parameters": [

    ]
}
~~~

### CODE REVIEW

**Comment by xprazak2** [comment]
Works nicely, could you pls make a change in a [test](https://github.com/theforeman/foreman/blob/develop/test/controllers/api/v2/locations_controller_test.rb#L15) as well?

**Comment by xprazak2** [comment]
LGTM, thanks.

**Comment by iNecas** [comment]
With large amounts of hosts (there are known 20k+ deployments), this can be pretty inefficient to render all hosts: the issue itself is requesting just a number, not the list itself. For this case, I would rather suggest using the number, than the rendering of the items. The host search can be used for that, if needed (which involves the pagination).

**Comment by snagoor** [comment]
@iNecas, thanks modified my commit to show just the count of the Hosts, based on taxonomies.

Snip of the API request
~~~
   "hosts_count": 8,
    "parameters": [
    ]
}
~~~

**Review by tbrisker — APPROVED** [review]
LGTM, thanks @snagoor !

**Pull request merged**
