### PR TITLE
Fixes #29881 - Require only used rss modules

### PR DESCRIPTION
**Pull request by tbrisker**
Before:
```
  /home/tbrisker/foreman/app/services/ui_notifications/rss_notifications_checker: 22.9453 MiB
    rss: 22.9453 MiB
      rss/maker: 10.0547 MiB
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/dublincore: 4.8984 MiB (Also required by: /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/taxonomy, /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/image)
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/1.0: 1.2891 MiB (Also required by: /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/content, /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/dublincore, and 5 others)
          /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/base: 1.2891 MiB (Also required by: /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/0.9, /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/atom)
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/image: 1.2891 MiB
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/taxonomy: 1.0313 MiB
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/maker/itunes: 0.5156 MiB
      rss/2.0: 4.125 MiB (Also required by: rss/content/2.0, rss/dublincore/2.0, and 2 others)
        rss/0.9: 3.0938 MiB
      rss/1.0: 3.3516 MiB (Also required by: rss/content/1.0, rss/dublincore/1.0, and 5 others)
        /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/parser: 1.5469 MiB (Also required by: rss/0.9, rss/atom)
          /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/rss: 0.5156 MiB (Also required by: rss/content, rss/dublincore, and 2 others)
      rss/image: 1.2891 MiB
      rss/itunes: 1.2891 MiB
      rss/taxonomy: 1.2891 MiB
      rss/atom: 0.5156 MiB
      rss/trackback: 0.5156 MiB
```

After:
```
  /home/tbrisker/foreman/app/services/ui_notifications/rss_notifications_checker: 7.4766 MiB
    rss/atom: 5.6719 MiB
    rss/parser: 1.8047 MiB
      /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/rss: 0.7734 MiB
```

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]

**Comment by ekohl** [comment]
Btw, this does suggest we can only parse atom feeds after this and not 2.0, 1.0 or 0.9 feeds. Is that correct?

**Comment by tbrisker** [comment]
> Btw, this does suggest we can only parse atom feeds after this and not 2.0, 1.0 or 0.9 feeds. Is that correct?

correct, that is the feed format we are using on the foreman website. Other feeds might require other formats to be required - i'll try to see how much including them affects the memory usage.

**Comment by ekohl** [comment]
I wonder if it makes sense to have fallback code where you load if it it can't be parsed. Realistically you're only going to see the RSS feeds in the dynflow worker or a rake task.

**Comment by ekohl** [comment]
> Other feeds might require other formats to be required

We know RH has its own RSS feed. Perhaps ATIX also has one. Worth to check what's used besides theforeman.org. Perhaps the whole world is on atom anyway.

**Comment by tbrisker** [comment]
Good point, looks like RH is using RSS 2.0. Adding back 2.0 and 1.0 just in case, doesn't lead to too much more memory usage, still a 10MB reduction: 
```
  /home/tbrisker/foreman/app/services/ui_notifications/rss_notifications_checker: 12.8906 MiB
    rss/atom: 5.6719 MiB
    rss/2.0: 4.125 MiB
      rss/0.9: 2.8359 MiB
    rss/parser: 1.5469 MiB
      /home/tbrisker/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rss/rss: 0.7734 MiB
    rss/1.0: 1.5469 MiB

**Review by lzap — APPROVED** [review]
LGTM

**Pull request merged**
