### PR TITLE
fixes #12791 - add boot_files_uri for SUSE

### PR DESCRIPTION
**Pull request by mmoll**
to be used together with mmoll/community-templates@6c9a9ea

### CODE REVIEW

**Comment by mmoll** [comment]
actually also doesn't work with safemode on.

**Comment by mmoll** [comment]
[test] and reopen, as Debian iPXE also fails with safemode on with the same message:
`There was an error rendering the Preseed default iPXE template: Safemode doesn't allow to access 'to_ary' on @host.to_jail.operatingsystem.to_jail.boot_files_uri(@host.to_jail.medium, @host.to_jail.architecture)`

**Comment by domcleal** [comment]
`to_ary`'s used when you do this style of variable assignment: `a, b = returns_array`, so splitting it up into an assignment of the return value and then accessing the array elements will work around it.  I think that might be a problem in safemode that we can't simply fix by creating a Jail.

You'll probably also need to add boot_files_uri to Jails inside the OS subclasses to make this work fully, and add :medium to Host::Managed::Jail.

Lastly, could you use a new ticket for this, or change it to fixes #12791?

**Comment by mmoll** [comment]
Thanks Dominic, together with mmoll/community-templates@6c9a9ea this seems to allow to render iPXE templates for autoyast, kickstart and preseed with safe_mode enabled.

**Comment by domcleal** [comment]
Merged as 1c81a69, thanks @mmoll.

**Pull request closed without merging**
