### PR TITLE
First support of chefproxy on Foreman

### PR DESCRIPTION
**Pull request by rvrignaud**
Based on @ares commits.

Related to theforeman/smart-proxy#112

@ohadlevy, @ares, @GregSutcliffe : thoughts, remarks ?

### CODE REVIEW

**Comment by rvrignaud** [comment]
I wanted to remove all kind of ambiguity if  we ever have another chef related feature on smart-proxy

**Comment by ohadlevy** [comment]
@rvrignaud ok.. maybe chef_feature? like we have puppet_ca etc?

**Comment by ares** [comment]
I just rebased https://github.com/theforeman/foreman/pull/968 so you may need to rebase onto it as well. Let me know if you have any questions.

**Comment by ohadlevy** [comment]
@rvrignaud @ares ping ?

**Comment by ares** [comment]
#968 is merged already. @rvrignaud could you please look at failing tests?

**Comment by domcleal** [comment]
Note that since the seed change was merged, you should now just add a line to db/seeds.rb instead of using a migration.

**Comment by domcleal** [comment]
Thanks for the patch @rvrignaud, merged as bb8da765 for Foreman 1.4.0.

**Pull request closed without merging**
