### PR TITLE
Fixes #18688 - pin sass-loader to version supporting webpack 1

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by mmoll** [comment]
@matanwerbner could you have a look here? This would unbreak at least a part of the currently failing package builds.

**Comment by matanwerbner** [comment]
Everything works as expected

**Comment by ares** [comment]
Works for me too, since it was approved by @matanwerbner I'll merge it.

**Comment by ares** [comment]
Thanks @tbrisker, merged as 147aa4e5b5ab64dcb3b2bd9761fecd708744288e

**Pull request closed without merging**
