### PR TITLE
Fixes #37248 - make hostsIndexContext a singleton

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Review by jeremylenz — DISMISSED** [review]
Works, nice find @MariaAga :)

needs eslint --fix

**Review by ofedoren — COMMENTED** [review]
Lint failures :/

**Comment by MariaAga** [comment]
Thanks both :) fixed!

**Comment by jeremylenz** [comment]
Needs a rebase to fix the unrelated failures

**Review by jeremylenz — APPROVED** [review]

**Pull request merged**
