### PR TITLE
Fixes #23295 - Robottelo tests reporting

### PR DESCRIPTION
**Pull request by ldjebran**
Enable to make test results xml reports compatible the ones created with robottelo pytest + https://github.com/SatelliteQE/betelgeuse  for Polarion reporting.
+ one module tests with tests attributes.

Part of robottelo minitest port project https://github.com/SatelliteQE/robottelo/projects/1.

To generate the robottelo report we need to "export GENERATE_ROBOTTELO_REPORT="true"

### CODE REVIEW

**Comment by ares** [comment]
ok to test

**Comment by tbrisker** [comment]
@ldjebran if you confirm the invitation to join the foreman github organization and make your membership public, tests will be triggered automatically.

**Comment by ldjebran** [comment]
rebased

**Comment by mmoll** [comment]
@ldjebran this needs another rebase :)

**Comment by ldjebran** [comment]
rebased

**Comment by omaciel** [comment]
@ares can we get this PR merged soon please?

**Comment by ares** [comment]
weird, I don't see how the test failures would be caused by this change, let me rerun tests, meanwhile I'll read through the robottelo_reporting gem [test foreman]

**Review by ares — APPROVED** [review]
Ok, tests now fail on single combination and don't seem to be related to the change in any way. Merging, thanks @ldjebran.

**Comment by lzap** [comment]
Sorry to be late in the party, but I don't think that adding random UUIDs across our codebase has been reasoned in this pull request or ticket. We should do maximum to avoid such things and I believe these can be generated automatically from test names. I suggest to refactor the minitest plugin in order to allow such an integration. Started discussion at: https://community.theforeman.org/t/on-uuids-in-tests/10347 because this is now spread across dozen of other PRs.

**Pull request merged**
