### PR TITLE
fixes #15651 - validate compute_profile name

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by timogoebel** [comment]
@anandkumaragrawal: Why would you want to limit the compute profile name?

**Comment by anandkumaragrawal** [comment]
Compute profile name is the name given to the profile (eg: large, small) and it should be meaningful. $$$ does not specify any name. Regarding utf characters, i have taken it in consideration.

**Comment by domcleal** [comment]
It's not Foreman's responsibility to determine what is or isn't a "meaningful" name from the user, as it will simply be error prone and open to a lot of interpretation (been through lots of this, and we have reverted many of these changes).  If the name isn't meaningful, don't enter it.

Validations should only require that names are present, within the field lengths, will not trigger other unfixable bugs in UI/API handling, and comply with any relevant RFCs or standards.

**Comment by timogoebel** [comment]
@anandkumaragrawal: I just typed something similar to @domcleal . I think, we should not merge this. Let me know if you disagree.

**Comment by dLobatog** [comment]
@anandkumaragrawal Sorry I'll close this off for the moment. Please reopen if you think this should be reconsidered and explain why, but generally we will make validations just to ensure input data is not dangerous or difficult to work with. Determining whether some name makes sense or not isn't really Foreman's responsibility. Thanks for the effort when making the patch though, I appreciate it.

**Pull request closed without merging**
