### PR TITLE
Fixes #24125 - Show error when libvirt not reachable

### PR DESCRIPTION
**Pull request by xprazak2**
(cherry picked from commit 91b8eed6b2b2869e760183a629a50bf0046448aa)

### CODE REVIEW

**Comment by tbrisker** [comment]
`test_develop` is failing after this change, investigating

**Comment by tbrisker** [comment]
Looks like 1.18 is also failing with the same error (and another one for related to this change)

**Comment by ares** [comment]
so, should we merge this (as the failure is unrelated) so that we don't forget, once tests are fixed?

**Comment by tbrisker** [comment]
One of the failures is related, Api::V2::ComputeAttributesControllerTest.test_0001_should create compute attribute

**Comment by tbrisker** [comment]
@xprazak2 shall we push this one out to 1.18.1 so we figure out the issues?

**Comment by xprazak2** [comment]
Yes, moving to 1.18.1.

**Comment by xprazak2** [comment]
I added another cherry-picked commit that hopefully fixes tests.

**Comment by tbrisker** [comment]
looks like test failure is still related.

**Review by tbrisker — APPROVED** [review]
Looks like it worked.

**Pull request merged**
