### PR TITLE
fixes #2588 - fixed regression introrduced earlier: localization works for non-AR classes too now

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
@domcleal, @ohadlevy ping

**Comment by domcleal** [comment]
@witlessbird I do get GitHub notifications, thanks ;)

**Comment by domcleal** [comment]
This looks correct, but would it be easy to write a test for this helper method?  I'm a bit sad that we've had to fix it so many times now.

It should cope with:
1. nil objects
2. non-AR objects
3. AR objects

**Comment by dmitri-d** [comment]
I could add the tests; my reasoning for not adding them was the permanent fix in upstream does come with tests...

**Comment by domcleal** [comment]
Good point, could you file an issue please to remind us to update gettext_i18n_rails?

Merged as b08d7e4.  Thanks!

**Pull request closed without merging**
