### PR TITLE
2 fixes in partition tables model & api

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by ohadlevy** [comment]
merged - thanks

**Comment by ohadlevy** [comment]
I've reverted this as it broke tests http://ci.theforeman.org/job/test_develop/231/console.

I'll try to look into the details later.

**Comment by ohadlevy** [comment]
@tstrachota ping ?

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
See the merge status link at the top, there are migration errors around ptable and os_family.

**Comment by lzap** [comment]
@tstrachota can you please review & rebase? ^^

**Comment by tstrachota** [comment]
Closing. Will open a new one.

**Pull request closed without merging**
