### PR TITLE
Fix menu remove2

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Comment by sseago** [comment]
This PR relates to https://github.com/theforeman/foreman/issues/1496

**Comment by domcleal** [comment]
PRs must always be targeted against develop, unless you're backporting a fix that's already in develop.  Please re-open a PR for develop, thanks.  If you would like a fix in 1.5-stable, mention it and we'll target the bug there, but develop comes first.

**Comment by sseago** [comment]
Sure, no problem -- re-opening on develop.

**Comment by domcleal** [comment]
#1499

**Pull request closed without merging**
