### PR TITLE
Fixes #7458 - allow searching hosts by their ip and mac addresses

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm this works, but I dont like non intuitive names `has_something`. Can't we just rename the original fields to `primary_ip/primary_mac` and name the new ones as `ip/mac`? This will not break compatibility because I just tested that the new field works for both primary and additional interfaces. Therefore searching will not be changed.

Since these are critical fields for provisioning, can you please add two tests for these?

**Comment by ares** [comment]
@lzap while I agree that renaming older names would be nicer, I don't agree that it wouldn't break compatibility. Note that new `has_ip` and `has_mac` can find more hosts, so if you have a bookmark or permission filter saying `ip ~ 192.168.*` that it can find more hosts... But if we agree on just documenting this at release notes, I'm fine with changing it.

What exactly do you want me to test here?

**Comment by lzap** [comment]
I agree. @eLobato what you think?

I was hoping for a regression prevention test, but I don't insist. We already have few basic search tests.

**Comment by ares** [comment]
Such tests sounds like testing the scoped_search functionality, I don't see much value in adding tests for this PR.

**Comment by dLobatog** [comment]
We could possibly test just the inclusion of the 'scoped_search' lines, but I can't see an easy way of doing that so :+1: to what @ares  said. 

@lzap I also think renaming to primary_ip/_mac would be nice but I'm afraid it might start breaking things. Is there a ticket for that? In my opinion we can get this search in the meantime & worry about the rename later.

**Comment by dLobatog** [comment]
Merged as 0c0d4e22415a4e7ac1ad2d85e32e5d919c3bd2e7, thanks @ares!

**Comment by lzap** [comment]
This is so confusing, we will never get to rename. I'd rather do it now (right after 1.8 release) than later.

**Pull request closed without merging**
