### PR TITLE
Fixes #19875 - Disable Style/MultipleComparison cop 

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
rebased

**Comment by ares** [comment]
I'm missing a smile for I don't have strong opinion :-) giving this didn't get to many :+1: I'd consider disabling though.

**Comment by mmoll** [comment]
disabled that cop

**Comment by mmoll** [comment]
anybody?

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Danke, @mmoll.

**Pull request merged**
