### PR TITLE
Fixes #31689 - Handle vertical drag & drop

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
The tests are failing on current tests and I'm wondering if we should add one for the horizontal?
I'm ok to test manually and merge without it, if we have test of drag on the component, that will be using it if you think it's better.

**Comment by ezr-ondrej** [comment]
[test katello] seems broken once again

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by xprazak2** [comment]
I do not thing this will have impact on katello as changes are limited to one component and are backwards compatible.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @xprazak2 ! :+1:

**Pull request merged**
