### PR TITLE
Refs #25217 - Add prop-types to the BreadcrumbBar

### PR DESCRIPTION
**Pull request by sharvit**
Adds relevant missing prop-types and default-props to the BreadcrumbBar

### CODE REVIEW

**Comment by ohadlevy** [comment]
@amirfefer can you review please?

**Review by amirfefer — APPROVED** [review]
Thanks @sharvit  :+1:

**Review by amirfefer — CHANGES_REQUESTED** [review]
This needs a rebase

**Review by ohadlevy — DISMISSED** [review]

**Comment by ohadlevy** [comment]
@sharvit can you rebase please?

**Comment by sharvit** [comment]
Rebased

**Review by amirfefer — APPROVED** [review]
LGTM :+1: 

Thanks @sharvit

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
