### PR TITLE
Fixes #20676 - relabel new button for autosign entry

### PR DESCRIPTION
**Pull request by ares**
before
before3
after
after4

### CODE REVIEW

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @ares

**Comment by ohadlevy** [comment]
@dLobatog doesnt that conflict with your  #4703 ?

**Comment by dLobatog** [comment]
@ohadlevy I think the disagreement there is about SSH keys, Autosign entries are created both in Foreman and the proxy. If I'm not wrong the discussion is about using "Add" for things that already exist, like SSH keys - creating an SSH key in Foreman does not actually create one using `openssl` or anything like that.

**Comment by ares** [comment]
Thanks for merging @dLobatog, I set a release in redmine to 1.16.0, please don't forget to set it after merge.

**Comment by dLobatog** [comment]
@ares Thanks - I revise daily http://projects.theforeman.org/projects/foreman/activity and set the release of anything that's 'Closed' then, that's why sometimes it's not done right after merge.

**Comment by ares** [comment]
Ok, in your case I'll just set it without reminding you if I see unassigned issue before you get to it, so I can delete the redmine notification. Sorry for bothering... I'm inbox driven :-)

**Pull request merged**
