### PR TITLE
Fixes #25355 - Remove HomeHelper

### PR DESCRIPTION
**Pull request by tbrisker**
It is no longer used - logic for menu display has moved to react and
menu classes.

### CODE REVIEW

**Comment by timogoebel** [comment]
This needs Katello/katello#7797.

**Comment by timogoebel** [comment]
This needs Katello/katello#7797.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
[test foreman]
[test katello]

**Comment by tbrisker** [comment]
Katello side has been merged and green now.

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
