### PR TITLE
Fixes #19766 - Disable Layout/AlignParameters cop 

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Do you want this PR get merged and thus this cop enabled? React :+1:
Do you want this cop to be disabled? React :-1:

**Review by dLobatog — DISMISSED** [review]

**Comment by tbrisker** [comment]
Looks like no consensus here, let's disable it.

**Comment by mmoll** [comment]
sure, updated

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
