### PR TITLE
fixes #10989 - removing 1.12 deprecations

### PR DESCRIPTION
**Pull request by unorthodoxgeek**

### CODE REVIEW

**Comment by domcleal** [comment]
Please wait until 1.11-stable is branched before doing this, see the ticket intro.

**Comment by dLobatog** [comment]
1.11-stable is branched - https://github.com/theforeman/foreman/tree/1.11-stable

**Comment by domcleal** [comment]
The Host#model_name getters/setters should be removed too.

**Comment by unorthodoxgeek** [comment]
@domcleal - done

**Comment by domcleal** [comment]
Merged as e2dd3c6, thanks @unorthodoxgeek.

**Pull request closed without merging**
