### PR TITLE
1009560 - do not treat `params[:dryrun]` with value `false` as true

### PR DESCRIPTION
**Pull request by pitr-ch**

### CODE REVIEW

**Comment by pitr-ch** [comment]
@domcleal ack?

**Comment by domcleal** [comment]
Could you file a redmine ticket for the issue please?

I'm not sure I see how this is happening - aren't params always strings?  Is apipie applying some magic?

**Comment by pitr-ch** [comment]
sure, http://projects.theforeman.org/issues/3577. That is true for params coming from url (GET) or forms (usual POST), but I think that in this case params are send as JSON so type for booleans and numbers isn't lost.

And I just noticed that I've opened 1000th pull-request :fireworks: :)

**Comment by isratrade** [comment]
I also thought all url params with strings.  @pitr-ch.  I still don't understand what is "in this case params are send as JSON", since the route is post :import_puppetclasses and the I don't see where params['dryrun']  is converted to JSON.

**Comment by domcleal** [comment]
@isratrade if the content-type was set to application/json and a hash is sent as the body of the request then it should get parsed into the params hash (as if you were creating a resource via the API).  I hadn't realised this meant we had non-string objects though, so one to remember...

**Comment by isratrade** [comment]
@domcleal, good to know.  thanks @pitr-ch

**Comment by domcleal** [comment]
Thanks @pitr-ch, merged as b1f7f9700 for Foreman 1.4.0.

**Comment by pitr-ch** [comment]
Thanks for the quick response :)

**Pull request closed without merging**
