### PR TITLE
Fixes #28724: Convert all Storybook stories to Component Story Format

### PR DESCRIPTION
**Pull request by jeremylenz**
[Component Story Format info](https://storybook.js.org/docs/formats/component-story-format/)

This PR converts all existing Storybook stories.

### CODE REVIEW

**Comment by xprazak2** [comment]
Probably unrelated to the changes, I am getting the following for `npm run stories`: 

no-enzyme

There are also linting errors.

**Comment by jeremylenz** [comment]
Linting issues addressed; removing [WIP]

**Comment by xprazak2** [comment]
Still getting an error, though a different one this time:

story-struct

**Comment by jeremylenz** [comment]
@xprazak2 I think it's related to moving lots of dependencies out of Foreman into foreman-js (not related to this PR).  To get rid of it I had to `rm -rf node_modules` and also `rm package-lock.json`

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Ah, removing package-lock.json helped, I should have thought of that. Thanks!

FactChartModal does not display, but it is unrelated to the changes so I created a separate [issue](https://projects.theforeman.org/issues/28753)

**Pull request merged**
