### PR TITLE
Fixes #20528 - Remove direct connection to rbovirt client

### PR DESCRIPTION
**Pull request by orrabin**
This depends on: https://github.com/fog/fog-ovirt/pull/3 and a new version of fog that connects to fog-ovirt.
Putting this on WoC until it can be reviewed without changing fog versions locally.

### CODE REVIEW

**Comment by iNecas** [comment]
Tested and works well. I've already merged the fog-ovirt. Let's release a new gem and bump dependency as part of this PR, just to not forget about that once fog gets released.

**Comment by iNecas** [comment]
It seems that the fog, as well as fog-ovirt was updated. Let's bump the fog and fog-ovirt dependencies and merge this one after that.

**Comment by mmoll** [comment]
I think the lower version boundaries would need to get updated in `bundler.d/fog.rb` and `bundler.d/ovirt.rb` with this PR.

**Comment by iNecas** [comment]
Yes, that's what I meant

**Comment by orrabin** [comment]
I changed the version in `bundler.d/fog.rb`.
This pr removes `rbovirt_client` but we still have a connection to the gem so I left `bundler.d/ovirt.rb` as is for now.

**Comment by orrabin** [comment]
I changed the version in `bundler.d/fog.rb` and updated `bundler.d/ovirt.rb` to include `fog-ovirt` instead of `rbovirt` to remove the direct connection to the rbovrit gem.

**Comment by iNecas** [comment]
The problem with the tests is, there is nowhere `require 'rbovit'` in the code, so it doesn't know, how to deal with `OVIRT` constant, and Rails think it should be defined in `app/models/compute_resources/foreman/model/ovirt.rb`, which it obviously is not. The solution should be putting `require 'rbovirt'` somewhere into the fog-ovirt, probably here https://github.com/fog/fog-ovirt/blob/1e47afcff5293a963fbda1e4217e7a19f68a4b21/lib/fog/ovirt/core.rb#L2

**Comment by orrabin** [comment]
@iNecas thanks, I added: https://github.com/fog/fog-ovirt/pull/4.
Keeping this on WoC until it's merged and a new gem is released.

**Comment by mmoll** [comment]
What's the status here? This needs a rebase...

**Comment by orrabin** [comment]
@mmoll I rebased, this needs a new version of fog-ovirt, there is one more issue I'd like to merge there before releasing a new version.

**Comment by orrabin** [comment]
@iNecas I released a new version of fog-ovirt, this is now ready to test.

**Comment by iNecas** [comment]
Tested and works well. Thanks @orrabin

**Review by iNecas — APPROVED** [review]

**Pull request merged**
