### PR TITLE
Fixes #28874 - set/get eager zero flag

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
@chris1984 Can you have a look if this is a better solution than https://github.com/theforeman/foreman/pull/7634 ?

**Comment by chris1984** [comment]
I do like it better in the JS part of the code, @ezr-ondrej since you do more on the JS/UI side your thoughts instead of https://github.com/theforeman/foreman/pull/7634

**Comment by sbernhard** [comment]
The PR https://github.com/fog/fog-vsphere/pull/252 in fog-vsphere is still required.

**Review by ezr-ondrej — CHANGES_REQUESTED** [review]
Thanks for figuring out the issue here! Looks like the right approach, just note on the casing (note I agree it's very confusing, but it is what it is)
We should use `eagerZero` instead in the front end.
- on submit we run https://github.com/theforeman/foreman/blob/0334a1e09c3cf556540278ad920df5d2d074ce7f/app/controllers/concerns/foreman/controller/normalize_scsi_attributes.rb#L8
- on edit, it will become `eagerZero` for the react component prop because of https://github.com/theforeman/foreman/blob/0334a1e09c3cf556540278ad920df5d2d074ce7f/app/views/compute_resources_vms/form/vmware/_base.html.erb#L63
  plus points if you manage to `s/:Size/:size/` there xD

**Comment by ezr-ondrej** [comment]
Should we also add `to_bool(vol['eager_zero'])` in `normalize_attributes`?
https://github.com/theforeman/foreman/blob/0334a1e09c3cf556540278ad920df5d2d074ce7f/app/models/compute_resources/foreman/model/vmware.rb#L702

**Comment by sbernhard** [comment]
As it is pretty hard for me (=no test environment on which I can directly change the code) to work on this PR, I'm happy that someone (@ezr-ondrej) continues. Would this be possible?

**Comment by ezr-ondrej** [comment]
> As it is pretty hard for me (=no test environment on which I can directly change the code) to work on this PR, I'm happy that someone (@ezr-ondrej) continues. Would this be possible?

Sure, I can take it over. Thanks a lot @sbernhard

**Comment by tbrisker** [comment]
closing in favor of GH-7650

**Pull request closed without merging**
