### PR TITLE
fixes to make an ESXi server appear in the UI without errors

### PR DESCRIPTION
**Pull request by pccowboy**
I am working with libvirt, and using ESXi in our datacenter.  These changes allow the UI to come up, at least if libvirt can authenticate to the ESXi host (I currently have the authentication hardcoded).

More work to come...

### CODE REVIEW

**Comment by ohadlevy** [comment]
thanks! just merged

**Comment by ohadlevy** [comment]
sadly i had to revert that commit, as it broke the generated urls
I'm guessing it also needed some modifications in virt, so if we can get all mods as one, I would be happy to re merge it.

Thanks..

**Comment by pccowboy** [comment]
Sorry about that - How is best to bundle the changes?

The head of my virt and foreman branches work at this point, although there are additions I would like to make for the URL generation still.

On that note, I would like to suggest using the libvirt UUID for the URL, instead of the name or the ID.  My reasons are:
1.  Names can be duplicated within a hypervisor
2.  IDs only exist for running guests
3.  UUID is guaranteed to be unique within a hypervisor

How does that sound to you?

**Comment by ohadlevy** [comment]
uuid sounds good way forward :-)

**Pull request closed without merging**
