### PR TITLE
Fixes #22990 - Port robottelo tier1 compute resources

### PR DESCRIPTION
**Pull request by odovzhenko**
Redmine issue: http://projects.theforeman.org/issues/22990

Port robottelo tier1 tests for environment part of robottelo minitest port project https://github.com/SatelliteQE/robottelo/projects/1

Related Robottelo issue: SatelliteQE/robottelo#5844

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Review by tbrisker — CHANGES_REQUESTED** [review]
@odovzhenko looks like one test is failing, can you take a look - `Models::OvirtTest.test_0002_accepts multiple certificates`

**Comment by mmoll** [comment]
> Models::OvirtTest.test_0002_accepts multiple certificates

this got fixed in develop, so it's unrelated

**Review by tbrisker — APPROVED** [review]
LGTM, thanks @odovzhenko !

**Pull request merged**
