### PR TITLE
fixes #11577 - Add additional volume to Openstack

### PR DESCRIPTION
**Pull request by amosin**
When creating a new virtual machine using OpenStack compute resource we wanted to be able to add a second volume to it "/dev/vdb" in addition to the boot volume. The second volume will only be created in case the size value is > 0.

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
@amosin Thanks for the patch! I was just testing it, it works well. There are a couple of issues with it in my opinion though:
1. It's not intuitive (at least not without reading the Redmine issue :smile: ), that a second boot device won't be created if size is 0.
2. It's very different from other compute resources. Other compute resources like oVirt or Libvirt allow you to create and attach as many disks as needed.
3. It doesn't have any tests.

This is how other compute resources look like when they have support for multiple storage disks.
screenshot from 2015-08-28 17-31-07

Do you think you could update your pull request with something like that? You can find the html.erb templates on  `app/views/compute_resources_vms/form/`. The issue in the Redmine tracker would probably have to change, we had [this one](http://projects.theforeman.org/issues/4521) in the past but chose to rename it and merge just the booting volume part because the rest was not completed.

Let us know if you can continue with this one, or if you need any help!

**Comment by shlomizadok** [comment]
@amosin - any news on this patch?

**Comment by amosin** [comment]
Hi, I haven't had time to work on this patch lately. I tried to make the storage interface look like the other compute resources. I was having hard time getting the array of hashes from the UI, for some reason it was only getting the last entered storage. Thanks!

**Pull request closed without merging**
