### PR TITLE
Fixes #13084 - compute resource IP validation fixed

### PR DESCRIPTION
**Pull request by lzap**
I tested this only with OpenStack.

### CODE REVIEW

**Comment by domcleal** [comment]
This change is missing a unit test, please add one/some.

**Comment by mmoll** [comment]
seems to fix this problem on EC2 for me

**Comment by domcleal** [comment]
Please note that this has been on the 1.11 blocker list, and should probably be fixed in time for RC1.  Please address the feedback given above.

**Comment by lzap** [comment]
Added new set of tests. To be honest, I am not sure what other attributes than `mac` or `ip` do we expect, but I added a generic test for that. Do you have an example? If this needs some more work, please ping me on IRC as I am a bit busy after the week off.

**Comment by domcleal** [comment]
Merged as d5b5059, thanks @lzap.

**Pull request closed without merging**
