### PR TITLE
fixes #24673 - compute resource vm tab loading

### PR DESCRIPTION
**Pull request by plessbd**
Fixes an issue loading vm tabs on compute resoruce

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by xprazak2** [comment]
[test upgrade]

**Comment by plessbd** [comment]
these errors dont seem to be related to my change, but If someone can help me figure out if they are and how to fix them I would be happy to do it.

**Review by xprazak2 — APPROVED** [review]
The test failures are not related to the changes, they are known for failing from time to time. I tested, the vms now load for me.

**Comment by xprazak2** [comment]
Thanks!

**Comment by tbrisker** [comment]
Cherry-picked to 1.19 as 936943637

**Pull request merged**
