### PR TITLE
Fixes #36923 - Navigation search menu should be less wide

### PR DESCRIPTION
**Pull request by MariaAga**
Making it so it has some space on the right side of the menu
Before /after:
Screenshot from 2023-11-16 12-59-50 Screenshot from 2023-11-16 12-54-07

### CODE REVIEW

**Review by kmalyjur — APPROVED** [review]
Looks great! The only thing is that when the scrollbar is present, the arrows in the menu slightly shift to the left, and the end of the search field could shift, too, but I don't think it's necessary at all.

image

**Review by ekohl — APPROVED** [review]
I don't mind merging with @kmalyjur's approval, but because there's a question: @MariaAga do you want to address that? Otherwise feel free to merge yourself.

**Comment by MariaAga** [comment]
Since the scroll bar is more part of the browser then the navigation, and more complicated to fix, I rather leave it like this for now. Thanks!

**Comment by pnovotny** [comment]
LGTM, tested on Sat. stream w/ this PR build.
menu-search-width-fixed

**Pull request merged**
