### PR TITLE
Fixes #20763 - Reword "Create SSH key" to "Add SSH key"

### PR DESCRIPTION
**Pull request by bastilian**
Add Button and page to add the key:

gnome-shell-screenshot-6y8s5y

gnome-shell-screenshot-0zo35y

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM

**Comment by iNecas** [comment]
Should we also change the wording in the API docs? https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v2/ssh_keys_controller.rb#L34

**Comment by bastilian** [comment]
@iNecas yeah, i think that make sense. Will change that. Not sure if renaming the attribute would make sense too, keeping in mind to keep backwards compatibility.

**Comment by bastilian** [comment]
@iNecas changed it now too.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Merged, thanks @bastilian.

**Pull request merged**
