### PR TITLE
fixes #5018 - pin rbvmomi gem to the rbvmomi version in fog gem

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
@shlomizadok Thanks, why not removing the pin as specified in the Redmine issue?

**Comment by shlomizadok** [comment]
@eLobato  - Thanks for reviewing. I generally took Dominic's advise from https://github.com/theforeman/foreman/pull/1784#issuecomment-59483329 and try to keep our gems to semver major version for compatibility purposes.

**Comment by dLobatog** [comment]
@shlomizadok ~~In that case, please pin to the major version :smile: , currently it's pinned to a minor version, 1.8.~~ <- dumb

**Comment by domcleal** [comment]
@eLobato I think it's correct... 1.8 means >= 1.8, but <= 2.0.

**Comment by dLobatog** [comment]
Merged as 84347e482d34fba5f4f63f31e60a48492036f707 , thanks @shlomizadok ! :wine_glass:

**Pull request closed without merging**
