### PR TITLE
Fixes #23840 - Host Class Changes With Managed State

### PR DESCRIPTION
**Pull request by akshay-mendhe**
Fixes #23840 - Host Class Does not Change With Managed State

### CODE REVIEW

**Review by akofink — CHANGES_REQUESTED** [review]
It doesn't seem to fix the issue on new Host object:

```rb
[1] pry(main)> h=Host.new
2018-08-31T14:08:33 [D|app|] Generated new randomized name generator register: 16751599
=> #<Host::Managed:0x000000000d23a660
 id: nil,
 name: "duane-osoria",
 last_compile: nil,
 last_report: nil,
 updated_at: nil,
 created_at: nil,
 root_pass: nil,
 architecture_id: nil,
 operatingsystem_id: nil,
 environment_id: nil,
 ptable_id: nil,
 medium_id: nil,
 build: false,
 comment: nil,
 disk: nil,
 installed_at: nil,
 model_id: nil,
 hostgroup_id: nil,
 owner_id: nil,
 owner_type: nil,
 enabled: true,
 puppet_ca_proxy_id: nil,
 managed: false,
 use_image: nil,
 image_file: nil,
 uuid: nil,
 compute_resource_id: nil,
 puppet_proxy_id: nil,
 certname: nil,
 image_id: nil,
 organization_id: nil,
 location_id: nil,
 type: "Host::Managed",
 otp: nil,
 realm_id: nil,
 compute_profile_id: nil,
 provision_method: nil,
 grub_pass: "",
 global_status: 0,
 lookup_value_matcher: nil,
 pxe_loader: nil,
 initiated_at: nil,
 build_errors: nil>
[2] pry(main)> h.managed?
=> false
```

**Comment by akshay-mendhe** [comment]
I don't know why, but I am getting this result on my system,

irb(main):001:0> pry
[1] pry(main)> h=Host.new
=> #<Host::Managed:0x0000000010536ca8
 id: nil,
 name: "karin-weinkauf",
 last_compile: nil,
 last_report: nil,
 updated_at: nil,
 created_at: nil,
 root_pass: nil,
 architecture_id: nil,
 operatingsystem_id: nil,
 environment_id: nil,
 ptable_id: nil,
 medium_id: nil,
 build: false,
 comment: nil,
 disk: nil,
 installed_at: nil,
 model_id: nil,
 hostgroup_id: nil,
 owner_id: nil,
 owner_type: nil,
 enabled: true,
 puppet_ca_proxy_id: nil,
 managed: true,
 use_image: nil,
 image_file: nil,
 uuid: nil,
 compute_resource_id: nil,
 puppet_proxy_id: nil,
 certname: nil,
 image_id: nil,
 organization_id: nil,
 location_id: nil,
 type: "Host::Managed",
 otp: nil,
 realm_id: nil,
 compute_profile_id: nil,
 provision_method: nil,
 grub_pass: "",
 global_status: 0,
 lookup_value_matcher: nil,
 pxe_loader: nil,
 initiated_at: nil,
 build_errors: nil>

[2] pry(main)> h.managed?
=> true

[3] pry(main)> h.class
=> Host::Managed(id: integer, name: string, last_compile: datetime, last_report: datetime, updated_at: datetime, created_at: datetime, root_pass: string, architecture_id: integer, operatingsystem_id: integer, environment_id: integer, ptable_id: integer, medium_id: integer, build: boolean, comment: text, disk: text, installed_at: datetime, model_id: integer, hostgroup_id: integer, owner_id: integer, owner_type: string, enabled: boolean, puppet_ca_proxy_id: integer, managed: boolean, use_image: boolean, image_file: string, uuid: string, compute_resource_id: integer, puppet_proxy_id: integer, certname: string, image_id: integer, organization_id: integer, location_id: integer, type: string, otp: string, realm_id: integer, compute_profile_id: integer, provision_method: string, grub_pass: string, global_status: integer, lookup_value_matcher: string, pxe_loader: string, initiated_at: datetime, build_errors: text)

[4] pry(main)>

**Comment by akshay-mendhe** [comment]
Can you tell me the scenario, you used to create host, as i am creating it from console?

**Comment by akofink** [comment]
I also created it from the Rails console with Katello (the centos7-devel forklift box).

**Review by akofink — DISMISSED** [review]
I just tried it again, and it's working as expected (not sure what changed). ACK from me! The following now work as expected:

```rb
Host.new
=> #<Host::Managed:0x000000000c185b08                                                                                                                                                                              
 id: nil,                                                                                                                                                                                                          
 ...                                                                                                                                                                                       
 managed: true,                                                                                                                                                                                                    
 ...
 location_id: nil,                                                                                                                                                                                                 
 type: "Host::Managed",                                                                                                                                                                                            
 ...
 build_errors: nil>

Host::Base.new
=> #<Host::Base:0x000000000c09d100
 id: nil,
 ...
 managed: false,
 type: nil,
 ...
 build_errors: nil>
```

**Comment by akofink** [comment]
It continues to behave as expected, but I just tried the following, which is not correct:

```rb
Host::Managed.new
=> #<Host::Managed:0x000000000aaa0230
 id: nil,
 ...
 managed: false,
 ...
 type: "Host::Managed",
 ...>
```

**Comment by akofink** [comment]
I think the default `Host.new` should not be a `Host::Managed`. Before this PR, `Host.new` returns a `Host::Managed` with `managed? == false`. We've made it a `Host::Managed` with `managed? == true`, which might cause the test failures.

**Comment by akshay-mendhe** [comment]
@akofink the same tests fails even without my change. Before this PR, the method "Host.new" was setting new host instance to "Host::Managed" state if not mentioned by passing arguments to new method in "app/models/host.rb" file. The tests which are failing are related to validations for OS, Mac, location, organization and other non mandatory fields that we use while creating host.

**Comment by akofink** [comment]
There are 4536 reported foreman failures. I doubt all those are failing on foreman develop. :confused:

**Comment by mmoll** [comment]
I can reproduce this (with the PR patch) locally:
```
Finished in 611.200610s, 11.4889 runs/s, 25.1407 assertions/s.
7022 runs, 15366 assertions, 19 failures, 890 errors, 1 skips
```

**Comment by tbrisker** [comment]
Thanks @akshay-mendhe ! This PR has been inactive for almost a year now, I'll go ahead and close it. If you still wish this change to be made, please feel free to reopen, rebase on the latest develop branch and make sure all the tests are passing.

**Comment by apuntamb** [comment]
This patch works for me, if we could re-open this and try running tests once again on latest, I guess we could get it in.

**Comment by tbrisker** [comment]
@apuntamb If you think this is needed please open a new PR. However looking at the original issue i am not certain it needs fixing. It's confusing, but the `managed` flag on the host is not actually related to the `Host::Managed` class at all, it just has the same name.

**Comment by apuntamb** [comment]
> @apuntamb If you think this is needed please open a new PR. However looking at the original issue i am not certain it needs fixing. It's confusing, but the `managed` flag on the host is not actually related to the `Host::Managed` class at all, it just has the same name.

Ohkk, if the flag and the class name do not share any relation, then I agree, it wouldn't need fixing. Thanks @tbrisker for confirming!

**Pull request closed without merging**
