### PR TITLE
Fixes #23834 - better assert in host test

### PR DESCRIPTION
**Pull request by lzap**
This fails in discovery tests, dunno why need to see more.

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap @ares what's the status here?

**Review by ares — DISMISSED** [review]
Looks reasonable to me, would you mind fixing the commit message? Then I think we can merge.

**Comment by lzap** [comment]
Done.

**Comment by lzap** [comment]
Rebased once again can we merge @ares ?

**Comment by tbrisker** [comment]
[test foreman]

**Review by tbrisker — APPROVED** [review]
Thanks @lzap !

**Pull request merged**
