### PR TITLE
Fixes #19762 - upgrade to rubocop 0.49.1

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker does it make sense to enable some of those new cops? at some point of time we should start reducing the number of todo's :)

**Comment by tbrisker** [comment]
@ohadlevy in general - yes, definitely. I'd rather do that in separate PRs though, so this PR doesn't get blocked by disagreements on which cops should be enabled and which not.

**Review by ohadlevy — APPROVED** [review]
will be waiting on tests :+1: @tbrisker

**Comment by tbrisker** [comment]
@ohadlevy all :green_apple: except the regular katello failures

**Comment by ohadlevy** [comment]
Thank @tbrisker

**Pull request merged**
