### PR TITLE
Fixes #17548 - Orphaned smart class parameters are hidden

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1: ack on green tests.

**Comment by ohadlevy** [comment]
@orrabin note the test failures...

**Comment by orrabin** [comment]
@ohadlevy I added fixtures because the integration tests where using orphaned smart class parameters. Please notice the api would always filter them out which is why I also had to fix some api tests after connecting these parameters to environment classes.

**Comment by ohadlevy** [comment]
thanks @orrabin

**Pull request merged**
