### PR TITLE
fixes #5834 - Hosts: . in the name is invalid - user is told this but the UI adds one anyway

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by dmitri-d** [comment]
tested, works. Adding a test for this would be helpful...

**Comment by GregSutcliffe** [comment]
@witlessbird did you test with :unattended => false? I'm concerned about breaking the situation where you do actually want to have the full domain in the name (becaus the Network tab is disabled in unmanaged hosts), but I've not had chance to test it myself yet...

**Comment by isratrade** [comment]
@GregSutcliffe, if full name is in `name`, then it's fine.  It has a period(.) in the name, so `name` is returned.

``` ruby
name.include?('.') ? name : "#{name}.#{domain}"
```

**Comment by domcleal** [comment]
When unattended = false, all that's happened is the code changed from domain.nil? to domain.blank?, practically the same.  Also, you wrote unit tests, right @GregSutcliffe? :)

**Comment by GregSutcliffe** [comment]
@domcleal my concern was dropping the check on SETTINGS[:unattended], not the change from nil? to blank?. But if the tests pass, then so be it :)

**Comment by isratrade** [comment]
@GregSutcliffe, it doesn't appear that the `SETTINGS[:unattended]` affects anything.  If `domain` is blank, then the method should not add a period (.) plus domain name regardless.

**Comment by GregSutcliffe** [comment]
Tested, fixes the problem. Code looks fine. :+1: to merge

**Comment by domcleal** [comment]
Merged as e254ea5 for Foreman 1.5.1, thanks!

**Pull request closed without merging**
