### PR TITLE
Fixes #22806 - rails now boot without telementry deps

### PR DESCRIPTION
**Pull request by lzap**
Reported by @mmoll thanks.

### CODE REVIEW

**Review by mmoll — APPROVED** [review]
tested with current staging DEBs, fixes the problem

**Review by ekohl — APPROVED** [review]

**Review by dLobatog — APPROVED** [review]
Thanks @lzap @mmoll

**Comment by dLobatog** [comment]
Will merge if tests pass

**Comment by mmoll** [comment]
test failures unrelated, AFAICT

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
