### PR TITLE
fixes #22518 - add hover css to table helper

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
hover

**Review by ekohl — APPROVED** [review]

**Review by timogoebel — APPROVED** [review]
I like it, huge win!

**Review by timogoebel — CHANGES_REQUESTED** [review]
@ohadlevy:
Could you also please add the helper to these tables?

* app/views/dashboard/_new_hosts_widget_host_list.html.erb
* app/views//about/index.html.erb

**Review by timogoebel — APPROVED** [review]
Actually, the tables break with the helper and I don't think the hovering is required there.

👍 from me

**Review by ares — APPROVED** [review]
APJ

**Review by ares — CHANGES_REQUESTED** [review]
tests failures are actually related, @ohadlevy please take a look

**Review by ares — APPROVED** [review]
another APJ

**Comment by ohadlevy** [comment]
:green_apple:

**Comment by timogoebel** [comment]
Thanks, @ohadlevy!

**Comment by ares** [comment]
@ohadlevy mind to also take a look to jquery data tables? they did not get the class, e.g. Administer -> Roles -> Filter tab

edit: excuse me, PEBKAC

**Pull request merged**
