### PR TITLE
Fixes #21129 - Switching the submit and cancel buttons

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Review by timogoebel — CHANGES_REQUESTED** [review]
@shiramax: Thanks. Could you please also change this for React?
https://github.com/theforeman/foreman/blob/65f2864da9d5c0fad8b50424690b410fc8e64cd6/webpack/assets/javascripts/react_app/components/common/forms/Actions.js#L9-L19

**Comment by shiramax** [comment]
@timogoebel , 
Do you know which feature is using this form right now?  didn't find it via mount_react_component or in the storybook.

**Comment by timogoebel** [comment]
@shiramax: It's not used anywhere just yet. You can test this with https://github.com/theforeman/foreman/pull/4807 if you want.

**Comment by shiramax** [comment]
@timogoebel  Done.

**Comment by ohadlevy** [comment]
[test]

**Comment by ohadlevy** [comment]
@shiramax can you please rebase?

**Comment by ohadlevy** [comment]
@shiramax please note that you would need to update jest tests/snapshots as well, you can do it by running ```npm test -- -u```

**Comment by shiramax** [comment]
@ohadlevy 
Thanks, done.

**Comment by ohadlevy** [comment]
Thanks!

**Comment by ares** [comment]
FYI I opened an issue in patternfly as I feel this feels surprising especially if the alignment differs in form and modal window - https://github.com/patternfly/patternfly/issues/830

**Pull request merged**
