### PR TITLE
Fixes #22711 - fix uglifyjs-webpack plugin

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by xprazak2** [comment]
[test katello]
Will not pass due to plugin requirement:
Foreman::PluginRequirementError: ERF72-4298 [Foreman::PluginRequirementError]: katello plugin requires Foreman >= 1.17 but current is 1.16.0

**Comment by mmoll** [comment]
Tes, katello tests are known to fail on stable branches as katello's master is tested against old Foreman versions in that case.

**Comment by ekohl** [comment]
@mmoll https://github.com/theforeman/foreman-infra/blob/c1946eaffbc16705d1cfe3ed2d38815d6e84bd7a/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy#L2-L6 should take care of that. If it doesn't, that's a bug.

**Review by dLobatog — APPROVED** [review]
Thanks @mmoll

**Comment by dLobatog** [comment]
@ekohl It seems to be a bug then, [Jenkins](http://ci.theforeman.org/job/test_develop_pr_katello/6122/database=postgresql,ruby=2.4,slave=fast/console) says `10:05:37 Using katello 3.7.0 from source at `/var/lib/workspace/workspace/test_develop_pr_katello/database/postgresql/ruby/2.4/slave/fast/plugin``

**Comment by ekohl** [comment]
@dLobatog it looks like that's actually a different job than I linked. @ehelms could you have a look?

**Comment by ehelms** [comment]
The job test_develop_pr_katello does not have any of the logic that switches Katello branch based on Foreman branch today since it lives outside the normal life cycle. We can add this in the meantime or wait nad look at it as part of re-factoring Foreman core jobs.

**Pull request merged**
