### PR TITLE
Fixes #31852 - New react test snapshots for patternfly update

### PR DESCRIPTION
**Pull request by johnpmitsch**
See https://github.com/theforeman/foreman-js/pull/260 and https://github.com/theforeman/foreman-js/pull/258

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I'm confused. The tests are not failing on other PRs now, and it's not failing for your PR eighter :thinking:
Is it black magic? :mage:

**Comment by johnpmitsch** [comment]
> I'm confused. The tests are not failing on other PRs now, and it's not failing for your PR eighter

@ezr-ondrej Nothing is currently failing, but in the PRs I linked above they are failing the foreman tests, I was able to reproduce this locally with the foreman-js PRs checked out. Once the foreman-js PRs are merged, will we see the same failures in foreman? If so, this will fix them.

**Comment by amirfefer** [comment]
Some thoughts:

`vendor-core` pins patternfly related packages with `^`:

```js
    "@patternfly/react-core": "^4.84.4",
```
https://github.com/theforeman/foreman-js/blob/f463eed42bae5e32b8546990d6c2fc777ffb623b/packages/vendor-core/package.json#L29

This means that  `npm`  installs the latest `minor` update after a clean `npm install`
 i.e - an  upgrade from `4.24.4` to `4.90.2`, the latest pf version, is valid, but this upgrade  includes some breaking changes.

According to npm [docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json), The `package-lock` file is ignored when publishing a package to npm:

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package

How about pinning packages in `vendor-core `with `~`? this assures that only the `patch` version can be updated.

**Comment by johnpmitsch** [comment]
> How about pinning packages in `vendor-core `with `~`? this assures that only the `patch` version can be updated.

We've discussed this before, I know I brought it up [here](https://community.theforeman.org/t/pinning-npm-packages-to-y-version/12393), though it was before the metapackages and dependabot.

I think it's a discussion worth revisiting!

> According to npm docs, The package-lock file is ignored when publishing a package to npm:

>> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package

Good to know! That explains a lot.

**Comment by johnpmitsch** [comment]
I think this was taken care of so I am closing, but feel free to comment if it's still needed!

**Pull request closed without merging**
