### PR TITLE
Fixes #31787 - Add AlmaLinux support

### PR DESCRIPTION
**Pull request by andrewlukoshko**
This PR adds support for AlmaLinux OS (https://almalinux.org)
It's already supported in Puppet: puppetlabs/facter#2292

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Do you happen to know the license for the image files? It probably is ok, but I'd rather be safe than sorry here.

**Comment by ekohl** [comment]
ok to test

**Review by lzap — APPROVED** [review]
We need the approval or license for that logo. Simply a link to some statement is good enough. Other than that, looks good.

Keep in mind that if you want also Katello (content management), more changes need to be done, but this is a good start.

**Comment by andrewlukoshko** [comment]
@ekohl AlmaLinux allows using and scaling their logo https://almalinux.org/legal/trademark-guidelines/

**Comment by lzap** [comment]
Yeah this is good enough, thank you. Does not look scaled :-)

**Comment by andrewlukoshko** [comment]
@lzap I've submitted PR to Katello too: https://github.com/Katello/katello/pull/9338
Is it enough or some extra changes need to be done?

**Comment by lzap** [comment]
Great, I think that should be it! Maybe checking out how Facter/Ansible/Chef (whatever you use) report the OS otherwise your OS will get flipped back to CentOS on every fact upload.

**Comment by lzap** [comment]
Oh I am not Katello expert but there is some code which detect OS when you sync a Kickstart repo, that needs to be most likely changed too. Try to sync an AlmaLinux kickstart to see what OS it creates.

**Comment by lzap** [comment]
Thanks merged.

**Comment by ekohl** [comment]
> @ekohl AlmaLinux allows using and scaling their logo https://almalinux.org/legal/trademark-guidelines/

This page is longer available. Now https://almalinux.org/p/terms-of-service/ states:

> Trademarks
>
> The trademarks, logos and service marks (“Marks”) displayed on this website are the property of AlmaLinux, Inc. or other third parties. You are not permitted to use these Marks without the prior written consent of AlmaLinux or the third party which owns the Mark.

I now wonder if this was also the case when we merged it. In the future we should screenshot the relevant license text in case it changes.

**Comment by jaboutboul** [comment]
Hello. It seems like that page got munged as part of the new site deployment. We haven’t changed those terms so you can proceed as usual. Sorry about that we’ll get that fixed.

**Pull request merged**
