### PR TITLE
fixes #8601 - cloudinitlike for vsphere

### PR DESCRIPTION
**Pull request by karmab**
this is a proposed patch to enable user_data type like cloudinit for vsphere
there is an associated pull request on fog side https://github.com/fog/fog/pull/3317
as the idea is to convert user_data string to a hash parsed later as a customisationspec template (vsphere specific)

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test]

**Comment by dLobatog** [comment]
Waiting on https://github.com/fog/fog/pull/3317 & a new Fog release after that, please @karmab ping us when everything is ready :smile:

**Comment by karmab** [comment]
fog dependency was merged :)

**Comment by karmab** [comment]
any update on this one ?

**Comment by dLobatog** [comment]
Sorry @karmab , I dropped the ball a bit on this one. We ship Fog 1.28.0 so :shipit: 

Merged as 5b1f7529284e9e62d9f8f08977b543d4a7b93f21, thanks @karmab !

**Pull request closed without merging**
