### PR TITLE
Fixes #8285 - Update README.md

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by boaz0** [comment]
:+1:  Well done! :-)

**Comment by dLobatog** [comment]
@GregSutcliffe Screenshot updated to show it's Openstack

**Comment by dLobatog** [comment]
@GregSutcliffe issue number added

**Comment by GregSutcliffe** [comment]
Merged as 9524694, thanks!

**Comment by dLobatog** [comment]
@GregSutcliffe thanks for merging, I think you forgot to close the door :smile:

**Pull request closed without merging**
