### PR TITLE
fixes #18712 - Spinner

### PR DESCRIPTION
**Pull request by gailsteiger**
create react Spinner component with patternfly styling

### CODE REVIEW

**Review by ohadlevy — CHANGES_REQUESTED** [review]
thanks @gailsteiger.

Can you please update all other spinners to use this ? not much point in having multiple spinner implementations.

**Comment by dLobatog** [comment]
Given my lack of success with https://github.com/idimaster/patternfly-react/pull/1 , and our growing set of Patternfly related components, how about we start extracting these to an npm package that we can use (and that we maintain?). 

I see a lot of benefits to doing it that way:

- The package can have it's own lifecycle, Foreman would just have to mount the components wherever needed and adapt it to use our API when needed.
- Maintainers don't have to be the same. We have a good number of people these days working exclusively on UI stuff who cannot merge things in the Foreman repo, but they should have access to merge stuff in the Patternfly React repo.
- Other projects can benefit from such a package and contribute to it. The few patternfly-react projects I've been seeing are unfortunately unmaintained or no actual project uses it. Since Foreman relies on React and Patternfly, we have a duty to keep that repository well maintained.

I don't mind to start this effort by moving some components to an npm package. My biggest concern with this, is that I'm not sure how possible is it to move our current components to an state where they don't need flux/redux. 

PS - If no one is starting this, I will after 1.15 is released, not before

**Comment by gailsteiger** [comment]
@dLobatog @matanwerbner @ohadlevy @lizagilman and anyone else :)

You might want to have a look at  [Web Components/Native Framework Proposal](https://t.co/z9r6UZHxPe) proposed at the February 22 Patternfly Community Meeting. [slides](https://github.com/patternfly/patternfly-design/blob/master/resources/community-meetings/PatternFly%20Community%20Meeting%202017-02.pdf),  [recording](https://bluejeans.com/s/Cnu5T/)

I think participating in this could be fruitful.

**Comment by tbrisker** [comment]
TBH I'm not sure I understand the value in creating a react component that just creates a spinner div - seems like a lot of code instead of just writing `<div class='spinner spinner-lg'>`. Am I missing something here?

**Pull request closed without merging**
