### PR TITLE
Refs #29590 - add debian pkgs to installed packages report

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Used wrong issue id. Updated to https://projects.theforeman.org/issues/29590

**Comment by sbernhard** [comment]
[test integration]

**Comment by sbernhard** [comment]
Someone has a feedback on this @ianballou / @chris1984 ?

**Review by chris1984 — APPROVED** [review]
Looks sane, I don't have merge perms. @Ron-Lavi Can this get a review/merge?

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

Thanks @sbernhard

**Pull request merged**
