### PR TITLE
Fixes #33550 - Remove Puppet API endpoints

### PR DESCRIPTION
**Pull request by nadjaheitmann**
Needed for seamless integration with the foreman_puppet plugin (https://github.com/theforeman/foreman_puppet/pull/196)
Prerequisite for this PR: https://github.com/theforeman/foreman_puppet/pull/201

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
I think we should do this. It will drop the enpoints here and only people with Puppet plugin installed will have them available. Which is expected behaviour IMHO.

**Comment by ezr-ondrej** [comment]
Given there was no push-back this morning, I'll merge this, in case there is a strong disagreement, we can always revert.
Thanks @nadjaheitmann ! :+1:

**Comment by ekohl** [comment]
For the past 2 weeks nightly has been broken due to this. Is anyone working on fixing this?

**Comment by nadjaheitmann** [comment]
As far as I understand, a new foreman_puppet release is necessary. @ezr-ondrej ? (the plugin replaces some functionality that was removed in this PR)

**Pull request merged**
