### PR TITLE
fixes #5129 - Host Group creation may fail if parameter is same name

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@jlsherrill, similar to @bbuckingham's PR #1366, but I limited it only to GroupParameter so it doesn't affect the others. I also limited it to if `self.new_record? && self.reference_id == 1`. In actuality, after initialize `reference_id` should also be `nil` so it should be fine. The reason that it previously broke tests is is that parameters were explicated created in tests such as

``` ruby
    parameter1 = GroupParameter.create :name => "some_parameter", :value => "value", :reference_id => hostgroups(:common).id
    parameter2 = GroupParameter.create :name => "some_parameter", :value => "value", :reference_id => hostgroups(:common).id
```

`

**Comment by domcleal** [comment]
Is this bug also relevant to orgs, locs, OSes and domains?  They all have near identical implementations, so I don't see why it would just be host groups.

**Comment by jlsherrill** [comment]
@domcleal this actually was fixed elsewhere for taxonomies:  https://github.com/theforeman/foreman/blob/develop/app/models/concerns/taxonomix.rb#L99

issue: http://projects.theforeman.org/issues/4731

Not sure about OSes and domains it may be that we haven't exposed the conditions necessary to reproduce in those areas (if its possible)

**Comment by jlsherrill** [comment]
Created a host group in the same way as before and this seems to resolve it.

**Comment by bbuckingham** [comment]
@domcleal, part of the reason that I closed the original PR is that it looked like the issue could exist in several places, as the parameters are used for multiple objects.  So, while it may only have been observed for hostgroups, it seems reasonable to protect all cases.

**Comment by domcleal** [comment]
@jlsherrill that's taxono_mix_ which is for resources inside a taxonomy, not taxonomies themselves.  I was concerned about other Parameter subclasses, e.g. DomainParameter, OrganizationParameter, while this fix has only been made in GroupParameter.

**Comment by jlsherrill** [comment]
@domcleal ahh good call :)

**Comment by isratrade** [comment]
re-committed and moved fix to `parameter.rb`.  Same as @bbuckingham's previous PR but with
 `if self.reference_id == 1` added which causes it not to break tests.

**Comment by domcleal** [comment]
Merged as 691f0a1 for Foreman 1.5.2, thanks @isratrade.

**Pull request closed without merging**
