### PR TITLE
fixes #8465 - Add Digital Ocean Support

### PR DESCRIPTION
**Pull request by TJM**
Adds the necessary shims to support Digital Ocean as a Compute Resource. This also _properly_ supports regions at the VM level instead of the compute resource level.

This should fix my bug #8465 to add support.

I am not sure what the next steps are.

~tommy

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by TJM** [comment]
If you are trying to test this, you need to make sure you are using an APIv1 Key...

These are listed on the API v1 page:
- Go to: https://cloud.digitalocean.com/api_access
  *\* Or you can locate the link from the API v2 page (https://cloud.digitalocean.com/settings/applications) in the heading: http://cl.ly/image/0w2L2Y3E2N3q

**Comment by dLobatog** [comment]
@TJM This looks pretty good, just a few comments:
- We tend to add new compute resources as plugins, as Foreman core is a bit overloaded already. Could you move this to a plugin? [Docker](https://github.com/theforeman/foreman-docker), [Xen](https://github.com/theforeman/foreman-xen), [Open nebula](https://github.com/theforeman/foreman-one) could be examples. If you want I can take these commits and do the grunt work. You'll get it packaged and added to the official plugins repository by doing this.
- Tests are lacking
- When creating the Compute Resource, a wrong client ID or API ID will trigger a `401 unauthorized` and Foreman does not know how to handle that and throws a 500. Could you fix that one?
- When clicking on 'Virtual Machines' under the Compute Resource menu, I see an error `There was an error listing VMs: undefined method `distribution' for nil:NilClass`. If you could change also 'virtual machines' to 'droplets' that'd be great too but it's not urgent obviously.
- When creating a new images, I see the proposed images are just the number, '14.04', '7.0 x32', etc.. Can this be fixed to return the whole name + version? It's confusing to see the version of the image but not the OS :smile:

**Comment by TJM** [comment]
Hi @eLobato ,

Thank you for your feedback.
- I kept thinking it should probably be a plugin, but my _original_ goal was to "copy" the rackspace setup since it was similar, and change a few prompts and the provider to make it work. I can look into making it a plugin.
- For tests, I just copied the rackspace section, need a good example to follow there... hopefully those plugins have good tests
- Ah, someone always has to go spoil the show, is it really a 500 error? dang! I thought I got a "red box" error when they were wrong.
- re: distribution .. I guess I better wrap that in .try... distribution is in there normally:

```
irb(main):051:0> client.images.last
=>   <Fog::Compute::DigitalOcean::Image
    id=7572830,
    name="Redmine on 14.04",
    distribution="Ubuntu"
  >
```
- Re: the "images" that are just versions, I thought I fixed that. I am not sure what exactly to change there, I think i just changed it on the "hostgroup"rm d screen maybe? Perhaps this one is related to the one above?

Thanks again for the feedback!

**Comment by TJM** [comment]
I have to say, that I was pretty happy that I was able to expose "Region" as a host creation option... it drove me crazy in the rackspace model that region is hardcoded at the compute resource level. ;)

**Comment by TJM** [comment]
See https://github.com/theforeman/foreman/pull/1978 for the "rest of the story" ... I screwed up and deleted the branch :)

**Pull request closed without merging**
