### PR TITLE
Fixes #6658: creating compute resource with name more than 245 chars fails

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@orrabin since this is likely to hit other models, does it make sense to go though all of them and add the validation globally?

we could even consider adding a validation based on the db length automatically?

**Comment by dLobatog** [comment]
@ohadlevy :+1: to the second idea

**Comment by domcleal** [comment]
I'm aware of both http://projects.theforeman.org/issues/6712 and http://projects.theforeman.org/issues/4153 with the same issue.

**Comment by orrabin** [comment]
The same validation was missing in all of the bugs here https://github.com/theforeman/foreman/pull/1593

**Comment by orrabin** [comment]
this will be fixed by https://github.com/theforeman/foreman/pull/1593

**Pull request closed without merging**
