### PR TITLE
Cleanup in French locale + translation fix

### PR DESCRIPTION
**Pull request by ryayon**

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks for the PR.  We manage our translations on a separate website, and they're synced into the latest release (i.e. 1.11.0) rather than being managed in git.

Could you please update the string at https://www.transifex.com/foreman/foreman/?

**Comment by ryayon** [comment]
Thanks,
I know something new today ;-).

Just did the translation.
Please let me know if it is good.

PS: in the meantime, I close this PR.

**Comment by domcleal** [comment]
Great, I see you're editing it on Transifex - just make sure you click Save after editing the string and it should work.  Cheers!

**Comment by ryayon** [comment]
I did it.
Hope this is fine.

**Comment by domcleal** [comment]
Yep, that's it, I see it saved now.

**Comment by ryayon** [comment]
thanks.

**Pull request closed without merging**
