### PR TITLE
Fixes #16835 - ptables search fails PG error

### PR DESCRIPTION
**Pull request by amitkarsale**
API get for search on ptables with organization ID fails with PGSQL error

### CODE REVIEW

**Comment by domcleal** [comment]
I can't reproduce the error reported in the ticket on Foreman, can you confirm that this bug exists?

It's unclear from the commit and the commit message (which should state what changed) why this reordering of the scoped search definitions fixes anything. Please supply a bit more context about the change and the cause.

**Comment by amitkarsale** [comment]
I and one of my colleague was able to reproduce the issue on foreman. 
Not sure why just re-ordering solves the issue,  we use `scope_search` gem for searching, the query formed while not reordering the scopes and ordering the scopes were different and as they are applied on the polymorphic table might have lead to form inconsistent query on scope_search gem.
I was going to ask someone from the community who has knowledge on scope_search gem regarding the behavior.

**Comment by domcleal** [comment]
I see the issue now when running the unit test, but it simply moves the bug from one taxonomy type to the other by reordering those conditions - it previously passes when using `location_id`, but now fails for `location_id`. I don't think this sufficiently fixes the issue.

**Comment by shlomizadok** [comment]
This fix does not solve the issue - I was able to reproduce with organization.
calling `/api/v2/ptables?search=FreeBSD&organization_id=2` would raise:
`error": {"message":"PG::UndefinedTable: ERROR:  missing FROM-clause entry for table \"organizations_templates`

* Please note that calling `/api/v2/ptables?search=FreeBSD&organization=MyOrg` works.

@amitkarsale - let me know if you plan to continue or close this.

**Comment by amitkarsale** [comment]
@shlomizadok I am looking into this issue, it should also works when `id` is provided. will submit a new PR on the same

**Comment by ohadlevy** [comment]
@amitkarsale what is the status of this pr? thanks.

**Comment by ares** [comment]
@amitkarsale was there any progress?

**Comment by amitkarsale** [comment]
will update on this shortly. Thanks

**Comment by tbrisker** [comment]
I can't seem to reproduce with current develop, does this only occur when certain plugins are enabled or was this resolved by some other fix?

**Comment by tbrisker** [comment]
never mind, managed to reproduce.

**Comment by tbrisker** [comment]
Closing after discussion with @amitkarsale.

**Pull request closed without merging**
