### PR TITLE
1009560 - Do not delete other obsolete environments 

### PR DESCRIPTION
**Pull request by pitr-ch**

### CODE REVIEW

**Comment by domcleal** [comment]
Deletion of obsolete environments without content is the normal behaviour for the puppet class import, at least via the GUI version.  Are you specifying a particular environment that you want to update when calling the API?

**Comment by pitr-ch** [comment]
Right now I think, it cannot be specified which environments should be updated via API.

**Comment by domcleal** [comment]
It can:

```
/smart_proxies/:smart_proxy_id/environments/:id/import_puppetclasses
/environments/:environment_id/smart_proxies/:id/import_puppetclasses
```

Especially for use with Katello, so you could just update the environment that's been promoted :)

**Comment by pitr-ch** [comment]
@domcleal yeah you are right, I've got confused. I am actually calling it :)

```
Started GET "/foreman/api/environments/8/smart_proxies/1/import_puppetclasses"
```

**Comment by domcleal** [comment]
Okay, so what's the bug you're trying to solve?  If you ask it to import_puppetclasses for environment "8", it will delete the env if there's no content?  Or it's deleting other environments?

**Comment by pitr-ch** [comment]
Other environments.

**Comment by pitr-ch** [comment]
the problem lies in https://github.com/pitr-ch/foreman/blob/bcb0124cb5b9006ae9133afdc27dc3a732d9fe70/app/controllers/concerns/api/import_puppetclasses_common_controller.rb#L46-L51 checking only `@changed['new']`

**Pull request closed without merging**
