### PR TITLE
Revert "Fixes #30665 - drop the intl polyfills"

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Reverts theforeman/foreman#7910

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Any idea why none of the tests caught this issue?

**Comment by ezr-ondrej** [comment]
> Any idea why none of the tests caught this issue?

People needed a completely fresh `npm i`, but why the CI passed I've got no idea

**Comment by jeremylenz** [comment]
The webpack compiled successfully. But our CI doesn't test if a browser loads a visible page..

**Comment by ezr-ondrej** [comment]
> The webpack compiled successfully. But our CI doesn't test if a browser loads a visible page..

It does. Some Integration tests are interacting with the fully loaded UI in headless browser. And going through login it probably should have gone through the full react page :shrug:

**Comment by jeremylenz** [comment]
Interesting.  When I had the blank page loaded I did see plenty of elements in the DOM, so maybe it was enough to trick it.

**Comment by tbrisker** [comment]
Huh, that might be it. We have a hack that basically hides the content and then shows it when it gets loaded, and when there are JS errors, that stops the code that removes that css. It has been a source of some other issues in the past, we might want to reconsider this flow: https://github.com/theforeman/foreman/pull/6502/

**Comment by ekohl** [comment]
We also have smoker (which does run a browser on the resulting packages) but that isn't set up to block the pipeline. We had failures in it so we (platform team) always felt uncomfortable with that. Perhaps we should, but IIRC we still had some issues. For example, https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/1164//artifact/artifacts/foreman-pipeline-katello-nightly-centos8-install/ shows blank screenshots for a bunch of pages.

**Pull request merged**
