### PR TITLE
Refs #19050 - Use Rails 5.0 on Ruby 2.3 again

### PR DESCRIPTION
**Pull request by mmoll**
This reverts commit 36e533a1fa921b062fadea51a35871bbfe2fc24c.

### CODE REVIEW

**Comment by mmoll** [comment]
As the major plugins are updated now, I'd like to get Rails 5.0 more exposure on Debian and Ubuntu nightlies.

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
[test foreman]

**Comment by GregSutcliffe** [comment]
Let's give it a try then, thanks @mmoll :P

**Pull request merged**
