### PR TITLE
Fixes #24845 - Inconsistent UI for Spice console

### PR DESCRIPTION
**Pull request by UXabre**
Verified on both VNC & Spice sources, now these console types look consistent

### CODE REVIEW

**Comment by tbrisker** [comment]
@UXabre is the issue only present in 1.19 and fixed already in develop?

**Comment by ohadlevy** [comment]
can you please provide before / after screenshots? thanks!

**Comment by ohadlevy** [comment]
oh, i missed this is against 1.19 branch. +1 for @tbrisker question.

**Comment by UXabre** [comment]
Hey @tbrisker, it's not fixed on develop, sorry. Probably best if I close this PR and create one for the develop? After that one is merged I'll recreate one for 1.19.

@ohadlevy, I'll post the screenshots on the new PR

**Comment by tbrisker** [comment]
@UXabre yes, please do. thank you!

**Pull request closed without merging**
