### PR TITLE
Fixes #34949 - Do not set taxonomies during extlogin

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by sbernhard — APPROVED** [review]
LGTM

**Comment by Ron-Lavi** [comment]
Thanks @adamruzicka, @sbernhard :)

**Comment by Ron-Lavi** [comment]
Thanks @adamruzicka, @sbernhard :)

**Comment by adamruzicka** [comment]
3.4 CP - https://github.com/theforeman/foreman/pull/9431
3.3 CP - https://github.com/theforeman/foreman/pull/9432

**Pull request merged**
