### PR TITLE
Fixes #28257 - Drop mysql bundler group

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
tests will fail on mysql for obvious reasons.

**Comment by mmoll** [comment]
@tbrisker Could you open an -infra PR to delete the mysql tests on develop?

**Comment by tbrisker** [comment]
@mmoll  - https://github.com/theforeman/foreman-infra/pull/1187

**Comment by mmoll** [comment]
[test katello]

**Comment by tbrisker** [comment]
all is green, but I think we need the packaging prs to also be ready to merge before merging this?

**Comment by tbrisker** [comment]
deb is https://github.com/theforeman/foreman-packaging/pull/4336 which i think is ready and rpm is https://github.com/theforeman/foreman-packaging/pull/4335 which still needs a bit more work

**Review by ekohl — APPROVED** [review]
Both packaging PRs look good to me. I assume you want to do the actual code cleanup in a separate PR.

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
