### PR TITLE
Fixes #17272 - Fixed Searches on parameters with !=

### PR DESCRIPTION
**Pull request by dhlavac**

### CODE REVIEW

**Comment by dLobatog** [comment]
Seems like Travis never returned 😄 but it's green on https://travis-ci.org/theforeman/foreman/builds/204618701

**Comment by dLobatog** [comment]
I was surprised but the tests indeed don't pass without the change. Thanks @dhlavac

**Comment by iNecas** [comment]
I don't know what happened to Jenkins on the PR, but there were tests actually failling with this one, fix opened in https://github.com/theforeman/foreman/pull/4324

**Comment by domcleal** [comment]
> I don't know what happened to Jenkins on the PR

The very first three comments: https://github.com/theforeman/foreman/pull/4323#issuecomment-282017760, https://github.com/theforeman/foreman/pull/4323#issuecomment-282017762, https://github.com/theforeman/foreman/pull/4323#issuecomment-282017765 were ignored and the PR was never tested.

**Pull request merged**
