### PR TITLE
Feature #29508 - Update masthead and sidebar to use PatternFly 4

### PR DESCRIPTION
**Pull request by jschuler**
This updates the sidebar and masthead to use PatternFly 4

Depends on https://github.com/theforeman/foreman/pull/7508

Screenshot from 2020-04-02 11-14-18

Pre PF4
[Alt text](https://www.youtube.com/watch?v=244V1Fx99zQ)

Post PF4
[Alt text](https://www.youtube.com/watch?v=Ex_47RUipLw)

### CODE REVIEW

**Comment by sharvit** [comment]
Thank you for your contribution @jschuler!
looks like a very nice start :+1:

**Comment by sharvit** [comment]
@Rohoover ^^

**Comment by Rohoover** [comment]
Looks good so far! If you haven't seen the naming doc, here it is:

https://docs.google.com/document/d/1eFbHZjuZC40SYqAn93dOXU0nUf3RnL10Bb8uHIk60w4/edit#heading=h.szoi0pdvuicg

**Comment by sharvit** [comment]
Thanks @jschuler, closing for https://github.com/theforeman/foreman/pull/7809

**Pull request closed without merging**
