### PR TITLE
Fixes #28645 - fix smart proxy version comparison test

### PR DESCRIPTION
**Pull request by tbrisker**
the 2.0 version bump caused the test to fail, since the expected
proxy version was calculated from the current foreman version leading to
negative minor version

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
This will actually fail in runtime as well, right? Users can run a combination of Foreman 2.0 and Foreman Proxy 1.24 at some point. They can even run Foreman 1.24 and Foreman Proxy 2.0. Just fixing it in the tests sounds like an incorrect place to fix it.

IMHO Foreman shouldn't be testing for versions but rather for capabilities, but we didn't start doing that in time to rely on just yet.

**Comment by tbrisker** [comment]
> This will actually fail in runtime as well, right? Users can run a combination of Foreman 2.0 and Foreman Proxy 1.24 at some point. They can even run Foreman 1.24 and Foreman Proxy 2.0. Just fixing it in the tests sounds like an incorrect place to fix it.

Actually, the test is testing that the proxy api returns a warning when the versions don't match.
The code itself won't fail. it just compares the major and minor - https://github.com/theforeman/foreman/blob/develop/app/controllers/smart_proxies_controller.rb#L163-L183

> 
> IMHO Foreman shouldn't be testing for versions but rather for capabilities, but we didn't start doing that in time to rely on just yet.

makes sense, but we're definitely not there yet

**Comment by ekohl** [comment]
> Actually, the test is testing that the proxy api returns a warning when the versions don't match.

Do we want an explicit test for a major version mismatch with static versions?

**Comment by tbrisker** [comment]
> Do we want an explicit test for a major version mismatch with static versions?

since the controller is comparing to the current version, i don't think using static version mocks in the test would be useful as it mocks half of the logic. added a test to make sure we warn on mismatching x version as well

**Review by ekohl — APPROVED** [review]
I wonder if these tests would be better with hardcoded versions but this keeps it consistent and only touches what it needs to.

**Pull request merged**
