### PR TITLE
Fixes #18765 - finish script use FQDN when IP is missing

### PR DESCRIPTION
**Pull request by lzap**
This is resurrect of

https://github.com/theforeman/foreman/pull/2171/files

The old patch did not pass review because I was unable to explain the
motivation. The reason for the fallback is that only cloud compute
resources usually provide IP addresses but virtualization do not. Our
users often associate finish templates with libvirt or VMWare but it
does not work at all. This only applies to externally managed networks
where we don't know the IP (no reservation made by Foreman).

Now there is a question of safety, with incorrect DNS setup, Foreman
could run finish script on incorrect server. Therefore I am sending this
patch for discussion - I think I could make this behavior an opt-it via
setting.

### CODE REVIEW

**Comment by dLobatog** [comment]
I don't think there's a lot to worry here regarding DNS, there are credentials/keypair which could stop even the SSH upload before it runs if it's really the wrong server. 

How about checking `provision_interface.subnet` - see if it matches with the IP that would be used for `provision_interface.fqdn`? In such a case we could warn and stop the finish step saying the DNS record for that fqdn appears to be wrong.

cc @lzap

**Comment by lzap** [comment]
I am not sure iI understand the check you recommend.

**Comment by lzap** [comment]
Rebased @dLobatog can you explain? This is pretty straightforward.

**Comment by lzap** [comment]
I don't think the subnet check is worth the effort, won't help in all cases.

**Review by dLobatog — APPROVED** [review]
@lzap Alrighty - let's merge if :green_apple:

**Comment by dLobatog** [comment]
Tests passed everywhere, on 2.3 postgres it looks like there was some Jenkins related failure: 'Caused: java.io.IOException: Remote call on slave04.osuosl.theforeman.org failed'

**Comment by lzap** [comment]
So you want me to rebase?

**Comment by lzap** [comment]
Oh thanks :-)

**Comment by ares** [comment]
setting redmine release to 1.19, please don't forget updating redmine issue after merging

**Pull request merged**
