### PR TITLE
[3.9] Include all GitHub Actions CI workflow that we have in develop

### PR DESCRIPTION
**Pull request by ekohl**
This picks all changes to `.github/workflows/foreman.yml` and corrects the Katello version matching this stable branch.

### CODE REVIEW

**Comment by evgeni** [comment]
Katello needs to pin its deps, otherwise we pull too-new rex/tasks :/

**Comment by ekohl** [comment]
https://github.com/Katello/katello/pull/10971

**Comment by ekohl** [comment]
Further Katello work is needed:
```
/home/runner/work/foreman/foreman/katello/test/katello_test_helper.rb:1:in `require': cannot load such file -- simplecov (LoadError)
```

I've updated https://github.com/Katello/katello/pull/10974 with all the appropriate cherry picks.

**Comment by ekohl** [comment]
No changes to the PR itself, but forcing a full retest now that Katello changes have been merged.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
