### PR TITLE
Fixes #27114 - eslint errors in DateTimePicker

### PR DESCRIPTION
**Pull request by MariaAga**
and fixes a type in the word `equal`

### CODE REVIEW

**Review by tbrisker — CHANGES_REQUESTED** [review]
IIUC, the issue here is that using `setState` inside `componenetDidUpdate` is considered bad practice. Moving it out to a separate function doesn't fix that, just causes the linter to not identify the issue.

**Comment by MariaAga** [comment]
@tbrisker The issue with using setState inside componenetDidUpdate is that it can create an infinite loop if it is set without a condition, in this case there is a condition (From the [React Docs](https://reactjs.org/docs/react-component.html#componentdidupdate) )

**Comment by sharvit** [comment]
@MariaAga what about using https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

wouldn't it make more sense in this case?

**Comment by MariaAga** [comment]
@sharvit You're right and I switched it for the Date components. But for the Time components it will require the component to save the time in the state and not use it so I'm leaving the componenetDidUpdate there

**Comment by MariaAga** [comment]
@sharvit You're right and I switched it for the Date components. But for the Time components it will require the component to save the time in the state and not use it so I'm leaving the componenetDidUpdate there

**Review by sharvit — APPROVED** [review]
Thanks @MariaAga

**Comment by tbrisker** [comment]
Thanks @MariaAga and @sharvit !

**Review by tbrisker — APPROVED** [review]

**Pull request merged**
