### PR TITLE
Fixes #16461 - expose override in filter API

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
Failed due to a gitexception (?) [test]

**Comment by ares** [comment]
I suppose it's now [test foreman] [test katello] [test upgrade]

**Comment by dLobatog** [comment]
Unrelated failures - http://ci.theforeman.org/job/test_develop_pr_core/10349/

**Comment by dLobatog** [comment]
Merged as 9bdc4fea9711290431b611337ac72c2003dc8efd, thanks @ares!

**Pull request closed without merging**
