### PR TITLE
Fixes #22856 - Extract the strings from a bare foreman

### PR DESCRIPTION
**Pull request by bkearney**
Pulled from the latest of develop on 12 March, 2018.

### CODE REVIEW

**Comment by bkearney** [comment]
[test]

**Comment by tbrisker** [comment]
@bkearney thanks, shouldn't this be done as part of the branching process, since we only pull in new translations before release?

**Comment by bkearney** [comment]
@tbrisker I have some better translations downstream, and I was hoping to get them into transifex before strings were extracted. TO do that, I need this file merged.

**Review by tbrisker — APPROVED** [review]
Ack, makes sense. Test failure unrelated. Thanks @bkearney !

**Pull request merged**
