### PR TITLE
Fixes #27559 - match old login page button attr

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Satellite 6.6 have login button like this:

```<input type="submit" name="commit" value="Log In" class="btn btn-primary" data-disable-with="Log In">```

New LoginPage form have:

```<button type="submit" disabled="" class="login-pf-submit-button btn btn-lg btn-primary btn-block">Log In</button>```

in this PR I have added the missing attributes,
blocked by patternfly PR: https://github.com/patternfly/patternfly-react/pull/2682

### CODE REVIEW

**Review by sharvit — DISMISSED** [review]
Thanks @laviro LGTM

**Comment by ares** [comment]
great, please let me know when patternfly PR is in and dependency is bumped, I'm happy to merge this PR afterwards

**Comment by ares** [comment]
patternfly PR is now blocked on missing unit tests, @laviro any chance you'd be able to add it? This should be fixed in 1.24 time frame, s owe have ~5 weeks from now.

**Comment by Ron-Lavi** [comment]
Thanks @ares I've updated the patternfly PR with the needed unit test,
and rebased this PR.

**Comment by ares** [comment]
no longer blocked, the upstream PR has been merged, not sure which package this lives in, but my guess is we need to bump patternfly-react@2.38.2

**Comment by Ron-Lavi** [comment]
Thanks @ares for pushing this PR forward,
I created a PR to foreman-js (referenced above) to bump patternfly-react version
so we could use the new feature.

**Comment by Ron-Lavi** [comment]
Updated `@theforeman/vendor-dev": "^1.7.0"` with the new version of `patternfly-react` that has the fix :)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @laviro, works as expected!
Thanks @ares for pushing it forward, hope you don't mind I'll steal this one.

**Comment by ezr-ondrej** [comment]
@ekohl could you ack it for packaging?

**Comment by sharvit** [comment]
Needs a packaging PR?
https://github.com/theforeman/foreman-packaging/tree/rpm/develop#updating-npm-packages

**Comment by ezr-ondrej** [comment]
> Needs a packaging PR?
> https://github.com/theforeman/foreman-packaging/tree/rpm/develop#updating-npm-packages

Yeah, it does.
- [ ] theforeman/foreman-packaging#4142

**Review by ekohl — APPROVED** [review]
Packaging is merged so :+1: on that. I'll trust the other reviewers on the actual JS part of the change.

**Comment by ezr-ondrej** [comment]
Thanks @sharvit and @ekohl, merging!

**Comment by ares** [comment]
Thanks for closing the loop @laviro :-)

**Pull request merged**
