### PR TITLE
Fixes #29584 - Preload Puma in production

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Note I haven't done testing on this and it would be interesting to see graphs but I don't have the setup for this. @imaanpreet would you be able to have a look at this?

**Comment by ohadlevy** [comment]
does this imply simply to run it with --cluster? this might be easy to test with docker-compose

**Comment by ekohl** [comment]
@ohadlevy since we're already setting workers, we are using clustered mode.

**Comment by Imaanpreet** [comment]
@ekohl sure. What you want me to test here? Katello Installation, please correct me if I understood wrong.

**Comment by ekohl** [comment]
That's correct. I'm mostly interested in stability and memory usage when a large number of requests is fired at the Ruby application.

**Comment by Imaanpreet** [comment]
@ekohl, now the Katello nightly installation works fine.

**Comment by sthirugn** [comment]
this change works fine in my local test.

**Review by tbrisker — APPROVED** [review]
not very familiar with puma internals, but makes sense. Thanks @ekohl !

**Comment by ekohl** [comment]
On a related note: in the katello devel scenario this has been used for a while, as well as cluster mode. https://github.com/theforeman/puppet-katello_devel/blob/832864d6a222e6cb11495dddc40a05ea0cae6732/manifests/params.pp#L50

I wonder if it makes sense to allow devel config in the same way so a) developers test a more production like setup b) developers get a faster setup.

**Comment by tbrisker** [comment]
makes sense to me. developing closer to prod is always better.

**Pull request merged**
