### PR TITLE
Fixes #20608 - Add index for ssh_keys

### PR DESCRIPTION
**Pull request by mmack**
Adds a index :user_id to ssh_keys

### CODE REVIEW

**Comment by timogoebel** [comment]
@theforeman-bot ok to test

**Comment by timogoebel** [comment]
LGTM.
Any comments, @tbrisker?

**Comment by tbrisker** [comment]
:+1: once tests are green, but related issue includes several missing indices - should we add them all at once or would it be best to split the issue into several issues and add them one at a time?

**Comment by timogoebel** [comment]
@tbrisker: I'd suggest adding them one by one. Regardless of that: The other missing indices are actually present, but mysql still seems to do a full table scan. @mmack is still investigating.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Merged, thanks @mmack.

**Pull request merged**
