### PR TITLE
Fixes #28594 - Drop reports api endpoints

### PR DESCRIPTION
**Pull request by tbrisker**
This has been replaced with /config_reports 1.11.
We maintain one endpoint for POST to /api/reports for backwards
compatibility due to ansible and chef callbacks still using it. The
endpoint however now points to the newer controller action so the code
isn't duplicated.

### CODE REVIEW

**Comment by tbrisker** [comment]
docs: https://github.com/theforeman/theforeman.org/pull/1518/

**Comment by mmoll** [comment]
test failures related

**Comment by tbrisker** [comment]
all :green_apple: now :)

**Comment by tbrisker** [comment]
All tests were green, repushed to fix typo in commit message and aborted them to save ci resources.

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
