### PR TITLE
Fixes #37280 - remove typeAheadSelect

### PR DESCRIPTION
**Pull request by MariaAga**
Just noticed it when going over our code that nothing uses it anymore.
Searched all foreman & katello org and didnt find anything, also searched "import typeAheadSelect foremanReact" in github and found nothing.

### CODE REVIEW

**Review by kmalyjur — APPROVED** [review]
Thanks, I also couldn't find it used anywhere and everything seems to be deleted as it should

**Review by ekohl — APPROVED** [review]
Looks like the last use in Foreman was removed in 0b167ac6bdd7be65ce632049306bc442a27dda3d which is quite some time ago. I can't find any traces either so :+1: to cleaning up.

**Comment by ekohl** [comment]
JS tests look unrelated and it's simply coveralls complaining. Probably something we should address, but not here.

**Comment by jeremylenz** [comment]
Hey! Katello needed that.. :smile:

**Comment by MariaAga** [comment]
Removing it from Katello so it wont be a problem :) @jeremylenz

**Pull request merged**
