### PR TITLE
Fixes #37836 - Add possibility to display action when table is empty

### PR DESCRIPTION
**Pull request by kmalyjur**
image

Needed for [this PR](https://github.com/theforeman/foreman_remote_execution/pull/913).

### CODE REVIEW

**Review by Thorben-D — CHANGES_REQUESTED** [review]
Good idea! Do you think it makes sense to extend this feature to `TableIndexPage`?

**Comment by kmalyjur** [comment]
@Thorben-D Thank you for looking into it. In the end, I won't be using the code, so I don't know if it's okay to merge it anyway for some future use or just leave it. I changed the empty state to this now:
image

**Review by Thorben-D — APPROVED** [review]
I think your second version looks even better!
Given that you have already gone through the trouble, I would opt to merge the feature, as it is not very invasive and IMO pretty useful for the future.

**Review by MariaAga — APPROVED** [review]
Thanks @kmalyjur @Thorben-D!

**Pull request merged**
