### PR TITLE
Refs #29257 - clean up unused setting UI helpers

### PR DESCRIPTION
**Pull request by ezr-ondrej**
In 623542da3c16d4033b94317e0ac757021132b884 (#7775) setting helpers are moved into React.
Cleans up dead code after the shift.

### CODE REVIEW

**Review by lzap — DISMISSED** [review]
You're unstoppable! More of these. Letting @xprazak2 to confirm as he was working the React part.

**Comment by xprazak2** [comment]
Needs a rebase and then a merge :)

**Comment by ezr-ondrej** [comment]
Rebased :)

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
