### PR TITLE
Fixes #31802 - Include All option for Status for Appiled Errata Report

### PR DESCRIPTION
**Pull request by JaskaranNarula**
Issue: https://projects.theforeman.org/issues/31802
Seems like need to edit another file to fix the issue i.e app/lib/katello/concerns/base_template_scope_extensions.rb
So opened a different PR for that. -->> https://github.com/Katello/katello/pull/9213

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
we should handle the special value somewhere. We don't currently.
So we should probably add `input() == 'all' ? nil : input()`

**Comment by JaskaranNarula** [comment]
this makes sense, let me try that out and test it out again.

**Comment by ezr-ondrej** [comment]
Any progress here? :)

**Comment by jlsherrill** [comment]
@ezr-ondrej is this what you mean?  https://github.com/Katello/katello/pull/9213/files

**Review by jlsherrill — APPROVED** [review]
Tested along side https://github.com/Katello/katello/pull/9213/files and it works well!

**Review by ezr-ondrej — APPROVED** [review]
Yup it works with the Katello counterpart.
I believe the katello part should go first tho.

**Comment by jlsherrill** [comment]
Works for me, merging the katello pr!

**Comment by jlsherrill** [comment]
katello pr merged

**Comment by ezr-ondrej** [comment]
Thanks @JaskaranNarula and @jlsherrill !

**Comment by tbrisker** [comment]
for the record - tests did not run on this PR. 
Is this for 2.5 or 2.6? it was merged while the branching was still in progress, so while redmine lists it as fixed in 2.5 it is actually not present in the 2.5-stable branch. let me know if it needs to be cherry-picked or not.

**Comment by ezr-ondrej** [comment]
It would be nice, but it was not the intention as Katello counterpart got merged to katello only yesterday, so 2.6 it is.
Sorry for the mess :(

**Comment by tbrisker** [comment]
Looks like the katello part did make it into 4.1 so we can pull this in to 2.5, seems low-risk enough.

**Comment by ezr-ondrej** [comment]
CP 2.5: #8500

**Pull request merged**
