### PR TITLE
Fixes #29143 - Lock audit comment for locked templates

### PR DESCRIPTION
**Pull request by ofedoren**
ScreenShot-1582559904708

### CODE REVIEW

**Comment by ares** [comment]
Don't we need this field enabled if locked template is e.g. reassigned to another org? Is threse anything else that can be changed for locked template? Perhaps that is an edge case which does not need audit comments, just wanted to check if this was thought about.

**Comment by ofedoren** [comment]
@ares, if I'm not mistaken, for locked templates we can change org/loc, OS association (for provisioning templates) and `Value Type` in template inputs (which is weird in my opinion since the inputs are locked) and `Provider Type` (in job templates).

**Comment by ares** [comment]
value type I think is being fixed in a separate PR - https://github.com/theforeman/foreman/pull/7418, the question is, do we want to keep audit comments available for reassining the OS and taxonomies?

**Comment by xprazak2** [comment]
So do we want to keep comments available for locked templates? Should we close or do we want to go ahead with this?

**Review by ares — APPROVED** [review]
Thanks, since I'm the only one and it's quite minor thing to change if we realized, someone would like to comment on OS change, I'm OK with merging.

Works well, thanks @ofedoren!

**Pull request merged**
