### PR TITLE
Fixes #23117 - ovirt_ostype host param selects type [CP 1.19]

### PR DESCRIPTION
**Pull request by lzap**
(cherry picked from commit 0e7fa37473739557ed75870ce5e47645277f5c31)

### CODE REVIEW

**Comment by tbrisker** [comment]
looks like this led to a regression, please cp https://github.com/theforeman/foreman/pull/5886 as well once that's merged in develop

**Comment by tbrisker** [comment]
Related PR has been merged, please include it as well in this and the other cherry-pick.

**Comment by lzap** [comment]
Pushed.

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
