### PR TITLE
fixes #2327 - add simplecov code coverage reports

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
rebased.  @isratrade, would you mind reviewing?

**Comment by isratrade** [comment]
@domcleal yes, will do this afternoon

**Comment by isratrade** [comment]
@ohadlevy, @domcleal, I ran it and the coverage/index.html report is nice.

**Comment by ohadlevy** [comment]
hmm.. it seems like it works only on 1.9?

```
WARNING: SimpleCov is activated, but you're not running Ruby 1.9+ - no coverage analysis will happen
```

should we restrict it only to 1.9 in the test group?

**Comment by domcleal** [comment]
Yes, SimpleCov is 1.9 only and you need rcov before that.  It no-ops when on 1.8 though, so I'd leave it in on all Ruby versions as we then don't have to check for the SimpleCov module in test_helper.  I don't think measuring code coverage on 1.8 is particularly useful, so haven't added rcov too.

**Comment by ohadlevy** [comment]
so in order to avoid the STDERR can we have it load only on 1.9/2.0?

**Comment by domcleal** [comment]
@ohadlevy fixed, which meant restricting it to 1.9 in the test group :)

**Comment by ohadlevy** [comment]
merged - thanks

**Pull request closed without merging**
