### PR TITLE
Fixes #9170 - wrong nic order in libvirt domain

### PR DESCRIPTION
**Pull request by ghost**
Hi,

This is my fix for #9170. Although it does fix an issue with interface ordering in libvirt domains, I have no idea what the other consequences are. I did verify that the unit and functional tests were ok, but couldn't get the integration tests to work.

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by domcleal** [comment]
[test], likely unrelated

**Comment by dLobatog** [comment]
@eolamey I've been trying to reproduce this without any success, with various configurations of nics/bridges in libvirt, like @GregSutcliffe mentioned on the issue in Redmine.

Could you record a screencast/gif with what you're doing, or write a test that does that, and fails unless you introduce this change?

**Comment by ghost** [comment]
@eLobato thank you for taking the time to test this. The steps are described in the ticket, I'm not sure a screencast would help.

What version of ruby are you using for your test? I was wondering if the behaviour for `object_id` had changed, since we are using 2.1.5, which I'm not sure is fully supported by foreman.

I'm not sure I understand the original code behaviour though, as relying on the interpreter's identifier for ordering the Hash seems a bit odd.

**Comment by ares** [comment]
@eolamey so I tried to get into deep with this issue but as others, I was unable to reproduce even using Ruby 2.1.5. On the other hand, I think you're right with ordering. What platform do you run Foreman on? What webserver do you use? Could you please put following 

``` ruby
logger.fatal self.interfaces.inspect
logger.fatal compute_attributes.inspect
true
```

to the end of `add_interfaces_to_compute_attrs` and paste the result here? feel free to remove any sensitive data e.g. IP addresses. I'm mostly curious about `object_id` values as it seems that the first in `self.interfaces` might get higher value. In such case they would really reorder and that would be the cause. If the log proves it, `each_with_index` makes sense to me.

**Comment by ares** [comment]
@eolamey do you need any help with this? I'd like to help so we can get this in asap

**Comment by dLobatog** [comment]
@eolamey any news? :bell: :smile_cat:

**Comment by mmoll** [comment]
[test]

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as bc4cddaadf87f4baa2044359e3206cb930b7a778, thanks @eolamey!

**Comment by ghost** [comment]
I am so sorry, I just received a notification about the pull request but hadn't seen @ares comment 2 months ago, probably lost in my github notifications. Thank you for merging this, and once again sorry for not getting back to you sooner.

**Pull request closed without merging**
