### PR TITLE
Fixes #5391 - Authorizer test should use testing permission

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dmitri-d** [comment]
lgtm!

**Comment by dmitri-d** [comment]
lgtm, provided tests pass.

**Comment by domcleal** [comment]
Why the change in seed filenames?

**Comment by ares** [comment]
@domcleal we need it to add roles before admin user is created, when user is saved, we make sure that he has "Anonymous" role assigned, if it does not exist, the callback crashes. This fix is needed for https://github.com/theforeman/foreman/pull/1371 to work.

**Comment by domcleal** [comment]
Merged as 29a52c6 for Foreman 1.5.0, thanks @ares!

**Pull request closed without merging**
