### PR TITLE
Fixes #23117 - ovirt_ostype host param selects type [CP 1.18]

### PR DESCRIPTION
**Pull request by lzap**
(cherry picked from commit 0e7fa37473739557ed75870ce5e47645277f5c31)

### CODE REVIEW

**Comment by xprazak2** [comment]
[test foreman]

**Comment by tbrisker** [comment]
looks like this led to a regression, please cp https://github.com/theforeman/foreman/pull/5886 as well once that's merged in develop

**Comment by xprazak2** [comment]
Thanks! I opened: https://github.com/theforeman/foreman/pull/5927 to cp #5886

**Comment by tbrisker** [comment]
@xprazak2 - please also CP 9f3477a23957a4113aa04ca0ab41cccff26320f5, this fix introduced a regression that is fixed by that

**Pull request merged**
