### PR TITLE
Refs #2002 - Fog quick hack

### PR DESCRIPTION
**Pull request by ares**
See http://projects.theforeman.org/issues/2002 for more details.

### CODE REVIEW

**Comment by ohadlevy** [comment]
please move this code to /lib/fog_extentions

thanks

**Comment by ares** [comment]
@ohadlevy Sorry, I didn't notice there is already a place for fog patches. Fixed, please rereview.

**Comment by domcleal** [comment]
:+1: fixes the issue for me

**Comment by ohadlevy** [comment]
merged at b2c8312 thanks!

**Pull request closed without merging**
