### PR TITLE
Fixes #21576 - Always use Rails 5.1, drop Rails 5.0

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
[test upgrade]

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
[test foreman]

**Comment by xprazak2** [comment]
[test katello]

**Comment by mmoll** [comment]
Katello test failures are expected, as some Rails 5 changes are missing on thier side. The test failures with Ruby 2.3 seem unrelated.

IMHO this is ready to go.

**Comment by xprazak2** [comment]
The test failures on 2.3 come all from js tests, so they seem unrelated to me as well. The fix for katello failure is already [in develop](https://github.com/theforeman/foreman/commit/9e005438d6d69e00c44e602fe9a892607fd0d93c), so this seems good to go.

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
@ehelms any objection to merging this? once we do katello test may be broken until rails 5.1 changes are done there. This is afaiu one of two PRs that are blocking 1.17 branching.

**Comment by tbrisker** [comment]
[test katello]

**Comment by mmoll** [comment]
The katello test is broken because of https://github.com/theforeman/foreman-tasks/pull/300 and a similar change missing on their side.

**Comment by ehelms** [comment]
It would be nice if we could get that foreman-tasks change merged and released and at least a Katello PR open before merging this to prevent build up of breakages. @jturel @jlsherrill  -- last I recall y'all had been working on the Katello side of Rails 5. Thoughts?

**Comment by mmoll** [comment]
@ehelms https://github.com/Katello/katello/pull/7094 would also need a merge

**Comment by mmoll** [comment]
The alias_method_chain thing was already in -tasks and Katello, but got reverted for Foreman 1.16, iirc.

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
foreman_docker is not compatible with 5.1, see https://github.com/theforeman/foreman-docker/pull/206.

As foreman_docker is a hard dependency of Katello, this is blocking Katello compatibiliy implicitly now.

**Review by dLobatog — COMMENTED** [review]
Let's try now that foreman-docker 4.0.0 with Rails 5 fixes is out.

**Comment by dLobatog** [comment]
[test katello]

**Comment by mmoll** [comment]
@dLobatog we will need a gem release of foreman_docker first as Katello does not use foreman_docker from git.

**Comment by dLobatog** [comment]
@mmoll But there is a gem release out already 😄 https://rubygems.org/gems/foreman_docker/versions/4.0.0

**Comment by mmoll** [comment]
https://github.com/Katello/katello/pull/7127

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
OK, this is down to 7 test failures in Katello - with https://github.com/Katello/katello/pull/7128 it might get to 2.

I would recommend to merge this **now** to get core to Rails 5.1 and **then** fix all the plugins, as only the plugin maintainers can fix the remaining problems with their specfic knowledge.

**Comment by mmoll** [comment]
One last rebase, all 💚 except Katello.

**Comment by ehelms** [comment]
[test katello]

**Comment by mmoll** [comment]
[test katello]

**Comment by dLobatog** [comment]
I'm OK with merging, and potentially breaking plugins (and working on fixing them myself) but I don't see a similar change in foreman-packaging yet - which means broken nightlies for an unknown amount of time (especially since many people will not pick this up during christmas holidays).

@ehelms Is ror51 ready yet? If so what's the effort like to update the current packaging to that?

**Comment by ehelms** [comment]
Nighties are already broken. As soon as we upgraded to 5.0 they broke. But
per the emails we agreed that a period of broken must occur and to mimimize
that. I have a test Copr SCL repository ready to test and a PR ready to go.
Once this is merged I need to just add in Foreman RPM updates and we can
review packaging plus runtime test it.

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
Thanks everyone! Let's hope all plugins can catch up quickly

**Pull request merged**
