### PR TITLE
fixes #26842 - altlinux: fix mediumpath

### PR DESCRIPTION
**Pull request by timogoebel**
Extracted from #6700.

### CODE REVIEW

**Review by tbrisker — DISMISSED** [review]
Thanks @timogoebel !

**Comment by timogoebel** [comment]
Test failure looks unrelated, but a merge commit snuck into the branch.

**Comment by lzap** [comment]
This is a great chance to move the method into Operatingsystem and only override it for relevant implementations.

```
app/models/operatingsystems/junos.rb
6:  def mediumpath(medium_provider)
7-    medium_provider.medium_uri.to_s
8-  end
9-

app/models/operatingsystems/rancheros.rb
8:  def mediumpath(medium_provider)
9-    ''
10-  end
11-

app/models/operatingsystems/gentoo.rb
4:  def mediumpath(_medium_provider)
5-  end
6-
7-  def url_for_boot(_medium_provider, file)

app/models/operatingsystems/vrp.rb
5:  def mediumpath(medium_provider)
6-    medium_provider.medium_uri.to_s
7-  end
8-

app/models/operatingsystems/redhat.rb
6:  def mediumpath(medium_provider)
7-    uri = medium_provider.medium_uri
8-
9-    case uri.scheme

app/models/operatingsystems/freebsd.rb
10:  def mediumpath(medium_provider)
11-    medium_provider.to_s do |vars|
12-      transform_vars(vars)
13-    end

app/models/operatingsystems/archlinux.rb
5:  def mediumpath(medium_provider)
6-    medium_provider.medium_uri.to_s
7-  end
8-

app/models/operatingsystems/xenserver.rb
5:  def mediumpath(medium_provider)
6-    medium_provider.medium_uri.to_s
7-  end
8-

app/models/operatingsystems/coreos.rb
8:  def mediumpath(medium_provider)
9-    medium_provider.medium_uri('$arch-usr/') do |vars|
10-      transform_vars(vars)
11-    end.to_s

app/models/operatingsystems/suse.rb
5:  def mediumpath(medium_provider)
6-    medium_provider.medium_uri.to_s
7-  end
8-

app/models/operatingsystems/nxos.rb
6:  def mediumpath(medium_provider)
7-    medium_provider.medium_uri.to_s
8-  end
9-
```

**Review by tbrisker — APPROVED** [review]
Thanks @timogoebel ! I'll merge this and cp it to 1.22-stable so it's working, unification can be done in a separate issue for develop

**Comment by tbrisker** [comment]
1.22- 7d3f1b77b

**Pull request merged**
