### PR TITLE
Fix #25252 - Fix webpack in forklift/vagrant dev environment

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by amirfefer** [comment]
have you tried using `bundle exec ./script/foreman-start-dev` ?

**Comment by ekohl** [comment]
IMHO this script should be removed and we should standardize on using `bundle exec foreman start`. Especially when using forklift since we there set up the `.env` file with the right parameters which this script ignores.

**Comment by sbernhard** [comment]
Didn't tried to start with bundle exec. 
I'm always starting my dev system by switching into the vagrant box with "vagrant ssh centos7-devel" and afterwards with ./scripts/foreman-start-dev

Without the change of this PR, I dont get the webpack running.

**Comment by ekohl** [comment]
@sbernhard please try it with `bundle exec foreman start` instead. It's the supported way in forklift. This script isn't because it doesn't respect `.env`. We put the right settings there in the forklift provisioning: https://github.com/theforeman/puppet-katello_devel/blob/master/templates/env.erb

**Comment by sbernhard** [comment]
Thanks @ekohl but unfortunately, this doesn't work for me. The webpack resources are not available.

Additionally, if "we" think, the foreman-start-dev shouldn't be used, we should remove it. I would prefer to print a message after the forklift system comes up (or after connecting with ssh) how to start foreman in dev mode and in normal mode.

**Comment by sbernhard** [comment]
Any update? In case you want to remove the foreman-start-dev script - remove it. Otherwise I would be happy that the script works as expected.

**Review by tbrisker — APPROVED** [review]
as long as this script is still present, we should make it work. No point arguing about it's presence every time someone sends a PR for it - lets open the discussion on discourse and get a decision.

**Pull request merged**
