### PR TITLE
refs #2445 -  move back FreeBSD icon

### PR DESCRIPTION
**Pull request by mmoll**
f6014fb broke display of the icon on the hosts page for me. Or am I missing something in the Debian nightlies?

### CODE REVIEW

**Comment by dLobatog** [comment]
@mmoll If you check the helper that displays this icon, it uses the right capitalization @bkearney changed it to - https://github.com/theforeman/foreman/blob/develop/app/helpers/operatingsystems_helper.rb#L28 

Maybe you're not seeing it for some other reason?

**Comment by mmoll** [comment]
I'm not getting it, the capitalization in that file is `FreeBSD`, not `Freebsd`, correct?

**Comment by dLobatog** [comment]
Merged as 9e02c5f50060597e84d9d38604ef8bfb5dbc74a4, thanks @mmoll!

**Comment by bkearney** [comment]
@dLobatog can you please check https://bugzilla.redhat.com/show_bug.cgi?id=1283668. This is what caused me to change it.

**Comment by dLobatog** [comment]
@bkearney I think that happened because the name of the OS created was not 'Freebsd' (case insensitive). Family is not enough to show the icon in Foreman, the name has to match an OS. Otherwise Ubuntu would show up with the Debian family icon instead of Ubuntu, CentOS as Red Hat, etc...

**Comment by bkearney** [comment]
@dLobatog so, how should I fix that bug?

**Comment by mmoll** [comment]
@bkearney I _think_ in that BZ the user created an OS with the name **Freebsd** and family **FreeBSD**, while both need to be **FreeBSD**, as this is the name by the fact, Facter is returning.

**Comment by dLobatog** [comment]
Nope, name 'freebsd', or 'Freebsd', etc.. all work. The person who opened the bug chose 'family FreeBSD' but the OS name had a different name. If the name doesn't contain 'freebsd' in it (regardless of capitalization) it won't show any icon. I don't think that needs to be fixed?

**Pull request closed without merging**
