### PR TITLE
fixes #2713 - do not update nics table on every host update as a workaround to bug #2489

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
looks much better :+1:

**Comment by isratrade** [comment]
@ohadlevy, yes, I like it much better in the bmc.rb model than looping through all the interfaces in the hosts_controller and checking if 1 of 3 fields were changed.

**Comment by isratrade** [comment]
re-committed with attrs_will_change!, instead of mac_will_change!

**Comment by domcleal** [comment]
That's much neater.  Could you update the tests also please?  A couple were added to test updated_at, they should test this instead, preferably with a non-privileged user too.

**Comment by isratrade** [comment]
re-commited.  testing workarounds is just as hit-or-miss as the actual code.  The test needed another parameter such as :mac in the update.  Otherwise it fails and I don't know why.  The param :mac is unchanged in the test.

**Comment by domcleal** [comment]
Just to check if I'm clear on the intention, is it to prevent updates to the NIC table if no change has been made too?  The updated_at hack would have caused this always to appear dirty, while the intention here is to only dirty the fields if set?  That's what the issue description suggests to me.

If so, I still see an UPDATE being made to the nics table if I edit a host that contains a BMC field and save with no changes.  Two attr setters are called during the edit, `username=` and `provider=`, which I guess is because both are set by the web page.  I think it should only call `attr_will_change!` if the value has actually changed?  Or is something else wrong here and Rails shouldn't call the setter unless the value has changed?

**Comment by isratrade** [comment]
@domcleal, I will check.  I thought that passord= or username= is only called if the valued is changed

**Comment by isratrade** [comment]
@domcleal, good catch.  I updated the PR and added 

``` ruby
self.attrs_will_change! if attrs_changed?
```

**Comment by domcleal** [comment]
@isratrade now it doesn't update usernames or providers, as `attrs_changed?` will always return false :)

**Comment by isratrade** [comment]
@domcleal, re-commited with change to commit message - fixes #2489 again rather than fixes #2713 which was closed.

**Comment by isratrade** [comment]
@domcleal, should I ignore the "test failures" from Jenkins??

**Comment by domcleal** [comment]
@isratrade yep, looks like it was having network problems.

I think we should probably fix this to only call will_change if the value has actually changed.  I like the improvement and removing of the hack, but it looks trivial to me to only call when it's changed.  Can we simply check the old value of `attrs[method]` against the new value and see if it's different?

**Comment by isratrade** [comment]
re-committed and changed commit message back to fixes #2713

**Comment by ohadlevy** [comment]
merged as ecd9c9c - thanks!

**Pull request closed without merging**
