### PR TITLE
Add single commit check to GH actions

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like it's working, i aborted all of the other CI tests. 
When there was one commit, the check was green, now with the extra test commit it is red.

@theforeman/core what do you think about this check? it's basically the outcome of me-- too many times rebasing when I should have squashed.

**Comment by ShimShtein** [comment]
@tbrisker, it will require extra step from PR author - if the PR has more than one commit, the author will have to squash them.
Isn't it better to allow only squash merges for the repo?

**Comment by ekohl** [comment]
On cherry picks it may be valid to have multiple commits in a single PR. Not sure how common those are in foreman.git, but in foreman-installer we regularly use that.

Another thing to note is that the PR processor also can't deal well with the actual commits changing. It parses the commits from the PR to set the Fixed in version. It also tells you it has invalid commits and as a required check, it does block merging. @tbrisker is an admin, so he can override it but I am wondering when this would actually prevent anything.

**Comment by sharvit** [comment]
A nice addition in my opinion, as far as it only reminds me and not blocking me from squashing and merging as it would be an extra step for the committer.

**Comment by tbrisker** [comment]
> @tbrisker, it will require extra step from PR author - if the PR has more than one commit, the author will have to squash them.
> Isn't it better to allow only squash merges for the repo?

The check is not blocking - it's just to make sure that the reviewer notices there is more than one commit and it might need squashing (sometimes having multiple commits is just fine).

**Review by lzap — CHANGES_REQUESTED** [review]
Please squash into one so we can also see it does work.

Before we merge let's check for warning jobs, but my hopes are low: https://github.community/t/non-blocking-warning-job/127108

**Comment by tbrisker** [comment]
updated to one commit. Looks like actions only have either success or failure exit codes right now: https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions

**Comment by tbrisker** [comment]
Merging following discussion on @theforeman/core call today.

**Comment by lzap** [comment]
Yeah, we could use https://github.com/marketplace/actions/github-checks or labels/comments too but I am fine with this.

**Pull request merged**
