### PR TITLE
Fixes #31597 - Add description for host param in LDAP

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Comment by yifatmakias** [comment]
ok to test

**Review by ofedoren — COMMENTED** [review]
Thanks, @adiabramovitch!

LGTM, although the commit message should probably be something like `Fixes #31597 - Add description for host param in LDAP`

Since it's about updating API documentation (hammer just fetches it).

**Comment by adiabramovitch** [comment]
Thank you, I changed it @ofedoren

**Comment by ofedoren** [comment]
@adiabramovitch, the commit message is still `Fixes #31597 - Add decription to --host` :)

You can change it locally via `git commit --amend` and then `git push --force`

**Comment by ezr-ondrej** [comment]
@adiabramovitch the commit message still doesn't include the `Fixes #31597 -` part. You should include that at the beggining of the line while editing the commit message by `git commit --amend` :)

**Review by ofedoren — APPROVED** [review]

**Review by ezr-ondrej — APPROVED** [review]
Thank you @adiabramovitch, nice addition!
And thanks to @ofedoren for reviewing :+1:

**Comment by tbrisker** [comment]
Congrats @adiabramovitch on your second PR getting merged! I've sent you an invite to the Foreman organization, so future PRs will automatically trigger CI.

**Pull request merged**
