### PR TITLE
Fixes #28109 - move export button from pages to routes

### PR DESCRIPTION
**Pull request by MariaAga**
The `PageLayout` component has moved to `routes` but `ExportButton` stayed behind in `pages/common/PageLayout/components`

### CODE REVIEW

**Review by xprazak2 — APPROVED** [review]
Works for me, we can merge after branching.

**Review by amirfefer — APPROVED** [review]
LGTM :+1:

**Review by tbrisker — APPROVED** [review]
This is just moving files around, i'm fine with getting it in prior to branching assuming [test foreman] is green.

**Comment by tbrisker** [comment]
[test foreman]

**Pull request merged**
