### PR TITLE
Fixes #21578 - Cmp.PropTypes to Cmp.propTypes

### PR DESCRIPTION
**Pull request by sharvit**
Chart, ChartBox and StatisticsChartsList are using prop-types in a wrong
way.

Chart is declaring about prop-types it is never used.

http://projects.theforeman.org/issues/21578

### CODE REVIEW

**Comment by sharvit** [comment]
[test foreman]

**Comment by sharvit** [comment]
Any idea why Travis is failing because of mismatched snapshots?

The changes shouldn't affect the snapshots and it is not failing locally.

**Comment by ohadlevy** [comment]
@sharvit this is the same failure @danseethaler is facing on #4944 - did you figure out which npm package shoudld be pinned?

**Comment by sharvit** [comment]
@ohadlevy - check out my comment on @danseethaler pr https://github.com/theforeman/foreman/pull/4944

**Review by waldenraines — APPROVED** [review]
This looks fine to me, approved pending passing tests.

**Comment by ohadlevy** [comment]
@sharvit please rebase

**Comment by sharvit** [comment]
Rebased and passed all tests.

**Pull request merged**
