### PR TITLE
Fixes #33802 - cleanup leftover statistics methods

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Just a cleanup of unused methods.

The only current user is being refactored in https://github.com/theforeman/foreman_statistics/pull/37

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test upgrade]

**Comment by ofedoren** [comment]
[test upgrade]

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej !

**Comment by tbrisker** [comment]
upgrade failures unrelated. Should this be merged before or after 3.1 branching? I assume the associated fix in f-statistics should be released when this is merged or the plugin will break.

**Comment by ezr-ondrej** [comment]
> upgrade failures unrelated. Should this be merged before or after 3.1 branching? I assume the associated fix in f-statistics should be released when this is merged or the plugin will break.

Yup, tho there are other fixes, that need to get into 3.1, so I'm going to get a release for 3.1 anyway.

**Pull request merged**
