### PR TITLE
Fixes #22163 - Update patternfly-react

### PR DESCRIPTION
**Pull request by danseethaler**
No snapshots were harmed in the making of this PR.

http://projects.theforeman.org/issues/22163

### CODE REVIEW

**Comment by mmoll** [comment]
[test upgrade]

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
@danseethaler please update the redmine ticket with the feature that requested the upgrade - thanks :)

**Comment by danseethaler** [comment]
@ohadlevy the Redmine currently says "Version 0.22.1 has a fix on the ListView that brings it into alignment with the main patternfly repo."

Did you want me to add something more?

**Comment by ohadlevy** [comment]
just in redmine its usually good to link the issues, as if we end up
cherry-picking a feature we can see all dependent items as well.

**Comment by danseethaler** [comment]
@ohadlevy ah I see, nice feature. Done.

**Pull request merged**
