### PR TITLE
Fixes #19728 - set admin user in rake console

### PR DESCRIPTION
**Pull request by lzap**
Backport of https://github.com/theforeman/foreman/pull/4563 without new admin account.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@lzap which one is the correct PR? this or #4563 ?

**Comment by lzap** [comment]
Both, this one is only for 1.15, see above.

**Comment by dLobatog** [comment]
[test katello]

**Review by dLobatog — APPROVED** [review]
Errors in the Katello job shouldn't show up after #4569 was merged, let's wait for that.

I still think there isn't any harm on the current behavior and insist it's not a Foreman feature - so in my view, it's *not* a regression, just an inconvenience for developers. Given 3 people want this for 1.15 (https://github.com/theforeman/foreman/pull/4563) I'll put it in 1.15 though.

@lzap thanks for separating this, IMO it makes much less risky than the full blown solution.

**Comment by lzap** [comment]
Thanks a lot for including this, it's not just for devs but also users (and Red Hat support teams).

**Comment by dLobatog** [comment]
Oh shoot.. since https://github.com/theforeman/foreman/pull/4569 wasn't cherry-picked to 1.15 yet, tests failed again. I'll cherry-pick it to the branch and rerun tests.

**Comment by dLobatog** [comment]
Cherry-picked, 0a95c528a63702f4ac2acb02d2407fff67fbbe6c
[test katello]

**Comment by dLobatog** [comment]
I kicked it with Katello 3.4 here (http://ci.theforeman.org/job/test_develop_pr_katello/database=postgresql,ruby=2.2,slave=fast/) - success!

**Comment by dLobatog** [comment]
Thanks @lzap !

**Pull request merged**
