### PR TITLE
Fixes #19534 - removed excessive encryptor logging

### PR DESCRIPTION
**Pull request by lzap**
I am still keeping the two most important one, when en/decryption fails, but we only log this once.

### CODE REVIEW

**Comment by timogoebel** [comment]
[test upgrade]

@lzap : Thanks. We should do either this or use a dedicated logger for this. I don't see any value in logging this at all. I'll leave this open for a bit before merging to give people time to comment on this.

**Review by tbrisker — APPROVED** [review]

**Comment by lzap** [comment]
I accidentaly pushed some other code into this PR, fixed. Sorry about that.

**Comment by lzap** [comment]
Tests failures unrelated, gem deps issues plus assert

    NoMethodError: undefined method `split' for nil:NilClass

**Comment by timogoebel** [comment]
Merged, thanks @lzap.

**Pull request merged**
