### PR TITLE
Fixes #3840 - Removes unused Signo related code

### PR DESCRIPTION
**Pull request by ares**
I'm on doubt whether we should also add a migration that would remove signo_sso and signo_url settings from database. Ideas?

### CODE REVIEW

**Comment by lzap** [comment]
I think we can add manual upgrade step for this one.

Do we have a page or branch with 1.7 upgrade instructions already? Let's
just put it there... ;-)

LGTM

## 

Later,
 Lukas #lzap Zapletal

**Comment by ohadlevy** [comment]
why not remove the setting? it would linger forever on old installs?

**Comment by ares** [comment]
I always try to avoid data manipulation in migrations since it can break easily. Deletion is probably the safest operation so I'll add it using some FakeSetting class.

**Comment by ares** [comment]
Migration added

**Comment by GregSutcliffe** [comment]
Seems fine:

```
sqlite> select * from settings where name like '%sign%';
67|signo_sso||Use Signo SSO for login|Setting::Auth|boolean|--- false
68|signo_url||Signo SSO url|Setting::Auth|string|--- http://url/

$ bundle exec rake db:migrate
==  RemoveSignoSetting: migrating ==
==  RemoveSignoSetting: migrated (0.0012s) ==

sqlite> select count(*) from settings where name like '%sign%';
0
```

Merged as 4fdfa62, thanks!

**Pull request closed without merging**
