### PR TITLE
Use patternfly v4 fonts and breadcrumbs

### PR DESCRIPTION
**Pull request by sharvit**
This PR works with https://github.com/theforeman/foreman-js/pull/125 and contains 2 commits.

1. use pf4 fonts and link colors
2. use pf4 breadcrumbs

# After:
screenshot-centos7-luna-devel sharvit-fedorabook-t480s example com-2020 03 12-14_31_06

# Before
screenshot-centos7-luna-devel sharvit-fedorabook-t480s example com-2020 03 12-14_40_07

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
Thanks, @sharvit! :+1: 
How about splitting this into 2 PRs (fonts and breadcrumbs)?

**Comment by ares** [comment]
I like it :+1:

**Comment by sharvit** [comment]
> Thanks, @sharvit! 
> How about splitting this into 2 PRs (fonts and breadcrumbs)?

Yes, First I wanted to prove I can use pf4 styles and components so I can merge https://github.com/theforeman/foreman-js/pull/125

Now I will do some separation, fix tests and apply some better practices :+1:

**Comment by sharvit** [comment]
@amirfefer see https://github.com/theforeman/foreman/pull/7519

**Comment by tbrisker** [comment]
depends on GH-7519 to go in first.

**Comment by jschuler** [comment]
@sharvit the test failure for breadcrumbs can be fixed like this
 https://github.com/theforeman/foreman/pull/7555/commits/c254b9dec05f3b00a7a494ca1a3d1fd53840fb01#diff-bb4404953dade08a64e59d9afa45fb3cL79

**Comment by sharvit** [comment]
Closed and opened https://github.com/theforeman/foreman/pull/7712 instead

**Pull request closed without merging**
