### PR TITLE
SyntaxError (/root/foreman_dev/foreman/app/helpers/layout_helper.rb:96: ...

### PR DESCRIPTION
**Pull request by skihero**
...invalid multibyte char (US-ASCII)

### CODE REVIEW

**Comment by ohadlevy** [comment]
Thanks!
I think the right way to fix it would be
<a class="close" href="#" data-dismiss="alert">&times;</a>

**Comment by skihero** [comment]
Ah, yes. Offending character blinded me.

**Comment by skihero** [comment]
Ah, yes. Offending character blinded me.

**Comment by ohadlevy** [comment]
why did you close it ? it seems like github didnt escape my html

**Comment by skihero** [comment]
Let me correct it and open a proper pull request.

**Comment by ohadlevy** [comment]
i've already fixed it in another commit afair

**Comment by skihero** [comment]
Oh yes, the pastebin that you had shared had this.

**Pull request closed without merging**
