### PR TITLE
Fixes #25666 - unpin daemons gem

### PR DESCRIPTION
**Pull request by mmoll**
This reverts commit db2eae404317e62248b3e7b500c6ade0c4a75cff.

### CODE REVIEW

**Comment by mmoll** [comment]
daemons 1.3.1 with a fix has been released.

**Comment by ekohl** [comment]
Is there a way in Rubygems to mark it as broken with `1.3.0` or do we not care about this?

**Comment by mmoll** [comment]
RPMs are on 1.2.3 and the only problems were seen with DEBs when 1.3.0 got released. So I think it's not really relevant. Otherwise we could set `>= 1.3.1` here and need to update our RPMs.

**Review by ekohl — APPROVED** [review]
Sounds like it's fine in the current version.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
