### PR TITLE
Fixes #20897 - change description for 'default' to help tooltip

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by orrabin** [comment]
ok to test

**Review by tbrisker — APPROVED** [review]
ACK, pending tests.

**Review by dLobatog — COMMENTED** [review]
@GregSutcliffe @ehelms @ohadlevy Could you add @shiramax to theforeman org?

**Comment by GregSutcliffe** [comment]
@shiramax @dLobatog invite to the Org sent

**Comment by tbrisker** [comment]
Thanks @shiramax and welcome!

**Pull request merged**
