### PR TITLE
Fixes #36408 - Remove '---' to allow to have different formats

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Quick format fix @ianballou

**Comment by ianballou** [comment]
@sbernhard mind posting screenshots of the difference?

**Comment by ianballou** [comment]
Also @sbernhard can you make a new redmine issue for this since the old one is closed?

**Comment by sbernhard** [comment]
All other report template don't have this "---" at the end of the file. 

Changed the ticket reference @ianballou

**Review by ianballou — APPROVED** [review]

**Pull request merged**
