### PR TITLE
Fixes #20591 - full ovirt cloud-init support

### PR DESCRIPTION
**Pull request by iNecas**
Currently, the cloud-init integration supports only a sub-set of
cloud-init commands. With `custom_script` support, one can pass
arbitrary cloud-init yaml to the managed host and make sure
the provisioned host will get it unchanged (which is not the case
when passing the user data currently, as the rbovirt parses into
ovirt-specific keys)

After the change, we would pass the cloud-init template to the ovirt as
is via `custom_script` ovirt functionality, and it would get to the
cloud-init directly, without any ovirt pre-processing.

Depends on https://github.com/fog/fog/pull/3961

### CODE REVIEW

**Comment by orrabin** [comment]
Tested with the fog change and this works well.
fog-ovirt change is now merged.

**Comment by mmoll** [comment]
what's the status here? ☝️

**Comment by orrabin** [comment]
[test katello]

**Comment by orrabin** [comment]
[test foreman]

**Comment by orrabin** [comment]
@iNecas could you please rebase this?

**Comment by mmoll** [comment]
@iNecas ping? :)

**Comment by iNecas** [comment]
Sry for delay, rebased.

**Comment by iNecas** [comment]
@orrabin mind having a look? Also, it seems we don't have cloudinit support in oVirt v4 API. It seems we need to pass a VM object to start method, with `initialization` attribute set with `custom_script` http://www.rubydoc.info/gems/ovirt-engine-sdk/OvirtSDK4/Vm#initialization=-instance_method

**Comment by iNecas** [comment]
Tracking the apiv4 cloudinit support in http://projects.theforeman.org/issues/23370

**Review by orrabin — APPROVED** [review]
This was already tested with v3 and worked well. I don't think we should keep it open until support is added for v4 since it already has it's own issue open.

**Comment by orrabin** [comment]
Merging this as per my last comment, fixes for v4 will be added on the fog-ovirt side.

**Comment by orrabin** [comment]
Thanks @iNecas !

**Pull request merged**
