### PR TITLE
Fixes #24478 - properly sanitize class name

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
reproducing steps and more detail can be found at https://github.com/theforeman/foreman/pull/5888#issue-204817657

**Comment by ares** [comment]
@lzap I ran discovery tests with this locally and this time they are green

**Review by lzap — APPROVED** [review]
Works for me, thanks for poking me.

**Comment by lzap** [comment]
I will let @xprazak2 to comment, I haven't yet reproduced or tested this.

**Comment by xprazak2** [comment]
Works for me. Thanks everyone!

**Pull request merged**
