### PR TITLE
Fixes #24720 - listen interface aligned in dev script

### PR DESCRIPTION
**Pull request by lzap**
[SKIP CI]

Just dev setup improvement for newcomers, this is confusing.

### CODE REVIEW

**Comment by bastilian** [comment]
Isn't this script obsolete, since there is also the `Procfile`?

**Comment by ekohl** [comment]
It was introduced in d8cbf89c068e0afab79beef0d9c5ee1acb0f62ff so longer after the Procfile. IMHO we should only have the Procfile so there's one recommended way.

**Comment by bastilian** [comment]
:+1: for only having the `Procfile`

**Comment by lzap** [comment]
I am all for dropping this the very first moment Procfile allows us an interactive console. Debugging is not possible via foreman gem, thus let's keep this. I am not using the gem for my development, that's show-stopper.

We have agreed on having this in the git repo. Let's not start over again.

**Comment by ekohl** [comment]
How about using `foreman` to start webpack here? `foreman start webpack &` instead of duplicating the effort?

**Comment by lzap** [comment]
Please have this merged and let's move the discussion somewhere else. This is a trivial patch, 0.0.0.0 is already present for the webserver and this aligns the webpack. I was approached from the field with this problem.

**Comment by lzap** [comment]
Noticed that @akofink uses that script as well. Do you know other devs using the script with commit access? ;-)

**Comment by akofink** [comment]
Actually, I personally don't use this script. I run ./node_modules/.bin/webpack-dev-server directly. :man_shrugging:

**Comment by ares** [comment]
I also run processes manually but I ser no harm in having Procfile and separate script doing the same. I think we had this discussion already when this script was merged. IMHO Procfile approach forces devs to use pry-remote and brings little value over shellscript.

**Review by tbrisker — APPROVED** [review]
let's not continue the argument, it's a 3 line script that is useful for some while others prefer not to use it. adding this parameter doesn't change that.

**Pull request merged**
