### PR TITLE
Fixes #29839 - Generate at should be current date

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Thanks @ranjan! I'm just bit worried about the user to be confused, when the value is preset for him.
Do you think users will understand that better?

**Comment by ranjan** [comment]
Hello @ezr-ondrej 
The current behavior is incorrect, it shows date 01-01-1970. I think it would be better to show current date.

In the previous version of foreman it shows the current date. but this change https://github.com/theforeman/foreman/commit/810504a13c23dedbcbf31cb3c46385411009bf1c#diff-ad91167458390bb9a369267bb6c1d852 override the default date to blank

**Comment by ezr-ondrej** [comment]
You sure that's what happening? This is what I've got: 
report_generate_at-2020-06-02_12 52 07

**Comment by ezr-ondrej** [comment]
This has been already fixed in 2.1 and defaults to current date.

**Comment by ezr-ondrej** [comment]
Thanks for your contribution @ranjan

**Pull request closed without merging**
