### PR TITLE
Fixes #35069 - ApplicationRecord.<=> undefined method 'name'

### PR DESCRIPTION
**Pull request by stejskalleos**
After 6.1 upgrade some tests (eg. Foreman Discovery)
are failing with following error:
```
NoMethodError: undefined method `name' for 0:Integer
    app/models/application_record.rb:43:in `<=>'
```

How to verify the fix:
* Enable `foreman_discovery` plugin
* Run `bundle exec rails test:discovery TEST=~/your-path-to-foreman_discovery/test/unit/host_discovered_test.rb`
(There are some other tests that are failing but that's not the problem of this PR)

### CODE REVIEW

**Comment by adamruzicka** [comment]
Why is it trying to compare an application record object against an integer?

**Comment by stejskalleos** [comment]
> Why is it trying to compare an application record object against an integer?

Great question for which I don't have answer. If you try it on Foreman 3.3, `<=>` method is not called at all.

**Review by Ron-Lavi — APPROVED** [review]
Looks safe to me :)

**Comment by adamruzicka** [comment]
Capturing a stacktrace in case we run to some issues later down the road

```
foreman/app/models/application_record.rb:42:in `<=>'                                                                                                                                                                                                         
gems/activemodel-6.1.6/lib/active_model/type/helpers/numeric.rb:14:in `cast'                                                                                                                                                       
gems/activemodel-6.1.6/lib/active_model/attribute.rb:175:in `type_cast'                                                                                                                                                            
gems/activemodel-6.1.6/lib/active_model/attribute.rb:43:in `value'                                                                                                                                                                 
gems/activemodel-6.1.6/lib/active_model/attribute.rb:155:in `changed_from_assignment?'                                                                                                                                             
gems/activemodel-6.1.6/lib/active_model/attribute.rb:60:in `changed?'                                                                                                                                                              
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:79:in `attribute_changed?'                                                                                                                                   
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:45:in `changed?'                                                                                                                                             
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:35:in `change_to_attribute'                                                                                                                                  
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:28:in `block in changes'                                                                                                                                     
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:27:in `each'                                                                                                                                                 
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:27:in `each_with_object'                                                                                                                                     
gems/activemodel-6.1.6/lib/active_model/attribute_mutation_tracker.rb:27:in `changes'                                                                                                                                              
gems/activemodel-6.1.6/lib/active_model/dirty.rb:231:in `changes'                                                                                                                                                                  
foreman/app/models/concerns/strip_whitespace.rb:9:in `strip_spaces'                                                                                                                                                                                          
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
gems/activesupport-6.1.6/lib/active_support/callbacks.rb:824:in `_run_validation_callbacks'
gems/activemodel-6.1.6/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
gems/activemodel-6.1.6/lib/active_model/validations.rb:337:in `valid?'
gems/activerecord-6.1.6/lib/active_record/validations.rb:68:in `valid?'
gems/activerecord-6.1.6/lib/active_record/validations.rb:84:in `perform_validations'
gems/activerecord-6.1.6/lib/active_record/validations.rb:47:in `save'
gems/activerecord-6.1.6/lib/active_record/transactions.rb:298:in `block in save'
gems/activerecord-6.1.6/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
gems/activerecord-6.1.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
gems/activerecord-6.1.6/lib/active_record/transactions.rb:298:in `save'
gems/activerecord-6.1.6/lib/active_record/suppressor.rb:44:in `save'
gems/activerecord-6.1.6/lib/active_record/persistence.rb:38:in `create'
gems/activerecord-6.1.6/lib/active_record/relation.rb:795:in `_create'
gems/activerecord-6.1.6/lib/active_record/relation.rb:99:in `block in create'
gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `block in scoping'
gems/activerecord-6.1.6/lib/active_record/relation.rb:804:in `_scoping'
gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `scoping'
gems/activerecord-6.1.6/lib/active_record/relation.rb:99:in `create'
gems/activerecord-6.1.6/lib/active_record/relation.rb:119:in `first_or_create'
foreman-discovery/test/unit/host_discovered_test.rb:206:in `block (2 levels) in <class:HostDiscoveredTest>'
foreman-discovery/test/unit/host_discovered_test.rb:205:in `each'
foreman-discovery/test/unit/host_discovered_test.rb:205:in `block in <class:HostDiscoveredTest>'
```

**Review by adamruzicka — APPROVED** [review]
Ok, let's go

**Pull request merged**
