### PR TITLE
Fixes #10332 websockets_encrypt = off is not working

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by dLobatog** [comment]
@roidelapluie There's another PR open to fix this https://github.com/theforeman/foreman/pull/2219 , would you mind to test it?

**Comment by roidelapluie** [comment]
@eLobato #2219 is more elegant. The only bad thing about it is that I am not sure ifnit can be cherry picked for 1.8.1 because it requires a migration?

I do not have a test setup with libvirt where i can play around now.

**Comment by domcleal** [comment]
> @eLobato #2219 is more elegant. The only bad think about it is that I am not sure ifnit can be cherry picked for 1.8.1 because it requires a migration?

Yeah, you're right, it's unlikely we'd pull it into 1.8 if it was merged for that reason.

**Comment by lzap** [comment]
> Yeah, you're right, it's unlikely we'd pull it into 1.8 if it was merged for that reason.

Let me take a look in failing tests.

Testing would be appreciated!

## 

Later,
 Lukas #lzap Zapletal

**Pull request closed without merging**
