### PR TITLE
Refs #36330 - Use merged translations

### PR DESCRIPTION
**Pull request by adamruzicka**
The previous approach with using separate domains and then doing multi- domain lookup made it hard for branding to hook into the process later. This introduces an alternative approach where all the domains are merged into the default app domain. The domains are still kept around separately in anyone wants to perform translations using a specific domain.

### CODE REVIEW

**Comment by ShimShtein** [comment]
@adamruzicka works like a charm, thanks a lot!

**Comment by ianballou** [comment]
Can someone ping me when this is merged to help remind me to CP it into 3.7 ? Or even better, do the CP when it merges :)

**Review by ShimShtein — APPROVED** [review]

**Review by ekohl — APPROVED** [review]
I think this is similar to what Foreman itself does so I'd be ok with merging this.

**Comment by Ron-Lavi** [comment]
Foreman 3.7 CP: https://github.com/theforeman/foreman/pull/9738

**Pull request merged**
