### PR TITLE
fixes #5441 - Add instance_type support to oVirt provider

### PR DESCRIPTION
**Pull request by bagasse**
Add Instance type / flavor support for oVirt compute resource provider.
Instance type values take precedence on templates values.

### CODE REVIEW

**Comment by bagasse** [comment]
[test katello]

**Review by dLobatog — APPROVED** [review]
@bagasse Thanks, the errors in Katello aren't really due to this PR, all tests passed in fact - merging

**Comment by bagasse** [comment]
@dLobatog, thanks for the review.

**Comment by iNecas** [comment]
FYI, the Katello failures were probably caused by https://github.com/theforeman/foreman-infra/pull/390, I'm going to send a PR to foreman-infra to fix this

**Pull request merged**
