### PR TITLE
fixes #4736 - organization edit ui has unselectable environment

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
This reverts what I did in e611a26ccde8f04b5b1fcb014fa518c07ec85715

**Comment by isratrade** [comment]
@thomasmckay, I don't understand how the KT environments are getting in the Puppet Environments table and being defined as used by a host. Can you explain this case? Hopefully this PR will fix it irregardless.

**Comment by ohadlevy** [comment]
@thomasmckay can you confirm this solves the original issue?

**Comment by isratrade** [comment]
ping @thomasmckay

**Comment by thomasmckay** [comment]
@isratrade will try to reproduce the scenario and then test this

**Comment by thomasmckay** [comment]
@isratrade This fix did make the UI puppet environment selectable but when I submit the org edit:

<pre>
ActiveRecord::RecordInvalid (Validation failed: Taxonomy has already been taken):
  app/controllers/concerns/foreman/controller/taxonomies_controller.rb:79:in `block in update'
  app/models/taxonomy.rb:40:in `block in no_taxonomy_scope'
  app/models/taxonomy.rb:47:in `block (2 levels) in as_taxonomy'
  app/models/concerns/foreman/thread_session.rb:143:in `as_location'
  app/models/taxonomy.rb:46:in `block in as_taxonomy'
  app/models/concerns/foreman/thread_session.rb:108:in `as_org'
  app/models/taxonomy.rb:45:in `as_taxonomy'
  app/models/taxonomy.rb:39:in `no_taxonomy_scope'
  app/controllers/concerns/foreman/controller/taxonomies_controller.rb:78:in `update'
  app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
  lib/middleware/catch_json_parse_errors.rb:9:in `call'
Request
Parameters:
{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"K0fst2tUvSFguNAnEcY6l4cHKB41X4duAh7ElBHKRVA=",
 "organization"=>{"name"=>"Mega Corporation",
 "description"=>"The number one mega company in the world!",
 "service_level"=>"",
 "ignore_types"=>["0",
 "0",
 "0",
 "0",
 "0",
 "0",
 "0",
 "0",
 "0"],
 "user_ids"=>[""],
 "smart_proxy_ids"=>[""],
 "subnet_ids"=>[""],
 "compute_resource_ids"=>[""],
 "medium_ids"=>[""],
 "config_template_ids"=>[""],
 "domain_ids"=>["1",
 "",
 "2",
 "3",
 "4",
 "5",
 "6",
 "7"],
 "environment_ids"=>["2",
 "",
 "2"],
 "hostgroup_ids"=>[""],
 "location_ids"=>[""]},
 "commit"=>"Submit",
 "id"=>"3-mega-corporation"}
</pre>

**Comment by thomasmckay** [comment]
```
<thomasmckay> josephmagen: commented on ##1347 but want to give you more details on how to reproduce
<nudnik> josephmagen: ##1347 is https://github.com/theforeman/foreman/pull/1347 "fixes #4736 - organization edit ui has unselectable environment #1347"
<thomasmckay> josephmagen: via api i make an environment "Development" but don't assign it to an org. then via api i make a host and assign it to org
<thomasmckay> josephmagen: when visiting the org edit page, the environments tab shows up red since Development must be assigned to the org
<thomasmckay> josephmagen: ...and that is the issue: adding Development environment to org 
```

**Comment by dLobatog** [comment]
I've tested the PR and it solves the issue, I noticed it's solved also for domains and other taxonomy attributes.

However it seems a little strange that the environment marked in red (used by a host) is on the left column (removed) and the text below says 'you cannot remove environments..'. 



Wouldn't it make more sense if these attributes (domains, subnets, environments, etc..) were automatically added to the taxonomy in question after events like what @thomasmckay described?

**Comment by isratrade** [comment]
@eLobato, I remember discussing this a while ago with @ohadlevy and/or @abenari.  We decided not to automatic fix an "orphan" but rather show an error for the use to fix himself. We can re-discuss if you feel it's important to automatically fix it.

**Comment by isratrade** [comment]
@eLobato, what are your thoughts on merging this PR as is?

**Comment by dLobatog** [comment]
I think it can go in, autofixing these conflicts might be overkill. Just to confirm some thought I just had, @thomasmckay , wouldn't making sure that all attributes of a host belong to the same taxonomies the host belongs in fix this? In your example I think it makes sense that creating the host throws a validation error 'environment development not in the same organization as host. please make sure environment development is part of the organization'.

**Comment by thomasmckay** [comment]
@eLobato - It would make sense that all resources for a host belong to the same org/loc as the host. Perhaps the recent work to insure resources in orgs plus validation would avoid this situation completely?

**Comment by dLobatog** [comment]
Interesting, I didn't know that. I'd go with closing this if that work you mention makes the situation that produces this bug impossible.

**Comment by domcleal** [comment]
@eLobato I think it may still be useful, and there's no indication that the other PR(s) is being merged.  It's a small, useful change.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/9f3cad157f366904c1e145d19bf35e8cd0282cf0 , thanks @isratrade !

**Pull request closed without merging**
