### PR TITLE
Fixes #11689: hide editor container when hidden value.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/11689

### CODE REVIEW

**Comment by waldenraines** [comment]
It's not pretty but it's the best I can do given the current limitations.

**Comment by dLobatog** [comment]
@waldenraines Mind to write a test? Otherwise :+1: , works great, thanks!

**Comment by waldenraines** [comment]
> @waldenraines Mind to write a test?

For the changes to layout_helper.rb you mean?

**Comment by dLobatog** [comment]
@waldenraines Just a functional test that verifies the editor isn't displayed when you click on "hidden button" should suffice, other issues stem from that, as far as I can see.

**Comment by waldenraines** [comment]
@eLobato updated.

**Comment by dLobatog** [comment]
Merged as 46f1c2e3ae434e7192395fe71e22c1d387f9591e, thanks @waldenraines!

**Pull request closed without merging**
