### PR TITLE
Upgrade foreman-vendor packages to 13.x

### PR DESCRIPTION
**Pull request by sjha4**
Pulling in https://github.com/theforeman/foreman-js/commit/0bb20a81069a9ffe3246b41832c52a0eb68c565a

### CODE REVIEW

**Comment by sjha4** [comment]
@MariaAga @ekohl This looks green.

**Review by MariaAga — APPROVED** [review]
Thanks!

**Comment by jeremylenz** [comment]
@theforeman/packaging Can we get this in?

**Comment by evgeni** [comment]
packaging in https://github.com/theforeman/foreman-packaging/pull/10675

**Review by evgeni — APPROVED** [review]

**Pull request merged**
