### PR TITLE
Fixes #22922 - Port robottelo tier1 compute profiles tests

### PR DESCRIPTION
**Pull request by odovzhenko**
Redmine issue: http://projects.theforeman.org/issues/22922

Port robottelo tier1 tests for environment part of robottelo minitest port project https://github.com/SatelliteQE/robottelo/projects/1

Related Robottelo issue: SatelliteQE/robottelo#5845

Relates on #5295 for rfauxfactory dependency.

### CODE REVIEW

**Comment by mmoll** [comment]
ok to test

**Comment by odovzhenko** [comment]
@mmoll This PR should be tested after merging #5295.

**Comment by mmoll** [comment]
@odovzhenko as #5295 got in now, please rebase :+1:

**Comment by odovzhenko** [comment]
@mmoll Rebased.

**Comment by mmoll** [comment]
test failures unrelated

**Comment by odovzhenko** [comment]
Rebased after merging #5335
Now tests are using valid_name_list and invalid_name_list from test_helper.rb

**Comment by ares** [comment]
Failures seems to be related, one ovirt test does not pass, @odovzhenko could you please take a look?

**Comment by mmoll** [comment]
it's not related and already fixed in develop :)

**Review by ares — APPROVED** [review]
Sorry, I was not aware of that unrelated failures. Code is good, merging, thanks @odovzhenko !

**Comment by odovzhenko** [comment]
@ares @mmoll Thank you a lot :)

**Pull request merged**
