### PR TITLE
fixes #10284 - improves foreman-debug usage for consumption from other

### PR DESCRIPTION
**Pull request by komidore64**
tools

### CODE REVIEW

**Comment by komidore64** [comment]
[test]

**Comment by lzap** [comment]
What exactly is wrong with interactive mode? When the shell is non-interactive do we not ask. If you see foreman-debug to block some other tool, then invoke it in non-interactive shell. Do we have a bug in there?

Uploading private data is dangerous operation, we should really warn the user before. I am fine with making this explicit, but can you keep the `-u` option interactive and maybe provide another option `-y` meaning "yes" (don't ask)?

When touching this, please add this line into the final output:

```
... list or IRC and provide the following URL:
http://debugs.theforeman.org/$(basename $TARBALL)
```

So users can directly copy-paste us download URL (password protected).

**Comment by komidore64** [comment]
@lzap it's not really consistent with the rest of `foreman-debug`. All other options to `foreman-debug` are flags or options that the user has to specify before running the script. Oh, except there's this one thing that prompts you with a question at the end. It's out of place.

I agree with you that uploading private data is indeed a sensitive operation, which is why I made the default action to not upload the `foreman-debug` archive, unless you give the `-u` flag.

`foreman-debug` still prompts for upload when i try to shell out to it from ruby like so:

``` ruby
def execute
  puts `/usr/sbin/foreman-debug -d /tmp/foobar`
end
```

I've had to resort to using `PTY` as a hack to make it work:

``` ruby
require 'pty'
require 'expect'

def execute
  PTY.spawn(external_command) do |p_out, p_in, pid|
    puts p_out.expect('Do you want to do this now? [y/N]')
    choice = upload? ? 'y' : 'n'
    p_in.puts choice
    puts choice
    Process.wait(pid)
    puts upload? ? UPLOAD_RESPONSE : NO_UPLOAD_RESPONSE
  end
end
```

The above kludge works, unless you're running on ruby `1.8.7`, then it errors out. `foreman-admin` lives outside of the SCL so it has to support ruby `1.8.7`.

**Comment by komidore64** [comment]
That `PTY#spawn` above is really gross and unnecessary. It makes `foreman-admin`'s `generate-debug` command extremely brittle because it's depending on very specific output from `foreman-debug`.

If the output or prompt question changes, it could cause `generate-debug` to hang indefinitely until the user kills it.

**Comment by komidore64** [comment]
bump

**Comment by komidore64** [comment]
rebase

**Comment by komidore64** [comment]
@lzap, doing a bit more research I don't think `tty -s` is correctly denoting an interactive vs a non-interactive shell.

I can run this in a shell getting the following:

``` sh
$ tty
/dev/pts/7 # exitstatus is 0
```

i can run the same thing in ruby, which you'd think would be a non-interactive shell:

``` ruby
pry> `tty`
"/dev/pts/7\n"
pry> $?
#<Process::Status: pid xxxxx exit 0>
```

So I think this might be our reason for still seeing the upload prompt even when executing from inside ruby.

**Comment by lzap** [comment]
Ok something is weird with the `tty -s` call, it does not really work as expected. I agree with what you have, but can you please reword the last section to this:

```
if [ $UPLOAD -eq 1 ]; then
  qprintf "Uploading..."
  rsync $TARBALL rsync://theforeman.org/debug-incoming
  qprintf "The tarball has been uploaded, please contact us on mailing list or IRC"
  qprintf "providing us the following URL:"
  qprintf "  http://debugs.theforeman.org/$(basename $TARBALL)"
else
  qprintf "To upload a tarball to our secured site, please use -u option."
fi
```

**Comment by komidore64** [comment]
@lzap certainly! I will reword to your suggestion and update the PR.

**Comment by komidore64** [comment]
@lzap updated

**Comment by lzap** [comment]
Looks like we are missing a final newline:

```
[lzap@lzapx foreman]$ script/foreman-debug -g -x


 HOSTNAME: lzapx.brq.redhat.com
       OS: redhat
  RELEASE: Fedora release 21 (Twenty One)
  FOREMAN: 
     RUBY: ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
   PUPPET: 3.7.1


A debug file has been created: /tmp/foreman-debug-wTxao.tar.xz (7776 bytes)

To upload a tarball to our secure site, please use the -u option.[lzap@lzapx foreman]$ 
```

**Comment by lzap** [comment]
And the `-u` option does not work. You need to add it to `getopts`.

**Comment by komidore64** [comment]
oops, yeah you're right!

**Comment by komidore64** [comment]
updated with addition to `getopts` and proper newlines for output.

**Comment by lzap** [comment]
WFM thanks

```
[lzap@lzapx foreman]$ script/foreman-debug -h
script/foreman-debug - configuration and log data collector

USAGE: script/foreman-debug [options]

Collects configuration and log data for Foreman, Smart Proxies, backend
services and system information while removing security information like
passwords, tokens and keys.

You may want to upload the tarball (with -u) to our public server via rsync.
This is a write-only directory (readable only by Foreman core developers)
Please note that the rsync transmission is UNENCRYPTED.

This program can be used on Foreman instances, Smart Proxy instances or
backend services separately.

OPTIONS:
  -d DIR  Directory to place the tarball in (default /tmp/foreman-XYZ)
  -g      Skip generic info (CPU, memory, firewall etc.)
  -a      Do not generate a tarball from the resulting directory
  -m NUM  Maximum lines to keep for each file (default 5000)
  -j PRG  Filter with provided program when creating a tarball
  -p      Additionally print password patterns being filtered out
  -q      Quiet mode
  -v      Verbose mode
  -u      Upload tarball (default: false)
  -h      Shows this message

[lzap@lzapx foreman]$ script/foreman-debug -x


 HOSTNAME: lzapx.brq.redhat.com
       OS: redhat
  RELEASE: Fedora release 21 (Twenty One)
  FOREMAN: 
     RUBY: ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
   PUPPET: 3.7.1


A debug file has been created: /tmp/foreman-debug-HnAMp.tar.xz (18868 bytes)

To upload a tarball to our secure site, please use the -u option.
[lzap@lzapx foreman]$ script/foreman-debug -u
This script must be run as root
[lzap@lzapx foreman]$ script/foreman-debug -u -x


 HOSTNAME: lzapx.brq.redhat.com
       OS: redhat
  RELEASE: Fedora release 21 (Twenty One)
  FOREMAN: 
     RUBY: ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
   PUPPET: 3.7.1


A debug file has been created: /tmp/foreman-debug-Vbslx.tar.xz (18976 bytes)

Uploading...
The tarball has been uploaded, please contact us on our mailing list or IRC
referencing the following URL:
    http://debugs.theforeman.org/foreman-debug-Vbslx.tar.xz
```

**Comment by lzap** [comment]
Merged as 6eb9ebfa3fc7dc9114ecea3fc5e5429adeead194, thank you!

**Comment by komidore64** [comment]
thanks @lzap!

**Pull request closed without merging**
