### PR TITLE
Fixes #14264 - improve primary interface selection

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
related PR https://github.com/theforeman/foreman/pull/3339

**Comment by iNecas** [comment]
:+1: for getting this out of the controller

**Comment by domcleal** [comment]
Thanks, this is a good improvement.  Would you mind moving the test too?  It'll be better kept with the other host unit tests and testing this code specifically.

**Comment by ares** [comment]
I think it was already covered by other hosts tests but I added few more for host initializer which uses private method `build_required_interfaces` as well and which were missing. I'd like to avoid testing private methods directly. I intentionally avoid using FactoryGirl in this case. I removed the functional test. Please take a look.

**Comment by domcleal** [comment]
Merged as 308f611, thanks @ares.

**Pull request closed without merging**
