### PR TITLE
fixes #14368 - update fog to 1.38.0

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dLobatog** [comment]
- [x]  EC2
- [x]  GCE
- [x]  OpenStack
- [x]  Libvirt
- [x]  oVirt
- [x]  Rackspace
- [x]  VMWare

**Comment by domcleal** [comment]
Regarding testing, you may want to skip those that have been extracted from Fog previously and aren't updated here.  Only OpenStack, oVirt and Rackspace have any code changes.

**Comment by dLobatog** [comment]
Thanks @domcleal , OpenStack passed basic testing (creating and provisioning a VM w/ various disk/network options). If someone can take up oVirt/RackSpace testing that'd be helpful!

**Comment by iNecas** [comment]
I can try ovirt if anyone is not already doing so

**Comment by iNecas** [comment]
Tested oVirt and it works as well

**Comment by domcleal** [comment]
Rackspace seems to be working well, I've created a few VMs successfully, and retrieved both VM and image lists.

**Comment by dLobatog** [comment]
Merged as 27ae0a7da15b3b26e85645c4773d15ac3d4d5157, thanks @domcleal!

**Pull request closed without merging**
