### PR TITLE
refs #9877 - s/variable/class parameter/ on param :override

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
@domcleal thanks :)

**Comment by dLobatog** [comment]
[test] rubocop job was aborted no idea why.

**Comment by shlomizadok** [comment]
@eLobato rubocop aborts on me ever since I said I should feed nudnik with it

**Comment by dLobatog** [comment]
Random test failure... http://ci.theforeman.org/job/test_develop_pr_core/4395/database=postgresql,ruby=2.0.0/testReport/junit/%28root%29/HostTest/test_0001_index_page/ [test]

**Comment by dLobatog** [comment]
Merged as 00c41428f08d427eb41c041e9bf8bb2eeac26bfc, thanks @shlomizadok !

**Pull request closed without merging**
