### PR TITLE
fixes #13759 - 500 when attempting to update a host

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by dLobatog** [comment]
@anandkumaragrawal Thanks for fixing this issue, I'll trigger tests with [test]. 

The problem here is just that we're allowing a key that simply shouldn't be allowed on create as you cannot create hosts with this key.

**Comment by anandkumaragrawal** [comment]
Test failure is unrelated to my changes.

**Comment by anandkumaragrawal** [comment]
[test] failure looks unrelated to the change

**Comment by domcleal** [comment]
This only removes documentation, which is correct to do. I don't see how this addresses the 500 error described?

The error for unknown attrs is by design with strong/protected attrs in development and test mode.  I don't see how you'd do that without removing data from the API responses or changing the behaviour (which doesn't seem desirable).

The commit message should also state what the change is (e.g. `remove capabilities from host API docs`).

**Comment by anandkumaragrawal** [comment]
Since my fork got corrupted, creating pull request for the same. Please refer https://github.com/theforeman/foreman/pull/3728

**Pull request closed without merging**
