### PR TITLE
fixes 1760 adds audited to EnvironmentClass

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
this might spam the audit log, maybe an alternative solution is to create a custom audit message when you run the importer?
e.g.

Audit.create .... <list of changes here>

**Comment by isratrade** [comment]
Ohad, are you handling this, or should I?

**Comment by ohadlevy** [comment]
@isratrade I think we need to agree on whats the best way forward, @abenari and I had a quick talk a few days ago, and we though that maybe one commit message per import is better, what do you think?

**Comment by isratrade** [comment]
@ohadlevy What will the one audit message include?  Is it just a general one-liner "import was done".  If not, and the audit message details which classes were removed, which classes were added, and which classes were updated, then it seems better to have it as multiple audit entries.  Maybe I'm missing something how the users use the audit trail.

**Comment by ohadlevy** [comment]
@isratrade why multiple not related operations are better then one unified message (that include all relevant data)? 
Since the import opeation is a bulk operation, why shouldnt the audit be a bulk operation too?

**Comment by isratrade** [comment]
@ohadlevy This is an issue of grouping the audit actions. Each row in the model has an auditable_type, action, etc.  It seems this information will get buried if all the changes (create, destroy, update) on a bulk import are condensed into the column "audited_changes"

**Comment by isratrade** [comment]
@ohadlevy, what's the decision about this.  To merge as is, or make a custom bulk audit message?

**Comment by ohadlevy** [comment]
i think we should ask the mailing list, I'm :+1: for bulk audit

**Comment by ohadlevy** [comment]
@isratrade, please reopen after a discussion from the list... thanks!

**Pull request closed without merging**
