### PR TITLE
Fixes #25111 - mini spin counter

### PR DESCRIPTION
**Pull request by tristanrobert**

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by ohadlevy** [comment]
@ares any comments?

**Review by ares — CHANGES_REQUESTED** [review]
Sorry for late reply

For many fields, it makes sense to limit minimum by 1, e.g. cpu count. Would you mind modifying it, so that it loads the minimum from data attribute? the same way we load softMax attribute. It should still default to 1 unless explicitly set to 0 (or other value)

**Comment by ohadlevy** [comment]
whats the status of the pr? thanks.

**Comment by tbrisker** [comment]
Thanks @tristanrobert ! Looks like this PR has been inactive for a very long time. I'm going to go ahead and close it for now, feel free to reopen if you wish to continue working on this.

**Pull request closed without merging**
