### PR TITLE
Fixes #34998 - long breadcrumb switcher is out of view

### PR DESCRIPTION
**Pull request by MariaAga**
Before: 
Screenshot from 2022-06-01 19-11-48

After: 
Screenshot from 2022-06-01 19-11-59

### CODE REVIEW

**Comment by adamruzicka** [comment]
This works nicely, although it makes one issue that was present even without this patch much more easier to spot. Once the button which opens the switcher get scrolled away from the screen, the whole switcher gets transparent background and stops being clickable. Actually trying to click it seems to click through to the page below it

https://user-images.githubusercontent.com/7326770/171574907-701d75ab-516c-4fcb-ac48-7a9e51fced16.mp4

**Comment by MariaAga** [comment]
@adamruzicka @Ron-Lavi Added `isScrollable` so the bug Adam mentioned won't happen

**Comment by adamruzicka** [comment]
Although it is now harder to trigger, it can still happen :/

https://user-images.githubusercontent.com/7326770/173544186-5db1daac-88b6-42f2-9df1-9fec5ffc165d.mp4

To be fair, I'm fine with it the way it is now, as long as it is tracked somewhere else.

**Comment by MariaAga** [comment]
added css rules.
When the thing that opens the popper is out of view the popper gets `visibility: hidden;`. the other elements inside have different rules for visibility so I just changed so they will match the parent visibility.

**Comment by adamruzicka** [comment]
LGTM

**Review by ofedoren — APPROVED** [review]

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga and @adamruzicka, works great, merging.

**Pull request merged**
