### PR TITLE
Fixes #16899 - rename helper with conflicting path name

### PR DESCRIPTION
**Pull request by ares**
help_path is defined by [this](https://github.com/theforeman/foreman/blob/develop/config/routes.rb#L19), since the route helpers were included after application helper, so it re-replaced the method by which we had replaced the original method :-)

### CODE REVIEW

**Comment by dLobatog** [comment]
https://github.com/search?l=&q=help_path+user%3Atheforeman+user%3Akatello&ref=advsearch&type=Code&utf8=%E2%9C%93 notice discovery and tasks use this too. I think it'd be OK to merge this along changes to the plugins and not deprecate it.

**Comment by ares** [comment]
yeah, I'll send patches to both, I agree with not deprecating it

**Comment by ares** [comment]
https://github.com/theforeman/foreman_discovery/pull/309 and https://github.com/theforeman/foreman-tasks/pull/207 opened

**Comment by dLobatog** [comment]
Thank you @ares!

**Pull request merged**
