### PR TITLE
Refs #28028 - update chromedriver to match jenkins version

### PR DESCRIPTION
**Pull request by tbrisker**
This is a stopgap to get tests running again, we should find a solution
that doesn't require manual update every time a new version of chromium
is released.

### CODE REVIEW

**Review by mmoll — APPROVED** [review]
fixes it :wrench:

**Comment by mmoll** [comment]
test failure unrelated :green_heart:

**Comment by mmoll** [comment]
merged, thanks @tbrisker!
This will need cherry-picking to all supported branches.

**Comment by tbrisker** [comment]
1.23 - 31ce69fde
1.22 - fc3c739e8

**Pull request merged**
