### PR TITLE
Fixes #34495 - Breadcrumb switcher doesn't work with katello [CP 3.2]

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This cherry-picks #9114, #9168

### CODE REVIEW

**Comment by ofedoren** [comment]
Is it OK to merge CPs even though the tests are :red_circle: ? :D Although it's only related to the snapshots, so we could ignore that or include regenerated ones in the PR...

**Comment by ezr-ondrej** [comment]
I guess both is fine, but let's have the tests green in stable branch :)

**Comment by ezr-ondrej** [comment]
:green_apple:

**Review by ofedoren — APPROVED** [review]
Thanks, @ezr-ondrej, merging.

**Pull request merged**
