### PR TITLE
Fixes #35176 - add review templates to host details

### PR DESCRIPTION
**Pull request by MariaAga**
~~blocked by https://github.com/theforeman/foreman/pull/9359~~
Screenshot from 2022-09-30 16-59-37
Screenshot from 2022-09-30 16-58-49

### CODE REVIEW

**Comment by MariSvirik** [comment]
1. I would use a switcher with a check and label https://www.patternfly.org/v4/components/switch/#checked-with-label - it's always clearer for a user.
2. I would use a close button at the end of the modal.
3. What is the size of the description?
4. What's the icon in the header - is it a copy?
@MariaAga

**Comment by MariaAga** [comment]
@MariSvirik 
2. are you sure? I thought we said the close button in the footer that was in the design was wrong?
3. not sure which description are you talking about, but the modal takes most of the screen
4. I moved the "open in a new tab" button to the title as the modal is really big which can make users not see the button on the right side as it was in the original design.
also it says "open in a new tab" on hover.

**Review by chris1984 — APPROVED** [review]
Tested and works well, looks nice.

**Review by jeremylenz — APPROVED** [review]
ACK based on @chris1984 

thanks @MariaAga!

**Comment by ares** [comment]
This is great community demo content :-)

**Pull request merged**
