### PR TITLE
fixes #3906 - Support for Junos ZTP

### PR DESCRIPTION
**Pull request by fraenki**
This adds support to provision Junos devices with foreman.
Be aware that db/migrate/20131218121601_add_junos_templates.rb is untested and possibly wrong ;-)

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test]

**Comment by dLobatog** [comment]
@fraenki great job, thanks! 

I've reviewed it and I like it, however the migration is wrong and it causes the test suite to fail, see [this](http://ci.theforeman.org/job/test_develop_pull_request/5126/database=mysql,puppet=3.0,ruby=1.9.3/console)

We'd appreciate some tests for the model and unattended controller, let us know if you need any help with that.

**Comment by fraenki** [comment]
I've fixed the db migration and added a change to the facts parser, but I'd need some help with the tests.

**Comment by lzap** [comment]
Mind rebasing? Btw what is the source image for the icon? Does it have a license?

**Comment by fraenki** [comment]
Rebased and replaced the Junos image with a dummy for now, because use of this logo needs to be approved by Juniper. We should add the original logo later...

**Comment by lzap** [comment]
Nice thanks. Out of my interest, how did you generate the image?

We should maybe create whole icon set of all letters for future purposes (GIMP + script in scheme or ImageMagick). We need this to be GNU GPL v2+.

**Comment by fraenki** [comment]
@lzap the image was generated manually with GIMP :) Just in case: the font is "Liberation Mono Bold".

**Comment by dLobatog** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
[test] again, http://ci.theforeman.org/job/test_develop_pull_request/5839/ shows it was green, something weird happened,

**Comment by domcleal** [comment]
It passed, but our slave ran out of disk space.  Now fixed.

**Comment by domcleal** [comment]
Thanks for the patch @fraenki.  This will be included in Foreman 1.4.0, but I'm just waiting on clarification from an expert colleague on how we should handle the BSD licence of the Junos provisioning script.  I'm pretty sure it's fine, but we may need to add the licence info to some of our documentation.

If I don't hear back in time for the 1.4 branch, then I'll merge it without that script for the time being and we'll add it back in ASAP.

**Comment by domcleal** [comment]
Merged as b80c6c0 for Foreman 1.4.0.  Thanks for the contributions @fraenki!

Templates were merged to community-templates (our upstream source for app/views/unattended/) in https://github.com/theforeman/community-templates/commit/c20ff869b3ac8486e6f7b3e84706669f5e1ff80c.

I've had to leave out the BSD script for the time being as I didn't hear back in time, so I've left a README in the above commit to explain and will endeavour to include it at a later date.

**Comment by crab86** [comment]
@fraenki: Could you describe the steps neccessary in order to get ztp for juniper to work with foreman? I tried it but getting error "Create DHCP Settings for lloyd-kibbler.vbox task failed with the following error: ERF12-6899 [ProxyAPI::ProxyException]: Unable to set DHCP entry ([RestClient::BadRequest]: 400 Bad Request) for proxy https://foreman.vbox:8443/dhcp" all the time. Unfortunately i could not find any documentation about how to use this feature with foreman? Thanks in advance.

**Comment by fraenki** [comment]
@crab86 Sorry, I no longer have access to Juniper devices, haven't used this feature in 4+ years :(

**Pull request closed without merging**
