### PR TITLE
Fixes #9430 - provisioning on VMWare fails with invalid MAC address

### PR DESCRIPTION
**Pull request by tstrachota**
Needs additional testing. I'm no VMWare expert so please keep an eye on my steps.

### CODE REVIEW

**Comment by tstrachota** [comment]
@shlomizadok could you please review?

**Comment by GregSutcliffe** [comment]
This looks like it should work, can test next week if no one beats me to it.

**Comment by shlomizadok** [comment]
lgtm too. Will test tomorrow. Yet would love if @GregSutcliffe will take a look too.

**Comment by shlomizadok** [comment]
It seems that creation of a vm on vmware fails, both on develop branch and this branch.
I do not know if it's a configuration on vsphere that has changed or a bug in the networking on those branches.

**Comment by shlomizadok** [comment]
(previous comment deleted, my local config was messed up so I started from scratch).
A few notes:
1. I could not reproduce the issue described in [9430](http://projects.theforeman.org/issues/9430).
2. With this PR, for some reason I am getting:
`failed to create a compute vmware (vmware) instance <host.name>: cluster is required for this operation` - but when I submit it again it creates the host. This is not happening in develop branch.
3. (side note): specifying an identifier on the interface when creating a host will cause creation to fail.

**Comment by domcleal** [comment]
#2150 may fix errors about cluster being required, which happens on develop currently due to the VM tab being greyed out: http://projects.theforeman.org/issues/9320

**Comment by shlomizadok** [comment]
Re-tested with a fresh develop branch, getting invalid MAC error.
Works with this PR.

**Comment by domcleal** [comment]
Also had test confirmation from Alexandre on the ticket.

**Comment by ares** [comment]
Merged as https://github.com/theforeman/foreman/commit/2ed715f58063d5871e046677c732a66d983de7d1, thanks @tstrachota!

**Pull request closed without merging**
