### PR TITLE
Fixes #22114 - Webpack common-chunk vendor.js

### PR DESCRIPTION
**Pull request by xprazak2**
Use webpack-common-chunk-plugin to include all
required modules from node_modules/ into vendor.js
(cherry picked from commit 3bba4cf188b755663523f86b10b20a2f4e4d7c8a)

### CODE REVIEW

**Comment by ohadlevy** [comment]
What is the difference between this pr and the original commit?

**Comment by xprazak2** [comment]
No difference, this is just a cherry-pick for 1.17-stable branch

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
thanks!

**Pull request merged**
