### PR TITLE
Cherry-picks for 1.18-stable

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Fixing the rubocop issues including the removal of unused `pluginEntries` function from plugin_webpack_directories.js

**Comment by mmoll** [comment]
are these fixes also going to development?

**Comment by bastilian** [comment]
Wouldn't it be nicer to have the parts in the initializer as a module, which would allow the implementation of loading webpack assets to be cleaner (and make it testable). It could also accommodate the functionality that is now in the module of the rake task file.

**Comment by mmoll** [comment]
@bastilian please note that this PR is against 1.18 and is only a tidied up version of a commit that got into develop.

**Comment by bastilian** [comment]
@mmoll ah! thanks, that I overlooked. :D

**Comment by xprazak2** [comment]
Exactly, this is a cp of #5413

**Comment by xprazak2** [comment]
I added a cherry-pick of https://github.com/theforeman/foreman/pull/5485

**Comment by mmoll** [comment]
@xprazak2 are the fixups for #23147 going to develop, too? I'd rather opt for having the same code.

**Comment by xprazak2** [comment]
They are on the way...

**Review by tbrisker — APPROVED** [review]
Thanks @xprazak2 !

**Pull request merged**
