### PR TITLE
Fixes #6914 - puppet class with numeric name can neither be edited nor d...

### PR DESCRIPTION
**Pull request by boaz0**
...eleted

### CODE REVIEW

**Comment by boaz0** [comment]
OK, from looking at the code, in `puppetclass` model, `to_param` returns the `name` attribute. Therefore, there is no reason to use the ID for routing to a specific puppetclass.

Correct me if I'm wrong.

BR.

**Comment by orrabin** [comment]
[test]

**Comment by isratrade** [comment]
@ripcurld00d, I think you're confusing `params[:id]` and `to_param`.

`params[:id]` is parsed from the URL and it may either by an integer or a string. 
puppletclasses/123  --> `params[:id]` = 123
puppletclasses/apache -- `params[:id]` = apache

The `to_param` is used if you already have the activerecord object. If this case, you are right that @puppetclass.to_param = apache

The code is correctly checking if  `param[:id]` is an integer, then it uses `find` but if it's a string, it uses `find_by_name`

The code will hopefully be cleaned later if we implement the `friendly_id` gem https://github.com/theforeman/foreman/pull/1246

**Comment by boaz0** [comment]
Hi @isratrade,

I am probably misssing something here. What is the point of checking that `params[:id]` is an integer?

**Comment by isratrade** [comment]
@ripcurld00d, the URL may contain either an a puppet class's id or name. Foreman tries to support both for most objects.  Therefore, in the code, we need to determine if `params[:id]` is an integer or string to determine whether to use `find` or `find_by_name`

**Comment by boaz0** [comment]
OK, this is a different idea.
This time if `params[:id]` is an integer and there is a record that its id equals to `params[:id`, then return it. Otherwise, it's a puppet-class name. I **do** think `friendly_id` is a better way to fix this, though.

**Comment by orrabin** [comment]
@ripcurld00d it depends where you want to look for `params[:id]` first. 
If I understand correctly if there is an integer to find `friendly_id` will still look for a name first and if it's not found look for a matching id. 
You are doing the opposite, first looking for an `id` and if there is no such id looking for a name. 
I'm not sure which is better but there is nothing preventing you from adding a puppetclass name that is an integer and both cases might find the wrong puppetclass.
[test]

**Comment by boaz0** [comment]
@orrabin - thanks for elobrating more about `friendly_id`. I used that logic (first looking for an id and then for  a name) to keep the old-behavior and _not to mimic_ `friendly_id`.

Yes, as you've mentioned, when there is a collosion between `id` and `name`, this may give a result that the user hasn't excpected.
For instance, the user creates a puppet class named `2` and there exists a puppet class called `apache`, which its index is **2**. Then, in that case, when the user tries to edit puppet class `2`, he will end up in `apache` edit page eventually.

_However_, it will cover a case when there is no collosion and there are puppet classes with only numerical characters in their names. So, there is some trade-off.

**EDIT** Yup, as I've suspected, there is a need to change the tests, because they will fail when we move to `friendly_id`. :smiley:

**Comment by orrabin** [comment]
@ripcurld00d I'd prefer changing it to act like `friendly_id` so the behavior doesn't suddenly change when #1246 is merged.

Maybe you should open a discussion on foreman-dev or foreman-users mailing list to determine which behavior is better in this case.

**Comment by boaz0** [comment]
@orrabin :+1: - I'll do that. Thanks.

**Comment by domcleal** [comment]
Or just use id-name like most other resources in to_param?

**Comment by boaz0** [comment]
@domcleal - another good approach, indeed. I am opening it to [discussion](https://groups.google.com/forum/#!topic/foreman-dev/vnAAaknhqv4) @ google groups, anyhow.

**Comment by boaz0** [comment]
`friendly_id` got merged and i didn't have the time to continue working on this -> closing this.

**Pull request closed without merging**
