### PR TITLE
fixes #5987 - remove unused packaging files

### PR DESCRIPTION
**Pull request by domcleal**
https://github.com/theforeman/foreman-packaging/tree/rpm/develop/foreman

### CODE REVIEW

**Comment by lzap** [comment]
+1 merge at will?

**Comment by domcleal** [comment]
please!

**Comment by domcleal** [comment]
There are equivalent PRs to the other three repos, if you'd be so kind.

**Comment by dLobatog** [comment]
Good riddance, merged as https://github.com/theforeman/foreman/commit/f71f2b66207531b93bc94f62a3d9faf0c2f3ef82 , thanks @domcleal 

Someone please else take care of https://github.com/theforeman/smart-proxy/pull/162  and https://github.com/theforeman/foreman-installer/pull/119 since I don't have write access to those repos.

**Pull request closed without merging**
