### PR TITLE
[cp] Fixes #23391, #23251 - adjust breadcrumbs switcher to pf design

### PR DESCRIPTION
**Pull request by amirfefer**
Cherry picked from commit [5b16c](https://github.com/theforeman/foreman/commit/5b16c0dc08e42839b20262f9e9733835bae999f1)

### CODE REVIEW

**Comment by xprazak2** [comment]
js test failing due to a known issue, https://github.com/theforeman/foreman/pull/5720 needs to get in first for tests to pass

**Comment by tbrisker** [comment]
related PR was merged, please rebase on latest 1.18-stable @amirfefer

**Comment by amirfefer** [comment]
rebased.

**Review by xprazak2 — APPROVED** [review]
Foreman tests are green, merging. Thanks!

**Pull request merged**
