### PR TITLE
two small Rubocop fixes

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
This is why I would prefer a Jenkins/travis/whatever job over hound :)

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
katello test failure unrelated :upside_down_face:

**Review by tbrisker — APPROVED** [review]
LGTM, for some reason it wasn't linked from #15286.

**Comment by tbrisker** [comment]
Thanks @mmoll !

**Pull request merged**
