### PR TITLE
fixes #2263 continuation - turn off auditing for migration of adding Hostgroup label

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@ohadlevy do you know a better way to turn off auditing in migration other than what I did?

**Comment by ohadlevy** [comment]
you can use save_without_auditing or *without_auditing block, see
https://github.com/collectiveidea/audited/blob/master/lib/audited/auditor.rb
*

**Comment by isratrade** [comment]
updated using save_without_auditing

**Comment by ohadlevy** [comment]
merged - thanks

**Pull request closed without merging**
