### PR TITLE
Fixes #35466 change location of puppet-release files

### PR DESCRIPTION
**Pull request by ikonia**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
`repo_subdir` is now always an empty string. Can you drop the variable altogether? Other than that it's correct.

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you also remove the usage of `repo_subdir` on the `rpm -Uvh` line?

**Comment by ikonia** [comment]
all changes made - attempting to squash the 2 additional changes into the single commit pattern.

**Comment by ikonia** [comment]
changes made just need to squash changes into single commit

**Comment by ikonia** [comment]
re-submit fresh PR - user error on the merge process

**Pull request closed without merging**
