### PR TITLE
Fixes #15344 - recover from fingerprint error on validation

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by lzap** [comment]
There's a rubocop failure, then I will test this. Thanks!

**Comment by ares** [comment]
fixed, thanks for letting me know

**Comment by lzap** [comment]
WFM. RTM. Thanks.

**Comment by ares** [comment]
why should I **Read The Manual**? :-) thanks for quick review

**Comment by lzap** [comment]
Merged as edb839629c94822c387b340f2db5e1efb8106ea8, thank you!

**Pull request closed without merging**
