### PR TITLE
fixes #26796 - coreos: url_for_boot

### PR DESCRIPTION
**Pull request by timogoebel**
Fixes:

```
ArgumentError: wrong number of arguments (given 2, expected 1)
from app/models/operatingsystems/coreos.rb:14:in `url_for_boot'
from app/models/concerns/host_common.rb:83:in `url_for_boot'
```

TODOs:

- [x] Add tests

### CODE REVIEW

**Comment by lzap** [comment]
ACK thanks.

**Comment by tbrisker** [comment]
@timogoebel what's the status here? I'd be happy to get this in to 1.22 if possible, i think the tests should also be covered by https://projects.theforeman.org/issues/25613 when someone implements that

**Comment by timogoebel** [comment]
> i think the tests should also be covered by https://projects.theforeman.org/issues/25613 when someone implements that

True, I actually implemented this in: https://github.com/theforeman/foreman/pull/6700

**Comment by timogoebel** [comment]
@tbrisker: There you go. Tests added.

**Review by tbrisker — APPROVED** [review]
Thanks @timogoebel ! waiting for the butler's ack as well

**Comment by mmoll** [comment]
all :green_heart:

**Comment by mmoll** [comment]
merged, danke @timogoebel!

**Comment by tbrisker** [comment]
1.22- 1072abd46

**Pull request merged**
