### PR TITLE
Fixes #28361 - Create notification on host build fail

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
I tried to test this but didn't find a way to break a kickstart template in a way, it would report failure. I could only delete the `touch` command we use in %post to simulate it. But if there's no way to trigger build failure, I wonder what's the benefit here. @lzap do you recall how failure in %post was suppose to work (https://github.com/theforeman/community-templates/pull/461), the main %post does not seem to work like with `set -e`

**Comment by lzap** [comment]
Well, that it's all wrong then. I assumed it's executed in `set -e` shell, I have probably misread the documentation. I was then testing this using `curl` and it was not complete end-to-end test.

Just to doublecheck, do you have `%post --erroronfail`? According to docs, it should actually "Display an error and halt the installation if the script fails. The error message will direct you to where the cause of the failure is logged."

How about this: `--interpreter=/usr/bin/bash -e`?

**Comment by ares** [comment]
we don't have `--erroronfail` in the main %post but I tried it with the same result. I can retry with interpreter and see if it changes anything.

**Comment by lzap** [comment]
The Foreman API extension is not a bad thing and it could be used by other plugins or features. But it really looks like for kickstart this is pretty much useless. Two options:

1) Try the `--interpreter=/usr/bin/bash -e` (this is purely an idea might not work if `exec` is used)

1) Wrap the shell inside of another shell with `-e`

1) Grep the log that's created via `%post --log=/mnt/sysimage/root/install.post.log` for strings like ERROR and send fail call in case there is a match.

**Review by ares — CHANGES_REQUESTED** [review]
With the suggestion from above, @xprazak2 could you please check if the suggested templates modification would actually work? If that won't work, while I see the potential value in this new endpoint, it would add a code that nothing is currently using.

**Comment by xprazak2** [comment]
Proposed check would bring more problems than it would solve. Grepping log files for random 'error' strings would fail builds even for hosts that are provisioned successfully - all it takes is to have a misconfigured repo:

```
No package katello-agent available.
Error: Nothing to do
error reading information on service goferd: No such file or directory
```

I can reopen when we have a clear criteria on when the build should be failed.

**Pull request closed without merging**
