### PR TITLE
let Foreman run on a sub path

### PR DESCRIPTION
**Pull request by iNecas**
e.g. for it being available on http://localhost:3000/foreman you run:

```
RAILS_RELATIVE_URL_ROOT=/foreman rails s
```

### CODE REVIEW

**Comment by ohadlevy** [comment]
sadly does not work without failing tests ;)

**Comment by iNecas** [comment]
Oh, haven't thought it could break something…:) will check

**Comment by iNecas** [comment]
Was the failing test the one fixed in 2117168c79b0c23e4591404e1e2e57942e51e2ba
or are there another ones? I've rebased the branch to have that one fixed

**Comment by ohadlevy** [comment]
did you get the tests failures? e.g.
RAILS_RELATIVE_URL_ROOT=/foreman rake

**Comment by iNecas** [comment]
There were two problems:
1. controller tests started to reflect the relative path settings just after
    making the request. That causes that calling e.g. `environments_path` prior
    the request was returning a path without the prefix.
   
    It was fixed by setting the 'SCRIPT_NAME', which is the way how `rack`
    handles the relative_path, in the setup phase of functional tests.
2. in `lib/foreman/controller/environments.rb` there was used `controller_path`
    directly with `redirect_to`. This doesn't reflect the relative path
    setting. Using it with `:controller => controller_path` goes through
    `url_for` method and puts there the prefix automatically.

The latest commit should fix both issues.

**Comment by ohadlevy** [comment]
merged - thanks!

**Pull request closed without merging**
