### PR TITLE
fixes #2236 - add option for hosts parameters to show on host properties page with searchable link on parameter value

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@abenari, can you look at the UI. If a HostParameter has "Show as Property" boolean is true, then it shows up at the bottom of the Properties table on hosts#show.  This is what jb wanted in issue #2236

**Comment by isratrade** [comment]
@domcleal, not much unit / functional testing for this PR, right?  Integration testing would be relevant though.

**Comment by GregSutcliffe** [comment]
I'm not sure this fixes #2236 actually - at least not completely. The point is to be able to show arbitrary data. While this allows you to show host parameters (which covers some user-defined data), you can't show anything else we know about a host - facts, subnet, IPs, compute resource details, and so on (some of this, such as IPs are already on the Host page, but I'm listing them for completeness). Facts are the big one, since they are also user-defined data - we definitely need a way to show them if we're going to close 2236, in my opinion.

I'm also wondering if we're overcomplicating the Parameters page - there's a lot going on there already. I'm not sure a box after every parameter is the cleanest solution here.

I was thinking of a slightly different approach - some way to specify a mini-template to display (as the column_view plugin does) where the extra piece of info is completely arbitrary (e.g. `<%= @host.subnet %>` or `<%= @host.facts_hash['uptime'] %>`) - this seems a much more general solution to me. However, I appreciate we then need a way to specify those extra fields.

To me, this is starting to feel like quite a niche requirement, i.e. a plugin rather than core, but I could be in the minority. If you agree, perhaps we need to extend the column_view plugin to be even better (despite the name, it can already add info to the Host page).

(I appreciate that all sounds really negative - it's going to be good to be able to display this stuff, but I don't think this is the direction we need)

**Comment by isratrade** [comment]
@GregSutcliffe, you're right. This PR is not "custom field" functionality.  It's just UI changes. The request from jb was for "management types" to view more "host properties" on the #show page and hyperlink the values for search_for, rather than having to go to #edit and then the parameters tab.  

An alternative option is to show ALL host parameters on the #show page under properties. This eliminates the migration and selectbox after each parameter .What do you think about this?

I suggest to create a new issue # and not use fixes #2236 for this PR.  

Separate functionality, I created an engine https://github.com/isratrade/foreman_custom_parameters which creates default parameters upon host creation (or hostgroup, os, domain).  This could be needed and a time-saver for some users.  Again, it's not "custom fields" functionality though.

**Comment by domcleal** [comment]
I concur with @GregSutcliffe, let's keep this out of core.  I think column_view goes quite a way to solving this at the moment (but with even more flexibility, as it can show facts under Properties too), but I could imagine adding this UI into the column_view plugin would solve the same problem without cluttering up core.

**Pull request closed without merging**
