### PR TITLE
Fixes #22778 - disableable bruteforce protection

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Perhaps it should be the number of attempts that's configurable? `0` for disable?

**Comment by lzap** [comment]
Absolutely, number of attempts should be configurable with 0 to disable it.

**Comment by ares** [comment]
@ekohl and @lzap updated the setting to integer as suggested

**Review by ekohl — APPROVED** [review]

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Comment by ares** [comment]
error unrelated, if we merge now, I have something to demo :-)

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
Thanks merged.

**Pull request merged**
