### PR TITLE
fixes #11149 - foreman-debug to collect two httpd katello.conf files

### PR DESCRIPTION
**Pull request by pmoravec**
in particular:

/etc/httpd/conf.d/05-foreman-ssl.d/katello.conf
/etc/httpd/conf.d/05-foreman.d/katello.conf

Signed-off-by: Pavel Moravec pmoravec@redhat.com

### CODE REVIEW

**Comment by lzap** [comment]
Can you move this into https://github.com/Katello/katello/blob/master/deploy/script/katello-debug.sh and flip the issue to Katello project instead? In Foreman Core we don't deploy any subdirectories there. Thanks

**Comment by domcleal** [comment]
@lzap well, we create the 05-foreman*.d directories in foreman-installer, e.g. https://github.com/theforeman/puppet-foreman/blob/master/manifests/config/passenger.pp#L100

**Comment by domcleal** [comment]
Merged as 56f7e20, thanks @pmoravec.

**Comment by lzap** [comment]
Haven't noticed that when I was checking, sorry `bout that.

**Pull request closed without merging**
