### PR TITLE
refs #2127 - add password_hash to API

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by isratrade** [comment]
@domcleal, lgtm, will merge after tests pass.

**Comment by lzap** [comment]
Sorry I missed this during my review. Mind writing few tests after you're back @witlessbird ? Tests are green!

**Comment by isratrade** [comment]
@lzap, I think that this can be merged without testing whether an attribute is included the response, since we don't test any other place if the expected attributes are in the response.

**Comment by lzap** [comment]
I am not sure what you mean, I was under impression you tested this and
you are going to merge this.

## 

Later,
 Lukas #lzap Zapletal

**Comment by isratrade** [comment]
@lzap, I will merge this without having a specific functional that `password_hash` appears in the response.

**Comment by isratrade** [comment]
merged as e5ee733519005503e7aeaa01c17650091c67bc86, thanks @domcleal !

**Pull request closed without merging**
