### PR TITLE
Fixes #19696 - Validate email addresses with extra dots.

### PR DESCRIPTION
**Pull request by rabajaj0509**
This commit adds a regex expression that validates the email addresses for extra dots.

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
@rahulbajaj0509 Looks like tests are failing with this change. Also, since this uses the email validator, please make the changes to the validator itself which you can find in `app/validators/email_validator.rb`.

**Comment by lzap** [comment]
Yep, never test emails with regexp, there can be much more weird characters in emails than you think :-)

**Comment by rabajaj0509** [comment]
@lzap then what do you think could be the solution rather than using a regexp ?

@tbrisker what is your call on using regexp ?

**Comment by rabajaj0509** [comment]
I have gone through this bug carefully and come to the conclusion that this has not been handled by the 'Mail' gem itself. There is no problem as such with our code. 

I have also raised an issue in the 'Mail' gem : 
https://github.com/mikel/mail/issues/1124

**Comment by rabajaj0509** [comment]
After raising an error with the mail gem, it seems that they have left out this feature intentionally for some reason. Therefore i have made the required changes in the code to handle consecutive dots in the e-mail address :)

**Comment by dLobatog** [comment]
@rahulbajaj0509 I would follow the advice at the threads pointed out by the Mail maintainer. These emails can be seen in the wild even if they don't adhere to the RFC:

https://github.com/swiftmailer/swiftmailer/issues/239
https://github.com/swiftmailer/swiftmailer/issues/71

To be fair I would close the issue and the attached bugzilla as won't fix, it's not worth being that restrictive (more so than GMail, for example, try sending emails to .....................youraddress......@gmail.com

**Review by dLobatog — COMMENTED** [review]
@rahulbajaj0509 I would follow the advice given by the Mail maintainer on the threads he posted. The point is these mail addresses violate the RFC but are common on the wild. Validating them means that in some time we would get reports saying they don't work:

https://github.com/swiftmailer/swiftmailer/issues/71
https://github.com/swiftmailer/swiftmailer/issues/239

I don't think being more restrictive than GMail (try sending an email to y.o.ur.....address....@gmail.com - it will get delivered to -> youraddress@gmail.com just fine) is worth it, especially when these addresses are used by some people. Feel free to close the attached Bugzilla as NOTABUG/WONTFIX

**Comment by rabajaj0509** [comment]
@dLobatog  thanks for your input on this one :)

**Pull request closed without merging**
