### PR TITLE
WIP: Fixes #33418 - Rework outofsync interval

### PR DESCRIPTION
**Pull request by nadjaheitmann**
This PR makes [puppet|ansible] interval setting overridable as host/hostgroup parameter instead of the global outofsync_interval setting. See forum discussion [here](https://community.theforeman.org/t/outofsync-interval-vs-origin-downcase-interval/24538).

This PR is still missing
- [ ] refactor of parameter/setting name
- [ ] more unit tests ?
- [ ] dashboard customization? (see details below)
- [ ] possible extensions for other parameters than host/hostgroup parameters

I have noticed an inconsistency with the dashboard. I set `ansible_interval` to e.g. 5 minutes and `outofsync_interval` to something bigger, 30 in the example. Configuration status for all is all fine, but for Ansible the same hosts are marked as `out of sync`. This problem becomes slightly more severe when you start changing the interval on a host or hostgroup level. I need a hint whether this a) works as intended or b) needs fixing. If it needs fixing, whether this should be done in the PR or a follow-up PR.

image

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
[test_katello]

**Comment by ekohl** [comment]
I like the direction of this PR but I would consider deprecating the old `outofsync_interval` altogether. Then you would only have `puppet_interval` and `ansible_interval`. Is it only Puppet and Ansible that base their interval on it?

**Comment by nadjaheitmann** [comment]
> I like the direction of this PR but I would consider deprecating the old `outofsync_interval` altogether. Then you would only have `puppet_interval` and `ansible_interval`. Is it only Puppet and Ansible that base their interval on it?

As of now, it is only Puppet and Ansible, not Salt and Chef afaik. If `outofsync_interval` is removed altogether, then what if there were hosts that have not sent any reports, yet?

**Comment by ekohl** [comment]
I must admit I haven't thought it through that much. I was reasoning from a user perspective.

However, no reports at all should be easy to detect, right? Thinking more, that case can't really be distinguished from the case where it hasn't reported in a certain period and all reports have been deleted because they were too old (default is 2 weeks or so?)

**Comment by nadjaheitmann** [comment]
> However, no reports at all should be easy to detect, right? 

I think so. It should say `last_report` is nil for host.

> Thinking more, that case can't really be distinguished from the case where it hasn't reported in a certain period and all reports have been deleted because they were too old (default is 2 weeks or so?)

If there ever was a report, it will set `last_report` to a particular date, if there was none, it should be `nil`. But if there are no reports at all (even if there were reports before), not sure whether there is a way to find out which configuration system is used for that particular host (looking from the dashboard perspective).

**Comment by nadjaheitmann** [comment]
@ekohl What do you think about adding addition parameter types to override? Right now it is only `HostParameter` and `GroupParameter` and it is fairly easy to add additional parameters.

**Comment by lzap** [comment]
> I like the direction of this PR but I would consider deprecating the old `outofsync_interval` altogether. Then you would only have `puppet_interval` and `ansible_interval`. Is it only Puppet and Ansible that base their interval on it?

Oh, I just commented in the Community thread about the same. I think we should now only present individual configuration management systems, its widgets and statuses in the UI/CLI. Overall "configuration" never made sense to me.

But I think more work needs to be done:

* Host has last_report field, that is a generic one. This could be stored in host facet similarly how we do in host_facets_reported_data_facets.
* @ares was talking today about probably moving status calculation to a background process and that this was mentioned by @stejskalleos if that turns out to be something we want to work on, we need to find a place to store this information, maybe if we can create a table (host_id, plugin_name, status_as_int) that could be generic enough so plugins (not only configuration management) could use this to generate searchable statuses

**Comment by nadjaheitmann** [comment]
> But I think more work needs to be done:
> 
>    * Host has last_report field, that is a generic one. This could be stored in host facet similarly how we do in host_facets_reported_data_facets.
>     * @ares was talking today about probably moving status calculation to a background process and that this was mentioned by @stejskalleos if that turns out to be something we want to work on, we need to find a place to store this information, maybe if we can create a table (host_id, plugin_name, status_as_int) that could be generic enough so plugins (not only configuration management) could use this to generate searchable statuses

Thank you @lzap . What does this mean for this PR? Wait until future design and dependencies become clear?

**Comment by lzap** [comment]
> What does this mean for this PR?

Nothing really, sorry, carry on. I like the proposal.

**Comment by nadjaheitmann** [comment]
> > What does this mean for this PR?
> 
> Nothing really, sorry, carry on. I like the proposal.

@lzap @ekohl What about I finishing up this PR by adding the other parameter types and adjusting the dashboard to show the right numbers? Then, I can open a follow-up PR that 

1.  removes the global `outofsync_interval` altogether + adjusting the dashboard
2.  maybe also refactors the parameter name to something like `ansible_outofsync_interval` and `puppet_outofsync_interval` (and adds 
3. adds an `salt_outofsync_interval` and `chef_interval` to the remaining plugins that should be shown on the dashboard

I think that removing the global `outofsync_interval` might need less obvious changes to Foreman, probably API(?) and testing. And it is technically separate from making making the `[puppet|ansible] _interval` overridable - so IMHO, it is cleaner to go with a follow-up PR.

**Comment by ekohl** [comment]
I think the plan makes sense, but I'm not too familiar with this area (only the Puppet side). Perhaps @ares has more insight in others.

**Comment by lzap** [comment]
I am okay, do you like the current proposal @ares ? If you do, I can handle formal review and testing.

**Comment by ezr-ondrej** [comment]
What is the status here @nadjaheitmann I believe we do want to get this in. Will you be able to finish this up, or should we brainstorm how to split this into smaller chunks and multiple PRs?

**Comment by nadjaheitmann** [comment]
> What is the status here @nadjaheitmann I believe we do want to get this in. Will you be able to finish this up, or should we brainstorm how to split this into smaller chunks and multiple PRs?

@ezr-ondrej This still has some problems I would like to brainstorm about. First thing is that performance is bad and second is that filter search links breaks.

**Pull request closed without merging**
