### PR TITLE
fixes #10441 - sort time and count-based columns in descending order

### PR DESCRIPTION
**Pull request by stbenjam**
Small usability tweak IMHO. On the hosts page, for example, if you're sorting by last reported, you're interested in the most recent.

### CODE REVIEW

**Comment by iNecas** [comment]
:+1:

**Comment by domcleal** [comment]
Probably also "Last report" on report/_list (and other columns) and hosts_count on realms/index?

**Comment by domcleal** [comment]
Did you want to include the "Last report" column in the report list too?

**Comment by stbenjam** [comment]
@domcleal `report/_list` default sort is on Last Report descending, so when you click it you want it go in reverse.

Updated realm.

**Comment by domcleal** [comment]
Ah yes, thanks.

**Comment by domcleal** [comment]
FYI, I filed https://github.com/wvanbergen/scoped_search/pull/126 as it appears to me that the ascending/descending arrows were pointing the wrong way, compared to other apps and our JS table impl.

**Comment by dLobatog** [comment]
Merged as 13325e01e0aa6c1ff795363f2aa6530a319573f0, thanks @stbenjam!

**Pull request closed without merging**
