### PR TITLE
Fixes #34942 - Adapt installation media search path for Ubuntu 20.04.3+

### PR DESCRIPTION
**Pull request by bastian-src**
Due to the old boot files path not being available any more (see [here](http://archive.ubuntu.com/ubuntu/dists/jammy/main/installer-amd64/current/legacy-images/)), the new path must be used (see [here](https://ubuntu.com/server/docs/install/autoinstall-quickstart)).

* introduce a function `is_subiquity?` to determine whether the new Ubuntu Autoinstall subiquity mechanism is used
* return new path according to Ubuntu version

### CODE REVIEW

**Comment by bastian-src** [comment]
[test foreman]

**Comment by bastian-src** [comment]
@lzap this is related to #9136. Would be great if we could cherry-pick both PRs for 3.1 in order to enable Ubuntu 22.04 support.

**Review by lzap — DISMISSED** [review]
Makes sense, I haven't tested, tests are red.

**Comment by ofedoren** [comment]
ok to test

**Comment by bastian-src** [comment]
Thanks @ofedoren! All tests seem to be fine.
Can you maybe tell me what I can do to cherry-pick this PR (and other related PRs) also for 3.1?

**Comment by ofedoren** [comment]
> Thanks @ofedoren! All tests seem to be fine. Can you maybe tell me what I can do to cherry-pick this PR (and other related PRs) also for 3.1?

Usually, you'd need to only create a separate PR with cherry-picks against e.g. 3.1-stable branch. But AFAIK we are done with releases for 3.x, but we better ask @upadhyeammit about that.

**Comment by bastian-src** [comment]
@ofedoren even if the cherry-pick question is not answered, we can merge this PR already to `develop`, right?

**Review by ofedoren — APPROVED** [review]
@bastian-src, yeap I guess so. LGTM and the tests are green, so merging.

**Pull request merged**
