### PR TITLE
fixes #21117 - update to react 15.6.2 (now with MIT license).

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Review by waldenraines — APPROVED** [review]
Everything I tested out worked for me.  Thanks @ohadlevy!

**Review by boaz0 — APPROVED** [review]
LGTM 💯

**Comment by ohadlevy** [comment]
@dLobatog any chance you can review this? thanks :-)

**Review by dLobatog — APPROVED** [review]
Looks good, no obvious issues on my setup with this version. Thanks @ohadlevy @ripcurld0 @waldenraines

**Pull request merged**
