### PR TITLE
fixes #5106: only puppet and puppet-ca proxies are now being shown on the 'new host' page

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by lzap** [comment]
I can confirm this fixes the issue. I can see only Puppet/Puppet CA there.

**Comment by domcleal** [comment]
@isratrade could you take this please?

**Comment by domcleal** [comment]
I'm wondering if we need the _override version any more?

**Comment by dmitri-d** [comment]
Can't quite remember, I think _override is being used some place else?

**Comment by domcleal** [comment]
Yeah, it seems to be used by other fields, just wondering if we even need it (and its unscoped call) if with_taxonomy_scope overrides them correctly.

**Comment by dmitri-d** [comment]
Agreed, I especially dislike the "unscope" bit -- a rather serious side effect. Probably worth creating a dedicated ticket though (want me to create it?)...

**Comment by domcleal** [comment]
That'd be good thanks, a refactor ticket.

**Comment by dmitri-d** [comment]
pls. see http://projects.theforeman.org/issues/5445

**Comment by domcleal** [comment]
Merged as 50e0bc5 for Foreman 1.5.0, thanks @witlessbird!

**Pull request closed without merging**
