### PR TITLE
Fixes #14071 - Using Sprockets directive to require host_edit_interfa…

### PR DESCRIPTION
**Pull request by xprazak2**
…ces.js

### CODE REVIEW

**Comment by ohadlevy** [comment]
IMHO sass include are now the default vs sprockets.

**Comment by dLobatog** [comment]
@xprazak2 What is `host_edit` used for in Taxonomies#edit ? I'm just wondering if we can do without loading that in there, in any case I don't think this affects the form other than the error is shown in there.

**Comment by xprazak2** [comment]
dLobatog: I have found that it is used when overriding parameters for locations. I started poking into it because I thought that it was related to #3218, but I double-checked and you are right, it does not seem to be breaking anything. I will try to extract the function somehow to get rid of the error.

**Comment by xprazak2** [comment]
I extracted the functions that are used for parameter overriding so we do not have to load the whole host_edit file in taxonomy/edit page.

**Comment by dLobatog** [comment]
@xprazak2 :clap: nice! Will merge if green

**Comment by dLobatog** [comment]
Merged as d05be6d1b8b17e679fbea54b07b06425dc2622ed, thanks @xprazak2!

**Pull request closed without merging**
