### PR TITLE
Fixes #26838 - Updated VMware vSphere 6.7 GuestOSIdentifier

### PR DESCRIPTION
**Pull request by snagoor**
Updated Guest OS identifier types per https://code.vmware.com/apis/358/vsphere/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html

### CODE REVIEW

**Comment by mmoll** [comment]
Katello test failure unrelated :green_heart:

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @snagoor!

**Comment by snagoor** [comment]
@mmoll Thank you for merging this. 

I believe we would also need an updated rbvmomi gem (https://github.com/vmware/rbvmomi) which contains the latest `vmodl.db` correct? 

In my environment, I had to manually replace this file to correctly identify the VMware Guest OS (i.e. Red Hat Enterprise Linux 8.0) when importing the VM from the VMware compute resource, otherwise its detecting wrong OS selection such as `Microsoft Dos`

**Comment by mmoll** [comment]
@snagoor No idea, tbh. At least in the past we didn't see such problems... Which does not mean, there will be none now...

**Comment by mmoll** [comment]
@snagoor BTW, AFAICT that would only hit RPM installs... then open an RPM PR over in https://github.com/theforeman/foreman-packaging and if this really fixes it a followup PR to bump the minimum version of rbvmomi in `bundler.d/vmware.rb` here.

**Pull request merged**
