### PR TITLE
Fixes #25869 - humanize name of TemplateKind in Audit log

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Humanizing is in `to_s` but should be "higher" - in `to_label`.

### CODE REVIEW

**Comment by ares** [comment]
ok to test

**Comment by lzap** [comment]
With the patch, I still see this in audit log:

```
[aud|I|8b5|643] ProvisioningTemplate (112) update event on template <%#
 | kind: PXELinux
 | name: An org test
 | model: ProvisioningTemplate
 | organizations:
 |  - SecondOrg
 | locations:
 |  - MyLoc
 | %>
 | test, <%#
 | kind: PXELinux
 | name: An org test
 | model: ProvisioningTemplate
 | organizations:
 |  - SecondOrg
 | locations:
 |  - MyLoc
 | %>
 | test2
```

Is this expected? I would expect model name rather than full template content.

**Comment by lzap** [comment]
Maybe I fail to understand what behavior you aim to change, can you elaborate on that please?

**Comment by ezr-ondrej** [comment]
The behaviour you experience comes from line https://github.com/theforeman/foreman/blob/c7e160b443424aed86bed57a58d300c8f65b9cdf/app/models/concerns/audit_extensions.rb#L138
where actually should not be the model present at all. I am not sure, what is causing the issue you have found, but would be weird my change could causing it.
I am addressing issue of bad humanization in GUI. Where change of Template type have been reported as TemplateKind#name - what comes from default implementation of to_label - but it is not humanized name.

There is a fallback allias to_s -> to_label and to_s gave already correctly humanized result, so I just forced them to both return humanized result.

**Comment by lzap** [comment]
Looks like a different one really. Anyway, how do I reproduce? Template kind is not an editable entity for user. Would you mind attaching a screenshot before and after the patch so I can see it?

**Comment by ezr-ondrej** [comment]
Yeah sure, would have been a good idea, right? Sorry :disappointed: 
Before
screenshot-2019-01-22 10-17-46
After
screenshot-2019-01-22 10-19-55
Notice the last row :female_detective: :)

**Review by lzap — APPROVED** [review]
Gotcha, thanks.

**Pull request merged**
