### PR TITLE
Fixes #27809 - wraps JS API functions with foremanUrl

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Review by tbrisker — DISMISSED** [review]
Thanks @amirfefer !

**Comment by tbrisker** [comment]
@amirfefer can you take a look at the jest failures? I think they are related but not 100% certain

**Comment by amirfefer** [comment]
I fixed the related tests, but still, there are 2 failures as a regression from https://github.com/theforeman/foreman/pull/6999 
EDIT: it a bit odd, but the new `LineChart` test failed only on my env (after reinstall npm):
```
 FAIL  webpack/assets/javascripts/react_app/components/common/charts/LineChart/LineChart.test.js
  ● Line Chart › should render line chart with timeseries

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "Line Chart should render line chart with timeseries 1".

    - Snapshot
    + Received

    @@ -35,13 +35,13 @@
                4,
                6,
              ],
              Array [
                "x",
    -           1557014400000,
    -           1559779200000,
    -           1562457600000,
    +           1557003600000,
    +           1559768400000,
    +           1562446800000,
              ],
            ],
            "onclick": [Function],
            "x": "x",
          }
```
looks like `getTime` returns a diffrenet value :confused:

**Comment by tbrisker** [comment]
> looks like getTime returns a diffrenet value confused

Looks like the times are off by 10800000 - which if i'm not mistaken is exactly 3 hours. This leads me to think there is a timezone difference in play.

**Review by tbrisker — APPROVED** [review]
Thanks @amirfefer !

**Pull request merged**
