### PR TITLE
Refs #19050 - Use Rails 4.2 on Ruby 2.3

### PR DESCRIPTION
**Pull request by mmoll**
This unbreaks Ubuntu/xenial and Debian/stretch nightlies

### CODE REVIEW

**Review by dLobatog — COMMENTED** [review]
@mmoll Does this not affect rpm nightly too?

**Comment by mmoll** [comment]
AFAICT no, but I don't watch these closely

**Comment by mmoll** [comment]
After seeing this again, nightly RPMs are using Ruby 2.2 now, so no change.

**Review by dLobatog — APPROVED** [review]
@mmoll Thanks. Let's merge to allow debs to at least test our nightlies and then we can figure out what to do next if it affects RPM.

**Pull request merged**
