### PR TITLE
Fixes #17796 - bump to rubocop 0.46

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
@mention-bot, you have found the perfect reviewers. Thank you!!1 :heart:

**Comment by tbrisker** [comment]
@shlomizadok This cop was only introduced in rubocop 0.44, while we currently pin rubocop to 0.42. 
Also, I'm not certain we should disable it but rather add to the todo since it will be required for rails 5 upgrade IIUC.

**Comment by shlomizadok** [comment]
@tbrisker - 
It is present (see: https://github.com/theforeman/foreman/pull/4024#discussion_r92941720, https://github.com/theforeman/foreman/pull/4118#discussion_r92996691 and other PRs)

I'll remove to .rubocop_todo

**Comment by tbrisker** [comment]
@shlomizadok hound runs with its own version of rubocop, which is currently 0.46. We should upgrade ours to match so that we can also run the same cops locally.

**Comment by shlomizadok** [comment]
OIC, so upgarde to 0.46 would be the right thing to do?

**Comment by dLobatog** [comment]
Thanks @shlomizadok @tbrisker !

**Pull request merged**
