### PR TITLE
fixes #8953 - update IPA userclass param on realm update

### PR DESCRIPTION
**Pull request by joshuabaird**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by stbenjam** [comment]
[test]

**Comment by dLobatog** [comment]
@joshuabaird Thanks for the patch! Could you write a test for it? :+1: to merge after that

Apologies for the delay :bow: , my schedule has been a bit hectic latelyf

**Comment by stbenjam** [comment]
@joshuabaird This should do it https://github.com/stbenjam/foreman/commit/626f0938af98043704d4b91cb7ed048d3585227f

**Comment by dLobatog** [comment]
@joshuabaird ping? @stbenjam if you want you can open a new PR rebased against this branch and I'll merge both PRs (yours for the tests, @joshuabaird 's for the patch)

**Comment by stbenjam** [comment]
Oh, @joshuabaird if you have time you can just add the tests to your PR

**Comment by stbenjam** [comment]
Actually disregard, I opened a new PR #2170 (I left you as the author @joshuabaird).

@eLobato You can close this one

**Comment by dLobatog** [comment]
Merged as 2d09a3cc84e1da93e0b20748c1936136c2c6045d , thanks @joshuabaird 

I'll merge your PR separately, changing the name to 'refs' since it's the tests, thanks @stbenjam too

**Comment by joshuabaird** [comment]
Thanks @eLobato and @stbenjam  - sorry for the delay.

**Pull request closed without merging**
