### PR TITLE
Fixes #28480 - Raise exception for non-existing image in GCE

### PR DESCRIPTION
**Pull request by eLvErDe**
I use custom images and deleted the one associated to the selected operating system.
End up with nil related issue and had to look into the code to figure out what was going so here's a PR raising a custom exception with better error message

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
ok to test

**Comment by ezr-ondrej** [comment]
@eLvErDe  could you please shorten the commit description?
Otherwise LGTM, @kgaikwad could you take a look? :)

**Review by kgaikwad — COMMENTED** [review]
@eLvErDe, 
Codewise looks good to me. But while testing the change from web-UI, I am still getting an error stack trace on the page with 500.
Not sure this is just me or you are also getting the same behavior, please confirm.

**Comment by eLvErDe** [comment]
Hello,

Well I did not checked the error code but yes it is still failing and that's excepted. The aim of the change is just to provide a better error message so the user can understand the image id associated to his operating system is invalid

**Review by kgaikwad — DISMISSED** [review]
Thank you @eLvErDe for confirming the behavior.
I noticed that you already updated a commit message but message formatting needs a correction to make it consistent. Something like - `Fixes #28480 - Raise exception for non-existing image in GCE`

For more details refer - https://projects.theforeman.org/projects/foreman/wiki/Reviewing_patches-commit_message_format

@ezr-ondrej,  
Once commit message format is fixed and no any additional comment then feel free to merge this PR :-)

For reference adding a web-UI screenshot -
Screenshot from 2019-12-11 16-23-57

**Comment by ezr-ondrej** [comment]
Yeah, it's not really nice, but there is an PR that is trying to improve this in foreman, so let's hope it gets in soon :)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @eLvErDe for the addition and @kgaikwad for the review! :+1:

**Pull request merged**
