### PR TITLE
Fixes #33986 - moves Callback ensures to separate files

### PR DESCRIPTION
**Pull request by ezr-ondrej**
We do not need to define the Ensure classes in core_extensions.
These are better off in separate files.

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej !

**Comment by evgeni** [comment]
can we next time ensure that such breaking changes at least have plugin PRs open ahead of merging?

this broke building discovery (a build that worked yesterday), so a PR that @lzap opened for packaging yesterday was now merged and is not building anymore, clogging our pipelines.

**Comment by tbrisker** [comment]
Sorry about that, my bad.

**Comment by lzap** [comment]
Yeah I will fix this. Honestly, this pace is a bit rough for plugin authors, I have 3+ plugins to catch up and what I need to do is test them with the stable version, fix all bugs, get the releases into nightly, backport this into the stable version packaging. It takes few days or weeks for some of us (hello @lzap!)

I'd appreciate if we could hold off just a tad until things settle down. Maybe not GA but RC3-ish date would be great:

https://community.theforeman.org/t/proposal-postpone-after-branching-refactoring-until-ga-is-out/26316

I am going to tag my 19.0 discovery (3.1 compatible) now, only then I can fix nightly, then I will do backport into 18.0 (which is rather unusual but thanks to puppet extraction we are still catching up). Hopefully I will not mess things up, but I highly doubt that so I need to test everything.

**Comment by ezr-ondrej** [comment]
I'm sorry about causing the mess with this, I believed we use this without the namespace everywhere and didn't believe this will cause any issues. But if we can't push breaking changes post branching, it becomes even harder to do some refactoring and IMHO we do not do enough of refactoring today and it makes our code quite ancient and we keep unecessary workarounds for years.

**Comment by evgeni** [comment]
I don't say we shouldn't do breaking changes after branching. But if we know that these changes will actually affect plugins (I think in this case we did) and we know plugins don't follow branching to the day, I think we should try to at least give plugin maintainers time to realize there is a breaking change coming and possibly act accordingly, instead of interrupting their preparation of the next stable plugin release.

**Comment by ezr-ondrej** [comment]
There I agree, but I realized only after it was merged, I've opened too many PRs and most of them were safe...
That was definitely my fault, for which I apologize, I'll try to think about consequences more.

**Pull request merged**
