### PR TITLE
Fixes #30519 - Add queries for config reports

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by xprazak2** [comment]
All green now.

**Comment by ezr-ondrej** [comment]
This works well and I do not intend to block it, so take this just as an idea:
Wouldn't it be nice to have the association from host to reports as well?

**Review by ezr-ondrej — DISMISSED** [review]
Works, just an idea above, but can be in separate PR once it finds it's use.

**Comment by xprazak2** [comment]
I added reports to host as well.

**Review by ezr-ondrej — APPROVED** [review]
Cool! thanks @xprazak2 !

**Comment by xprazak2** [comment]
Can I have a merge please?

kitten_please

**Comment by ezr-ondrej** [comment]
Thanks @xprazak2, sorry for the waiting! :(

**Pull request merged**
