### PR TITLE
Revert "Fixes #28945 - Taxonomy scope for interfaces action"

### PR DESCRIPTION
**Pull request by mmoll**
Reverts GH-7468

### CODE REVIEW

**Comment by mmoll** [comment]
This is just to show that this revert fixes the browser integration tests.

**Comment by mmoll** [comment]
all :green_heart:

**Comment by ares** [comment]
I believe @stejskalleos will take a look at fixing the test, thanks for PR confirming which commit caused that!

**Comment by ares** [comment]
Oh, he already did - https://github.com/theforeman/foreman/pull/7499, this is probably replaced by that PR. I'm closing this one for now, thanks again @mmoll!

**Pull request closed without merging**
