### PR TITLE
fixes #5389 - URL doesn't update correctly after creating a new host

### PR DESCRIPTION
**Pull request by abenari**

### CODE REVIEW

**Comment by dLobatog** [comment]
I updated the title to point to http://projects.theforeman.org/issues/5389 instead of 5132

**Comment by domcleal** [comment]
If merging, please be sure to amend the commit message too.  Thanks.

**Comment by dLobatog** [comment]
@abenari The fix looks right, however I could not get my computer (Ubuntu 14.04, Firefox 29, Chrome 34) to update the URL on the bar after creation of a host. Do you know any steps/any setup in which this works?

**Comment by abenari** [comment]
@eLobato works on my environment :), fedora 20 chrome 34.
Please make sure you are clearing the browser cache before testing the patch.

**Comment by abenari** [comment]
changed commit message to the correct bug number.

**Comment by dLobatog** [comment]
Nevermind, it was me not recompiling the assets. :)

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/5f58478b95ffd51eb41f53718e09c03a3613c827 for Foreman 1.5, thanks @abenari !

**Pull request closed without merging**
