### PR TITLE
Fixes #25091 - exclude snapshots rake task on production env

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ares** [comment]
Interesting issue, does it make sense to ship the rake task in deb/rpm packages in case it does not work?

**Comment by ares** [comment]
alternative fix #6101

**Comment by timogoebel** [comment]
@mmoll: Does the fix in #6101 also work for you? I like it a little bit more.

**Comment by mmoll** [comment]
@timogoebel GH-6101 also fixes the problem :+1:

**Pull request closed without merging**
