### PR TITLE
Fixes #21450 - Update rubocop to 0.51.0

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by mmoll** [comment]
If possible, I suggest to have a run with 0.49 over all the files and fix everything before regenerating the _todo file with 0.51, there are a few violations.

**Comment by tbrisker** [comment]
@mmoll thanks, I fixed those that were obvious, the others will have to go to the todo list.

**Comment by timogoebel** [comment]
@tbrisker: We also need to change this across _all_ plugins as the CI tests will use the new version regardless of what the plugins specified.

**Comment by tbrisker** [comment]
@timogoebel thanks, I sent a mail to the -dev list giving everyone a heads up on this and what needs to be done.

**Review by timogoebel — APPROVED** [review]
Looks good, thanks @tbrisker.

**Pull request merged**
