### PR TITLE
Fixes #37115 - Drop unused react-dnd-test-utils dependency

### PR DESCRIPTION
**Pull request by ekohl**
Testing out if this breaks things.

### CODE REVIEW

**Comment by ekohl** [comment]
At least the JS tests pass with this, rest is still running.

**Comment by MariaAga** [comment]
Should it also be removed from `package-exclude.json`?

**Comment by ekohl** [comment]
@evgeni I recall that sometimes it was useful to keep it in for stable branches. Do you recall?

**Comment by evgeni** [comment]
It's useful for plugins, foreman itself would use the branch-matching exclude (I think)

**Comment by ekohl** [comment]
Oh yes, plugins were the reason.

I'll note that with this and raising the max version to `< 19.0.0` I could at least get `npm install` and a compile to work on NodeJS 18.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
