### PR TITLE
Fixes #24657 - Pin react-bootstrap to 0.32.1

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Packaging should be ok, 0.32.2 was recently released and makes quite significant changes in dependency versions, which is likely reason for the failures.

**Comment by xprazak2** [comment]
I added fixes for bookmark tests.

**Review by mmoll — APPROVED** [review]
test failure unrelated.

**Comment by mmoll** [comment]
merged, díky @xprazak2!

**Comment by mmoll** [comment]
@xprazak2 could you open cherry-pick PRs to the stable branches?

**Pull request merged**
