### PR TITLE
Fixes #7562 - reducing number of reports created by test to stop sigkill ...

### PR DESCRIPTION
**Pull request by orrabin**
...during test

### CODE REVIEW

**Comment by domcleal** [comment]
Could you run `/usr/bin/time rake ...` before and after the change - just for the one test would be fine.  It should hopefully record the maximum memory size, so we should see a noticeable difference (decrease!).

**Comment by orrabin** [comment]
@domcleal these are the results:

before change:
35.45user 1.91system 0:38.35elapsed 97%CPU (0avgtext+0avgdata 2907344maxresident)k
0inputs+26520outputs (0major+246155minor)pagefaults 0swaps

after change:
27.32user 1.47system 0:29.14elapsed 98%CPU (0avgtext+0avgdata 2540400maxresident)k
0inputs+21880outputs (0major+223589minor)pagefaults 0swaps

**Comment by domcleal** [comment]
So it dropped by 400MB or so, not bad.  Given we run 4/5 in parallel on a slave, that'll make a decent difference I think.

**Comment by orrabin** [comment]
@domcleal I hope it is enough to stop the error.
I just changed the commit message so tests are running again, can you merge when it's finished?

**Comment by isratrade** [comment]
merged as bd058e6739a0020e35056d7c223f7dfe16eec785. Thanks @orrabin !

**Pull request closed without merging**
