### PR TITLE
fixes #14170 - permit 'zone' parameter for GCE CR creation

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by tbrisker** [comment]
@domcleal is there a reason we don't just alias zone to url? Looks like it effectively already is: https://github.com/theforeman/foreman/blob/develop/app/models/compute_resources/foreman/model/gce.rb#L59

**Comment by domcleal** [comment]
Do you mean: is there a reason it's not using alias_attribute rather than having its own getter/setters?  I think even if using alias_attribute/method etc it'd still need to be explicitly listed for attr_accessible.

The reason we probably don't use `url` in the form is also linked to the API, which accepts "zone" and various other aliases for compute resources, shows them in API responses and just uses this field for storage.

**Comment by dLobatog** [comment]
I had success with this - however we might want to change the manual for 1.11, the way of obtaining the API key in GCE is a bit different now, and not very intuitive (http://www.theforeman.org/manuals/1.10/index.html#5.2.4GoogleComputeEngineNotes)

**Comment by dLobatog** [comment]
Merged as 7c9391e615812c629acef99405af2cafde5f4cfe, thanks @domcleal!

**Comment by domcleal** [comment]
> however we might want to change the manual for 1.11, the way of obtaining the API key in GCE is a bit different now, and not very intuitive (http://www.theforeman.org/manuals/1.10/index.html#5.2.4GoogleComputeEngineNotes)

Could you file a ticket at https://github.com/theforeman/theforeman.org/issues please?  I'll try and run through it again soon and update it if nobody else does.

**Pull request closed without merging**
