### PR TITLE
fixes #2542 - sort image listing with datatables

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: useful fix, but not related to the bug.  Could you file a new one please?

**Comment by isratrade** [comment]
@domcleal, I corrected the commit message.  It fixes issue #2542

**Comment by domcleal** [comment]
@isratrade ah thanks, that makes more sense.  I see a data-table='inline' missing in app/views/compute_resources_vms/index/_openstack.html.erb which might have been what @ohadlevy meant in the original bug report too, could you add that please?

**Comment by isratrade** [comment]
@domcleal, re-committed with change to compute_resources_vms/index/_openstack.html.erb

**Comment by domcleal** [comment]
As discussed on IRC, the sort_asc and related assets seem to be missing, causing 404s.

**Comment by isratrade** [comment]
@domcleal re-committed with sort images

**Comment by domcleal** [comment]
Thanks @isratrade, merged as af1b6350!

**Pull request closed without merging**
