### PR TITLE
top-bar menu items reorderd

### PR DESCRIPTION
**Pull request by abenari**
1. Top menu reordered.
2. Created classes for menu items, sub menu and dividers, following katello navigation classes idea.

### CODE REVIEW

**Comment by abenari** [comment]
Needs to be merged with https://github.com/theforeman/foreman_discovery/pull/37
This commit will break any plugin that manipulated foreman top bar menu.

**Comment by ehelms** [comment]
A few comments:

1) I think the use of verbs in the left hand side breaks with expectations. If I click on 'Configure', I expect to see a list of objects that I can configure. Some might argue, CRUD is a type of configuration, but in most applications, to configure something does not mean managing CRUD on an entity. Another issue you run into is the expectation that when the menu is a verb (aka an action), the user is performing that action on said entity. So, if I see Monitor -> Dashboard, as a user I expect to go monitor my dashboard when in reality the dashboard is a form of monitoring for the user. Similar with "Provision", as a user I expect that to give me a list of objects that I can go provision, when the intent is to give me a list of entities that are related to the large process of provisioning. In the case of 'Adminster', this use of a verb works because the action I am going to perform is to administer one of the entities in the dropdown list that is presented to me as a user.

2) Typically, a Dashboard implies a landing place that is the root or interface that the user is returned to when not viewing something else. To hide it under a menu, and for that menu to be the farthest to the right seems to break from what I expect as a user.

3) I would expect to see subnets near domains given how closely related they are.

4) General comment since I am still coming up to speed on all Foreman entities and this may or may not be applicable. Ordering the items in the dropdown list such that the user sees a pattern of interaction can be helpful. Similar to the left to right workflow from above, users tend to think of a dropdown as the list of entities being in some logical order that they would interact with. The first item should be the first entity a user would need to create, the second the second etc. For example, if I were creating a dropdown of CRUD actions, I would expect to see them in the order of create, read, update, delete since I have to create items before I can read or update or delete them.

**Comment by ohadlevy** [comment]
@ehelms How would you call it then?

**Comment by ehelms** [comment]
@ohadlevy apologies for the delay, I wanted to do some proper research before I offered anything further, since this originally started on the dev list, I'll post my thoughts post-research there

**Comment by ehelms** [comment]
Since this PR is slightly disconnected from the dev list, as a follow up I ended up posting my thoughts here - https://groups.google.com/forum/#!msg/foreman-dev/uV_MZMD9Pi8/UXQ4jf1EOxMJ

**Comment by ohadlevy** [comment]
replaced by #987

**Pull request closed without merging**
