### PR TITLE
fixes #1875: users without 'view_hosts' permission do not see 'Bare Metal' option on the 'New Host' screen

### PR DESCRIPTION
**Pull request by dmitri-d**
Do not merge before https://github.com/theforeman/foreman/pull/1549 has been merged, as this PR depends on the updated 'anonymous' role.

### CODE REVIEW

**Comment by lzap** [comment]
FYI tests failed and typo in the commit headline

**Comment by dmitri-d** [comment]
@lzap, tests failures are because #1549 hasn't been merged yet

**Comment by dLobatog** [comment]
[test] now that https://github.com/theforeman/foreman/commit/a0bd5bb282c27f72a5e3746a1582b73366c15d21 has been merged

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
@eLobato, @lzap: rebased

**Comment by domcleal** [comment]
I'm a bit confused about the linking of view_hosts to bare metal host creation - wouldn't a new permission be more appropriate?

**Comment by dmitri-d** [comment]
@domcleal: hmm -- depending on the screen we don't always distinguish between physical and virtual hosts. Do you think we should introduce something like 'physical_host' set of permissions? Should we then update other screens, e.g. "Hosts", to use those?

**Comment by domcleal** [comment]
We distinguish viewing hosts using filters, e.g. a filter on host/managed where "compute_resource = foo".  I guess you could do something similar to filter viewing or editing to bare metal hosts with "not has compute_resource".

Viewing hosts aside, creation of hosts on a particular resource isn't restricted at the moment.  Frankly, I think this is a regression in Foreman 1.5 with the new filter system as there's no way to restrict on what CR/host group etc a host is created with.  http://projects.theforeman.org/issues/4477, http://projects.theforeman.org/issues/6470 and others track this.

I think all you need to worry about here is creating something like how "view_compute_resources" works here, restricting what CRs a user can see and thus provision onto...

**Pull request closed without merging**
