### PR TITLE
fixes #5690 - determine host taxonomy fact based on setting value

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by domcleal** [comment]
@eLobato could you review please?

**Comment by dLobatog** [comment]
Looks good to me, although I don't understand well the purpose, wasn't it picking up the fact with just the string instead of the symbol?

**Comment by stbenjam** [comment]
@eLobato Nope, the previous code was `taxonomy_class.find_by_title(facts["#{taxonomy}_fact"])`, which looked for a fact named `location_fact` instead of pulling the actual fact name from the `Setting[:location_fact]`.

**Comment by stbenjam** [comment]
And sorry if the to_sym was distracting, it's not really even needed for Setting.  I can remove it.

**Comment by dLobatog** [comment]
Oh got it, now I understand why tests were passing. Will test again and merge if OK.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/ea450c06aba11e03e6a5a926950b8c0cff1b8f2c , thanks @stbenjam !

**Pull request closed without merging**
