### PR TITLE
Fixes #25760 - audit emails generate incorrect links

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by ohadlevy** [comment]
does this work as expected? (I assume so, but wondering if we can write any test to verify) - also, can you expand the audit list if there is only one match?

**Comment by xprazak2** [comment]
It does not really work for me, I think the search query in URL needs some escaping. After clicking the link in e-mail, I get to `/audits?search=id%253D3245`, compared to `audits?search=id+%3D+3245&page=1` when searching in UI manually. Also link shown on hover does not look right:

**Comment by glekner** [comment]
added missing spaces for the query and a test. @xprazak2 can you take a look again ? Thanks

@ohadlevy
`ListView.Item` doesn't receive an `expanded` prop, as it manages it in its state ( not sure why ) 
I managed to make it work by rendering the child `ListView.GroupItem` but its not pretty.

**Comment by ohadlevy** [comment]
should we contribute / add this prop to PF ?

**Comment by ohadlevy** [comment]
does it make sense to split the issue? so the audits mails are enabled followed by a pr to expand the audit if there is only one item?

**Comment by glekner** [comment]
@ohadlevy
Its a one line change after my PF pr is merged https://github.com/patternfly/patternfly-react/pull/1114

**Comment by ohadlevy** [comment]
OK, do note we need to bump patternfly version prior to that.

**Comment by xprazak2** [comment]
Works! The ListItem is expanded after search:



Travis failures related.

**Comment by glekner** [comment]
travis fixed

**Comment by tbrisker** [comment]
Can we please split this into 2 PRs? one for fixing the audit mails which we will need to cherry-pick to the stable branches as well, and another to update the patternfly-react version and auto-expend the item which will only be in 1.22 or later (I don't want to bump a dependency during the stabilization period if we can avoid it).

**Comment by glekner** [comment]
@tbrisker removed js changes.
I have no idea why the snapshot has `initExpanded` value. seems to be in develop aswell

**Comment by tbrisker** [comment]
@glekner I think the snap change is because a new patternfly react version was released with your change and we don't pin to a specific enough version in package.json.

**Review by tbrisker — APPROVED** [review]
Thanks @glekner, just waiting for the tests to pass.

**Comment by mmoll** [comment]
foreman test failures unrelated :green_heart:

**Comment by mmoll** [comment]
Merged, thanks @glekner!
@glekner could you open a PR with a cherry-pick to 1.20-stable please?

**Pull request merged**
