### PR TITLE
Fixes #3122: 'column reference id is ambiguous' no longer appears on dashboard and report screens

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks @witlessbird, merged as 83b2874 for Foreman 1.3.1.  The SQL's nicer too :)

**Comment by isratrade** [comment]
nitpik, @witlessbird, just wondering by you decided to go with select("hosts.id") rather than pluck("hosts.id")
select() returns ActiveRecord::Relation and pluck() returns Array.

**Comment by dmitri-d** [comment]
@isratrade: pluck is the source of the problem in #3122 -- hence my use of select(). This seems to be ActiveRecord 3.2.8/pg specific though, I'll see if there's the same issue in 3.2.14.

**Comment by isratrade** [comment]
@witlessbird, interesting.  Good to know

**Pull request closed without merging**
