### PR TITLE
Fixes #22654 - ignore filters created by plugin DSL

### PR DESCRIPTION
**Pull request by ares**
@rplevka mind to test this? if you don't want to create new env, just delete all audits and restart Foreman with Katello

### CODE REVIEW

**Comment by ares** [comment]
@xprazak2 mind to review the code? I think you mostly worked on this area

**Review by tbrisker — APPROVED** [review]
Code makes sense, did not test it.

**Comment by xprazak2** [comment]
I tested, Katello permissions are no longer audited on freshly seeded db.

**Comment by tbrisker** [comment]
Thanks @ares and @xprazak2 !

**Pull request merged**
