### PR TITLE
Fixes #23699 - Remediation Support for Host Status

### PR DESCRIPTION
**Pull request by akshay-mendhe**

### CODE REVIEW

**Comment by akshay-mendhe** [comment]
Sorry for two PRs but first PR automatically closed while Github was down.

**Comment by akshay-mendhe** [comment]
Hello, @ares I am having one more doubt regarding taking this method to status.rb file. I moved this method as like to_label but is it Ok to make the method remediation_help_text as self method in build_status.rb file and should we pass any parameter to this method? as the method is now defined in both status.rb and build_status.rb file returning nil and string respectively. But now there is no object of class from build_status.rb that I can access in view, so should I make this method a class method?

**Comment by akshay-mendhe** [comment]
Hello, @lzap You already reviewed this one https://github.com/theforeman/foreman/pull/6135 , can you please take a quick review on this one?

**Comment by tbrisker** [comment]
Closing in favor of GH-6692, thanks @akshay-mendhe !

**Pull request closed without merging**
