### PR TITLE
fixes #5537: it's possible to specify menu item url directly now

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by waldenraines** [comment]
@witlessbird the following plugin menu definition;

``` ruby
   divider :top_menu, :parent => :content_menu
    menu :top_menu,
         :content_views,
         :caption => N_('Content Views'),
         :url_hash => {:controller => 'katello/api/v2/content_views',
                       :action => 'index',
                       :url => 'content_views'},
         :engine => Katello::Engine
```

is generating the url:  `/katello/api/content_views?url=content_views`.  I would expect that url to be `/content_views`.

**Comment by waldenraines** [comment]
This works great when I use it correctly, thanks!

**Comment by domcleal** [comment]
Looks fine, could you add a small test to test/unit/menu_item_test.rb please?  Mostly to highlight the difference that this changes the linked URL, but not the hash which is used for authorisation (AIUI the issue).

**Comment by dmitri-d** [comment]
@domcleal: ping?

**Comment by domcleal** [comment]
Merged as 902c71e for Foreman 1.6.0, thanks @witlessbird.

**Pull request closed without merging**
