### PR TITLE
Fixes #25449 - update fog-aws to last version

### PR DESCRIPTION
**Pull request by ares**
Basic functionality seems to work fine, I didn't do full provisioning because of missing AMI, but all seemed to work.

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]

**Comment by chris1984** [comment]
[test foreman]

**Comment by ares** [comment]
would be good to get in just after branching

**Comment by chris1984** [comment]
All tests are green on this one :+1:

**Comment by ares** [comment]
@tbrisker, could we get this in for early testing?

**Review by tbrisker — APPROVED** [review]
Thanks @ares ! this also needs a bump in packaging accordingly to get the newer version, though merging this won't break anything (since the new permitted versions include the old ones)

**Pull request merged**
