### PR TITLE
fixes #6382 - revert name change of 48bit mac address regex

### PR DESCRIPTION
**Pull request by jlsherrill**
as this broke the discovery plugin

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1: without actual testing :)

**Comment by knowncitizen** [comment]
This works for me. ACK.

**Comment by lzap** [comment]
WFM

**Comment by domcleal** [comment]
Merged as 67c3b86 for Foreman 1.6.0, thanks @jlsherrill.

**Pull request closed without merging**
