### PR TITLE
Fixes #32337 - Drop Facter < 2.2 support

### PR DESCRIPTION
**Pull request by ekohl**
Includes https://github.com/theforeman/foreman/pull/8449. See individual commits for details. Still heavy WIP and just here for review.

### CODE REVIEW

**Comment by lzap** [comment]
I will need to see a JSON fixture from facter 2.2 version in this patch, this patch redefines the vacuum we had in this area and it must be covered with tests from the day one.

**Comment by ares** [comment]
Hello @ekohl, given this is a draft for a very long time we'd like to know if you have a plan to move this out of the draft in a foreseeable future.

If we don't get a reply in 2 weeks, we'll close the PR but it can always be reopened.

**Comment by ekohl** [comment]
I've at least rebased it. https://github.com/theforeman/foreman/pull/8449 should still be merged first (since this PR includes it).

**Comment by tbrisker** [comment]
@ekohl #8449 has been merged, please rebase.

**Comment by ekohl** [comment]
Trivial rebase done, no actual code changes.

**Comment by ezr-ondrej** [comment]
This needs rebase now.

**Comment by ekohl** [comment]
> This needs rebase now.

I still disagree that #33470 was a good idea and left a comment that I think it should be reverted: https://github.com/theforeman/foreman/pull/8870#issuecomment-1010873598

**Comment by ezr-ondrej** [comment]
> I still disagree that #33470 was a good idea and left a comment that I think it should be reverted: [#8870 (comment)](https://github.com/theforeman/foreman/pull/8870#issuecomment-1010873598)

Not much to do about it now I guess, but it should not be all that relevant for this PR and the rebase should be trivial, right?

**Comment by lzap** [comment]
I am closing for now, please feel free to reopen. Thank you!

**Pull request closed without merging**
