### PR TITLE
fixes #16083 - pin gettext_i18n_rails for Ruby 2.0.0

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
This will need to be cherry picked to 1.11-stable and 1.12-stable after merge to fix those PR tests.

**Comment by iNecas** [comment]
Thanks, merged as 791fedd

**Comment by iNecas** [comment]
I will do the cherry-pick's as well

**Comment by iNecas** [comment]
Cherry-picked to both branches

**Pull request closed without merging**
