### PR TITLE
Fixes #20949 - Replace deprecated AM::Errors usage

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
taken from Dominic's rails51 branch

**Comment by mmoll** [comment]
[test katello]

**Comment by tbrisker** [comment]
looks like there are quite a few other cases where we use `errors[]=` (or `errors[]<<` which i am not sure is still valid either), could you please take a look?

**Comment by mmoll** [comment]
At least everything that gets hit by any tests should be covered. Rails 5.1 does have these deprecated methods removed and I don't see anything still failing there pointing to anything missed here.

**Comment by tbrisker** [comment]
Ok, I'll merge this for now and hopefully we won't see any failures further on in areas not covered by tests. Thanks @mmoll and @domcleal !

**Pull request merged**
