### PR TITLE
Fixes #36263 - hosts names are hidden in small screens

### PR DESCRIPTION
**Pull request by ekohl**
(cherry picked from commit b82e989fccbf4c672c894872d835a398b1c426c5)

### CODE REVIEW

**Comment by ofedoren** [comment]
Should we cherry-pick https://github.com/theforeman/foreman-packaging/pull/9349 into 3.6? Just for the sake of being able to check if we still can build Foreman with CPs? (I know this CP doesn't affect anything, but still...)

**Comment by ekohl** [comment]
I'm pretty sure we haven't considered packit builds in stable branches and this isn't updated:
https://github.com/theforeman/foreman/blob/3a0c7bdbc57f4e726b4352c0d22131bdb0a0dd38/.packit.yaml#L21-L24

Also the repositories it uses should be updated to not use nightly.

@evgeni can we somehow automate this or should it become part of the branching procedure?

@ofedoren for now we can ignore packit.

**Comment by evgeni** [comment]
> @evgeni can we somehow automate this or should it become part of the branching procedure?

Right now, packit doesn't support templating here, so we can't easily automate it (well, a `sed` in `rel-eng` would do…), but I have a todo item to talk to the packit team about a few "nice to haves" after my PTO, so I can add that there.

**Review by ofedoren — APPROVED** [review]
Thanks, @ekohl and @evgeni.

**Pull request merged**
