### PR TITLE
Api v1 users controller

### PR DESCRIPTION
**Pull request by mbacovsky**
- basic users controller finished
- tests added

### CODE REVIEW

**Comment by logicminds** [comment]
Since I split the routes file into their own api routes files you will need to refactor your routes into config/routes/api/v1.rb

**Comment by ohadlevy** [comment]
hey @mbacovsky would you mind rebasing?
thanks!

**Comment by mbacovsky** [comment]
rebased with current api branch

**Comment by mbacovsky** [comment]
rebased with current api branch

**Comment by ohadlevy** [comment]
merged!

**Pull request closed without merging**
