### PR TITLE
fixes #1976 - fix path to Puppet to /usr/bin

### PR DESCRIPTION
**Pull request by domcleal**
Only puppetd was in /usr/sbin/

### CODE REVIEW

**Comment by skottler** [comment]
This will only work with Puppet 3+ so I think there is some more templating that needs to be added to use the old path for certain versions. Maybe we should add a helper to return the proper path to keep these templates nice and clean?

**Comment by GregSutcliffe** [comment]
These are executed in a shell right? Can we get the template to use PATH?

```
PUPPET=`which puppet`
$PUPPET agent --test
```

**Comment by domcleal** [comment]
@skottler the "puppet agent" style should work all the way back to 2.6.  It was just the puppetd shortcut was removed in 3.0.

@GregSutcliffe or since it's in a shell, just leave off the path :)  Kickstart should be fine, but other things may not.  Jumpstart for instance might not have normal paths, let alone CSW paths initialised.  I know nothing about YaST to comment there.

**Comment by skottler** [comment]
Sorry I was unclear. I mean the path to the puppet binary.

**Comment by domcleal** [comment]
Ah ok.  I thought /usr/bin/puppet had always been there and it was just the puppetd binary that lived in sbin.  My 2.7 system here has:

/usr/bin/filebucket
/usr/bin/pi
/usr/bin/puppet
/usr/bin/puppetdoc
/usr/bin/ralsh
/usr/sbin/puppetca
/usr/sbin/puppetd

**Comment by skottler** [comment]
Weird, I just installed a fresh RHEL6.3 system and `puppet` is in /usr/bin.
Not sure why it's in /usr/sbin on my local machine. Anyhow, sorry to
incorrectly interject.

**Comment by ohadlevy** [comment]
merged - thanks @domcleal

**Pull request closed without merging**
