### PR TITLE
Fixes #23608 - Only calculate lookup values once

### PR DESCRIPTION
**Pull request by credbbl**

### CODE REVIEW

**Comment by ohadlevy** [comment]
ok to test

**Comment by ohadlevy** [comment]
What's the performance difference? Thanks!

**Comment by ekohl** [comment]
I do wonder why the `lookup_values_cache` method has the name cache in it if it doesn't cache. This looks like a sensible change but I would consider renaming the method to `lookup_values` and the local variable `lookup_values_cache`.

**Comment by credbbl** [comment]
Runtime difference is, depending on number of parameters, 4-10s vs. 700ms.

I can rename it.

**Comment by ekohl** [comment]
> Runtime difference is, depending on number of parameters, 4-10s vs. 700ms.

That makes sense. You go from a linear number of queries (depending on the number of keys) to a constant number of queries (1). It is doubly inefficient because the queries that were sent were all the same and more complex depending on number of keys.

**Comment by ohadlevy** [comment]
@ShimShtein @orrabin can you please review? thanks.

**Comment by ShimShtein** [comment]
LGTM, we can remove the WIP, and squash the commits

**Review by dLobatog — APPROVED** [review]
Thanks @credbbl and @ShimShtein  - I'll merge and cherry-pick to 1.17/1.18

**Comment by dLobatog** [comment]
Apologies, it got merged to develop in 2 commits to develop. It was cherrypicked in 1 commit to 1.17-stable and 1.18-stable

**Comment by lzap** [comment]
Good work guys, nice catch! Since 1.18 is not yet out, shall we also patch N-1 (1.16)?

**Comment by formorer** [comment]
Could we please patch this in 1.16 too? For some reasons we will have to stay on 1.16 and the performance issues are really a problem for us. Thanks

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman/pull/5602

**Pull request merged**
