### PR TITLE
Fixes #19506 - reset cache after CR update

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
actually this might desired only if the caching is enabled for the CR

**Comment by timogoebel** [comment]
> actually this might desired only if the caching is enabled for the CR

Yes. One more comment. Should the callback function always return true to not stop other callbacks from running?

**Comment by ares** [comment]
Thanks @timogoebel, could you take another look please?

**Review by timogoebel — APPROVED** [review]
@ares: Thanks. Will merge once tests pass.

**Comment by timogoebel** [comment]
Merged, thanks @ares.

**Pull request merged**
