### PR TITLE
Fixes #23269 - Align ovirt cr automatic network selection on vmware cr

### PR DESCRIPTION
**Pull request by bagasse**
Add `.ovirt_network` css class in selector to add support for ovirt and align vmware and ovirt behavior on this part.

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Review by tbrisker — APPROVED** [review]
Test failures unrelated. Code makes sense to me from a brief look, but would prefer if @orrabin who's most familiar with ovirt also approve it.

**Review by orrabin — COMMENTED** [review]
@bagasse could you show an example of this on ovirt? I was not able to reproduce the subnet changing my network selection.

**Comment by bagasse** [comment]
@orrabin, sure.
foreman_ovirt

**Comment by orrabin** [comment]
[test foreman]

**Review by orrabin — APPROVED** [review]

**Comment by orrabin** [comment]
Reading the code - I did not have vlan id defined in my networks, the code looks fine and this sounds like a valid usecase.

**Comment by orrabin** [comment]
Thanks @bagasse !

**Pull request merged**
