### PR TITLE
fixes #2801 - remove LOWER() in default_scope of models that could cause PG error

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
@isratrade the Rails 3 commit is on this PR too, should just be the #2801 commit.

**Comment by isratrade** [comment]
@domcleal, yes, this is why I wrote above "Do not merge until after PR #801 is merged".  How do you suggest to handle PR's that are dependent on other PR's, or in other words, I prefer that PR #801 is reviewed and merged first (although fundamentally it doesn't matter).  Either way, I need to re-base after #801 is merged.

**Comment by isratrade** [comment]
@domcleal, on 2nd thought, for the purposes of discussion, it's best not to have the other commit in the "Files Changed" tab.

**Comment by domcleal** [comment]
Thanks, we'll do them separately, especially as this was raised by a user against 1.2.

Could you add a test for the case that the user hit, which was searching for "facts." and expecting an autocomplete.  I think the equivalent of the auto-complete test in `test/unit/host_test.rb` for FactValues would work, e.g. `FactValue.complete_for("facts.")`

**Comment by isratrade** [comment]
@domcleal, is Jenkin's hanging?  This PR was pushed yesterday and testing are still "Determining merge status".  I saw on IRC that are you have a battle of patience with Jenkins.  May you win!

**Comment by domcleal** [comment]
@isratrade yep, we can't get a build working of the main "develop" branch so it won't test PRs until it thinks the main branch is OK.  Hopefully today.

**Comment by domcleal** [comment]
Merged as 60e2072a7, thanks @isratrade!

**Pull request closed without merging**
