### PR TITLE
Fixes #18065 - make API v1 deprecation warning more apparent

### PR DESCRIPTION
**Pull request by tstrachota**
Since the text is wrapped in `N_()` and the whole string is translated later in apipie I didn't find any better solution than placing html tags into the string. Ideas are welcome.

### CODE REVIEW

**Comment by dLobatog** [comment]
@domcleal Mind to take a look? I think at first that the tags in the string is a bad practice and the string should be split to translate it in chunks (and not translate the tags). I've messed up a few times translations so I think it's best if you also can check it out. Thanks!

**Comment by domcleal** [comment]
Yes, translating it as two sentences might be best here, or use % placeholders to add the HTML tags instead of putting them in the translation.

**Comment by tstrachota** [comment]
OK, I'll use the placeholders. I'm afraid we cannot split it into chunks here, because gettext wouldn't match the resulting string with existing translation later in apipie (`N_()` vs `_()`).

**Comment by tstrachota** [comment]
Hmm, even placeholders won't solve the issue. So with current state of apipie there's imho no other solution than having the html tags in the string. If you're against please close the PR. I'm not going to change apipie now as the issue is really low prio.

**Comment by dLobatog** [comment]
@tstrachota 

Would:

```ruby
'<b>' +
 N_("Foreman API v1 is deprecated. Please use v2.") +
'</b><br />' + 
N_("If you still need to use v1, you may do so by either passing 'version=1' in the Accept Header or using api/v1/ in the URL.")
```

work?

**Comment by ohadlevy** [comment]
@dLobatog maybe add it to a notification warning? :)

**Comment by dLobatog** [comment]
@ohadlevy Not sure if serious but this is about `apidoc/v1.html`, not worth adding notifications to that page in my opinion!

**Comment by tstrachota** [comment]
@dLobatog IMHO it wouldn't, because:
```ruby
docs = '<b>' +
 N_("Foreman API v1 is deprecated. Please use v2.") +
'</b><br />' + 
N_("If you still need to use v1, you may do so by either passing 'version=1' in the Accept Header or using api/v1/ in the URL.")

#evaluates as 
'<b>Foreman API v1 is deprecated. Please use v2.</b><br />If you still need to use v1, you may do so by either passing 'version=1' in the Accept Header or using api/v1/ in the URL.'

#and then _(docs) won't match because you only have the first and the second part in translations separately.
```
Please see:
https://github.com/grosser/fast_gettext/blob/master/lib/fast_gettext/translation.rb#L52-L55

**Comment by ohadlevy** [comment]
@dLobatog my thought process was to add a warning to notification if we detect someone using a deprecate methods, including API v1. (no need to duplicate it on every api call, but rather one warning with a list of calls/users who used it.)

**Comment by tstrachota** [comment]
@ohadlevy this could be a another improvement. This PR is trying to fix the case when someone comes to the apidoc, looks at v1 and doesn't notice there's v2 that should be used preferably.

**Comment by ares** [comment]
I'm sorry, what exactly is the issue with HTML tags in translated strings? I understand they could be mistakenly broken during translations but we already use them in popovers on multiple places

* https://github.com/theforeman/foreman/blob/develop/app/views/roles/_form.html.erb#L19
* https://github.com/theforeman/foreman/blob/develop/app/views/filters/_form.html.erb#L47
* https://github.com/theforeman/foreman/blob/develop/app/views/nic/_base_form.html.erb#L14

I suppose in this case it does not matter that much. Notifications are definitely a good idea but we can merge this too so users get more visible warning before they even do the API call.

So if breaking strings on translations is the only concern, :+1: from me and if no one NACKs within a week I think we can merge it.

**Comment by ares** [comment]
Thanks @tstrachota, merged as 9d9af9e8b5ffa8498fd36722bb9a91a429735884

**Pull request closed without merging**
