### PR TITLE
Fixes #12659 - Fixed "inherit" behavior

### PR DESCRIPTION
**Pull request by ShimShtein**
Instead of using `.data` (that adds additional info, but doesn't change the `data-*` attributes, now it's using `.attr`.

### CODE REVIEW

**Comment by dLobatog** [comment]
@ShimShtein Thanks, mind to add a integration test for this to ensure it keeps on working? We don't have tests for this area of the code and if someone changes it it'll break again w/o us noticing automatically. Just verifying that clicking the inherit button once loads the inherited value, twice loads the original value should be fine.

file

The behavior is a bit confusing though, if I uncheck inherit, change the value, then click on inherit again, it won't load the inherited value again. Can this be fixed too? I think the problem is that since the value is not blank, it won't change it to the inherited value.

**Comment by ShimShtein** [comment]
> if I uncheck inherit, change the value, then click on inherit again, it won't load the inherited value again

I don't call the ajax again, so I can't calculate what the default was. I think it's better not to connect those  issues, please open a new one, and I'll fix it by saving the old value in the data attributes.

> mind to add a integration test for this to ensure it keeps on working?

Sure, I'll add it, since we don't have any other way of dealing with it. But IMHO the proper test here will be a unit test for the javascript.

**Comment by dLobatog** [comment]
@ShimShtein I would literally go out to celebrate the first unit test in our js :smile: , I was just suggesting the easy-but-not-terrible way out. Fine to solve the other issue in other ticket. Let's just make sure it doesn't fall through the cracks when we close this!

**Comment by ShimShtein** [comment]
Integration test added.

**Comment by ShimShtein** [comment]
Issue for inherit value changes created: http://projects.theforeman.org/issues/12710

**Comment by domcleal** [comment]
@dLobatog do you mind if I review and merge this alongside #2957, since it's best tested together?

**Comment by dLobatog** [comment]
@domcleal np, I'll hold off from merging then

**Comment by domcleal** [comment]
Merged as 6f65fd1, thanks @ShimShtein.

**Pull request closed without merging**
