### PR TITLE
fixes #3853 - allow rabl template override to be specified

### PR DESCRIPTION
**Pull request by thomasmckay**
http://projects.theforeman.org/issues/3853

### CODE REVIEW

**Comment by domcleal** [comment]
This looks reasonable to me, @isratrade or @abenari?

**Comment by isratrade** [comment]
@thomasmckay, it's make sense to me in Ruby but not in Rails.  I'm not sure how the Rails router matches a controller#action that has an argument.  Can you give an example how the #index action is called by an engine an passes an argument to #index?  Any params in the URL are in the params array.

**Comment by thomasmckay** [comment]
https://github.com/Katello/katello/pull/3504/files#diff-c687645002b1eed9efe2be3c5ea46de5R33

katello engine is extending foreman organization model. This allows the org controller in katello to override the foreman rabl to add extended attributes.

**Comment by isratrade** [comment]
@thomasmckay, interesting.  However, I'm a leary little of adding arguments to controller actions.  Can you check if this does the same thing.

``` ruby
def index
    rabl ||= 'api/v2/taxonomies/index'
    render rabl
```

and in Katello when you inherit the controller

``` ruby
def index
   rabl = 'katello/api/v2/organizations/index'
   super
end
```

I also suggest to use a more descriptive variable name like `json_template`, `api_template`, `json_template_path`, `api_template_path`  You never know if we may switch from the rabl gem in the future.

**Comment by thomasmckay** [comment]
@isratrade Updated to avoid adding params to methods.

**Comment by thomasmckay** [comment]
@isratrade ack?

**Comment by isratrade** [comment]
@thomasmckay, looks good.

**Comment by ohadlevy** [comment]
merged as c053792, thanks!

**Pull request closed without merging**
