### PR TITLE
#2368 - Foreman translation and Transifex integration

### PR DESCRIPTION
**Pull request by lzap**
Renaming app.pot to foreman.pot so I will be able to add a project to Transifex.

Also all languages are now autodetected so we do not need to maintain the list manually.

Foreman in production mode now does use MO files instead direct (slow) reading of PO files. This need a change in our installation instructions. Right after database migration (and before starting foreman up) we need to add one extra step:

```
rake gettext:pack
```

Also I am adding a Makefile that offers the same, but with GNU gettext package. Also it offers "make check" to do a deep checkup of all translations for general issues. There is also a README with a link to our wiki page where I want to put more info about it.

And I am adding German translation which replaces 

https://github.com/theforeman/foreman/pull/494

because it was in the non-UTF8 encoding and gettext was not able to parse it.

### CODE REVIEW

**Comment by lzap** [comment]
More info here: http://projects.theforeman.org/projects/foreman/wiki/Translating

**Comment by lzap** [comment]
Ok rebased on Rails 3.2 now. I have decided to pull in all BK's translations and to carry on with string extraction in this PR. Please do not merge yet. Feel free to comment tho.

**Comment by skottler** [comment]
Can you squash the commits into a single one? Also is there a ticket on projects.theforeman.org for this? If not please create one and add the number to the commit message to make writing release notes more sane.

**Comment by lzap** [comment]
Will do squash after final review, there will be commits from three authors in this PR so I just want to keep the history at this point. Will do!

**Comment by skottler** [comment]
WFM - thanks @lzap!

**Comment by ohadlevy** [comment]
[test]

**Comment by lzap** [comment]
Squashed everything I could and ready for review. @ohadlevy please ping me once this is ready to be merged and I will rebase to minimize the window. [test]

**Comment by lzap** [comment]
Closing this one and filing new rebased PR: https://github.com/theforeman/foreman/pull/527

**Pull request closed without merging**
