### PR TITLE
Refs #3809 - Use parentheses in method definitions

### PR DESCRIPTION
**Pull request by dLobatog**
This was done in a minute with --auto-correct, it just adds parentheses to method definitions with parameters to comply with the standard, `def method(parameter, parameter)`

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1: pending tests

**Comment by ohadlevy** [comment]
merged as 5f029ed thanks @eLobato !

**Comment by lzap** [comment]
> ```
> A .sass-cache/2a0a5d01108a2d6e7f880f9c6b05f63356bccec0/application.css.scssc (0)
> A .sass-cache/2a0a5d01108a2d6e7f880f9c6b05f63356bccec0/bootstrap_and_overrides.css.scssc (0)
> A .sass-cache/2a0a5d01108a2d6e7f880f9c6b05f63356bccec0/staypuft.css.scssc (0)
> ```

Were these added intentionally?

## 

Later,
 Lukas #lzap Zapletal

**Comment by dLobatog** [comment]
Where are these? I updated the PR prior to merging to remove that.

**Pull request closed without merging**
