### PR TITLE
Fixes #34791 - remove pf3 bookmarks

### PR DESCRIPTION
**Pull request by MariaAga**
We stopped using this code here: https://github.com/theforeman/foreman/pull/8743

### CODE REVIEW

**Review by adamruzicka — COMMENTED** [review]
Wow, nice balance `+20 −1,437`.

I clicked around and haven't seen any issues so +1 from me.

On a side note, are we sure it is not used from some plugin?

**Comment by MariaAga** [comment]
I didn't find any plugins that use this (in theforeman/katello orgs). The bookmarks are/were delivered through the search bar so I don't think any plugin used the bookmarks component alone.

**Review by adamruzicka — APPROVED** [review]
Alright, let's get this in

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
