### PR TITLE
fixes #7818 - explicitly render role permissions to fix oj 2.10.3 error

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dLobatog** [comment]
Any idea if the Katello tests have to do with this? They're not even the same API version...

**Comment by domcleal** [comment]
Probably a similar issue, but not ours.

**Comment by dLobatog** [comment]
@domcleal Ok, I think I have it. Let me try check if I can quickly fix it and I'll merge.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/1155fbf13a6c6cbcb9f4cdfc2f0907eaddaf2cc5, thanks much @domcleal!

**Pull request closed without merging**
