### PR TITLE
needs review: add turbolinks support.

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
checking if Jenkin's test passes.  My tests passed locally. Same as PR #1315 except last commit removed.

**Comment by isratrade** [comment]
@domcleal, @ohadlevy, see https://github.com/rails/turbolinks/issues/382 where @dhh answered that gem 'turbolinks' is not supported in Ruby 1.8.7

**Comment by domcleal** [comment]
@isratrade file a feature request in redmine for turbolinks then, mark it as "blocked by" #4656 and we'll have to revisit another day :(

**Comment by domcleal** [comment]
Else try and make it optional, but that might lead to more subtle bugs.

**Comment by isratrade** [comment]
@ohadlevy, I assume that AS::Concern resolves the dependency issue of calling `super` on an included method that's been aliased with alias_method_chain. This seems to be what is happening as `url_for_without_xhr_referer` in turbolinks calls to `url_for` in rails which calls `super`

What was the maintainer's point that was application-specific to us?  I don't see it.

I'm also not sure who the commit rails/turbolinks@8eaf3f8 would fix it.  It just seems to be a re-factoring.

**Comment by ohadlevy** [comment]
@isratrade see https://github.com/rails/turbolinks/pull/358

**Comment by dLobatog** [comment]
Aside from this needing a rebase, it needs a corresponding PR in [foreman-packaging](https://github.com/theforeman/foreman-packaging) to build rpms/debs for turbolinks.

**Comment by isratrade** [comment]
closing turoblinks PR for now. may re-open at a later date.

**Comment by domcleal** [comment]
Might be worth revisiting this now, as 1.8's dropped.

**Pull request closed without merging**
