### PR TITLE
refs #22857 - remove separate kickstart for RHEL

### PR DESCRIPTION
**Pull request by stbenjam**
Requires: https://github.com/theforeman/community-templates/pull/462

### CODE REVIEW

**Review by lzap — APPROVED** [review]
WFM but want to hear more opinions on that. Thanks for working on this, this was confusing. Community-templates PR must be merged first - then we can remove here and the rest will be imported before the release.

**Review by timogoebel — APPROVED** [review]
Looks good to me.

**Comment by timogoebel** [comment]
@mmoll: Since you merged the community-templates PR: ACK from you?

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
sorry, yes :+1:

**Comment by mmoll** [comment]
merged, thanks @stbenjam!

**Pull request merged**
