### PR TITLE
Foreman::Provision::SSH requires fog even on non-fog installations

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
another option would be to require the file only in the right context?

maybe not all files (e.g. in orchestration) should be auto loaded in the first place?

**Comment by isratrade** [comment]
@ohadlevy, is there an easy method is check if Fog exists

**Comment by ohadlevy** [comment]
https://github.com/theforeman/foreman/blob/develop/app/models/concerns/fog_extensions.rb#L45

**Comment by isratrade** [comment]
@ohadlevy, @domcleal, do you prefer to move ssh.rb back to /app/services and wrap require 'fog' in a begin/rescue block?

**Comment by skottler** [comment]
@isratrade I like the begin/rescue block because it makes the solution more durable long term instead of relying on directory structure (although, admittedly it's unlikely to change soon).

**Comment by isratrade** [comment]
@ohadlevy, @domcleal, any comment on which option to go with:
1) move files back to /lib and it works
2) keep files in app/services and wrap require 'fog' in a begin/rescue block

**Comment by domcleal** [comment]
I'd prefer (2)

**Comment by isratrade** [comment]
I kept ssh.rb in app/services/foreman/provision folder and wrapped require 'fog' in a begin/rescue block
I moved provision.rb back to lib/foreman since it's not a service object and felt it it better in /lib

**Comment by isratrade** [comment]
Btw, the typos that @ares fixed in PR #811 did not fix the issue.  I thought that was maybe the issue.

**Comment by skottler** [comment]
:+1: looks good now. Just waiting for tests to run.

**Comment by domcleal** [comment]
I don't really like the splitting up of provision.rb and ssh.rb, seems like it'll be confusing for anybody trying to find one from the other.  I guess it's not really a service because it doesn't operate on models, is that right?

**Comment by isratrade** [comment]
@domcleal, I see /app/services as a place for service objects which have an initialize method.  I think that all files in app/services can be initiated expect for access_permissions.rb

**Comment by domcleal** [comment]
@isratrade ah, that makes sense and matches the other modules we declare in lib/foreman. :+1: then

**Comment by domcleal** [comment]
Merged as 1d9828b0, thanks @isratrade!

**Pull request closed without merging**
