### PR TITLE
Fixes #4031 - change TFTP record on build flag change

### PR DESCRIPTION
**Pull request by ares**
More info here http://projects.theforeman.org/issues/4031

### CODE REVIEW

**Comment by ares** [comment]
@GregSutcliffe could you please review? I think you worked on this, I'm not sure whether I'm missing something but without this, provisioning does not work for me.

**Comment by GregSutcliffe** [comment]
I'm not sure what to say - your fix looks right to me, but equally, that code hasn't changed since I touched it last in Oct 2012, so I would have expected more reports of broken provisioning by now.

**Comment by ares** [comment]
Not sure whether this info could help but I didn't have "PXE Localboot Default" template in foreman which I know have some special effect.

Maybe if someone could test this PR manually before merging could help? I just don't see a way how this could work without this patch.

**Comment by domcleal** [comment]
The name was changed w/seeds to "PXELinux default local boot", but it should have been seeded.

**Comment by domcleal** [comment]
Utterly strange, but you're correct.  @GregSutcliffe has tested it.

Merged as 7e80f0a for Foreman 1.4.  Thanks @ares!

**Comment by GregSutcliffe** [comment]
Yep, I can confirm this is needed. I have no idea what changed somewhere else in the codebase, but clearly this was "working by accident" until recently.

Good catch @ares - just in time!

**Pull request closed without merging**
