### PR TITLE
Fixes #27346 - show audit records for host create

### PR DESCRIPTION
**Pull request by kgaikwad**
adding @ares, @tbrisker  in loop.

Instead of adding hard-coded list into main objects, I have considered parent classes which are not abstract and having DB table.

### CODE REVIEW

**Comment by tbrisker** [comment]
Thanks @kgaikwad! I think this may be an outcome of having multiple different ways we do auditing currently around STI. perhaps we should try to think how we can make it simpler in a way that works for everything? Some differences off the top of my head:
1. `Host::*` audits are manually converted to `Host::Base` in `AuditExtensions` before saving - i.e. audited on subclass but saved as parent class.
2. `Taxonomy`, `LookupKey`, `Nic::*` are saved as `Location`/`Organization`, `PuppetClassLK`/`VariableLK` and Nic type respectively, i.e. audited on parent class but saved with subclass. (also from `AuditExtensions`)
3. `Parameter`, `Template` are audited on the subclass
4. `OperatingSystem`, `Setting` and many others are audited on the parent class

I wonder if simplifying these options (maybe just using the last two - so the audit definition is on the class we care about) would be possible and make some of the rest of the work around audits easier and less error prone?

**Comment by kgaikwad** [comment]
Thank you @tbrisker for bringing this. 
I am trying to understand reason behind this implementation (1) & (2). Please correct me If I am getting it wrongly but these changes were added to avoid complications while showing audits as well as to minimize dataset. But I will check more on these to find a better solution.

**Comment by ares** [comment]
@tbrisker is this acceptable at least as an interim solution? While I'd like to investigate if unification of STI classes auditing make sense, I'd also like to get this fixed.

Quick comment on your findings, points 3 and 4 makes sense to me from user perspective. Point 1 seems reasonable. Point 2 - I can understand taxnomy and lookup keys, not sure about nics though.

**Comment by tbrisker** [comment]
@ares my comment was more of an observation and thinking out loud than a requirement. If @kgaikwad found a simple way to fix part of it in this PR it would be good, but if not we can stay with this solution, or do an explicit workaround for the hosts so we know to remove it once we fix the sti handling.
Can we add a test though to make sure this doesn't break again?

**Comment by ares** [comment]
ok, thanks @tbrisker, @kgaikwad would you mind adding a test for host object? then I think we're ready to merge

**Review by ares — CHANGES_REQUESTED** [review]
test

**Comment by kgaikwad** [comment]
@ares, @tbrisker,
Sorry for the delay. 
I have added test which will check 'Host::Base' included in audit's main_objects.

@tbrisker, My apologies. I will need some more time to investigate changes around an unification of STI classes.

**Review by ares — APPROVED** [review]
Thank you both @kgaikwad and @tbrisker, I'm merging as it fixes the issue and is a good solution until we simplify the STI in audits.

**Pull request merged**
