### PR TITLE
Fixes #31482 - don't require ansible to render the inventory

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ezr-ondrej @ares this is the followup we discussed in https://github.com/theforeman/foreman/pull/8113 -- I remember Ondrej mentioning possible improvements to the rendering API, I'm all ears :)

**Comment by ezr-ondrej** [comment]
Why don't we include ansible variable overrides here? is it correct?
I think that those should be included and in that case, we would need ansible plugin, or we could have ansible plugin check just for those variables?

**Comment by evgeni** [comment]
I have no idea what ansible overrides are, but we can include them based on the plugin presence, like we do for Katello

**Comment by ezr-ondrej** [comment]
> I have no idea what ansible overrides are, but we can include them based on the plugin presence, like we do for Katello

Ansible variables overrided through the Foreman UI :thinking:

**Comment by evgeni** [comment]
Ah! Aren't those more related to Ansible Roles that Foreman executes, and this inventory is not used in that case anyways?

**Comment by ezr-ondrej** [comment]
well  yeah, I guess :) global atributes should be defined as Global parameters :+1:

**Review by ezr-ondrej — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
Thanks @evgeni ! :)

**Pull request merged**
