### PR TITLE
fixes #4612 Typo in oVirt name

### PR DESCRIPTION
**Pull request by abenari**

### CODE REVIEW

**Comment by abenari** [comment]
this replaces #1295, thanks @abonas for your work on this patch.

**Comment by domcleal** [comment]
Looks good.  Could you also have the "Available Providers" tab in About use this too?

**Comment by abenari** [comment]
@domcleal now includes the about page

**Comment by domcleal** [comment]
Merged as ddce3dc for Foreman 1.5.1, thanks @abenari!

**Pull request closed without merging**
