### PR TITLE
Fixes #13076 - Reduced host#show tab headings font size

### PR DESCRIPTION
**Pull request by alongoldboim**

### CODE REVIEW

**Comment by dLobatog** [comment]
Please include screenshots to showcase the issue. Also, that CSS rule is so general it's changing more than just the host form.

**Comment by alongoldboim** [comment]
Fixed font to be 12px as well.
selection_004

**Comment by dLobatog** [comment]
Merged as c4dd28f82c6e5d4ff9b6680c30a0eb2201508fd6, thanks @alongoldboim!

**Comment by tbrisker** [comment]
This broke all the forms. Created #3078 to revert this.

**Pull request closed without merging**
