### PR TITLE
Fixes #10976 - Suggest new ip button does not work

### PR DESCRIPTION
**Pull request by tstrachota**
The jQuery selector for finding subnet id didn't find the correct field.

### CODE REVIEW

**Comment by domcleal** [comment]
Merged as 36746b8, thanks @tstrachota.

**Comment by lzap** [comment]
I have raised the following concern in the ticket which was not addressed. Looks like there are users on the list hitting this:

> Nitpick: The "Error generating IP: Not Found" error is being inserted in the field itself on error (e.g. proxy is not reachable). This is not only nice from the UX standpoint, but when you try to create new host with proxy unavaiable and you don't even open the interface form and submit, the IP is kept set to this string, which causes validation error. We should totally leave IP field empty on errors showing this message in a bubble or something.

Do we want to fix this? @ShimShtein

**Comment by tstrachota** [comment]
@lzap @ShimShtein I totally missed that in the issue, thanks for bringing it up. I think it's a serious UX issue that should be fixed.

**Comment by lzap** [comment]
If folks agree, I can create a new ticket for this one. I just feel it's not good to fill this in the field itself.

**Comment by domcleal** [comment]
Yes, please just copy it to a separate ticket, blank the release field.

**Comment by lzap** [comment]
Created the ticket, sorry for the delay :-)

**Pull request closed without merging**
