### PR TITLE
Refs #23095 - Robottelo tests attr - subnets and parameters

### PR DESCRIPTION
**Pull request by ldjebran**
Related robottelo issues:
SatelliteQE/robottelo#6125
https://github.com/SatelliteQE/robottelo/issues/5874

Update to PR: https://github.com/theforeman/foreman/pull/5389

Port robottelo tier1 tests for organization part of robottelo minitest port project: https://github.com/SatelliteQE/robottelo/projects/1

### CODE REVIEW

**Comment by ldjebran** [comment]
rebase

**Comment by tbrisker** [comment]
Thanks @ldjebran ! following https://community.theforeman.org/t/on-uuids-in-tests/10347/19, can you please update this PR without the ids?

**Comment by ldjebran** [comment]
@tbrisker rebased and removed the ids

**Review by tbrisker — APPROVED** [review]
Thanks @ldjebran !

**Pull request merged**
