### PR TITLE
Fixes #8337 - reworded oVirt template help text

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by dLobatog** [comment]
Merged as 05f5945e0984b9d4749640abbb079416260bcbc9 , thanks @lzap !

**Comment by ohadlevy** [comment]
IMHO this should be changed to oVirt, as in all other places we talk about
ovirt, not rhev?

**Comment by lzap** [comment]
You mean to delete the " / RHEV" part from the string? Should I open another PR?

**Comment by dLobatog** [comment]
I thought about this too, and merged it because for a long time I didn't know oVirt = RHEV, leaving RHEV out would be ok too I guess as we do not have a provider "oVirt/RHEV"

**Comment by lzap** [comment]
> I thought about this too, and merged it because for a long time I didn't know oVirt = RHEV, leaving RHEV out would be ok too I guess as we do not have a provider "oVirt/RHEV" 

Frankly, I think we should go the other way around - renaming as much as
possible to oVirt/RHEV. The plugin would stay ovirt of course while it's
description and most of helper text would mention RHEV.

While we can brand this and it is expected that RHEL/Sat 6 customers
will probably use RHEV, they can use oVirt too. It will work.

## 

Later,
 Lukas #lzap Zapletal

**Pull request closed without merging**
