### PR TITLE
Fixes #14375 - Add search to bookmarks controller

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
Codeclimate is right. However, this belongs to a separate pull request, imho

**Comment by dLobatog** [comment]
@shlomizadok Thanks, please add a permission for this route - then it'll pass tests and we can merge it.

**Comment by shlomizadok** [comment]
@dLobatog - Added. Thanks for the heads up.

**Comment by shlomizadok** [comment]
@dLobatog, all tests besides code climate are :green_apple: 
For code climate, I have created issue [#16689](http://projects.theforeman.org/issues/16689)

**Comment by dLobatog** [comment]
Thanks @shlomizadok !

**Pull request merged**
