### PR TITLE
Fixes #35819 - Details tab cards have horizontal scroll

### PR DESCRIPTION
**Pull request by MariaAga**
small screen:
Screenshot from 2022-12-02 18-32-31
"large" (zoomed out) screen with different amount of (some fake) cards
Screenshot from 2022-12-02 17-11-51
Screenshot from 2022-12-02 17-11-42
Screenshot from 2022-12-02 17-11-29

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
Looks better than before. But depending on screen width, the space between the columns seems very wide:

details-tab-no-flex

details-tab-3-col

also @MariSvirik I think you mentioned you want to move the 'Expand all cards' button; where should it go?

**Comment by MariaAga** [comment]
Thanks, What do you think is the alternative to the space? the empty space is there only when there is no space for a card

**Comment by jeremylenz** [comment]
I meant the margins (spacing) between the columns get too wide. I think ideally the columns should have the same spacing regardless of how many columns there are. (you know, like it was in the flex layout ;)

**Comment by MariaAga** [comment]
Do you mean that the all the extra empty space should be on the right side instead spread between the columns?

**Comment by ekohl** [comment]
I noticed this as well and I'd like to see this in 3.5.  I'm debating whether to hold the 3.5.0 GA release or not, but know I'm keen on seeing this resolved.

**Comment by jeremylenz** [comment]
> Do you mean that the all the extra empty space should be on the right side instead spread between the columns?

Yes, exactly.

**Comment by MariSvirik** [comment]
@jeremylenz based on the super old mock from Marvel it was located on the left-hand side - that keeps the position the same next to the cards no matter how wide the screen is.
Screenshot 2022-12-05 at 16 33 07

https://marvelapp.com/prototype/995cc27/screen/86551793

**Comment by MariaAga** [comment]
Moving the space to right side, instead of having space between cards is a bit more complicated than expected, as a different solution we can let the cards expand and take that space in their width like this:
Screenshot from 2022-12-07 14-25-06
Screenshot from 2022-12-07 14-25-17

**Review by jeremylenz — APPROVED** [review]
Great work @MariaAga 

ACK :+1:

**Pull request merged**
