### PR TITLE
Fixes #28545 - Remove smart variable pages

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test upgrade] for some reason it failed to build ruby-libvirt gem

**Comment by ekohl** [comment]
Any reason this is separate from https://github.com/theforeman/foreman/pull/7273?

**Comment by tbrisker** [comment]
just an attempt to break up the removal into smaller chunks

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
