### PR TITLE
Add "Reviewed by Hound" badge

### PR DESCRIPTION
**Pull request by salbertson**
screenshot 2018-10-18 09 49 13

### CODE REVIEW

**Comment by mmoll** [comment]
:-1: from me for adding the hound badge, as we recently moved away from it for JS (because we can't use eslint plugins in it) and personally I'd also like to remove it for the Ruby code, mainly as https://github.com/houndci/hound/issues/1250 is still unsolved after almost two years and also we can't use Rubocop plugins in hound.

**Comment by lzap** [comment]
I personally would not mind having that in our README until we decide to remove it. It did decent job already, it is not perfect but I still find it useful. But that's not reason to refuse such patch. I also see there is something happening in the relevant PR which is a good sign already.

@salbertson please remove the image and amend. This is far from being decided yet, we are a big team.

**Comment by salbertson** [comment]
@mmoll we are making progress on configuring linter versions, it's really close. https://github.com/houndci/hound/issues/1250#issuecomment-430701302

**Comment by salbertson** [comment]
> it is not perfect but I still find it useful

@lzap I'd love to hear how we can make it better. Are there any other [issues](https://github.com/houndci/hound/issues) you've been waiting on?

**Comment by lzap** [comment]
@salbertson nah, I am good, thanks. I created thread on our site to bring some attention to the discussion: https://community.theforeman.org/t/reviewed-by-hound/11512

**Comment by timogoebel** [comment]
@salbertson: Please see this threads for issues we have with hound:

https://community.theforeman.org/t/replacing-hound-ci-for-the-js-stack/11116
https://community.theforeman.org/t/houndci-annoying/6475/8

The two most painful things in my opinion are:
- The linter versions are not configurable.
- It's very easy for "unlinted" code to still sneak in. I'm not sure, why.
- I dislike the inline comments in the Code. They feel like spam to me.

**Comment by salbertson** [comment]
@timogoebel awesome, thank you for the feedback! We are actively working on making linter versions configurable and the option to move comments out of the code changes, using GitHub's Checks interface.

https://github.com/houndci/hound/issues/1250#issuecomment-430701302

https://github.com/houndci/hound/pull/1597

> It's very easy for "unlinted" code to still sneak in. I'm not sure, why.

Do you have any more detail or a good example for us to look into?

**Comment by ohadlevy** [comment]
I personally think that as long as we use hound (and we still do) we should have the badge in our readme, if / when we decide to move away from it, we should remove it too, :+1: to merge this PR.

**Comment by ekohl** [comment]
> Do you have any more detail or a good example for us to look into?

If you only check diffs then you assume a strictly linear history. Let's say you submit a PR X that has a certain coding style, submit & merge PR Y that changes the coding style and then merge PR X. Now you have a commit with a different coding style that could still have passed checks.

**Comment by lzap** [comment]
@ohadlevy you want to comment on the discourse thread then?

I think it's fair to give credit, folks already expressed they commitment to make sure the badge stays there for as long as possible fixing some bugs or doing enhancements which is great. I did not read those tho, don't have any details about it.

**Review by mmoll — APPROVED** [review]
I'm OK with this :+1:

**Review by ohadlevy — APPROVED** [review]

**Review by lzap — APPROVED** [review]
I am glad, hope for the best changes in the future so we can keep using Hound. Thanks all!

**Pull request merged**
