### PR TITLE
Fixes #18949 - info message about current user

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
Follow-up from https://github.com/theforeman/foreman/pull/4385

**Comment by dLobatog** [comment]
@iNecas Looks good to me - integration tests are failing though, I'll look into it and check if this PR is causing it or there is another reason.

**Comment by dLobatog** [comment]
Seems that this is happening because your branch doesn't have https://github.com/theforeman/foreman/pull/4386/files - merging

**Comment by dLobatog** [comment]
Thanks @iNecas !

**Pull request merged**
