### PR TITLE
Fixes #30748 - Adds Netplan support for Ubuntu 18.04+

### PR DESCRIPTION
**Pull request by stefanlasiewski**
Adds a conditional to use `/etc/netplan` for Ubuntu 18.04+ systems, but use `/etc/network/interfaces` for older Ubuntus.

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Review by lzap — CHANGES_REQUESTED** [review]
Hello, it does not work becuase vlanid method appears to return turthy value (probably empty string):

```diff
     KERNEL 
-    APPEND initrd= interface=auto url=http://foreman.some.host.fqdn/unattended/provision ramdisk_size=10800 root=/dev/rd/0 rw auto hostname=snapshothost console-setup/ask_detect=false console-setup/layout=USA console-setup/variant=USA keyboard-configuration/layoutcode=us localechooser/translation/warn-light=true localechooser/translation/warn-severe=true locale=en_US
+    APPEND initrd= interface=auto url=http://foreman.some.host.fqdn/unattended/provision ramdisk_size=10800 root=/dev/rd/0 rw auto hostname=snapshothost console-setup/ask_detect=false console-setup/layout=USA console-setup/variant=USA keyboard-configuration/layoutcode=us localechooser/translation/warn-light=true localechooser/translation/warn-severe=true netcfg/use_vlan=true netcfg/vlan_id= locale=en_US
     IPAPPEND 2
```

You need to test for presence, ideally with `if @host.provision_interface.vlanid.present?`

**Comment by lzap** [comment]
Please amend this change and tests will pass:

```diff
diff --git a/app/views/unattended/provisioning_templates/PXELinux/preseed_default_pxelinux.erb b/app/views/unattended/provisioning_templates/PXELinux/preseed_default_pxelinux.erb
index 55129ff05..02100a6b6 100644
--- a/app/views/unattended/provisioning_templates/PXELinux/preseed_default_pxelinux.erb
+++ b/app/views/unattended/provisioning_templates/PXELinux/preseed_default_pxelinux.erb
@@ -28,7 +28,7 @@ oses:
   else
     options << 'console-setup/ask_detect=false console-setup/layout=USA console-setup/variant=USA keyboard-configuration/layoutcode=us localechooser/translation/warn-light=true localechooser/translation/warn-severe=true'
   end
-  if @host.provision_interface.vlanid
+  if @host.provision_interface.vlanid.present?
     options << "netcfg/use_vlan=true netcfg/vlan_id=#{@host.provision_interface.vlanid}"
   end
   options << "locale=#{host_param('lang') || 'en_US'}"
```

**Comment by ekohl** [comment]
This looks like a duplicate of https://github.com/theforeman/foreman/pull/7940. Are you sure you pushed the right branch?

**Comment by lzap** [comment]
Oh good point, let's close this one then and continue there.

**Comment by lzap** [comment]
Oh I get it, @stefanlasiewski pushed into incorrect PR. Damn. Reopening.

**Comment by ekohl** [comment]
@lzap do you plan to revisit this? I still think this is a valuable change.

**Comment by stefanlasiewski** [comment]
@lzap I tried to clean up my previous merge request, and have repushed.

**Comment by stefanlasiewski** [comment]
I messed up too much here and am going to resubmit my PR.

**Pull request closed without merging**
