### PR TITLE
Fixes #36551 - Update PermissionDenied component

### PR DESCRIPTION
**Pull request by MariaAga**
Removed props were never used, updating this component to not use pf3, and be similar to what we have in foreman ansible https://github.com/theforeman/foreman_ansible/blob/master/webpack/components/AnsibleRolesSwitcher/components/AnsiblePermissionDenied.js

### CODE REVIEW

**Comment by ofedoren** [comment]
Thanks, @MariaAga, just few notes:

1. Why do we remove `back` button? Even though it's not quite useful, since it seems it always leads to `/`.
2. This change will add 3rd way of showing `permissions needed` :/ Here are some I found:
ScreenShot-1688059694379
ScreenShot-1688059704069
ScreenShot-1688059715828

**Comment by MariaAga** [comment]
1. yeah I wasnt sure if we really need it there since it always just goes to the main page, maybe I should just hard code it like we do in the 403 page?
2. if this is merged then I can replace the ansible permission component

**Comment by ofedoren** [comment]
ok to test

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga, let's get this in. Seems like pretty safe patch.

Katello failures are related, but there is a fix for it already.

**Pull request merged**
