### PR TITLE
Fixes #11692: update ace-rails-ap to 4.x.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/11692

### CODE REVIEW

**Comment by domcleal** [comment]
Given v4 precompiles the worker files, should they be removed from our assets?

**Comment by domcleal** [comment]
And talking of precompilation, there appears to be duplication between the app.js and the precompiled files which isn't necessary - see my ticket comments.

**Comment by waldenraines** [comment]
@domcleal sorry, somehow I missed that comment, updated.

**Comment by waldenraines** [comment]
@domcleal I believe I have addressed all comments.

**Comment by domcleal** [comment]
Merged as 4901dd3, thanks @waldenraines.

**Pull request closed without merging**
