### PR TITLE
Fixes #11388 - Popovers display with correct size and dismiss on next click

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
Can you provide a list of places where this has changed? For the moment I could see changes when importing classes, also on the Subnet form, but the parameter info boxes look the same.

**Comment by tbrisker** [comment]
@eLobato info boxes that were well sized before will look the same, however the behaviour has changed so that any click will close the box (instead of only clicking on the "i" again). This change effects all info boxes in the app - everywhere the `popover` helper is used. This is used AFAIK in host/hostgroup parameters, in interfaces, in subnets, and in lookup keys (class parameters/smart variables). 
I have also updated the PR now making the default `:html => true`  instead of having to manually declare it every time a popover is activated.

**Comment by tbrisker** [comment]
@eLobato update: I found the code that was causing the limited height and removed it.

**Comment by dLobatog** [comment]
Merged as 33e9c5fd7ee21d54945b29e535aed70635aaf3ec, thanks @tbrisker!

**Pull request closed without merging**
