### PR TITLE
Fixes #24056 - Moved facets to Host::Base

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
This is an alternative solution to https://github.com/theforeman/foreman/pull/5739. 
It moves the definition of facet relations to `Host::Base`.
Use case: Fact values are connected to `Host::Base`. When user requests to see fact values, system tries to authorize the user for the given host (that is an instance of `Host::Base`). When the user has custom filter on facet's value set, authorizer will try to search for relevant relation on the `Host::Base` instance and fail.

**Comment by tbrisker** [comment]
I must say I like this option more. While it looks like a bigger change the the alternative, it is mostly just extracting facet logic from the host class. This makes it easier to understand what is the facet code and even just reading it now i thought of some ways we can improve it.

**Comment by ShimShtein** [comment]
>  it is mostly just extracting facet logic from the host class.

@tbrisker, as a side note, this logic never was in host class, it was always an `ActiveSupport::Concern`. Before the change it was attached to `Host::Managed`, but this change splits it into two concerns - one that defines facet's relations and another one that adds `Host::Managed` related cloning info.

P.S. In a long range, I can see cloning concern moving to `Host::Base` too.

**Comment by tbrisker** [comment]
oops, please ignore my comment before coffee.

**Comment by ShimShtein** [comment]
ping @tbrisker?

**Comment by mmoll** [comment]
what's the status here? :)

**Comment by ShimShtein** [comment]
Rebased, still waiting for review.

**Review by mmoll — DISMISSED** [review]
looks good to me :+1:

**Comment by parthaa** [comment]
@ShimShtein I still get the error with your changes

```
irb(main):003:0> User.current = User.find_by_login("apiuser")
......
irb(main):004:0> Authorizer.new(User.current).find_collection(Host, {:permission => :view_hosts, :joined_on => FactValue})
ActiveRecord::ConfigurationError: Can't join 'Host::Base' to association named 'content_facet'; perhaps you misspelled it?
```

**Comment by ShimShtein** [comment]
@parthaa I think I found what could be the problem. Can you try this new version?

**Comment by mmoll** [comment]
[test foreman]

**Comment by parthaa** [comment]
> I think I found what could be the problem. Can you try this new version?

Works well +1

**Comment by mmoll** [comment]
@ShimShtein now tests fail :boom:

**Comment by ShimShtein** [comment]
[test foreman]

**Comment by mmoll** [comment]
test failures IMHO unrelated now :green_heart:

**Review by mmoll — DISMISSED** [review]

**Comment by ShimShtein** [comment]
@tbrisker, mind take a look?

**Comment by mmoll** [comment]
@ShimShtein please rebase to get Rails 5.2 into the test run

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
Merging now as I'm fine with this and everything is still deep green after a rebase :green_heart:

**Comment by mmoll** [comment]
merged, thanks @ShimShtein!

**Pull request merged**
