### PR TITLE
Fixes #16970 - added list of Rails config files

### PR DESCRIPTION
**Pull request by lzap**
Side effect is providing list of foreman hooks installed, which was the main
motivation for the patch.

### CODE REVIEW

**Comment by domcleal** [comment]
Under what circumstances is a list of packaged config files important? If you want to include a list of foreman_hooks scripts, please add it to the plugin instead, not Foreman.

**Comment by lzap** [comment]
Do you prefer package only change?

**Comment by domcleal** [comment]
I don't think I understand the question?

**Comment by lzap** [comment]
If you prefer the debug script in the main foreman_hooks git repo, or just in RPM/DEB repos.

**Comment by domcleal** [comment]
In the plugin repo.

**Comment by lzap** [comment]
Sure https://github.com/theforeman/foreman_hooks/pull/40

**Pull request closed without merging**
