### PR TITLE
Strong Params: Adding strong_parameters gem

### PR DESCRIPTION
**Pull request by daviddavis**
We'd like to use strong_params in Katello. We figured it might be beneficial to have it in foreman as well so you can incrementally start using it?

### CODE REVIEW

**Comment by daviddavis** [comment]
[test]

**Comment by lzap** [comment]
We'd need links to our koji build system with RPMs, then pull request into foreman-packaging for comps files.

But isn't better approach to raise a ticket for us so we can evaluate and put it on sprint? This should be part of larger patch that would introduce this into the codebase. Just like that it does not make much sense to me.

**Comment by thomasmckay** [comment]
@lzap I suggested to @daviddavis that he put this p-r against foreman in addition / to augment the katello p-r https://github.com/Katello/katello/pull/3523

The "raise a ticket for us" comment is odd, since effectively all of katello and foreman dev teams are unified at this point. The lines will continue to blur. You'll note, I hope, that David did post to foreman-dev on the topic to strong support. While the katello engine may implement it sooner, since it has immediate need to replace what is there now, the goal would be that a core aspect like this would land in foreman as well. That was my intention in encouraging David to submit this.

Hope that helps clarify things.

**Comment by skottler** [comment]
@thomasmckay @daviddavis we usually just create a ticket for everything because it makes writing release notes substantially easier. Additionally, we've agreed as of the sprint before this one that we'd put everything that gets worked on into the sprint backlog, so that's the source of the "make the ticket and we'll put it into the sprint."

Before this PR gets merged there will need to be builds for the strong_params package in Koji otherwise the nightly packages will not work properly due to the missing dependencies. Let me know if you need a hand getting started with koji or the thirdparty repo.

**Comment by domcleal** [comment]
As lzap suggested, this PR should include full conversion of Foreman to use the gem - we shouldn't carry an additional unused dependency.

**Comment by domcleal** [comment]
Closing for the reason stated in my reply above, we should be making use of the gem and not just adding it.  Ticket [#3917](http://projects.theforeman.org/issues/3917) remains open so it can be prioritised.

**Pull request closed without merging**
