### PR TITLE
Fixes #32372 - Correct path for logs in kickstart

### PR DESCRIPTION
**Pull request by martin-schlossarek**
This pull requests fixes the destination path for pre section logs in kickstart_default.erb.

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]
This was introduced in bb4633bcd4facc339a8099f4a8e89312323d8b61 so needs a cherry pick to Foreman 2.4.

**Comment by ekohl** [comment]
ok to test

**Comment by ekohl** [comment]
The bot isn't happy about the length of the commit message. We try to follow the common convention to have a short first line. https://chris.beams.io/posts/git-commit/#limit-50 does a great job of describing why. Overall it's still a great post and a must read for any git user IMHO.

I'd also suggest you modify it to describe what it does rather than what was broken. What I would write is:

```
Fixes #32372 - Correct path for logs in kickstart

bb4633bcd4facc339a8099f4a8e89312323d8b61 refactored the kickstart but 
used an incorrect path for logs in the %pre section. This corrects it.
```

**Comment by lzap** [comment]
I thought I have fixed this, there might be a PR hanging with this change.

You will need to update snapshot files *snap.txt or run `RAILS_ENV=test bundle exec rake snapshots:generate`

**Comment by martin-schlossarek** [comment]
> The bot isn't happy about the length of the commit message. We try to follow the common convention to have a short first line. https://chris.beams.io/posts/git-commit/#limit-50 does a great job of describing why. Overall it's still a great post and a must read for any git user IMHO.
> 
> I'd also suggest you modify it to describe what it does rather than what was broken. What I would write is:
> 
> ```
> Fixes #32372 - Correct path for logs in kickstart
> 
> bb4633bcd4facc339a8099f4a8e89312323d8b61 refactored the kickstart but 
> used an incorrect path for logs in the %pre section. This corrects it.
> ```

Sorry for that. I fixed the commit message (copied yours :)).

**Review by ekohl — DISMISSED** [review]
If the tests are green, I think it can be merged. However, I'm quite certain @lzap is correct and we need to regenerate the snapshots.

**Review by lzap — APPROVED** [review]
Thank you very much. I would swear I have fixed this - someday in the past - somewhere. I dunno. Thanks.

**Comment by lzap** [comment]
Now I understand it! I was fixing similar issue and it was ME who actually introduced this:

https://github.com/theforeman/foreman/pull/7973/files

It looks like there are two remaining leftovers, would you mind raising a new PR fixing the rest?

```
app/views/unattended/provisioning_templates/provision/atomic_kickstart_default.erb
65:cp -vf /tmp/*pre*log /tmp/sysimage/root/

test/unit/foreman/renderer/snapshots/ProvisioningTemplate/provision/Atomic Kickstart default.snap.txt
29:cp -vf /tmp/*pre*log /tmp/sysimage/root/
```

No need to create another Redmine issue, just use `Refs #32372 - correct remaining paths` in the commit message, it is the same problem. My bad! I thought I saw this :-)

**Comment by martin-schlossarek** [comment]
Of course :)

New PR: #8462

**Comment by ezr-ondrej** [comment]
CP 2.4: #8478

**Pull request merged**
