### PR TITLE
Fixes #34938 - don't re-evaluate input() values on each host

### PR DESCRIPTION
**Pull request by evgeni**
poor laptop benchmark: with 3500 hosts, generating an Ansible inventory
took 200 seconds before, and 160 seconds after this patch.

### CODE REVIEW

**Review by ares — DISMISSED** [review]
APJ

**Review by ofedoren — DISMISSED** [review]
Thanks, @evgeni, seems logical to me.

**Comment by evgeni** [comment]
[Queries::LocationQueryTest.test_0001_fetching location attributes](https://ci.theforeman.org/job/test_develop_pr_core/10577/database=postgresql,ruby=2.7,slave=fast/testReport/junit/(root)/Queries__LocationQueryTest/test_0001_fetching_location_attributes/)
    [Queries::OrganizationQueryTest.test_0001_fetching organization attributes](https://ci.theforeman.org/job/test_develop_pr_core/10577/database=postgresql,ruby=2.7,slave=fast/testReport/junit/(root)/Queries__OrganizationQueryTest/test_0001_fetching_organization_attributes/)

This looks rather unrelated?

**Comment by evgeni** [comment]
seems to be related to https://github.com/theforeman/foreman/commit/c367ccbcb634a46e18710198f73aecb114464763?

cc @adamruzicka @nofaralfasi

**Comment by evgeni** [comment]
[test foreman]

**Comment by evgeni** [comment]
[test katello]

**Review by ofedoren — APPROVED** [review]

**Comment by ehelms** [comment]
[test katello]

**Pull request merged**
