### PR TITLE
fixes #3270 - load subnets for the domain associated with each NIC

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@domcleal thanks, would you mind adding a test?

**Comment by domcleal** [comment]
@ohadlevy for the helper itself?

**Comment by ohadlevy** [comment]
@domcleal good question, I guess since this is in AJAX, we would need something else then what we currently have, otherwise, we could have done something similar to a functional test with an assert_tag test
e.g.

``` ruby
 assert_tag :tag => 'a', :attributes => { :href => '/roles/1/edit' }
```

Since its outside of this PR discussion, I'll merge as is.. thanks!

**Comment by ohadlevy** [comment]
merged as 2899ab7 thanks @domcleal

**Pull request closed without merging**
