### PR TITLE
Fixes #23684 - Put production JS assets into dependencies

### PR DESCRIPTION
**Pull request by ehelms**
This is to ensure that the following works:

  NODE_ENV=proudction npm install
  NODE_ENV=production rake webpack:compile

### CODE REVIEW

**Comment by ehelms** [comment]
Proposing the addition of this testing to coincide with this -- https://github.com/theforeman/foreman-infra/pull/684

**Review by mmoll — APPROVED** [review]
works as expected now :+1:

**Comment by sharvit** [comment]
What is the reason to move dependencies to production instead use `NODE_ENV=proudction npm install --production=false`?

**Comment by ehelms** [comment]
@sharvit Sorry, I don't follow your question as it seems contradictory to set production and also set it to false? The premise behind the PR is that, today, you cannot run the following successfully:

```
NODE_ENV=production npm install
NODE_ENV=production rake webpack:compile
```

**Comment by sharvit** [comment]
Well, as weird as it may feel, we basically have 2 environments, dev and prod.

If production-env mean env to **run** the final product, what are the dependencies needed to **run** the final product?
None of them, because we **compile them into assets** (using other dependencies which acting as "build-dependencies"?)

Does it still make sense to put **all** our dependencies as "devDependencies"?
I think no, because **it helps us when we know what dependencies will/should land into assets**.
Then, when we writing code, we know we **shouldn't import any "devDependencies"**.

The command `NODE_ENV=production rake webpack:compile` mean **build production assets**.
Should we be able to compile production-assets in a production-environment? Or we need to do it in a dev/build env?

Running `NODE_ENV=proudction npm install --production=false` says, **I know i'm in a production-env, but I want to install all the dependencies so I can build my production assets later**.

I think that we should build our production product in a build-environment, which is closer to dev then prod because it depends on tools.

This make more sense to me:
```
npm install // because I should already be in a dev-env from the beginning?
NODE_ENV=production rake webpack:compile // to tell webpack we actually wants to build production product
```

**Comment by ehelms** [comment]
So, you are arguing that the following use case:

```
NODE_ENV=production npm install
NODE_ENV=production rake webpack:compile
```

Is an invalid use case? I am asking because your above workflows should work even with the changes I made here. However, the workflow outline does not currently work without this change. I would argue that I should be able to install the *minimal* set of dependencies needed to compile webpack in a production manner. Here are two use cases why this is important:

 1) I want to identify what node modules are required minimally by RPM build environment to detect any requires updates to those RPM based packages without having to sift through non-production modules
 2) If we were to ever move to a model where we simply took a tarball of `node_modules` and put that into our source tarball to use instead of RPM based nodejs packages, we would want the minimal set possible to save on storage and bandwidth.

**Comment by sharvit** [comment]
I'm not sure if I can say it's invalid, but it doesn't make sense to me.

> I would argue that I should be able to install the minimal set of dependencies needed to compile webpack in a production manner.

This is make sense to me, I wish npm could work like bundle when you can define gem-groups manually.
Don't understand me wrong, I am fine with adding those dependencies from dev to prod and I did with few projects when I wanted to let heroku do the build after every git-push (and it lead to some confusions).

It just that most of the js community deciding not to do so when it is possible.

**Comment by ehelms** [comment]
@sharvit Are you good with this getting merged? @mmoll If so, mind doing the honors?

**Comment by ohadlevy** [comment]
@ehelms I think this is not a common way of doing npm packages, and will hurt us in the long run.
I would suggest that node_modules is a build artifact, meaning that you threat it like source files? imho the workflow should be
for foreman
```
npm i --no-optional
NODE_ENV=production rake webpack:compile 
```

I think we should start considering building the webpack based assets as a separate package ?

**Comment by sharvit** [comment]
@ehelms If it's possible and make sense to you, I would personally prefer not merge it and update the `npm install` script to install devDependencies as well.

**Comment by ehelms** [comment]
Sorry y'all, you've entirely lost me. Perhaps we should start at the beginning and give me your understanding of what the "dependency" group should be. Since from where I sit, that should be every dependency required for the UI to actually work and without this change, that does not currently happen when I use NODE_ENV=production.

**Comment by sharvit** [comment]
From my point of view, "dependency" group should be dependencies that land into assets.
I think the packaging should also install "devDependencies" because they contain the building tools (and more stuff).

**Pull request closed without merging**
