### PR TITLE
Fixes #23736 - Add RancherOS templates into seeds

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by lzap** [comment]
This patch looks more like new sync of templates from community repo and fixing seeds. Can you rename the ticket and commit message then?

**Comment by xprazak2** [comment]
Exactly, I need to add a sync from community templates to avoid chicken-and-egg problem.
When I try to add just templates, [seed_test](http://ci.theforeman.org/job/test_develop_pr_core/17632/database=sqlite3,ruby=2.4,slave=fast/testReport/junit/(root)/SeedsTest/test_0005_populates_config_templates/) complains about .erb template files not being used in seeds.
When I add it only to seeds, they cannot be seeded because the .erb files are [missing](http://ci.theforeman.org/job/test_develop_pr_katello/7299/database=postgresql,ruby=2.4,slave=fast/testReport/junit/(root)/Katello__LocationsTest/test_0001_don_t_create_a_default_location_if_no_locations_exist/) 

I would prefer to keep this as 2 commits so that the db/seeds part can be easily cherry-picked into 1.18. Which message would you like me to rename?

**Review by lzap — APPROVED** [review]
I haven't noticed it's a second commit, that's fine thanks.

**Comment by lzap** [comment]
Thanks.

**Pull request merged**
