### PR TITLE
Fixes #29708 - Remove internal use of deprecated JS API

### PR DESCRIPTION
**Pull request by johnpmitsch**
The API module is deprecated and can be updated internally.

### CODE REVIEW

**Comment by johnpmitsch** [comment]
This should be updated in general, but also is a priority because now that Katello can use `foremanReact` directly in testing, this deprecation causing some issues during testing. I [explained further here](https://github.com/Katello/katello/pull/8644#issuecomment-624253461) (in the second section)

**Comment by tbrisker** [comment]
Test failures seem related.
Additionally, the old API module was deprecated for removal in 1.26, which is 2.1 - so we should probably drop it (or update the deprecation to 2.2 if there are still places using it that we don't want to break right now)

**Comment by johnpmitsch** [comment]
> Additionally, the old API module was deprecated for removal in 1.26, which is 2.1 - so we should probably drop it (or update the deprecation to 2.2 if there are still places using it that we don't want to break right now)

Looks like foreman-tasks still needs to be updated, for example [here](https://github.com/theforeman/foreman-tasks/blob/master/webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js#L1) - so my preference would be to remove internal usage and move the deprecation to 2.2 here and remove the actual functionality in another PR so we can be thorough in ensuring we don't break plugins

**Comment by johnpmitsch** [comment]
@tbrisker @sharvit I updated and also bumped the deprecation as discussed. Tests are passing locally, it looks like the failures could be unrelated?

**Comment by mmoll** [comment]
Travis tests are green after a re-kick and Foreman test failure is unrelated. :green_heart:

**Review by tbrisker — APPROVED** [review]
Thanks @johnpmitsch !

**Pull request merged**
