### PR TITLE
Fixes #17461 - Minor changes to message text

### PR DESCRIPTION
**Pull request by Conor0Callaghan**
Corrected from operating systems to operating system

### CODE REVIEW

**Comment by timogoebel** [comment]
@ivernus : Thanks for your patch. The changes to the po/pot-File are unnecessary. The fixed test gets extracted automatically during release prep. Could you please revert them? Thanks.

**Comment by Conor0Callaghan** [comment]
@timogoebel I think that's correct? does it look right now?

**Comment by timogoebel** [comment]
@theforeman-bot ok to test

@ivernus : Thanks, i'll quickly kickstart our ci pipeline.

**Comment by timogoebel** [comment]
Merged, thanks @ivernus .

**Pull request merged**
