### PR TITLE
Fixes #32904 - update js vendor to 8.7

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@tbrisker I'd love to merge this, I think that these dependencies are upgraded as part of release process, or should we wait for packaging here?

**Comment by MariaAga** [comment]
I will be also adding a pr for katello

**Review by ekohl — COMMENTED** [review]
Should we wait for https://github.com/theforeman/foreman-js/pull/313 to be merged and then update to that?

**Comment by tbrisker** [comment]
This requires updating the packaged version, which is currently 8.4.5. It would be good to actually get that in sooner and test that nightly builds are passing, but I agree with @ekohl that we should update to a version that includes the fix required for the ace search.

**Comment by tbrisker** [comment]
foreman-js 8.7.0 has been released with the brace fix, please update this PR to require that version and update the RPM package.

**Comment by MariaAga** [comment]
Updated with 8.7 . Thanks for the update!

**Review by ekohl — APPROVED** [review]
:+1: pending a packaging update: https://github.com/theforeman/foreman-packaging/pull/6832

**Comment by ehelms** [comment]
The builds are now available in Koji for foreman-js.

**Pull request merged**
