### PR TITLE
Fixes #6693 - set parameters tab to error state and focus when validation fails

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by lzap** [comment]
I am unable to reproduce the bug. When I provide blank param/value, the form ignores that fact and continues. I see the same behavior in both New OS and Edit OS forms. Blank param/value parameters are simple ignored, with or without your patch. Help me here how should I test this.

**Comment by orrabin** [comment]
@lzap, you need to save a parameter with a value and then edit the OS and try to add another parameter with the same name.

**Comment by lzap** [comment]
Unable to reproduce on both Foreman develop or Satellite 6.0 latest drop.
- I go to OS
- edit RHEL 6.5
- insert new param test/test
- edit the same OS
- insert new param with test/ (nothing)
- submit (it works, no error message at all)

I can do the same for New OS or even when I try to add a parameter with name and value blank. In all cases, the form submits and deletes the incorrect parameter.

**Comment by orrabin** [comment]
@lzap your steps are correct but the second parameter should be test/something.

The problem that blank values doesn't cause an error is handled in a different PR: https://github.com/theforeman/foreman/pull/1610 and until it is merged you cant check that part, you can only check "UI shouldn't switch to other tab while creating OS parameters with same name".
The problem here is that any error that is shown in the UI didn't change the tab heading to red and didn't focus on it automatically

**Comment by domcleal** [comment]
It would be useful to update the commit message to more precisely say what's being changed - as a suggestion: "fixes #6693 - set parameters tab to error state and focus when validation fails"

**Comment by orrabin** [comment]
@domcleal changed the comment

**Comment by lzap** [comment]
_R E P R O D U C E D_

Works for me. :+1:

**Comment by dLobatog** [comment]
Tested, and this works on edit, params tab show the error "name is taken", that's fine. 

However this should work on create too. When I try to create a OS and params are wrong, for instance name is duplicated, it just goes ahead and creates the OS with both parameters (wrong).

**Comment by orrabin** [comment]
@eLobato the problem is fixed in: https://github.com/theforeman/foreman/pull/1607
both PRs together provide a full fix to the errors in parameters tab

**Comment by lzap** [comment]
I am fine to merge.

LZ

## 

Later,
 Lukas #lzap Zapletal

**Comment by ohadlevy** [comment]
just do it (tm)

**Comment by dLobatog** [comment]
I've just tested #1607 and it fixes what I commented. I'l be merging this soon but I'd suggest for the next time not to split similar issues like these two.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/2b5f9c11bdcb158598dc80aaba51347615ca1c4f , thanks @orrabin !

**Pull request closed without merging**
