### PR TITLE
Fixes #15166 - correct layout of dashboard when zoomed

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by lzap** [comment]
Merged as 38fdd66f31a115367f463d5b34a5ab499784a7f6, thank you!

**Comment by helge000** [comment]
Thanks @tbrisker ! Is there a way I can test this patch on a running 1.11 instance?

**Comment by tbrisker** [comment]
@helge000 if you are running from RPMs then you will need to find the correct place inside the minified css file to add the missing line.

**Comment by helge000** [comment]
Hm, found this in `/var/lib/foreman/public/assets/application-1a0ab09dde694d9a282a3d17e322281c0334b1a20b87179b6c489aa3d05a4883.css`  and added `clear: both;`. However, it did not solve the scaling issue with me.

**Comment by tbrisker** [comment]
@helge000 if you check the page source with chrome dev tools or firebug, does the style get applied? If not, you may need to clear your cache, or possibly check that you added it in the right location (under   `.dashboard .status-table li`). I just tested with the latest nightly and it seems to work fine when zoomed, and it does not look like this css changed from 1.11.

**Pull request closed without merging**
