### PR TITLE
Fixes #9434 - managed alias accepts only static boot mode subnet

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
Rebased

**Comment by dLobatog** [comment]
@ares :+1: , good to go after fixing the failing test in my opinion.

**Comment by ares** [comment]
I fixed the failing test and extracted it to separate PR, as it's not related to this.https://github.com/theforeman/foreman/pull/2224

**Comment by ares** [comment]
Rebased again

**Comment by dLobatog** [comment]
@ares Needs rebasing :sob:

**Comment by ares** [comment]
3rd rebase

**Comment by dLobatog** [comment]
Merged as a45253c2b7c747b15506dddc4efa86396c6ef53f, thanks @ares !

**Pull request closed without merging**
