### PR TITLE
Fixes #7591 - Inconsistent terminology around Login vs Sign Out

### PR DESCRIPTION
**Pull request by boaz0**
Used `grep -rn --color '[Ss]ign [Oo]ut' foreman/` to find all occurrences of 'Sign out', 'sign out', 'Sign Out' or 'sign Out' in Foreman.

### CODE REVIEW

**Comment by boaz0** [comment]
How can I tell what the merge conflicts are?

**Comment by dLobatog** [comment]
Thanks for the fix. Please don't modify .po files, those are generated automatically on every release according to i18n marked strings.

**Comment by boaz0** [comment]
@eLobato, thanks a lot! :smile:

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@domcleal @stbenjam @GregSutcliffe :+1: to this?

**Comment by lzap** [comment]
+1 There will be likely conflict with https://github.com/theforeman/foreman/pull/1800 for the record :-)

**Comment by stbenjam** [comment]
http://ux.stackexchange.com/questions/1080/using-sign-in-vs-using-log-in argues for "Sign in/out" but I have no preference, they seem equivalent to me, so we should just be consistent.

**Comment by dLobatog** [comment]
Alright, @ripcurld00d can you rebase? I'd say let's merge this and if someone is bothered about sign in vs log in then that person can change it everywhere.

For the record my preference is sign up (register), log in, and log out. I think non-native speakers might confuse sign up with sign in.

**Comment by shlomizadok** [comment]
Speaking of terminology, I think (not sure though) there are two terminologies:
`Register, Log in, Log out` or `Sign up, Sign in, Sign out`

**Comment by boaz0** [comment]
@eLobato :octocat:

**Comment by stbenjam** [comment]
[test]

**Comment by isratrade** [comment]
merged as f83023096a5fb900fb7d27cd0bc40117a34f1493. Thanks @ripcurld00d !

**Pull request closed without merging**
