### PR TITLE
Fixes #7634 - rename chef feature

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
or we may wait a bit and the `Chef` feature will be created by foreman_chef plugin, so I'd change this PR to simply remove `Chef Proxy` feature

**Comment by dLobatog** [comment]
@ares What you last said sounds to me like a good strategy. 
@domcleal Why is this a blocker?

**Comment by ares** [comment]
I'd say that removing this feature from foreman proxy is not a good idea for 1.6.1. So I'm for merging this so we resolve the issue for 1.6 and remove this later (in 1.7).

**Comment by domcleal** [comment]
@eLobato because it's broken on 1.6 currently, as the 1.6 proxy renamed it (I missed that).  I agree with @ares.

**Comment by ares** [comment]
so I wonder whether we should revert flags or is there something required from my side?

**Comment by domcleal** [comment]
Yeah, I was thinking about that too when I saw this PR at first.. it'd help for cross-version compatibility, but that's not a huge concern.  But then I figured you might want to move to just "Chef" rather than "Chef Proxy" in foreman_chef anyway.

**Comment by domcleal** [comment]
@ares are you _sure_ the proxy feature was renamed?

```
["bmc","chefproxy","dhcp","dns","facts","puppetca","tftp"]
```

On develop locally.

**Comment by ares** [comment]
I was quite sure when I worked on that. Just to avoid confusion before I'll try to find the change in history, are you running modularized proxy and did you try to refresh features of that proxy?

**Comment by domcleal** [comment]
@ares yeah, modular smart proxy and I tried refreshing with your change, only to find it wasn't picked up.  I did a db:migrate:down and it picked up the Chef Proxy feature again.

**Comment by ares** [comment]
@domcleal I can't reproduce it now, is seems that something was broken in my env. I checked that plugin in chef_plugin.rb didn't change since modularization commit. Sorry for false positive, I suppose this is not 1.6.1 blocker and we can remove the feature completely in 1.7, so closing this PR. My apologies.

**Comment by domcleal** [comment]
Phew, thanks!

**Pull request closed without merging**
