### PR TITLE
Fixes #8779 - add vlanid to subnet ENC

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
IIRC there's a host unit test that checks this, it will probably need an update.  (And if it doesn't, we should probably add vlanid to the test subnet so that it does.)

**Comment by ares** [comment]
@domcleal fixed

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@ares :+1: too, this needs a rebase after your PR that changed the default boot mode to DHCP. Will merge after that if Mr Jenkins is pleased.

**Comment by ares** [comment]
@eLobato rebased, let's see what Mr. Jenkins thinks about it

**Comment by dLobatog** [comment]
Merged as a899d97175c683bb648e3cbd34d0aebcae1252cf, thanks @ares !

**Pull request closed without merging**
