### PR TITLE
Fixes #35561 - Allow delaying yggdrasil restart

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ianballou — DISMISSED** [review]
Worked for me! I'm able to switch freely between content sources now.

**Review by ianballou — APPROVED** [review]
Retested and working well

**Comment by jeremylenz** [comment]
Should probably make a corresponding change in https://github.com/theforeman/katello-pull-transport-migrate as well.

**Comment by adamruzicka** [comment]
> Should probably make a corresponding change in https://github.com/theforeman/katello-pull-transport-migrate as well.

I briefly considered that, but is it necessary? I don't mind doing the change for the sake of consistency, but I don't expect that the rpm variant of it would be installed through an already deployed pull provider client.

**Comment by jeremylenz** [comment]
> I don't mind doing the change for the sake of consistency

Yeah, it's more the principle. Just feels wrong to have the two sources of truth, but it would make me feel better if they were at least manually synced.

**Review by jeremylenz — APPROVED** [review]
ACK based on @ianballou, thanks @adamruzicka!

**Pull request merged**
