### PR TITLE
fixes #2933 - Installation media API misses some features

### PR DESCRIPTION
**Pull request by tstrachota**
- added missing fields to show rabl
- apipie params for os ids

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm jenkins issue? [test]

**Comment by domcleal** [comment]
@isratrade, could you review please?

**Comment by isratrade** [comment]
@domcleal, @theforeman, PR is fine with me.  My goal in the future is for a user to pass a list of fields to include in the response, something like ?fields=field1, field2,abc_ids

**Comment by domcleal** [comment]
Thanks @tstrachota, merged as d4ea640.

**Pull request closed without merging**
