### PR TITLE
[WIP] Fixes #22110 - update tests for minitest 5.11

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by boaz0 — DISMISSED** [review]
LGTM 👍

**Comment by mmoll** [comment]
seems like there's still an issue... https://github.com/seattlerb/minitest/issues/729

**Comment by mmoll** [comment]
Setting to WIP as there are a few changes required and/or changes to minitest will happen in the near future.

**Comment by mmoll** [comment]
This should be good to go now, after the Rails 5.1.6 update, which brought adjustments in Rails for the new minitest version.

**Comment by mmoll** [comment]
*sigh*, while the console output regarding the class names seems to be fixed, the result still is broken.

**Pull request closed without merging**
