### PR TITLE
Fixes #32508 - use root_pass.present? to check the root_pass

### PR DESCRIPTION
**Pull request by evgeni**
.empty? doesn't work on NilClass

### CODE REVIEW

**Comment by evgeni** [comment]
cc @tbrisker stable-pick candidate

**Review by tbrisker — APPROVED** [review]
Thanks @evgeni !

**Comment by tbrisker** [comment]
2.5  - 6e53aa9ef

**Comment by tbrisker** [comment]
2.4 - 351c0c13a

**Pull request merged**
