### PR TITLE
Fixes #24071 - Adding locked state

### PR DESCRIPTION
**Pull request by sbernhard**
Adding locked state to ptable api/v2 view

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]
LGTM.

**Review by tbrisker — APPROVED** [review]
Thanks @sbernhard !

**Review by dLobatog — APPROVED** [review]
I think someone forgot to merge :smile:

**Comment by lzap** [comment]
Time to merge: 1,5 hours. Guys we are on a roll!

**Comment by sbernhard** [comment]
Thank you. Very appreciated.

**Pull request merged**
