### PR TITLE
Fixes #20950 - Use 'distinct' in AR finders

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
taken from Dominic's rails51 branch

**Review by iNecas — CHANGES_REQUESTED** [review]
Based on grep, I've found one more https://github.com/theforeman/foreman/blob/develop/app/models/puppetclass.rb#L104

**Comment by mmoll** [comment]
updated, test failure unrelated.

**Comment by tbrisker** [comment]
Thanks @mmoll and @domcleal !

**Pull request merged**
