### PR TITLE
Fixes #21828: Update patternfly-react version to 0.13.0

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/21838

### CODE REVIEW

**Comment by waldenraines** [comment]
> Issues: #21828

Should be [#21838](http://projects.theforeman.org/issues/21838)

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
@waldenraines please note that snapshot update is required too.

**Comment by waldenraines** [comment]
> @waldenraines please note that snapshot update is required too.

Can you please point me to some documentation on how to do that, it's been a while.

**Comment by waldenraines** [comment]
@ohadlevy updated.

**Comment by waldenraines** [comment]
[test foreman]

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
