### PR TITLE
fixes #8221 - search for subnet with taxonomy scope

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
Wouldn't that undo the fix of whatever it was that _override was added for?

**Comment by ares** [comment]
I know @isratrade added bi-directional inheritance of taxonomies, this _override changes the direction and was intentional. I'm not sure about the need of this but @isratrade might be able to put some light on it.

**Comment by shlomizadok** [comment]
Went through this with @isratrade -- the `domain.subnets` does not require bi-directional inheritance of of taxonomies, (especially when the override unscopes the `domain.subnets`) hence the change. @isratrade -- would love your input.

**Comment by isratrade** [comment]
All places where we use `with_taxonomy_scope_override`, it is on the model

``` ruby
Hostgroup.with_taxonomy_scope_override(@location,@organization)
Domain.with_taxonomy_scope_override(@location,@organization).order(:name)
ComputeResource.with_taxonomy_scope_override(@location,@organization)
```

The issue with subnets is that we have `accessible_subnets` and `domain_subnets`. 

`accessible_subnets' stays "as is"

``` ruby
  def accessible_subnets
    Subnet.with_taxonomy_scope_override(@location,@organization).order(:name)
```

but `domain_subnets` is what @shlomizadok is changing

``` ruby
  def domain_subnets(domain = @domain)
    return [] if domain.blank?
-    domain.subnets.with_taxonomy_scope_override(@location,@organization).order(:name)
+    domain.subnets.with_taxonomy_scope(@location,@organization).order(:name)
  end
```

Note that it's `domain.subnets` and not `Subnet`. In this case, even though it's confusing, I think removing the `_override` is correct, at least in the example that @shlomizadok showed me.

**Comment by shlomizadok** [comment]
refactored to use accessible_subnets helper method (which uses the override and bi-directional inheritance of the taxonomies)

**Comment by dLobatog** [comment]
Looks good to me, I also agree using overriding in the model is the usual practice, I wonder if we can put all of these unspoken conventions together somewhere :book: 

Merging in 3..2...1... :bomb:

**Comment by dLobatog** [comment]
Merged as e23023e29632a755582b2bd080fc7b226e606620, thanks @shlomizadok !

**Pull request closed without merging**
