### PR TITLE
fixes #4643 - Retrieving Optional LDAP attributes fails on 1.8.7

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
@domcleal Oops, I didn't see you marked this is ready to merge. I just added a test to make sure we test the whole authenticate business so something isn't missed again later.

**Comment by domcleal** [comment]
@stbenjam nice, thanks!

**Comment by domcleal** [comment]
Merged as b7f90cc for Foreman 1.5.0, thanks @stbenjam.

**Pull request closed without merging**
