### PR TITLE
Fixes #13984 - inherit subnet from hostgroup even for image-based provisioning

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
[test]

**Comment by domcleal** [comment]
I don't know that subnet_id should be assigned unconditionally because it's valid to leave it blank.  This is probably even desired for some types of provisioning, e.g. EC2 image provisioning.

In those cases, the CR provides an IP address which will be assigned to the primary NIC, but if the subnet gets inherited from the host group then it'll probably not match the IP's network.

Would assigning subnet_id `unless compute_provides?(:ip)` work for both?

**Comment by iNecas** [comment]
In that case, shouldn't the user rather not use the hostgroup with the subnet specified, or override the subnet by the one that doesn't have dhcp integration? `unless compute_provides?(:ip)` might work, although it would be a bit surprising behaviour TBH. It would still be better than it's right now.

**Comment by domcleal** [comment]
> In that case, shouldn't the user rather not use the hostgroup with the subnet specified

Usually the host group is relatively independent of the provisioning method and compute resource.  Most of the attributes that are provisioning related aren't actually on the host group.  It's usually possible to use a host group on a number of compute resources, bare metal etc.

> or override the subnet by the one that doesn't have dhcp integration?

This might work if setting a subnet, but if you don't want to set a subnet (because cloud-based CRs such as EC2/Rackspace won't have them stored in Foreman) then `assign_hostgroup_attributes` will still set subnet_id.

**Comment by iNecas** [comment]
Updated

**Comment by domcleal** [comment]
Merged as 17f4ee6, thanks @iNecas.

**Pull request closed without merging**
