### PR TITLE
Refs #25882 - use working iterator for webpack entries

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by sharvit — APPROVED** [review]
LGTM

**Review by tbrisker — APPROVED** [review]
Tested this with several plugins (but not katello) and compilation seems to work now. Can someone with a working katello dev setup apply this and check if the webpack compilation works properly?

**Comment by jturel** [comment]
Taking a look @ Katello

**Comment by jlsherrill** [comment]
@tbrisker i ran: 
```
node_modules/webpack/bin/webpack.js --config config/webpack.config.js --bail --env.pluginName=katello
```

and saw both katello and katello:common get compiled:
```
             katello/katello.js  3.24 MB      30  [emitted]  [big]  katello
              katello/bundle.js  1.45 MB      31  [emitted]  [big]  bundle
      katello/katello:common.js     3 MB      32  [emitted]  [big]  katello:common
              katello/vendor.js  27.7 MB      33  [emitted]  [big]  vendor
```

also checked the generated manifest.json:

```
    "katello": [
      "katello/katello.js",
      "katello/katello.css"
    ],
    "bundle": [
      "katello/bundle.js",
      "katello/bundle.css"
    ],
    "katello:common": "katello/katello:common.js",
```

which i believe looks right (was missing katello:common previously)

**Comment by jturel** [comment]
Before patch:

```
I, [2019-01-22T16:28:50.322686 #13936]  INFO -- : Writing /home/vagrant/katello/public/assets/katello/widgets/tabs-dab9b127ac0fb65d3066c7f30ece8a4a542854cb6766127d25b0a21b016d4bc8.css.gz                                                                                     
/home/vagrant/foreman/node_modules/webpack/bin/webpack.js --config /home/vagrant/foreman/config/webpack.config.js --bail --env.pluginName=katello                                                                                                                              
/home/vagrant/foreman/config/webpack.config.js:74
    for (var entry of plugins['entries']) {
                           ^

TypeError: plugins.entries[Symbol.iterator] is not a function
    at module.exports.env (/home/vagrant/foreman/config/webpack.config.js:74:28)
    at handleFunction (/home/vagrant/foreman/node_modules/webpack/lib/prepareOptions.js:26:13)
    at prepareOptions (/home/vagrant/foreman/node_modules/webpack/lib/prepareOptions.js:11:13)
    at requireConfig (/home/vagrant/foreman/node_modules/webpack/bin/convert-argv.js:98:14)
    at /home/vagrant/foreman/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
```

After patch:

```
                 katello/katello-146c94e21fe60903ccea.js.gz     126 kB          [emitted]
              katello/bundle-447cf1da8a6273d7d28a.js.map.gz     164 kB          [emitted]                                                                                                                                                                                      
             katello/katello-146c94e21fe60903ccea.js.map.gz     352 kB          [emitted]  [big]                                                                                                                                                                                
      katello/katello:common-f8a96a579eba9f209ee7.js.map.gz     369 kB          [emitted]  [big]
                  katello/vendor-385bdafcd166b9d752a4.js.gz    1.39 MB          [emitted]  [big]
              katello/vendor-385bdafcd166b9d752a4.js.map.gz    3.32 MB          [emitted]  [big] 
```

Looks good!

**Review by jturel — APPROVED** [review]

**Comment by tbrisker** [comment]
93e9a04fc is the 1.21-stable cherrypick for the record

**Pull request merged**
