### PR TITLE
Fixes #19855 - Disable Style/ConditionalAssignment cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by lzap** [comment]
I hate this cop. -1

**Comment by mmoll** [comment]
allright, changed this PR to disable that cop

**Review by lzap — DISMISSED** [review]
Thanks a bunch!

**Comment by mmoll** [comment]
rebased.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @mmoll.

**Pull request merged**
