### PR TITLE
Fixes #33656 - Updating scoped search for org and loc at FactValue

### PR DESCRIPTION
**Pull request by domitea**
Adding own external search method for scoped search at organization_id and location_id. It's avoids producing bad SQL query that produces bad results in some cases.

It about the case when you're clone a default Viewer role and assign her to a Organization and Location. It then produces in cloned filters `taxonomy_search` something similar to `(organization_id ^ ( ID )) and (location_id ^ ( ID ))`. It works great with the object with taxonomy but `FactValue`. This model has association to Organization and Location through Host (https://github.com/theforeman/foreman/blob/develop/app/models/fact_value.rb#L15) but it's not included in Taxonomy at all. Thanks this conditions, the request for index page of `FactValue` produces SQL query with empty results for user with cloned role (Clone of Viewer role and added Org and Loc). I found that the problem is by `scoped_search` generation of query for the `FactValue` in method of `Authorizer` class (https://github.com/theforeman/foreman/blob/develop/app/services/authorizer.rb#L100). This method produces SQL part, that expects that taxonomy (`organization_id` and `location_id`) is a part of `FactValue` model but it's not (see https://github.com/theforeman/foreman/blob/develop/app/models/fact_value.rb#L15). So I need to found a way how to say to this method that `organization_id` and `location_id` are accessible through `Host` association. Solution is creating own external search method for `organization_id` and `location_id`.

### CODE REVIEW

**Comment by ares** [comment]
If I get that correctly, the ext method is mainly required to add the `joins :host`. Would it work and make sense to add this join to the relation that loads taxonomies? That way whenever the taxonomies are filtered, host would be available in the SQL query and the filtering would work, not only when scoped search is used. Facts seems to require the parent object (host) for any taxonomies query, since they inherit the relationship from it.

**Comment by domitea** [comment]
As we discussed earlier, I tried to rewrite custom SQL snippet (aka inject own SQL code through external method) for `Scoped Search` into their own syntax and I don't think it's possible. At least without improving `Scoped Search` itself.

For a quick recap: `Scoped Search` has many parameters. Two of them are `in_key` and `on_key` (https://github.com/wvanbergen/scoped_search/blob/92939afa16dd9d18f39e5ac1fd22d3a8f4154a48/lib/scoped_search/definition.rb#L78). These key can be used for edit relation is some cases (at least code allows it). BTW: It's used in `FactValue` model (https://github.com/theforeman/foreman/blob/develop/app/models/fact_value.rb#L19) already but... Wait until the end ;)

Back to the scope of the PR... With the updated code, the Foreman throws exception `undefined method table_name for nil class` at https://github.com/wvanbergen/scoped_search/blob/b692e733535714f9b82cc9d5cc1f2bf3856f79fb/lib/scoped_search/query_builder.rb#L361 and the reason is fairy simple. Model allows to show us a `reflections` thanks to `ActiveRecord`. It return hash with reflections for given model where key is plural of related model and value is AR related stuff (it's not important for PR). When I tried to use a both keywords (`in_key` and `on_key`) it tries through `Scoped Search` logic produce correct SQL query. I have some relations in the request, so it makes sense that the `Scoped Search` uses `construct_join_sql` to produce nice SQL join for given relation. In that case is given by `in_key`. The problem is fairly simple.  `Scoped Search` is trying to find correct relation in `relations` (https://github.com/wvanbergen/scoped_search/blob/92939afa16dd9d18f39e5ac1fd22d3a8f4154a48/lib/scoped_search/definition.rb#L315) for given model by using a singular (https://github.com/wvanbergen/scoped_search/blob/b692e733535714f9b82cc9d5cc1f2bf3856f79fb/lib/scoped_search/query_builder.rb#L359) variant of the relation name and it's obviously return `nil` in the hash full of plural keys. The fun part is already used definition. It uses also external method. Sure, there is little complex query but the `in_key` and `on_key` logic is bypassed. 

I really like to go much deeper in that but I think it's little out of scope of this PR but good idea :+1:

**Comment by ares** [comment]
I think I found a simpler solution

```
scoped_search :relation => :host, :on => :location_id, :rename => :location_id, :complete_enabled => false, :only_explicit => true, :validator => ScopedSearch::Validators::INTEGER
scoped_search :relation => :host, :on => :organization_id, :rename => :organization_id, :complete_enabled => false, :only_explicit => true, :validator => ScopedSearch::Validators::INTEGER
```

The `ext_method` you used does not take [scoped_search operators](https://github.com/wvanbergen/scoped_search/wiki/query-language#comparison-operators) into the account, they don't map 1:1 to SQL operators.

**Comment by ares** [comment]
[test foreman]

**Comment by domitea** [comment]
Let's see if rebasing helps

**Comment by domitea** [comment]
[test katello]

**Comment by domitea** [comment]
Rebase helps, let's if Katello tests are fine with that too.

**Review by ares — APPROVED** [review]
the katello failure
```
NameError: undefined local variable or method `updated_at' for #<Setting::ForemanTasks:0x000000000ccb4808>
```
does not seem to be related

Retested to double check and it fixes the issue, thanks @domitea, merging!

**Review by ares — CHANGES_REQUESTED** [review]
Actually not merging, please update the commit message so that it describes the current implementation.

**Comment by domitea** [comment]
@ares PR reworded. I hope that the commit message fits to the PR now.

**Comment by ezr-ondrej** [comment]
Katello failure is unrelated, but FactValue search is very complex especially when permissions are considered, would be nice to have a test for that, what do you think @domitea ?
I'd be ok doing it as a follow up, but I'd not see this on first sight, and reverting this would not break any tests, which might cause trouble in the future.

**Review by ares — APPROVED** [review]
It would certainly be nice to add an integration test covering the user story. I'm leaving that to a separate PR to get the relatively simple fix in. Thanks @domitea and @ezr-ondrej, merging!

**Pull request merged**
