### PR TITLE
Fixes #5664 - Host filters can use taxonomies

### PR DESCRIPTION
**Pull request by ares**
Also disables taxonomy filters on resources that do not support them.

### CODE REVIEW

**Comment by dLobatog** [comment]
Looks good, although I will have to check (one by one unless there is a list) which resources can and cannot be filtered by taxonomy. 
Other than that I think it could use a `allows_taxonomy_filtering(Location, Organization)` method to save up some lines of code.

**Comment by ares** [comment]
> Looks good, although I will have to check (one by one unless there is a list) which resources can and cannot be filtered by taxonomy. 

hm, good idea, maybe we could add a check for existing organization_id search into Taxonomix module, thoughts?

> Other than that I think it could use a allows_taxonomy_filtering(Location, Organization) method to save up some lines of code.

could you elaborate what do you mean by that?

**Comment by dLobatog** [comment]
Nevermind, what you did looks right. I just didn't find the `def allows_taxonomy_filtering?(taxonomy)` method at first and was a little confused.

**Comment by ares** [comment]
ok, ad

> Looks good, although I will have to check (one by one unless there is a list) which resources can and cannot be filtered by taxonomy.

since Taxonomix define scoped_search on org and loc I think it should be ok, Host was the special case because it belongs to only one taxonomy so we don't use Taxonomix there

so is this PR still waiting on contributor?

**Comment by dLobatog** [comment]
Don't think so, I'll give it a 2nd review & test just in case I missed something else!

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/82b4749eeddabc542ebf1eaec6fdf2d76d2fdd75 , thank you @ares !

**Pull request closed without merging**
