### PR TITLE
Fixes #8566 - reorganized settings categories

### PR DESCRIPTION
**Pull request by xprazak2**
SSL cert settings were moved from 'Provisioning' into 'Auth'

### CODE REVIEW

**Comment by dLobatog** [comment]
@xprazak2 Thanks for the patch! Seems OK, I have not tested it yet, but I assume no migration of data would be needed as it's just a cosmetic change, the setting stil has the same name.

**Comment by xprazak2** [comment]
@eLobato I just realized, category of the moved settings gets changed and already existing records should be probably modified to reflect the change. Should I write migration for that?

**Comment by domcleal** [comment]
It's not entirely cosmetic, the category is stored in the settings table as it's actually STI.  The setting classes though appear to update it (end of the initialisation loop), so I would expect on the next restart for the categories to update without needing a migration?

**Comment by xprazak2** [comment]
> The setting classes though appear to update it (end of the initialisation loop)

I thought exactly the same thing, but update in the block is called on a Hash:
https://github.com/theforeman/foreman/blob/develop/app/models/setting.rb#L244

**Comment by domcleal** [comment]
Maybe try adding :category to the list of attributes to update in `Setting.create!`

**Comment by xprazak2** [comment]
Not sure I follow. Could you point me to the line you are referring to?
I believe the following line does not update the already existing settings at all:
https://github.com/theforeman/foreman/blob/develop/app/models/setting/auth.rb#L20

**Comment by domcleal** [comment]
The line you linked to calls [Setting.create!](https://github.com/theforeman/foreman/blob/develop/app/models/setting.rb#L162) which has special handling for settings that already exist.  It calls [create_existing](https://github.com/theforeman/foreman/blob/develop/app/models/setting.rb#L172) which updates the default value and description every time, so you could perhaps add :category to the to_update line.

**Comment by xprazak2** [comment]
I see, thx. Unfortunately, changing STI category on a runtime is not this simple :( , so I did it a bit differently...

**Comment by domcleal** [comment]
@xprazak2 tests are failing, specifically SettingTest.test_create_exclamation_updates_description

**Comment by xprazak2** [comment]
I'll look into it.

**Comment by domcleal** [comment]
Looks good, could you just add a unit test for the behaviour of changing setting categories please?  Something that creates a setting via `create!`, then calls it again with a different category, and checks it's updated the record correctly.

**Comment by xprazak2** [comment]
I've added the unit test for create! method.

**Comment by domcleal** [comment]
Merged as fb293de, thanks @xprazak2.

**Pull request closed without merging**
