### PR TITLE
bugfix: #5963 fix Role has_permission? function

### PR DESCRIPTION
**Pull request by martin-ducar-gd**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by martin-ducar-gd** [comment]
I've checked the jobs and the test failure doesn't seam to be releated with the change, can you please confirm?

**Comment by domcleal** [comment]
@martin-ducar-gd confirmed.. we'll get this fixed first, thanks!

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/3f5ddc49bd321a23dd8fc17e6b3cd64bfd3f5e4a, thanks @martin-ducar-gd ! 
This method isn't used anywhere but it's helpful for `foreman-console` users :smile:

**Pull request closed without merging**
