### PR TITLE
Fixes #19886 - Disable Style/ParallelAssignment cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
vote :+1: for merging and enabling this cop
vote :-1: for disabling this cop

**Review by ares — COMMENTED** [review]
I don't think this is a good idea. The parallel assignment is often used to indicate the value is temporarly stored elsewhere and will be restore later. What are pros of disabling this?

**Comment by mmoll** [comment]
I find it a tad more understandable in most places, but no hard feelings disabling it.

**Comment by mmoll** [comment]
No real support for that one, disabling.

**Review by ekohl — APPROVED** [review]

**Comment by mmoll** [comment]
bump?

**Comment by ares** [comment]
Thanks @mmoll, merging!

**Pull request merged**
