### PR TITLE
Fixes #15996 - Multiple nav bars

### PR DESCRIPTION
**Pull request by anandkumaragrawal**
Multiple navigation bars (top bar starting with "Default Organization") on screen

In Firebug Console: Uncaught TypeError: Cannot read property 'hide' of undefined

### CODE REVIEW

**Comment by timogoebel** [comment]
[test]

**Comment by dLobatog** [comment]
Can you really reproduce this? The instructions just say go to 'all hosts' and click on a host, which clearly isn't enough to reproduce it.

**Comment by mmoll** [comment]
That's probably the same as http://projects.theforeman.org/issues/15956

**Comment by anandkumaragrawal** [comment]
@dLobatog, Yes i can reproduce that  when Foreman cannot find VM, it is similar to the one as mentioned by @mmoll

**Comment by dLobatog** [comment]
Merged as 42c1cf29ff5702f9d0d483afa084194e7d2a7982, thanks @anandkumaragrawal!

**Pull request closed without merging**
