### PR TITLE
Fixes #35866 - Make RSS notification expire after 1 month

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I know we try to avoid introducing too many settings, but Tomer isn't here anymore. Should this be configurable?

**Comment by ekohl** [comment]
@adamruzicka this may have gotten lost in your queue, but I'll summarize. I don't mind this going in, but before we do I'd like your opinion on whether it should be a setting instead.

**Comment by adamruzicka** [comment]
I did not get that far back in my queue yet. We can make it configurable, but I can't really say I see much value in it

**Comment by adamruzicka** [comment]
Filed an issue to consider making it configurable https://projects.theforeman.org/issues/35907 . Let's keep this one as is for now

**Review by ekohl — APPROVED** [review]
I guess this is better than it was. I also linked up the issues in Redmine using Related issues so it's easier to find.

**Pull request merged**
