### PR TITLE
Fixes #35418 - Update websockify to make noVNC functional

### PR DESCRIPTION
**Pull request by lkthomas**
Go to the web UI: Infrastructure → Compute Resources → (My VM host) → “Virtual Machines” → (My VM and confirmed using VNC instead of SPICE) → Console, I see this error: "The connection was closed by the browser. please verify that the certificate authority is valid", I checked all my certificate setting and from shell confirmed the websockify actually fired properly, it just the web UI didn't function correctly. Somehow to noVNC library on theforeman repo is 2 years old, after updating the code from noVNC/websockify and adjust the libvirt VM to listen all interface, finally web console start working.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I'd prefer to stop vendoring websockify. Instead I'd prefer to use a system package.

**Comment by lkthomas** [comment]
I am new to this, can you provide more insight so I could make the change?

**Comment by lkthomas** [comment]
how about you approve this PR first and make it functional, then we can discuss what we should do to improve it, it's totally broken right now, without this PR it wouldn't work.

**Comment by ekohl** [comment]
> how about you approve this PR first and make it functional

This blows up the repository a lot. I'd rather not.

> I am new to this, can you provide more insight so I could make the change?

I think it mostly comes down to changing the code to look in `$PATH` rather than the vendored location, which is here:
https://github.com/theforeman/foreman/blob/2bdd1979cfedc43106c4af01f93f64e0b790abca/lib/ws_proxy.rb#L66-L68

AFAIK you can just pass a command name and it'll look in `$PATH`.

Then we change packaging to depend on websockify. I can take care of that.

**Comment by ekohl** [comment]
> Then we change packaging to depend on websockify. I can take care of that.

https://github.com/theforeman/foreman-packaging/pull/8421 should be that for RPM. A similar change should also be made for Debian, but that's rather trivial.

**Comment by lkthomas** [comment]
the Ubuntu library could well be outdated as well. Shall we use pip3 to install it as a requirement?

**Comment by ekohl** [comment]
No, using pip is an absolute no-go for production. If anything, we should package it ourselves then.

It looks like both Debian Bullseye and Ubuntu Focal are on 0.9.0 (https://packages.debian.org/bullseye/python3-websockify and https://packages.ubuntu.com/focal/python3-websockify), which I think are new enough.

**Comment by lkthomas** [comment]
Ok I only tested 0.10.0 version, this is also why we should bundle it into the package instead of relying on third party, which, also the intention from the my original PR.

**Comment by ekohl** [comment]
Sorry, but bundling is a no-go. I consider it a historical mistake to have done so in the first place.

**Comment by lkthomas** [comment]
okay, should I close this MR and you can open another one to use the system package?

**Comment by ekohl** [comment]
I've opened https://github.com/theforeman/foreman/pull/9392, but have not tested it yet.

**Pull request closed without merging**
