### PR TITLE
Fixes #25431 - remove hirb-unicode-steakknife gem

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by timogoebel** [comment]
@leewaa: Can you ack? Does that fix the issue for you?

**Review by leewaa — APPROVED** [review]
LGTM

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
@ekohl: Can you please ack and merge?

Just a side note: I thought I had commit right to Foreman but can't merge this and feel very patronized.

**Comment by ohadlevy** [comment]
I guess this is because of code owners? The same happens on every change to
package.json file....

**Review by ekohl — APPROVED** [review]
It is indeed code owners

**Comment by timogoebel** [comment]
Thanks, @tbrisker!

**Pull request merged**
