### PR TITLE
Fixes #6606 - Allow deletion of non-admin users if there's only one admin

### PR DESCRIPTION
**Pull request by daviddavis**
Apologies if this is a dupe but I searched and didn't see anything in redmine/github.

### CODE REVIEW

**Comment by lzap** [comment]
No need to apologize. Reproduced, tested, works for me, unit tests green. Thanks for the contribution.

**Comment by lzap** [comment]
Mind adding one extra test for this?

**Comment by daviddavis** [comment]
@lzap will do.

**EDIT:** Updated with a test.

**Comment by domcleal** [comment]
Thanks @daviddavis, merged as 7096627 for Foreman 1.6.0.

**Pull request closed without merging**
