### PR TITLE
add stale action to replace prprocessor

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I tried my best to translate the logic from https://github.com/theforeman/prprocessor/blob/master/config/close_inactive.yaml and https://github.com/theforeman/prprocessor/blob/master/scripts/close_inactive.rb into `actions/stale`.

Technically, this now gives  week more time as the workflow first marks things as "stale" (after 90 or 30 days) and only then after 7 days closes it. We can fine-tune that, but I didn't feel like it's a bad thing.

It's also explicitly configured to only touch PRs, even if we have issues disabled in this repo.

**Comment by evgeni** [comment]
one thing that this does not do (and can't do too well), is removing the PR from the redmine.

I think that's OK tho?

**Comment by ekohl** [comment]
> one thing that this does not do (and can't do too well), is removing the PR from the redmine.
> 
> I think that's OK tho?

We can implement this in the regular PR processor: when a PR is closed without being merged we can remove the link. That would then also work for manual actions.

**Review by ekohl — APPROVED** [review]

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-infra/pull/1896 - removes the cronjob
https://github.com/theforeman/prprocessor/pull/180 - removes the code

**Comment by ekohl** [comment]
> We can implement this in the regular PR processor: when a PR is closed without being merged we can remove the link. That would then also work for manual actions.

I think https://github.com/theforeman/prprocessor/pull/182 would do that. At this point I haven't tried it out though.

**Pull request merged**
