### PR TITLE
Refs #3809 - Remove Rails/ReadWriteAttribute cop

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
I prefer the more verbose read/write_attribute methods. why do this?

**Comment by ohadlevy** [comment]
@eLobato I tend to agree with @unorthodoxgeek on this one, but it could be that I'm just too used to the current syntax.

**Comment by ares** [comment]
+1 for keeping more verbose variant

also to save you some time I'd prefer if you first create a list of cops that you plan to implement so we can vote beforehand

**Comment by iNecas** [comment]
+1 on @ares proposal, as that was also something I tried to suggest some time ago: deciding once the PR is done has several downsides:
- not everyone is reviewing every PR, so some cops get enabled even if the majority of developers don't agree with it (I wouldn't say one needs to follow all the rules that rubocop offers for the code to be perfect, some cops are even making it worse IMO)
- if the PR gets NACKed, the person to create the PR just lost some time with creating it

Let's have a proper discussion and agreement on what cops to enable before proceeding with opening further PRs

**Pull request closed without merging**
