### PR TITLE
Fixes #25488 - Update Foreman to use fog-vsphere 2.5.0

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
Packaging PR here:
https://github.com/theforeman/foreman-packaging/pull/3214
https://github.com/theforeman/foreman-packaging/pull/3215

**Comment by chris1984** [comment]
@tbrisker can I get a review please

**Review by lzap — APPROVED** [review]
Looks good, I will let @ekohl to finish packaging reviews then this can be merged. Thanks!

**Review by ekohl — APPROVED** [review]
Packaging has been merged.

**Comment by chris1984** [comment]
[test foreman]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test upgrade]

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
