### PR TITLE
Fixes #17284 - Ignore angular router on proxy page

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ohadlevy** [comment]
can't this be fixed in katello code?

**Comment by gailsteiger** [comment]
Why is this even happening?
If this can't be solved at the 'source' what's to prevent the angular router from taking over in another case?

**Comment by xprazak2** [comment]
Seems it can be fixed in [Bastion](https://github.com/Katello/bastion/pull/139) after all.

**Comment by dLobatog** [comment]
Closing due to https://github.com/Katello/bastion/pull/139 - thanks all. Feel free to reopen if the other PR is rejected for some reason

**Pull request closed without merging**
