### PR TITLE
Fixes #21180 - Enable adding 3rd party libraries from plugins

### PR DESCRIPTION
**Pull request by xprazak2**
@waldenraines, this should help with additional dependencies.

1) add package.json to your plugin root
2) add dependencies into package.json
3) run `npm install` **in foreman folder**
4) observe dependencies being installed for all plugins with package.json

Dependencies from plugins can be used in the same fashion as the ones from core

### CODE REVIEW

**Comment by danseethaler** [comment]
I've tested this out with the `react-router-dom` dependency in katello and it worked great! Good work on this @xprazak2!

**Comment by xprazak2** [comment]
Because the `postinstall` task calls `plugin_webpack_directories.rb` to find out what plugins we have, we need to `bundle install` before we `npm install`. I added this step into .travis.yml to pass the tests on Travis.

**Comment by tstrachota** [comment]
I didn't have a chance to do the code review yet, but it worked nicely for me so far :+1:. 
Great addition @xprazak2, thanks!

**Review by waldenraines — APPROVED** [review]
I also tested this out as part of a review of @tstrachota's date work and everything worked fine.

The code looks fine to me so I'll go ahead and approve this from my perspective.

**Comment by tstrachota** [comment]
@xprazak2 there are some conflicts, could you rebase, please?

**Comment by xprazak2** [comment]
I rebased and aligned it with #4924

**Comment by ares** [comment]
[test upgrade] [test foreman]

**Comment by tstrachota** [comment]
Tests green, the code looks good and it works fine
:+1: to merge from my side

**Comment by ares** [comment]
Thanks @xprazak2, merged as 5316000ba8366f240a289f0dbab73ec348dfe72f. Thanks also @tstrachota, @danseethaler and @waldenraines who tested it.

**Pull request closed without merging**
