### PR TITLE
Fixes #25567 - Fix TFTP for RancherOS

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ekohl** [comment]
Could we introduce some test for this? Perhaps a test for every subclass of `OperatingSystem` which calls the public API functions.

**Comment by lzap** [comment]
Hmmm rancheros_provision.erb is mentioned in snapshot test suite (`snapshots.yaml`) but the snap file is actually missing! I am only able to find `test/unit/foreman/renderer/snapshots/ProvisioningTemplate/snippet/rancheros_cloudconfig.snap.txt`. Maybe the test is not correct and when there is a parsing error it silently skips it.

Edit: There are actually two:

```
$ g find Ranch
app/assets/images/RancherOS.png
test/unit/foreman/renderer/snapshots/ProvisioningTemplate/PXELinux/RancherOS PXELinux.snap.txt
test/unit/foreman/renderer/snapshots/ProvisioningTemplate/provision/RancherOS provision.snap.txt
```

**Comment by lzap** [comment]
I can confirm that PXELinux template is actually snapshotted, why it does not fail?

**Comment by tbrisker** [comment]
@lzap i figured out why this wasn't picked up by the snapshots - the snapshot service uses a RH host to generate all the snaps, so it won't catch issues in a specific OS family (https://github.com/theforeman/foreman/blob/develop/test/unit/foreman/renderer/template_snapshot_service.rb#L25)
Opened https://projects.theforeman.org/issues/25613 to track that.
@ekohl - since fixing the snapshot tests will detect other such regressions, would you be ok with merging this as is? I want to get this in 1.20.1 if possible, and won't be able to write tests for it in time.

**Comment by ekohl** [comment]
>  @ekohl - since fixing the snapshot tests will detect other such regressions, would you be ok with merging this as is? I want to get this in 1.20.1 if possible, and won't be able to write tests for it in time.

I guess this is suitable now for a cherry pick

**Review by lzap — APPROVED** [review]
Thanks good catch. I can merge.

**Comment by tbrisker** [comment]
Thanks, 1.20 is f58a31b49

**Pull request merged**
