### PR TITLE
Fixes #28566 - add organizations and locations to http proxy show api

### PR DESCRIPTION
**Pull request by bbuckingham**
Adding organizations and locations to the show/GET API for the
http proxy.  This will be added to the CLI as well and is to
provide consistency with the information shown on the UI.

### CODE REVIEW

**Comment by bbuckingham** [comment]
The CLI change that goes with this one is in : https://github.com/theforeman/hammer-cli-foreman/pull/470

**Comment by bbuckingham** [comment]
The redmine attached to this PR is in the Foreman Hammer CLI project.   If I should create and associate a separate Foreman redmine, please do let me know and I can do that.  Thanks!

**Review by ianballou — DISMISSED** [review]
Worked just fine for me when testing with the related hammer PR.

```
Id:            1
Name:          a proxy
Username:      
URL:           https://proxy.example.com:8080
Locations:     
    Default Location
    Norway
Organizations: 
    Default Organization
```

**Review by mmoll — DISMISSED** [review]

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Comment by tbrisker** [comment]
1.24 - ad6d297a

**Pull request merged**
