### PR TITLE
fixes #2272 Added Capybara intergration tests

### PR DESCRIPTION
**Pull request by isratrade**
- Added folders
  test/integration - for non-javascript tests
  test/integration/js - for javascript tests
- Fixed view titles to be consistent
- Other misc changes to get tests to pass

All current integration tests pass!!

Still more pending tests to add in separate pull requests.

### CODE REVIEW

**Comment by domcleal** [comment]
@isratrade I haven't reviewed the PR itself, but a few observations from running it on Jenkins :)

The tests create temporary Firefox profiles underneath /tmp, I think on each test.  They do seem to get cleared out at the end of the run, but in the meantime we end up with hundreds of 7MB profiles:

```
drwx------ 3 jenkins jenkins 4096 Mar 13 10:13 webdriver-profile20130313-3936-1466vvn
drwx------ 3 jenkins jenkins 4096 Mar 13 10:17 webdriver-profile20130313-3971-11i3rcp
drwx------ 3 jenkins jenkins 4096 Mar 13 10:19 webdriver-profile20130313-3971-1wglstq
drwx------ 3 jenkins jenkins 4096 Mar 13 10:14 webdriver-profile20130313-4067-196ccgh
drwx------ 3 jenkins jenkins 4096 Mar 13 10:22 webdriver-profile20130313-4067-8ug3rw
```

Could you investigate the teardown please to see if the driver isn't clearing these out as soon as the test completes?  I suspect it's using a temp file that Ruby itself is deleting on close.

We run the "jenkins:unit" rake task from Jenkins, but an environment variable flag would be really useful to enable or disable these integration tests as they're so resource intensive.  I was thinking we could then run the tests separately for fewer database/Ruby combinations than we do the main unit tests.

There is one normal functional test failure:

```
  1) Failure:
test_should_destroy_hostgroups(Api::V1::HostgroupsControllerTest) [/var/lib/workspace/workspace/test_develop_pull_request/database/postgresql/label/el/puppet/3.0/ruby/1.9.3/test/functional/api/v1/hostgroups_controller_test.rb:35]:
"Hostgroup.count" didn't change by -1.
<2> expected but was
<3>.
```

The Capybara tests are still running, will let you know the outcome.

**Comment by isratrade** [comment]
@domcleal, here is the standard teardown code in test_helper for Capybara

I fixed the v1/hostgroup failure

```
teardown do
  DatabaseCleaner.clean       # Truncate the database
  Capybara.reset_sessions!    # Forget the (simulated) browser state
  Capybara.use_default_driver # Revert Capybara.current_driver to Capybara.default_driver
end
```

**Comment by domcleal** [comment]
I've fixed the setup on the Jenkins slaves now so they run using Xvfb with a Jenkins plugin, so you can ignore the teardown comment, this seems to have fixed it (I guess it happened as Firefox wouldn't launch).  Using a Jenkins plugin means we don't need the headless gem I proposed either.

It took about 50 minutes to run all the tests, without any other load on our slave, so I think we still need an option to turn it on and off for both Jenkins and developers.

**Comment by isratrade** [comment]
@domcleal rebased and should be ready for merge!

**Comment by isratrade** [comment]
closed. will re-submit pr for 3.2 branch

**Pull request closed without merging**
