### PR TITLE
Fixes #29968 - Upgrade vendor to ^v4.5.0

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
this matches what we currently have in packaging. 
Thanks @sharvit !

**Review by tbrisker — COMMENTED** [review]
Or actually, vendor is at 4.5 in packaging but builder is still at 4.3

**Comment by tbrisker** [comment]
ping @sharvit - this is just missing a bump in packaging to get in and blocking a few other PRs

**Comment by sharvit** [comment]
Thanks @tbrisker,

https://github.com/theforeman/foreman-packaging/pull/5380

**Comment by tbrisker** [comment]
I guess this needs bumping to 4.7 now?

**Comment by sharvit** [comment]
> I guess this needs bumping to 4.7 now?

Closing and creating https://github.com/theforeman/foreman/pull/7744 instead.

**Pull request closed without merging**
