### PR TITLE
Fixes #35817 - Avoid using fixtures for test settings

### PR DESCRIPTION
**Pull request by ekohl**
When running rake snapshots:generate it doesn't load the fixtures. This normally happens in the test setup code, but snapshot generation doesn't use this. This patch uses the settings DSL to set a different default depending on the environment. An additional benefit is that the code is more localized.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Both of the failures are about the setting table being empty IMHO.
One of them easily fixable by just creating the setting tho I'm not sure how to fix the uniqueness test.

**Comment by ezr-ondrej** [comment]
This mixes test code with production code, which I'm generally against, but the benefits you're describing are outweighing the cons here so :+1:

**Review by stejskalleos — CHANGES_REQUESTED** [review]
Looks like failures are related to the changes.

**Comment by stejskalleos** [comment]
Reopening the PR, I'm still having the problem on the develop branch.
@ekohl can you please rebase the PR?

**Comment by jcpunk** [comment]
I think I've got work blocked waiting for this PR

**Pull request closed without merging**
