### PR TITLE
Fixes #30897 - document template parameters (DRAFT)

### PR DESCRIPTION
**Pull request by lzap**
As part of the effort to document template parameters, I have found few copies under a different names. Let's deprecate some and document everything so we have a more consistent experience.

This is a WIP, for the context read:

https://community.theforeman.org/t/help-needed-document-template-parameters-you-know/20595

Tests will fail at this point. I just want to start discussion for now.

### CODE REVIEW

**Comment by lzap** [comment]
Marek has an interesting idea to actually seed those parameters with default values into the database (Parameters model) so when user creates new host, all those Parameters would be ready for override. This could however create a bad UX which could be fixed in the Host Form UI overhaul which is planned.

**Comment by ares** [comment]
Hello @lzap, given this is a draft for a very long time we'd like to know if you have a plan to move this out of the draft in a foreseeable future. Given it was reopened 6 days ago, I assume you plan to get back to it.

If we don't get a reply in 2 weeks, we'll close the PR but it can always be reopened.

**Comment by tbrisker** [comment]
2 weeks have passed, closing. Feel free to reopen when you get back to this.

**Comment by lzap** [comment]
Too much of a bite this one. I am keeping this closed.

**Pull request closed without merging**
