### PR TITLE
Fixes #24003 - remove babel-polyfill from vendor.js

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
When running with production-compiled assets and plugins using webpack (rex and ansible in my case), this fixed the issue of trying to import it multiple times that caused all js to break

**Review by dLobatog — APPROVED** [review]
Merging as this fixes REX. The job invocation page does not load properly without this (if you follow the method to reproduce nightly issues as described here, substitute katello by foreman_remote_execution: https://community.theforeman.org/t/nightlies-assets-are-now-broken/9810/38?u=dlobatog).

Unfortunately I still get `Error: Component not found:  ReportJsonViewer among BookmarkContainer, DonutChart, StatisticsChartsList, PowerStatus, NotificationContainer, ToastNotifications, StorageContainer, PasswordStrength, BreadcrumbBar, FactChart` on the reports page, error coming from  foreman_ansible.

**Comment by dLobatog** [comment]
Thanks @tbrisker

**Comment by ohadlevy** [comment]
could this be order dependent? e.g. making sure it loads and register
before the view?

**Comment by ares** [comment]
Setting redmine release to 1.19, if this needs to be cherrypicked, please update accordingly.

**Pull request merged**
