### PR TITLE
Fixes #9351 - use correct interfaces url for AJAX calls

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@tstrachota could you do the review please since you're familiar with this?

**Comment by tstrachota** [comment]
@ares :+1:
Thanks for fixing it.

**Comment by ares** [comment]
hopefully I didn't break katello tests with this change :-) setting as ready to merge so someone with permission can merge it

**Comment by domcleal** [comment]
[test]

**Comment by ares** [comment]
are failing tests those randomly failing?

**Comment by domcleal** [comment]
Looks like they're happening on quite a few PRs, yeah.  Related to #9138... I wonder if poltergeist could have made it worse under certain conditions, e.g. high slave load.

**Comment by ares** [comment]
so can we ignore it and merge this? or should I retrigger tests until it's green?

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@ares CI is stable after disabling the NIC modal tests

**Comment by dLobatog** [comment]
Merged as ce58db0a5a4da71b65aa8e6601a2c6eea7a5d212, thanks @ares

**Pull request closed without merging**
