### PR TITLE
Fixes #36550 - Add PermissionDenied to reports tab in host

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga, LGTM and fixes the issue:
ScreenShot-1688057723845

Out of the scope: funny thing, I can't find any other usage of `PermissionDenied` component across the organization... But we have a lot of places which show similar message if the permissions are missing, is there a guide or maybe something that tracks unification for such cases? So each plugin should show the same component.

**Comment by ofedoren** [comment]
Test failures are unrelated... still.

**Comment by MariaAga** [comment]
`PermissionDenied` is used in Katello :) 

> But we have a lot of places which show similar message if the permissions are missing,

like where?

**Comment by ofedoren** [comment]
> like where?

https://github.com/theforeman/foreman/pull/9764#issuecomment-1613570599 :)

**Pull request merged**
