### PR TITLE
Refs #25974 - sort uptime facts by freshness

### PR DESCRIPTION
**Pull request by ares**
I expect some tests to fail and tell me, what the order is :-)

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]
Tests? :)

**Comment by ares** [comment]
I was waiting on which test fails, since I know I added one for the ordering by type. And just updated that one, I don't think we need to add a new one. Let's see if it now turns green

**Comment by timogoebel** [comment]
Looks like the test is flakey, see https://ci.theforeman.org/job/test_develop_pr_core/21878/database=mysql,ruby=2.5,slave=fast/testReport/junit/(root)/HostTest___uptime_seconds/test_0003_should_return_uptime_and_based_on_backup_facts_even_if_there_are_multiple_other_facts/

**Comment by ekohl** [comment]
[tset foreman]

**Comment by ares** [comment]
let's see with rebased branch, this should ideally get in for 1.22

**Comment by ares** [comment]
all green now

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @ares.

**Pull request merged**
