### PR TITLE
Fixes #29110 - updated fact parser to handle v3 debian OS (2.0 CP)

### PR DESCRIPTION
**Pull request by lzap**
(cherry picked from commit 5d61c18fa7bdee314ac146ba6b35353c16c63b37)

### CODE REVIEW

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
@lzap please rebase :)

**Comment by mmoll** [comment]
rebased.

**Comment by mmoll** [comment]
:green_heart:

**Review by tbrisker — APPROVED** [review]
Thanks @lzap !

**Pull request merged**
