### PR TITLE
change default order to fact_name

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@isratrade you removed the following line

``` ruby
 scoped_search :on => :value, :default_order => true
```

**Comment by isratrade** [comment]
@ohadlevy.  Yes, because we aren't sorting by value.  I added :default_order => true to the next line :on => :name

**Comment by ohadlevy** [comment]
so, by removing that line, you disable search on value as well,

it should simply be

``` ruby
 scoped_search :on => :value
```

**Comment by ohadlevy** [comment]
maybe a stupid question, but why does this actually solves the problem @abenari do you have an idea?

**Comment by isratrade** [comment]
@abenari can you check if this pull request is ready?

**Comment by isratrade** [comment]
@abenari, can you check this and write @ohadlevy if it's OK.

**Comment by ohadlevy** [comment]
not sure if this is required or if it makes any sense, if required, please reopen

**Pull request closed without merging**
