### PR TITLE
Fixes #26581 - Improve Layout active MenuItems performance

### PR DESCRIPTION
**Pull request by glekner**
Since PF VerticalNav component receives a `activePath` prop, there is no need to handle the active state of each Menu Item inside the items array.
This should also improve performance because there is no need to iterate through the items after each navigation.

### CODE REVIEW

**Review by sharvit — DISMISSED** [review]
Thanks @glekner looks good and works as expected :+1:

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
@glekner note the test failures.

**Comment by glekner** [comment]
tests fixed

**Comment by mmoll** [comment]
[test upgrade]
[test katello]

**Comment by mmoll** [comment]
[test katello]

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @glekner!

**Pull request merged**
