### PR TITLE
refs #35069 - ApplicationRecord.<=> undefined method 'name'

### PR DESCRIPTION
**Pull request by stejskalleos**
In https://github.com/theforeman/foreman/pull/9266 the issue was fixed only partially, it's still failing in same cases, for example when running `foreman_leapp` tests:

```shell
bundle exec rails test:foreman_leapp

Error:
PreupgradeReportTest::#create_report#test_0001_with commands and hints:
NameError: undefined local variable or method `name' for #<JobInvocation:0x0000000013ea4080>
    app/models/application_record.rb:43:in `<=>'
    app/models/concerns/foreman/sti.rb:26:in `save'
    /home/lstejska/projects/foreman_leapp/app/models/preupgrade_report.rb:10:in `create_report'
    /home/lstejska/projects/foreman_leapp/test/models/preupgrade_report_test.rb:18:in `block (3 levels) in <class:PreupgradeReportTest>'
    /home/lstejska/projects/foreman_leapp/test/models/preupgrade_report_test.rb:17:in `block (2 levels) in <class:PreupgradeReportTest>'

Error:
PreupgradeReportTest::#create_report#test_0002_no entries:
NameError: undefined local variable or method `name' for #<JobInvocation:0x00000000141db6e0>
    app/models/application_record.rb:43:in `<=>'
    app/models/concerns/foreman/sti.rb:26:in `save'
    /home/lstejska/projects/foreman_leapp/app/models/preupgrade_report.rb:10:in `create_report'
    /home/lstejska/projects/foreman_leapp/test/models/preupgrade_report_test.rb:26:in `block (3 levels) in <class:PreupgradeReportTest>'
    /home/lstejska/projects/foreman_leapp/test/models/preupgrade_report_test.rb:25:in `block (2 levels) in <class:PreupgradeReportTest>'

39 tests, 73 assertions, 0 failures, 2 errors, 0 skips
```

### CODE REVIEW

**Review by adamruzicka — COMMENTED** [review]
This can give wrong results. Let's say I'm comparing apples to oranges, neither responds to `name`. In this case `apple.try(:name) <=> orange.try(:name)` would be `nil <=> nil` which is `0`, while it should be `nil` as those things are generally not comparable to each other?

To be fair, I'm not sure if that can happen or why rails does this in the first place

**Comment by stejskalleos** [comment]
> This can give wrong results. Let's say I'm comparing apples to oranges, neither responds to name.

Good point, I didn't catch that. But what's the proper fix? Looks like we are expecting that every model that inherits from `ApplicationRecord` has `name` attribute. Maybe we should implement `<=>` on `JobInvocation` model and sort by `created_at` I guess.

**Comment by adamruzicka** [comment]
Could we just return `nil` in case any of the two objects does not respond to `name`?

**Comment by ekohl** [comment]
I also thought about that, but isn't that what `try` does? Then it becomes `nil <=> nil`. On the other hand, what would be sane sorting? You could think about generic fallbacks like comparing the class name and ID/primary key but where does that really happen and is that any better?

**Comment by stejskalleos** [comment]
> Could we just return nil in case any of the two objects does not respond to name?

agree, that would be easiest fix. I also added tests just to be sure

**Comment by stejskalleos** [comment]
Aaand it's green, @adamruzicka @ekohl could you guys do the re-review? It's blocking tests in `foreman_leapp`

**Review by adamruzicka — APPROVED** [review]

**Review by ekohl — APPROVED** [review]

**Pull request merged**
