### PR TITLE
fixes #24561 - adds webpack analyze support

### PR DESCRIPTION
**Pull request by ohadlevy**
to use, simply execute:

```npm run analyze```

### CODE REVIEW

**Comment by ohadlevy** [comment]
output report is something like 
image

**Review by amirfefer — DISMISSED** [review]
Thanks @ohadlevy  works well and great feature !
Test failures related to `enzyme` and should be fixed here #5932

**Comment by ohadlevy** [comment]
rebased.

**Comment by tbrisker** [comment]
can you add it here please so we don't package it: https://github.com/theforeman/foreman-packaging/blob/24358abf5cb6fc8f1ea8549fcd5e42490ffbe4c2/update-requirements#L8-L28

**Comment by ohadlevy** [comment]
@tbrisker added https://github.com/theforeman/foreman-packaging/pull/2846

**Review by amirfefer — APPROVED** [review]

**Comment by ohadlevy** [comment]
@ekohl can you please approve the PR? thanks.

**Review by tbrisker — APPROVED** [review]
Thanks @ohadlevy !

**Pull request merged**
