### PR TITLE
Fixes #35151 - Add CentOS Stream 9 installation medium

### PR DESCRIPTION
**Pull request by Dyrkon**
CentOS Stream 9 installation medium added.

### CODE REVIEW

**Comment by stejskalleos** [comment]
ok to test

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected.

**Comment by stejskalleos** [comment]
Thanks @Dyrkon !

**Comment by upadhyeammit** [comment]
cped for 3.4-stable c7b7aaa5f7afef8a72e1e686ce1f0fa5856d01e6

**Pull request merged**
