### PR TITLE
Fixes #31526 - ConfigReports chart clicks

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Config Reports charts were falsly clickable.
This charts do not have any search url, so this makes them not clickable.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I can't quite tell, but are these the ones on the dashboard? If so, I'd like them to actually get fixed. See https://projects.theforeman.org/issues/24351 for the regression I reported for that about 2 years ago.

**Comment by ezr-ondrej** [comment]
> I can't quite tell, but are these the ones on the dashboard? If so, I'd like them to actually get fixed. See https://projects.theforeman.org/issues/24351 for the regression I reported for that about 2 years ago.

Nope, that's different one, these are charts in config report view. But I can take a look into that, I agree it's quite useful!

**Comment by ezr-ondrej** [comment]
Can be closed if #8210 is merged.

**Review by tbrisker — DISMISSED** [review]
Thanks @ezr-ondrej !

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej ! merging, core tests were already green before.

**Comment by tbrisker** [comment]
2.3 - feca7075f

**Pull request merged**
