### PR TITLE
Fixes #6865 - display notifications below navbar

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by shlomizadok** [comment]
Shouldn't this be overridden elsewhere and not in the vendor css?

**Comment by tbrisker** [comment]
@shlomizadok generally, that would be true, but this scss is only loosely based on the original vendor's code so I think this should be fine. 
In any case, we should eventually replace this old, dead library (no updates in 2 years) with https://www.patternfly.org/patterns/toast-notifications/, I opened [an issue](http://projects.theforeman.org/issues/14178) to take care of that.

**Comment by shlomizadok** [comment]
:+1:

**Comment by dLobatog** [comment]
I'd suggest closing this as no fix. The top-right corner is _the place_ for these notifications to be, moreover you cite Patternfly guidelines which recommend that. Selenium should close these dialogs as users would have to do the same.

It looks odd to move all notifications down too - http://i.imgur.com/AZBddgh.png

**Comment by lzap** [comment]
Putting testing things aside, the fact it blocks you for several seconds from clicking on Administer menu is _super annoying_ and I vote for moving it below a bit. If this is recommended in Patternfly, then it's a bug in their design and it must be fixed.

**Comment by tbrisker** [comment]
@kybaker - thoughts about this? I agree with @lzap that it is annoying to have notifications block the nav bar menus.Wouldn't it make sense to have them pop up just below the menu?

**Comment by ohadlevy** [comment]
@tbrisker giffi? :)

**Comment by kybaker** [comment]
@tbrisker - This was a subject of debate when designing https://www.patternfly.org/patterns/toast-notifications/. The result was having the notification overlay the content was much more disruptive than the menu. Also the top left overlay is a more traditional expected interaction. It seems the trouble comes when there is the inability to close the message in combination with abundance of unimportant messages. I suggest using the PatternFly Toast Notifications as-is.

**Comment by tbrisker** [comment]
@kybaker AFAICT this does not overlay the content in any page, all pages have a header and the notifications fit nicely in that space. 
before:
a
After:
b
(still needs a small change so it appears under the menu)

**Comment by lzap** [comment]
Thanks for the screenshots - it looks like even if we move it down a bit, you are still not able to utilize all the menuitems as it stills overlays first few items. If that's true, I don't think it is worth changing.

**Comment by tbrisker** [comment]
@lzap that can easily be fixed by adjusting the z-index, I will do that if we agree this change is good. 
Not sure which would be better from the UX point of view, this was originally raised by QA which hit it during attempted automation for logging out (failed because menu was not visible). 
It seems like we can have the notification below the menu and above content when it's just one line, but longer notifications might cover up the buttons which would be just as problematic.

**Comment by tbrisker** [comment]
I'm going to close this as wontfix. We should move to patternfly toast notifications but that will be a separate fix.

**Comment by lzap** [comment]
How about to hide it the moment you hover with mose over it? This way we are not breaking Patternfly layout...

**Comment by dLobatog** [comment]
Not worth the trouble IMO, moreover from time to time users might want to copy stuff from the notification, I certainly do it sometimes.

**Pull request closed without merging**
