### PR TITLE
Fixes #23859 - Fix queue orchestration compute

### PR DESCRIPTION
**Pull request by tristanrobert**
Hello,

as you asked me for, here is the PR intended to fix the #23859 bug I have submitted to you.
This fix could help me to develop my [foreman-proxmox](https://github.com/tristanrobert/foreman_proxmox) plugin.
I am pleased to help you.

### CODE REVIEW

**Comment by timogoebel** [comment]
Thanks for this, please also incorporate the changes to `vm_exists?` (and the respective tests) from https://github.com/theforeman/foreman/pull/5569/files into this commit. Thanks.

cc: @leewaa

**Comment by mmoll** [comment]
ok to test

**Comment by mmoll** [comment]
Untested, but looks good visually.

@tristanrobert @timogoebel What are the actual (user facing) consequences of this issue with the current code (which, AFACT is in effect since 1.15)?

**Comment by tristanrobert** [comment]
This PR could be seen as refactoring only. Using it could ease to understand the code, but it does not change actually its features.
So it's up to you to merge it or not.

My actual issue still remains.
Indeed, to know if a vm is to be created, foreman uses vm_exists? from app/models/concerns/orchestration/compute.rb which uses persisted? from app/models/concerns/fog_extensions/model.rb which uses !!identity from fog.
My issue is that [proxmox](https://pve.proxmox.com/pve-docs/api-viewer/index.html) requires vmid to be submitted by the client in order to create a new vm.
So if I use vmid as identity of compute object, my vm will always be persisted to foreman and it never could create a new vm in proxmox this way.
If I can't find a way to change identity in [fog-proxmox](https://github.com/fog/fog-proxmox) gem, I may need a new implementation of the persisted? method.
I will tell you when I find a good solution.

**Review by timogoebel — APPROVED** [review]
Thanks, looks good. I concur this is a cosmetic change only. I believe it's important, though as it already caused a lot of confusion. Thanks.

**Comment by timogoebel** [comment]
> My issue is that proxmox requires vmid to be submitted by the client in order to create a new vm.
> So if I use vmid as identity of compute object, my vm will always be persisted to foreman and it never could create a new vm in proxmox this way.

@tristanrobert: From a quick glance you should be able to overwrite `persisted?` for proxmox either via a concern in your gem (that is foreman_proxmox, see https://github.com/theforeman/foreman-digitalocean/blob/d41cafbf406283535c43d3c00b203973402661fd/lib/foreman_digitalocean/engine.rb#L37-L38 for an example) or in fog directly. The concern you mentioned (app/models/concerns/fog_extensions/model.rb) should not be included by default. Are you sure this is the method foreman uses for proxmox?

But let's move this discussion somewhere else please, e.g. an issue in your gem. Ping me if you want, happy to help if I find the time.

**Comment by timogoebel** [comment]
@tristanrobert: Another sidenote: I'd love to see the inline cache invalidation in Foreman core so other compute resources can make use of this. :-)

**Comment by mmoll** [comment]
allright, let's bring this to develop without cherry-picking down then :+1:

**Comment by mmoll** [comment]
merged, merci @tristanrobert!

**Pull request merged**
