### PR TITLE
fixes #5197 Preallocated disk support for ovirt.

### PR DESCRIPTION
**Pull request by leon-strong**
Have tested this on my ovirt instance,  if someone else could verify also - doing this pull request as i really want this to get into the next release.

### CODE REVIEW

**Comment by leon-strong** [comment]
this was based on #1462

**Comment by mmoll** [comment]
[test]

**Comment by lzap** [comment]
Hello, thanks for your contribution. Spinning up my Foreman to test this out.

**Comment by lzap** [comment]
UI

I dont like the UI, can you do a simple check box Thin provisioning instead? Or maybe we can keep the dropdown but change the label to "Allocation" @ohadlevy ? I am not sure if there is a third option, if not, I'd recommend to go with simple checkbox.

Second, thin provisioning should not be the default value. We should stick with the safest option which is full preallocation.

And the last point - when I select Thin provisioning, I still see the volume as Preallocated.

**Comment by ohadlevy** [comment]
@lzap I agree, most likely a simple radio button or checkbox would suffice.

**Pull request closed without merging**
