### PR TITLE
Fixes #9593 - replace .all.map(&:<attr>) with .pluck(:attr)

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
@unorthodoxgeek Could you review this one?

**Comment by unorthodoxgeek** [comment]
Sure

**Comment by unorthodoxgeek** [comment]
looks good to me. go for a merge :+1:

**Comment by domcleal** [comment]
This needs testing on an SCL installation, as Rails 3.2.8 (which we use there) has difficulty with `.pluck(:foo)` when the table name isn't specified and there's a join (which there might be due to default scoping).  Perhaps add the table names in too, to be sure it works?

**Comment by tbrisker** [comment]
[test] random jenkins timeout

**Comment by dLobatog** [comment]
@tbrisker @domcleal I'm going to check how tests go in 3.2.8, will merge if OK.

**Comment by dLobatog** [comment]
Merged as 9e3125880132b3c11bafe9ba24e39a20a6be6a85, thnanks @tbrisker !

**Pull request closed without merging**
