### PR TITLE
Fixes #20657 - make proxy labels bold

### PR DESCRIPTION
**Pull request by ares**
before:
before
after:
after

should be coordinated with plugins PRs

### CODE REVIEW

**Comment by ares** [comment]
related PRs:
* https://github.com/theforeman/foreman_openscap/pull/278
* https://github.com/Katello/katello/pull/6911

**Comment by ares** [comment]
@Rohoover this is based on your suggestion, any comments?

**Comment by Rohoover** [comment]
A few changes:
1) Can we change that reload/refresh/revert icon to a button?
2) For "Failed Features" - What would go here? I don't think it should be left blank.
3) Can we change the labels to title case... "Failed features" = "Failed Features"

smartproxyv1

**Comment by ares** [comment]
@Rohoover I did changes in separate PRs keep discussion on every change isolated. This PR only addresses labels being bold. So the main question for this PR - ACK for bold labels?

For other items you suggested please see following PRs

> Can we change that reload/refresh/revert icon to a button?

https://github.com/theforeman/foreman/pull/4761

> For "Failed Features" - What would go here? I don't think it should be left blank.

already fixed by https://github.com/theforeman/foreman/pull/4762

> Can we change the labels to title case... "Failed features" = "Failed Features"

I can do that, should I change all labels then? E.g. "Configuration Status", "Active Features", "Hosts Managed"? I would send a separate PR for this.

**Comment by Rohoover** [comment]
@ares 
Thanks for clarifying. Bold looks good! Thanks!

**Review by dLobatog — APPROVED** [review]
Thanks @ares & @Rohoover

**Pull request merged**
