### PR TITLE
Fixes #13519 - Alias lookupkey key to parameter

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by orrabin** [comment]
@shlomizadok I'm not sure what's better - alias or rename.
Using rename might break the api (if someone is searching by key) but alias causes the api to show both `key` and `parameter` (also `puppetclass` and `puppetclass_name`).
Not breaking the api is probably the better solution but I'm still mentioning this in case someone knows how to fix it.

**Comment by orrabin** [comment]
Test failure is unrelated, I'm keeping this open to see if anyone has comments on how to fix the 2 options in the ui, if there is no solution I'd rather this goes in as is then brake the api.

**Comment by ekohl** [comment]
I agree we shouldn't break the API. We should deprecate it and wait at least 1 release to remove it.

**Comment by dLobatog** [comment]
@orrabin By 2 options in the UI, you mean the alias and the original name in the API GET response right? I think that's fine, in fact better than breaking the API.

**Comment by ekohl** [comment]
@dLobatog I think @orrabin means that in the search completion it will suggest both options. Personally I think that's fine - some users may in fact already be using key= searches and can have bookmarks.

**Comment by shlomizadok** [comment]
I don't see the problem. We're adding an alias. We're not breaking or changing existing calls - unless I'm missing something?

**Comment by orrabin** [comment]
@shlomizadok the issue was should we add a deprecation warning and later remove the old search options (and change alias to rename) to avoid having 2 ways to search on the same field.

**Comment by shlomizadok** [comment]
@orrabin - I don't think we should deprecate. I think it's fine to leave both original and alias

**Comment by ekohl** [comment]
I think we should deprecate. As a python developer I'd like to quote [PEP-20 (Zen of Python)](https://www.python.org/dev/peps/pep-0020/):

> There should be one-- and preferably only one --obvious way to do it.

**Comment by tbrisker** [comment]
@ekohl As a former Pythonista I sympathize, however:

> **Yukihiro Matsumoto:** Ruby inherited the Perl philosophy of having more than one way to do the same thing. [<sup>1</sup>](http://www.artima.com/intv/rubyP.html)

:+1: to alias.

**Comment by orrabin** [comment]
[test]

**Comment by orrabin** [comment]
merged as 9734f1f395b38a5b4920086bb287ea5857704df3, thanks @shlomizadok !

**Comment by shlomizadok** [comment]
Congrats on your first merge, @orrabin !! :100:

**Pull request closed without merging**
