### PR TITLE
Fixes #4596 - change parent of hostgroup

### PR DESCRIPTION
**Pull request by dLobatog**
Still a few things to polish up, such as the `_parameters` template, which should not require an explicit mention of `@hostgroup` since its used in other models.

Also this needs some testing. If anyone knows any cleaner way of doing this, I'd be glad to hear it.

### CODE REVIEW

**Comment by isratrade** [comment]
@eLobato, the parent of a hostgroup is still disabled in the form. You need to remove the line below from `select_f f, :parent_id` in `app/views/hostgroups/_form.html.erb`

``` ruby
  :disabled => !@hostgroup.new_record?,
```

You probably deleted this on your local dev box.  Otherwise, fixing this issue is really hard :-)

After I enabled the parent select box, the pupppetclass tab did not update after I changed the parent.

**Comment by dLobatog** [comment]
a

Is this the expected behavior? (wait for the gif to load)

**Comment by isratrade** [comment]
It looks good, except for the user experience. When you edit hostgroup 'sparedani' by selecting parent 'castor', the javascript/ajax should populate the environment, puppet ca, puppetmaster select boxes with 'Inherited from Parent (value)' and the Puppet Classes should also be populated with the inherited classes from 'castor'.

**Comment by dLobatog** [comment]
Rebased with latest develop, ping @isratrade ?

**Comment by isratrade** [comment]
@eLobato, I changed a parent hostgroup but the puppetclasses didn't update. I assume it may be because of an error in my logs

```
  GroupParameter Load (0.4ms)  SELECT "parameters".* FROM "parameters" WHERE "parameters"."type" IN ('GroupParameter') AND "parameters"."reference_id" IS NULL AND "parameters"."id" IN (434, 435) ORDER BY parameters.name
not found: Couldn't find GroupParameter with ID=434 for Hostgroup with ID=
```

**Comment by dLobatog** [comment]
@isratrade Sorry, I forgot to update this PR with the latest local branch, which had a lot more of code than the original one. It's updated now, thanks for reviewing

**Comment by isratrade** [comment]
@eLobato, looks good but some issues.
1) when editing existing hostgroup and change parent to blank, there is a 404 error
2) when creating new hostgroup (or nest), and selecting parent hostgroup, there is a 404 error.

**Comment by isratrade** [comment]
@eLobato, when reviewing this PR, I may have discovered 2 more bugs. Please confirm that then I'll enter into Redmine.
1) hostgroup parameters are not inheriting on all descendants.  @ohadlevy, do you recall this. afair, this is just a UI issue as the parameters show up ok in yaml output.
2) `blank_or_inherit_f` is returning wrong inherited value.
       ex. if parent hg environment is "production", the child drop-down list will show "Inherit parent (production)". However, if I overwrite child to be "development", after I save and re-edit, the blank select is "Inherit parent (development)"

**Comment by ohadlevy** [comment]
@isratrade i think that 1) is just a UI bug. (using wrong method to grab the parameters in the view?

**Comment by dLobatog** [comment]
@isratrade 404s are fixed now, I also fixed a bug we had for a long time that allowed setting the current node, and its descendants as parents of themselves, which doesn't make sense.

**Comment by dLobatog** [comment]
@isratrade also, 1) is an UI issue, 2) I can't replicate the issue with the steps you mentioned, after saving the hostgroup the environment is 'development' instead of 'inherit development'

**Comment by isratrade** [comment]
lgtm +1, no errors when playing with difference scenarios of changing parent. I did encounter a bug that's not connected with your PR and will add to redmine.  Validation errors on hostgroup parameters are not shown.

**Comment by isratrade** [comment]
@ohadlevy, @domcleal, are you comfortable with me merging this PR? Do you want to test it first?

**Comment by domcleal** [comment]
I won't test it, but you can merge if you're happy.

My only concerns after a quick scan read are:
a) some taxonomy context code added to methods, but please ensure that this doesn't affect Foreman when taxonomies are disabled (should be no taxonomy related DB queries etc)
b) no tests for model methods
c) commit message should be one line

**Comment by dLobatog** [comment]
I've just rebased this, anything blocking this from being merged?

**Comment by isratrade** [comment]
@eLobato, strange, the parent hostgroup select box is now disabled. It seems something must have changed since the last time I reviewed this.

**Comment by dLobatog** [comment]
@isratrade Indeed, the fact this magically shrank to a 4 files PR was a dead giveaway, I think something went wrong when I rebased, now it should be good, please take another look.

**Comment by isratrade** [comment]
@eLobato, two things I've noticed so far while checking
1) after parent is changed, the multi-select js widget on locs/orgs reverts to not being a widget
2) inherit parent (parent value) - if "child" value is selected, the blank option should be "inherit parent (parent value)" but it is "inherit parent (child). I hope that makes sense. 

@domcleal, I tested it locally with taxonomies disabled and it looks fine.

**Comment by dLobatog** [comment]
@isratrade 1) I should fix that , 2) I see 'Inherit parent "some inherited value"' as the blank option, could you tell me how to replicate what you got?

**Comment by isratrade** [comment]
I now see that the "inherit parent" issue seems to be a bug unrelated to your PR. Here's how to reproduce. Edit any hostgroup, any field that inherits and is null, the value is 
1) value is nill - droplist shows options:  inherit parent (parent value), option1, option2
2) select option1 - droplist shows options:  inherit parent (option1), option1, option2.

The value (inside the parenthesis) show not change, but it does. I assume a separate bug can be opened to solve this if it's not trivial.

**Comment by dLobatog** [comment]
Fixed the problem with the taxonomies box. for the other problem, sorry I still can't reproduce it, I get "inherit parent (no value)", when it inherits empty values.

**Comment by dLobatog** [comment]
Ping?

**Comment by isratrade** [comment]
@eLobato, looks good. I see that you fixed the UI bug (http://projects.theforeman.org/issues/3014) which didn't display the inherited parameters. Thanks! Btw @domcleal, I see this 3014 redmine bug was already closed. It was only a UI bug. The yaml was always right.

**Comment by isratrade** [comment]
merged as e14b6968afc277a1b461974bbb37c02319c04bc2. thanks @eLobato !

**Pull request closed without merging**
