### PR TITLE
Refs #23350 - Robotello tests attr - Role

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
GH-5830 minus the one test that had comments.

**Comment by mmoll** [comment]
[test foreman]
[test katello]

**Comment by mmoll** [comment]
test failures unrelated :green_heart:

**Comment by tbrisker** [comment]
@mmoll thanks for bringing these tests back! I believe we agreed in the discourse discussion there is no need to add the `test_attributes`, care to remove them while you're at it?

**Comment by mmoll** [comment]
@tbrisker sure, removed. :scissors:

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
