### PR TITLE
Fixes #11237 - documenting hostgroup association to compute profile

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by dLobatog** [comment]
Merged as 0e082559b9474ead25de795f36e03f15a5fdb307, thanks @orrabin!

**Comment by omaciel** [comment]
Hi @orrabin did you have any unittests for this change? Just wondering how much functional test will be required for this change.

**Comment by dLobatog** [comment]
@omaciel None afaik, this is just docs. Hammer might want to test it.

**Comment by orrabin** [comment]
@omaciel I tested locally with hammer. As @eLobato said I only changed the docs, the update was working through the api directly it just couldn't be seen in hammer.

**Pull request closed without merging**
