### PR TITLE
Fixes #35536 - Template input_resource macro & preview error

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ofedoren — APPROVED** [review]
Thanks, @stejskalleos, works for me. Although we provide zero (`""`) info instead of at least something (`"$USER_INPUT[organization]"`).

Also, looking at the issue I can understand why `input_resource('organization').title` wouldn't work, but I don't understand how did you get `nil` for `input_resource` which will always return that `"$..."` string...

**Comment by stejskalleos** [comment]
> but I don't understand how did you get nil for input_resource which will always return that "$..." string...

@ofedoren That's simple, try to run job with input_resource. When you are redirected to the job invocation detail, you will see the template preview error. After page refresh it will disappear and everything works as usual.

**Comment by ofedoren** [comment]
Well, I'm OK with merging this as a workaround, but I think the actual fix for this would be revisiting REX plugin, since it's kinda related to how the `template_input_values` are created (I've noticed that it makes `input_resource` to return resource's id instead of actually the activerecord object) or create a specific resolver for such inputs (something like `InputType::UserInput::ResourceInput::Resolver`).

**Comment by stejskalleos** [comment]
@ofedoren I created https://projects.theforeman.org/issues/35671 for the REX change

**Review by ofedoren — APPROVED** [review]
@stejskalleos, okay then, let's get this in. Hopefuly someone will revisit that ticket in the future :)

**Pull request merged**
