### PR TITLE
Fixes #29350 - Fix Layout/EmptyLineAfterGuardClause cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
No hard feelings about that one, feel free to downvote ;)

**Comment by tbrisker** [comment]
@theforeman/core please vote :)

**Comment by lzap** [comment]
Hate this one with all my heart.

**Comment by tbrisker** [comment]
looks like no strong consensus on this one, let's disable it

**Comment by timogoebel** [comment]
5 vs 2  - looks like we should enable it!

**Comment by lzap** [comment]
I like this style and I follow it, however I think enforcing it is not good. There are some cases I intentionally break it. Don't want to block anything, if you feel you need it then just do it.

**Comment by tbrisker** [comment]
5-4 now :) let's disable

**Comment by mmoll** [comment]
Disabled.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
