### PR TITLE
Fixes #18986: upgrade patternfly-sass to 3.23.0.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/18986

### CODE REVIEW

**Comment by waldenraines** [comment]
I'm assuming this is a false positive?

http://ci.theforeman.org/job/test_develop_pr_core/12578/database=postgresql,ruby=2.4,slave=fast/testReport/junit/(root)/HostsControllerTest/test_0070_select_multiple_action_with_valid_host_ids_param_should_return_a_selection_page/

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
Anyone know why this unrelated failure is happening?

http://ci.theforeman.org/job/test_develop_pr_core/12578/database=postgresql,ruby=2.4,slave=fast/testReport/junit/(root)/HostsControllerTest/test_0070_select_multiple_action_with_valid_host_ids_param_should_return_a_selection_page/

**Comment by ohadlevy** [comment]
@waldenraines I believe this will be fixed by #4404

**Comment by tbrisker** [comment]
Thanks @waldenraines

**Pull request merged**
