### PR TITLE
[WIP] - using webpack partial loading to not include brace on every page load.

### PR DESCRIPTION
**Pull request by ohadlevy**
before
```
                             Asset       Size  Chunks                    Chunk Names
    bundle-bd6d20c219f363d8d582.js     162 kB       0  [emitted]         bundle
    vendor-5836403a12b6bcadb31e.js    3.82 MB       1  [emitted]  [big]  vendor
   bundle-bd6d20c219f363d8d582.css      72 kB       0  [emitted]         bundle
bundle-bd6d20c219f363d8d582.css.gz    13.9 kB          [emitted]
 bundle-bd6d20c219f363d8d582.js.gz    43.4 kB          [emitted]
 vendor-5836403a12b6bcadb31e.js.gz    1.22 MB          [emitted]  [big]
                     manifest.json  216 bytes          [emitted]
```

after
```
                             Asset       Size  Chunks                    Chunk Names
                   brace.bundle.js    1.39 MB       0  [emitted]  [big]  brace
    bundle-ad8a3786dfbd55767f1e.js     163 kB       1  [emitted]         bundle
    vendor-1b851a04dcf2a7d4fd9c.js    2.43 MB       2  [emitted]  [big]  vendor
   bundle-ad8a3786dfbd55767f1e.css      72 kB       1  [emitted]         bundle
bundle-ad8a3786dfbd55767f1e.css.gz    13.9 kB          [emitted]
 bundle-ad8a3786dfbd55767f1e.js.gz    43.7 kB          [emitted]
                brace.bundle.js.gz     355 kB          [emitted]  [big]
 vendor-1b851a04dcf2a7d4fd9c.js.gz     860 kB          [emitted]  [big]
                     manifest.json  248 bytes          [emitted]
```

this pr doesn't fully work yet, so ymmv

### CODE REVIEW

**Comment by ohadlevy** [comment]
this works with webpack as a proxy, not in the default current dev configuration (see https://community.theforeman.org/t/using-webpack-infront-of-rails-in-development/9658 for context) not sure yet why.

**Comment by ekohl** [comment]
I haven't looked at the details or practical issues, but I like the idea. Not sure I'll have a lot of time to experiment with this though. At least this week I won't.

**Comment by tstrachota** [comment]
@ohadlevy I was able to get async chunk loading in our default setup by changing the public path to a full url in my dates PR: https://github.com/theforeman/foreman/pull/5184/files#diff-a58d55bdb5770c78ad512f8e91f8d051R39

**Pull request closed without merging**
