### PR TITLE
Fixes #7483 - Use hidden input value to hold raw template contents

### PR DESCRIPTION
**Pull request by sodabrew**
Store the in-progress template in the value of a hidden input tag rather than the text content of a hidden div tag.

### CODE REVIEW

**Comment by sodabrew** [comment]
I also updated `IE_diff_mode` by replacing `$(#new).contents().text()` with `$(#new).val()`. I don't have means to test this easily, though.

**Comment by sodabrew** [comment]
@domcleal Would it be better to target `develop` instead of `1.6-stable`?

**Comment by domcleal** [comment]
Ah yes, please send the PR to develop and then we'll cherry pick it for release.  Sorry, hadn't noticed that.

**Comment by sodabrew** [comment]
Rebased the branch and opened new PR at #1778.

**Pull request closed without merging**
