### PR TITLE
Fixes #24619 - handle Rails env in db:create

### PR DESCRIPTION
**Pull request by iNecas**
This is a change needed for migration to Rails 5.2

### CODE REVIEW

**Comment by iNecas** [comment]
@mmoll I've extended the check on `db:drop` as well.

Test failures from previous run were unrelated, as they are failing in develop as well https://ci.theforeman.org/view/Core/job/test_develop/3676/

**Review by mmoll — APPROVED** [review]
while katello tests still fail, this should be fine :+1:

**Comment by iNecas** [comment]
We actually need this PR to get in first before we fix the rest of Katello tests.

**Comment by mmoll** [comment]
yes, I guess there's still something to do on the Jenkins side...

**Comment by mmoll** [comment]
merged, díky @iNecas!

**Pull request merged**
