### PR TITLE
fixes #3243 non-required/Slow SQL queries on host show page

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: this is all good, but I wonder if you'd like to go further?

I see three queries to pull back reports on host show, which are all doing `h.reports.recent(7)`:

```
Report Load (0.2ms)  SELECT status FROM "reports" WHERE "reports"."host_id" = 65 AND (reported_at > '2013-10-08 12:30:38.672887') ORDER BY reported_at
Report Load (0.2ms)  SELECT "reports".* FROM "reports" WHERE "reports"."host_id" = 65 AND (reported_at > '2013-10-08 12:30:40.239651') ORDER BY reported_at
Report Load (0.2ms)  SELECT "reports".* FROM "reports" WHERE "reports"."host_id" = 65 AND (reported_at > '2013-10-08 12:30:40.242262') ORDER BY reported_at
```

Clearly reports must be one of the slower parts of the page, so could we cache this lookup somewhere?  Even the database or AR query cache won't help here, since the reported_at timestamp is slightly different since it's based off of the current timestamp at each of the three calls.  Three separate hosts_helper methods use the same query: reports_show, runtime_chart, resources_chart.

**Comment by ohadlevy** [comment]
@domcleal I'll look into it unless you'll beat me to it... we can do a few more optimizations like:
- move graphs to ajax
- move VM info to ajax (just like BMC)
  ...

TBH: We should spend more time on performance  (at least for popular actions)

**Comment by domcleal** [comment]
I think the graphs would be less of a problem if we have to pull the last 7 days back anyway for the Metrics tab, but generally agreed.

Let me know if you want to keep this as-is and do this separately.

**Comment by ohadlevy** [comment]
:+1 to merge as is for now.

**Comment by domcleal** [comment]
Okay, merged as 577ecc2 for Foreman 1.3.1 and filed the reports stuff as [#3265](http://projects.theforeman.org/issues/3265).  Thanks @ohadlevy!

**Pull request closed without merging**
