### PR TITLE
Fixes #16681 - error creating config_group ActiveModel::ForbiddenAttr

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by domcleal** [comment]
Please address the feedback from @theforeman-bot. Rather than state an error message, the commit message should state what's changed, e.g. `use strong params in config groups API`.

**Comment by domcleal** [comment]
If you change a pull request in future, please add a comment so the reviewer knows that it's been updated and what's changed.

**Comment by domcleal** [comment]
I think this will also require `wrap_parameters` to be defined in the controller using the accessible_attributes method from the parameters helper.

With this PR, creating a config group with an _unwrapped_ hash containing puppetclass_ids/names fails to associate any classes. This would have worked prior to strong parameters as both associations were listed as accessible attributes.

**Comment by ranjan** [comment]
@domcleal Creating config group with puppet_classes is working as expected. Added test which includes  puppet_classes.

**Comment by domcleal** [comment]
This doesn't appear to fix the issue I described with _unwrapped_ requests - it will need a wrap_parameters statement to fix I think. Your test only tests a wrapped request.

**Comment by ranjan** [comment]
Thanks @domcleal,  got the difference between wrap and unwrapped parameter :). Updated PR

**Comment by domcleal** [comment]
Merged, thanks @ranjan.

**Pull request merged**
