### PR TITLE
Fixes #16614 - Humanize Audit class name

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
[test hound]

**Comment by shlomizadok** [comment]
[test houndci] or [test hound] ?

**Comment by shlomizadok** [comment]
[test] then ?

**Comment by dLobatog** [comment]
@shlomizadok I think they're having internal problems, it's been failing a little bit today on other PRs.

**Comment by dLobatog** [comment]
Thanks @shlomizadok ! 

PS I realized this needs translating right after clicking the button, will follow up this myself, don't worry

**Comment by shlomizadok** [comment]
@dLobatog - Thanks. I do not think that a class name needs translation. It is translated at the [Permission model](https://github.com/theforeman/foreman/blob/develop/app/models/permission.rb#L15-L17)

**Pull request merged**
