### PR TITLE
Fixes #24556 - correct puppet origin detection

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by tbrisker** [comment]
@bastilian - since you wrote the code, can you please take a look?

**Comment by bastilian** [comment]
@ares will a matching source always be last in puppet reports? Would it make sense to collect all sources' items and check them all for a "Puppet" source and not rely on one single item? It would also avoid issues where the order of items could be random.

**Comment by ares** [comment]
> @ares will a matching source always be last in puppet reports? Would it make sense to collect all sources' items and check them all for a "Puppet" source and not rely on one single item? It would also avoid issues where the order of items could be random.

I never saw a report that would have different or random order, the "Puppet" resource represents the puppet run, which should always be last. I fixed the problem for me and the reporter also confirmed it fixes the issue for him. Since reports can be pretty long, I would prefer to just look at last until we know we need to check all logs.

**Comment by bastilian** [comment]
> Since reports can be pretty long, I would prefer to just look at last until we know we need to check all logs.

@ares Totally agree, just wanted to make sure.

Codewise a :+1: from me then, @tbrisker.

**Review by tbrisker — APPROVED** [review]
Thanks @ares and @bastilian !

**Comment by tbrisker** [comment]
Cherry-picked to 1.19-stable as 3bcbda5fdfeace9d7219ef17ff7dfaff57353915, please open a CP pr for 1.18-stable as well if you want to get this into 1.18.2

**Pull request merged**
