### PR TITLE
Refs #16074 - Load .env when not running a Procfile

### PR DESCRIPTION
**Pull request by xprazak2**
Loads .env file when Webpack is started from node_modules/.bin

### CODE REVIEW

**Comment by xprazak2** [comment]
[test foreman]

**Comment by domcleal** [comment]
Can you move the `bindOn` and `require('dotenv')` into the dev server setup block, near the bottom? I think this will reduce the dependencies needed when using webpack in production mode, as the BIND environment var isn't required there.

**Comment by domcleal** [comment]
Oh, please also rebase the branch when you update it to ensure tests pass with the fix from #16599.

**Comment by domcleal** [comment]
Merged as b831082, thanks @xprazak2.

Please do add a comment when changing a PR to say what's changed.

**Pull request closed without merging**
