### PR TITLE
Fixes #23776 - Remove deprecations for 1.18

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I didn't see that GH-5638 was not against develop, cherry-pick to it, also.

**Review by xprazak2 — APPROVED** [review]
LGTM

**Comment by timogoebel** [comment]
@mmoll, @xprazak2: I believe this should have been removed in 1.20, not 1.18. Can we please add this again?
`notice()` was deprecated in 1.18, so we should keep it two more versions and not remove it in 1.18.

**Comment by mmoll** [comment]
@timogoebel It was marked for removal with 1.18, but yes, the 1.18 note was added in cf94f62eb, which is only part of 1.18.

I'll open a PR to correct this.

**Pull request merged**
