### PR TITLE
Fixes #26235 - Check for path in webpacked plugins

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Fixes failures in test env: 
https://ci.theforeman.org/job/foreman_ansible-pull-request/302/database=postgresql,label=fast,ruby=2.5/testReport/junit/(root)/HostIntegrationTest__clone%20page/test_0001_clones_lookup_values/

**Comment by xprazak2** [comment]
I moved the issue to appropriate project in Redmine.

**Review by ekohl — APPROVED** [review]
Can you describe why the path could be empty? Is this when something doesn't come from a gem?

**Comment by ekohl** [comment]
Is this test relevant?

```
Capybara::ElementNotFound: Unable to find visible css "#environment_id"
    test/integration/host_js_test.rb:377:in `block (2 levels) in <class:HostJSTest>' 
```

**Review by tbrisker — APPROVED** [review]
test failures unrelated, thanks @xprazak2 !

**Comment by xprazak2** [comment]
@ekohl, we register a fake plugin in [test_helper](https://github.com/theforeman/foreman/blob/develop/test/test_helper.rb#L30) to skip tests

**Comment by ares** [comment]
This caused a regression, audits page no longer loads

**Comment by ezr-ondrej** [comment]
The mentioned regression is introduced in #6538 already, just not reproducible on full page load.

**Comment by ezr-ondrej** [comment]
No, sorry bad work with redmine on my side. It is this one: #6405.

**Comment by ares** [comment]
sorry, bisect in this case didn't work well, since it seems to happen only with specific timeout

**Pull request merged**
