### PR TITLE
Fixes #13529 - Remove duplicate permissions

### PR DESCRIPTION
**Pull request by shlomizadok**
A migration which adds unique constraint
and removes duplicate permissions

### CODE REVIEW

**Comment by shlomizadok** [comment]
[test] failure unrelated?

**Comment by ohadlevy** [comment]
[test]

**Comment by tbrisker** [comment]
APJ

**Comment by ohadlevy** [comment]
it looks like test failure is due to rabl? wasn't it fixed already?

**Comment by tbrisker** [comment]
@ohadlevy jenkins had a long queue, build is running now

**Comment by tbrisker** [comment]
Merged as 954abbaf59154c90717f6b56d54fae9d8168d010, thanks @shlomizadok!

**Pull request closed without merging**
