### PR TITLE
Fixes #9299 - Windows installation media should be more transparent

### PR DESCRIPTION
**Pull request by DimmKirr**
Fixes #9299

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@kireevco My only 2 concerns with the PR are:
- Are we only going to be able to boot Windows 8.1 if we stick to wimboot?
- Microsoft says [`WIMBoot is not recommended on systems with fixed internal storage of more than 32GB`](https://technet.microsoft.com/en-us/library/dn594399.aspx) , is there any issue you've had with that?

**Comment by DimmKirr** [comment]
I was booting windows server 2012 without any problems. Hard drives I had were 150g.

I think this Microsoft article is talking about something else, and not wimboot from iPXE.

**Comment by dLobatog** [comment]
@kireevco Cool, please ping me here once the other PRs have been merged as they pretty much depend on each other. There are some `trailingwhitespace` bugs rubocop is whining about sorry!

**Comment by dLobatog** [comment]
[test] because of the latest enabled cops

**Comment by DimmKirr** [comment]
trailingwhitespace should be fixed.
Can we please merge this, anything else I could do?

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
@kireevco Tests failing sorry!

**Comment by DimmKirr** [comment]
Bummer. Could someone kindly send me link to the build?

**Comment by domcleal** [comment]
The unit tests actually pass, it's just the style tests.  There are two instances of trailing whitespace listed here: http://ci.theforeman.org/job/test_develop_pr_rubocop/2088/checkstyleResult/new/

**Comment by DimmKirr** [comment]
[test]

**Comment by mmoll** [comment]
[test] <- you have to be a public member of the theforeman organization on GH for this to work.

**Comment by DimmKirr** [comment]
Ah... It was a nice try :)

How can I test it? Hopefully I fixed styling.

**Comment by mmoll** [comment]
http://ci.theforeman.org/job/test_develop_pr_rubocop/2918/checkstyleResult/new/source.7/#19
Delete the spaces in that line. You can of course always insall rubocop on your machine and even integrate it into your Editor/IDE to catch it beforehand. :)

**Comment by DimmKirr** [comment]
Will do.
All next patches will be rubocopped. That one was a very quick patch that I
felt needs to go up to help Windows users.

Thank you.

**Comment by mmoll** [comment]
[test]

**Comment by dLobatog** [comment]
Merged as fe102b163043bd7c25725d5006d36278afc30dc3, thanks @kireevco

**Comment by DimmKirr** [comment]
Appreciate your patience.

## 

Sincerely,
 Dmitry Kireev
 cel.: +1 (818) 850-5577
 email, gtalk: dmitry@kireev.co
dmitry@kireev.co skype: kireev.co
 aim: 336719228

**Comment by domcleal** [comment]
@eLobato I don't see a commit in develop for this, and the SHA above is something else.  Could you double check where it went please?

**Comment by dLobatog** [comment]
My bad, it was pushed in my original repo only, I could not rely on my script as I had to squash these 5 commits. 85e625447252ac1810a6e2bdabf03baeb3d4d56c contains this. Thanks @kireevco @domcleal @mmoll

**Comment by DimmKirr** [comment]
Thanks @elobato, @domclean, @mmoll
I'll try to be more organized next time too.

## 

Sincerely,
 Dmitry Kireev
 cel.: +1 (818) 850-5577
 email, gtalk: dmitry@kireev.co
dmitry@kireev.co skype: kireev.co
 aim: 336719228

**Pull request closed without merging**
