### PR TITLE
Fixes #11062 - do not process data when FormData is used

### PR DESCRIPTION
**Pull request by ares**
@shlomizadok could you please tests with foreman_openscap which contains file uploads through two-pane

### CODE REVIEW

**Comment by ohadlevy** [comment]
@ares whats the original code that generate the issue in the first place?

**Comment by ares** [comment]
the code that causes it: https://github.com/theforeman/foreman/pull/1986/files#diff-ddda07bc3bc6c2037aa8990079397468R75

the fix is to disable data processing if FormData is used instead of serialization, more info in redmine issue, if you have troubles with reproducing, I can demonstrate through hangout

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
[test]

**Comment by domcleal** [comment]
@shlomizadok could you give this a test please to check for regressions?  See the description.

**Comment by shlomizadok** [comment]
Tested, works very well. Thanks @ares :+1:

**Comment by domcleal** [comment]
Thanks @ares, merged as 17dffb0.

**Pull request closed without merging**
