### PR TITLE
Fixes #35132 - Make audits host detection regex more strict

### PR DESCRIPTION
**Pull request by ShimShtein**
Before the PR, Foreman tried to fix the auditable type to `Host::Base` in case a derived class was generating the audit.
The problem is that it also replaced the `auditable_type` column for Katello facets too:
```
irb(main):001:0> 'Katello::Host::SubscriptionFacet' =~ /Host::/
=> 9
```

This caused Subscription and Content facet's audits to be recorded as `Host::Base`, which caused wrong auditable association.
The regex was changed to be more strict:
```
irb(main):009:0> 'Katello::Host::SubscriptionFacet' =~ /^(::)?Host::/
=> nil
irb(main):010:0> '::Host::Managed' =~ /^(::)?Host::/
=> 0
irb(main):011:0> 'Host::Managed' =~ /^(::)?Host::/
=> 0
```

Now we need a migration to fix back facet audits. We can detect incorrect records by looking at `auditable_type` and `associated_type` columns. There is no circular association in host, so having host as both associated and as the audited record is incorrect.
Now I needed to guess which audits belonged to which facet. To do that, I am looking for column names that are unique to the facet, if I find those, I can assume it was that facet.
This leaves us with audits with changes to columns with ambiguous names. From looking at the DB, I have found only changes to `uuid` column. During these searches, I have seen that all those `uuid` values are present in only in content facet, hence I assume the change was performed on content facet instance.

### CODE REVIEW

**Comment by ShimShtein** [comment]
@adamruzicka , ready for review

**Comment by adamruzicka** [comment]
Another class that would have gotten matched is  `ForemanOpenscap::Host::OvalFacet`, but those don't seem to get audited at all.

I've checked on a couple of machines and the migration seemed to work well on all of them. Considering the migration set certain records to appear as if produced related to classes from katello, shouldn't it live in katello?

@ianballou could you take a look here and give this a blessing from katello's point of view. Also do you have any idea why the uuid in content facet tends to fluctuate a bit?

**Comment by ianballou** [comment]
Hmm I'm not sure why the UUID would change, that is coming from Candlepin.  @jeremylenz or @chris1984 , do you know why uuid would pop up in audits?

**Comment by jeremylenz** [comment]
One thing that would do it is if you unregistered and reregistered a host. I just tested this, same Rails ID, different uuid:

```
[20] pry(main)> Host.find(5).subscription_facet.uuid
=> "1dd3c792-f24d-4a9f-bf3e-6d401ce57eeb"

[root@rhel8b vagrant]# subscription-manager identity
system identity: 1dd3c792-f24d-4a9f-bf3e-6d401ce57eeb
name: rhel8b.fedora.example.com
org name: Default Organization
org ID: Default_Organization
environment name: Library
[root@rhel8b vagrant]# subscription-manager unregister
Unregistering from: centos8-katello-devel.fedora.example.com:443/rhsm
System has been unregistered.
[root@rhel8b vagrant]# subscription-manager register --activationkey ak1 --org Default_Organization
The system has been registered with ID: 4026cc36-3d01-4bda-b546-9d20b400d643
The registered system name is: rhel8b.fedora.example.com

[21] pry(main)> Host.find(5).subscription_facet.uuid
=> "4026cc36-3d01-4bda-b546-9d20b400d643"

**Comment by ianballou** [comment]
I gave it a test and it looks good to me! It's nice seeing the more detailed model types.

**Comment by jeremylenz** [comment]
[test foreman]

**Review by ianballou — APPROVED** [review]
I'll give this my Katello ACK, but we'll need someone from Foreman to review instead. @adamruzicka, looks like you're assigned, is it on the right backlogs? Just want to make sure it doesn't get left behind.

**Comment by adamruzicka** [comment]
Yes, I'm watching this. Now that it has a katello ack, I'll deal with the rest.

[test foreman]

**Comment by adamruzicka** [comment]
Oh, right, the failing foreman test is before the jenkins jobs were split up. Let's get this in

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ShimShtein & @ianballou & @jeremylenz !

**Pull request merged**
