### PR TITLE
Fixes #37724 - Pin fog-libvirt to ~> 0.12.0

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
This doesn't make sense to me. It removes the upper bound but there is no version 1.0. Please don't create garbage issues and PRs without any context or reasoning why. It's impossible for a reviewer to figure out what's going on.

**Comment by stejskalleos** [comment]
> This doesn't make sense to me. It removes the upper bound but there is no version 1.0.

The goal was to allow the 0.12.Z updates. Why we need to pin the Z version as well?

**Comment by ekohl** [comment]
> This doesn't make sense to me. It removes the upper bound but there is no version 1.0.

Sorry, this should have been "you're adding the upper bound".

More explicitly, you're effectively changing it from `>= 0.12.0` to `>= 0.12.0 < 1`. While that may not be a bad thing, I wonder what you're trying to achieve.

**Comment by stejskalleos** [comment]
OMG, I see it now; that's what happens when push PR happens before I think. Yeah, sorry, I'm closing the PR.

**Pull request closed without merging**
