### PR TITLE
Fixes #11465 - Hiding table headers when tables empty

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by tbrisker** [comment]
Hi,
Why did you choose to use javascript to hide the headers instead of not loading them at all when not needed?

**Comment by xprazak2** [comment]
Hi @tbrisker, I tried not to load them when rendering partials but then I found out not all actions in the form result in template re-rendering. Adding puppet classes when creating a new hostgroup makes the template re-render, but removing the classes makes no ajax request. That could leave us with no puppetclasses assigned in 'Puppet Classes' tab but they would be shown in 'Parameters' tab.

**Comment by tbrisker** [comment]
In that case, I would suggest opening a different issue/pr that makes sure this tab is reloaded via ajax every time it need to be reloaded (i.e. when puppet classes change).
This issue should only handle the matter of not displaying unneeded headers (both the "class parameters" etc and the table headers themselves) on the forms.

**Comment by xprazak2** [comment]
@tbrisker: I surely can open up a new issue, but we will probably need to use js to manipulate with table headers in some cases - when adding the parameter overrides

**Comment by tbrisker** [comment]
@xprazak2 I believe that would be better to only add headers via js when needed (i.e. overrides) and not for everything. 
Just so you know, the overrides mechanism will be changed soon to perform override in-place instead of in a different table, which means this will only be a temporary workaround. 
This change is the next thing on my plate for this form, as it will also allow for cleaning a lot of the js cruft that has been accumulating around this.

**Comment by xprazak2** [comment]
@tbrisker: ok, I will add the issue regarding template re-rendering and I will change this when it is resolved.

**Comment by tbrisker** [comment]
@xprazak2 I don't think this need to wait for that, simply have the headers displayed only when there are relevant parameters. The problem with reloading the tab when a puppet class is removed means that the table and its headers will remain in the tab, but once it's resolved the reload will cause them to be removed.

**Comment by xprazak2** [comment]
@tbrisker: The table header for puppet params is re-rendered when puppetclass is added/deleted in [this PR](https://github.com/theforeman/foreman/pull/2691), so I removed it here. Adding a new Global host param in is the same case as override - no requests to server so table header can probably be handled by js, which leaves us Inherited Global params. They change when hostgroup/parent is changed so I will try to make the table render server-side, add it to the other PR and make further changes here if you agree.

**Comment by dLobatog** [comment]
Sorry but I'm a bit on the fence about this one. The `None!` messages IMO are not necessary, you could save a bunch of code by removing those and all the logic involved to show them. 

Judging the PR by Patternfly standards, this goes against the [empty tables pattern](https://www.patternfly.org/patterns/table/#grid-and-empty-table). Unfortunately the Parameters redesign PDF does not contain any examples, so if you could, please contact @kybaker and have him take a look.

**Comment by ehelms** [comment]
For what its worth, right now Katello implements the Patternfly empty tables pattern.

**Comment by dLobatog** [comment]
For future reference -

Before this PR:

screenshot from 2015-09-10 16-08-13

After this PR:

screenshot from 2015-09-10 16-08-32

**Comment by kybaker** [comment]
We absolutely do not want to hide tables (or any content) ever just because users have not used them yet for multiple reasons. The primary reason is hiding parts of the UI make it very difficult to build a mental model of the application functionality. It makes discoverability of feature impossible. This does not mean we can't implement better progressive disclosure of the information which would require heavier modification of the UI.

I recommend following the PatternFly empty pattern which can be seen here - https://www.patternfly.org/patterns/table/, this has been tested and vetted with users. As a bonus we could write instructions about how to use the data in the table and possibly link to the documentation. This effort is non-trivial but would be very beneficial.

**Comment by tbrisker** [comment]
I would suggest that we close this PR for now and come back to it later if needed, as other planned changes will also reduce the number of tables. 
The original intent of this issue was to treat the situation where some hosts had four empty tables with unclear meaning, and only display them when needed. 
However, as @kybaker and @eLobato  mentioned it would be better to have it display helpful text about the empty tables.
As [#11458](http://projects.theforeman.org/issues/11458) will lead to reduction to two tables - one for puppet class parameters and one for global parameters - I would prefer that any handling of this issue be deferred to after that issue is solved. I will update the redmine issue accordingly.
Thank you for your effort @xprazak2 !

**Comment by xprazak2** [comment]
ok, @tbrisker, @eLobato, @ehelms and @kybaker, I will delete the remote branch to close this. I will also close [#11658](http://projects.theforeman.org/issues/11658) because it was spawned by this issue (as discussed above) and we will not need it.

**Comment by tbrisker** [comment]
@xprazak2 no need to delete your branch, you can simply close the PR. #11658 seems like it is till valid in any case.

**Comment by xprazak2** [comment]
@tbrisker I did not notice, must be a recently new feature. thx

**Comment by domcleal** [comment]
Please remember to update Redmine tickets when closing PRs, I've done both.

**Pull request closed without merging**
