### PR TITLE
Fixes #13556 - explicit priority for features

### PR DESCRIPTION
**Pull request by lzap**
Adds explicit priority number to features. With this, we can explicitly set the
order in more natural way. It is leveraged in Smart Proxy list/show pages.

### CODE REVIEW

**Comment by lzap** [comment]
@tbrisker this fixes the ordering of tabs, I am working on tests now.

**Comment by lzap** [comment]
I removed fixtures from whole Smart Proxy Controller test file. I can push this futher maybe removing all features and proxies fixtures from whole codebase if that turns out to be doable in reasonable time.

**Comment by dLobatog** [comment]
:-1: from me, sorry. I think this is a lot of code overhead for little benefit. 

Other than the ordering of tabs does this affect anything else? We can order that strictly w/o touching the database - why is the default order wrong?

**Comment by shlomizadok** [comment]
I agree with @dLobatog. I'd just order them alphabetically.

**Comment by tbrisker** [comment]
I agree. Thinking about it, since features will always be a very short list, we can set the order in `TABBED_FEATURES` and simply use [set intersection](http://ruby-doc.org/core-2.2.0/Array.html#method-i-26) on the arrays:

```
def tabbed_features(proxy)
  TABBED_FEATURES & proxy.features
end
```

**Comment by ares** [comment]
I like this approach, it's easy to extend from plugins. @tbrisker is right about the number of features so if you decide to make the order hardcoded, please make sure we have good control in plugin API to put our feature into specific position (ideally not by modifying the constant)

**Comment by lzap** [comment]
If we keep them ordered alphabetically, it looks weird. Currently, if you look on the Smart Proxy Show page, it shows tabs in this order: DHCP, DNS, Logs, TFTP, Puppet, Puppet CA.

Let me try another run, a simple plugin API that can also do the feature creation in the DB.

**Comment by lzap** [comment]
I currently don't have time for that, closing this patch.

**Pull request closed without merging**
