### PR TITLE
STI for Host

### PR DESCRIPTION
**Pull request by isratrade**
This branch is a refactoring of @GregSutcliffe 's branch #415

### CODE REVIEW

**Comment by isratrade** [comment]
@ohadlevy, I don't know where your comments where. I made some changed and squashed it into my last commit.  Usually, it says "Diff Outdated" for the old comments.  Anyway, here's a summary of my changes.

1) I moved the two scopes used by host_mailer.rb from base.rb back to managed.rb
2) I changed the relationships in Hostmix.rb to use Host::Managed and not Host::Base.  It makes sense, since the has_many_hosts is called from managed.rb and not base.rb

``` ruby
        has_many :hosts, {:class_name => "Host::Managed"}.merge(options)
```

3) I left hostable.rb as an initializer.  I tried to be extend Host::Hostmix in lib/core_extensions.rb but it didn't work, since this file is called in application.rb **before** the rails application is loaded.

**Comment by isratrade** [comment]
@ohadlevy, change the author of first commit in this pr to @GregSutcliffe.  When I rebased I needed to resolve some conflicts and it changed the author to me.

**Comment by isratrade** [comment]
@ohadlevy, just pushed new commit

**Comment by ohadlevy** [comment]
squashed & merged + moved the merge_facts into private

thanks @GregSutcliffe @isratrade !

**Pull request closed without merging**
