### PR TITLE
Fixes #25762 - display filterable request UUID

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Takes over #6377 inconporates the coments there and changes how we filter the results - now we use the fetch function.

Thanks @ares for doing all the work :+1:

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I have no idea why the lint fails on `DefaultEmptyState` component :thinking:

**Comment by xprazak2** [comment]
Rebase on latest develop should fix it - https://github.com/theforeman/foreman/pull/7370

**Comment by ezr-ondrej** [comment]
Let see :)

**Comment by xprazak2** [comment]
Works for me:
uuid

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Comment by ezr-ondrej** [comment]
@ares do you want to demo it? :)

**Comment by ares** [comment]
I'm on PTO next week/demo so free to take it. But I'm also fine with demoing the demo after if you don't want to take the credit :-)

**Comment by ezr-ondrej** [comment]
I can demo it, but I would rather leave the honors to you, as it's mostly your feature :) I think it's ok to demo it the next demo ;)

**Pull request merged**
