### PR TITLE
fixes #2157 - methods should accept hosts argument

### PR DESCRIPTION
**Pull request by domcleal**
Methods are called from line 25 with hosts as the argument.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@isratrade mind having a look? I thought we decided its not required? maybe its a left over?

**Comment by isratrade** [comment]
@domcleal, good catch.  Since hosts is already defined in the initialize and accessible by each method, I think a cleaner not pass the hosts variable as a parameter.  

Line #25
- ids[col] = self.send(col, hosts)
- ids[col] = self.send(col)

**Comment by isratrade** [comment]
@domcleal, I'm confused with my tests didn't fail for used_ids??  Are you using Ruby 1.9

**Comment by ohadlevy** [comment]
@isratrade, I can confirm it only fails on 1.9, @skottler don't we run 1.9 tests on ci.theforeman.org?

**Comment by ohadlevy** [comment]
@domcleal, I've amended your commit and merged - thanks!

**Comment by domcleal** [comment]
@isratrade yep, it was on Ruby 1.9 (F17)

**Pull request closed without merging**
