### PR TITLE
Fixes #27338 - add GCE params in compute_resource APIs

### PR DESCRIPTION
**Pull request by kgaikwad**
adding @shiramax and @jyejare into the loop.

### CODE REVIEW

**Review by shiramax — DISMISSED** [review]
looks good to me :)

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by kgaikwad** [comment]
Done with rebase.

**Review by ezr-ondrej — APPROVED** [review]
I do not like this endpoint in general, but that's nothing you can do something about :)
Thanks @kgaikwad, LGTM.

**Comment by ezr-ondrej** [comment]
@tbrisker seems small and pretty useful, what do you think?

**Review by tbrisker — APPROVED** [review]
Fine by me, thanks

**Pull request merged**
