### PR TITLE
Revert "Fixes #24003 - remove babel-polyfill from vendor.js"

### PR DESCRIPTION
**Pull request by mmoll**
This reverts commit bff82b8918b68b0127e4ea32a7d3b958f1a55a91.

### CODE REVIEW

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
Fixes test_develop.

**Comment by tbrisker** [comment]
I'm trying to fix it without reverting this, since this broke rex. will update soon.

**Review by tbrisker — APPROVED** [review]
Merging to get develop working again until we figure out the correct way to fix this. thanks @mmoll !

**Comment by ohadlevy** [comment]
can you guys share why the revert was needed? or in other words what didn't work?

**Comment by tbrisker** [comment]
this was causing integration tests to fail because the polyfill was loaded after the vendor.js

**Pull request merged**
