### PR TITLE
ignore .rvmrc in .gitignore

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by skottler** [comment]
:+1:

**Comment by GregSutcliffe** [comment]
Looks good, can we also add:

```
.rbenv-gemsets
.ruby-version
```

For us RBenv users?

**Comment by domcleal** [comment]
@lzap tried to sneak the same into his bundler_ext PR, but a slightly different rbenv filename - I don't know the difference.  see https://github.com/lzap/foreman/commit/1142220d2d508b891bf0dbbae2bbd3f7d5bf6f9c

**Comment by lzap** [comment]
I think newer version of rvm uses some timestamps like .rvmrc-20090901-0910 thus the star

```
.rvmrc*
```

I am also for .rbenv-version

**Comment by domcleal** [comment]
Combining all of that, should it be:

```
.rbenv*
.rvmrc*
.ruby-version
```

**Comment by lzap** [comment]
Sounds like a plan!

**Comment by GregSutcliffe** [comment]
:+1:

**Comment by ohadlevy** [comment]
@isratrade ping?

**Comment by isratrade** [comment]
@ohadlevy I updated the commit to @domcleal 's suggestion

**Comment by ohadlevy** [comment]
thanks!

**Pull request closed without merging**
