### PR TITLE
[WIP] Fixes 23010 - adding deprecation warnings to flot

### PR DESCRIPTION
**Pull request by lizagilman**
Added deprecation warnings to old flot functions, as we are moving to c3.

### CODE REVIEW

**Comment by boaz0** [comment]
Hey @lizagilman 
Sorry to inform you but I am actually working on this in https://github.com/theforeman/foreman/pull/5454

**Comment by lizagilman** [comment]
Hey @ripcurld 
sorry ohadlevy asked me to work on that and I didn't notice your pr
perhaps you can assign yourself on this bug 
@tbrisker should we close this pr?

**Comment by tbrisker** [comment]
It's strange that the bot didn't automatically assign the issue to @ripcurld when he opened a PR.
However, looking at the two PRs, this one uses the deprecation method we use to deprecate functions, while the other adds comments in the code that state a function is deprecated which is not visible to anyone not reading the code. The idea of using a deprecation method is that plugin authors will get an indication that their code needs updating before a function is removed.
Both PRs in my opinion are lacking one very significant issue - we cannot deprecate a function if we don't have a working alternative for it. Right now we only have a new implementation for pie charts afaik, so both of these PRs should not be merged until we have a new implementation for all charts.
I suggest you combine forces and work together to make sure that all deprecated methods have a good replacement, and then deprecate them in the supported way (using `tfm.tools.deprecate`).

**Comment by lizagilman** [comment]
afaik once #5019 will get merged we are done moving to c3 (except of plugins)
possibly @amirfefer can confirm that?

**Comment by amirfefer** [comment]
afaik we are still using `flot_pie_chart` in some places such as `config_report/metrics`

**Comment by boaz0** [comment]
I am closing https://github.com/theforeman/foreman/pull/5454 in favor to this PR.

**Comment by lizagilman** [comment]
Patternfly-react has a verity of chart components implemented - https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=Chart&selectedStory=Area%20Charts&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
Is this a satisfying replacement for plugin maintainers?
@tbrisker @amirfefer

**Comment by tbrisker** [comment]
Right now, the only chart type we have integration with in Foreman core is donut chart. 
While it is true that plugin authors can use any other chart type, it isn't something we provide in core, unlike the flot charts. 
There are also flot-based time and bar charts used in core, and there may be others in various plugins. I did not check which are being used in the public plugins, and in any case we should use the deprecation so that even private plugins have time to adapt to this change. This is especially important since this isn't just a function name change, this requires a much more significant rewrite effort for the charts to work with c3.

**Comment by lizagilman** [comment]
closing this pr as we still have some work until full migration is completed

**Pull request closed without merging**
