### PR TITLE
Fixes #29967 - encrypt root password in settings

### PR DESCRIPTION
**Pull request by patilsuraj767**
This will encrypte and mask the root password in Settings > Provisioning tab.

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by tbrisker** [comment]
@patilsuraj767 please rebase on latest develop branch

**Comment by patilsuraj767** [comment]
> @patilsuraj767 please rebase on latest develop branch

Done.

**Comment by lzap** [comment]
Is migration necessary? I mean, this could make existing password unreadable. Also there is a typo in the title.

**Comment by patilsuraj767** [comment]
> Is migration necessary? I mean, this could make existing password unreadable. Also there is a typo in the title.

@lzap 
[create_existing](https://github.com/theforeman/foreman/blob/8d6c949b86a6e2d46df4a8637bd5fc5523194ff6/app/models/setting.rb#L235) method is called every time when rails initialize and it has the [condition](https://github.com/theforeman/foreman/blob/8d6c949b86a6e2d46df4a8637bd5fc5523194ff6/app/models/setting.rb#L250) which will take care of encrypting the raw password. So no need of migration.

**Review by lzap — CHANGES_REQUESTED** [review]
It does not work for me. Value is shown both in UI and also it is stored in the database.

**Review by lzap — APPROVED** [review]
So with ENCRYPTION_KEY set in my initializer it works in the database, password is even replaced on the UI page but after I edit it, the word is visible until next page refresh. This is probably a UI thing, please confirm if this is a different bug and let's merge this.

**Comment by patilsuraj767** [comment]
> So with ENCRYPTION_KEY set in my initializer it works in the database, password is even replaced on the UI page but after I edit it, the word is visible until next page refresh. This is probably a UI thing, please confirm if this is a different bug and let's merge this.

Yes, the same happens with me and not only with the root_pass but also with other settings which are encrypted. It appears as a plain text until the page refresh.

**Pull request merged**
