### PR TITLE
Fixes #33735 - add recent reports card in host details

### PR DESCRIPTION
**Pull request by amirfefer**
I'm not sure how to render the report status, we don't have enough room for it in a card, looking for an aggregation design

https://user-images.githubusercontent.com/11807069/137978441-909cb18d-31b7-451a-a6c7-7b258a8dd2ed.mov

### CODE REVIEW

**Comment by ekohl** [comment]
@amirfefer In https://github.com/theforeman/foreman_host_reports there is work to redesign host reports. Perhaps we can share some efforts.

@lzap this is related to our work to build a new report overview but then on the host detail page. How do we avoid duplicate work?

**Comment by amirfefer** [comment]
Thanks @ekohl,

I created an aggregate report status (failures, pending, ok):

Screen Shot 2021-10-21 at 12 27 08

**Comment by ekohl** [comment]
I'm hesitant to map the current reports this way. It makes it unclear as to which report it is (old vs new). We don't use the grouped logic anywhere else and that creates an inconsistent UX. You also miss the case where there is something applied. I'd personally still stick with the numbered columns, just as we have on today's dashboard for consistency.

In the working group we also discussed making the timestamp the link. That's the primary key and the most relevant part.

It'd also be great if we could consistently use icons for the source, just like we do in the current reports overview already.

**Comment by lzap** [comment]
I was assuming that with the new detail page, we will have separate tabs for each configuration management tool: Ansible, Puppet and with that, we would have a plenty of space to render detailed cards.

In the new reports design, each report has a type (Ansible or Puppet) and the only common thing that is quick to fetch are number or resources which failed, passed, skiped or other. So we will be showing something like:

* Last Puppet report: date, time, resources failed, passed, skipped, other
* Last Ansible report: date, time, resources failed, passed, skipped, other
* Last XXX report (for each type as the community adds new types)

I am not so sure how useful is showing last N reports, I think only the last one of each type is relevant for the main host detail page. On the Ansible/Puppet tabs, we will show more details, probably list of last N reports with more details and statistics.

**Comment by ares** [comment]
After an agreememt with @amirfefer we're closing this for now as more design discussion and mockups will be created for this area.

**Comment by lzap** [comment]
We will be working on new Monitor - Dashboard widgets pretty soon, that shoould give us some more information too,

**Pull request closed without merging**
