### PR TITLE
call npm install with --no-optional and --no-audit for plugins

### PR DESCRIPTION
**Pull request by evgeni**
speedup all the things, please

### CODE REVIEW

**Comment by evgeni** [comment]
@laviro @amirfefer mind having a look please if I am not crazy?

**Review by ekohl — APPROVED** [review]

**Review by Ron-Lavi — COMMENTED** [review]
Not that I am against it.. though it took only 4s less on my end.

This branch:
`added 4254 packages from 2661 contributors and audited 4262 packages in 195.597s`

on upstream/develop:
`added 4254 packages from 2661 contributors and audited 4262 packages in 199.281s`

**Comment by evgeni** [comment]
@laviro yeah, you'll notice more impact if you run it on slower machines, like our CI nodes ;)

Do you have plugins installed?

**Comment by Ron-Lavi** [comment]
> @laviro yeah, you'll notice more impact if you run it on slower machines, like our CI nodes ;)
> 
> Do you have plugins installed?

Yes, I have tasks, REX, katello, cloud and maybe more? :D

btw, if we decide to add the `package-lock.json` as we discussed last UX interest group,
seem that `npm ci` (clean install) takes 2 minute less !
`added 3821 packages in 64.204s`

**Comment by Ron-Lavi** [comment]
cc @Andrewgdewar

**Review by Ron-Lavi — APPROVED** [review]
Let's have this one if it helps, found no regressions :)
about the lock file, we can continue to discuss on https://community.theforeman.org/t/using-a-package-lock-json-for-foreman/25021

when the lock file contains only Foreman's dependencies and in the post-install it installs plugins, the installations results in: `added 3821 packages in 77.409s`

**Pull request merged**
