### PR TITLE
Refs #37505 - fix clevis & tang snippet

### PR DESCRIPTION
**Pull request by IncredibleRichie**
This fixes #37505

### CODE REVIEW

**Review by stejskalleos — APPROVED** [review]

**Review by ekohl — DISMISSED** [review]
Since https://projects.theforeman.org/issues/36885 hasn't been released yet, you can use `Refs #36885` instead of `Fixes #37505`. This results in a cleaner changelog and clearly relates the issues.

**Review by sbernhard — APPROVED** [review]
Thanks @IncredibleRichie

**Comment by sbernhard** [comment]
@ekohl The commit message was adjusted and is fine now. Ready to merge this.

**Comment by sbernhard** [comment]
@ekohl the commit title was changed.

**Comment by stejskalleos** [comment]
Thanks @IncredibleRichie @sbernhard @ekohl

**Pull request merged**
