### PR TITLE
Refs #36400 - add ouia-ids to ChartBox

### PR DESCRIPTION
**Pull request by MariaAga**
Automation to find missing ouia-ids didnt run on https://github.com/theforeman/foreman/pull/9709 
adding them now

### CODE REVIEW

**Comment by ofedoren** [comment]
Could you please regenerate snapshots? I guess the failures are because of this...

**Comment by MariaAga** [comment]
Started running tests and my laptop crashed for 15 minutes :upside_down_face: 
Updated the snapshots

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga. Although, we don't use `Refs` for something that was already released, but since I don't think we would need to CP that and it's a minor follow up, I'd merge it as is. Unless you want to create a separate issue (in this case it wouldn't look weird, since it's rather more about ouia-ids than config reports page).

**Comment by MariaAga** [comment]
@ofedoren I think we can get it in as is

**Comment by ofedoren** [comment]
Thanks, @MariaAga, merging.

**Pull request merged**
