### PR TITLE
Fixes #34250 - Insecure help text at Host Registration

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Did you intend to drop the test?

**Comment by stejskalleos** [comment]
> Did you intend to drop the test?

Yes, in past we decided to not do these tests anymore as they don't provide much value.

**Review by ekohl — APPROVED** [review]
Fine by me then. Thanks!

**Comment by ezr-ondrej** [comment]
CP 3.1:  d82efa74b

**Pull request merged**
