### PR TITLE
refs #19419 - test aws fog_extensions name methods

### PR DESCRIPTION
**Pull request by timogoebel**
This adds some tests for #4493. I will rebase this once the other PR is merged.

### CODE REVIEW

**Comment by tbrisker** [comment]
@timogoebel - #4493 has been merged, please rebase.

**Comment by timogoebel** [comment]
@tbrisker: Thanks, rebased.

**Comment by tbrisker** [comment]
test failures seem unrelated, merging.

**Comment by tbrisker** [comment]
Thanks @timogoebel !

**Pull request merged**
