### PR TITLE
fixes #19235 - vmware.rb : add Server 2016 support

### PR DESCRIPTION
**Pull request by ricou84**
Add support for Windows 2016 server image based provisionning

### CODE REVIEW

**Comment by ricou84** [comment]
Seems not sufficient to support 2016

**Comment by mmoll** [comment]
please see the URL in line 191, the whole dataset would need an update, if there's a new vSphere version available

**Comment by Nokrite** [comment]
Seems sth. wrong with the patch
```
         "windows9_64Guest" => "Microsoft Windows 10 (64-bit)",
+        "windows9srv-64" => "Microsoft Windows Server 2016 (64-bit)",
         "windows9Server64Guest" => "Microsoft Windows Server Threshhold (64-bit)",
```
From the [vSphere 6.5 GuestOSIdentifier Documentation](http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.GuestOsDescriptor.GuestOsIdentifier.html) the name should be windows9Server64Guest instead of windows9srv-64. If i understand it right, just the label "Microsoft Windows Server Threshhold (64-bit)" should be replaced with "Microsoft Windows Server 2016 (64-bit)"

**Review by ghost — CHANGES_REQUESTED** [review]
From the vSphere 6.5 GuestOSIdentifier Documentation the name should be "windows9Server64Guest" instead of "windows9srv-64". If i understand it right, just the label "Microsoft Windows Server Threshhold (64-bit)" should be replaced with "Microsoft Windows Server 2016 (64-bit)"

http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.GuestOsDescriptor.GuestOsIdentifier.html

**Review by mmoll — CHANGES_REQUESTED** [review]
Please either synchronize the whole list here, if that fixes the original issue or open another issue to synchronize the list and then continue to research the Win 2016 problem.

**Comment by ghost** [comment]
@mmoll i revised the whole list from the new vSphere 6.5 documentation. 
see #4543

**Comment by mmoll** [comment]
GH-4617 got in, this can get closed.

**Pull request closed without merging**
