### PR TITLE
Fixes #32018 - Add limit-offset pagination to GraphQL

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by timogoebel** [comment]
Doesn't relay already offer pagination? We've been using it in lisa for ages. I believe there is no need to do this ourselves.

**Comment by xprazak2** [comment]
Relay offers cursor based pagination which is useful for viewing items on previous or next page. To my knowledge, there is no way to 'skip pages' when loading items by page since it relies on cursor pointing to the following item. So we cannot go from page 1 directly to page 3 - we need cursor of the last item on page 2, but that page has not been loaded. Or am I missing something?

**Comment by kamils-iRonin** [comment]
> To my knowledge, there is no way to 'skip pages' when loading items by page since it relies on cursor pointing to the following item.

@xprazak2 I think you can use the `first` and `last` arguments, we do this in Lisa [1]. Let's say your page size is 10 and you want to load page 3. The query would be:

```
query {
  hosts(first:30, last:10) {
    edges {
      node {
        name
      }
    }
  }
}
```

[1] https://github.com/dm-drogeriemarkt/lisa/blob/728a40b7fb7c6dfd6e1ef4525b5751b59e99d89c/src/containers/DashboardContainer/index.js#L39-L40

**Comment by xprazak2** [comment]
That is clever, thanks!

**Pull request closed without merging**
