### PR TITLE
Fixes #20516 - GET hosts API displays owner_name attribute

### PR DESCRIPTION
**Pull request by snagoor**
GET hosts API now returns owner_name attribute

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
Can you add tests please?

**Review by timogoebel — CHANGES_REQUESTED** [review]
@snagoor : Please fix the useless assigned variable issue in the test. Looks good otherwise. Thanks.

**Comment by snagoor** [comment]
@timogoebel its already fixed.

**Review by timogoebel — CHANGES_REQUESTED** [review]
@snagoor : Thanks.

Could you please add `owner` to preloading?

```diff
diff --git a/app/controllers/api/v2/hosts_controller.rb b/app/controllers/api/v2/hosts_controller.rb
index dfefa099b..d158dfa08 100644
--- a/app/controllers/api/v2/hosts_controller.rb
+++ b/app/controllers/api/v2/hosts_controller.rb
@@ -20,7 +20,7 @@ module Api

       add_smart_proxy_filters :facts, :features => Proc.new { FactImporter.fact_features }

-      add_scope_for(:index) { |base_scope| base_scope.preload([:host_statuses, :compute_resource, :hostgroup, :operatingsystem, :interfaces, :token]) }
+      add_scope_for(:index) { |base_scope| base_scope.preload([:host_statuses, :compute_resource, :hostgroup, :operatingsystem, :interfaces, :token, :owner]) }

       api :GET, "/hosts/", N_("List all hosts")
       api :GET, "/hostgroups/:hostgroup_id/hosts", N_("List all hosts for a host group")
```

**Comment by snagoor** [comment]
@timogoebel done changes as requested. Can you please take another look?

**Review by timogoebel — APPROVED** [review]
@snagoor: Looks good to me, thanks.

**Review by dLobatog — APPROVED** [review]
Thanks @snagoor & @timogoebel - the failing katello tests match what was corrected in https://github.com/Katello/katello/pull/6927

**Pull request merged**
