### PR TITLE
Fixes #24665 - mount breadcrumbs only when for 200 response

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ohadlevy** [comment]
lgtm - any chance to add a test? thanks.

**Comment by ares** [comment]
what test do you have in mind? a unit test for helper? or "negative" integration tests that verifies there's no breadcrumbs on 500 page?

**Comment by ares** [comment]
added unit tests for now

**Comment by ohadlevy** [comment]
[test foreman]

**Review by ohadlevy — DISMISSED** [review]

**Comment by ohadlevy** [comment]
perhaps you need to rebase? it seems that factorybot is failing.

**Review by amirfefer — APPROVED** [review]
Thanks @ares :+1: 
Tests seem unrelated, a rebase would be useful.

**Comment by ohadlevy** [comment]
@amirfefer I actually rebased and force pushed earlier, and I'm not sure that if all the test failures are not relevant, lets see..

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
@ares any idea for the test failures? they seem to be consistent.

**Comment by mmoll** [comment]
test failures are unrelated

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
