### PR TITLE
Fixes #26761 - support associate/disassociate vms action for GCE

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by jyejare** [comment]
QE Testing (Manual):

Catogarized scenarios with Passed, Doubtfull and other issues, there as follows:


**Expected Resuls** (PASSed):

1. Deleting Associated VM deletes the VM from GCE.

2. Deleting Disassociated VM does not deletes the VM from GCE.

3. Importing VM as managed host also associates VM to host profile.

4. Buttons:
- 1. Disassociate Host: Displays for associated host.
- 2. Asociate Host: Displays for disassociated host.
- 3. Unmanage Host: Displays for managed host.
- 4. Managed Host: Displays for unmanaged host.

5. The managed Hosts VM gets deleted from GCE when we delete it from Compute Resource - > VMs tab, but the host profile is intact.

6. Powering on/off the unmanaged host from Hosts page works.

7. Powering on/off the managed host from Hosts page works.

8. Reimporting the VM(that has host profile already from last unmanaged host) throws an error for name already taken, changing the name imports the VM with new name.

9. Error message is displayed when there is no host profile to associate with, while associating VM.

10. All the tabs are displayed while importing the VM as managed.

11. Except VM and OS tabs, all the tabs are displayed while importing the VM as unmanaged.

12. While importing the VM as managed and unmanaged host, the IP remains same as its in GCE.


**Doubtful Results**(Possible failures or May be Not):

1. For Disassociated hosts, following fields are displayed in VM under CR, where as I see more fields for EC2.
State, Machine Type, Zone, Private and Public IP

2. For Associated hosts, following fields are displayed in VM under CR, where as I see more fileds for EC2.
State, Machine Type, Zone, Private and Public IP


**Extra Issues observed:**(Out of Associate / Disassociate PR scope Failures)

1. The VM power off/on from CR -> VMs throws below error but the VM in GCE is turning on and off as expected.
Error - undefined method `state' for #<Fog::Compute::Google::Server:0x005564da4bac78> Did you mean? start status

power_on_off_error_in_UI


2. Accessing VM console from CR, shows error type message for currently not supported, ,should be an info type message.

vm_console_not_supported_info


3. The VM power off dialog shows unusual name of VM.

power_off_dialog_bad_hostname

**Comment by kgaikwad** [comment]
> **Doubtful Results**(Possible failures or May be Not):
> 
> 1. For Disassociated hosts, following fields are displayed in VM under CR, where as I see more fields for EC2.
>    State, Machine Type, Zone, Private and Public IP
> 2. For Associated hosts, following fields are displayed in VM under CR, where as I see more fileds for EC2.
>    State, Machine Type, Zone, Private and Public IP

@jyejare, 
Thank you for testing all scenarios.
These details varies as per provider. Initially, for GCE only showing above details.
In [PR-6780](https://github.com/theforeman/foreman/pull/6780), I have added two more fields - created, image.

**Review by ezr-ondrej — COMMENTED** [review]
Looks nice and simple :+1:

Could you just please add test?
[ec2](https://github.com/theforeman/foreman/blob/3145e584321cfbc8ddde6078fd800594aa45fea0/test/models/compute_resources/ec2_test.rb#L14) could be a nice example as it is having the same implementation.

**Comment by kgaikwad** [comment]
Thank you for review, @ezr-ondrej!
I have created an [issue](https://projects.theforeman.org/issues/26082) which needs to be fixed on `fog-google` side so that I can create gce compute_resource in test environment. That is why I haven't added test for this patch.
I will keep a note for myself to add tests after above ticket get resolved.

**Comment by ezr-ondrej** [comment]
That is not relevant I believe, as the referenced test is not using the fog at all, but mocks the `vm` out completely. That is better way to test as "does fog works as expected" is not relevant to this test.
We want to test "having vm with public/private IP address, it will associate it with host having the same IP address". I believe following tests are doing exactly that:
```ruby
    describe '#associated_host' do
      let(:cr) { FactoryBot.build_stubbed(:gce_cr) }

      test "matches host by public_ip_address NIC" do
        host = FactoryBot.create(:host, :ip => '10.0.0.154')
        compute = mock('gce_compute', :public_ip_address => '10.0.0.154', :private_ip_address => "10.1.1.1")
        assert_equal host, as_admin { cr.associated_host(compute) }
      end

      test "matches host by private_ip_address NIC" do
        host = FactoryBot.create(:host, :ip => '10.1.1.1')
        compute = mock('gce_compute', :public_ip_address => '10.0.0.154', :private_ip_address => "10.1.1.1")
        assert_equal host, as_admin { cr.associated_host(compute) }
      end
    end
```
The only thing that is not tested here is that "gce_vm instance will respond to `private_ip_address` and `public_ip_address`" but that I believe is part of the fog API, what should be tested if `fog` so I believe it is ok to leave out? :slightly_smiling_face:

Feel free to use these if you agree, I tested those and it works.
Otherwise the PR is ready I believe :+1:

**Comment by kgaikwad** [comment]
@ezr-ondrej,
Great help!  Added test cases as suggested under GCE.
Sorry for confusion, I thought it will fail on compute_resource build part.

**Comment by ezr-ondrej** [comment]
Please rebase, I guess the other PR of yours is conflicting :frowning_man:

**Comment by kgaikwad** [comment]
> Please rebase, I guess the other PR of yours is conflicting

Done, updated PR!

**Review by ezr-ondrej — APPROVED** [review]
Thaks @kgaikwad, merging :+1:

**Pull request merged**
