### PR TITLE
fixes #7009, N+1 (actually 6+1) queries in dashboard page

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by domcleal** [comment]
This is the same as http://projects.theforeman.org/issues/5841, right?

**Comment by ohadlevy** [comment]
IMHO no, this is simply avoiding multiple select when they could be done in
one query. its a query against hosts, not reports.

**Comment by domcleal** [comment]
Ah yes, ta.

**Comment by GregSutcliffe** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @ohadlevy, merged as 9f1c910 for Foreman 1.6.0.

**Pull request closed without merging**
