### PR TITLE
Fixes #26757 - respect current user timezone in search

### PR DESCRIPTION
**Pull request by ares**
The problem is that if user has set some time zone, when we rely on scope search for parsing time, it ignores the time zone unless it's set explicitly. Reproducible with applied errata report template or most likely in any search bar when searching by time.

Prerequisites for testing:
* have some data with datetime column, e.g. host
* be a user with non UTC timezone

Tests needed (anticipated impacts):
* in vanilla Foreman, try searching for hosts reported later than at $x, e.g. `last_report > "2019-05-07 17:33:00"`, see SQL log, we blindy take the time and put it to SQL. With scoped search 0.4.7, it works as expected and does the calculation, e.g. for user in +0200 it will use 15:33:00 as the time for comparison.

### CODE REVIEW

**Comment by timogoebel** [comment]
Does a test in Foreman make sense?

**Comment by ares** [comment]
Tests are in scoped search itself, I don't think we need to retest this here.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Packaging looks good, waiting on approval: https://github.com/theforeman/foreman-packaging/pull/3723 (merged)

**Comment by ares** [comment]
all green, the redmine issues check seems to have some issues, but the commit message is ok

**Comment by timogoebel** [comment]
@ares: Yeah, I'd love to merge. But I _can_ not.

**Review by evgeni — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @ares.

**Pull request merged**
