### PR TITLE
fixes #3845 - store users previous taxonomy selections

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by domcleal** [comment]
@eLobato could you review please?  Not looked into it deeply, but wondering why we need the DB rather than session storage (which seems to work for URLs).

**Comment by stbenjam** [comment]
Is session info stored somewhere persistently? I thought it was ephemeral for only the current session.  The idea is when you log out and back in (or session expires), you're at the same org/location as before.

**Comment by domcleal** [comment]
That was my assumption as well, until Daniel looked into this bug:
http://projects.theforeman.org/issues/3963#note-5

Since we expire the user's session in the controller, we can actually store data back into the new session (in the above case, the original URL), so you might be able to repeat this with their taxonomy data, then restore it on login.  #1191 will handle the related default taxonomy feature, which is what I'd expect logout/login to obey.

**Comment by stbenjam** [comment]
Ah ok, I'll try it the same way as 3963 then.

**Comment by dLobatog** [comment]
@stbenjam Nothing much to comment on, I'll wait until you store this data in the new session. Make sure to include a test that simulates a logout/login that recovers the old taxonomies :)

**Comment by stbenjam** [comment]
Ok @eLobato have a look!

**Comment by stbenjam** [comment]
So "session", normally a SessionHash, stores the implementation with stringified keys.  That's why I had to slice with strings.  You can otherwise normally set and get with either symbols or strings.

However in minitest, its just a plain Hash, which means you can only access keys as they were originally created (thus it must be stringified key in my assertion...).  That's pants.

**Comment by dLobatog** [comment]
:+1:  looks sane to me, however the duplication between locations/organizations tests is becoming worrisome, probably worth a refactor soon. 

@stbenjam https://github.com/seattlerb/minitest is just waiting for your PR to fix that :tongue:

**Comment by stbenjam** [comment]
This is labeled "Waiting for contributor" -- does it need something from me?

**Comment by domcleal** [comment]
@stbenjam no, I just hadn't got around to updating it yet

**Comment by domcleal** [comment]
Merged as f639fdc for Foreman 1.4.1, thanks @stbenjam!

**Pull request closed without merging**
