### PR TITLE
Fixes #35694 - Add foreman product version macro

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
We already have many things with `foreman_` prefixed. Should there be an additional macro in case you want to display the real Foreman version somewhere as well as a branded one?

**Comment by adamruzicka** [comment]
I talked about it with @ShimShtein and we didn't really see a use for it right now, but of course we could keep it just in case

**Comment by ShimShtein** [comment]
@adamruzicka I would suggest a deprecation message for the `foreman_short_version` just in case someone is using it.
@ekohl I think it will create confusion to have both. Maybe renaming it to `foreman_core_short_version` or something that would be more explicit.

**Comment by adamruzicka** [comment]
> I would suggest a deprecation message for the foreman_short_version just in case someone is using it.

Oh, I was under the impression it never made it into a release, but it already is in 3.4. Maybe we should keep it after all?

**Comment by ShimShtein** [comment]
Hmmm... Let's split it to two issues: keeping the current macro vs deprecating it and adding the new macro.

I suggest adding the new macro in this PR, and later on we can discuss renaming/deprecating of the `foreman_short_version`.
Maybe adding a bit more explicit info to the documentation.

**Review by ShimShtein — DISMISSED** [review]

**Comment by ShimShtein** [comment]
@ekohl any comments before I merge?

**Review by ekohl — CHANGES_REQUESTED** [review]
@adamruzicka please open a new issue. The existing one was already part of the 3.4.0 changelogs so your change wouldn't show up in the 3.5.0 changelogs (and any potential cherry picks). Other than that :+1:

**Comment by adamruzicka** [comment]
> @adamruzicka please open a new issue

Done

**Review by ekohl — APPROVED** [review]

**Pull request merged**
