### PR TITLE
Refactor /models directory

### PR DESCRIPTION
**Pull request by isratrade**
- Created /concerns directory and moved mixins from /models to /concerns
- Added extend ActiveSupport::Concern to mixins and related code (ex. included do end)
- Created /services directory and added moved files from /models to /services
- Added /mailers directory
- Add folders for STI
- Moved /lib/foreman/model to /models/compute_resources
- Added add directories under /models to config.autoload_paths
- Moved file from /models to /mailers
- Moved file from /models to /helpers

Refactoring only.  NO NEW CODE.  ALL TESTS PASS

### CODE REVIEW

**Comment by ohadlevy** [comment]
app/models/host_template_helpers.rb → app/helpers/host_template_helpers.rb

this is not a helper as in rails helper, not sure if belongs there

**Comment by ohadlevy** [comment]
one issue i have with this patch, is that you moved files manually, and then added / deleted them.
this would mean you lose the ability to git blame easily.

**Comment by ohadlevy** [comment]
why did you leave the control mixin under /lib ?

**Comment by isratrade** [comment]
@ohadlevy 

I moved the files using git mv.  I will look to see if there's a way that keeps git blame information.

I will move HostTemplateHelpers to models/concerns

I plan to move the /lib controller related mixins to app/controllers/concerns in the next commit.  I wanted the first commit just to mostly clean up /models. Btw, app/controllers/concerns will be in the default load path in Rails 4

**Comment by ohadlevy** [comment]
@isratrade, i'm closing this one, in favor of redoing it again after 1.1 is released as part of the upgrade to rails 3.2

**Pull request closed without merging**
