### PR TITLE
fixes #2741 - remove dash from -%> to %>

### PR DESCRIPTION
**Pull request by isratrade**
I'm pretty sure that -%> is a Rails 2.x syntax.  Here's what the current docs say.
http://api.rubyonrails.org/classes/ActionView/Base.html

<%- and -%> suppress leading and trailing whitespace, including the trailing newline, and can be used interchangeably with <% and %>.

### CODE REVIEW

**Comment by dmitri-d** [comment]
lgtm.

**Comment by ares** [comment]
:+1:

**Comment by ohadlevy** [comment]
my tests claim differently... whitespaces are added to the file.

reading the docs again, does claim that <%- -%> removes whitespaces, where <% %> will not.

so imho, unless you want the whitespaces, you should still use <%- -%>

imho, we should change this PR to keep the -%> from empty lines.. e.g.

``` erb
<% if true -%> 
...
<% end -%>
```

but remove them where they are not needed, e.g.

``` erb
<h1>hello <%= 'world' -%>
```

**Comment by isratrade** [comment]
I don't see any difference in the html page source for .html.erb files when I use -%> or %>
<% if true %> does not add a blank line

**Comment by dmitri-d** [comment]
when using ERB directly I can see the difference in output, ie: ERB.new("<% if true %>\n<%= 'aaa' %>\n<% end %>", nil, '-').result and ERB.new("<% if true -%>\n<%= 'aaa' %>\n<%- end -%>", nil, '-').result have expected differences (no "\n" before the text string the latter case).

I cannot see any difference in rendered html templates however.

**Comment by isratrade** [comment]
@witlessbird, thanks for checking this. +1

**Comment by ohadlevy** [comment]
[test]

**Comment by isratrade** [comment]
@domcleal, can this be merged?

**Comment by domcleal** [comment]
It can, but I'd like to wait until we're out of the 1.3 window as it could make cherry picking harder than we need.  It's never really struck me as urgent :)

Could you check these others please, probably from recent patches?

<pre>
app/views/common/_puppetclasses_or_envs_changed.html.erb
42:        &lt;% end -%>
43:      &lt;% end -%>
44:    &lt;% end -%>
app/views/compute_resources_vms/show/_gce.html.erb
23:    &lt;% if @vm.public_ip_address.present? -%>
28:    &lt;% end -%>
app/views/compute_resources_vms/form/_ec2.html.erb
12:&lt;% if compute_resource.subnets.any? -%>
16:&lt;% end -%>
app/views/compute_resources_vms/form/_gce.html.erb
5:-%>
app/views/compute_resources_vms/form/vmware/_network.html.erb
2:  &lt;% if (networks = compute_resource.networks).any? -%>
app/views/compute_resources_vms/index/_gce.html.erb
4:    &lt;th>&lt;%= _('Name') -%>&lt;/th>
5:    &lt;th>&lt;%= _('Type') -%>&lt;/th>
6:    &lt;th>&lt;%= _('State') -%>&lt;/th>
10:  &lt;% @vms.each do |vm| -%>
19:  &lt;% end -%>
app/views/operatingsystems/_form.html.erb
6:    &lt;% if SETTINGS[:unattended] -%>
</pre>

**Comment by isratrade** [comment]
thanks @domcleal, I updated the new files in a separate commit that can be squashed.

**Comment by isratrade** [comment]
rebased and ready for merge now that 1.3 is released.

**Comment by domcleal** [comment]
Merged as 4d4557e909, thanks @isratrade!

**Pull request closed without merging**
