### PR TITLE
fixes #7764 - pin json gem to version 1.8

### PR DESCRIPTION
**Pull request by shlomizadok**
Also creates same issue with foreman_openscap policies.

### CODE REVIEW

**Comment by domcleal** [comment]
We currently rely on ruby193's JSON RPM and I'm not particularly keen on distributing another right now.  Moving to a newer software collection or our own will make this easier to update.

Is the issue in the description still reproducible, or is this only a separate issue you're trying to fix?

**Comment by shlomizadok** [comment]
I am also creating a rubygem-json package, will send a pr to foreman-packaging as I finish.
I have the same issue on foreman_openscap with json-1.5.5, also on the lookup_key, with the same error:

``` log
only generation of JSON objects or arrays allowed
...
app/models/lookup_key.rb:138:in `value_before_type_cast'
app/helpers/lookup_keys_helper.rb:75:in `hostgroup_key_with_diagnostic'
```

Updating the json gem version will solve both.

**Comment by domcleal** [comment]
Creating the package isn't really the problem (we already have it), it's that it replaces a component of the existing SCL, which I'm not keen to do.

**Comment by shlomizadok** [comment]
I have not found the json package on foreman-packaging.
I am neither keen to replace and existing SCL - but haven't find a way around it.

**Comment by domcleal** [comment]
It's not in foreman-packaigng, because it's part of the SCL.  It will be easier to adopt a newer version of JSON when we move to Rails 4 or our own software collection, which is very likely in the next release cycle IMO.

**Comment by ohadlevy** [comment]
@shlomizadok is this a total blocker for openscap? are there any workarounds ?@domcleal if it is, do we have any other option?

**Pull request closed without merging**
