### PR TITLE
Fixes #19921 - Upgrade fast-gettext to 1.4 or newer

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
Test failures are unrelated.

**Comment by dLobatog** [comment]
Thanks @tbrisker !

**Comment by dLobatog** [comment]
@tbrisker Mind updating https://github.com/theforeman/foreman-packaging/tree/rpm/develop/rubygem-fast_gettext & foreman.spec? They're 1.1.0 now

**Comment by tbrisker** [comment]
@dLobatog Thanks, opened https://github.com/theforeman/foreman-packaging/pull/1682

**Pull request merged**
