### PR TITLE
Fixes #6476 - oVirt VM association with multiple interfaces

### PR DESCRIPTION
**Pull request by treydock**
I have no tests with this PR.  I could not work out how to unit test an instance of Fog::Compute::Ovirt::Server and as far as I could tell no tests already existed for the majority of the Foreman::Model::Ovirt class.

I'd be happy to add tests if someone can offer some guidance or examples to reference.

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
Looks good, thank you! 

There are some tests for Vmware that you could use as a template for Ovirt, it should be rather straightforward, let us know if you need some help here or in #theforeman-dev

https://github.com/theforeman/foreman/blob/develop/test/unit/compute_resources/vmware_test.rb

**Comment by domcleal** [comment]
I've added a test in #1693.

**Comment by domcleal** [comment]
Merged as 5743465 for Foreman 1.6.0-RC2, thanks @treydock!

**Pull request closed without merging**
