### PR TITLE
Fixes #25428 - fixed telemetry plugin API const error

### PR DESCRIPTION
**Pull request by lzap**
This sneaked in, apparently no plugins are using telemetry yet!

### CODE REVIEW

**Comment by mmoll** [comment]
I didn't test this... for consistency reasons, would `Foreman::Telemetry::DEFAULT_BUCKETS` also work in plugins?

**Comment by lzap** [comment]
Sorry what, you want me to write it `Foreman::Telemetry::DEFAULT_BUCKETS` ?

**Comment by mmoll** [comment]
@lzap exactly :+1:

**Comment by lzap** [comment]
Sure thing. Done.

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
