### PR TITLE
Fixes #4486 - organization not searchable by name

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by domcleal** [comment]
Couple of notes while I think of them:
- scoped_search on name is defined also in the hostgroup model, it should be removed there?
- scoped_search on name is already defined in app/models/taxonomies/*, why isn't this working?
- I don't think http://projects.theforeman.org/issues/4443 is a dupe, since the error is a PostgreSQL error due to using title in the default_scope ordering when it isn't in the SELECT list.

**Comment by tstrachota** [comment]
You're correct, it's not a dupe. I'll undo relations on the issues and try to investigate about the first two bullets.

**Comment by dLobatog** [comment]
Point 2 noted by @domcleal happens because of the way the SQL query is constructed from scoped_search, I submitted an alternative way of fixing this that removes the unnecessary scoped_search scopes in `Organization` and `Location`, see https://github.com/theforeman/foreman/pull/1279

**Comment by tstrachota** [comment]
I looked at the double scoped_search definition problem:
Removing the scoped_search from Organization and Location breaks the search completion. It seems to be a singleton class issue. `search_for` scope correctly uses definition from the super class (I guess this is thanks to Rails' implementation) while the completion looks into the class' scoped_search definition that is empty when it's defined in the superclass.

It's ugly duplicity but I vote for filing a bug against scoped_search and keeping it there until it's fixed. What do you think?

**Comment by domcleal** [comment]
@tstrachota sounds fair (even better if you or @abenari can send a PR), so we need to ensure these are duplicated?

**Comment by abenari** [comment]
The completer code that guess the model name from controller name is in foreman:
https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/foreman/controller/auto_complete_search.rb#L6
This looks like the line that needs fixing. We might want to add code for the org/location as we did for hosts here.

**Comment by tstrachota** [comment]
@abenari this line actually works. It finds correct model (`Organization` in our case) but calling `complete_for` on that model fails. More precisely it returns only `and`, `or` as it doesn't find any searchable attributes.
We can temporarily tweak the line you suggested but I still consider more systematic to have it fixed in scoped search.

**Comment by tstrachota** [comment]
OK, I'm taking it back. The tweak @abenari suggested doesn't work. I tried to use Taxonomy model for orgs and locations. It completes the attribute names correctly but the values are then mixed from both Location and Organization. I've ran out of ideas.
@abenari can you live with duplicate scoped search definition? Any better solution would be welcome.

**Comment by abenari** [comment]
@tstrachota I am good with duplicated definition with a one-line of comment that explains it.

**Comment by domcleal** [comment]
I'd suggest filing an issue against scoped_search and a refactor issue in redmine so we can remove it later, once fixed.

**Comment by tstrachota** [comment]
Good, I'll do so. Thanks for opinions, guys.

**Comment by tstrachota** [comment]
Code updated + new refactor issue http://projects.theforeman.org/issues/4613

**Comment by domcleal** [comment]
Merged as ca27623 for Foreman 1.5.0, thanks @tstrachota!

**Pull request closed without merging**
