### PR TITLE
Fixes #32266 - render_error call in userdata fixed

### PR DESCRIPTION
**Pull request by lzap**
The method requires string and hash not just hash.

### CODE REVIEW

**Review by ofedoren — COMMENTED** [review]
Thanks, @lzap. LGTM, but don't we want to have this string translated?

**Review by timogoebel — DISMISSED** [review]

**Comment by lzap** [comment]
Thank you, Maria noticed that the messages are untranslated, it looks like we do translate them in unattended_controller so I am amending a change.

**Review by timogoebel — APPROVED** [review]

**Review by ofedoren — APPROVED** [review]
Thanks, @lzap! Merging.

**Comment by ezr-ondrej** [comment]
CP 2.4: #8504

**Pull request merged**
