### PR TITLE
fixes #6487 - use consistent icon set

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
Tell me what you think :-)

**Comment by isratrade** [comment]
+1 from me

**Comment by dLobatog** [comment]
[test] , because Katello tests are failing :+1: if OK.

**Comment by lzap** [comment]
@mmoll you said that you don't like the BSD icon on IRC the other day. Can you elaborate?

@ohadlevy @domcleal Greg? (sorry can't spell the nick out of my head and github is not helping me out :-)

**Comment by lzap** [comment]
Note: I am leaving original icons of all open source projects and replacing only those dummy ones. For the BSD, I was thinking leaving it as is, but to me it's little bit unclear (for me, not UX designer), so I am providing an example how would it look like. If you prefer the original one, I will drop it.

**Comment by mmoll** [comment]
I think the old Darwin one is OK to use. http://www.hexley.com/ sounds quite liberal, but IANAL.

**Comment by lzap** [comment]
> I think the old Darwin one is OK to use. http://www.hexley.com/ sounds quite liberal, but IANAL.

Oh that tiny little 21px daemon holding something ... yeah. Unreadable
for me :-)

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by mmoll** [comment]
:mag_right: time to use the :mag:  ;)

**Comment by GregSutcliffe** [comment]
@lzap my username is GregSutcliffe on here, it's the one place I don't use gwmngilfen :P

I'm fine with this PR, for the record :)

**Comment by lzap** [comment]
Uh thanks all

Not sure if I can follow "small patch, author to merge" policy here.

LZ

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Please don't.

**Comment by dLobatog** [comment]
I think that's not Foreman's policy is it?

**Comment by lzap** [comment]
I heard it discussed, if you say so.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Sorry, this might just be OCD, but it's bugging me that the letters aren't centred in the circles.. they're all a pixel off.  Is it possible to fix - maybe reducing the width to an even number, or using some anti-aliasing on the letter?

**Comment by lzap** [comment]
Facepalm.

https://github.com/lzap/foreman-dummy-icons/commit/2f71843399310046fe7bf8ba3f757d3e8eeaee7e

Easy to generate, but I will need to pick icons up again. Will make a
script for this for future cases.

## 

Later,
 Lukas "lzap" Zapletal

**Comment by lzap** [comment]
I fixed the pixel off, we can regenerate if you won't like it. You know, we just want to make you happy once you return back, so I have to merge this one :-)

Merged as 11153f1 for Foreman 1.6!

**Pull request closed without merging**
