### PR TITLE
fixes #3169 - configurable page title

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by lzap** [comment]
LGTM +1

**Comment by domcleal** [comment]
Closing, as agreed I don't think this needs to be configurable in the app.

**Comment by lzap** [comment]
But it could still be a read-only option in settings.yaml...

## LZ

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Yeah, but I see it as a slippery slope.  I don't think we want to make the UI configurable to this extent.

**Comment by GregSutcliffe** [comment]
JFTR, I'm with Dominic on this.

**Pull request closed without merging**
