### PR TITLE
fixes #6177 - clear host facts/reports when build=true set over API

### PR DESCRIPTION
**Pull request by domcleal**
Ignore the test failure on Katello, that's some other problem.  Foreman's passing fine.

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1: I assume the test failure is unrelated?

**Comment by domcleal** [comment]
Indeed, something's up with katello tests generally.

**Comment by domcleal** [comment]
[test]

**Comment by GregSutcliffe** [comment]
Massive :+1: for the extensions in the Host Factory, they're really taking shape now. Tested the PR locally, works great. Merge at will.

**Comment by ohadlevy** [comment]
merged as aa19255

**Pull request closed without merging**
