### PR TITLE
Fixes #17874 - Extract contains_erb? from lookup key

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]
@tbrisker : Looks good to me. Thanks for improving the code.

**Comment by timogoebel** [comment]
@tbrisker : Please rebase and we're ready to go.

**Comment by tbrisker** [comment]
@timogoebel rebased, thanks.

**Comment by timogoebel** [comment]
Merged, thanks @tbrisker.

**Pull request merged**
