### PR TITLE
fixes #12612 - Update fog to 1.37.0

### PR DESCRIPTION
**Pull request by timogoebel**
- Update fog to 1.37.0
- Add fog-vsphere
- Add a require when loading the fog extensions, see https://github.com/fog/fog-vsphere/issues/10

### CODE REVIEW

**Comment by timogoebel** [comment]
Let's wait for tests...

**Comment by dLobatog** [comment]
@timogoebel Thanks! I can do some basic testing with AWS, Openstack, DigitalOcean, Google Compute Engine, and Libvirt. If someone could do the same with Rackspace / Vmware / oVirt (or any of the ones I mentioned as well) that'd be helpful.
- [x] AWS
- [x] VMWare
- [x] Libvirt
- [x] OpenStack
- [ ] DigitalOcean
- [x] Rackspace
- [x] oVirt
- [x] Google Compute Engine

**Comment by timogoebel** [comment]
@dLobatog : I tested vmware. That still works. I can ask a co-worker to test as well if we need a second opinion.

**Comment by timogoebel** [comment]
@dLobatog : Happy new year! :-) How can we continue work on this?

**Comment by dLobatog** [comment]
@timogoebel I'll test DO and GCE today, sorry for the delay. Happy new year!

**Comment by dLobatog** [comment]
DO won't work but that's fine, it's because the plugin doesn't use API v2 yet and v1 doesn't work anymore. GCE works fine.

**Comment by domcleal** [comment]
Rackspace works fine, though I hit an unrelated bug filed as http://projects.theforeman.org/issues/13084.

**Comment by timogoebel** [comment]
Awesome, that everything still seems to work. @dLobatog: Are we ready to merge this? Do we need someone to test ovirt?

**Comment by lzap** [comment]
I am on it. Hold on.

**Comment by lzap** [comment]
So I was testing this rebased on `develop` and with https://github.com/theforeman/foreman/pull/3051 patch because of the Rails 4.1 bugfix described there. It works. Tested with oVirt Engine Version: 3.6.1.3-1.el7.centos7.

**Comment by dLobatog** [comment]
Merged as e35faf64a7ca1aa07c249397a7ea701d61a451b3, thanks @timogoebel!

**Pull request closed without merging**
