### PR TITLE
fixes #5965: removed 8443 port from the suggested ovirt url

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dLobatog** [comment]
Shouldn't it be 443 instead of nothing at all?

**Comment by domcleal** [comment]
443's implied if the protocol's "https".

**Comment by dLobatog** [comment]
Oh right, dumb me. Will merge in a second.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/9557f30c0282db2c595450fd44298fe9b1d5d6a0 , thanks @domcleal & @witlessbird !

**Pull request closed without merging**
