### PR TITLE
Fixes #30246 - Upgrade vendor to v4.11.1

### PR DESCRIPTION
**Pull request by sharvit**
This would use the version with the pf4 v4: https://github.com/theforeman/foreman-js/pull/142

packaging: https://github.com/theforeman/foreman-packaging/pull/5491

### CODE REVIEW

**Comment by sharvit** [comment]
foreman-tasks: https://github.com/theforeman/foreman-tasks/pull/567
katello: https://github.com/Katello/katello/pull/8795

**Comment by sharvit** [comment]
I found the root for many of the "testing" issues that also caused this issue where it resolves the wrong library when testing.
I could fix that locally with some changes in tfm-test.

PR soon

**Comment by sharvit** [comment]
This should fix the testing issue https://github.com/theforeman/foreman-js/pull/145

**Comment by sharvit** [comment]
Look like it doesn't resolve the custom-modules well in node-10, will need to send another fix to tfm-test

**Comment by sharvit** [comment]
This should fix the nodejs-10 issue: https://github.com/theforeman/foreman-js/pull/146

**Comment by tbrisker** [comment]
@sharvit looks like the issue is still present in 4.10.2 as well.

**Comment by sharvit** [comment]
@tbrisker, unfortunately, but this should fix that: https://github.com/theforeman/foreman-js/pull/146

**Comment by Ron-Lavi** [comment]
looks like @theforeman packages are now upgraded to `v4.11.0` which should fix the jest errors :)
can you re-run the tests?

**Comment by sharvit** [comment]
> looks like @theforeman packages are now upgraded to `v4.11.0` which should fix the jest errors :)
> can you re-run the tests?

Yes, updating the package.json to use the fixed version

**Comment by sharvit** [comment]
Bahhh it fails again, the error is when you use tfm-test from npm :/

**Comment by sharvit** [comment]
It is finally green :)

**Review by Ron-Lavi — DISMISSED** [review]
Thanks @sharvit ! LGTM :)

**Comment by sharvit** [comment]
updated the commit message and created packaging pr https://github.com/theforeman/foreman-packaging/pull/5521

**Review by tbrisker — APPROVED** [review]
Thanks @sharvit , waiting for the butler to finish before merging.

**Pull request merged**
