### PR TITLE
fixes #16089 - replace flot-rails with npm jquery-flot

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by tbrisker** [comment]
@domcleal Thanks, though I wonder if we should bother with this since flot.js is unmaintained and there is a PR in progress to replace flot with c3? (https://github.com/theforeman/foreman/pull/3603)

**Comment by domcleal** [comment]
That PR doesn't remove flot-rails as a dependency, which is what I'm trying to fix in this issue. It's also only WIP, not in a reviewable state.

**Comment by tbrisker** [comment]
@domcleal Very well. This works well, merging.

**Comment by tbrisker** [comment]
Merged as 551407c293a9b60cc39e319d108f97e47dcb06b1, thanks @domcleal!

**Pull request closed without merging**
