### PR TITLE
Fixes #34219 - Add page title to Host Detail

### PR DESCRIPTION
**Pull request by kmalyjur**
Adds the host's name as the title of the Host Detail page.

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]
Works well

**Comment by adamruzicka** [comment]
Thank you @kmalyjur !

**Comment by ekohl** [comment]
@adamruzicka this should go into 3.5, correct?

**Comment by adamruzicka** [comment]
It would be nice to have it in 3.5

**Pull request merged**
