### PR TITLE
fixes #6267 - singularize of HostClass and HostgroupClass is wrong

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
This seems to be a rails bug.

> "Class".singularize
> => "Clas"

**Comment by domcleal** [comment]
Maybe update test/lib/inflection_test.rb?

**Comment by isratrade** [comment]
re-committed with tests

**Comment by domcleal** [comment]
Merged as 7f7c531 for Foreman 1.6.0, thanks @isratrade.

**Pull request closed without merging**
