### PR TITLE
Fixes #27786 - fix scss link to pf-react

### PR DESCRIPTION
**Pull request by sharvit**
Should fix: https://community.theforeman.org/t/foreman-develop-package-release-170-failed/15263

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @sharvit ! test failure unrelated. Is there a way we can make errors like this fail tests at the PR level instead of finding them in nightlies?
 
fyi, in the future if you are sending a followup to a previous PR that still hasn't been released you can use `Refs #...` instead of opening a new issue, that way if the commit is cherry-picked to stable branches the follow-up won't be missed.

**Comment by sharvit** [comment]
> Thanks @sharvit ! test failure unrelated. Is there a way we can make errors like this fail tests at the PR level instead of finding them in nightlies?

Yes, `webpack build` would produce those errors so triggering a build in a test pipeline makes sense to me.



> fyi, in the future if you are sending a followup to a previous PR that still hasn't been released you can use `Refs #...` instead of opening a new issue, that way if the commit is cherry-picked to stable branches the follow-up won't be missed.

:+1:

**Comment by tbrisker** [comment]
We do build webpack for the integration tests, but looks like it passed in this case: https://ci.theforeman.org/job/test_develop_pr_core/1955/database=postgresql-integrations,ruby=2.5,slave=fast/consoleFull

**Comment by sharvit** [comment]
> We do build webpack for the integration tests, but looks like it passed in this case: https://ci.theforeman.org/job/test_develop_pr_core/1955/database=postgresql-integrations,ruby=2.5,slave=fast/consoleFull

It works because it installs `devDependencies`, therefore it install `@theforeman/vendor-dev` that installs `patternfly-react` so you end up having the `patternfly-react` module.

**Pull request merged**
