### PR TITLE
Fixes #19787 - Fix Layout/SpaceAfterComma cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Personally I prefer the style the cop enforces, but wouldn't be really sad if others want to have the cop disabled.

Opinions?

**Review by ekohl — APPROVED** [review]
Though not involved in core that much, I personally like this style for readability.

**Review by tbrisker — APPROVED** [review]
I agree, this improves readability, I'll give it another day or two just in case others object.

**Comment by tbrisker** [comment]
Looks like there aren't any objections, merging. Thanks @mmoll !

**Pull request merged**
