### PR TITLE
refs #4305 - add support for OracleLinux

### PR DESCRIPTION
**Pull request by mmoll**
The icon was made with The GIMP and the Liberation Sans Bold font

### CODE REVIEW

**Comment by skottler** [comment]
I wonder if we're allowed to use the Oracle Linux name with our own logo. Have you checked on that @mmoll?

**Comment by mmoll** [comment]
@skottler Hm, damn good question, what do the licensing experts say on paragraph 4 of https://oss.oracle.com/ol6/EULA ? @domcleal maybe?

**Comment by skottler** [comment]
@mmoll I believe that shipping a variant of their logo would be in violation of what they lay out in the EULA and might also be a trademark issue.

**Comment by mmoll** [comment]
Going for the "JunOS solution" then ;)

**Comment by lzap** [comment]
This is already the second time when we are facing this. I wonder if we want to create/use some kind of icon set that would give our users good experience so we do not need to reinvent the wheel in GIMP everytime.

I have no idea with the trademark, but don't we use other trademarked names like RHEL, Ubuntu, OpenSUSE already?

**Comment by skottler** [comment]
@lzap yeah, but the issue isn't with the trademark itself. It's that we're attaching an unofficial logo to the trademarked name. I'm not a lawyer, though, so we should actually verify that it's an issue.

**Comment by dLobatog** [comment]
Judging by this commit, `OracleLinux` is the string that comes from Facter so... https://github.com/puppetlabs/facter/commit/d55983e3a44ce9431e8c6e03928ae1810f54096d

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/foreman/commit/b13262944f99a2e4c3c65f6ba084a530d45e2e02 , thanks @mmoll !

**Pull request closed without merging**
