### PR TITLE
Fixes #26085 - Set default taxonomy setting to seeded taxonomies

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by kgaikwad** [comment]
@tbrisker
I think, issue id is different as per PR commit message.

**Comment by tbrisker** [comment]
@kgaikwad oops, my mistake. thanks for noticing!

**Comment by tbrisker** [comment]
This is https://projects.theforeman.org/issues/26085 - the bot missed linking it.

**Comment by xprazak2** [comment]
Updates the setting values, the default values remain not set. This means that when someone changes the value, UI does not show it in bold to indicate it differs from default. On the other hand, if we set it as default value and users delete that org/loc, they are stuck with default value pointing to deleted record and no way to update it, which is not good.

I think it is ok as it is and leave the defaults blank.

location-setting

**Review by xprazak2 — APPROVED** [review]

**Comment by xprazak2** [comment]
Unless anyone has concerns regarding the defaults, I think we can merge.

**Comment by xprazak2** [comment]
Thanks!

**Comment by tbrisker** [comment]
Thanks, cherry-picked to 1.21 as b7dbbcc7b

**Pull request merged**
