### PR TITLE
Fixes #25451 - Make certificate loading robust

### PR DESCRIPTION
**Pull request by ekohl**
This is copied from Katello's app/services/cert/rhsm_client.rb which should probably be merged in a cleaner way.

### CODE REVIEW

**Comment by ehelms** [comment]
I tested this code change on nightly and the puppet bats tests passed. So if unit tests are happy, I think this is good by me and the WIP can be dropped.

**Comment by ekohl** [comment]
I've added some tests, created an issue and dropped the WIP. Ready for review now.

**Comment by timogoebel** [comment]
Two test classes in a single file aren't the rails way (at least with my limited understanding). I would have used two `context` blocks. Otherwise, this looks good. I'd be ok to merge this.

**Comment by ekohl** [comment]
I agree this looks cleaner.

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks, @ekohl.

**Pull request merged**
