### PR TITLE
refs #18264 - remove text order assumption in response body test

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@domcleal any idea why the tests failed? thanks.

**Comment by domcleal** [comment]
One is in a completely different test (AboutIntegrationTest), and the other two state that the slave was taken offline by me (as it was faulty).

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
@domcleal this fails now due to 
```
Capybara::ElementNotFound: Unable to find field "compute_resource_password"...
Stacktrace

Capybara::ElementNotFound: Unable to find field "compute_resource_password"
    test/integration/compute_resource_js_test.rb:46:in `block in <class:ComputeResourceJSIntegrationTest>' (Capybara::ElementNotFound)
/usr/local/rvm/gems/ruby-2.1.5@test_develop_pr_core-0/gems/capybara-2.13.0/lib/capybara/node/finders.rb:44    
```
wasnt this fixed as part of commit: e53fd8e1b24fe7d0d578bb73243a0c28d66e7638 ?

**Comment by domcleal** [comment]
No, e53fd8e fixes the error reported at #4397. Again, I don't see that it's related to this test.

**Comment by ohadlevy** [comment]
@domcleal its not, I'm trying to understand if your branch is not rebased or if we have a new test failure.

regardless, thanks, merging..

**Comment by domcleal** [comment]
The grandparent of this commit is e53fd8e: https://github.com/theforeman/foreman/commits/62546226ed3af9be7d3cfec5f35c59ed25fb979b

**Pull request merged**
