### PR TITLE
Fixes #22747 vet puppetclass_id on addition

### PR DESCRIPTION
**Pull request by iwalmsley**
setting validation on create, adding test

### CODE REVIEW

**Review by dLobatog — COMMENTED** [review]
@iwalmsley Looks good, will merge if tests pass.

**Comment by dLobatog** [comment]
[test]
[test develop]
[test upgrade]
[test katello]

**Review by dLobatog — APPROVED** [review]
Thanks @iwalmsley

**Comment by iwalmsley** [comment]
Thank you very much.

**Pull request merged**
