### PR TITLE
Fixes #2408: don't try to reset the password in rake permissions:reset i...

### PR DESCRIPTION
**Pull request by skottler**
...f Facter.domain is nil

### CODE REVIEW

**Comment by ohadlevy** [comment]
@skottler any idea why it fails?

**Comment by skottler** [comment]
Why the domain isn't set on the machine then creation of the User object fails because the domain is invalid and mail subsequently can't be delivered.

**Comment by ohadlevy** [comment]
@skottler i meant the test :)

**Comment by skottler** [comment]
Whoops! Not sure why it fails, but I just kicked off a fresh build since it seems likely it was just an intermittent failure.

**Comment by skottler** [comment]
http://ci.theforeman.org/view/PR%20Tests/job/test_develop_pull_request/287/ failed in a completely different way, but not with the same error so I _think_ this is fine :8ball:

**Comment by domcleal** [comment]
:+1: ignore that test failure. [test]

**Comment by ohadlevy** [comment]
merged - thanks

**Pull request closed without merging**
