### PR TITLE
Fixes #14191 - remove simplecov test coverage reporting

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
Currently the entire pull request test suite runs at about 1:02-1:08 hours, let's see how much this improves it.

**Comment by domcleal** [comment]
1:02-1:08 isn't correct, it's closer to 15 to 25 minutes depending on which tests are running, versions of Ruby etc.  I guess you're taking queue times into account, which isn't helpful.  Slaves are also of varying performance and run many tests in parallel, so please don't use timings for performance comparisons.

I left a comment on the ticket too.

**Comment by dLobatog** [comment]
I'd say YAGNI to this gem - if we ever want to measure this, adding it back is fairly trivial. So :+1:

**Comment by domcleal** [comment]
Alright, merged as 1680e94, thanks @tbrisker.

**Pull request closed without merging**
