### PR TITLE
fixes #5443 - cron.log is now properly rotated

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
Can you file a PR for Debian too please?

**Comment by lzap** [comment]
We don't share this? Hmmm

Where do I find Debian cron files?

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
This is in the "rpm" path ;)

They're in foreman-packaging, deb/develop branch.

**Comment by lzap** [comment]
https://github.com/theforeman/foreman-packaging/pull/226

**Comment by domcleal** [comment]
Merged as 3307133 for Foreman 1.5.0, thanks @lzap!

**Pull request closed without merging**
