### PR TITLE
Fixes #35894 - Properly detect setting changes

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Oh my... right, sorry :( this seems to be quite safe solution and with the cache it should not impact the performance almost at all :+1:

**Comment by stejskalleos** [comment]
@adamruzicka Do we have steps how to reproduce the issue that is being fixed here?

**Comment by adamruzicka** [comment]
They're in the issue. Edit: Also the test hints towards it

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected

**Comment by stejskalleos** [comment]
Thanks @adamruzicka @ezr-ondrej !

**Pull request merged**
