### PR TITLE
Fixes #27249 - flip the comma cop

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by ekohl — DISMISSED** [review]

**Review by ezr-ondrej — DISMISSED** [review]
Now with the javascript around, where we are forcing it I agree it should be the same for Ruby :+1:

**Comment by mmoll** [comment]
Should TrailingCommaInHashLiteral also get enabled similarly?

**Comment by ares** [comment]
I repushed also with TrailingCommaInHashLiteral set the same way, asking @theforeman/core for votes, so far we have +2/-0

**Comment by tbrisker** [comment]
looks like you need to rebase, but big +1 from me

**Comment by ares** [comment]
I had to rebase already, I'd appreciate to get this in soon, to avoid rebasing whenever someone extends a hash/array :-)

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
