### PR TITLE
fixes #25136 - fix infinite loop in autoyast templates

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by mmoll** [comment]
@timogoebel I guess you tested this also on develop and it's already fixed differently there?

**Comment by timogoebel** [comment]
@mmoll: Yeah, develop is not affected. We solved this with the new renderer. @kamils-iRonin might even remember how.

**Comment by kamils-iRonin** [comment]
@timogoebel @mmoll as far as I remember we have `Foreman::Renderer::Scope::Partition` scope in which we do not load variables

**Comment by timogoebel** [comment]
I might have a less invasive solution for this. Please do not merge, yet.

**Comment by timogoebel** [comment]
Pushed another version, this now also fixes the detection of dynamic templates. We have to check on every line if it's a dynamic template. The first line is metadata in our case.

**Comment by timogoebel** [comment]
The latter might be required for develop as well, I have to check.

**Comment by timogoebel** [comment]
[test katello]

**Comment by ekohl** [comment]
FYI: the bot should automatically add the `Stable branch` label

**Review by tbrisker — COMMENTED** [review]
Thanks @timogoebel !

**Review by tbrisker — APPROVED** [review]

**Pull request merged**
