### PR TITLE
Refs #9673 - Return value if type cast failed during classification

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by domcleal** [comment]
`fixes #9673`, or is this a partial fix?

**Comment by GregSutcliffe** [comment]
@domcleal This was the hack I gave the user on IRC (thanks @eLobato!), which allowed him to progress. I'd like @ares to review and see if there's some underlying reason why yaml was being converted to a hash and (failing to go) back to yaml. I don't want to obscure an issue if it's going to hit that rescue _every_ time...

**Comment by ares** [comment]
I think this should be closed since https://github.com/theforeman/foreman/pull/2232 replaces it.

**Comment by GregSutcliffe** [comment]
:+1: to closing

**Pull request closed without merging**
