### PR TITLE
Fixes #36656 - Pin @adobe/css-tools to 4.2.0

### PR DESCRIPTION
**Pull request by nofaralfasi**
(cherry picked from commit 7b74d9dc5508ba412154ad6ecde4b2fb0ea3b2e0)

Blocks:
* https://github.com/theforeman/foreman_ansible/pull/654

### CODE REVIEW

**Comment by nofaralfasi** [comment]
test_js (12) are failing in foreman_ansible 10.0-stable branch. 
Fixing this from the foreman_ansible plugin didn't work - https://github.com/theforeman/foreman_ansible/pull/661

**Comment by MariaAga** [comment]
@nofaralfasi are the test failures related?

**Comment by nofaralfasi** [comment]
> @nofaralfasi are the test failures related?

Not as far as I know.

**Review by MariaAga — APPROVED** [review]
tested and looks like this is not breaking anything

**Comment by nofaralfasi** [comment]
Thanks @MariaAga! The tests are passing in foreman_ansible.

**Pull request merged**
