### PR TITLE
fixes #9782 - implement mediapath for suse/yast

### PR DESCRIPTION
**Pull request by mmoll**
basically GH-2393, but after 3b75c0a this works now.

### CODE REVIEW

**Comment by ares** [comment]
Thanks @mmoll, it looks like tests are failing. I guess suse fixtures needs some tweaks but I didn't check details.

**Comment by mmoll** [comment]
indeed, fixed. :green_heart:

**Comment by iNecas** [comment]
Tested and I can confirm it addes the `@mediapath` to the suse templates correctly. ACK

**Comment by dLobatog** [comment]
Merged as 7aa342eabf33f96916f3061db313aecba46b0933, thanks @mmoll!

**Pull request closed without merging**
