### PR TITLE
Fixes #37061 - Mention SEED_ADMIN_PASSWORD in DEV docs

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Please motivate why this is a good thing. There is no context in the issue or in the commit message. Explaining your thought process is very important to me.

**Comment by stejskalleos** [comment]
@ekohl sorry, was too hasty with pushing the PR, thinking "the headline" is enough.

Commit message & PR description update.

**Review by ofedoren — COMMENTED** [review]
I'm kinda okay with the changes.

Question though: if it's more for the newcomers, should we maybe point out in the docs that for custom passwords `SEED_ADMIN_PASSWORD` env variable can/should be used instead? I guess the first thing what a newcomer would do is to read installation steps anyway...

**Comment by stejskalleos** [comment]
`SEED_ADMIN_PASSWORD` added to the DEV doc

**Review by ofedoren — COMMENTED** [review]
Well, if we have it mentioned in the docs, why would we have the default `changeme` anyway? :)

**Comment by stejskalleos** [comment]
:thinking: I guess you are right, document it is enough.

**Comment by ofedoren** [comment]
Well, LGTM, but it appears that we have the same as part of https://github.com/theforeman/foreman/pull/9906. Should we maybe merge that instead? (sorry @stejskalleos, should've found it earlier than make you make changes here :/)

**Comment by ekohl** [comment]
I've merged my own PR since I can bypass the checks. I think that obsoletes this PR.

**Pull request closed without merging**
