### PR TITLE
Fixes #23857 - Fix Performance/InefficientHashSearch cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Rubocop 0.56+ has this check and because we use hound, we can't check and enforce this right now. However, I think the [spectacular performance improvement](https://github.com/JuanitoFatas/fast-ruby#hashkey-instead-of-hashkeysinclude-code) justifies to bring in this change now.

**Comment by mmoll** [comment]
AFAICT, the two failing tests point to a problem in these tests (or the code they should test), investigating...

**Comment by tbrisker** [comment]
@mmoll tests should be fixed with the merge of GH-5679, please rebase

**Comment by mmoll** [comment]
katello test filters unrelated :green_heart:

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
