### PR TITLE
Fixes #26924 - Deprecate rake taks for puppet import

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I'm strongly in favor of this and IMHO this should be cherry picked into 1.22.

**Comment by ares** [comment]
I agree with @ekohl re cherry-picking

**Review by tbrisker — APPROVED** [review]
Thanks @xprazak2 !

**Comment by tbrisker** [comment]
1.22 - 833831edd

**Pull request merged**
