### PR TITLE
Fixes # 33665 - add AppStream repo for Rocky Linux installs

### PR DESCRIPTION
**Pull request by Bonehead5338**
Rocky install failed with missing package wget without this

https://projects.theforeman.org/issues/33665

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Review by lzap — APPROVED** [review]
The failure is unrelated.

**Comment by lzap** [comment]
I am taking a deeper look on this hack, looks like it breaks things for some scenarios. Hold on.

**Comment by lzap** [comment]
So I did some testing today, not Rocky but CentOS 8 Stream, and it looks like this workaround is not needed at all. Can you take a look:

https://community.theforeman.org/t/testing-of-centos-alma-rocky-8-apprepo/25649

**Comment by Bonehead5338** [comment]
@lzap I can try again and report back. My Rocky 8.4 install wouldn;t complete without it though. The before/after result would not be different for anything matching 'centos' in the name as the logic is the same. The logic is only different for those matching 'rocky'. I just moved the string-matching piece up to a variable.

**Comment by Bonehead5338** [comment]
Default Template:
```
# This kickstart file was rendered from the Foreman provisioning template "Kickstart default".



url --url https://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/kickstart
```

modified template:
```
# This kickstart file was rendered from the Foreman provisioning template "Kickstart default Rocky".



url --url https://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/kickstart
# repository added using BaseOS to AppStream string replacement
repo --name AppStream --baseurl https://dl.rockylinux.org/pub/rocky/8/AppStream/x86_64/kickstart
```

result with default template:
image

result with modified template is a complete install

**Comment by Bonehead5338** [comment]
Ok in addition, if I change the installation media from /kickstart to /os (Like the default 'CentOS Stream' medium), it works with default template..

```
# This kickstart file was rendered from the Foreman provisioning template "Kickstart default".



url --url https://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os
```

Maybe that is the solution.

EDIT: and it gets latest packages. I think this issue can be closed thanks @lzap

**Review by lzap — CHANGES_REQUESTED** [review]
I tested this and this workaround is no longer necessary for Pulp3, we will be actually dropping it instead:

https://github.com/theforeman/foreman/pull/8836

I also tested this without Katello and Anaconda works fine against upstream repositories too. This is really not needed at all.

**Comment by lzap** [comment]
Let me know if you still need any kind of change for Rocky, worked for me with what we have currently.

**Pull request closed without merging**
