### PR TITLE
Fixes #11153 - handle ldap errors gracefully

### PR DESCRIPTION
**Pull request by ares**
Before (sorry for missing icons):

problem

after:
submit

refresh

### CODE REVIEW

**Review by dLobatog — COMMENTED** [review]
@ares How does this differ from https://github.com/theforeman/foreman/pull/4199 ?

**Comment by ares** [comment]
I didn't see that one in action so I can't tell, I was reviewing https://github.com/theforeman/foreman/pull/4668 while I found these issues so I fixed them right away. If you think it's already solved by #4199, I can close it. PR #4199 should be linked to http://projects.theforeman.org/issues/11153/ in that case.

One difference I see from quick reading the code is that this patch registers the error on auth_source_id of the external group so in UI you can see the field marked red. I'm not sure how base errors are displayed on that page.

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Comment by ares** [comment]
[test katello]

**Review by dLobatog — CHANGES_REQUESTED** [review]
@ares I think I covered this error in #4199 , is this still relevant?

**Comment by ares** [comment]
If nothing else, this fixes the issue on refresh button which was not covered. It is still relevant. Removing WOC. The before is still reproducible, you need to be in production env. Someone please review.

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @ares !

**Pull request merged**
