### PR TITLE
Fixes #11413 - disable SQL logging by default

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
I think that if you want to change the default maybe `config/logging.yaml` is a better option. I'd recommend adding `config/logging.yaml` to the `.gitignore` and shipping a `logging.yml.example` as we do with settings and database. That way everyone can have their own option easily.

**Comment by tbrisker** [comment]
@eLobato I think this should be the default for rake, I've seen a couple of users already on IRC that missed the admin password because of this, and it also hides any errors when running migrations or tests. Note that if someone enables sql logging in the config it will still take precedence due to the `reverse_merge`, but if it isn't manually set I think the default should be off for rake and on for rails.

**Comment by domcleal** [comment]
logging.yaml shouldn't really be used to enable/disable individual loggers though, that's what SETTINGS is for.  I'd suggest just turning off SQL logging by default, it was done this way because it matched previous behaviour, but it ought to be off by default like other debug-level stuff (LDAP, permissions).

**Comment by dLobatog** [comment]
Alright, set `:sql => { :enabled => false }` then and we close this off.

**Comment by domcleal** [comment]
And update the settings.yaml.example to match, please.

**Comment by tbrisker** [comment]
@eLobato @domcleal I updated this as requested.

**Comment by domcleal** [comment]
Yes, it has the re-review label already.  There are a lot of PRs.

**Comment by domcleal** [comment]
Merged as a683aa2, thanks @tbrisker.

**Pull request closed without merging**
