### PR TITLE
Skip listing vms that are unregistered

### PR DESCRIPTION
**Pull request by gilesw**

### CODE REVIEW

**Comment by bgupta** [comment]
What does unregistered mean in this case?

**Comment by gilesw** [comment]
Hi bgupta, I logged onto the vmhosts and actually these problematic guests are registered. So sorry about that. Further investigation has revealed that these guests only have:-

uuid.location = xxx
uuid.bios = xxx

and not

vc.uuid

http://communities.vmware.com/thread/290235?start=0&tstart=0

So I think these guests were migrated from another older esxi host and not updated to have a vc.uuid. I can find out some more on Monday when I'm back in the office. It would probably be a better solution to fallback to using uuid.bios as a unique identifier for these hosts so they're still listed. I'll have a dig around to see if rbvmomi has access to this.

g.

**Comment by ohadlevy** [comment]
@gilesw thanks! this sounds like it better suited to be a patch against fog?

**Comment by lzap** [comment]
I'd appreciate global variable that would allow to turn this on or off. Sometimes it can be useful to see other VMs.

**Comment by ohadlevy** [comment]
@lzap vms without identity are not real vms imho.. .once they'll be put into running mode they should have an uuid.

I think this happens because of import or something from older esx?

this patch imho should be done in fog (to ignore those hosts in the first place), similar to how we skip templates... see https://github.com/fog/fog/blob/master/lib/fog/vsphere/requests/compute/list_virtual_machines.rb#L26

**Pull request closed without merging**
