### PR TITLE
Import improvements

### PR DESCRIPTION
**Pull request by Orphis**
Task rake puppet:import:puppet_classes improved.
Batch argument fixed and new argument to only import one environment instead of everything (which can be really slow).
Fixed the import_environments REST call.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@Orphis does this patch ready? I got a mixed singals on IRC, so wasnt sure :)

**Comment by ohadlevy** [comment]
this code has changed heavily, and i guess now can be easily adapter to the required change here, any chance you want to give it another try?

**Comment by Orphis** [comment]
I will have a look in a couple of weeks.

**Comment by ohadlevy** [comment]
ok - closing in the mean while, reopen / new one if needed - thanks

**Pull request closed without merging**
