### PR TITLE
Fixes #37215 - Stop using CV/LCE in ansible report if not set to hosts

### PR DESCRIPTION
**Pull request by ianballou**
Backport of https://github.com/theforeman/foreman/pull/10074/commits/6f60b5f061dd818206936b085e6c5ed53177a8e4 that supports older Safemode (removes safe navigation usage).

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
I feel like this would read better if we added, both to content_facet.rb and its Jail, methods for `single_content_view_id` and `single_lifecycle_environment_id`. Then you could just use those without need for ternaries. Thoughts?

**Comment by ianballou** [comment]
> I feel like this would read better if we added, both to content_facet.rb and its Jail, methods for `single_content_view_id` and `single_lifecycle_environment_id`. Then you could just use those without need for ternaries. Thoughts?

Sure, I can do that.

**Comment by ianballou** [comment]
Actually @jeremylenz since this is a backport I'm not sure it's a good idea to make changes in both Katello and Foreman. There shouldn't be another z-release of Foreman 3.9, but if there was, it would need to come out with another z-release of Katello as well.

**Comment by ianballou** [comment]
We've already done this strategy with the ternaries as well, so at least there's some precedent.

**Review by jeremylenz — APPROVED** [review]
@ianballou Oh right, I didn't think about the two-repo issue. I'm fine with the ternaries then.

I don't think test failures are related? so acking

**Pull request merged**
