### PR TITLE
Fixes #13068 - Added padding for dashboard documentation page

### PR DESCRIPTION
**Pull request by alongoldboim**
selection_002

### CODE REVIEW

**Comment by domcleal** [comment]
This seems to affect _every_ instance of btn-info in a header, not just the text.  e.g. a btn-info button (on the Puppet classes page) now has an additional 5px of margin, when it had 5px of left margin from the button on the right.

Surely it should apply the margin consistently to the left, so add it to the text too?

**Comment by alongoldboim** [comment]
I think it looks better to always place the documentation btn on the right.
before:
selection_015
after:
selection_014

**Comment by domcleal** [comment]
Can this be done in the helper that adds the dashboard buttons without relying on more CSS to pull it about (like other pages)?

**Comment by alongoldboim** [comment]
@domcleal This is done by using `dashboard_actions` helper function, the css changes the documentation button position not only for dashboard page but app wide.

**Comment by domcleal** [comment]
So it should probably be fixed in any incorrect helpers then?  CSS might change it app wide, but it seems confusing to override behaviour like that, in lieu of fixing the root cause.

**Comment by domcleal** [comment]
Please note that this PR is on the 1.11.0 regressions list and should be updated ASAP.

**Comment by alongoldboim** [comment]
Working on other issues won't have time to complete this in time, closing changing bug status to new so someone else could pick it up.

**Pull request closed without merging**
