### PR TITLE
fixes #2782 - LDAP password overwritten as blank

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
I'm still surprised that this is necessary in Rails and it doesn't handle it out of the box for passwords

**Comment by ohadlevy** [comment]
@isratrade should we update the form to be consistent as well? I saw some left over JS in it.

**Comment by isratrade** [comment]
@ohadlevy, rebased and deleted unnecessary js

**Comment by ohadlevy** [comment]
merged as 6a44fab thanks!

**Pull request closed without merging**
