### PR TITLE
Fixes #19388 - Show full text of highlighted multiselect lines

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
thanks, can you provide a before / after screenshots / animated gifs? :)

**Comment by tbrisker** [comment]
Before is available in the redmine issue, here is the after:
recorded

**Comment by tbrisker** [comment]
test failures unrelated

**Comment by ares** [comment]
Thanks @tbrisker, merged as 1ef4c7a8d44d0251ef91d7aac267c1ebba67dd4e

**Pull request closed without merging**
