### PR TITLE
Fixes #19491 - properly i18n notification seed

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by tbrisker** [comment]
@jlsherrill looks like you missed a few strings in that file, mind fixing all of them?

**Comment by jlsherrill** [comment]
Whoops, thanks @tbrisker !

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
Thanks @jlsherrill !

**Comment by ohadlevy** [comment]
@lzap a similar fix is probably needed on discovery, I would also suggest this fix goes into 1.15.1 ?

**Comment by ares** [comment]
@dLobatog, @tbrisker I suppose this was not backported to 1.15.1 correct?

**Comment by jlsherrill** [comment]
doesn't look like, i assume we could propose for 1.15.2 if it fits that criteria

**Pull request merged**
