### PR TITLE
Fixes #16702 - pass params to dashboard widgets

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
Without this, the widgets ignore any filter set by the user.

**Comment by timogoebel** [comment]
[test foreman]

**Comment by timogoebel** [comment]
Looks good and fixes the issue. 👍 on successful tests.

**Comment by timogoebel** [comment]
Merged as 10bceb1670c27ba686b885d55daf3810b628c9b9, thanks @tbrisker!

**Pull request closed without merging**
