### PR TITLE
Fixes #25833: increase hover delay for menu items.

### PR DESCRIPTION
**Pull request by waldenraines**
Ensure menu items don't close too quickly by increasing the delay.

https://projects.theforeman.org/issues/25833

### CODE REVIEW

**Comment by waldenraines** [comment]
[test foreman]

**Review by amirfefer — CHANGES_REQUESTED** [review]
Thanks @waldenraines :+1: 

The delay feels longer than expected to me
ezgif com-video-to-gif 1

how about decreasing it a bit?

**Comment by waldenraines** [comment]
Anyone have any thoughts on this?

```
Stacktrace
Capybara::Poltergeist::JavascriptError: One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

[sprintf] huh?
[sprintf] huh?
    at http://127.0.0.1:42252/webpack/vendor-7072f429e647f40ef323.js:246 in vo
    test/integration/host_js_test.rb:539:in `block (2 levels) in <class:HostJSTest>' (Capybara::Poltergeist::JavascriptError)
/usr/local/rvm/gems/ruby-2.4.3@test_develop_pr_core-0/gems/poltergeist-1.18.1/lib/capybara/poltergeist/browser.rb:396    
```

Umm, what?

**Comment by waldenraines** [comment]
> The delay feels longer than expected to me
> how about decreasing it a bit?

I suppose we could, I just wasn't sure what the best value was so as to not get the bug reopened.  @Rohoover do you have any thoughts?

**Review by chris1984 — COMMENTED** [review]
What about 50 instead of 100?

**Comment by Rohoover** [comment]
Hey, I tried this out on the dogfood server and I personally didn't experience any miss-clicks from delay. It does seem a bit longer than expected in the video above.

**Comment by waldenraines** [comment]
> Hey, I tried this out on the dogfood server and I personally didn't experience any miss-clicks from delay. It does seem a bit longer than expected in the video above.

I think the dogfood server would have the standard version of what is in master (oops, develop :man_facepalming:).  You can try this out on my sandbox if you want, just message me and I'll give you the details.

**Comment by ohadlevy** [comment]
Story book?

**Comment by ares** [comment]
[test foreman] perhaps you'll need to rebase

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
Is this a known issue in travis?

```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory```

**Comment by ohadlevy** [comment]
https://community.theforeman.org/t/can-we-drop-node-js-6-14-from-travis-javascript-test-matrix/12737

**Comment by waldenraines** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
whats the status of this pr?

**Comment by Rohoover** [comment]
@waldenraines 

Got a chance to test the new delay. I like it quite a bit! Nice job!

**Comment by waldenraines** [comment]
> whats the status of this pr?

Should just need to be reviewed/merged.

**Review by ares — APPROVED** [review]
Much better experience. For things like that I'd like to have more opinions, but given we have ack from @Rohoover and how complicated the patch or the delay adjustment is, I'll go ahead and merge.

Thanks @waldenraines, merging!

**Comment by ezr-ondrej** [comment]
It is introducing this regression:
Regresion
My wild guess is that if the Audits start to render too soon, they got re-rendered after the timeout :man_shrugging: but not really sure.

**Comment by waldenraines** [comment]
> It is introducing this regression:

I can barely tell what is happening in the gif, can you explain it please?

**Comment by ezr-ondrej** [comment]
Yeah sorry, the Audits page in not loading - is blank, the component is rendered, but not visible. I do not know why, but i went commit by commit and this is the first where it happens for me.

**Comment by tbrisker** [comment]
@ezr-ondrej - I'm seeing the audits page fail to load when I have an audit that is missing UserInfo, with the following error in the console:
```
Warning: Failed prop type: The prop `userInfo.search_path` is marked as required in `UserDetails`, but its value is `undefined`.
```
When I comment out the required props in the UserDetails component, the page loads just fine.

**Comment by ares** [comment]
So, what's the status here? Should we revert until we have the fix ready? Did someone open a tracking issue already? I suppose that should be 1.22 blocker.

**Comment by tbrisker** [comment]
https://projects.theforeman.org/issues/26286 is for the issue I've uncovered, I'm not sure this change is related to it. Perhaps the latest audits changed while trying to bysect leading to this commit?

**Comment by waldenraines** [comment]
> https://projects.theforeman.org/issues/26286 is for the issue I've uncovered, I'm not sure this change is related to it. Perhaps the latest audits changed while trying to bysect leading to this commit?

Yeah, I don't see how it could be related.  The delay I added doesn't delay the loading of the javascript or anything like that and with the JS error @tbrisker mentions above I think it really seems unrelated.

**Pull request merged**
