### PR TITLE
Fixes #18977 - Do not raise on creating a role in plugin initialization

### PR DESCRIPTION
**Pull request by adamruzicka**
As an alternative to https://github.com/theforeman/foreman-packaging/pull/1561

### CODE REVIEW

**Comment by ehelms** [comment]
Might make more sense to just check if we are in the migration step via `Foreman.in_rake?('db:migrate')` at https://github.com/theforeman/foreman/pull/4396/files#diff-d0644101ad428cdee084ab59f3e9a43cR238

I'd worry this rescue would hide other issues instead of targeting the current specific scenario.

**Comment by iNecas** [comment]
Good point @ehelms !

**Comment by adamruzicka** [comment]
done

**Comment by iNecas** [comment]
So `rake plugin:apipie:cache[%%{gem_name}]` would not hit the issue (https://github.com/theforeman/foreman-packaging/pull/1561/files#diff-67e0a6165416d559ed233a03cbf4dbc1R866) after this change?

**Comment by ares** [comment]
I don't think we should limit ourselves to `Foreman.in_rake?('db:migrate')`. There are other tasks that would fail such as `apipie:cache`, `assets:precompile` etc. I think we should avoid explicit list. I'd rather do the rescue, check whether the cause was missing permission (needs changing ArgumentError to some specific exception) and then check whether we are in any rake task or testing env. If all of that is true, we should print warning but continue working, otherwise we should fail with explaining message like "Can not continue since some permissions were not found, please run rake db:seed and retry"

**Comment by iNecas** [comment]
Sounds good, with one update: I would not touch the original condition that is there (as it could have consequences on the tests, where we don't assume the permissions are seeded this way). +1 for new execption class and catching/logging that in case we are in rake (without specifying which rake it is), otherwise re-raising

**Review by iNecas — APPROVED** [review]
Approving the change. Will merge unless @ehelms has something to say

**Comment by iNecas** [comment]
Pending tests failures

**Comment by iNecas** [comment]
Test failures independent, squashing and merging now

**Pull request merged**
