### PR TITLE
Fixes #25326 - Fix Lint/SafeNavigationConsistency cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by tbrisker** [comment]
not sure i like this one... even though it's harmless, in both cases it's also unneeded.

**Comment by mmoll** [comment]
Yes, in the cases it was autocorrected, the original problem would never happened, but especally in new code I can see that this cop can lead to better implicit nil checks.

I would be open to refactor those two occurences if the cop can get globally enabled then.

**Comment by mmoll** [comment]
Looking at this again, I think at these occurences the redundantness can't get detected without performing a real static code analysis, which Rubocop doesn't do...

**Comment by mmoll** [comment]
rebased. anyboy?

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
Thanks @mmoll !

**Pull request merged**
