### PR TITLE
Fixes #35660 - Update report templates for multi CV

### PR DESCRIPTION
**Pull request by jeremylenz**
~~Goes with https://github.com/Katello/katello/pull/10296~~ The Katello PR is now merged, so these report templates will be broken until this is in.

The methods `#content_view` and `#lifecycle_environment` no longer exist on host or content facet, so these need to be updated on the reports.

### CODE REVIEW

**Comment by jeremylenz** [comment]
Should not be merged until after Foreman branching, so leaving as draft until then.

**Comment by MariaAga** [comment]
@jeremylenz can someone from the Ketello team test and approve this?

**Comment by ianballou** [comment]
Works for me with the related Katello PR! I won't ACK yet since it should not merge without the other.

**Comment by ianballou** [comment]
@jeremylenz we'll need to match up the Katello version that the multi-cv change goes into with the required Katello plugin version in the report.

**Comment by jeremylenz** [comment]
Thanks! Updated to require Katello 4.8.

**Review by ianballou — APPROVED** [review]
The Katello PR has been acked!

**Comment by jeremylenz** [comment]
Test failure doesn't seem related

**Comment by jeremylenz** [comment]
@MariaAga any update?

**Review by Ron-Lavi — APPROVED** [review]
Thanks @jeremylenz @ianballou !

**Pull request merged**
