### PR TITLE
Fixes #31372 - improve facet relation hook

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This introduce more rigid relation registration.
Instead of refreshing the relations every time we register new facet.

### CODE REVIEW

**Comment by ShimShtein** [comment]
The idea of both refreshing and registering on the go is there because we don't know what would be created first: the model object, or the facet definition object. This will specifically break in autoreload scenarios.
Maybe a more selective refresh would be enough?

**Comment by ezr-ondrej** [comment]
> The idea of both refreshing and registering on the go is there because we don't know what would be created first: the model object, or the facet definition object. This will specifically break in autoreload scenarios.

Will it break for sure? We do both on `configure_facet` in https://github.com/theforeman/foreman/pull/8151/files#diff-526e6699abd24a30179b91a275b04f4e893bbd369956953aa8e7fee5b38c401fR20-R27
I go over the curently registered and run `register_facet_relation_for_type` and register the `after_entry_created` hook so it will happen for all the ones that get registered after the model is already loaded.
So I believe both cases are covered in here :thinking:

**Comment by ezr-ondrej** [comment]
@ShimShtein I've rebased and I'd love to get this in, it is very dangerous to register the relation twice, which might happen in some edge cases in the current behaviour.

This approach registers the currently loaded facets and those loaded after are loaded through the hook, so this is covering all the cases, but exactly once, never re-register.

**Review by ShimShtein — APPROVED** [review]
Looks good, merging!

Thanks @ezr-ondrej!

**Pull request merged**
