### PR TITLE
fixes #9998 - Add styling to error reporting

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
@stbenjam Could you spare some time to review this one?

**Comment by shlomizadok** [comment]
@stbenjam ping

**Comment by stbenjam** [comment]
Sorry for the delay, tested it out and looks good to me :+1:

**Comment by dLobatog** [comment]
Merged as 63287a97004fd37c40682fde964d03421ab849c8, thanks @shlomizadok and @stbenjam for testing!

**Pull request closed without merging**
