### PR TITLE
Fixes #24754 -  update react to 16.4

### PR DESCRIPTION
**Pull request by amirfefer**
The installed react version is the latest (16.4.x) while enzyme adapter works with 16.3.x

### CODE REVIEW

**Comment by mmoll** [comment]
why not use enzyme-adapter-react-16 then?

**Comment by amirfefer** [comment]
@mmoll  according to enzyme documentation  `enzyme-adapter-react-16` suits  ^16.4.0-0
let me check if it works well :)

**Comment by amirfefer** [comment]
@mmoll It works well with `enzyme-adapter-react-16`

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merging, as RPM repos already have 16.4

**Comment by mmoll** [comment]
merged, thanks @amirfefer!

**Pull request merged**
