### PR TITLE
Fixes #11004 - changed the cursor on hover on facts distribution graph.

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Hey, thanks for the pull request.  It was in my review queue, so I'd have got to it soon.  Is there a reason you've closed it?

**Comment by amirfefer** [comment]
yea, there was a similar issue(#11006) and in it i fixed both of the problems, what status of related issue do i need to place on 11004 on redmine?

**Comment by domcleal** [comment]
I'd say they're probably two separate issues, so might be better as two PRs.  You could create one PR with a commit message of "fixes #11004, #11006 - change X and Y" though (fill in the bit after the hyphen).

**Pull request closed without merging**
