### PR TITLE
Fixes #20872 - scoped_search should be >= 4.1.2

### PR DESCRIPTION
**Pull request by dLobatog**
As to introduce the fix for relations between classes with polymorphism
(https://github.com/wvanbergen/scoped_search/commit/e629a484cc57c65cd394e47006eb30b24e4382bc)

### CODE REVIEW

**Comment by ares** [comment]
@dLobatog mind to open foreman-packaging PR with the update? it works for non packages setups.

**Comment by ares** [comment]
to make things faster, I opened https://github.com/theforeman/foreman-packaging/pull/1805 so please just review/merge it, then this is good to go :-)

**Review by dLobatog — COMMENTED** [review]
@ares Merged on foreman-packaging - it's built on 1.15 and nightly, the koji-foreman-1.16 tag is empty yet

**Comment by ares** [comment]
Thanks @dLobatog, merged as bd9d07c15223180fa18d28f5dc13654bfc591ff5

**Comment by ares** [comment]
cherrypicked to 1.16 as 0ec839db27ee99458da83372ff639552bb516b3c and to 1.15 as b3f57754f66322b541a502376ebd9e42f02253db

**Pull request closed without merging**
