### PR TITLE
Fixes #37236 - Add primaryButton prop to PermissionDenied component

### PR DESCRIPTION
**Pull request by ofedoren**
@MariaAga, this is something that I've also used in https://github.com/theforeman/foreman_openscap/pull/546.

### CODE REVIEW

**Review by MariaAga — APPROVED** [review]
Nice addition, thanks!

**Review by MariaAga — CHANGES_REQUESTED** [review]
Can you open a Katello PR for the snapshots?

**Comment by ofedoren** [comment]
@MariaAga, done: https://github.com/Katello/katello/pull/10929.

**Review by MariaAga — APPROVED** [review]

**Comment by MariaAga** [comment]
Thanks!

**Pull request merged**
