### PR TITLE
fixes #5994: Power and Console buttons are available to non-admin users with appropraite permissions

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
@domcleal, @ares: I decided not to try to fix query generation, but rather opted for changing of scoped_search definition for organization_id and location_id on Host::Managed, as it appears it's the only place that uses `:belongs_to` relation for organizations and locations (and the source of the problem with the query).

**Comment by dmitri-d** [comment]
also: this fix affects which values are being suggested when for auto-completion of organization and location ids: it will only show ids that are present in organization_id and location_id of hosts table, which is a subset of all available ids...

**Comment by ohadlevy** [comment]
Won't this break primary host search api / hammer?

**Comment by dmitri-d** [comment]
I don't think so...

**Comment by ohadlevy** [comment]
Didn't we lose the ability to search by location=xyz?

**Comment by dmitri-d** [comment]
search by location/organization name and location/organization ids works, with the caveat I mentioned above.

**Comment by ohadlevy** [comment]
@witlessbird oops, I've missed that, thanks!

**Comment by domcleal** [comment]
Thanks @witlessbird, merged as 5aac54d for Foreman 1.5.2.

**Pull request closed without merging**
