### PR TITLE
Fixes #16379 - Improve layout of hostname randomize button

### PR DESCRIPTION
**Pull request by tbrisker**
This moves the button from being a line of its own to an icon inside the
input. Also added a form_feedback option to the field helper to allow
easy addition of more icons in inputs in the future.

### CODE REVIEW

**Comment by tbrisker** [comment]
Before:
screenshot from 2016-08-30 11-02-11

After:
screenshot from 2016-08-30 11-01-29

@rohoover - I'd be happy for your input

**Comment by ares** [comment]
I think it deserves its own redmine issue.

**Comment by tbrisker** [comment]
@ares thanks, updated

**Comment by ares** [comment]
Works nicely, ACK pending jenkins and feedback from @rohoover

**Comment by ohadlevy** [comment]
@tbrisker how about having it as a btn inside the input, similar to the date picker at https://www.patternfly.org/pattern-library/forms-and-controls/date-picker ?

**Comment by tbrisker** [comment]
@ohadlevy I personally think it looks nicer not as a button, but I may be wrong. I'll do whatever @rohoover says will work better.

**Comment by Rohoover** [comment]
Visually I am not bothered by either approach so I have to default to the closest standard for consistency which would be what @ohadlevy suggested.

Leaving it "naked" without the button would be a new pattern or exception.

**Comment by tbrisker** [comment]
Changed to a button, updated screenshot:
screenshot from 2016-08-31 15-46-20

**Comment by ohadlevy** [comment]
@tbrisker what do you see if the feature is disabled?

**Comment by tbrisker** [comment]
@ohadlevy just a regular text input with no button

**Comment by ohadlevy** [comment]
ack assuming this is the right icon to use (didnt find a better one).

**Comment by Rohoover** [comment]
This is the correct icon. It's labeled as such in font awesome and is the generally accepted icon for "random" in a multitude of applications. +1

**Comment by lzap** [comment]
Works as expected, thanks.

**Comment by ehelms** [comment]
[test]

**Comment by lzap** [comment]
Merged as 3b6f9323cd186c355a8519d887cc13c30c5e2276, thank you!

**Pull request closed without merging**
