### PR TITLE
Fixes #21992 - Uses patternfly spinner component

### PR DESCRIPTION
**Pull request by lupandaniel**

### CODE REVIEW

**Comment by sharvit** [comment]
Thanks @lupandaniel :+1: Works great

Can you please update the test snapshot by running `npm test -- -u`?

**Comment by lupandaniel** [comment]
@sharvit it's done. Thanks 👍

**Review by sharvit — APPROVED** [review]
Thanks @lupandaniel LGTM

**Comment by ohadlevy** [comment]
[ok to test]

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
thanks @lupandaniel :)

**Pull request merged**
