### PR TITLE
fixes #8884 - drop Gemfile support for Ruby 1.9.3

### PR DESCRIPTION
**Pull request by domcleal**
This will obviously fail on Ruby 1.9.3 tests, but I can remove those from Jenkins prior to it being merged.

### CODE REVIEW

**Comment by brandonweeks** [comment]
Finally! 💯

**Comment by dLobatog** [comment]
@domcleal Cool, this needs  to be rebased, you can remove the Jenkins job prior to that so that when you push the rebased version, it only runs on Ruby 2.x

**Comment by domcleal** [comment]
Jobs updated to remove 1.9.3 and rebased.

**Comment by dLobatog** [comment]
Merged as 59e6ee202b794a0c9fcde447a36c4ab660a34d78, thanks @domcleal!

**Pull request closed without merging**
