### PR TITLE
Fixes #35490 - Registration - Changing proxy cause an error

### PR DESCRIPTION
**Pull request by stejskalleos**
**Steps to reproduce**
* Go to registration form
* generate command with proxy
* Unselect proxy and generate command again

### CODE REVIEW

**Comment by stejskalleos** [comment]
[foreman test]
[katello test]

**Comment by stejskalleos** [comment]
[test foreman]

**Comment by stejskalleos** [comment]
[test katello]

**Comment by stejskalleos** [comment]
[test integration]
[test unit]

**Comment by stejskalleos** [comment]
[test katello]

**Review by ares — APPROVED** [review]
Thanks @stejskalleos, merging!

**Pull request merged**
