### PR TITLE
Fixes #18491 - Fix failing users js test

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
@tbrisker How do you reproduce this error locally? Specific node version, etc..? Tests completely pass on my computer without this, I only see the error on Travis

**Comment by tbrisker** [comment]
@dLobatog 
```
2.0.0@foreman_gemset ~/foreman (18491) $ node -v
v6.9.4
2.0.0@foreman_gemset ~/foreman (18491) $ npm -v
3.10.10
```

**Comment by dLobatog** [comment]
@tbrisker Thanks 😄 - tried with `/usr/local/n/versions/node/6.9.4/bin/npm run test` and it definitely fails without your test consistently.

**Comment by dLobatog** [comment]
Thanks @tbrisker !

**Pull request merged**
