### PR TITLE
fixes #23681 - move auth_source_ldap js to webpack

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ares** [comment]
[test foreman] many js related errors but sqlite was green so let's rerun and see

**Comment by ohadlevy** [comment]
@ares updated hopefully with a fix

**Comment by ohadlevy** [comment]
Green again

**Review by ares — APPROVED** [review]
Looks good, works well and tests are green :-) Thanks @ohadlevy, merging!

**Pull request merged**
