### PR TITLE
Refs #35578 - Fix netplan interface template syntax

### PR DESCRIPTION
**Pull request by ekohl**
This was reported @ https://github.com/theforeman/foreman/pull/9439#issuecomment-1323507573. I'd like to add test coverage to this, but opening this so I don't forget.

Fixes: 73f9b5017f4598b340f78102ed010ab379ecffe6

### CODE REVIEW

**Comment by ekohl** [comment]
I started down a rabbit hole of adding tests, but it's deep. I think for now this should be sufficient.

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, tests are green, let's get this in!

**Comment by stejskalleos** [comment]
Thanks @ekohl !

**Comment by ekohl** [comment]
@stejskalleos when you merge, please don't use squash unless you really mean it. We always use rebase when possible. The reason is that we don't want the `(#PR)` to be added to the commit message.

**Comment by ekohl** [comment]
Cherry picked to 3.5-stable as 69122e863d38670b1de33e74cea7a1c8f4ec7850

**Pull request merged**
