### PR TITLE
fixes #5939: it's no longer possible to switch tabs when compute profile is being edited.

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
Github is being wonky: the changes are:

https://github.com/witlessbird/foreman/blob/5939/app/assets/javascripts/two-pane.js#L35
https://github.com/witlessbird/foreman/blob/5939/app/assets/javascripts/two-pane.js#L78

**Comment by domcleal** [comment]
This doesn't seem to actually disable the tabs, just changes the cursor and colour - you're able to switch to them still.

**Comment by dmitri-d** [comment]
@domcleal: what browser did you use?

**Comment by domcleal** [comment]
@witlessbird Chrome 35.0.1916.114 on Linux

**Comment by dmitri-d** [comment]
@domcleal: not sure how much I like this, but I can't think of any other way to fix the issue.

**Comment by domcleal** [comment]
Or can we re-enable/display the missing buttons when a tab is selected?

**Comment by dmitri-d** [comment]
That would require intercepting an internal bootstrap.js event, or introducing our own, in addition to carrying two-pane open/closed state. Not sure if that would be much better than what I have here :(.

**Comment by domcleal** [comment]
Hm okay.

There's a new issue on other pages that use tabs inside two-pane views - try going to Domains, click to edit a domain, then try to click the Parameters tab.

**Comment by dmitri-d** [comment]
@domcleal: this looks better, I think...

**Comment by ohadlevy** [comment]
how about something like

``` js
$('#myTab a').click(function (e) {
  close_two_pane_if_open();  
  $(this).tab('show')
})
```

**Comment by dmitri-d** [comment]
That would result in loss of changes made in the open window, esp. unpleasant as it may happen accidentally.

**Comment by domcleal** [comment]
Thanks @witlessbird, merged as e8015ce for Foreman 1.6.0.

**Pull request closed without merging**
