### PR TITLE
Fixes #32490 - Fixing the permission in the file /root/ansible_provisioning_call.sh

### PR DESCRIPTION
**Pull request by aldreygalindo**
Fixing the permission in the file /root/ansible_provisioning_call.sh. This file created when the customer used the image based and has the ansible tower callback.

### CODE REVIEW

**Comment by ares** [comment]
I assume we'll need to rerender the template snippets for tests to pass, please execute `rake snapshots:generate` and add new changes to the commit

**Comment by ares** [comment]
[test foreman] [ok to test] seems the github button didn't allow all jobs

**Comment by ares** [comment]
tests fail as expected, @aldreygalindo please run the `rake snapshots:generate` and repush with the changes, thank you

**Comment by aldreygalindo** [comment]
Thanks for your feedback @ares. I am fixing my environment to make it.

**Comment by aldreygalindo** [comment]
@ares I ran the command: After run: RAILS_ENV=test bundle exec rake snapshots:generate. But the issue remains. Could you indicate how I can solve it?

**Comment by ezr-ondrej** [comment]
Easiest solution would be to pull newest `develop` branch, create new branch from it, run the `RAILS_ENV=test bundle exec rake snapshots:generate` and open a new PR with that.

Without new branch you would need to:
- `git rebase -i develop`
- drop your conflicting changes by `git checkout --ours .`
- `git rebase --continue` to finish the rebase
- run `RAILS_ENV=test bundle exec rake snapshots:generate`
- `git commit` the new changes
- ideally rebase again to squash the commits (`git rebase -i develop`, chaging second `pick` to `f`)
- `git push --force`

**Comment by ezr-ondrej** [comment]
I'm sorry for confusing you, you could have just drop the second commit as you got it in separate commit.
I've done so for you, unfortunatelly, you didn't allow pushes from maintainers, so I've opened a PR with that: #8630.

**Comment by tbrisker** [comment]
Thanks @aldreygalindo for your contribution! I've merged this in GH-8630, closing this PR.

**Pull request closed without merging**
