### PR TITLE
fixes #9982 - update fog to 1.29.0

### PR DESCRIPTION
**Pull request by domcleal**
RPMs are a trivial update, don't worry about waiting for those.

### CODE REVIEW

**Comment by domcleal** [comment]
Oh, wait a minute, I might have just opened a can of worms in the RPM packaging.

**Comment by domcleal** [comment]
I had to revert the fog-core bump as 1.30.0 depends on excon 0.45.0, which depends on json 1.8.2, but we're using an older json 1.5 from the ruby193 SCL.  This version of fog claims to support fog-core 1.27.4 and up, so I don't think leaving it is a problem for now.

This should resolve itself if/when we update our packages for a new SCL, but I'll add some notes in redmine so we know it might block future updates.

**Comment by iNecas** [comment]
ACK

**Comment by dLobatog** [comment]
Cool, we leave it as fog-core 1.29 then.

**Comment by dLobatog** [comment]
Merged as da20284b326e55f086103c00534c9e6ecfa73251, thanks @domcleal!

**Pull request closed without merging**
