### PR TITLE
fixes #4564 - has_ancestry definition should be removed from hostgroup

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by isratrade** [comment]
[test]

**Comment by domcleal** [comment]
Could you check the ticket number please?  4565 is something else :)  Just do a `git commit --amend` to fix it and then `git push -f` to update the branch here.

**Comment by orrabin** [comment]
@domcleal Updated

**Comment by domcleal** [comment]
Thanks, that's better.  I made you a member of the GitHub org and Redmine.  If you go to https://github.com/orgs/theforeman/members and click "Make public" next to your name (so theforeman shows up on your profile), then Jenkins will test your PRs automatically in future.

[test] for now.

**Comment by ohadlevy** [comment]
merged as 182b148 thanks @orrabin

**Pull request closed without merging**
