### PR TITLE
fixes #3828 - set language locale for API messages and error responses

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by thomasmckay** [comment]
No, I don't think this is going to work at all. The API feeds both the UI and the CLI and needs to be locale-aware. Shouldn't results be dependent on the locale of the user / request header?

**Comment by isratrade** [comment]
@thomasmckay, @daviddavis, To follow up on our irc conversation, what should be localized and what not?  The bug in Redmine issue #3828 was API messages and error responses not in English 

```
Unprocessable entity SmartProxy (id: new):
   No ha sido posible establecer una comunicación con el proxy:
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B:
certificate verify failed
   Por favor, comprueba que el proxy está configurado y ejecutándose en
el equipo
```

**Comment by thomasmckay** [comment]
The API call needs some sort of precedence in determining locale:

```
locale = user-default-locale
locale = request-header-locale if !locale
locale = server-default-locale if !locale
locale = english if !locale
```

All calls to the server should go through this logic, right?

**Comment by isratrade** [comment]
@thomasmckay, check this fix.
`set_gettext_locale` is a method in the gettext_18n_rails that does what I think you you.

``` ruby
  def set_gettext_locale
    requested_locale = params[:locale] || session[:locale] || cookies[:locale] ||  request.env['HTTP_ACCEPT_LANGUAGE'] || I18n.default_locale
    locale = FastGettext.set_locale(requested_locale)
    session[:locale] = locale
    I18n.locale = locale # some weird overwriting in action-controller makes this necessary ... see I18nProxy
  end
```

**Comment by thomasmckay** [comment]
ack, thanks!

**Comment by domcleal** [comment]
Merged as 5a864be for Foreman 1.4.0, thanks @isratrade!

(@thomasmckay, you may want to ensure any base controllers in Katello also call this.)

**Pull request closed without merging**
