### PR TITLE
Fixes #21815 - Do not search for permissions when db is empty

### PR DESCRIPTION
**Pull request by xprazak2**
To be merged after we move to Rails 5.1 if the issue manifests itself.

### CODE REVIEW

**Comment by xprazak2** [comment]
This should be added to 1.17 milestone

**Comment by ares** [comment]
> This should be added to 1.17 milestone

added, feel free to ping me if you need more PRs marked

**Comment by mmoll** [comment]
This seems to happen also with Rails 5.0 with Katello...

please rebase.

**Comment by xprazak2** [comment]
Rebased

**Comment by xprazak2** [comment]
@ares , could you review? It should fix the katello failures for #4836

**Review by tbrisker — APPROVED** [review]
LGTM

**Review by ohadlevy — APPROVED** [review]
LGTM too

**Comment by ares** [comment]
Thanks @xprazak2, works fine here. Merging

**Pull request merged**
