### PR TITLE
Fixes #2749 - power status helper can handle unknown states

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
Good one, did you catch some error like that? IPMI providers are completely unreliable.

:+1: to merg after Mr Jenkins is back

**Comment by domcleal** [comment]
[test]

**Comment by ares** [comment]
@eLobato yeah, connection timeout in my case, also for some users the status was nil since they didn't have correct permissions

**Comment by dLobatog** [comment]
Merged as 2c7ea23b592775b20c2cdffebcc7b9ba69772baa, thanks @ares

**Pull request closed without merging**
