### PR TITLE
Fixes #27402 - LDAP usergroup sync

### PR DESCRIPTION
**Pull request by ezr-ondrej**
If usergroup that has no external usergroup attached gets synchronized, the users in group that belongs to LDAP auth source are removed from the group (as it behaves like it would be synced, but no users are found).

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test foreman][test katello]

**Comment by ezr-ondrej** [comment]
[test foreman]

**Review by ares — APPROVED** [review]
Thanks @ezr-ondrej, makes sense and fixes the problem. Merging!

**Comment by ares** [comment]
Test failures unrelated, cc @tbrisker this should go to 1.23 and 1.22 ideally where the regresssion was introduced. @ezr-ondrej it would be great if you open CP against 1.22-stable and 1.23-stable e.g. next week.

**Comment by ezr-ondrej** [comment]
@tbrisker should we backport it?

**Comment by tbrisker** [comment]
cherry-picked:
1.22 - 26c374053
1.23 - 5ae3099fb

btw, everyone can open a pr against the stable branches to propose backports.

**Pull request merged**
