### PR TITLE
fixes #5909 - return r/w resources from authorized scope

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ares** [comment]
If I understand correctly, the read only is set because the models can contain attributes from other tables. Making it writeable means something will fail (hopefully) later when you save it. A better solution might be to add `:select => "#{resource.table_name}.*"` where the actual query is triggered.

**Comment by domcleal** [comment]
Since [Rails 4.1 removes this behaviour anyway](https://github.com/rails/rails/commit/5a687e930ffd4785be7af4816f97000fc3e948b3) isn't this the easier way to go?  I can double check exactly what query was generated, but I suspect it may require changes across the app to fully fix that way.

**Comment by ares** [comment]
Interesting, OK so :+1:, I'll try to test later. Let's hope we get to 4.1 soon.

**Comment by ares** [comment]
Merged as 0d80512c3293895750ffda82489b719c38ec5612, thanks @domcleal!

**Pull request closed without merging**
