### PR TITLE
[WIP] Fixes #24352 - Upgrade to Webpack 4

### PR DESCRIPTION
**Pull request by himdel**
This upgrades foreman to webpack4.

TODO: 

* ? Reference the issue via `Fixes #24352` **in the commit message** (which commit?)
* [ ] make sure vendor ends up having all the same files as before

Cc @ohadlevy - you asked for this, but not sure if an issue already exists?
(Also, the [search form](https://projects.theforeman.org/search?all_words=1&attachments=0&commit=Submit&issues=1&options=0&page=2&q=webpack&titles_only=&utf8=%E2%9C%93) doesn't seem able to give more than 10 result per page, so .. I couldn't find it, no idea if there or not.)

### CODE REVIEW

**Comment by ohadlevy** [comment]
[ok to test]

**Comment by ohadlevy** [comment]
@himdel thanks! I've created https://projects.theforeman.org/issues/24352.

**Comment by ohadlevy** [comment]
@sharvit can you review please?

**Comment by ohadlevy** [comment]
@himdel I did a very quick test, I've observed the following:

The application won't start correctly, I've seen this in the browser console logs:
```
Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (bundle-60f8360ac0fe1faca59d.js:1)
    at Object.node_modules/babel-polyfill/lib/index.js (bundle-60f8360ac0fe1faca59d.js:1)
    at n (bundle-60f8360ac0fe1faca59d.js:1)
    at Object../webpack/assets/javascripts/bundle.js (bundle-60f8360ac0fe1faca59d.js:1)
    at n (bundle-60f8360ac0fe1faca59d.js:1)
    at ./webpack/assets/javascripts/bundle.js (bundle-60f8360ac0fe1faca59d.js:1)
    at bundle-60f8360ac0fe1faca59d.js:1
application-f6e0c69b32e8c802ce890c3ac4e46891a7b5bc01fdb0544a18282599e4ed2358.js:9 Uncaught ReferenceError: tfm is not defined
    at application-f6e0c69b32e8c802ce890c3ac4e46891a7b5bc01fdb0544a18282599e4ed2358.js:9
login:46 Uncaught ReferenceError: tfm is not defined
    at login:46
```

compiling time is very long, on my env (including a few plugins) these are the stats 

### webpack 4

```
version: webpack 4.16.2
Time: 130109ms
Built at: 2018-07-23 13:20:54
                                               Asset       Size  Chunks                    Chunk Names
                  bundle-60f8360ac0fe1faca59d.css.gz   13.7 KiB          [emitted]         
                     bundle-60f8360ac0fe1faca59d.css   71.1 KiB       0  [emitted]         bundle
                      vendor-0cb086dd8e1ffca17030.js   3.69 MiB       1  [emitted]  [big]  vendor
   foreman_remote_execution-07201aced32d18e6ff51.css   9.14 KiB       2  [emitted]         foreman_remote_execution
    foreman_remote_execution-07201aced32d18e6ff51.js   2.16 MiB       2  [emitted]  [big]  foreman_remote_execution
            foreman_ansible-b5754ff900b9d1c1beb2.css   9.14 KiB       3  [emitted]         foreman_ansible
             foreman_ansible-b5754ff900b9d1c1beb2.js   2.19 MiB       3  [emitted]  [big]  foreman_ansible
                                       manifest.json  503 bytes          [emitted]         
                      bundle-60f8360ac0fe1faca59d.js   3.86 MiB       0  [emitted]  [big]  bundle
foreman_remote_execution-07201aced32d18e6ff51.css.gz   1.98 KiB          [emitted]         
         foreman_ansible-b5754ff900b9d1c1beb2.css.gz   1.97 KiB          [emitted]         
                                    manifest.json.gz  239 bytes          [emitted]         
 foreman_remote_execution-07201aced32d18e6ff51.js.gz    734 KiB          [emitted]  [big]  
          foreman_ansible-b5754ff900b9d1c1beb2.js.gz    742 KiB          [emitted]  [big]  
                   vendor-0cb086dd8e1ffca17030.js.gz   1.13 MiB          [emitted]  [big]  
                   bundle-60f8360ac0fe1faca59d.js.gz   1.16 MiB          [emitted]  [big]  
```

### webpack 3

```
Version: webpack 3.12.0
Time: 90074ms
                                               Asset       Size  Chunks                    Chunk Names
foreman_remote_execution-f398c0e14b725d8f4b90.css.gz    2.02 kB          [emitted]         
             foreman_ansible-67acb6033a6418ea282d.js     190 kB       0  [emitted]         foreman_ansible
    foreman_remote_execution-f398c0e14b725d8f4b90.js     150 kB       2  [emitted]         foreman_remote_execution
                      vendor-006110822861b6733af8.js    3.87 MB       3  [emitted]  [big]  vendor
                     bundle-ceabc5d95e689c1e100d.css    72.7 kB       1  [emitted]         bundle
   foreman_remote_execution-f398c0e14b725d8f4b90.css    9.35 kB       2  [emitted]         foreman_remote_execution
            foreman_ansible-67acb6033a6418ea282d.css    9.35 kB       0  [emitted]         foreman_ansible
                                       manifest.json  503 bytes          [emitted]         
                      bundle-ceabc5d95e689c1e100d.js     183 kB       1  [emitted]         bundle
         foreman_ansible-67acb6033a6418ea282d.css.gz    2.02 kB          [emitted]         
                  bundle-ceabc5d95e689c1e100d.css.gz      14 kB          [emitted]         
                                    manifest.json.gz  238 bytes          [emitted]         
 foreman_remote_execution-f398c0e14b725d8f4b90.js.gz      29 kB          [emitted]         
          foreman_ansible-67acb6033a6418ea282d.js.gz    41.4 kB          [emitted]         
                   bundle-ceabc5d95e689c1e100d.js.gz    37.1 kB          [emitted]         
                   vendor-006110822861b6733af8.js.gz    1.18 MB          [emitted]  [big]  
```

it looks like the chunks do not work as expected, see especially the size difference for example in foreman_ansible or foreman_remote_execution ?

**Comment by ohadlevy** [comment]
@himdel whats the status of the PR? thanks :)

**Comment by himdel** [comment]
Sorry @ohadlevy I still have to investigate your last comment. Thanks

**Comment by himdel** [comment]
Getting somewhat closer now..

```
Version: webpack 3.12.0
Time: 8853ms
        Asset       Size  Chunks                    Chunk Names
    bundle.js     930 kB       0  [emitted]  [big]  bundle
    vendor.js    21.2 MB       1  [emitted]  [big]  vendor
   bundle.css     165 kB       0  [emitted]         bundle
manifest.json  153 bytes          [emitted]         
```

=>

```
Version: webpack 4.16.5
Time: 8457ms
Built at: 08/06/2018 12:18:07 PM
        Asset       Size  Chunks             Chunk Names
    bundle.js   74.6 KiB  bundle  [emitted]  bundle
   vendor.css    216 KiB  vendor  [emitted]  vendor
    vendor.js   21.6 MiB  vendor  [emitted]  vendor
manifest.json  153 bytes          [emitted]  
```

**Comment by himdel** [comment]
But... @ohadlevy is there any info on what should actually be where?

I... have no idea what's actually supposed to end up in `bundle`, and what in `vendor`.

---

I would assume that `vendor` is for anything from `node_modules`, but perhaps not, because `bundle` seems to take stuff from `node_modules` as well, and `config/webpack.vendor.js` contains an explicit list of ..something.

So, how is this supposed to work? Is `vendor` just for things from that list? Should anything included by something in the list go to `vendor` as well? Should code required by bits in `vendor` and bits in `bundle` end up in `bundle` or in `vendor`?

**Comment by ohadlevy** [comment]
(edit, i clicked send too quickly)
bundle is everything not in config/webpack.vendor.js, the idea is that we officially declare 3rd npm packages that plugins can expect to have available.

/cc @sharvit - anything you want to expand on?

**Comment by himdel** [comment]
Ok, looks like with the latest changes, 

```
Version: webpack 4.16.5
Time: 8435ms
Built at: 08/06/2018 2:59:53 PM
        Asset       Size  Chunks             Chunk Names
   bundle.css    216 KiB  bundle  [emitted]  bundle
    bundle.js   4.09 MiB  bundle  [emitted]  bundle
    vendor.js   21.2 MiB  vendor  [emitted]  vendor
manifest.json  153 bytes          [emitted]  
```

But now we're just explicitly matching the paths against the list in `vendorEntry` which means any recursive dependencies of vendor end up in bundle, which is probably not desired.


Looking into this further, we can probably extend the logic from "file is in vendorEntry" to something like "file is a recursive vendorEntry dependency".

(=> still wip) (But no more babel-polyfill or tfm errors.)

**Comment by sharvit** [comment]
> bundle is everything not in config/webpack.vendor.js, the idea is that we officially declare 3rd npm packages that plugins can expect to have available.
>
> /cc @sharvit - anything you want to expand on?

We are facing a problem when plugin developers need to maintain a `package.json` file synced with the foreman `package.json` so their dev/testing tools would be able to use the same `node_modules` the foreman uses. When we build the plugin, we let the foreman do this job and build the plugin with the `vendor.js` chunks.

Therefore, we are talking about a solution of exporting an npm package with the relevant `node_modules` and the `vendor.js` file. We can also export the build process so they can use it to test and build themselves.

Anyway, I don't think it should affect this PR for any reason, thanks for taking the webpack-4 challenge seriously :1st_place_medal:

**Comment by himdel** [comment]
OK, thanks! So... that means that we really need everything from `webpack.vendor.js` and all their dependencies to end up in `vendor`... sounds like maybe I don't have to muck with `test` functions and can achieve the same by correctly assigning priorities, I will try that :).

Out of curiosity, @sharvit do the plugins ever run on their own, without the rest of foreman?

(Just trying to figure out the difference from manageiq, where we do just one webpack build for the core+plugins, and I've written a webpack [plugin](https://github.com/ManageIQ/manageiq-ui-classic/pull/3776/files#diff-0ba08fd09771643ea6efb63f4e89a142) to pick the right `node_modules` to use (including the support for the core sharing packages).)

**Comment by ekohl** [comment]
> Out of curiosity, @sharvit do the plugins ever run on their own, without the rest of foreman?

For their Ruby parts the answer is no, they never run without Foreman. There we use Foreman to run tests as well. I'm not too sure about the JS part but it would make sense to me to keep them equivalent.

**Comment by sharvit** [comment]
> Out of curiosity, @sharvit do the plugins ever run on their own, without the rest of foreman?

They never run on their own but they do run unit-tests, storybook, linting and some other tasks in a local npm environment.

**Comment by himdel** [comment]
note to self: this will also need `optimization.runtimeChunks` to only emit the webpack runtime in the first included chunk (https://github.com/ManageIQ/manageiq-ui-classic/pull/4430)

EDIT: tentatively adding to the `vendor` chunk, as that seems to be included first

**Comment by himdel** [comment]
TODO: this breaks `npm run storybook`...

```
info => Loading custom webpack config (full-control mode).
/home/himdel/foreman/node_modules/webpack/lib/DefinePlugin.js:93
		compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/home/himdel/foreman/node_modules/webpack/lib/DefinePlugin.js:93:18)
    at Compiler.apply (/home/himdel/foreman/node_modules/@storybook/core/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/himdel/foreman/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/home/himdel/foreman/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/home/himdel/foreman/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/home/himdel/foreman/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/himdel/foreman/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
```

.. probably just need to upgrade `.storybook/webpack.config.js` as well ... and either replace the config completely or upgrade storybook... https://github.com/storybooks/storybook/pull/3576 ... 4.0.0alpha7+

**Comment by ohadlevy** [comment]
@himdel whats the status of the PR? thanks!

**Comment by ares** [comment]
Thanks @himdel, we're closing this PR since it has been inactive and I believe already resolved by vendor-js, that now locks webpack at 4.29.6 https://github.com/theforeman/foreman-js/blob/master/packages/vendor/package-lock.json#L7416.

**Pull request closed without merging**
