### PR TITLE
Fixes #22110 - allow minitest 5.11 and newer

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
welp, failures *could* be related.

**Comment by evgeni** [comment]
[test foreman]
[test katello]

**Review by ekohl — APPROVED** [review]
:+1: assuming this is green.

**Comment by evgeni** [comment]
[test katello]

**Comment by evgeni** [comment]
cool, the next thing that breaks katello. wth.

**Comment by evgeni** [comment]
[test katello]

**Comment by evgeni** [comment]
So Katello failed once, and twice did it  timeout.

Are we calling this a series of flukes and merging, or does this warrant further investigation?

**Review by ekohl — APPROVED** [review]
We see Katello tests failing all the time. I'd be OK merging this.

It may affect other plugins so a post to https://community.theforeman.org/c/development/9 may be useful for plugin authors.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @evgeni

**Comment by evgeni** [comment]
> We see Katello tests failing all the time. I'd be OK merging this.
> 
> It may affect other plugins so a post to https://community.theforeman.org/c/development/9 may be useful for plugin authors.

https://community.theforeman.org/t/moving-to-minitest-5-14-and-minitest-reporters-in-3-2-develop/26465

**Pull request merged**
