### PR TITLE
Fixes #27313 - Add Annotation Notes support in Images based builds

### PR DESCRIPTION
**Pull request by Rohan21Lobo**
Issue and PR for fog-vsphere https://github.com/fog/fog-vsphere/issues/218

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
This works, we need to release new fog-vsphere and than do the packaging.
I will release the gem tomorrow :)

**Comment by ezr-ondrej** [comment]
ok to test

**Comment by ezr-ondrej** [comment]
[test foreman] should be unrelated

**Comment by tbrisker** [comment]
Please update the minimum fog-vsphere requirement in `bundler.d/vmware.rb` to the one containing this change.

**Comment by ezr-ondrej** [comment]
The fog-vsphere is released.
Packaging: theforeman/foreman-packaging#3935
@Rohan21Lobo could you set `bundler.d/vmware.rb` to `gem 'fog-vsphere', '~> 3.2'`? Thanks!

**Review by ekohl — APPROVED** [review]
:+1: from a packaging side (which is needed because of CODE_OWNERS)

**Comment by ezr-ondrej** [comment]
Retested, works as expected with the new `fog-vsphere`.
Thanks @Rohan21Lobo :+1: merging!

**Pull request merged**
