### PR TITLE
Fixes #20959 - Remove :status option on 'head' to positional argument

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
taken from Dominic's rails51 branch

**Review by tbrisker — CHANGES_REQUESTED** [review]
Looks like you missed one at app/controllers/application_controller.rb:110

**Comment by mmoll** [comment]
indeed, updated.

**Review by tbrisker — APPROVED** [review]

**Comment by mmoll** [comment]
💚

**Comment by tbrisker** [comment]
Thanks @mmoll and @domcleal !

**Pull request merged**
