### PR TITLE
Fixes #12617 - Created new concern: SelectiveClone

### PR DESCRIPTION
**Pull request by ShimShtein**
Created new way to declare which properties will be cloned. This way any extension can add properties that will be cloned.

### CODE REVIEW

**Comment by dLobatog** [comment]
@ShimShtein Next step: move the whole `clone` behavior to a gem :smile: - merging..

**Comment by dLobatog** [comment]
Merged as 64d191c861b83a8619af9373f970bca48ee209ec, thanks @ShimShtein!

**Comment by dLobatog** [comment]
It'd make sense to write this in http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin too @ShimShtein

**Comment by domcleal** [comment]
If this is meant to be used from plugins, it should probably be exposed through the plugin registration API with support to ensure it'll work with class auto-reloading.  I think at the moment it's likely only usable in development from within the class being reloaded itself.

**Comment by dLobatog** [comment]
@domcleal I think plugin host/hostgroup extensions should be able to use it?

**Comment by domcleal** [comment]
Yes, until the class is reloaded?  (The two points I made are only just related, but generally things set through the plugin registration API are always kept in memory and should be taken care of through reloads etc.)

**Comment by ShimShtein** [comment]
@domcleal, about your two points:
1. It doesn't have to be used by plugins. I am using this internally as part of facet initialization.
2. It shouldn't interfere with reloading. You can always add it as an initializer: 

``` Ruby
Rails.application.config.to_prepare do
  Host::Managed.include_in_clone :a, :b, :c
end
```

**Comment by domcleal** [comment]
> 1. It doesn't have to be used by plugins. I am using this internally as part of facet initialization.

I wasn't suggesting it has to be used by plugins, but if it is added to the plugin docs then it should probably work in a particular way.

**Pull request closed without merging**
