### PR TITLE
Fixes #2632 - Translate rest of errors

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
The closing bracket should be before the % sign in all of these, or I think it'll interpolate the string before it translates, so the key won't match.

Could you improve the commit message too please?  e.g. "extract strings from validation errors"

**Comment by ares** [comment]
Thank you for review, I fixed it.

**Comment by lzap** [comment]
Looks good to me. +1

**Comment by domcleal** [comment]
Thanks @ares, merged as e52abb1.

**Pull request closed without merging**
