### PR TITLE
Use React.StrictMode

### PR DESCRIPTION
**Pull request by Ron-Lavi**
StrictMode is a tool for highlighting potential problems in an application.
Like Fragment, StrictMode does not render any visible UI. It activates additional checks and warnings for its descendants.

Note: Strict mode checks are run in development mode only; they do not impact the production build.

StrictMode currently helps with:

Identifying components with unsafe lifecycles
Warning about legacy string ref API usage
Warning about deprecated findDOMNode usage
Detecting unexpected side effects
Detecting legacy context API

### CODE REVIEW

**Comment by MariaAga** [comment]
@laviro, can you post what errors strict mode is currently catching?

**Comment by Ron-Lavi** [comment]
> @laviro, can you post what errors strict mode is currently catching?

They should catch those that describe above: https://github.com/theforeman/foreman/pull/8811#issue-749543893
I saw errors about using legacy lifecycles and some deprecated React methods like findDOMnode, also saw some new errors for elements with the same ID but maybe it was there earlier

**Comment by MariaAga** [comment]
@laviro So we can what issues we have now, can you post the errors it outputs for the current branch?

**Comment by Ron-Lavi** [comment]
@MariaAga, here are a few errors/warnings that were found using this PR (compared to the `develop` branch):

Dashboard (but not specific to Dashboard):

```console
react-dom.development.js:88 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: NavbarHeader, NavbarToggle, VerticalNav.Masthead, withContext(Component)

Learn more about this warning here: https://fb.me/react-legacy-context
  ...
  ...

react-dom.development.js:88 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of notificationContainer which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

react-dom.development.js:88 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: BaseVerticalNavItemHelper
```

Audits:

In addition to the above errors^

```console
react_devtools_backend.js:2540 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Modal

Learn more about this warning here: https://fb.me/react-legacy-context
    in Modal (created by ForemanModal)
```

Models:

```console
react_devtools_backend.js:2540 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Body, Header, Provider
```

**Comment by Ron-Lavi** [comment]
@MariaAga can you take another look? thanks

**Comment by MariaAga** [comment]
Thanks Ron! I think we should fix what we can from the errors, but I don't think we should use the StrictMode.
I tried using foreman with this pr and it looks like it adds around 10 errors per page to the console, and most if not all of the errors are not related to foreman, but are from pf.
I'm against adding strict mode as it clutters our console and makes it difficult to notice other errors, and we can't fix most of them anyway.

**Comment by Ron-Lavi** [comment]
thanks @MariaAga,
moved it to draft, and hopefully, I will have time to dig into it and fix those issues,
in case these issues aren't fixable then it will be just annoying to see the error, I agree with that 👍🏼

**Comment by Ron-Lavi** [comment]
@amirfefer would it be helpful with detecting legacy components in order to make the upgrade to React v18?

**Comment by Ron-Lavi** [comment]
let's close for no interest? :D

**Pull request closed without merging**
