### PR TITLE
Fixes #11016: added test-unit gem for ruby 2.2.x

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by domcleal** [comment]
There seem to be some remaining problems:
1. pg is still failing for some reason
2. MySQL and sqlite3 have an issue in the backtrace silencer, which needs to handle `plugin.name` being nil
3. After the backtrace silencer's fixed, there's probably at least one remaining error

(http://ci.theforeman.org/job/test_develop_pr_core_ruby22/4/database=mysql,ruby=2.2/console)

**Comment by dLobatog** [comment]
Seems to fix the issue with `--trace`, I still get a few errors with Ruby 2.2. If you want to fix those @witlessbird , that'd be great as 2.2 is coming to foreman sooner than later. I'll merge since Jenkins doesn't test 2.2 for the moment.

**Comment by dLobatog** [comment]
Merged as 4ffb5093bca2c2fcd17872ba8e9eed99c5aada49, thanks @witlessbird!

**Comment by domcleal** [comment]
Why was this merged, if the tests fail?  It's of little use if the tests fail, since we can't then add this Ruby version to Jenkins, developers can't use Ruby 2.2, and we don't know if Foreman actually fully functions under this version.

I've filed http://projects.theforeman.org/issues/12219 with notes about the current failures, please take a look so this can be finished properly.

**Comment by iNecas** [comment]
Thanks for merging this PR. Although some tests might be failing, this really unblocked the developers from starting using Foreman with ruby 2.2.0, which is pretty good step towards making Foreman fully working with it. No point in waiting with this kind of PRs until everything works.

**Pull request closed without merging**
