### PR TITLE
Fixes #22596: provide way to opt-out of jquery multiselect.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/22596

### CODE REVIEW

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Review by dLobatog — CHANGES_REQUESTED** [review]
I tested this by adding the the `.without_jquery_multiselect` class to a couple of divs in the Host#new form (in ERB, so they're `.without_jquery_multiselect` as  soon as they're rendered) they seem to still get selected. Adding a couple screenshots:

**Comment by dLobatog** [comment]
screenshot from 2018-02-19 11-28-31
screenshot from 2018-02-19 11-26-32

**Comment by dLobatog** [comment]
Disregard my latest comment, I was trying it out with the wrong field. It works:
screenshot from 2018-02-19 11-41-02

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @waldenraines ~!

**Pull request merged**
