### PR TITLE
fixes #9973 - API doc keyword substitution with sprintf needs symbols

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
Hmm [test]

**Comment by dLobatog** [comment]
@domcleal I guess this will pass all tests after a rebase

**Comment by domcleal** [comment]
@eLobato thanks, rebased

**Comment by dLobatog** [comment]
Merged as 75c85026c9dc1ca3ba4072090fe7e1b4390c5346, thanks @domcleal !

**Pull request closed without merging**
