### PR TITLE
fixes #16287 - Move gridster from bundle to npm

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
test failures do not seems related.

**Review by xprazak2 — DISMISSED** [review]
Works for me, but let's wait with merging until packaging for 1.22 is branched.

**Comment by ohadlevy** [comment]
rebased

**Comment by mmoll** [comment]
@ohadlevy is there a corresponding RPM PR?

**Comment by ohadlevy** [comment]
> @ohadlevy is there a corresponding RPM PR?

https://github.com/theforeman/foreman-packaging/pull/3687

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @ohadlevy!

**Pull request merged**
