### PR TITLE
Fixes #7571 - prevent ContentLoad from firing twice on document.ready

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker I verified that this works, but I'm not sure  what is the difference? I assume that document.body triggered twice also when you get back an html response in ajax? 
but if that's the case, in the host show page we have 4 ajax actions, shouldnt it be executed 5 times then?

**Comment by tbrisker** [comment]
I think the event is being propagated up the DOM tree - firing once on `body` and once on `document`.  Since the handler is bound to the document, it detects every time `ContentLoad` is fired and runs the `onContentLoad` handler, causing the duplicate firing.

**Comment by ohadlevy** [comment]
@tbrisker so does it mean it only happens when there is an AJAX url, or always?

**Comment by tbrisker** [comment]
This was always happening, we only noticed it now because the ajax caused double requests to the server. 
You can add a `console.log("foo")` inside `onContentLoad` and see that it fires twice on every page, not just this one.

**Comment by ohadlevy** [comment]
merged as 02c939c thanks @tbrisker

**Pull request closed without merging**
