### PR TITLE
fixes #2649 - adding missing devel deps

### PR DESCRIPTION
**Pull request by lzap**
SSIA

rubygem-single_test

http://koji.katello.org/koji/taskinfo?taskID=39491
http://koji.katello.org/koji/taskinfo?taskID=39477
http://koji.katello.org/koji/taskinfo?taskID=39479

rubygem-rack-mini-profiler

http://koji.katello.org/koji/taskinfo?taskID=39573
http://koji.katello.org/koji/taskinfo?taskID=39575
http://koji.katello.org/koji/taskinfo?taskID=39576

### CODE REVIEW

**Comment by domcleal** [comment]
There are two more entries in the repoclosure, which are both dependencies for foreman-devel:

<pre>
     foreman-test = 0:1.2.9999-4.201306131832gita933fc2.fc18
     foreman-assets = 0:1.2.9999-4.201306131832gita933fc2.fc18
</pre>

http://ci.theforeman.org/job/packaging_repoclosure/lastBuild/console

Currently -test, -devel and -assets are enabled only on non-SCL builds (conditional in the .spec), so -test and -assets also need adding to comps.  That would then mean checking that we have all the -assets and -test dependencies in comps too, could you verify that?  Maybe run repoclosure locally against a repo that has single_test and rack-mini-profiler added.

I can't say I'm very sure why we're trying to ship these three packages really, they're not terribly useful for the effort.

**Comment by lzap** [comment]
Okay, I reviewed foreman-assets and added it - all deps are already present and are built. Now I will package remaining three deps for foreman-test and push the change here.

Also I sorted everything properly. After the review, I will squash it don't worry :-)

**Comment by lzap** [comment]
@domcleal Done! The only one I had to build was fortunately only "rr" - http://koji.katello.org/koji/taskinfo?taskID=39669

Letting you to review commit by commit and then I can squash for you.

**Comment by domcleal** [comment]
This looks good to me for Fedora 18, thanks.  Could you file a bug so we revisit the spec file itself, refresh the test subpackage and enable it for SCL builds too?  Once squashed, :+1: to merge.

**Comment by lzap** [comment]
There is a task for that - is the one you need any different?

https://trello.com/card/review-bundler-and-spec/5162af6bb868365e0c007135/98

LZ

On Fri, Jun 14, 2013 at 10:21:13AM -0700, Dominic Cleal wrote:

> This looks good to me for Fedora 18, thanks.  Could you file a bug so we revisit the spec file itself, refresh the test subpackage and enable it for SCL builds too?  Once squashed, :+1: to merge.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman/pull/718#issuecomment-19470167

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Ah, I missed that, sorry, was checking redmine.  I just noticed foreman-test is missing from the F18 comps, could you add that too please?

**Comment by domcleal** [comment]
Actually, better add it to both so when it's enabled for SCL it's automatically included?

**Comment by lzap** [comment]
Ah right, good catch. Added.

LZ

On Mon, Jun 17, 2013 at 01:45:11AM -0700, Dominic Cleal wrote:

> Actually, better add it to both so when it's enabled for SCL it's automatically included?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman/pull/718#issuecomment-19532670

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Merged as 63e9d25.  Fingers crossed that's it!  Thanks @lzap.

**Pull request closed without merging**
