### PR TITLE
Fixes #23095 - Port robottelo tests for subnets and parameters

### PR DESCRIPTION
**Pull request by odovzhenko**
Redmine issue: http://projects.theforeman.org/issues/23095

Port robottelo tier1 tests for environment part of robottelo minitest port project https://github.com/SatelliteQE/robottelo/projects/1

Related Robottelo issue: SatelliteQE/robottelo#5874

### CODE REVIEW

**Comment by odovzhenko** [comment]
Rebased.

**Comment by mmoll** [comment]
The failures on MySQL seem related

**Comment by odovzhenko** [comment]
@mmoll MySQL tests fixed.

**Comment by mmoll** [comment]
test failure unrelated

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
Merged, дякуємо @odovzhenko!

**Pull request merged**
