### PR TITLE
Fixes #6518 - lookup the bmc smartproxy via subnets.id

### PR DESCRIPTION
**Pull request by dLobatog**
Discussion started in #1569

### CODE REVIEW

**Comment by sodabrew** [comment]
This looks reasonable. @bwitt and I can test your alternate approach.

**Comment by sodabrew** [comment]
This is working for us. Thanks @eLobato!

**Comment by bwitt** [comment]
Thanks @eLobato !

**Comment by domcleal** [comment]
Merged as 57a32e9 for Foreman 1.6.0.  Thanks @bwitt, @eLobato and @sodabrew!

**Pull request closed without merging**
