### PR TITLE
Fixes #18227 - clean up variables after rendering

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mmoll** [comment]
@ares this needs a rebase now

**Comment by ares** [comment]
Thanks @mmoll, I rebased it.

**Comment by ares** [comment]
Test failures are unrelated :-)

**Review by lzap — APPROVED** [review]
Overall looks good, was trying to find if this does not enable breaking safemode but looks safe. The test is a bit unreadable tho :-)

**Comment by ares** [comment]
Just fixed typo in commit message, @lzap anything to add?

**Comment by lzap** [comment]
Nope, tests are not green tho.

**Comment by ares** [comment]
[test foreman]

**Comment by ares** [comment]
@lzap only codeclimate is red now which I believe is not mandatory to be green.

**Comment by lzap** [comment]
Small typo in the comment, then merging thanks!

**Comment by ares** [comment]
@lzap I fixed the comment

**Comment by lzap** [comment]
Thanks, good job!

**Pull request merged**
