### PR TITLE
Fixes #15278 - taxonomies support granular filters

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
@ares Sorry, I'm not able to reproduce this. I created an user with the following filters:
- view/create/edit/remove_locations , name ~ a
- view/create/edit/remove_domains, name = lobatolan.home

I tried to edit a Location or a Domain but neither threw any error. I guess I'm missing something else to reproduce the bug. Can you write a test for it? 

Thanks!

**Comment by ares** [comment]
I hoped it would be obvious that if `all_checkbox` returns nil, it will fail on `nil + something` at https://github.com/ares/foreman/blob/ca465a1f81fab540ab6970bf426b8fec14f25579/app/helpers/taxonomy_helper.rb#L163 anyway I added the test that verifies that. Unfortunately it has to create several objects in DB.

I think you might have left an unlimited filter with view_domain permission in Default role when you tried to reproduce. I haven't noted it anywhere but there must be no unlimited filter for the resource.

**Comment by dLobatog** [comment]
@ares Thanks, I can reproduce it now. Merging if Jenkins thinks it's :+1: too

**Comment by dLobatog** [comment]
@ares Actually not.. I think you need to mark the string as `html_safe` or similar where you concatenate it -> https://github.com/ares/foreman/blob/ca465a1f81fab540ab6970bf426b8fec14f25579/app/helpers/taxonomy_helper.rb#L163 

screenshot from 2016-06-03 13-49-26

**Comment by ares** [comment]
Added `html_safe`, I wonder how I could have missed that, it displayed the form correctly for me. I thought multiple_select always returns some html tags... anyway good catch, thanks @dLobatog

**Comment by dLobatog** [comment]
Merged as f358e67675391aaf8151f6c55227d3a6919738a9, thanks @ares!

**Pull request closed without merging**
