### PR TITLE
Fixes #3350 - Adds title on login page

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by lzap** [comment]
We already have something like:

```
  def title(page_title, page_header = nil)
    content_for(:title, page_title.to_s)
    @page_header       = page_header || @content_for_title || page_title.to_s
  end
```

Maybe to reuse that?

**Comment by ares** [comment]
@lzap as you can see, such method can't be used if you don't want to create page header. We'd have to add another bool argument whether to create header or not which I find redundant. Setting title is already abstracted by `content_for`

**Comment by lzap** [comment]
Oh right, +1

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by ohadlevy** [comment]
merged as a20ca53, thanks!

**Pull request closed without merging**
