### PR TITLE
Refs #3809 - Remove cops for empty lines

### PR DESCRIPTION
**Pull request by dLobatog**
Cops to standardize lines before/after methods, module definitions, etc..

### CODE REVIEW

**Comment by daviddavis** [comment]
LGTM

:+1: :+1: :+1:

**Comment by ares** [comment]
+1

**Comment by domcleal** [comment]
Could you combine your PRs please, with the exception of the assignment one (which is still under debate I'd say)?  Then I can merge them without requesting a series of rebases :)

**Comment by daviddavis** [comment]
@domcleal done.

https://github.com/theforeman/foreman/pull/2174

**Comment by dLobatog** [comment]
@daviddavis thanks!

**Comment by dLobatog** [comment]
Closed in favor of https://github.com/theforeman/foreman/pull/2174

**Pull request closed without merging**
