### PR TITLE
refs #6832 - prevent extraction of string interpolation

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dLobatog** [comment]
@domcleal Strange error - http://ci.theforeman.org/job/test_develop_pr_core/3550/database=postgresql,ruby=1.9.3/console , looks like a problem with gettext, maybe it's temporary?

**Comment by domcleal** [comment]
@eLobato yeah, bug in fast_gettext 0.9.1, see foreman-dev

**Comment by domcleal** [comment]
[test]

**Comment by tbrisker** [comment]
:+1: makes sense.

**Comment by dLobatog** [comment]
Merged as d8f79a65575055483211d60c8ee9a005c3bdc4d6, the `.to_s` was actually even redundant in the original code, thanks @domcleal !

**Pull request closed without merging**
