### PR TITLE
Fixes #36543 - open navigation items in new tab

### PR DESCRIPTION
**Pull request by MariaAga**
ctrl+click currently opens items only if they are in the third level ( for example "Report Templates" will open, but "All hosts" will not)

### CODE REVIEW

**Comment by MariaAga** [comment]
draft as this causes double navigation

**Comment by MariaAga** [comment]
Fixed

**Review by ekohl — COMMENTED** [review]
In Firefox you can also use middle mouse to open a new tab. The code suggests it would also work, but did you by any chance test that too?

**Comment by MariaAga** [comment]
by mistake only checked middle key and not ctrl + click, which doesnt work, so I'll fix that and will make sure it works on firefox and chrome

**Comment by MariaAga** [comment]
Should be good now, couldnt find a way without this workaround

**Comment by ofedoren** [comment]
[test unit]
[test integration]

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga, checked with Chrome and Firefox, middle button click and ctrl click both work and open a new tab for second level (all hosts) and third level (templates).

**Pull request merged**
