### PR TITLE
Fixes #34546 - Bookmarks should update the searchbar

### PR DESCRIPTION
**Pull request by MariaAga**
Can be tested on Audits page, before this pr when a user selected a bookmark the list would update but the searchbar wouldn't.
Now the search bar gets the bookmark text

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
I'm not against this solution, it looks clean enough, tho I was always wondering why autocomplete is connected component? I really do hate that ^\_^
I think that SearchBar should be connected not autocomplete, that would also solve the issue with having multiple autocompletes on the page.
I'd really love if we could fix that and keep the query for the search component.
Tho it's just my suggestion and I do get that it would make the PR much more complex, so definitelly not a blocker for this, the best would be to get this in and follow up with the rewrite if someone feels the same way about the Autocomplete ^\_^

**Comment by MariaAga** [comment]
Yeah the components are a bit messy and there are more bugs (if a user enters a search and then moves to a react page the search stays for example) 
I think it's best that we make this change when we re-write the search into pf4, after all my reading the auto complete component I might do that :sweat_smile:

**Comment by ezr-ondrej** [comment]
Yeah, that's a great idea, then lets get this in and rewrite once we migrate to PF4 :+1:

**Review by ezr-ondrej — APPROVED** [review]
LGTM, needs testing tho, if someone can test I would appreciate it, but if not I'll get to it next week :)

**Review by lzap — APPROVED** [review]
Tested okay thanks.

**Pull request merged**
