### PR TITLE
Fixes #27531 - fix storybook after vendor update

### PR DESCRIPTION
**Pull request by sharvit**
The related commit in `foreman-js`:
https://github.com/theforeman/foreman-js/commit/6026737cf2d8ee8c3633d5e8eccfc43885c56bb3

### CODE REVIEW

**Review by amirfefer — DISMISSED** [review]
Stroybook works well!
Thanks @sharvit  !

**Comment by tbrisker** [comment]
This requires bumping the packaged version as well.

**Review by waldenraines — DISMISSED** [review]
LGTM

**Comment by sharvit** [comment]
Once https://github.com/theforeman/foreman/pull/6988 merge I will rebase this PR.

**Comment by sharvit** [comment]
Rebased

**Review by tbrisker — COMMENTED** [review]
Thanks @sharvit !

**Review by tbrisker — APPROVED** [review]

**Pull request merged**
