### PR TITLE
Fixes #29490 - adds http_proxy support in GCE

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Review by shiramax — COMMENTED** [review]
@kgaikwad 
I've tested this PR and I'm getting: 
2020-05-17T12:49:41 [D|app|405f6095] Unpermitted parameter: :cr_id
2020-05-17T12:49:41 [W|app|405f6095] Failed to connect
2020-05-17T12:49:41 [D|app|405f6095] Backtrace for 'Failed to connect' error (ArgumentError): unsupported proxy https://proxy4
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/httpclient-2.8.3/lib/httpclient.rb:508:in `proxy='
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:407:in `new_client'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:216:in `client'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/google-api-client-0.23.9/generated/google/apis/compute_v1/service.rb:20058:in `list_zones'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/fog-google-1.8.2/lib/fog/compute/google/requests/list_zones.rb:13:in `list_zones'
 | /home/mshira/git/foreman/app/models/compute_resources/foreman/model/gce.rb:49:in `zones'
 | /home/mshira/git/foreman/app/models/compute_resources/foreman/model/gce.rb:315:in `validate_zone'
 | /home/mshira/git/foreman/app/models/compute_resources/foreman/model/gce.rb:290:in `ensure_attributes_and_values'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:606:in `catch'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:606:in `block in default_terminator'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:202:in `block in halting'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `block in invoke_before'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `each'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `invoke_before'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:134:in `run_callbacks'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activemodel-6.0.2.2/lib/active_model/validations.rb:407:in `run_validations!'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activemodel-6.0.2.2/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activemodel-6.0.2.2/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activemodel-6.0.2.2/lib/active_model/validations.rb:337:in `valid?'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.2.2/lib/active_record/validations.rb:68:in `valid?'
 | /home/mshira/git/foreman/app/models/compute_resource.rb:111:in `test_connection'
 | /home/mshira/git/foreman/app/models/compute_resources/foreman/model/gce.rb:193:in `test_connection'
 | /home/mshira/git/foreman/app/controllers/compute_resources_controller.rb:134:in `test_connection'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.2.2/lib/abstract_controller/base.rb:196:in `process_action'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 | /home/mshira/git/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 | /home/mshira/git/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 | /home/mshira/git/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 | /home/mshira/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'


when pressing 'Test connection', does it make sense ? is there a way for me to test it? 
thanks

**Comment by kgaikwad** [comment]
> @kgaikwad
> I've tested this PR and I'm getting:
> 2020-05-17T12:49:41 [D|app|405f6095] Unpermitted parameter: :cr_id
> 2020-05-17T12:49:41 [W|app|405f6095] Failed to connect
> 2020-05-17T12:49:41 [D|app|405f6095] Backtrace for 'Failed to connect' error (ArgumentError): unsupported proxy https://proxy4
> | /home/mshira/.rvm/gems/ruby-2.5.5/gems/httpclient-2.8.3/lib/httpclient.rb:508:in `proxy=' | /home/mshira/.rvm/gems/ruby-2.5.5/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:407:in `new_client'

@shiramax,
Did you verify `test_connection` action while creating http_proxy i.e `https://proxy4`? is it working for you? From above log, IIUC then it seems like your foreman server is not able to reach this proxy server.

**Review by shiramax — APPROVED** [review]
Thanks @kgaikwad , It did fail because https://proxy4 was not running.

**Comment by kgaikwad** [comment]
@tbrisker ,
This is RFE related to GCE. As it is very small change can I create cherry-pick pull-request against 2.1?

**Comment by tbrisker** [comment]
> @tbrisker ,
> This is RFE related to GCE. As it is very small change can I create cherry-pick pull-request against 2.1?

yes

**Pull request merged**
