### PR TITLE
Fixes #21451 - Close button in the notifications drawer

### PR DESCRIPTION
**Pull request by sharvit**
Close button should have a blue highlight (found here):

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/notification-drawer-vertical-nav.html#0

### CODE REVIEW

**Comment by sharvit** [comment]
Done with commits.
Can be merged now.

**Comment by ohadlevy** [comment]
[ok to test]

**Comment by ohadlevy** [comment]
@sharvit please rebase to avoid test failure - thanks

**Comment by ohadlevy** [comment]
thanks @sharvit

**Pull request merged**
