### PR TITLE
Fixes #10194 - token_duration > 0, updated help text

### PR DESCRIPTION
**Pull request by xprazak2**
token generation cannot be disabled, token_duration setting must be greater than 0

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by domcleal** [comment]
> token generation cannot be disabled

Er, why?

**Comment by xprazak2** [comment]
In [additional info](http://projects.theforeman.org/issues/10194), there is a suggestion to remove the possibility to disable token generation. Do we want to keep it?

**Comment by domcleal** [comment]
I personally don't see the harm - some slightly ambiguous help text isn't a good reason for me.

**Comment by domcleal** [comment]
I personally don't see the harm in keeping it - some slightly ambiguous help text isn't a good reason for me to remove it.

**Comment by xprazak2** [comment]
ok, I will make changes to keep it

**Comment by domcleal** [comment]
Merged as 615728b, thanks @xprazak2.

**Pull request closed without merging**
