### PR TITLE
Fixes #24654 - use dynamic attrs for Factory Bot 5.x compat

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
See GH-5962 for a pinning, more suitable for cherry-picking to the -stable branches.

**Comment by tbrisker** [comment]
[test foreman]

**Comment by tbrisker** [comment]
Failing tests are unrelated, merging so a pr fixing the webpack issue will be capable of passing CI.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
