### PR TITLE
Fixes #30905 - do not use ancestry 3.2.0

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Do not install ancestry 3.2.0 as it has bad require.
Details in https://github.com/stefankroes/ancestry/issues/510

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test upgrade] why do you ignore me, upgrade? :(
EDIT: ah, right it runs on previous commit... no bueno.

**Comment by ezr-ondrej** [comment]
It's as :green_apple: as it gets .... I know very sad... xD

**Comment by tbrisker** [comment]
@ezr-ondrej 3.2.1 was released which should fix this error, i believe the pinning is no longer needed

**Comment by evgeni** [comment]
Jenkins is for some reason still pulling in 3.2.0 *sometimes*, making builds unreliable. Let's just not allow that!

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
:green_apple:

**Pull request merged**
