### PR TITLE
Fixes #24621 - Use custom scope in ResourceSwitcher

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Usage: pass `:resource_filter => "use_this_query = true"` as one of the options for `breadcrumbs` helper.

**Comment by ares** [comment]
Seems like travis errors are related, @xprazak2 mind to take a look? It would be good to have code review done by @ui/ux team. I can help testing.

**Comment by xprazak2** [comment]
Tests should be fixed, lets see if Travis agrees.

**Comment by xprazak2** [comment]
[test]

**Comment by ares** [comment]
Works nice, could someone from @theforeman/ui-ux review the JS part? I haven't spotted anything wrong but I don't feel comfortable merge without JS expert ACK. :+1: for ruby part and functionality.

**Review by tstrachota — APPROVED** [review]
Works fine and the code looks good to me.

**Comment by tstrachota** [comment]
Katello failures are unrelated, merging. Thanks @xprazak2

**Pull request merged**
