### PR TITLE
Fixes #31474 - ALTLinux icons show

### PR DESCRIPTION
**Pull request by majioa**
- [x] + 16x16 ALTLinux icon
- [x] + 64x64 ALTLinux icon
- [x] ! code parsing a record name to match ALTLinux family

### CODE REVIEW

**Comment by ekohl** [comment]
This is now a PR to 1.24 stable, but we only accept PRs to develop. When they're merged, they can be cherry picked to supported stable branches.

Do you know what the license is on ALTLinux icons? Can we include them in our repo?

**Comment by majioa** [comment]
@ekohl license of icons are GPLv3, and you can include them into the repo.

> This is now a PR to 1.24 stable, but we only accept PRs to develop. 

Ok, please do what needed to merge there

**Comment by majioa** [comment]
Sorry GPL-2.0+

**Comment by ezr-ondrej** [comment]
@majioa sorry, but you'll need to close this PR and open another one against develop branch.
Once we merge that one, we can backport it to stable versions, but stable versions are `2.2` and `2.3`, so we would not backport it to 1.24, as there wouldn't be another release for that version, so the code would not get to the production.

Why do you want this in 1.24 release?

**Comment by majioa** [comment]
because we have version 1.24.3 here in ALTLinux, so we need the version exactly

**Comment by majioa** [comment]
Of course, when we'll build Foreman 2, think, wll create create the PR against the develop.

**Comment by ezr-ondrej** [comment]
> because we have version 1.24.3 here in ALTLinux, so we need the version exactly

Unfortunatelly we don't support that version anymore, so even if we would merge this, it would not get to you, because the change would not get packaged and released.

The best option for you to get this change to you is open the PR against `develop` branch, once merged backport to 2.2 and after the next 2.2 release upgrade to that release. In the meantime, you'll have to patch your foreman manually if you need this change before upgrade.

**Comment by ezr-ondrej** [comment]
Closing this in favor of #8199

**Pull request closed without merging**
