### PR TITLE
Fixes #25777 - upgrade patternfly-react

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by mmoll** [comment]
needs a corresponding RPM PR.

**Comment by sharvit** [comment]
@mmoll I had some troubles when I tried to do so.
see: https://community.theforeman.org/t/unable-to-npm2rpm/12426

**Comment by sharvit** [comment]
Bump https://github.com/theforeman/foreman-packaging/pull/3339

**Comment by ohadlevy** [comment]
test failure not related.

**Review by ohadlevy — APPROVED** [review]

**Pull request merged**
