### PR TITLE
Fixes #33426 - changing virtual in ks fixed

### PR DESCRIPTION
**Pull request by lzap**
In https://projects.theforeman.org/issues/28521 I refactored how virtual tty changing work, but it is not working correctly. According to

https://listman.redhat.com/archives/kickstart-list/2016-March/msg00000.html

there really needs to be both `exec` and `chvt3` with redirection of stdout and stderr. So I am reverting the old behavior to fix this.

### CODE REVIEW

**Comment by ares** [comment]
note for myself - test with both 7 and 8

**Comment by lzap** [comment]
FYI @ares it's been confirmed it works for both in https://bugzilla.redhat.com/show_bug.cgi?id=1997065 so you can theoretically just double check the syntax :-)

**Review by ares — APPROVED** [review]
Thanks @lzap, merging!

**Comment by ezr-ondrej** [comment]
CP 3.0: b3b1e643f

**Pull request merged**
