### PR TITLE
Fixes #26826 - Increase js heap size for plugin asset compile

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like katello is tested against develop instead of stable: `Foreman::PluginRequirementError: ERF72-8416 [Foreman::PluginRequirementError]: katello plugin requires Foreman >= 1.23 but current is 1.21.3`

**Comment by mmoll** [comment]
@ekohl Yes, that's known

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
third time lucky :man_shrugging:

**Pull request merged**
