### PR TITLE
add packit config

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
This actually worked, and I am impressed!

https://copr.fedorainfracloud.org/coprs/g/theforeman/pr-testing-playground/build/5201845/

**Comment by ehelms** [comment]
The Packit robot seems a bit noisy. Can it be configured to just fail like our other jobs and then click the failure to investigate the issue?

**Comment by evgeni** [comment]
> The Packit robot seems a bit noisy. Can it be configured to just fail like our other jobs and then click the failure to investigate the issue?

Yes, no.
Normal failures (as in: the package failed to build in copr) are only reported as states in GitHub, the same way all our other checks do.
What we've seen here are two (different) issues to even set the job up:
1. "Failed to load packit config file" I had errors in the config (or the prod instance didn't have my patches yet *whistle*)
2. config/permission changes to the custom copr project, I stopped using that after the patches have been deployed, so that won't happen again

**Review by ehelms — APPROVED** [review]
I am good to give this a trial.

**Pull request merged**
