### PR TITLE
Fixes #9147 - move managed checks to the start of the DHCP/DNS/TFTP orchestration checks

### PR DESCRIPTION
**Pull request by ares**
Replaces #2116, there was last missing check but @GregSutcliffe won't get to it anytime soon so I took his commit, fixed https://github.com/theforeman/foreman/pull/2116#discussion-diff-24655127 and amended (that's the only change I did).

### CODE REVIEW

**Comment by lzap** [comment]
Testing, someone review pls

**Comment by lzap** [comment]
Tested with and without discovery (bare-metal provisioning). Code looks sane. I am not merging since I am little biased in getting this in ASAP :-) @orrabin @eLobato @orabin ?

**Comment by ares** [comment]
(no need to review the whole PR, which was reviewed already, just the diff linked), @eLobato already spent time on reviewing it so I think he'll be able to finish it tomorrow

**Comment by dLobatog** [comment]
Merged as 5440d482b0087fe29b3fb4567e0ca73f2d3af221, thanks @ares @lzap @GregSutcliffe @orrabin

**Pull request closed without merging**
