### PR TITLE
Fixes #36395 - move value setting to seed

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by evgeni** [comment]
In https://github.com/theforeman/foreman/pull/9500 we discussed that such things are better as seeds, not migrations.

**Comment by ShimShtein** [comment]
Moved to seeds

**Comment by evgeni** [comment]
I wonder if we should add a test for that in `test/unit/tasks/seeds_test.rb`? something like:

```ruby
test 'ensures stable instance_id' do
  seed
  instance_id = Setting[:instance_id]
  assert instance_id, "instance_id was not generated"

  seed
  assert_equal instance_id, Setting[:instance_id]
end
```

**Comment by ShimShtein** [comment]
Tests added

**Review by evgeni — APPROVED** [review]

**Pull request merged**
