### PR TITLE
Fixes #26553 - autocomplete reduce the usage of dispatch

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Reduce the use of `dispatch`, instead return plain objects.
Thanks @sharvit for the idea, looks cleaner.

### CODE REVIEW

**Review by sharvit — DISMISSED** [review]
Thanks @Laviro

**Comment by Ron-Lavi** [comment]
@amirfefer @tbrisker could you ack?

**Comment by Ron-Lavi** [comment]
@theforeman/ui-ux could you take a look ?

**Comment by sharvit** [comment]
It's a simple change, can we merge it? @tbrisker @ohadlevy

**Comment by mmoll** [comment]
@Laviro please rebase :)

**Comment by mmoll** [comment]
[test katello]

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @Laviro!

**Pull request merged**
