### PR TITLE
Allow using thin as a back-end server

### PR DESCRIPTION
**Pull request by iNecas**
New setting in sysconfig/foreman:

```
FOREMAN_USE_THIN=1
```

### CODE REVIEW

**Comment by ohadlevy** [comment]
the init scripts / rpm packaging have been moved to a new repo, and I guess we should remove these files from here once they new repo is fully up2date? @jmontleon whats your take about this?

**Comment by jmontleon** [comment]
The SPEC file is still copying foreman.init file into place from the downloaded source. If it isn't included there, then it will need to be downloaded as part of separate source or always included as a patch.

**Comment by iNecas** [comment]
I vote for moving it into the rpms repository, since it's more rpms specific (unless it's reused by the DEB packages)

**Comment by jmontleon** [comment]
My point is the foreman.init file still needs to be sourced from somewhere. Usually an RPM includes the source code for the program as a gz/bz2 tar file, the SPEC file, and patches (which are hopefully temporary). 

If the init file is not included in the foreman repo, then it would need to be included in some other way. You can certainly have more than one source included, but that seems silly for inclusion of just one file. 

And Debian, et al still need (or at least probably want) an init script, so I don't think that it is really distro or rpm specific.

**Comment by ohadlevy** [comment]
@iNecas did this get merged into the RPM eventually?

**Comment by iNecas** [comment]
@ohadlevy nope, from the discussion above I understood that tha init script will be still managed in the foreman repo, so this changes should go there as well

**Comment by ohadlevy** [comment]
@jmontleon bump?

**Comment by jmontleon** [comment]
I did some poking at other rpms (httpd, etc) and it looks like startup scripts get packaged as additional sources pretty frequently, so I will take foreman.init, tidy this and the other issue I have for it up, and do it that way.

**Comment by skottler** [comment]
Is this still moving forward?

**Comment by jmontleon** [comment]
The updated scripts should be included in 1.0.0-1.

**Comment by skottler** [comment]
Awesome! Can we close this pull request or should it stay open for tracking?

**Comment by jmontleon** [comment]
Not sure if it was added to the Deb packages. Might be worth adding Greg to the conversation.

**Comment by ohadlevy** [comment]
since this is not part of foreman core now, maybe (if still required) a new pull request should be made against the packaging repo.

**Pull request closed without merging**
