### PR TITLE
Adding more files (log, reports) to gitignore

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by domcleal** [comment]
Where do these come from?  I don't recognise them.

**Comment by daviddavis** [comment]
I think the log.age files might be getting generated by our logging setup but I've never seen these reports before. They're like `test/reports/TEST-ActionController-TestCase.xml`. From googling, it looks like ci_reporter generates them?

**Comment by skottler** [comment]
These are fine to add to `.gitignore`, but the xmlunit reports only get generated by the rake task that jenkins runs to create test report data that Jenkins can consume. `rake test` is usual way for humans to run the tests.

**Comment by daviddavis** [comment]
@skottler the reports are actually getting generated every time we run our Katello tests. The only way we have to run them is via the rake task @ehelms setup:

https://github.com/Katello/katello/blob/engine/lib/katello/tasks/test.rake

Would you know of a way to prevent the reports getting generated?

**Comment by domcleal** [comment]
I think this is still useful, so merged as 47b19af1.  Thanks @daviddavis.

The reports should only get generated when running the jenkins:\* rake tasks, not the main test:\* ones.

**Comment by daviddavis** [comment]
Oh ok. Thanks!

**Comment by isratrade** [comment]
+1

**Pull request closed without merging**
