### PR TITLE
Fixes #29471 - add 6.0 deprecations to whitelist

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test foreman]

**Comment by mmoll** [comment]
This perhaps needs a refresh and should go in last with a switch to Rails 6 at least in one test combination, so we always see, if the list is up to date.

**Comment by ezr-ondrej** [comment]
#7575 reduces the list noticeably. (if merged)

**Comment by tbrisker** [comment]
fixed in gh-7322

**Pull request closed without merging**
