### PR TITLE
fixes #11389 - removing API V1, moving to plugin

### PR DESCRIPTION
**Pull request by unorthodoxgeek**
moved to plugin: https://github.com/unorthodoxgeek/foreman_v1

### CODE REVIEW

**Comment by domcleal** [comment]
This API shouldn't be removed until it's been deprecated with documentation and logging through at least one release.  I'd suggest starting with that before considering removal.

**Comment by unorthodoxgeek** [comment]
may I suggest adding the plugin by default (removing it from gemfile in a later version), and putting the deprecation warnings in the plugin itself?

**Comment by domcleal** [comment]
There's no precedent for adding a Foreman plugin to Foreman's default Gemfile.  At the very least it would cause a chicken and egg bootstrapping issue with packaging that you'd have to fix somehow, since they'd require each other to build.  It would also make Foreman core dependent on compatibility of the plugin with core, and I'm unsure if we'd want that.

**Comment by unorthodoxgeek** [comment]
@ohadlevy - you put the ticket in, how do you think it should be done?

**Comment by ohadlevy** [comment]
@domcleal can't we simply document it? it seems a common practice around other large projects, e.g. rails.

**Comment by domcleal** [comment]
Sure, deprecate it with documentation before removing it - consider adding it to the 1.11 checklist.

**Comment by dLobatog** [comment]
Closing due to inactivity

**Pull request closed without merging**
