### PR TITLE
fixes #10021 - config groups are now taxable

### PR DESCRIPTION
**Pull request by ohadlevy**
requires testing

### CODE REVIEW

**Comment by domcleal** [comment]
Unit tests and rubocop are failing.

**Comment by ohadlevy** [comment]
@domcleal tests pass now

**Comment by ohadlevy** [comment]
@domcleal ping

**Comment by dLobatog** [comment]
@ohadlevy Are the permissions checked on ConfigGroups#index? I can assign one config group to organization 'foo' and another to organization 'bar' yet I see both on the list when I'm scoped to only see 'foo', or 'bar'.

Similarly on Host#new, it seems useless to choose a organization to limit config groups? Neither choosing an organization on the form nor scoping my session to a organization limits the config groups shown in the Puppet tab.

**Comment by tbrisker** [comment]
@ohadlevy,
Thank you very much for your efforts!
This PR has been open for a very long time with no activity.
Please indicate if you plan to continue working on it or not; if not, feel free to close it.
If you do not respond either way within a couple of weeks, I will assume this PR is abandoned and will go ahead and close it for you.

**Comment by ohadlevy** [comment]
@tbrisker thanks for the kind reminder - I'm not planning to work on it, if anyone else wishes he may use this as a starting point - thanks

**Pull request closed without merging**
