### PR TITLE
Fixes #9444 - prevent 404 error on current_parameters and domain_selected

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by dLobatog** [comment]
@tbrisker I can't seem to get the original 404s on the latest develop branch, could you provide some instructions? Currently I:
- Go to Host group#new
- Choose an existing domain
- Choose no domain
- Check production.log, I can't find any 404.

Does this only happen with Katello installed?

**Comment by domcleal** [comment]
@eLobato as noted in http://projects.theforeman.org/issues/9444#note-3, I think the domain selected stuff is irrelevant now (maybe even the controller action is now unused) and it's just when you select an environment that you get a 404 on current_parameters.

**Comment by dLobatog** [comment]
@tbrisker Currently the 404 I get when selecting an environment is `HostgroupsController#puppetclass_parameters` with `Parameters: {"hostgroup_id"=>"null"}`. Is this PR supposed to fix that?

**Comment by dLobatog** [comment]
Ok just got it, @tbrisker could you please write a test to ensure we don't break this again? :+1: to merge after that in my opinion.

**Comment by dLobatog** [comment]
Merged as e1aec1dcdecbe4f9006c9404c820072e8e636cb6, thanks @tbrisker !

**Pull request closed without merging**
