### PR TITLE
CP 3.9 Fixes #36966, #36896, #36963 UI fixes

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
Actually, please cherry pick the real commits that were merged. Because of GitHub's way of merging the commit sha changes. So the "Cherry picked from" SHAs don't resolve in a normal repository.

**Comment by MariaAga** [comment]
@ekohl what are the "real commits" and where do I find them?

**Review by ekohl — APPROVED** [review]
Disregard that, I was confused by the GH UI. Somehow https://github.com/MariaAga/foreman/commit/be9867524534ff962f1642cafe2a304b3cc213a5 didn't show as being in develop but it really is.

Shame I didn't see this earlier (because I was on vacation) and nobody else did either. Now it missed 3.9.0 GA.

**Comment by ekohl** [comment]
Ok, so I wasn't blind and those commits do indeed only live in your fork. Not in develop itself. For next time, the process is to pull the develop branch and use the commit IDs there, not from the PR you made.

We should have documentation on this, but I'm not aware of any that we have today.

**Comment by MariaAga** [comment]
I use your comment from here as documentation :sweat_smile:  https://community.theforeman.org/t/update-stable-branch-workflows/34136/2

**Pull request merged**
