### PR TITLE
Fixes #24562 - upgrade enzyme to 3.4.0

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by ohadlevy** [comment]
such an annoying change, I have no idea why they would change the snapshots :( :+1: for the PR - thanks!

**Review by ohadlevy — APPROVED** [review]

**Comment by boaz0** [comment]
[test upgrade]

**Comment by ohadlevy** [comment]
[test upgrade]

**Review by ekohl — APPROVED** [review]
Packaging ignores enzyme

**Pull request merged**
