### PR TITLE
[WIP] Fixes #14833 - Add oVirt API option to provision VMs from template

### PR DESCRIPTION
**Pull request by ik5**
based on @dLobatog original PR.

### CODE REVIEW

**Comment by ik5** [comment]
@orrabin, missing some tests, and there is a [fog-ovirt](https://github.com/fog/fog-ovirt/pull/38) PR for it as well, still need more testing from my side

**Comment by ShimShtein** [comment]
@ik5, can you please rebase?

**Comment by ik5** [comment]
@ShimShtein now the code breaks on my tests on `ovirt has no compute
service`, not sure if it something I did, or something in `foreman`, after
the rebase, prior to it, the code worked :/

So still investigating it

**Comment by orrabin** [comment]
@ik5 the code in `preallocate_disks` is only executed if the disk is preallocated, what if you want to clone but keep it as thin provisioning?

**Comment by ik5** [comment]
at the moment it will take the template version, exactly the point where
I'm thinking at this time what to do :D

**Comment by orrabin** [comment]
Replaced by https://github.com/theforeman/foreman/pull/6295

**Pull request closed without merging**
