### PR TITLE
fixes #25154 - do not join reports when searching

### PR DESCRIPTION
**Pull request by timogoebel**
This might not be a proper fix. We might need to optimize the generated SQL or add indices.

### CODE REVIEW

**Review by ares — APPROVED** [review]
Makes sense, tested and works fine, pending jenkins ACK :+1:

**Comment by timogoebel** [comment]
@ares: I guess this is still slow when you explicitly search for `origin = Puppet` (or similar).

**Comment by ares** [comment]
Yes, but that I think is still better than nothing, before the change we did not allow searching by origin. People will experience this though when they click on dashboard widget link. Possibly also when rendering the widgets, I haven't check the time difference before the change.

**Comment by timogoebel** [comment]
All right, I gave that a go. Explicitly searching for a source is fast enough. From my end, this is ready to 🚢.

**Review by tbrisker — APPROVED** [review]
Thanks @timogoebel !

**Pull request merged**
