### PR TITLE
Removed has_many_polymorphs and renamed to thread_session.rb

### PR DESCRIPTION
**Pull request by isratrade**
all tests passed

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
No more git gems! Yay!

**Comment by ohadlevy** [comment]
looks _good_  (I think) can you see if we are missing any methods, e.g. something like:

User.methods (before the change) - User.methods (after the change)?

**Comment by isratrade** [comment]
It looks like the the only extra methods are those added by the gem "has_many_polymorphs"

(without the gem) > User.methods.count
=> 598 
(with the gem) > User.methods.count
 => 605 
["_metaclass", "instantiate_with_polymorphic_checks", "_logger_debug", "has_many_polymorphs", "acts_as_double_polymorphic_join", "_logger_warn", "create_has_many_polymorphs_reflection"] 

(without the gem) > User.methods.count
=> 569 
(with the gem) > User.methods.count
 => 577 
["has_many_polymorphs", "_metaclass", "instantiate_with_polymorphic_checks", "acts_as_double_polymorphic_join", "create_has_many_polymorphs_reflection", "original_primary_key", "_logger_warn", "_logger_debug"]

**Comment by ohadlevy** [comment]
merged - thanks!

**Comment by GregSutcliffe** [comment]
That makes the packaging _so_ much easier.....

**Pull request closed without merging**
