### PR TITLE
Fixes #34142 - make the core cards arrangeable in new host page (#8995)

### PR DESCRIPTION
**Pull request by amirfefer**
(cherry picked from commit 71ce89cba9532ccae50b422236ac77a45dd3ee25)

### CODE REVIEW

**Comment by amirfefer** [comment]
[test katello]

**Comment by amirfefer** [comment]
[katello test]

**Comment by amirfefer** [comment]
[katello test]

**Comment by ezr-ondrej** [comment]
This has already beend cherry-picked in 7f4a799d36d830817e14bb4bafd34d6b5538a109, sorry for the confusion. Closing this one, thanks @amirfefer !

**Pull request closed without merging**
