### PR TITLE
fixes #17197 - don't update DNS on ip6 change to empty string

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by timogoebel** [comment]
@domcleal : Thanks. Looks great. Have you investigated where the "nil" vs. "empty" values come from?

**Comment by domcleal** [comment]
`nil` could be set if the host's created through the API or fact imports etc, it's the default value of most fields. The web UI form will always send an empty string for an empty field, so it changes value.

**Comment by timogoebel** [comment]
Thanks, l'll merge when the tests have run.

**Comment by timogoebel** [comment]
Merged, thanks for this quick fix @domcleal .

**Pull request merged**
