### PR TITLE
Fixes #27385 - upgrade vendor the v0.1.1

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by sharvit** [comment]
Do not merge, releasing v0.1.1

**Comment by sharvit** [comment]
Ok to merge :+1:

**Review by tbrisker — APPROVED** [review]
Thanks @sharvit ~

**Comment by tbrisker** [comment]
packaging is at https://github.com/theforeman/foreman-packaging/pull/3948

**Review by ekohl — APPROVED** [review]

**Pull request merged**
