### PR TITLE
Add support to the Portuguese of Brazil

### PR DESCRIPTION
**Pull request by flamarion-zz**
Use very Foreman in my daily life, and as I have enough experience in translation (I've been a translator / proofreader GNOME and Debian for several years) I am willing to translate the interface Foreman for my language so that its use is more extensive here in Brazil.

### CODE REVIEW

**Comment by lzap** [comment]
Hello,

thanks for the contribution. We will include the new language in Foreman
1.5.

By the way, you can also use Transifex.com for translations:

http://projects.theforeman.org/projects/foreman/wiki/Translating

But PO files is okay, works for us. Just subscribe to the Transifex.com
project for news. We have usually "merge windows" when we ask
translators to complete translations (e.g. before releases) and we send
notifications via Transifex messages.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
I see you've started submitting updates to Transifex - is that currently up to date with the translations you've done so far in this PR?  If so, we'll just close this PR for now and once the translation on Tranisfex is at about 50% then we'll pull it down in a sync.

Thanks for your efforts!

**Comment by flamarion-zz** [comment]
I did this PR before ask in #theforeman-dev how to the best way for translate the foreman.
From now on I gonna do every translations on the Transifex.
Please, close this PR.
Thank you.

**Comment by ohadlevy** [comment]
thanks!

**Pull request closed without merging**
