### PR TITLE
Fixes #29988 - Upgrade Rails to 6.0.3.1

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by mmoll** [comment]
The deprecation message seems to have changed, however, it can get deleted in `config/as_deprecation_whitelist.yaml` if it's fixed with this anyway. :+1:

**Comment by mmoll** [comment]
Katello failures unrelated, I'd say. Needs RPMing.

**Comment by tbrisker** [comment]
[test katello] just to make sure

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
