### PR TITLE
Fixes #27668 - Allow bootdisk_build? in safemode

### PR DESCRIPTION
**Pull request by Rohan21Lobo**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Good catch!

**Comment by ekohl** [comment]
Bootdisk is a plugin. Can't the plugin set the whitelist?

**Comment by ekohl** [comment]
I think we should revert this and add the Jail to the bootdisk plugin like [foreman_chef](https://github.com/theforeman/foreman_chef/blob/cc06963dce795dee98e22bafa446abae5003de4b/app/models/foreman_chef/concerns/host_extensions.rb#L79-L81) does for its own methods.

**Comment by Rohan21Lobo** [comment]
@ekohl This should be fine?

https://github.com/Rohan21Lobo/foreman_bootdisk/commit/eda2b11183910cd1b4924ed061070fa72a507f0a

**Comment by ekohl** [comment]
I think that's correct yes.

**Comment by tbrisker** [comment]
tests did not run and are now failing. as suggested by @ekohl, i'll go ahead and revert this change in favor of fixing it in the plugin.

**Comment by Rohan21Lobo** [comment]
I submitted this against bootdisk project https://github.com/theforeman/foreman_bootdisk/pull/83

**Comment by lzap** [comment]
Sorry, I haven't realized I am in core. Thanks.

**Pull request merged**
