### PR TITLE
Fixes #29183 - hide image selection from compute-profile in GCE

### PR DESCRIPTION
**Pull request by kgaikwad**
+ adding @jyejare and @shiramax into the loop

### CODE REVIEW

**Review by apuntamb — APPROVED** [review]
@kgaikwad looks good to me.

**Comment by kgaikwad** [comment]
@ezr-ondrej, adding you into loop. It is a small UI change for Compute Profile page.

**Comment by ezr-ondrej** [comment]
This PR looks quite ok, but all the image handling is done in `compute resources -> images` and just selecting the image in provisioning. Maybe it would be worth to leave out this option here completely?

**Review by ezr-ondrej — APPROVED** [review]
Moving image is for an RFE, this works as expected :+1:

**Pull request merged**
