### PR TITLE
Fixes #34498 - added RHEL9 and CentOS9 Guest OSes

### PR DESCRIPTION
**Pull request by snagoor**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
All VMWare docs I could find are out of date, but I trust you :) @ezr-ondrej

**Comment by ezr-ondrej** [comment]
I can't find the values in any doc, do we have the doc or are we adding the values in hope vmware will add them ? :)

**Comment by snagoor** [comment]
> I can't find the values in any doc, do we have the doc or are we adding the values in hope vmware will add them ? :)

@ezr-ondrej These values are from the VMware API and supported GuestOS list is added with each release, you can take a look at the below URL

https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html

**Review by ezr-ondrej — APPROVED** [review]
Great, thanks @snagoor ! :+1:

**Comment by ezr-ondrej** [comment]
CP 3.2: #9143

**Comment by ares** [comment]
FYI, this does nothing, it just adds a label for the value that we expect from rbvmomi. That gem is archived (and we only package old version), it didn't recieve an update since 2021, so rhel 9 won't appear in the list. We should at some point start migrating to the new API and drop this gem entirely.

**Pull request merged**
