### PR TITLE
Fixes #30502 - remove unused charts

### PR DESCRIPTION
**Pull request by ezr-ondrej**
On statistics rewrite to React, some charts were left unused, I think it's time to drop their legacy implementation.
I think first PR on the way to the charts left unused is #3603. I'm not sure, if we continued using those charts later on somewhere else.

### CODE REVIEW

**Comment by ekohl** [comment]
It's good practice to link to the exact commit that dropped it. Is it 6cc3bb9e2f1c9fac2021e014d4e81d8410753e46?

Also note that `app/assets/config/manifest.js` still links to `charts.js` that's removed here. There may be more references.

**Comment by ezr-ondrej** [comment]
I think first PR was #3603 where we dropped the main usage of the charts (in statistics).
The `chart.js` is being kept, there is still one chart that is being used (yes, we should transfer that one to `c3`/React as well)

**Comment by ohadlevy** [comment]
does this impact plugins?

**Comment by ezr-ondrej** [comment]
> does this impact plugins?

Yes, possibly, I haven't found any that would be using it, but it would use a deprecation warning just to be sure I guess.
Lets do it for one version (2.2).

**Comment by ohadlevy** [comment]
can find using github search, e.g.
https://github.com/search?l=HTML%2BERB&q=flot_pie_chart&type=Code

**Comment by ezr-ondrej** [comment]
Mmm after some thinking, let's switch to PF4 charts first.

**Pull request closed without merging**
