### PR TITLE
Fixes #25817 - Allow update datacenter by name in API

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by chris1984** [comment]
[test katello][test foreman]

**Review by chris1984 — COMMENTED** [review]
@orrabin is this going to affect anything with VMware datacenters

**Comment by orrabin** [comment]
@chris1984 it shouldn't because the VMware does not implement `get_datacenter_uuid` but it it does right now there is a bug in the PR and if it's needed we can implement `get_datacenter_uuid` with different behavior.

**Review by chris1984 — DISMISSED** [review]

**Comment by chris1984** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Thanks @orrabin !

**Pull request merged**
