### PR TITLE
WIP: @foreman/vendor sub-package

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like this will need a rebase and integration tests look to be broken.

@sharvit @tbrisker Since this is a large change, it would help me if we came up with agreed criteria to get this merged and work towards that. 

Are there other UI developers who should be pinged specifically to review and test?

**Comment by johnpmitsch** [comment]
The overall approach looks good at first glance, I'll poke around more as this PR progresses!

One concern - If I am a developer who hasn't been part of these conversations, how do I know how to add a new dependency using the npm scripts? Can we document this somewhere?

**Comment by ehelms** [comment]
@sharvit What are the next steps for this PR?

**Comment by sharvit** [comment]
@ehelms I will soon remove the WIP tag and will post a status update with a call to review

**Comment by sharvit** [comment]
This solution has abandoned. New work in progress here: https://github.com/theforeman/foreman/pull/6605

**Pull request closed without merging**
