### PR TITLE
Refs #28391 - snapshots update after vendor 3.9.0 upgrade with patternfly-react 2.39.10

### PR DESCRIPTION
**Pull request by Ron-Lavi**
patternfly fixed their modal issue which broke our tests
updated the PF version in foreman-vendor-core, blocked by https://github.com/theforeman/foreman-js/pull/98
modal tests forward-ref snapshots need to be updated.

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
using `vendor v3.9.0` @sharvit could you take a look? thanks

**Comment by tbrisker** [comment]
Is it me or did we have to change these snapshots multiple times already when bumping vendor versions? Perhaps we should not be using snapshots for something that changes this often?

**Comment by Ron-Lavi** [comment]
@tbrisker, actually we downgraded patternfly since there was an issue that caused our tests to fail, and when they fix it we upgraded to the newest version, that's why you see the same snapshots changing which all relate to the modals changes in react-bootstrap.

**Review by sharvit — APPROVED** [review]
Thanks @laviro

**Comment by Ron-Lavi** [comment]
packaging PR got merged https://github.com/theforeman/foreman-packaging/pull/4510

**Review by evgeni — APPROVED** [review]
ACK package.json

**Pull request merged**
