### PR TITLE
Fixes #8418 - Add 'facts' feature to features

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by dLobatog** [comment]
@orrabin Doesn't this belong in [foreman-discovery](https://github.com/theforeman/foreman_discovery)?

**Comment by orrabin** [comment]
@eLobato discovery needs the facts to be enabled but this is just to show if facts are enabled or not so I don't think it's specific to discovery

**Comment by domcleal** [comment]
Please "fix" a different ticket as that one is already in the smart proxy repo, or use "refs" at a bare minimum (I'd prefer not reusing a ticket across repos).

Features are added via DB seeds, not migrations.

**Comment by dLobatog** [comment]
Merged as a2523ccf030169eaf170c329e2f68193777ab2cb , thanks @orrabin !

**Pull request closed without merging**
