### PR TITLE
fixes #11745 - page fails to load properly after editing a template

### PR DESCRIPTION
**Pull request by phirince**
This is the best solution I could come up with. Please review and let me know what you think.

-PP

### CODE REVIEW

**Comment by domcleal** [comment]
Hi @phirince.  I invited you to our GitHub organisation so your PRs get automatically tested.  You should have an e-mail about it.  Once accepted, please set your membership to public [on this page](https://github.com/orgs/theforeman/people) so Jenkins can see you're a member.

[test] in the meantime.

**Comment by phirince** [comment]
Thanks @domcleal !

-PP

**Comment by domcleal** [comment]
Thanks, that'll be easier.

I'm a little concerned that the code is getting that far (set_mode is quite deep)  I think fixing it further up might be better.  There's a check that happens before the diff/edit mode is even set to see if the page needs an editor:

https://github.com/theforeman/foreman/blob/develop/app/assets/javascripts/editor.js#L30-L32

Would moving the set_diff/edit_mode into that conditional, to run after create_editor(), work?

**Comment by phirince** [comment]
Yes, move the set_diff/edit_mode to the conditional is the right fix.

But this problem went away after this commit:
https://github.com/theforeman/foreman/commit/a265235eab649fa76e942205ef4964579532ce72#diff-fd61d47ff16a49707d50fa5f9ae7c5f5

But this is still a logical error and causes the function to be called unnecessarily after "Submit". I'll Update the new diff. Feel free to close it with or without merging it.

-PP

**Comment by domcleal** [comment]
Merged as 083edbe, thanks @phirince.

I fixed up the indentation, just check your editor is set to 2 space soft tabs.

**Pull request closed without merging**
