### PR TITLE
Fixes #25701 - remove old settings from settings.yaml.test

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
This does depend on https://github.com/theforeman/foreman/pull/6338, right?

**Comment by tbrisker** [comment]
@ekohl no, we already default to true if the setting is missing in `config/settings.rb`

**Comment by tbrisker** [comment]
[test katello] doesn't seem related, but just to make sure

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
