### PR TITLE
fixes #16039 - update fog-openstack paths to load extensions

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
Tests running at http://ci.theforeman.org/job/test_develop_pull_request/16160/.

**Comment by tbrisker** [comment]
:+1: once Jenkins is green.

**Comment by dLobatog** [comment]
Merged as 14c3ceb37f1258ca3a51ac9860944e4f80930ba5, thanks @domcleal!

**Comment by dLobatog** [comment]
I'll cp it to 1.12-stable

**Pull request closed without merging**
