### PR TITLE
Description settings search

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
@girijaasoni how about this?

**Comment by stejskalleos** [comment]
But it's case sensitive wich beats the purpose :/

**Comment by stejskalleos** [comment]
TBH there i going to be more to unwrap, it's not fixing all issue but it's something ...

**Comment by girijaasoni** [comment]
> @girijaasoni how about this?

Name autocomplete isn't working either for the settings with non nil values. 
All the settings which had no value are removed from the db, this fix would only be a hack for description

**Comment by stejskalleos** [comment]
Yeah, but maybe we should fix it in other PR, this one at least fix the search for description

**Pull request closed without merging**
