### PR TITLE
Fixes #18422 - Expose dynflow worker pool size in config

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by iNecas — APPROVED** [review]
Tested and works well. Letting others to review but ok to merge from my point

**Review by dLobatog — APPROVED** [review]
Thanks @adamruzicka , out of curiosity why the db_pool_size has a + 5 ? Will merge after knowing that (could be a typo)

**Comment by adamruzicka** [comment]
Dynflow has pool_size set to 5 and db_pool_size set to pool_size + 5 by default. My understanding was that the db_pool should be large enough to have a connection for each worker and some more just in case. Did I get that right, @iNecas ?

**Comment by iNecas** [comment]
Yes. That's the reason: one connection in pool for each worker + additional for non-worker connections to database.

**Comment by dLobatog** [comment]
Thanks @iNecas too

**Pull request merged**
