### PR TITLE
fixes #14961 - show subnet usage statistics

### PR DESCRIPTION
**Pull request by timogoebel**
This is just a little i hacked together to show the IP usage of a subnet.
I haven't tested this against a real smart proxy, yet. Works great with the internal DB.

What do you think?

image

### CODE REVIEW

**Comment by lzap** [comment]
I think it's great from the UI perspective, but the API needs to be generic (and perhaps more simple - just to return the grand total). Changes are likely required on the proxy side, we don't want to transfer all the IPs just to get the grand total. Also keep in mind that for new features we always want CLI/API support as well.

If this was just to test if we like it - I totally love it! Go ahead if you want to carry on.

**Comment by timogoebel** [comment]
@lzap : Yes, this is not ready for merging. Wanted to get some early feedback. What do you mean by the API needing to be more generic? Would you mind to elaborate? :-)

**Comment by lzap** [comment]
> @lzap : Yes, this is not ready for merging. Wanted to get some early feedback. What do you mean by the API needing to be more generic? Would you mind to elaborate? :-)

Sure, I think the Subnet class should only expose one method which will
return grand total and maximum available addresses. Currently it's a bit
DB IPAM oriented.

## 

Later,
 Lukas #lzap Zapletal

**Comment by timogoebel** [comment]
Reworked API, added REST-API, added smart proxy interface in https://github.com/theforeman/smart-proxy/pull/434

Do we need/want caching for this?

**Comment by ohadlevy** [comment]
does it make any sense to cache it? what about subnets without a proxy
(e.g. only db allocation)?

**Comment by timogoebel** [comment]
> does it make any sense to cache it?

I'm still undecided. Apparently calculating the free IPs on a dhcp smart proxy is way more difficult than I thought (and therefore more expensive to do). Caching makes sense. Have to look into that first.

> what about subnets without a proxy
> (e.g. only db allocation)?

They are easy to handle and should work already.

**Comment by ohadlevy** [comment]
@timogoebel bump?

**Comment by timogoebel** [comment]
@ohadlevy : Actually, what kept me from finishing this is the smart-proxy part. Maybe @witlessbird can help with implementing an api that shows how many ips are available and free? I'll be more than happy to revisit this, then. I still believe Foreman should be able to replace an IPAM like bluecat or infoblox completely. Maas.io has something similar, so we should too. :-)

**Comment by lzap** [comment]
Can't we simply use DHCP IP range defined in foreman? Isn't what's on proxy irrelevant?

**Comment by timogoebel** [comment]
@lzap: We can only rely on the data in Foreman when using the internal DHCP provider. When we have an actual dhcp server serving the ranges I believe Foreman doesn't have all the necessary data.

**Review by dLobatog — CHANGES_REQUESTED** [review]
Setting to WoC until the smart-proxy part is done

**Pull request closed without merging**
