### PR TITLE
Fixed #7020: Validation instead or error when comments in 'audit comment' exceeds 255 characters

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@orrabin I assume adding it into the audit class did not work?

**Comment by orrabin** [comment]
@ohadlevy no, it didn't show an error but the template wasn't really saved

**Comment by orrabin** [comment]
[test]

**Comment by ohadlevy** [comment]
merged as 3702133 thanks @orrabin

**Pull request closed without merging**
