### PR TITLE
Add a default setting for livbirt networks

### PR DESCRIPTION
**Pull request by GregSutcliffe**
I'm fed up of typing "virbr1" 20 times a day, so this adds a Setting for the default network to attach libvirt NICs to.

### CODE REVIEW

**Comment by ohadlevy** [comment]
maybe it simple makes more sense to map subnets to compute resources networks?

**Comment by GregSutcliffe** [comment]
What if you don't have a proxy for every network? I have libvirt hosts with multiple internal networks, and I don't use a proxy for the host-only networks.

**Comment by ohadlevy** [comment]
proxy? i mean subnet

**Comment by GregSutcliffe** [comment]
Well, ok, so I mean that I have networks that Foreman knows nothing about, and I don't want to manage them. I should still be able to attach virtual NICs to them

**Comment by ohadlevy** [comment]
yeah, I just think of a simple join between subnets and compute resources

so if you select a compute resource X, and subnet Y, you get network name Z?

**Comment by GregSutcliffe** [comment]
I get that, but what if one of the interfaces doesn't belong to a foreman subnet? Worse, what if there's conflicting IP ranges? Consider this:

libvirt host A:
  virbr0: NAT network, 192.168.100.0/24 (Foreman subnet: foo.com)
  virbr1: Host-only network, 192.168.150.0/24 (not in foreman)
libvirt host B:
  virbr0: NAT network, 192.168.101.0/24 (Foreman subnet: bar.com)
  virbr1: Host-only network, 192.168.150.0/24 (not in foreman)

Neither of the Host-Only networks are in Foreman, and if I tried to add them, it would complain about conflicting ranges (192.168.150.0 in two places). How to handle subnets in multiple locations is a wider discussion though :P

I think your suggestion is fine, so long as we keep the ability to type into the box if required. Using the simple join to populate the "default value" would be fine though.

**Comment by ohadlevy** [comment]
ok - bump? :)

**Comment by GregSutcliffe** [comment]
Give me a chance - I've got a lot to do in the next 2 weeks :)

**Comment by ohadlevy** [comment]
closing this ticket for now, reopen once a new patch is ready :)

**Comment by GregSutcliffe** [comment]
So I'm guessing this needs a new table, and some UI changes? Presumably, we need a way to create the Resource X / Subnet Y = Device Z mapping. Should I mock something up and let @abenari take a look?

**Comment by ohadlevy** [comment]
a join table of 
subnets, compute resource and the relevant mapping
e.g.

subnet = DC1
compute_resource = vsphere
network_name_in_vsphere =  'DC1-net'

something like that, makes sense?

the harder part would be to handle the UI (esp around multi nic)

**Pull request closed without merging**
