### PR TITLE
Fixes #34481 - Update foreman-js to 10.1.0

### PR DESCRIPTION
**Pull request by ofedoren**
Needed by https://github.com/theforeman/foreman/pull/9051.

Packaging PR: https://github.com/theforeman/foreman-packaging/pull/7601.

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
Thanks, @ofedoren 👍

Tested and PF4 pages seem to work as expected. could you please fix the broken snapshots?

**Comment by ofedoren** [comment]
Thanks, @amirfefer :) I forgot to run the tests locally :facepalm: All is green now, except Katello, but I guess I can't fix them here :/

**Review by amirfefer — APPROVED** [review]
Thanks, @ofedoren !

needs a packaging ACK

**Comment by amirfefer** [comment]
@theforeman/packaging could we get an ACK here as well? :)

**Review by evgeni — APPROVED** [review]

**Review by ezr-ondrej — APPROVED** [review]
Thanks @ofedoren ! :+1:

**Pull request merged**
