### PR TITLE
Fixes #30344 - use pf4 navigation

### PR DESCRIPTION
**Pull request by MariaAga**
Using the new pf4 navigation.
Using a popper workaround as suggested here: https://github.com/patternfly/patternfly-react/issues/6396#issuecomment-947703071
Not sure if we want to keep the white color for a hovered menu item? 
flyout will open on focus, hover and click. Will close on a click outside of the flyout.
Will merge all the commits later :) 

Screenshot from 2021-10-25 10-07-00

Screenshot from 2021-10-25 10-07-14

### CODE REVIEW

**Comment by MariSvirik** [comment]
@MariaAga based on [PF4 page](https://www.patternfly.org/v4/components/navigation#flyout) the 'selected state' should be just on the selected nav items (in your example Hosts). Otherwise, it's not clear which page is selected.

What's more, hovered items in flyout nav should look the same on all levels. Also, PF4 example uses the same background for the first level nav and for the other levels as well.  I'm not sure if that's an easy fix in foreman and also not sure if that would visually work better.
Screenshot 2021-10-25 at 11 11 32

**Comment by MariaAga** [comment]
@MariSvirik  Shouldn't the hover change the color?
here the page is "Hosts > Hardware" and "Locations" is being hovered.
Changed the colors as instructed.
Screenshot from 2021-10-25 15-23-03

**Comment by ekohl** [comment]
https://community.theforeman.org/t/new-pf4-navigation/25838 was opened. Let's try to avoid having two discussions in parallel and stick to one place.

**Comment by MariaAga** [comment]
Current bugs:

- [ ] I killed login page css

Screenshot from 2021-10-25 15-45-50
- [ ]  Also need a solution to user not being able to access menu items that are located very low and can't be scrolled down to.
- [ ] Should apply pf4 capitalization rules
- [ ] Should highlight selected org/location in "mobile view"
- [ ] Popovers are hidden by a grey thing: 
Screenshot from 2021-10-28 12-18-40

**Pull request closed without merging**
