### PR TITLE
fixes #2996 - VM show screen syntax error on ruby 1.8

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
Braces do match, ship it!

**Comment by domcleal** [comment]
[test] again, rubygems failed

**Comment by skottler** [comment]
@domcleal can you rebase this? I'll test it after that's done.

**Comment by domcleal** [comment]
@skottler thanks, rebased

**Comment by ohadlevy** [comment]
rebased and merged as 2460248 for 1.3, thanks!

**Pull request closed without merging**
