### PR TITLE
Fixes #35346 - change only the corresponding network

### PR DESCRIPTION
**Pull request by sbernhard**
Issue: all networks are changed currently.
Solution: find out which network need to be changed by using the nic id.

### CODE REVIEW

**Comment by sbernhard** [comment]
Before the change:
https://user-images.githubusercontent.com/25485845/183510723-ebcb0e91-19a0-4a57-9e6b-00a008768614.mp4

After the change:
https://user-images.githubusercontent.com/25485845/183510737-533db08a-b920-4a40-820e-5c48c4ef02ad.mp4

**Comment by stejskalleos** [comment]
Hi @sbernhard, where can I find these fields? I thought it's about creating / editing host but it's not there

**Comment by sbernhard** [comment]
Compute profile for a ovirt compute resource.

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**, works as expected.
Thanks @sbernhard !

**Pull request merged**
