### PR TITLE
Fixes #11709 - better error for DNS conflict timeouts

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
Amended text change - the behavior is different when `query_local_nameservers` is true. This gives us better error message (no 500 error - proper validation error now) and also gives consistent info to users.

**Comment by unorthodoxgeek** [comment]
can you add a test to mimic the error and check that the behaviour is correct?

**Comment by lzap** [comment]
Sure, pushed.

**Comment by dLobatog** [comment]
Merged as 613bef500f858adcf4556a8b56b14dae03b368e7, thanks @lzap!

**Pull request closed without merging**
