### PR TITLE
Fixes #32808 - Add visual Amazon support

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by ekohl** [comment]
With these images we always ask for proof that we're legally allowed to ship this image. There may be trademarks on it which can prevent that.

**Comment by sbernhard** [comment]
> With these images we always ask for proof that we're legally allowed to ship this image. There may be trademarks on it which can prevent that.

It's pretty hard to find anything related Amazon Linux and its Logo trademarks.

What would be the alternative? Create a "alternative" logo like a box with "AL2" in it?

**Comment by lzap** [comment]
Approval via email is okay: https://press.aboutamazon.com/contact-pr

We have acquired approvals for many commercial logos, should not be any problem.

**Review by ekohl — COMMENTED** [review]
I think AL can be confusing since AlmaLinux has the same abbreviation. It's also important that the commits are squashed so we don't have a problematic file (due to license) in our git history.

Have you sent anything to Amazon's PR contact email? Any progress on it?

**Comment by sbernhard** [comment]
> I think AL can be confusing since AlmaLinux has the same abbreviation. It's also important that the commits are squashed so we don't have a problematic file (due to license) in our git history.
> 
> Have you sent anything to Amazon's PR contact email? Any progress on it?

Yes, I sent a mail but no response since 2 weeks. 

Alma Linux has a logo - so I would assume there is no real conflict.  Would you prefer "Amazon"?

Of course,I would squash it later. Just want to know your opinion.

**Comment by ekohl** [comment]
> Yes, I sent a mail but no response since 2 weeks.

Perhaps we can ask Red Hat legal for advice.

> Alma Linux has a logo - so I would assume there is no real conflict. Would you prefer "Amazon"?

I think `Amazon` would be clearer than AL.

> Of course,I would squash it later. Just want to know your opinion.

Thanks. I'm also making a note so we don't forget it either :)

**Comment by ezr-ondrej** [comment]
@sbernhard we can use the colored letter in the meantime while waitig for amazon aproaval.

**Comment by sbernhard** [comment]
> @sbernhard we can use the colored letter in the meantime while waitig for amazon aproaval.

what do you mean by "the colored letter"? Do you mean what we have currently? Or should I adjust something in this PR?

**Review by ezr-ondrej — APPROVED** [review]
Sorry @sbernhard, `AL` works :)

**Comment by ezr-ondrej** [comment]
@ekohl I think `Amazon` is too long and I'm ok with AL until we get the copyright ack for the real icon. I'd not block this for preferences over icon. Can we get this in 2.6 as is ? :)

**Review by ekohl — APPROVED** [review]

**Pull request merged**
