### PR TITLE
fixes #6091 - menu removal wasn't traversing menu hierarchy

### PR DESCRIPTION
**Pull request by sseago**
This will need backport to 1.5-stable as the foreman_openstack_simplify plugin in Staypuft depends on it.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Redmine ticket's at http://projects.theforeman.org/issues/6091.  Please amend the commit message to read "fixes #6091 - menu removal ...".

Thanks for resubmitting, it'll be reviewed soon.

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Jenkins is reporting test failures, could you try fixing please?

<pre>
Expected [] to be nil. (test_delete_missing)
/var/lib/workspace/workspace/test_develop_pr_core/database/mysql/puppet/3.0/ruby/1.9.3/test/unit/menu_mapper_test.rb:172    
</pre>

It'd also be appreciated if you could add a similar unit test for the issue at hand.  Thanks.

**Comment by sseago** [comment]
Sure, I'll look into that now.

**Comment by sseago** [comment]
OK, I've fixed the test failure (tests depended on the return value of the delete method, which my original change had not preserved properly), and I added a new test to verify that delete of submenu items works now/

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @sseago, merged as cd3baa1 for Foreman 1.5.1.

**Pull request closed without merging**
