### PR TITLE
fixes #32516 - Add Rocky icons

### PR DESCRIPTION
**Pull request by lumarel**
This PR will add the Rocky Linux logo to Foreman.
Here also the reference about the [discussion](https://community.theforeman.org/t/client-recognition-for-rocky-linux-in-foreman-katello/23437).

I checked the licensing about the logos with the Rocky core team so this shouldn't be a problem! (ref: [here](https://github.com/rocky-linux/branding))

If I can improve something I'm really open for recommendations, as I'm not really familiar with the code of Foreman/Katello.
Thank you!

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Review by lzap — APPROVED** [review]
License is good, thanks.

FYI making PRs from `develop` branch will cause you headache once you pull :-)

**Comment by lumarel** [comment]
> 
> 
> License is good, thanks.
> 
> FYI making PRs from `develop` branch will cause you headache once you pull :-)

Thank you as well @lzap ! And for the recommendation as well, I'm still trying to learn how this works in bigger repos :)

**Comment by ezr-ondrej** [comment]
CP 2.5: #8587

**Pull request merged**
