### PR TITLE
Fixes #22875 - Fix digest limits (for 1.16-stable)

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
TY

**Review by dLobatog — APPROVED** [review]
:+1: if tests pass, thanks @mmoll

**Comment by mmoll** [comment]
@ekohl It seems that still the wrong Katello version is used. You meant this was fixed in the past?

**Comment by dLobatog** [comment]
@mmoll I'm fine with fixing this myself if it breaks with another Katello version, unlikely

**Comment by ekohl** [comment]
@mmoll it was pointed out to me that I was looking at the wrong job and this is not yet fixed.

**Pull request merged**
