### PR TITLE
Fixes #9631 - adds missing bond test

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test] because of poltergeist timeout

**Comment by dLobatog** [comment]
It failed just on MySQL and Ruby 2.0.0, let's try again [test]

**Comment by unorthodoxgeek** [comment]
yay! more tests!
:+1:
why did it fail on mysql? poltergeist or an actual failure? if it's just silly poltergeist stuff, I say merge.

**Comment by domcleal** [comment]
We only run integration tests on PostgreSQL to save time, so er, unless you have a link to the failure, I don't know.

**Comment by ares** [comment]
the fail was unrelated IIRC

**Comment by dLobatog** [comment]
Merged as b3bdb09208a3966cda8cf5828802fed5157b7e1c, thanks @ares

**Pull request closed without merging**
