### PR TITLE
roles edit page folded by first letters.

### PR DESCRIPTION
**Pull request by abenari**
just because roles page is too long.

### CODE REVIEW

**Comment by domcleal** [comment]
Nice, I like the idea of improving this UI.  I'm less sure about using first letters, as that means you need to know roughly what the name of the security groups is.  Could we provide something like a list of the groups that expands, or a better way to show an overview?

**Comment by ohadlevy** [comment]
@abenari @domcleal I tend to agree its not idea, couple of ideas:
- add popup on each letter (with the permission group)
- change to accordion style ?

anything else? any other similar screens which we might be able to consider for evaluation?

**Comment by domcleal** [comment]
The accordion style is what I had in mind too.

**Comment by abenari** [comment]
comments accepted will send a new PR with a different implementation, closing this one.

**Pull request closed without merging**
