### PR TITLE
Fixes #21448 - execute npm run lint from context of plugins

### PR DESCRIPTION
**Pull request by tstrachota**
Moves linting of plugins to a postlint script similar to how we do npm install for plugins.

### CODE REVIEW

**Comment by xprazak2** [comment]
It works for katello, but it only lints the index.js file and not the whole webpack folder:

```
[vagrant@centos-devel foreman]$ npm run lint

> TheForemanDevDeps@1.17.0 lint /home/vagrant/projects/foreman
> eslint -c .eslintrc webpack/ script/ || exit 0

// output ommited
✖ 3 problems (3 errors, 0 warnings)

> TheForemanDevDeps@1.17.0 postlint /home/vagrant/projects/foreman
> node ./script/npm_lint_plugins.js

> katello@1.0.0 lint /home/vagrant/projects/katello
> eslint --fix webpack/index.js || exit 0

// output ommited
✖ 6 problems (6 errors, 0 warnings)
```

I think you want the lint command in plugins to use the foreman's config.

All plugins must also have the lint task defined in their package.json, because we run this from their directory and not from foreman.

**Comment by tstrachota** [comment]
@xprazak2 I updated the script and it checks whether the lint task is defined now.

Imho it's correct that a plugin decides what files should be checked.

**Comment by xprazak2** [comment]
👍 works now, plugins without a `lint` task are skipped so there are no errors.

Ok, we'll say that it is a plugin's responsibility to add a `lint` task to its package.json.

**Review by waldenraines — APPROVED** [review]
This works great for me, thanks @tstrachota!

**Comment by tstrachota** [comment]
Tests seem to have failed because of `factory_girl` dependency. I triggered them again.

**Comment by tstrachota** [comment]
Tests are green. Any other comments to the code?

**Review by waldenraines — APPROVED** [review]
LGTM

**Review by dLobatog — APPROVED** [review]
Works great, thanks @tstrachota 

Could you add a section to the [Foreman handbook](https://github.com/theforeman/theforeman.org/blob/gh-pages/handbook.md) about plugins & linting?

**Comment by danseethaler** [comment]
Sorry, I'm late to the conversation. I have a few questions about the purpose and scope of this change. Let me know if I'm missing something obvious 😊

What's the purpose of linting all the foreman plugins at once? Shouldn't each plugin manage their own linting process in their own repository? I think it would be great to try and standardize on linting rules but this seems like it would simply run the individual lint scripts in each isolated repo. I'm not sure what we gain from that.

When would `npm run lint` be executed? As far as I understand `npm run lint` is never called as part of any automated processes associated with PRs. We are only relying HoundCI to call out any linting failures. We would definitely run it locally before a commit but in that situation the linting status of plugins is irrelevant.

IMHO relying on a linting process that requires all files to be in harmony with the current style rules can make it difficult to make changes to the rules. In #4997 I recommend upgrading to `eslint-config-airbnb` but only updating the react components when we work on them. This allows us to keep our rules up to date without having to spend days researching and refactoring our react code.

The code here looks great - just trying to get a better understanding of our process. Thanks for any feedback!

**Pull request merged**
