### PR TITLE
Fixes #26341 - graphql: Run GraphQL tests in Jenkins

### PR DESCRIPTION
**Pull request by kamils-iRonin**
This adds graphql tests to the Jenkins flow

### CODE REVIEW

**Comment by timogoebel** [comment]
This at least picks up the failing tests.

@evgeni: You being the Jenkins master, mind taking a 👀?

**Comment by evgeni** [comment]
@timogoebel I have no idea what I am looking at or what I should do. The only thing I see are tests that fail.

**Comment by timogoebel** [comment]
@evgeni: I wanted to know your opinion if merging this PR will break the CI in any way as we change the rake task that jenkins calls. We obviously have to fix the tests before we merge this.

What I currently see is that Jenkins now reports:
```
Build finished. 120 tests run, 0 skipped, 10 failed.
```

It should have run more tests.

**Comment by evgeni** [comment]
it aborted after the graphql tests i think, fix em andit will run the rest

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Test failures are unrelated.

**Comment by timogoebel** [comment]
Thanks, @kamils-iRonin.

**Comment by tbrisker** [comment]
Looks like test-develop is now failing: http://ci.theforeman.org/blue/organizations/jenkins/foreman-develop-test/detail/foreman-develop-test/54/pipeline/

**Comment by tbrisker** [comment]
Looks like test-develop is now failing: http://ci.theforeman.org/blue/organizations/jenkins/foreman-develop-test/detail/foreman-develop-test/54/pipeline/

**Comment by kamils-iRonin** [comment]
That's weird. I've run `bundle exec rake jenkins:unit TESTOPTS="-v" --trace
` command locally and all GraphQL tests passed successfully.

**Comment by timogoebel** [comment]
@theforeman/infrastructure: Mind taking a look?
The error message is

```
2.3 -I"lib:test" -I"/usr/local/rvm/gems/ruby-2.3.5@foreman-develop-test-54-ruby-2-3-postgres/gems/rake-12.3.2/lib" "/usr/local/rvm/gems/ruby-2.3.5@foreman-develop-test-54-ruby-2-3-postgres/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/graphql/queries/architecture_query_test.rb" "test/graphql/queries/architectures_query_test.rb" "test/graphql/queries/authorized_model_query_test.rb" "test/graphql/queries/location_query_test.rb" "test/graphql/queries/locations_query_test.rb" "test/graphql/queries/model_query_test.rb" "test/graphql/queries/models_query_test.rb" "test/graphql/queries/nodes_query_test.rb" "test/graphql/queries/operatingsystem_query_test.rb" "test/graphql/queries/operatingsystems_query_test.rb" "test/graphql/queries/subnet_query_test.rb" "test/graphql/queries/subnets_query_test.rb" "test/graphql/queries/usergroup_query_test.rb" "test/graphql/queries/usergroups_query_test.rb" -v --ci-reporter

-- execute("SET CONSTRAINTS ALL DEFERRED;")

   -> 0.0003s

  * DEFERRED: MenuItem::MenuItem#caption should be tested. 

  * DEFERRED: MenuItem::MenuItem#html_options should be tested. 

sh: 2.3: command not found

rake aborted!
```

I'm wondering why it calls `2.3` and not ruby?!

**Comment by tbrisker** [comment]
I managed to reproduce locally by running `RUBY=2.5 bundle exec rake jenkins:unit TESTOPTS="-v" --trace` - looks like for some reason rake looks at the RUBY env var set by the pipeline e.g. at https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/test_foreman.groovy#L19 as the ruby binary it should use. I'll continue investigating, but looks like that env var should be renamed.

**Comment by tbrisker** [comment]
https://github.com/ruby/rake/blob/2a16d036ccafa51c407a648e081b686ded03e784/lib/rake/file_utils.rb#L10 is the culprit - rake takes the ruby to run from the RUBY env variable if it is present, then when the TestTask is [defined](https://github.com/ruby/rake/blob/master/lib/rake/testtask.rb#L117) it uses that ruby to run the test. We didn't hit this before because we didn't run other TestTask instances in jenkins.

**Comment by tbrisker** [comment]
and now with the PR - https://github.com/theforeman/foreman-infra/pull/966

**Comment by timogoebel** [comment]
@tbrisker: Thanks for your help. I figured it must have been something on Jenkins, but did not think of the ENV variable. Good job, well done!

**Pull request merged**
