### PR TITLE
Fixes #37168 - fix potential for duplicate html-id

### PR DESCRIPTION
**Pull request by m-bucher**
This issue is visible, if Katello is installed

### CODE REVIEW

**Comment by MariaAga** [comment]
The fix is good, but `setting_js_test` should also be fixed

**Comment by m-bucher** [comment]
@MariaAga, done. I am not sure about the other failed tasks; are they related?

**Review by MariaAga — APPROVED** [review]
The rest is unrelated, thanks!

**Comment by quba42** [comment]
Oh, it got merged.

Maybe that is why `gh pr checkout 10049` would not work. I was very confused.

Edit: Turns out it did not work, because I tried to check out the PR in the Katello repo... very confused indeed!

**Pull request merged**
