### PR TITLE
Bkearney/i18n usergroups and roles

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by skottler** [comment]
Looks good. Can you squash the commits?

**Comment by bkearney** [comment]
On 03/06/2013 03:17 PM, Sam Kottler wrote:

> Looks good. Can you squash the commits?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theforeman/foreman/pull/457#issuecomment-14523454.
> 
> I crossed two pull requests. I forced update so that only the correct 
> items are in each now.

-- bk

**Comment by skottler** [comment]
Okay, perfect. Thanks! @ohadlevy - looks good for merge when you're back.

**Comment by ohadlevy** [comment]
merged - thanks!

**Pull request closed without merging**
