### PR TITLE
fixes #9720:  changed ipam attribute from bool to String

### PR DESCRIPTION
**Pull request by sanakhanlibre**
Redmine Issue: http://projects.theforeman.org/issues/9720

### CODE REVIEW

**Comment by ares** [comment]
The subnet IPAM used to be bool and v1 is frozen, that's probably the reason, we fix the v1 controller that will translate this bool to new values - false is for `None`,  true is for `DHCP`, this was the behaviour before the IPAM change. Internal DB won't be supported in v1.

**Comment by ares** [comment]
I'll add comment to issue as well, @sanakhan-libre thanks for the patch, would you like to try to fix the v1 controller?

**Comment by sanakhanlibre** [comment]
@ares sure :) I'd be happy to. But I am about a week new to foreman, so I will need your help :)

**Comment by ares** [comment]
@sanakhan-libre ok, so basically you have to modify https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v1/subnets_controller.rb#L43 so it converts ipam parameter to value, something like

``` ruby
new_params = params[:subnet].deep_clone
new_params[:ipam] = new_params[:ipam] ? Subnet::IPAM_MODES[:dhcp] : Subnet::IPAM_MODES[:none]
@subnet = Subnet.new(new_params)
```

similarly for update action

**Comment by ares** [comment]
and I forgot to mention that functional test would be great, you can take a look at https://github.com/theforeman/foreman/blob/develop/test/functional/api/v1/domains_controller_test.rb

when I think about it more, we should probably also convert this when displaying the values, so we might need to update show and list views, but that should be it...

**Comment by domcleal** [comment]
Please also see my comments on -dev, we haven't bothered with compatibility layers for any other attributes, and it wasn't done for v2 which is also stable.

**Comment by dLobatog** [comment]
@sanakhan-libre Are you planning on taking this up?

**Comment by sanakhanlibre** [comment]
yes @eLobato. Should I add aditional tests? Followed instructions [from](http://theforeman.org/contribute.html), do these look fine:
http://pastebin.com/zA2PjsSw
http://pastebin.com/2qv19kHE
Also can you review [this](http://pastebin.com/8KFcpFCN).

**Comment by dLobatog** [comment]
@sanakhan-libre These look fine, but can you add the tests to the commit? Thanks!

**Comment by tbrisker** [comment]
@sanakhan-libre,
Thank you very much for your efforts! 
This PR has been open for a very long time with no activity. 
Please indicate if you plan to continue working on it or not; if not, feel free to close it. 
If you do not respond either way within a couple of weeks, I will assume this PR is abandoned and will go ahead and close it for you.

**Comment by tbrisker** [comment]
Dear @sanakhan-libre ,
It has been 20 days since my last comment with no replies. 
I am assuming this pull request has been abandoned and closing it.
If you wish to continue working on this in the future, feel free to reopen.
On behalf of the entire Foreman team, I wish to thank you for your efforts here and hope to see more contributions from you in the future.

**Pull request closed without merging**
