### PR TITLE
Fixes #20537: Monospace fonts in fullscreen editor

### PR DESCRIPTION
**Pull request by yaunj**
The fullscreen editor is used to edit parameters which can be in YAML.
Since YAML is an indentation sensitive format, monospaced fonts makes
for easier editing.

### CODE REVIEW

**Comment by dLobatog** [comment]
ok to test

**Review by dLobatog — APPROVED** [review]
Thanks @yaunj  - looks good, I'll test it if tests pass and merge.

**Comment by yaunj** [comment]
Thanks, it's a small, but useful change. I've been using a userstyle css to fix it for myself, but would be nice to have in upstream as well. :-)

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @yaunj !

**Comment by ares** [comment]
Setting release to 1.16 in redmine

**Pull request merged**
