### PR TITLE
Fixes #29496 - Fix pagination for client-side paging

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
travis fails but I've seen that elsewhere too, foreman integration test timeouted as well as katello [test foreman][test katello][test upgrade]

since this blocks the foreman_leapp PR, could some reviewer familiar with this part please take a look? cc @ezr-ondrej @adamruzicka @tbrisker @amirfefer @sharvit 
thank you!

**Comment by adamruzicka** [comment]
FWIW I tested it with the [leapp PR](https://github.com/oamg/foreman_leapp/pull/56) and it works nicely

**Review by ezr-ondrej — DISMISSED** [review]
Nice and simple! :heart:
Thanks @xprazak2 :+1:

**Comment by ezr-ondrej** [comment]
@xprazak2 [test foreman][test katello] seems unrelated, but lint :policeman: complains. Can you fix the linting errors?

**Review by ezr-ondrej — APPROVED** [review]
Thanks @xprazak2 ! :+1:

**Pull request merged**
