### PR TITLE
fixes #6116 - search hosts by parent host group and its decendants

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by lzap** [comment]
I am able to confirm it works. The only drawback is that for some reason the search box does not offer you possible values (hostgroup does). Is this expected behavior?

**Comment by lzap** [comment]
I guess so: `:only_explicit => true,`

:+1:

**Comment by isratrade** [comment]
@lzap, try it now. Actually, the reason is `:complete_value => true`.  It was `false`.  `only_explicit => true` is for limiting it to _not_ run when just only free text is entered.

**Comment by lzap** [comment]
Works for me. :+

**Comment by lzap** [comment]
:+1:

**Comment by domcleal** [comment]
Merged as 7cf9909 for Foreman 1.6, thanks @isratrade.

**Pull request closed without merging**
