### PR TITLE
Fixes #31073 - test Taxonomix with Domain

### PR DESCRIPTION
**Pull request by ezr-ondrej**
As we plan to extract Environment, we need to use Domain in tests.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by lzap** [comment]
[test katello]

**Review by lzap — APPROVED** [review]
I am assuming no other changes than refactoring of names. RTM

**Comment by ezr-ondrej** [comment]
[test katello]
Yup just changing the test model from Environment to Domain :)

**Review by tbrisker — APPROVED** [review]
Thanks @ezr-ondrej !

**Pull request merged**
