### PR TITLE
Fixes  #24735 - parameters missing from GET hostgroup api

### PR DESCRIPTION
**Pull request by kgaikwad**
Reference [PR-4718](https://github.com/theforeman/foreman/pull/4718)  which added `include parameters` change.

### CODE REVIEW

**Comment by xprazak2** [comment]
Test failures unrelated, the parameters show for me now in the response:



@kgaikwad, could you change the commit message to 'Fixes #24735 ...' please? We use 'Refs' when we do not have a separate ticket for the issue.

**Comment by kgaikwad** [comment]
@xprazak2,

Thank you. Updated the commit message to 'Fixes #24735 ...'.

**Comment by xprazak2** [comment]
Nice, could you add a simple test as well so that we can catch possible regressions?

**Comment by kgaikwad** [comment]
@xprazak2, 

We already have one test case in file [test/controllers/api/v2/hostgroups_controller_test.rb](https://github.com/theforeman/foreman/blob/develop/test/controllers/api/v2/hostgroups_controller_test.rb#L38). 
When I try to run it against `develop` branch, it is failing on my development setup and same test with this branch, it passes successfully. 
I guess, this is what you would like to have in a test similar to above. Please correct me if any other scenario that needs to be handle in a different test case.
or I think I will need to add test case in Katello?

**Review by xprazak2 — APPROVED** [review]
Ah, so we have tests already, I did not notice. I think this is good to go now.

**Comment by mmoll** [comment]
merged, thanks @kgaikwad!

**Pull request merged**
