### PR TITLE
Fixes #14572 - fix updating storage in compute profiles based on template

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ares** [comment]
https://github.com/iNecas/foreman/blob/fix-profiles/app/assets/javascripts/compute_resource.js#L76 I think this needs fixing as well

**Comment by iNecas** [comment]
Right, I was just telling to myself: "don't forget to search for other references to that id!" Of course I did. Luckily we have @ares watching us :)

**Comment by iNecas** [comment]
Fixed

**Comment by ares** [comment]
without #3412 the JS fails, it would be nice to rescue from this issue and add storage volumes... even with the patch it could happen with libvirt

**Comment by iNecas** [comment]
Thanks for the review, I've added additional check to see if the networks element is available

**Comment by ares** [comment]
Works nicely, ACK pending Jenkins

**Comment by dLobatog** [comment]
@ares Jenkins says :+1:

**Comment by ares** [comment]
so do I :-) merged as deda3a7795fd65610590c3d3b6e58f957ceda6db, thanks @iNecas

**Pull request closed without merging**
