### PR TITLE
fixes #15720 - rename *_filter to *_action

### PR DESCRIPTION
**Pull request by domcleal**
The older 'filter' name is changing in Rails to 'action' and is being
deprecated.

### CODE REVIEW

**Comment by tbrisker** [comment]
LGTM, let's wait for jenkins to give it the :green_heart:

**Comment by tbrisker** [comment]
Actually, a deeper search led to a few references in comments to `before_filter`, for consistency we should change those as well:

```
2.0.0@foreman_gemset ~/foreman (domcleal-15720-filter-action) $ git grep -n before_filter
app/controllers/concerns/foreman/controller/taxonomy_multiple.rb:6:    #before_filter :find_multiple, :only => [:select_multiple_organization, :update_multiple_organization,
app/controllers/templates_controller.rb:82:    # Not using before_filter :find_resource method because we have enabled preview to work for unsaved templates hence no resource could be found in those cases
app/controllers/unattended_controller.rb:159:  # Cleans Certificate and enable autosign. This is run as a before_filter for provisioning templates.
app/controllers/unattended_controller.rb:167:    # This should terminate the before_filter and the action. We return a HTTP
app/controllers/unattended_controller.rb:174:  # Reset realm OTP. This is run as a before_filter for provisioning templates.
app/controllers/unattended_controller.rb:179:    # This should terminate the before_filter and the action. We return a HTTP

```

**Comment by domcleal** [comment]
Thanks, PR updated to rename the commented instances of `before_filter`.

**Comment by tbrisker** [comment]
Merged as df6a9f3457fb1b4d388f22e3412f2e9c5b358467, thanks @domcleal!

**Pull request closed without merging**
