### PR TITLE
Fixes #20321 - run puppet tasks under admin

### PR DESCRIPTION
**Pull request by ares**
the patch looks scary to review but it only wraps tasks in block like
```
User.as_anonymous_admin do
end
```

### CODE REVIEW

**Comment by mmoll** [comment]
adding `?w=1` to the URL makes it easier to review on the GH Web UI 🔍

**Review by dLobatog — APPROVED** [review]
@ares Thanks, setting this for 1.15.3

**Comment by ares** [comment]
Rebased to pin down ruby2ruby

**Comment by ares** [comment]
all green, code climate got stuck but is green too - https://codeclimate.com/github/theforeman/foreman/pull/4681

**Review by dLobatog — APPROVED** [review]
Merging, thanks @ares !

**Pull request merged**
