### PR TITLE
Let setting admin attribute on user creation

### PR DESCRIPTION
**Pull request by iNecas**
Otherwise rails scream about mass-assignment protection.

### CODE REVIEW

**Comment by domcleal** [comment]
@isratrade, would you mind reviewing and writing a test for this please?  Seems like something we should have caught.

**Comment by isratrade** [comment]
@domcleal, sure

**Comment by isratrade** [comment]
@iNecas, @domcleal, my suggestion is to use what's in users_controllers rather than removing :admin key from the hash

``` ruby
    @user = User.new(params[:user]){|u| u.admin = params[:user][:admin] }
```

**Comment by iNecas** [comment]
@isratrade the suggested doesn't work for me, since rails still throws an exception for me. There might be some behavioral change in Rails versions, but I prefer a solution that works on more versions anyway.

**Comment by lzap** [comment]
I can confirm @iNecas patch works for me too.

**Comment by lzap** [comment]
@iNecas I think @isratrade mean this:

```
admin = params[:user].delete :admin
@user = User.new(params[:user]){|u| u.admin = admin }
```

which is working for me too.

**Comment by iNecas** [comment]
@isratrade ping

**Comment by domcleal** [comment]
Closing in favour of @lzap's GH-591 PR.  Thanks @iNecas!

**Comment by iNecas** [comment]
#591 doesn't seem to touch API controller, which was addressed by this patch

**Comment by ares** [comment]
which makes this issue a blocker for https://bugzilla.redhat.com/show_bug.cgi?id=965790

**Comment by ares** [comment]
@isratrade comment implemented in https://github.com/iNecas/foreman/pull/1 when Ivan merges it will buble up here.

**Comment by domcleal** [comment]
Thanks for the patch @iNecas and @ares.  Merged as 7fab6ba in develop.

**Pull request closed without merging**
