### PR TITLE
fixes #22271 - rake console works with rails 5.1

### PR DESCRIPTION
**Pull request by timogoebel**
cc: @tbrisker, as discussed on irc

### CODE REVIEW

**Review by mmoll — APPROVED** [review]
test failures unrelated, fixes the issue for me

**Review by ares — APPROVED** [review]
interesting, I always used `bundle exec rails console` which worked fine... but `bundle exec rake console` failed and I can confirm, this fixes it

**Comment by ares** [comment]
Thanks @timogoebel, merging!

**Comment by ares** [comment]
cherry-picked to 1.17-stable as 7e5b518d7e996efa9faae781ca37e1b38f5fad9d

**Pull request merged**
