### PR TITLE
Fixes #11466, #11462 - Improve layout of textareas

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
Some Before & After screenshots:
**Before**
_Host parameters_
host

_Hostgroup parameters_
image

_Puppetclass parameters_
image

_Template_
image

**After**
_Host parameters_
image

_Hostgroup parameters_
image

_Puppetclass parameters_
image

_Template_
image

**Comment by dLobatog** [comment]
@tbrisker Thanks for the screenshots, very useful. On Chromium, it looks good. Unfortunately it seems that on Firefox it looks considerably worse, not sure why. I experimented a while ago with this and [using input-group-addon helped](https://github.com/eLobato/foreman/commit/8abc5bbe25375e5450cd549c918a9f8f1f6b6c43). 

Can you try to fix that?

screenshot from 2015-08-27 21-31-30

**Comment by tbrisker** [comment]
Thanks for the input and suggestions @eLobato. 
I have also incorporated the changes from #2634 into this as they were required for the host[group] parameters to display correctly, so I believe this PR should replace that one.

Here are a few screenshots of the updated changes:
**Chrome**
_Host parameters_
screenshot from 2015-09-02 11-26-39
_Host group parameters_
screenshot from 2015-09-02 11-25-50
_Puppet class variables_
screenshot from 2015-09-02 11-31-58

**Firefox**
_Host parameters_
screenshot from 2015-09-02 11-33-37
_Host group parameters_
screenshot from 2015-09-02 11-34-16
_Puppet class variables_
screenshot from 2015-09-02 11-34-41

There are still some issues with the table alignments on the host/hostgroup parameters. 
This is unrelated to this issue and will be handled separately under issue #11460.

**Comment by dLobatog** [comment]
Awesome, to be continued on [11466](http://projects.theforeman.org/issues/11466) then. Thanks!

**Comment by dLobatog** [comment]
Merged as 77b975de37245f85425b91c3e4f1622ce2bfcb6f, thanks @tbrisker!

**Pull request closed without merging**
