### PR TITLE
Fixes #12204 - Show interface form helptext in popovers

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
:+1:

**Comment by dLobatog** [comment]
Thanks @tbrisker , looks way cleaner. Before we merge, I wanted your opinion on a couple of things.

Now that the form contains popovers without text for most info, the Identifier field doesn't fit as well as before. How about changing the label to 'Device identifier', and making the popover just an icon like you did with the others? 

The DNS name also contains some help in-line that could be put into a popover so that it looks more unified with the rest of the form. Does that sound good? 

I'm not completely sure about IP address, although I'd put the `suggest new` as an icon within the form if I had the time. That'd be a different PR though.

Let me know how all of these sound to you.

**Comment by tbrisker** [comment]
@dLobatog I move the additional help text to popovers as well. I agree the `suggest new` link should be changed into a button or an icon (perhaps a `glyphicon-refresh`).

**Comment by dLobatog** [comment]
@tbrisker Thanks. It looks great. However now we have lot of space on the right side that it's unneeded. I tried adding `:size => 'col-md-9' to the text_f and I think it looks better, not sure. Maybe there's a better relation of sizes or something. I also had to override the model-dialog min width of 1000px.

screenshot from 2015-10-26 12-37-32
screenshot from 2015-10-26 12-37-22

Do you think you can wrap it better? If not, I guess the 2nd option is acceptable?

**Comment by tbrisker** [comment]
@dLobatog I can make the modal smaller without breaking the labels by enlarging the label. However, if the host has a compute profile with network settings, the layout gets broken:
screenshot from 2015-10-26 15-23-44

Since that part of the form is shared with the compute profile form, changing it would require also changing the entire compute profile form as well. While that would be a good change to do anyways, would you say it is a good idea to add it to this PR or split the entire resizing forms into a separate one?

**Comment by dLobatog** [comment]
@tbrisker Either add it to this PR - or open a new PR that depends on this, and I'll try to merge them both at the same time. 

The only issue I have with merging it as it is now is that someone might notice it looks odd, and without knowing you're working on a fix for resizing the form, there's a chance someone else will try to fix it too.

**Comment by tbrisker** [comment]
@dLobatog I added the changes in a separate commit so it would be easier to remove if we decide to leave it as is in the end. TBH I don't like these changes very much, setting sizes on dozens of fields and labels just to get the one modal to look a bit better.

**Comment by dLobatog** [comment]
I'll merge for the moment, nothing wrong with the specified length on the labels. @tbrisker Popovers overwhelmingly lack a title now, so if you could, a PR refactoring it, removing the `popover(""` part by setting it as a default or as part of the options would be great.

Merged as 1f71c494930deda987209ad6e6534785077c4ec1, thanks @tbrisker !

**Pull request closed without merging**
