### PR TITLE
Fixes #22908 - add placeholder to datatable search inputs

### PR DESCRIPTION
**Pull request by amirfefer**
before:
before_placeholder

after:
after_placeholder

### CODE REVIEW

**Review by ohadlevy — APPROVED** [review]
no objections for this, besides the fact that I want to get rid of data tables :)

**Comment by ares** [comment]
> no objections for this, besides the fact that I want to get rid of data tables :)

:+1: until that happens :-)

**Comment by ares** [comment]
Travis tests failures seem to be related, @amirfefer please take a look

```
Summary of all failing tests
 FAIL  webpack/assets/javascripts/foreman_tools.test.js
  ● activateDatatables › calls $.fn.DataTable when it finds a data-table=server
    expect(jest.fn()).toBeCalledWith(expected)
    
    Expected mock function to have been called with:
      [{"ajax": "http://example.foo", "dom": "<'row'<'col-md-6'f>r>t<'row'<'col-md-6'><'col-md-6'p>>", "ordering": false, "processing": true, "serverSide": true}]
    But it was called with:
      [{"ajax": "http://example.foo", "dom": "<'row'<'col-md-6'f>r>t<'row'<'col-md-6'><'col-md-6'p>>", "language": {"searchPlaceholder": "Filter..."}, "ordering": false, "processing": true, "serverSide": true}], [{"dom": "<'row'<'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>", "language": {"searchPlaceholder": "Filter..."}}]

```

**Comment by amirfefer** [comment]
thanks @ares ,
fixed :)

**Review by ohadlevy — APPROVED** [review]

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
test failure not related, thanks @amirfefer

**Pull request merged**
