### PR TITLE
Fixes #22927 - method in audit_associations to get class

### PR DESCRIPTION
**Pull request by kgaikwad**
With this commit, we can override association_class method in other plugins like Katello.

### CODE REVIEW

**Comment by kgaikwad** [comment]
@ares, I have added this change so that I can override this `find_association_class(name)` in other plugins.

**Review by timogoebel — APPROVED** [review]
LGTM.

**Comment by mmoll** [comment]
@kgaikwad please rebase :)

**Review by tbrisker — APPROVED** [review]
LGTM, will merge when tests pass.

**Comment by mmoll** [comment]
test failure unrelated

**Comment by mmoll** [comment]
merged, thanks @kgaikwad!

**Pull request merged**
