### PR TITLE
Fixes #34596 - sanitize default template names

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Default boot templates are weirdly interconnected with its settings.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by ezr-ondrej** [comment]
[test foreman]
[test upgrade]

**Comment by ezr-ondrej** [comment]
[test foreman]

**Comment by ezr-ondrej** [comment]
[test foreman] wth jenkins? :(

**Comment by ezr-ondrej** [comment]
[test katello]

**Review by lzap — APPROVED** [review]
Sure, why not. Thanks.

**Comment by lzap** [comment]
Katello tests CI issue. Merging.

**Pull request merged**
