### PR TITLE
fixes #3137 - API v2 continue - apply to all actions, not just :index, :show to show error if optional nested object does not exist

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
The original idea was just to have :index and :show actions on nested routes. This PR is now that we decided to apply it to all routes

**Comment by domcleal** [comment]
This makes sense to me, but it looks like routes need updating too as I'm getting 404s when doing PUT to /api/organizations/:id/domains/:id.  Also seeing the fix isn't working for stuff like GET /api/organizations/unknown_id/domains/ as it's showing _all_ domains.

**Comment by domcleal** [comment]
(Adding some tests would help)

**Comment by isratrade** [comment]
correct, there are a bunch of nested routes not defined.  These will be defined in a separate PR for http://projects.theforeman.org/issues/3492

This small fix is just with the current controllers that have `find_optional_nested_object`

I will also add tests in the PR for issue #3492

**Comment by isratrade** [comment]
closing, incorporated in PR #3492

**Pull request closed without merging**
