### PR TITLE
Cherry-picks for RC2

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test katello]

**Comment by tbrisker** [comment]
[test katello]

**Comment by mmoll** [comment]
katello test failures are known with 1.18, I think it's not related, but might be wrong

**Comment by xprazak2** [comment]
Seems like a rebase helped, the failing foreman tests are for BookmarksController

**Comment by ares** [comment]
see https://github.com/theforeman/foreman/pull/5689 for bookmarks tests stabilizations (should also go to 1.18 to avoid these failures)

**Comment by tbrisker** [comment]
Thanks @xprazak2 @mmoll @ares @ohadlevy @witlessbird !

**Pull request merged**
