### PR TITLE
fixes #3364 Add option to disable automatc host creation

### PR DESCRIPTION
**Pull request by mmatuska**
Add option to disable automatc host creation when a report is received

### CODE REVIEW

**Comment by domcleal** [comment]
I think this'll cause an error in the controller, which doesn't handle nil reports today:

https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v2/reports_controller.rb#L20

Tests in test/unit/report_test.rb would be great if you could please - you could look at host_test.rb for inspiration, which has one for the fact version.  Don't forget to add the setting to test/fixtures/settings.yml.

[test]

**Comment by domcleal** [comment]
This is causing test failures at the moment as the new setting is missing from the fixtures (test/fixtures/settings.yml), could you add it there?

A test would be really valuable too :)

**Comment by mmatuska** [comment]
Would a unit test like this do the trick in host_test.rb?

``` ruby
  test "host is not created when receiving a report if setting is false" do
    Setting[:create_new_host_when_report_is_uploaded] = false
    assert_equal false, Setting[:create_new_host_when_report_is_uploaded]
    Report.import read_json_fixture("/../fixtures/report-no-logs.json")
    host = Host.find_by_name('builder.fm.example.net')
    Setting[:create_new_host_when_report_is_uploaded] =                                                                                                                                    
        Setting.find_by_name("create_new_host_when_facts_are_uploaded").default
    assert_nil host
  end
```

**Comment by domcleal** [comment]
[test]

**Comment by ohadlevy** [comment]
@mmatuska can you double check why the tests are failing? thanks

**Comment by ohadlevy** [comment]
[test]

**Comment by ohadlevy** [comment]
thanks! squashed and  merged as 4ab0b55

**Pull request closed without merging**
