### PR TITLE
Fixes #2875: only show URL and description for a CR if they exist

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by lzap** [comment]
+1 LGTM

I wonder - can we actually display _more_ information? For some resources, it is useful to see more flags, users need to go for Edit screen.

**Comment by domcleal** [comment]
I don't agree with hiding the description as that's user data, but agree with the URL.

The better way of doing this would be via provider-specific views, which @GregSutcliffe has implemented here: https://github.com/theforeman/foreman/pull/753/files#diff-3

It's not been merged yet, so I'll try to do that soon and you can rebase on top of it.

**Comment by domcleal** [comment]
(you can then add fields that are specific to whatever CR provider you've got in mind that doesn't use a URL)

**Comment by skottler** [comment]
@domcleal it's only hidden if the user doesn't enter it. Otherwise (right now) if there's no description for the CR it just has a blank value which is rather ugly.

I like Greg's approach, though.

**Comment by domcleal** [comment]
@skottler ok, that's fine then.  Now I've merged Greg's CR-specific stuff, could you rebase please?  I think you can now move URL into the templates only where it's applicable and perhaps add additional fields for whichever CR it is that was missing the URL.

**Comment by ohadlevy** [comment]
@skottler ping

**Comment by domcleal** [comment]
@skottler ping, this on the 1.3 target list but will be bumped to 1.4 if not updated.

**Comment by skottler** [comment]
I'll update this tomorrow. Sorry about the hold up.

**Comment by skottler** [comment]
I've rebased the PR off the latest version of develop.

**Comment by domcleal** [comment]
What did you think about using the provider-specific pages?  Anything you wanted to add? :)

**Comment by skottler** [comment]
Updated to use the new views @domcleal.

**Comment by domcleal** [comment]
Great, thanks for the update @skottler!  Merged as 5cd5a55 for Foreman 1.3.0.

**Comment by lzap** [comment]
Why are we including this for 1.3? I mean, this is nice improvement indeed. But to me it looks like 1.4 feature.

**Comment by domcleal** [comment]
@lzap the redmine issue was marked for 1.3.0 still.  Up to you if you want to leave it out, but please update the ticket to reflect the version.

**Pull request closed without merging**
