### PR TITLE
Fixes #18538 - add sass support to webpack

### PR DESCRIPTION
**Pull request by matanwerbner**
This can really improve css maintainablity

### CODE REVIEW

**Comment by tbrisker** [comment]
@matanwerbner - looks like you got a typo in the issue number? Also one of the tests seems to have broken. other than that :+1:

**Comment by dLobatog** [comment]
@matanwerbner Thanks - I agree with @tbrisker, make sure tests pass and please check out packaging for these 2 new packages.
https://github.com/theforeman/foreman/pull/4291#issuecomment-280316317

**Comment by gailsteiger** [comment]
Excellent. OK to merge.

 +1 for the source maps.

@tbrisker  Can we remove the 'sass-rails' gem and rely on webpack exclusively?

**Comment by tbrisker** [comment]
@gailsteiger tests are failing, so this isn't ok to merge yet. As for `sass-rails`, afaiu it is needed so the legacy assets can be written in sass, so we won't be able to remove it until all stylesheet assets are moved to webpack (which i'm not sure is feasible anyways).

**Comment by ohadlevy** [comment]
@matanwerbner for future PR's, there is no need to close the PR, simply force push another branch into it.

**Pull request closed without merging**
