### PR TITLE
Fixes #11434 - vdsmdummy interfaces are ignored

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
Merged as 676ef853a4be161f602a6b531590b1ac4be9c093, thanks @ares!

**Comment by ares** [comment]
not sure why but PR processor didn't pick it, I'll assign it manually

**Comment by domcleal** [comment]
It looks like it might have clashed with a simultaneous edit on the ticket from you.  By the way, tests hadn't run on this PR yet - best to wait for them.

**Comment by ares** [comment]
oh yeah, update of the ticket took a bit longer, I though it was some redmine hiccup, thanks for checking

**Pull request closed without merging**
