### PR TITLE
Fixes #25961 - report expiration record disappearing

### PR DESCRIPTION
**Pull request by lzap**
During the refactoring to use batch processing I changed
messages/sources deletion from distinct approach to direct approach.
I've missed that this actually deletes records, even those still
associated to different reports.

I am putting the distinct queries back, but putting them outside of the
batch loop because they can be executed just once after deletion is
done.

### CODE REVIEW

**Comment by lzap** [comment]
How about now?

**Comment by iNecas** [comment]
@lzap mind adding 'reproducer steps' so that people that's reporting is not their daily bread can still help reviewing?

**Review by tbrisker — APPROVED** [review]
Thanks @lzap !

**Comment by tbrisker** [comment]
1.21- 5cedb388c
1.20- df2bbad16

**Comment by lzap** [comment]
Sorry @iNecas it's `foreman-rake reports:expire` to reproduce.

**Pull request merged**
