### PR TITLE
Fixes #26799 - typo in redux consts

### PR DESCRIPTION
**Pull request by MariaAga**
was:PASSWORD_STRENGTH_PASSWROD_MATCHED
should be:PASSWORD_STRENGTH_PASSWORD_MATCHED

### CODE REVIEW

**Review by mmoll — DISMISSED** [review]

**Comment by mmoll** [comment]
@MariaAga please rebase, that should fix the snapshot mismatches

**Review by Ron-Lavi — DISMISSED** [review]

**Comment by xprazak2** [comment]
Not likely caused by this change, but snapshot tests are still failing.

**Comment by MariaAga** [comment]
I can't find why the snapshots are failing in travis but work locally

**Comment by mmoll** [comment]
@MariaAga update your local pattenfly-react and you'll see it :bomb: :boom:

Test failure unrelated. :green_heart:

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, thanks @MariaAga!

**Pull request merged**
