### PR TITLE
Fixes #21500 - dismiss notifications

### PR DESCRIPTION
**Pull request by sharvit**
The notification drawer should get close
when clicking outside of the box

### CODE REVIEW

**Comment by ohadlevy** [comment]
@rohoover - is that a desired behavior ?

**Comment by iNecas** [comment]
Personally I would expect this behavior, it felt like a bug to ne from the beginning

**Comment by Rohoover** [comment]
It's supposed to remain open. The idea behind this was so that when an event occurred you could compare what the drawer was telling you to what content was on your screen. I'm not personally opposed to having it close, and potentially leaving it open later when the functionality becomes more robust.

**Comment by ohadlevy** [comment]
thanks @sharvit!

**Pull request merged**
