### PR TITLE
Sync from community-templates

### PR DESCRIPTION
**Pull request by stbenjam**
This is so we can remove the SSH snippet from foreman_remote_execution now

### CODE REVIEW

**Comment by stbenjam** [comment]
Do you want a redmine for this? I think usually this is not done via a PR, but it's making @theforeman-bot unhappy without one.

**Comment by domcleal** [comment]
Nah, it's fine.

**Comment by domcleal** [comment]
It looks like the snippets haven't been renamed correctly with underscore prefixes, can you check them?  They shouldn't all be new files.

Any new templates must also be added to the seeds list (the script ought to warn about this).

**Comment by stbenjam** [comment]
Ah I didn't have prename installed - where's that come from? yum whatprovides doesn't show anything with it.

I fixed it by hand easily enough though.

``` bash
for i in `ls | grep -v ^_`; do mv $i _$i; done
```

**Comment by stbenjam** [comment]
https://github.com/theforeman/community-templates/pull/235 was merged, and synced here.

From our perspective I think this should have everything we need so we can remove the snippet from foreman_remote_execution.

**Comment by stbenjam** [comment]
Ok, seems like transient failures now [test]

**Comment by domcleal** [comment]
Merged as 572cd37, thanks @stbenjam.

**Comment by stbenjam** [comment]
Thanks!

**Pull request closed without merging**
