### PR TITLE
Fixes #33416 - Simplify ForemanSwitcher

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
katello tests unrelated

**Comment by xprazak2** [comment]
Works as expected. @tbrisker, is dropping `beforeRenderingCallback` the main reason behind this or is there something else? The redmine issue does not give too many details...

**Review by ezr-ondrej — APPROVED** [review]
Nice simplification! :)

**Comment by tbrisker** [comment]
@xprazak2 IIRC, I found myself needing to dig through these components while working on https://github.com/theforeman/foreman/pull/8724, and realized they could be made simpler.

**Pull request merged**
