### PR TITLE
webpack asset compilation for 1.18

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@ehelms @ekohl Please confirm that these did fix asset precompilation with plugins using the new style JS assets.

**Review by ehelms — APPROVED** [review]

**Review by ekohl — APPROVED** [review]
Yes, this is what we need for webpack compilation.

**Comment by ohadlevy** [comment]
@mmoll rebase is required?

**Comment by mmoll** [comment]
@ohadlevy I dont' think so. Why? :)

**Review by dLobatog — APPROVED** [review]
I confirm `webpack` runs when building an RPM using a tarball created from this branch, using `assets:precompile[foreman_remote_execution]`. Thanks @mmoll!

**Pull request merged**
