### PR TITLE
fixes #9059 adds puppetssldir setting

### PR DESCRIPTION
**Pull request by grimblenz**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Could you also add an example line for the new setting to config/settings.yaml.example?

**Comment by GregSutcliffe** [comment]
[test]

**Comment by dLobatog** [comment]
I have rebased your 6 commits into one and merged it as b57a1e3396d041d55d9b9b80f6d23cd3eb97dab8

Thanks @grimblenz!

**Comment by dLobatog** [comment]
@grimblenz you might want to update your git config to link to your stocky at gorgon email account, so that the commit links to your user name on :octocat: 

thanks again!

**Pull request closed without merging**
