### PR TITLE
Fixes #8417 - Correctly focus on errors in puppet form

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tbrisker can you rebase please?

**Comment by tbrisker** [comment]
@ohadlevy rebased.

**Comment by ohadlevy** [comment]
I've created multiple errors (primary value + matcher values) and initially only the primary / default value is highlighted, and after another submit, the matcher values are highlighted.

**Comment by tbrisker** [comment]
@ohadlevy I think that is an unrelated issue with lookup keys/values not being validated all at the same time but rather stopping validation once an error is discovered.
This issue is about a UI inconsistency in which the validation errors did not cause the focus to be automatically taken to the first error detected

**Comment by ohadlevy** [comment]
merged as d755be5 thanks @tbrisker

**Pull request closed without merging**
