### PR TITLE
Fixes #13387 - Update the zanata configuration file

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by domcleal** [comment]
This hasn't been agreed yet, nor is it the active translation site - setting WoC.

**Comment by lzap** [comment]
Is there a thread about this? I've only seen short discussion so far. We need an approval from our top translators at least. In general, I am open to this move as Zanata is more open than Transifex, but we need to listen to our translators. Maybe it offers something they need.

**Comment by lzap** [comment]
Any comments? The idea behind moving from proprietrary to free service is good!

**Comment by bkearney** [comment]
@lzap we discussed at FOSDEM and it was not a good time to move given the amount of administration which would be required. I have the mapping files, so I can move us later if need be.

**Comment by lzap** [comment]
> @lzap we discussed at FOSDEM and it was not a good time to move given the amount of administration which would be required. I have the mapping files, so I can move us later if need be.

Sounds like a plan, thanks!

## 

Later,
 Lukas #lzap Zapletal

**Pull request closed without merging**
