### PR TITLE
Fixes #4976 - ensure the process is really running inside a rake task

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
:+1:

We have a few references to $0 and ARGV too, perhaps we should update those too?
- app/models/user.rb:8
- app/models/config_template.rb:5
- config/initializers/fix_cache.rb:8

**Comment by iNecas** [comment]
Good point, will address them as well

**Comment by iNecas** [comment]
Updated + fixed tests

**Comment by domcleal** [comment]
Merged as e4fde4e for Foreman 1.5.0, thanks @iNecas!

**Pull request closed without merging**
