### PR TITLE
Fixes #33197 - Show error message if credentials are wrong

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Will show error message if username and / or password are wrong:

image

Similar behavior as if the fingerprint is wrong.

**Comment by sbernhard** [comment]
Looks like the katello issue is not related to this change.

**Comment by sbernhard** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Test failures don't seem related, thanks @sbernhard !

**Pull request merged**
