### PR TITLE
Fixes #6361 - all hosts permission removed from anonymous role

### PR DESCRIPTION
**Pull request by dLobatog**
http://projects.theforeman.org/issues/6361

### CODE REVIEW

**Comment by isratrade** [comment]
Ack

**Comment by domcleal** [comment]
Maybe remove this from test fixtures too, if that's possible?  (anonymous_1_0 in test/fixtures/filterings.yml)

**Comment by dLobatog** [comment]
@domcleal good catch, it's removed now.

**Comment by dLobatog** [comment]
Tests seemed to fail on `show returns YAML output for rundeck` 1.8.7, I think it's unrelated with this PR.

**Comment by dLobatog** [comment]
[test]

**Comment by dLobatog** [comment]
#1371 has been merged, https://github.com/theforeman/foreman/commit/a0bd5bb282c27f72a5e3746a1582b73366c15d21 contains code that fixes this issue, so I'm closing.

**Pull request closed without merging**
