### PR TITLE
Fixes #23462 - bump patternfly-react to ^2.1.0

### PR DESCRIPTION
**Pull request by tstrachota**
patternfly-react 2.1.0 introduced inline editing for tables (see https://github.com/patternfly/patternfly-react/releases).

### CODE REVIEW

**Comment by tstrachota** [comment]
(pending a PR into foreman-packaging)

**Comment by ohadlevy** [comment]
[test foreman]

**Comment by ohadlevy** [comment]
@ekohl ack?

**Comment by ekohl** [comment]
I'd appreciate if https://github.com/theforeman/foreman-packaging/pull/2447 could be merged first but other than that ACK

**Comment by ohadlevy** [comment]
ack, pending https://github.com/theforeman/foreman-packaging/pull/2447, this also required for https://github.com/theforeman/foreman/pull/5461

**Review by ekohl — APPROVED** [review]
Packaging ACK

**Comment by mmoll** [comment]
merged, díky @tstrachota!

**Pull request merged**
