### PR TITLE
fixes #18481 - host index page loads faster

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by dLobatog** [comment]
Thanks @timogoebel

**Comment by lzap** [comment]
Nice.

**Comment by ohadlevy** [comment]
:+1: indeed, but in all honestly, i would prefer we fix the root cause instead of the "short term" solution.

**Comment by timogoebel** [comment]
> i would prefer we fix the root cause instead of the "short term" solution.

I fully agree. The index might prove valuable in any case.

**Pull request merged**
