### PR TITLE
Fixes #31754  Forceful Reregistration using Curl command

### PR DESCRIPTION
**Pull request by JaskaranNarula**
https://projects.theforeman.org/issues/31754

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@stejskalleos could you please take a look?

**Comment by stejskalleos** [comment]
Hi @JaskaranNarula 
thanks for contributing to the Foreman code!

Unfortunately I already work on the same feature, where we allow user to set `--force` parameter in UI form (Hosts > Register Host).
We cannot have `--force` as default option, as it could cause some problems - for example accidentally registering host that is already registered and changing its configuration.

In next days I'll update [Redmine](https://projects.theforeman.org/issues/30440) issue with all tasks planned for upcoming releases, didn't have time yet to do it so the list is not up to date.

Please feel free to contact me on IRC, I can point you to tasks that could be done.

**Comment by ezr-ondrej** [comment]
@JaskaranNarula does this work for you? If the solution would be ok for you, please feel free to close this PR, otherwise please share your thoughts :)

**Comment by JaskaranNarula** [comment]
Sure @ezr-ondrej it makes sense. 
I am closing this PR.

**Pull request closed without merging**
