### PR TITLE
Refs #32685 - Use actual model

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by ekohl** [comment]
Is there a test that could have caught this?

**Comment by ofedoren** [comment]
> Is there a test that could have caught this?

Well, I guess it breaks only for plugins because of nested/modulized model names...

**Comment by adamruzicka** [comment]
Can't say that I understand the fix, but it fixed the tests in tasks. Here's a run of tasks' tests using this branch https://github.com/theforeman/foreman-tasks/actions/runs/3183196835/jobs/5190133815 .

**Comment by evgeni** [comment]
> Well, I guess it breaks only for plugins because of nested/modulized model names...

Can we easily write a test that would do the same? (If not, that's OK, but I often think we should try harder to make plugin life easier)

**Comment by ofedoren** [comment]
> > Well, I guess it breaks only for plugins because of nested/modulized model names...
> 
> Can we easily write a test that would do the same? (If not, that's OK, but I often think we should try harder to make plugin life easier)

**Easily** -- no, doable -- yes? :/

**Review by kamils-iRonin — APPROVED** [review]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
