### PR TITLE
feature #1906 add Trend information

### PR DESCRIPTION
**Pull request by rbirnie**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@abenari can you please review? thanks!

**Comment by abenari** [comment]
Hi @rbirnie,
Patch looks great. 
I have a few questions:
1. Why do we need trends for Environment, Operating Systems and Model instead of just facts. (I can understand there is no single good fact that represent the os, but what about the env. and model)
2. The check for missing button seems to belong to the migration code not the ui (we need the code to run only once right? )
3. Trend Index page could be very long, maybe we can arrange it differently with accordion or any other way of collapsing the tables.

**Comment by rbirnie** [comment]
1. I added Env and Model so that when editing the fact it'll go into the correct model rather than just editing the name to be prettier (which is all you can do for regular facts).
2. We only need it to run once.
3. I'd really like doing accordion, do we have that built-in anywhere else that I could mirror or should I go look for some jQuery? I also thought about breaking it into two columns but figured it'd break the regularity of the site (everything else is a single column).

**Comment by abenari** [comment]
Here is my first version of accordion: https://github.com/abenari/foreman/commits/1906
1. I didn't understand the logic of editing environment and model from the trends page, way is it needed?
2. Are model and environments trends exceptionally useful? should we make them default?

**Comment by rbirnie** [comment]
1. I didn't want the user to edit a name on the Trends page and have it not propagate to the Environtment/Model or vice versa. This is mostly for model as sometimes these can come out cryptic from vendor and would need some updating. 
2. I don't know if they are exceptionally useful. When I set out creating the page they were on the list of what I wanted to track so I added them. Originally it took me a while to get the logic between Facts and Trends laid out in my head because of the 1-many polymorphic, so version 1 of the Trends page only tracked OS/Model/Env because they were easiest. The goal of the "Check for Missing" button was to add these three by default (originally this was in my :after_save but it seemed a waste to run so often if it was only needed once).

**Comment by rbirnie** [comment]
New FactValues aren't getting added to the trends page. I tried adding an after_save to the FactValue model, but I guess Host creation skips validations so they aren't catching. Where should this go? 

Currently need to hit the "Check for Missing" button to get new factvalue's.

**Comment by ohadlevy** [comment]
@rbirnie just FYI, both @abenari and I are working on this, expect an update patch for review soon... thanks!

**Comment by rbirnie** [comment]
@abenari @ohadlevy : Take a look!

**Comment by ohadlevy** [comment]
merged - thanks!

**Pull request closed without merging**
