### PR TITLE
fixes #2562 for libvirt domain listen address

### PR DESCRIPTION
**Pull request by PrimusNZ**
Fixes the listen address set on creation of new domains.

This will restore proper connectivity with applications who connect to the vnc display address returned via libvirt API

### CODE REVIEW

**Comment by ohadlevy** [comment]
[test]

**Comment by lzap** [comment]
Hey, I tested behavior on both and it works the same. What platform/version are you experiencing an error?

**Comment by PrimusNZ** [comment]
This issue occurs when trying to connect to a host created by foreman via virt-manager.
My versions are as follows:

Hypervisor: CentOS 6.4, libvirt-0.10.2-18.el6_4.5.x86_64
Client: Fedora 19 (Did same behaviour on F18), virt-manager-0.10.0-0.4.gitb68faac8.fc19.noarch

virt-manager debug output from host created by foreman:
2013-05-21 19:38:40,273 (console:1138): Starting connect process for proto=vnc trans=ssh connhost=192.168.254.254 connuser=root connport=None gaddr=0 gport=5905 gsocket=None
2013-05-21 19:38:40,314 (console:413): VNC connection to 0:5905
2013-05-21 19:38:40,579 (console:1025): Viewer disconnected

After changing the address from '0' to '0.0.0.0':
2013-05-21 19:41:28,078 (console:1138): Starting connect process for proto=vnc trans=ssh connhost=192.168.254.254 connuser=root connport=None gaddr=0.0.0.0 gport=5905 gsocket=None
2013-05-21 19:41:28,093 (console:413): VNC connection to 192.168.254.254:5905
2013-05-21 19:41:28,636 (console:1053): Viewer connected

**Comment by ohadlevy** [comment]
do we have a redmine ticket for this one?

**Comment by lzap** [comment]
I was not creating one.

LZ

On Tue, May 21, 2013 at 04:45:19AM -0700, Ohad Levy wrote:

> do we have a redmine ticket for this one?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman/pull/626#issuecomment-18203587

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by PrimusNZ** [comment]
This has redmine ticket #2562

**Comment by domcleal** [comment]
@lzap were you testing with virt-manager too?  It's an interoperability issue I think, rather than not working if you always use Foreman.

I guess this will break for people who have VMs created via Foreman today with "0", right?

**Comment by ohadlevy** [comment]
I guess we can extend the logic to only update the connection if its not '0' or '0.0.0.0', this can ensure that we dont break older clients while still updating the default?

**Comment by PrimusNZ** [comment]
and make 0.0.0.0 the default for creating hosts.

OR (My preferred option), we move both sections (The create address and the update address) out of being hard coded and have a configurable address on the settings page (Set it to 0 by default for backwards compatibility)

**Comment by lzap** [comment]
I think we should have "libvirt" word in the setting name, maybe there are other consoles for other providers.

This works for me.

**Comment by PrimusNZ** [comment]
so something like libvirt_default_listen_address ?

**Comment by domcleal** [comment]
Thanks for the fixes @ProGEEK.

Should we just not remove the update_display, since it isn't possible to change on the fly?  Having the listen address set when the VM's created is still useful.

**Comment by PrimusNZ** [comment]
the update_display call updates the password also (As the web proxy sets a new password every time the page is loaded)

Will it work if we just remove the :listen parameter ?

**Comment by lzap** [comment]
This WFM

**Comment by domcleal** [comment]
I like the look of this, will test later.  [test]

**Comment by domcleal** [comment]
Works well for me.  Thanks for nailing this irritating bug @ProGEEK, it's much appreciated!

Squashed and merged as 710dfa8.

**Pull request closed without merging**
