### PR TITLE
fixes #5685 - add :path_ids to with_taxonomy_scope instead of with_taxonomy_scope_override for SmartProxy select dropdowns

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by domcleal** [comment]
Please file a new redmine ticket detailing the issue (I can't tell from the title), don't re-use the number of a bug that's already shipped.

**Comment by domcleal** [comment]
Or ask @stbenjam to include it in his PR.

**Comment by isratrade** [comment]
[test]

**Comment by isratrade** [comment]
@domcleal, ping. I think this is good to go.

**Comment by domcleal** [comment]
It hasn't been reviewed or tested yet.

**Comment by domcleal** [comment]
Merged as 58ea0de for Foreman 1.5.1, thanks @isratrade.

**Pull request closed without merging**
