### PR TITLE
Refs #26968 - don't disable Katellos MeantimeReporter

### PR DESCRIPTION
**Pull request by evgeni**
katello dropped the relevant code, relying on our implementation now

look @ezr-ondrej, I DIDN'T FORGET ;)

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
I think one of our Jenkins Nodes isn't properly cleaned up:
```
PG::ObjectInUse: ERROR:  database "test_develop_pr_katello-1-test" is being accessed by other users
DETAIL:  There are 21 other sessions using the database.
```

Going to trace that first before restarting the tests.

**Comment by ezr-ondrej** [comment]
[test katello]
sorry, I'll rekick them tho if you wanna safe some of these failures, I can poke you once it appears, they are quite regular

**Comment by ekohl** [comment]
I've seen them before when on a Jenkins node a job didn't really stop but Jenkins was no longer tracking them.

**Comment by ezr-ondrej** [comment]
[test katello]

**Pull request merged**
