### PR TITLE
Fixes #37184 - Report template generates incorrect kernel version

### PR DESCRIPTION
**Pull request by hao-yu**
Sort the kernel version facts of a host by updated date.

### CODE REVIEW

**Comment by adamruzicka** [comment]
Some of the test failures are related

**Comment by hao-yu** [comment]
ack. will fix them.

**Comment by adamruzicka** [comment]
[test katello]

**Review by adamruzicka — APPROVED** [review]
LGTM, the same test failures can be seen in other PRs

**Pull request merged**
