### PR TITLE
Fixes #28001 - remove Rainbow in templates render task

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by timogoebel** [comment]
I thought the gem was loaded as part of rails. Why don‘t we just add the gem?

**Comment by mmoll** [comment]
It was not part of my dev env and as this file seems to be the only one using rainbow I'd rather delete it, but leave it to the others to decide. If it's staying in, AFAICT it also needs a require line in this file.

**Comment by timogoebel** [comment]
The thing is, that the output of the rake task is quite unreadable without this. But I'd like to hear other's opinions.

**Comment by ekohl** [comment]
Perhaps a helper that colors it red and attempts to use Rainbow but falls back to plain strings? It looks like deface pulls it in if I look at our packaging repository.

**Comment by timogoebel** [comment]
> It looks like deface pulls it in if I look at our packaging repository.

Interesting. I guess it wouldn't hurt to add it to the console gem group and require it in this file, would it?

**Comment by mmoll** [comment]
alternate PR: GH-7095

**Comment by lzap** [comment]
I don't mind adding development gems if they are added properly. For production deployment, I'd be against pulling this (package maintenance). So +1 to add the dependency to the proper bundler group.

**Comment by mmoll** [comment]
I still think this PR here is the more correct one. However, I updated GH-7095 to add it to development only.

**Comment by lzap** [comment]
Honestly I don't understand why this rake task exists. We do have a test that compares snapshots, I've extended it recently to work with multiple OS names, families and versions but this rake task has a hardcoded host. On the other hand it has extensible folder to read templates from. I think this rake task should be dropped and we should move this feature into `snapshots.rake` as a different task reusing the code we already have.

**Comment by ekohl** [comment]
My understanding is that the goal of this task is to integrate it in CI on **other** projects. We can use this in community-templates to test every PR and make sure it renders correctly.

**Comment by lzap** [comment]
Well I understand the goal, but not the implementation. Since snapshot generator/test already laid ground for such thing, I don't understand why this rake task has its own context.

**Comment by timogoebel** [comment]
> Since snapshot generator/test already laid ground for such thing, I don't understand why this rake task has its own context.

The test implementation sucks, the rake task has the better design. We just never got around to switch the test cast to the rake task.

**Comment by tbrisker** [comment]
Closing this in favor of #7095. Feel free to open follow up prs refactoring or changing code, this issue is about broken dependency.

**Pull request closed without merging**
