### PR TITLE
fixes #23335 - normalize scsi attributes in rails 5

### PR DESCRIPTION
**Pull request by timogoebel**
This cherry-picks #5475 into `1.17-stable`.

### CODE REVIEW

**Comment by timogoebel** [comment]
This is another proof that we should not use 🐶.

**Comment by timogoebel** [comment]
Test failures and reports on Redmine suggest, that this does not work on 1.17. I'll investigate.

**Comment by mleklund** [comment]
I am willing to work with anyone to test code against a 1.17 install.  Anything you need.

**Comment by timogoebel** [comment]
@mleklund: If you could test the version I just pushed here, that would be a huge help. Please make sure to revert the old patch beforehand (`patch -R` reverses a patch, I believe).

**Comment by mleklund** [comment]
that appears to have fixed the vmware issue.  Looks like I have some param_true to clean up in my preseeds.

```
patch p1 -R < ~/vmware.patch
wget -O ~/vmware.patch2 https://github.com/theforeman/foreman/pull/5481/commits/49cf99a4bacd65e70de430845c6c1960b8c95553.patch
patch -p1 < /tmp/vmware.patch2
```

Then restart foreman, for anyone following along. 😀

**Comment by mmoll** [comment]
@timogoebel could you please rebase this onto a current 1.17-stable? It looks a bit like there are tests failures that should have gotten fixed in the meanwhile.

**Comment by timogoebel** [comment]
Rebased.

**Review by mmoll — APPROVED** [review]
Ruby 2.5 test errors irrelevant for 1.17-stable

**Comment by mmoll** [comment]
merged, danke @timogoebel!

**Pull request merged**
