### PR TITLE
Fixes #25365 - Disable Rails/RefuteMethods cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
While I find this easier to read, there might be some secrect conspiracy, seeing "refute" as Ruby-esque or Railsy... As always, vote :+1: and :-1: here.

**Comment by mmoll** [comment]
[test upgrade]

**Comment by mmoll** [comment]
[test katello]

**Comment by mmoll** [comment]
[test foreman]

**Comment by lzap** [comment]
There is a slight difference between the two, but I prefer the more expected "assert_not" because I learned this in JUnit years ago. It is less surprising basically. Tests are passing, so apparently we dont hit the semantic difference.

**Comment by mmoll** [comment]
Disabled that cop

**Comment by timogoebel** [comment]
@mmoll: Please rebase.

**Comment by mmoll** [comment]
rebased.

**Review by tbrisker — APPROVED** [review]
Thanks @mmoll !

**Pull request merged**
