### PR TITLE
fixes #29432 - add flatcar os support

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by TheKangaroo** [comment]
I added the new flatcar OS for our upcoming CoreOS to flatcar migration.
LGTM. Thank's for supporting flatcar 😍

**Comment by ekohl** [comment]
[test katello]

Out of interest, do you run facter on it and if so, what does it show for the osfamily?

**Comment by timogoebel** [comment]
> Out of interest, do you run facter on it and if so, what does it show for the osfamily?

Flatcar is similar to the original CoreOS and does not provide a package manager or the means to install software. You are supposed to run facter in a container, so I guess you would need to mount `/etc/os-release` into the container.

```
flatcar-update-01 ~ # cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2411.1.0
VERSION_ID=2411.1.0
BUILD_ID=2020-02-28-1535
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2411.1.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```

We don't run facter on CoreOS but have a custom tool called `blossom` (written in go) that can retrieve a certificate from PuppetCA and then send facts to Foreman via a small plugin that implements a custom fact parser. It's closed-source for the time being, though.

**Review by ekohl — APPROVED** [review]
Given the `ID_LIKE` I'm more confident that it should be a single class in Foreman. Thanks for that.

**Comment by TheKangaroo** [comment]
Yes, that's correct. We use a self-made go container to push facts to foreman which basically uses /etc/os-release information for the os facts.

**Pull request merged**
