### PR TITLE
Refs #20708 - reset default templates type

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
The linked issue caused issues on Rails 5. It turns out that we configure default `type` value to `Template` which causes problems. After removing it seems to work fine.

**Comment by mmoll** [comment]
fixes the problem for me 👍

**Review by mmoll — APPROVED** [review]

**Comment by iNecas** [comment]
[test foreman ] [test katello]

**Comment by iNecas** [comment]
[test foreman]

**Review by dLobatog — APPROVED** [review]
👍 if tests pass, what problems did it cause on Rails 5?

**Comment by mmoll** [comment]
@dLobatog see https://github.com/theforeman/foreman/pull/4778#issuecomment-328283576

**Comment by tbrisker** [comment]
If there are any with type `Template` shouldn't we change them as well? I'm not sure if there are, but since it was the default and now is invalid any existing ones should be updated.

**Comment by ares** [comment]
there should not be such templates, STI in rails 4 changes the type before save (or earlier) but rails 5 seems to have some additional check just during initialization

**Comment by iNecas** [comment]
I consider all questions as resolved now. Thanks @ares

**Pull request merged**
