### PR TITLE
Refs #24654 - pin factory_bot(_rails)

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
This is only a temporary bandaid to get green tests. This is IMHO more suitable for cherry-picking to the -stable branches. See GH-5963 for the real fix.

**Comment by mmoll** [comment]
[test upgrade]

**Comment by tbrisker** [comment]
I agree we should only pin this for stable branches, can you open it against them?

**Comment by mmoll** [comment]
opened.

**Pull request closed without merging**
