### PR TITLE
Fixes #23129 - Disable webpack source maps in production

### PR DESCRIPTION
**Pull request by ekohl**
Scratch build: http://koji.katello.org/koji/taskinfo?taskID=93561

### CODE REVIEW

**Review by xprazak2 — APPROVED** [review]
LGTM.

Test failures unrelated, [some](http://ci.theforeman.org/job/test_develop_pr_core/16947/database=postgresql,ruby=2.3,slave=fast/testReport/junit/(root)/OperatingsystemTest__families/test_0008_families_as_collection_contains_correct_names_and_values/) of them should be [fixed](https://github.com/theforeman/foreman/pull/5397/files) already.

@sharvit, any objections?

**Comment by tstrachota** [comment]
Looks good to me

**Comment by xprazak2** [comment]
Thanks everyone!

**Comment by ares** [comment]
Set the release in redmine issue to 1.18.0, please don't forget to set it after merging the PR. Thanks.

**Pull request merged**
