### PR TITLE
fixes #24469 - host_enc uses reduce

### PR DESCRIPTION
**Pull request by timogoebel**
Just a tiny, tiny refactoring.

### CODE REVIEW

**Review by ik5 — COMMENTED** [review]
I like the refactoring part, is there a test that can be use to see that nothing broke?

**Comment by timogoebel** [comment]
Yeah, we have a couple of test for this.
https://github.com/theforeman/foreman/blob/e74416f15c80b293c5c374708fb623982ed872d7/test/unit/foreman/renderer/scope/macros/host_template_test.rb#L11-L38

**Review by ik5 — APPROVED** [review]
lgtm, and the tests works

**Comment by timogoebel** [comment]
@ares: This could be another quick merge.

**Review by ares — APPROVED** [review]
Works still the same, which is great :-) Thanks @timogoebel, merging.

**Pull request merged**
