### PR TITLE
Fixes #8546 - Namespace interfaces and subnets to avoid a facts clash

### PR DESCRIPTION
**Pull request by GregSutcliffe**

### CODE REVIEW

**Comment by mmoll** [comment]
besides the obvious test problem... tested, works for me :+1:

**Comment by ohadlevy** [comment]
a simple test can be to query to all facter hash keys and make sure non of
these keys exists in the enc output.

**Comment by GregSutcliffe** [comment]
@ohadlevy which version of facter? And what about custom facts?

**Comment by dLobatog** [comment]
Merged as d3b7f426959b7195ceedac1b9e719bfd1563af02, thanks @GregSutcliffe!

**Pull request closed without merging**
