### PR TITLE
Fixes #25230 - Remove useless html from toast notifications

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by ohadlevy — DISMISSED** [review]

**Comment by ohadlevy** [comment]
@tbrisker please note the linting errors.

**Comment by tbrisker** [comment]
Fixed, too bad i had to skip 3000 lines of travis output to see it failed on linting and then try to figure out where in the code it is...

**Comment by ohadlevy** [comment]
yep... this is the impact of disabling hound... in theory we could think of
setting up travis  build matrix,
https://docs.travis-ci.com/user/build-matrix/

**Review by ohadlevy — APPROVED** [review]

**Comment by tbrisker** [comment]
cherry-picked to 1.20-stable as f555b8f8f

**Pull request merged**
