### PR TITLE
Refs #25053 - Remove unused fact_names_by_id hash

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Approved, you were faster than me. I suggest to hold on with this after 1.20 because of plugins? I *believe* no one is using it tho.

**Comment by lzap** [comment]
I searched all my drive and I don't see any plugin that uses it so I think it does not exist :-) I think we can safely merge.

**Comment by tbrisker** [comment]
@lzap These are all private methods, I don't see any reason not to merge :)

**Comment by lzap** [comment]
Oh of course. Merged, thanks.

**Pull request merged**
