### PR TITLE
Fixes #32741 - Allow merge for yaml/json variables

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Looks like the Katello test failures are not related to this change.

**Comment by sbernhard** [comment]
[test katello]

**Comment by sbernhard** [comment]
[test katello]

**Comment by sbernhard** [comment]
Tests are green @ezr-ondrej :-)

**Review by ezr-ondrej — APPROVED** [review]
I'm not happy about the tests, that I've completely rewritten in another PR, so I'll need to rewrite yours as well, but that's my issue xD

Thanks @sbernhard ! Make sense and works.

**Pull request merged**
