### PR TITLE
fixes #26021 - update react to 16.8

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ohadlevy** [comment]
packaging PR at https://github.com/theforeman/foreman-packaging/pull/3443

**Comment by ohadlevy** [comment]
/cc @amirfefer 
@ekohl ack?

**Review by amirfefer — COMMENTED** [review]
Awesome ! React hooks looks promising :)
I tested it and it seems to work well.
React strongly suggests adding `eslint-plugin-react-hooks` lint rule, can we add it to our specific eslint config?

**Comment by ohadlevy** [comment]
not sure, but I would suggest to do it in a follow up PR? :-)

**Comment by ohadlevy** [comment]
@amirfefer ack?

**Comment by Ron-Lavi** [comment]
Great !!!
need this upgrade also for [Patternfly-TypeAhead-Upgrade](https://github.com/patternfly/patternfly-react/pull/1367)

**Review by amirfefer — APPROVED** [review]

**Review by Ron-Lavi — APPROVED** [review]
Seems to work smoothly :+1:

**Review by ekohl — APPROVED** [review]

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
