### PR TITLE
Fixes #7592 - flipped the order of logged-in user menu

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by lzap** [comment]
Works as expected, can you add the separator (divider) as well @shlomizadok please?

**Comment by shlomizadok** [comment]
@lzap - Added. Thanks.

**Comment by lzap** [comment]
Retesting...

**Comment by lzap** [comment]
Works as expected, looks good, merging. Thanks!

Merged as efe9748

**Pull request merged**
