### PR TITLE
Fixes #37499 - clean up unmanaged repositories during host registration

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
What are your thoughts about this PR @nofaralfasi  / @ares? / @stejskalleos Is this something interesting? 

If this is something we want, I would suggest to add a GUI to enable/disable cleaning the not managed repositories. 

The clean_unmanaged_repositories snippet could be used during usual host provisioning, too.

**Review by stejskalleos — COMMENTED** [review]
We already have something in the core: https://github.com/theforeman/foreman/commit/f884babadf8c78495442a54028333aefec123be1

**Comment by sbernhard** [comment]
> We already have something in the core: [f884bab](https://github.com/theforeman/foreman/commit/f884babadf8c78495442a54028333aefec123be1)

The mentioned PR is about removing the repositories which were added during provisioning. 

This PR is about removing all repositories which are configured on a host and are not managed by subscription manager. If a host is configured to consume the repositories from foreman/katello and therefore has a subscription-manager registration, we expect to have all repositories maintained by foreman/katello. There should not be any other repository besides the repositories from sub-man.

**Review by ekohl — CHANGES_REQUESTED** [review]
Conceptually I think we shouldn't do this.

Registration should just be that: get the host into a manageable situation. We always applied the same to provisioning. Once a host is manageable, then you can use configuration management (Ansible, Puppet, ...) to get it into the right shape.

Perhaps something like this is better suited for https://github.com/theforeman/foreman-operations-collection. Then use REX (with foreman_ansible) to apply that.

**Pull request closed without merging**
