### PR TITLE
Fix #3116 NIC type selection for vSphere

### PR DESCRIPTION
**Pull request by mmatuska**
Provide solution issue [#3116](http://projects.theforeman.org/issues/3116)
Add NIC selection for vSphere and two initial types: E1000 and VMXNET 3

For the future the selection can be optimized to vSphere allowed network interface types, but it is quite complicated to query the API for this result (and not supported by fog at all).

Reviewed by: Dominic Cleal

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks for the patch @mmatuska, merged as c75be21b for Foreman 1.4.

**Comment by ohadlevy** [comment]
does this fully replace #480 ?

**Comment by domcleal** [comment]
@ohadlevy mostly, just not the hardware profile stuff?  I think we're probably best off closing it now.

**Pull request closed without merging**
