### PR TITLE
Fixes #32457 - Register host & apply inherited attributes

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by ares — APPROVED** [review]
Thanks @stejskalleos, works great, merging!

**Comment by ares** [comment]
This deserves 2.5 cherrypick I believe

**Comment by tbrisker** [comment]
2.5 - 230333714

**Comment by LiohMoeller** [comment]
This issue is still present on Foreman 3.5.1.

Steps to reproduce:
- Create a Host Group
- Select 'Puppet Proxy', 'Puppet CA' and 'Environment' from the relevant Pull-Down-Menus on the Host Group
- Create a Global Registration Template associated with the newly created Host Group
- Register a client using the Global Registration template

The client is registered, but Puppet Parameters from the Host Group are not adopted, leading to empty ‘Environment’ ‘Puppet Proxy’ and ‘Puppet CA Proxy’ on the host object and a puppet.conf on the client which looks like this:
<pre><code class="text">
[main]

[agent]
pluginsync      = true
report          = true
certname        = my.host.tld
</code></pre>

The issue does not occur if the host object already exists and Puppet settings are defined on the host object.

A partial workaround, still leading to a non-functional result, is to define puppet_ca_server and puppet_server as Parameters on the hostgroup. In this case server and ca are written correctly, but environment not. Trying to set the host_puppet_environment  parameter manually on the host group, still leads to the same result (variable empty)

**Pull request merged**
