### PR TITLE
Using __ instead of _ to avoid conflict with underscore.js, fixes #3984.

### PR DESCRIPTION
**Pull request by waldenraines**
window._ was defined as a custom i18n function which prevents the use
of underscore.js.  This commit changes the use of _ to __ in js files
to be consistent with gettext_i18n_rails_js and to allow the use
of underscore.js.

### CODE REVIEW

**Comment by domcleal** [comment]
From my testing (and aside from [bug #3988](http://projects.theforeman.org/issues/3988) which you can avoid with a git revert of 9ef39dd6a) `rake locale:find` doesn't find changes to strings in JavaScript now.  I think you need to remove the change to js_gettext_function in lib/tasks/locale.rake so it defaults back to `__`.

**Comment by waldenraines** [comment]
@domcleal fixed, thanks.

**Comment by domcleal** [comment]
Thanks @waldenraines, merged as ad01d4d20f for Foreman 1.4.

Would you mind updating the JavaScript bits in http://projects.theforeman.org/projects/foreman/wiki/Translating please?  Cheers.

**Comment by waldenraines** [comment]
@domcleal done.

**Comment by domcleal** [comment]
@waldenraines thanks, though it was just the JavaScript examples that would change to `__`, the Ruby ones still use `_`

**Comment by waldenraines** [comment]
Oops, too aggressive of a find/replace.  Updated.

**Pull request closed without merging**
