### PR TITLE
Fixes #21766 - Enforce uniquness of TaxableTaxonomy in DB

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ares** [comment]
[test foreman] - failures seemed as jenkins issue, for katello it fails on migration having `[5.0]`, the same for upgrades 

```
Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x000000008a9378>
/usr/local/rvm/gems/ruby-2.2.5@test_develop_pr_upgrade-2/gems/activerecord-4.2.9/lib/active_record/migration.rb:664:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.5@test_develop_pr_upgrade-2/gems/activerecord-4.2.9/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.5@test_develop_pr_upgrade-2/gems/activerecord-4.2.9/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.5@test_develop_pr_upgrade-2/gems/activerecord-4.2.9/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/rvm/gems/ruby-2.2.5@test_develop_pr_upgrade-2/gems/activerecord-4.2.9/lib/active_record/migration.rb:416:in `method_missing'
/var/lib/workspace/workspace/test_develop_pr_upgrade/database/postgresql/old_branch/1.14-stable/ruby/2.2/db/migrate/20171126131104_remove_duplicate_taxable_taxonomies.rb:1:in 
```

**Comment by tbrisker** [comment]
Thanks, pushed again without versioned migration.

**Review by dLobatog — CHANGES_REQUESTED** [review]
@tbrisker Apparently the deletion of duplicate `TaxableTaxonomy` generates a query that is invalid in MySQL

**Comment by tbrisker** [comment]
@dLobatog thanks, pushed with a less-performant version that will hopefully work on mysql as well.

**Comment by ares** [comment]
LGTM, anything else @dLobatog or good to merge?

**Review by dLobatog — APPROVED** [review]

**Pull request merged**
