### PR TITLE
fixes #2986 - remove #show method from controllers and routes.rb when not used

### PR DESCRIPTION
**Pull request by isratrade**
Merge for 1.4.  This breaks api deprecation message for several show actions is it causes ActionController::RoutingError

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Merged as 32f72fd, thanks @isratrade!

**Comment by isratrade** [comment]
@domcleal, are you sure you wanted to merge this even though it breaks the api deprecation message as it causes ActionController::RoutingError

**Comment by domcleal** [comment]
@isratrade it won't go into 1.3 as we've already branched.  I think we can take another PR now to remove the deprecation notice too for 1.4.

**Comment by isratrade** [comment]
Great.  I agree.  I'll submit an issue to remove deprecation notice.

**Comment by isratrade** [comment]
@domcleal, on a second look, I'll keep the deprecation notice in application_controller.  It is still relevant for #index calls, just not #show calls.

**Pull request closed without merging**
