### PR TITLE
Fixes #36023: Add missing VMWare GuestOS mappings

### PR DESCRIPTION
**Pull request by Areyus**
This brings Foreman's GuestOSIdentifier mapping up to date with rbvmomi2 3.7 and VSphere 8.0U2

### CODE REVIEW

**Comment by Areyus** [comment]
I was not able to test this directly myself, since I am currently missing the required infrastructure. but I confirmed all used identifiers match with the current rbvmomi2 release and all known values from rbvmomi2 are also present in Foreman.
Judging from past PRs in the area, this should be enough.

**Comment by ekohl** [comment]
ok to test

**Review by ekohl — APPROVED** [review]
I think this looks good and I can verify we now have descriptions for everything.

We can get the missing items with `rake console` and print `RbVmomi::VIM::VirtualMachineGuestOsIdentifier.values - Foreman::Model::Vmware.new.guest_types_descriptions.keys`.

On `develop`:
```
["windows11_64Guest",
 "windows12_64Guest",
 "windows2019srv_64Guest",
 "windows2019srvNext_64Guest",
 "windows2022srvNext_64Guest",
 "freebsd13Guest",
 "freebsd13_64Guest",
 "freebsd14Guest",
 "freebsd14_64Guest",
 "oracleLinux9_64Guest",
 "sles16_64Guest",
 "debian11Guest",
 "debian11_64Guest",
 "debian12Guest",
 "debian12_64Guest",
 "asianux9_64Guest",
 "other5xLinuxGuest",
 "other6xLinuxGuest",
 "other5xLinux64Guest",
 "other6xLinux64Guest",
 "darwin19_64Guest",
 "darwin20_64Guest",
 "darwin21_64Guest",
 "darwin22_64Guest",
 "darwin23_64Guest",
 "vmkernel7Guest",
 "vmkernel8Guest",
 "amazonlinux2_64Guest",
 "amazonlinux3_64Guest",
 "crxPod1Guest",
 "rockylinux_64Guest",
 "almalinux_64Guest"]
```

On this branch:
```
[]
```

And all descriptions match the docs.

**Comment by ekohl** [comment]
Tests are still running now, but otherwise :+1: to merging.

**Pull request merged**
