### PR TITLE
fixes #2281 - don't allow admin flag to be removed from admin account

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Doesn't work for me. I did this:

1) Added a new admin to edit the "admin" account from
2) Edited "admin"
3) Unchecked the admin box
4) Saved -> this worked

A little debug seems to show admin_changed? is always coming back 'false' on my box, and I'm not sure if it's just me.

**Comment by skottler** [comment]
[test]

**Comment by ohadlevy** [comment]
@GregSutcliffe @domcleal should i merge this?

**Comment by domcleal** [comment]
No, Greg's right - it's broken!  I think how the controller handles admin flags is affecting it.. possibly.  Closing until I can rework it.

**Pull request closed without merging**
