### PR TITLE
Fixes #35978 - Search should have a name attribute

### PR DESCRIPTION
**Pull request by MariaAga**
Blocked by https://github.com/theforeman/foreman-js/pull/450

### CODE REVIEW

**Comment by MariaAga** [comment]
@ofedoren Can you take a look?
Katello test fixes are here: https://github.com/Katello/katello/pull/10439

**Review by ofedoren — APPROVED** [review]
Thanks, @MariaAga, looks safe to me, also big :cookie: for Katello fixes.

ACK from me, but shouldn't we also ask @theforeman/packaging ?

**Comment by evgeni** [comment]
*technically* not, as it's not a *new* dep (but codeowners might still enforce that).
But it'd cool if we could have a packaging PR prepared for bumping builder and vendor?

**Comment by ekohl** [comment]
Technically we're pretty much at the end of stabilization week and this can break a bunch of plugins. However, I'd be OK with proceeding with this and postponing branching by a week if needed

**Comment by MariaAga** [comment]
This is needed so users can submit new/edit Job Templates in REX, and use the old job invocation form as without the name attribute the pages dont save. it has been broken since moving to the new pf4 search.

**Comment by MariaAga** [comment]
@evgeni https://github.com/theforeman/foreman-packaging/pull/9024

**Comment by evgeni** [comment]
The packaging PR looks fine. @ekohl shall we merge this and the packaging one today, and see how things go?
I have no powers in katello, so that'll be broken for a moment, but given a PR exists shouldn't be too long?

**Review by ekohl — APPROVED** [review]
I'd say we either merge this today or we're too late. Given that we should update anyway, let's pull the trigger and fix any issues we find.

I would appreciate it if all plugins were updated as well, but that can happen even after we branch Foreman.

**Pull request merged**
