### PR TITLE
Refs #3860 - add Kernel.rand to safemode functions

### PR DESCRIPTION
**Pull request by lzap**
This is handy function that is needed for auto-provisioning of discovered
hosts: https://github.com/theforeman/foreman_discovery/pull/98

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
It might make sense to attempt to allow plugins to add their own methods to the Safemode Jail. I've no idea if this is possible though - I might take a look :)

**Comment by domcleal** [comment]
http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Extend-safemode-access ?

**Comment by ohadlevy** [comment]
API is better, if needed, you can do something like
https://github.com/Katello/katello/blob/master/app/models/katello/concerns/host_managed_extensions.rb#L58
too.

**Comment by dLobatog** [comment]
@lzap I've set this as waiting for contributor since it looks like discovery could add it on its own. I don't see any cons for adding this to the jail though, but if only discovery requires it maybe it's best to do it there for the moment?

**Comment by GregSutcliffe** [comment]
@domcleal that'll teach me to search!

@eLobato @lzap +1 for doing it in discovery, it's a really minor thing.

**Comment by lzap** [comment]
Yeah I guess the random is only for discovery. Closing now, adding it there.

**Pull request closed without merging**
