### PR TITLE
Fixes #28468 - Misspelling on login page

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Note the card title misspelling.

Before:
screencapture-localhost-5000-users-login-1575973025581

After:
screencapture-localhost-5000-users-login-1575972962424

Needs ack from @rohoover

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Good catch @laviro! WFJ :)

**Comment by tbrisker** [comment]
[test foreman]

**Review by waldenraines — APPROVED** [review]
LGTM.

**Review by ohadlevy — APPROVED** [review]

**Comment by Rohoover** [comment]
LGTM... it matches the button - that's awesome.

**Comment by Ron-Lavi** [comment]
Thanks everyone !
Can we cherry pick this to 1.23?

**Comment by tbrisker** [comment]
Afraid not easily. This is a translated string, meaning the cherry-picking it will break all translations of it

**Comment by tbrisker** [comment]
@laviro looks like you are in luck and this string hasn't been translated yet. You can open a cherry-pick PR against the stable branches but please also change all occurrences of the string in the `locale/` and `application/assets/javascript/locale/` folders just to make sure it's consistent

**Comment by Ron-Lavi** [comment]
opened cp PR in https://github.com/theforeman/foreman/pull/7244

**Pull request merged**
