### PR TITLE
Fixes #12341 - Added divs to make changes in alerts easier

### PR DESCRIPTION
**Pull request by alongoldboim**

### CODE REVIEW

**Comment by dLobatog** [comment]
@alongoldboim Thanks! This is changing significantly on Patternfly (https://github.com/theforeman/foreman/pull/2137/files#diff-d07b3cdd6c00768e06bfed349d3c808fR428) , perhaps you want to wait until then to make this refactor or is there anything that requires it right now?

**Comment by alongoldboim** [comment]
I kinda need it sooner, I don't see a real reason for waiting :).

**Comment by dLobatog** [comment]
@alongoldboim What are you trying to do with these divs exactly? It's basically the same as not having them as you can match deface with `alert-xxxx` already, the helper creates a div with these classes. 

Do you want to wrap alerts in something? You can use `closing_selector` on deface for that, or [`surround`](https://github.com/spree/deface#examples).

**Comment by dLobatog** [comment]
@alongoldboim An example that I've tested:

``` ruby
Deface::Override.new(
  :virtual_path => 'templates/_form',
  :name => 'replace-alerts',
  :replace => 'erb[loud]:contains("alert-success")',
  :text => "<h1>hi there</h1>")
```

**Comment by alongoldboim** [comment]
@dLobatog ill try it :), thanks.

**Comment by alongoldboim** [comment]
@dLobatog Works like a charm :+1:,
We can wait for Patternfly.

**Comment by dLobatog** [comment]
Alright, closing this for the moment then, thanks @alongoldboim !

**Pull request closed without merging**
