### PR TITLE
Fixes #20952 - Replace AC::Parameters Hash methods

### PR DESCRIPTION
**Pull request by mmoll**
Replaces any methods that used to be from Hash with the more limited
ActionController::Parameters API.

### CODE REVIEW

**Comment by mmoll** [comment]
taken from Dominic's rails51 branch

**Comment by mmoll** [comment]
[test foreman]

**Comment by mmoll** [comment]
Seems to be incompatible with Rails 4.2. Unless somebody has a quick idea how to fix, I'd just leave this open for now.

**Comment by mmoll** [comment]
While I guess this topic will need to be revisited for Rails 5.1, this is 100% green for 4.2 and 5.0 now and allows to remove the deprecaction whitelisting.

**Comment by iNecas** [comment]
Makes sense. Thanks @mmoll

**Pull request merged**
