### PR TITLE
fixes #4599 - DNS and DHCP records for BMC and managed interfaces not using FQDN

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Strange, just the one failure on sqlite3 + Ruby 1.8.7:

http://ci.theforeman.org/job/test_develop_pr_core/906/database=sqlite3,puppet=3.0,ruby=1.8.7/testReport/%28root%29/Api__V2__InterfacesControllerTest/test_0005_update_a_host_interface/

**Comment by treydock** [comment]
@domcleal I know why.  I added another record to the nics fixture, and assigned it to the same host so the failing test was using the wrong fixture.  I've amended my commit to reuse the existing fixture.

**Comment by stbenjam** [comment]
[test]

**Comment by domcleal** [comment]
@witlessbird or @lzap, would you mind reviewing please?

**Comment by dmitri-d** [comment]
lgtm. @domcleal: I see there are lots of conditional tests in test/unit/orchestration/dhcp_test.rb and test/unit/orchestration/dns.rb, which isn't great as the tests will pass when SETTINGS[:unattended] is set to false. I'll add a ticket about that if there are no objections?

**Comment by domcleal** [comment]
Sure, thanks.  It'd be better to skip/pending.  To be honest, the test suite will fail in all kinds of wonderful ways when unattended=false.

**Comment by domcleal** [comment]
Thanks @treydock!  Merged as 21e07e9 for Foreman 1.5.0.

**Pull request closed without merging**
