### PR TITLE
Fixes #16562 - Enable JS testing on CI

### PR DESCRIPTION
**Pull request by dLobatog**
This enables JS testing on every PR. 
I've enabled it on my local repo to test it: https://travis-ci.org/dLobatog/foreman/builds/159996940
https://github.com/dLobatog/foreman/pull/28

cc @gailsteiger @ohadlevy @tbrisker

### CODE REVIEW

**Comment by timogoebel** [comment]
Do we really want to test this on travis? I am under the impression, that they are incredibly slow to queue tests.

**Comment by ohadlevy** [comment]
Also.. do we want to run the tests conditionally? I would assume that are
way more non JS commits (for now), so the tests can be skipped? (see
https://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps
)

**Comment by dLobatog** [comment]
@timogoebel Any other suggestions? I don't want to add more load and 'npm installs' to our Jenkins when there's no reason to. 

@ohadlevy I guess I could do something like `if $( git diff --name-only HEAD~1..HEAD webpack/ ) then; npm run test;` I'll try it in my repo first

**Comment by dLobatog** [comment]
Updated so that it only runs when the last commit contains changes in 'webpack/'

**Comment by timogoebel** [comment]
> Any other suggestions? I don't want to add more load and 'npm installs' to our Jenkins when there's no reason to.

@dLobatog : I think, there is a good reason to use the jenkins farm. Travis being slow. But to be honest, I don't have strong feelings for this matter. We can try travis and if it doesn't work, try something else.

**Comment by dLobatog** [comment]
@timogoebel We can always change from one to the other. I personally prefer Jenkins too as it's more configurable, but our infra is quite loaded already. I doubt it'll be much faster, it took 2m 50s to run it on 3 different versions of node (https://travis-ci.org/dLobatog/foreman/jobs/159996945) - I'll remove 0.10 as it isn't really relevant.

**Comment by ohadlevy** [comment]
merged as 0d8ad89 thanks @dLobatog !

**Pull request closed without merging**
