### PR TITLE
Fixes #17587 - remove autoprefixer gem

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
TBH I'm not certain that we really need this gem at all.

**Comment by dLobatog** [comment]
Feel free to remove it - it was a dependency of bootstrap-sass that we needed to pin so that Foreman w/ Patternfly worked in Ruby 1.9.3. We don't care about that ruby now so...

**Comment by tbrisker** [comment]
test failure unrelated

**Comment by dLobatog** [comment]
Thanks @tbrisker !

**Pull request merged**
