### PR TITLE
[cp] Fixes #23690 - update react to 16.3

### PR DESCRIPTION
**Pull request by amirfefer**
(Cherry picked from commit [c50b2](https://github.com/theforeman/foreman/commit/c50b21ee733acaccf1cd82fa3caf7c4b5bfea757) and commit [2e418](https://github.com/theforeman/foreman/commit/2e41835d428e63bba9f98d520888e5fadcfe8598))

### CODE REVIEW

**Comment by xprazak2** [comment]
@amirfefer, according to the issue description, version 16.3 is needed to use `getDerivedStateFromProps`, but 1.18 is not using it at the moment. Is this something katello needs? cc @jturel

There is no need to squash commits for cherry-picks. I would prefer to have a separate commit for each to keep better track of things.

**Comment by waldenraines** [comment]
> @amirfefer, according to the issue description, version 16.3 is needed to use getDerivedStateFromProps, but 1.18 is not using it at the moment. Is this something katello needs? cc @jturel

Yes, we need this for katello.

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
> [test katello]

No thoughts on the test failures, seem completely unrelated.

**Comment by amirfefer** [comment]
@xprazak2 - I removed squash

**Comment by xprazak2** [comment]
Merging, thanks!

It would make me very happy if in the future we could avoid packaging changes when the RC1 is already out.

**Pull request merged**
