### PR TITLE
fixes #18200 - don't re-encrypt settings when value is unchanged

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
Looks good, but can you add a test for a case when value is not decryptable? You handle this correctly in the code, but I cannot find coverage for this case, it's important one. If setting is corrupted somehow, we need to be able to overwrite it with the new value (e.g. when algorithm is changed).

**Comment by domcleal** [comment]
Test added to check an unencrypted database value (the point of `is_decryptable?`) is then encrypted when setting the new value.

**Comment by lzap** [comment]
I think I did not understand semantics of `is_decryptable?` but that does not change a thing, you made it correctly. Thanks, waiting for tests.

**Review by lzap — APPROVED** [review]
RTM

**Comment by lzap** [comment]
Unrelated failures, thanks @domcleal !

**Pull request merged**
