### PR TITLE
Fixes #7778 - allow + in user login

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by iNecas — APPROVED** [review]
Any other character to add or you prefer one char per PR? :)

**Comment by dLobatog** [comment]
Interesting to see that Katello tests passed now 😕

**Comment by ares** [comment]
@inecas I saw the request for ˋ+ˋ one day after you merged the previous one. And the previous one just after ˋ$ˋ was merged :-) since I already knew how to do it, I thought it would be good to just send a PR. I hope there's no more special chars required, otherwise I'll prepare another caro for you :-)

**Comment by iNecas** [comment]
I thought it wasn't on purpose :)

**Pull request merged**
