### PR TITLE
fixes #2458 - Directory structure precreated

### PR DESCRIPTION
**Pull request by ares**
see http://projects.theforeman.org/issues/2458

### CODE REVIEW

**Comment by domcleal** [comment]
Sounds like an error in the install procedure where Foreman is being run as root, not under the foreman user.  Could there be a rake task or similar being run?  It's important to fix that as another side effect is root-owned files under tmp/, which will cause errors later.

**Comment by ares** [comment]
I'll go through log from katello-configure and try to figure out what exactly created it.

**Comment by ares** [comment]
Original permission problem fixed in katello-installer (see https://github.com/Katello/katello-installer/pull/4 for more details). Having empty directories on server may cause a bit of confusion however since we already have parent directory there because of SELinux I think adding these would be ok.

**Comment by ohadlevy** [comment]
@domcleal any opinion here?

**Comment by domcleal** [comment]
I'm indifferent about adding them.  My only slight concern is if we started relying on them being there and they change, but that's minor.

**Comment by GregSutcliffe** [comment]
Do they _have_ to be top-level directories? I have to add those manually in the debian packages (locales caught me out that way) ...

**Comment by domcleal** [comment]
@GregSutcliffe they're all under db/openid-store, not top-level.  I think that's just GitHub displaying them in a strange way, see https://github.com/ares/foreman/tree/fix/2458-storage_permissions/db/openid-store.

**Comment by GregSutcliffe** [comment]
Ah ok, yeah I misread the diff. Naughty Github :)

No issues on deb packaging then ;)

**Comment by ohadlevy** [comment]
merged - thanks

**Pull request closed without merging**
