### PR TITLE
Fixes #17580 - React Chart Component has unsafe function

### PR DESCRIPTION
**Pull request by gailsteiger**
make hasData function more robust

### CODE REVIEW

**Comment by domcleal** [comment]
I don't know why you have attributed this commit (a8c9f1e) to me, I think you're mistaken.

**Comment by mmoll** [comment]
it seems 78e86121 got squahed into this?

**Comment by gailsteiger** [comment]
@tbrisker @dLobatog could you please review

**Comment by ohadlevy** [comment]
does it require any additional tests?

**Comment by gailsteiger** [comment]
@ohadlevy I don't think it needs another test. It's a very edge case. but I made the change because I generally use the more robust coding convention.

It's not something I ever test, just programming defensively.

**Comment by dLobatog** [comment]
Thanks @gailsteiger !

**Pull request merged**
